trigger:
- Development

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
  
- script: 
- task: SqlAzureDacpacDeployment@1
  inputs:
    AuthenticationType: 'server'
    ServerName: 'azrvaultdatasit001.database.windows.net'
    DatabaseName: 'vault_edw'
    SqlUsername: 'svc_airflow'
    SqlPassword: 'V@ult22$'
    deployType: 'SqlTask'
    SqlFile: 'prueba.sql'
    IpDetectionMethod: 'AutoDetect'
  