trigger:
- Development

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
  
- script: 
- task: SqlAzureDacpacDeployment@1
  inputs:
    azureConnectionType: 'ConnectedServiceName'
    AuthenticationType: 'servicePrincipal'
    ServerName: 'azrvaultdatasit001.database.windows.net'
    DatabaseName: 'vault_edw'
    deployType: 'SqlTask'
    SqlFile: 'prueba.sql'
    IpDetectionMethod: 'AutoDetect'
  