[DEFAULT]
# Paths
files_directory = /Files
archive_directory = /Files/Archive
processed_directory = /Files/Processed
source_directory = /Files/Source
xlsx_directory = /Files/xlsx
log_directory = /Logs

# Server
server = azrvaultdatauat001.database.windows.net
database = vault_edw
table_name = nfp_policy
schema = edw_stage
chunksize = 5000
# 'azure_function' or 'sql_server_credentials'
auth_method = sql_server_credentials
# Only used if auth_method is 'sql_server_credentials'
username = 
password = 

# Column data
validate_column_empty = True
column_to_validate = Reporting Month
column_mapping_file = /Files/json/column_mapping.json

# Logs
# Options: all, error, none
show_records = error
