UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Additional Replacement Cost Coverage' , IVANS_coverage_cd = 'ARCC' where internal_coverage_cd = 'Additional Replacement' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Additional Replacement Cost Coverage' , IVANS_coverage_cd = 'ARCC' where internal_coverage_cd = 'Additional Replacement Cost Coverage' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Additional Replacement Cost Coverage \& Wildfire Replacement Cost Coverage' , IVANS_coverage_cd = 'ARWFR' where internal_coverage_cd = 'Additional Replacement Wildfire' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'All Other Perils' , IVANS_coverage_cd = 'PERIL' where internal_coverage_cd = 'AOP' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Taxes' , IVANS_coverage_cd = 'TCF' where internal_coverage_cd ='Broker''s Premium Tax' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Collections' , IVANS_coverage_cd = 'COLCT' where internal_coverage_cd = 'Bank Vaulted Jewelry (Scheduled)' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Collections' , IVANS_coverage_cd = 'COLCT' where internal_coverage_cd = 'Collectibles' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Collections' , IVANS_coverage_cd = 'COLCT' where internal_coverage_cd = 'Collectibles (Blanket)' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Collections' , IVANS_coverage_cd = 'COLCT' where internal_coverage_cd = 'Collectibles (Scheduled)' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Collections' , IVANS_coverage_cd = 'COLCT' where internal_coverage_cd = 'Coins' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Collections' , IVANS_coverage_cd = 'COLCT' where internal_coverage_cd = 'Coins (Blanket)' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Collections' , IVANS_coverage_cd = 'COLCT' where internal_coverage_cd = 'Coins (Scheduled)' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Surcharge' , IVANS_coverage_cd = 'STS' where internal_coverage_cd = 'Colorado Hazard Mitigation Fund' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Contents Extended Replacement Cost' , IVANS_coverage_cd = 'CERC' where internal_coverage_cd = 'Contents Extended' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Contents off Premises Loss Exclusion' , IVANS_coverage_cd = 'XCPL' where internal_coverage_cd = 'Contents Off Premises Loss Exclusion' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Fee' , IVANS_coverage_cd = 'POLFE' where internal_coverage_cd = 'Correction' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Cyber Coverage' , IVANS_coverage_cd = 'CLIAB' where internal_coverage_cd = 'Cyber (HSB)' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Cyber Coverage' , IVANS_coverage_cd = 'CLIAB' where internal_coverage_cd = 'Cyber' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Cyber Liability Coverage' , IVANS_coverage_cd = 'CLIAB' where internal_coverage_cd = 'Cyber Liability' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Home Cyber Protection Coverage' , IVANS_coverage_cd = 'CLIAB' where internal_coverage_cd = 'Cyber Protection' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Deductible Waiver for Large Losses' , IVANS_coverage_cd = 'WDEDC' where internal_coverage_cd = 'Deductible Waiver for Large Losses' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Deletion of Cosmetic Damage Exclusion' , IVANS_coverage_cd = 'XECOD' where internal_coverage_cd = 'Deletion Cosmetic Damage Exclusion' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Dwelling Reconstruction Cost Coverage' , IVANS_coverage_cd = 'RCD' where internal_coverage_cd = 'Dwelling Reconstruction Cost' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Earthquake Coverage Extension' , IVANS_coverage_cd = 'EQKEX' where internal_coverage_cd = 'Earthquake Coverage Extended' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Earthquake Coverage Extension for Loss Assessment' , IVANS_coverage_cd = 'EQKLA' where internal_coverage_cd = 'Earthquake Coverage Extended for Loss Assessment' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Surcharge' , IVANS_coverage_cd = 'STS' where internal_coverage_cd = 'EMPA Surcharge' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Surcharge' , IVANS_coverage_cd = 'STS' where internal_coverage_cd = 'EMPATF Surcharge' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Extended Replacement Cost Coverage' , IVANS_coverage_cd = 'EXRCC' where internal_coverage_cd = 'Extended Replacement Cost Coverage' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Fee' , IVANS_coverage_cd = 'POLFE' where internal_coverage_cd = 'FIGA Assessment' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Collections' , IVANS_coverage_cd = 'COLCT' where internal_coverage_cd = 'Fine Arts' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Collections' , IVANS_coverage_cd = 'COLCT' where internal_coverage_cd = 'Fine Arts (Blanket)' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Collections' , IVANS_coverage_cd = 'COLCT' where internal_coverage_cd = 'Fine Arts (Scheduled)' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Taxes' , IVANS_coverage_cd = 'TCF' where internal_coverage_cd = 'Fire Marshal Tax' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Fee' , IVANS_coverage_cd = 'POLFE' where internal_coverage_cd = 'FSLSO Fee' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Ensuing Fungi Increase' , IVANS_coverage_cd = 'MOLD' where internal_coverage_cd = 'Fungi Bacteria' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Fungi Liability Extension' , IVANS_coverage_cd = 'MODEX' where internal_coverage_cd = 'Fungi Liability Extension' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Guaranteed Replacement Cost Coverage' , IVANS_coverage_cd = 'GUARP' where internal_coverage_cd = 'Guaranteed Replacement Cost' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Collections' , IVANS_coverage_cd = 'COLCT' where internal_coverage_cd = 'Furs' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Collections' , IVANS_coverage_cd = 'COLCT' where internal_coverage_cd = 'Furs (Blanket)' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Collections' , IVANS_coverage_cd = 'COLCT' where internal_coverage_cd = 'Furs (Scheduled)' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Collections' , IVANS_coverage_cd = 'COLCT' where internal_coverage_cd = 'Guns' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Collections' , IVANS_coverage_cd = 'COLCT' where internal_coverage_cd = 'Guns (Blanket)' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Collections' , IVANS_coverage_cd = 'COLCT' where internal_coverage_cd = 'Guns (Scheduled)' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Surcharge' , IVANS_coverage_cd = 'STS' where internal_coverage_cd = 'Healthy Homes Fund Surcharge' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Hurricane Premium' , IVANS_coverage_cd = 'HURR' where internal_coverage_cd = 'Hurricane' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Increased Incident Business Property' , IVANS_coverage_cd = 'INCBP' where internal_coverage_cd = 'Increased Incident Business Property' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Increased Incident Business Threshold' , IVANS_coverage_cd = 'INBUS' where internal_coverage_cd = 'Increased Incident Business Threshold' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Increased Incidental Business Threshold' , IVANS_coverage_cd = 'INBUS' where internal_coverage_cd = 'Increased Incidental Business Property' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Fees' , IVANS_coverage_cd = 'POLFE' where internal_coverage_cd = 'Inspection Fee' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Collections' , IVANS_coverage_cd = 'COLCT' where internal_coverage_cd = 'Jewelry' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Collections' , IVANS_coverage_cd = 'COLCT' where internal_coverage_cd = 'Jewelry (Blanket)' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Collections' , IVANS_coverage_cd = 'COLCT' where internal_coverage_cd = 'Jewelry (Scheduled)' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Landscaping Coverage Increased Limits' , IVANS_coverage_cd = 'PST' where internal_coverage_cd = 'Landscape' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Law \& Ordinance Coverage Increase' , IVANS_coverage_cd = 'BOLAW' where internal_coverage_cd = 'Law Ordinance' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Law \& Ordinance Coverage Increase' , IVANS_coverage_cd = 'BOLAW' where internal_coverage_cd = 'Law And Ordinance' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Law \& Ordinance Coverage Increase' , IVANS_coverage_cd = 'BOLAW' where internal_coverage_cd = 'Law Ordinance Coverage Increase' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Law \& Ordinance Coverage Increase' , IVANS_coverage_cd = 'BOLAW' where internal_coverage_cd = 'Law Ordinance Increase Term' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Homeowners Liability Premium' , IVANS_coverage_cd = 'PL' where internal_coverage_cd = 'Liability Coverage' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Liability Extension' , IVANS_coverage_cd = 'PL' where internal_coverage_cd = 'Liability Extension' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Loss Assessment Increase' , IVANS_coverage_cd = 'LAC' where internal_coverage_cd = 'Loss Assessment Increase' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Collections' , IVANS_coverage_cd = 'COLCT' where internal_coverage_cd = 'Lux' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Fees' , IVANS_coverage_cd = 'POLFE' where internal_coverage_cd = 'MGA Fee' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Mine Subsidence Coverage' , IVANS_coverage_cd = 'MIN' where internal_coverage_cd = 'Mine Subsidence' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Collections' , IVANS_coverage_cd = 'COLCT' where internal_coverage_cd = 'Misc' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Collections' , IVANS_coverage_cd = 'COLCT' where internal_coverage_cd = 'Miscellaneous (Scheduled)' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Taxes' , IVANS_coverage_cd = 'TCF' where internal_coverage_cd = 'Municipal Premium Tax' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Taxes' , IVANS_coverage_cd = 'TCF' where internal_coverage_cd = 'Municipal Tax' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Collections' , IVANS_coverage_cd = 'COLCT' where internal_coverage_cd = 'Music' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Collections' , IVANS_coverage_cd = 'COLCT' where internal_coverage_cd = 'Music (Blanket)' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Collections' , IVANS_coverage_cd = 'COLCT' where internal_coverage_cd = 'Musical Instruments (Blanket)' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Collections' , IVANS_coverage_cd = 'COLCT' where internal_coverage_cd = 'Musical Instruments (Scheduled)' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Optional Coverage Premium - Manual' , IVANS_coverage_cd = 'OCP' where internal_coverage_cd = 'Optional Coverages' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Optional Coverage Premium - Manual' , IVANS_coverage_cd = 'OCP' where internal_coverage_cd = 'Manual' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Property Remediation and Coverages for Escaped Liquid' , IVANS_coverage_cd = 'OILSR' where internal_coverage_cd = 'Optional Property Removal Escape Liquidity' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Optional Replace Cost' , IVANS_coverage_cd = 'CERC' where internal_coverage_cd = 'Optional Replace Cost' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Fee' , IVANS_coverage_cd = 'POLFE' where internal_coverage_cd = 'PLIGA Assessment' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Premises Liability Limitation' , IVANS_coverage_cd = 'ADDRL' where internal_coverage_cd = 'Premises Liability Limitation' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Replacement Cost Coverage' , IVANS_coverage_cd = 'RCC' where internal_coverage_cd = 'Replacement Cost Coverage' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Taxes' , IVANS_coverage_cd = 'TCF' where internal_coverage_cd = 'Rhode Island Surplus Lines Tax' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Roof Covering Full Reconstruction Cost Coverage' , IVANS_coverage_cd = 'RFCON' where internal_coverage_cd = 'Roof Covering Full Reconstruction' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Service Line Protection' , IVANS_coverage_cd = 'SRVLN' where internal_coverage_cd = 'Service Line' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Collections' , IVANS_coverage_cd = 'COLCT' where internal_coverage_cd = 'Silver' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Collections' , IVANS_coverage_cd = 'COLCT' where internal_coverage_cd = 'Silver (Blanket)' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Collections' , IVANS_coverage_cd = 'COLCT' where internal_coverage_cd = 'Silver (Scheduled)' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Collections' , IVANS_coverage_cd = 'COLCT' where internal_coverage_cd = 'Stamps' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Collections' , IVANS_coverage_cd = 'COLCT' where internal_coverage_cd = 'Stamps (Blanket)' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Collections' , IVANS_coverage_cd = 'COLCT' where internal_coverage_cd = 'Stamps (Scheduled)' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Sinkhole Collapse' , IVANS_coverage_cd = 'SINK' where internal_coverage_cd = 'Sinkhole' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Sinkhole Collapse Coverage Extension' , IVANS_coverage_cd = 'SINEX' where internal_coverage_cd = 'Sinkhole Collapse' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Fees' , IVANS_coverage_cd = 'POLFE' where internal_coverage_cd = 'Stamping Fee' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Subscriber Contribution' , IVANS_coverage_cd = 'SUBSC' where internal_coverage_cd = 'Subscriber Contribution' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Fee' , IVANS_coverage_cd = 'POLFE' where internal_coverage_cd = 'Subscriber Contribution (Homeowners)' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Sump Pump \& Sewers Increased Limits' , IVANS_coverage_cd = 'SEWER' where internal_coverage_cd = 'Sump Pump' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Sump Pump Premium' , IVANS_coverage_cd = 'SEWIN' where internal_coverage_cd = 'Sump Sewers Increased Limits' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Taxes' , IVANS_coverage_cd = 'TCF' where internal_coverage_cd = 'Surplus Lines Tax' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Home Systems Protection' , IVANS_coverage_cd = 'HSP' where internal_coverage_cd = 'Systems Protection' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Thoroughbred Horse Liability Extension' , IVANS_coverage_cd = 'EQUIN' where internal_coverage_cd = 'Thoroughbred Horse Liability Extension' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Fees' , IVANS_coverage_cd = 'POLFE' where internal_coverage_cd = 'Transaction Fee' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Collections' , IVANS_coverage_cd = 'COLCT' where internal_coverage_cd = 'Wearable Collectibles' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Collections' , IVANS_coverage_cd = 'COLCT' where internal_coverage_cd = 'Wearable Collectibles (Scheduled)' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Wildfire Premium' , IVANS_coverage_cd = 'WLFRP' where internal_coverage_cd = 'Wildfire' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Wind/Hail Premium' , IVANS_coverage_cd = 'WNDHL' where internal_coverage_cd = 'Wind/Hail' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Collections' , IVANS_coverage_cd = 'COLCT' where internal_coverage_cd = 'Wine' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Collections' , IVANS_coverage_cd = 'COLCT' where internal_coverage_cd = 'Wine (Blanket)' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Collections' , IVANS_coverage_cd = 'COLCT' where internal_coverage_cd = 'Wine (Scheduled)' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Workers Compensation Endorsement' , IVANS_coverage_cd = 'WORKE' where internal_coverage_cd = 'Workers Compensation' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Collections' , IVANS_coverage_cd = 'COLCT' where internal_coverage_cd = 'Worldwide Jewelry (Blanket)' and product_cd = 'HO' ;
UPDATE edw_core.tinternal_coverage set IVANS_coverage_nm = 'Collections' , IVANS_coverage_cd = 'COLCT' where internal_coverage_cd = 'Worldwide Jewelry (Scheduled)' and product_cd = 'HO' ;