-- Product
update edw_stage.ControlLoadTable
set CustomScript  = '{              "SelectStatement": "SELECT [Id]
      ,[InternalName]
      ,[Name]
      ,[CreatedDate]
      ,[UpdatedDate]
      ,[IsEnabled]
      ,[ProductLine]
      ,[RateDefinitionServiceName]
      ,[RulesDefinitionServiceName]
      ,[FormDefinitionServiceName]
      ,[ExternalUserCanBind]
      ,[ExternalUserCanOffer]
      ,[RoundPremiumToNearestDollar]
      ,[CanBillToBrokerage]
      ,[CanBillToInsured]
      ,[CanBillToMortgagee]
      ,CASE WHEN [name] = ''Condo'' THEN ''CO'' ELSE [ProductCode] END AS [ProductCode]
      ,[ExternalSourceId]
      ,[IncrementPolicyNumberOnRenewal]
      ,[GeneratePolicyNumberOnCreation]
      ,[PrimaryInsuredMustBeIndividual]
      ,[AllowPolicyNumberOverride]
      ,[CanBindWithoutIssuance]
      ,[AllowedStates]
      ,[BrokerageMustHaveEffectiveLicenseToBind]
      ,[CanChangeRiskState]
  FROM "          }'
where JSON_value(SourceObjectSettings,'$.table') = 'Product';