update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Endorsement' where task_workflow_nm = 'Admitted Endorsement' and task_workflow_step_nm  =  'Admitted Endorsement Bound & Issued';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Endorsement' where task_workflow_nm = 'Admitted Endorsement' and task_workflow_step_nm  =  'Admitted Endorsement Declined';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Endorsement' where task_workflow_nm = 'Admitted Endorsement' and task_workflow_step_nm  =  'Admitted Endorsement Not Taken';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Endorsement' where task_workflow_nm = 'Admitted Endorsement' and task_workflow_step_nm  =  'Admitted Endorsement Offered';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Endorsement' where task_workflow_nm = 'Admitted Endorsement' and task_workflow_step_nm  =  'Non Premium Endorsement Review';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Endorsement' where task_workflow_nm = 'Admitted Endorsement' and task_workflow_step_nm  =  'Premium Endorsement Bind Request';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Endorsement' where task_workflow_nm = 'Admitted Endorsement' and task_workflow_step_nm  =  'Premium Endorsement Review';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Renewal' where task_workflow_nm = 'Admitted Renewal' and task_workflow_step_nm  =  'Admitted Renewal Issued';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Renewal' where task_workflow_nm = 'Admitted Renewal' and task_workflow_step_nm  =  'Admitted Renewal Not Taken';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Renewal' where task_workflow_nm = 'Admitted Renewal' and task_workflow_step_nm  =  'Bind Admitted Renewal';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Renewal' where task_workflow_nm = 'Admitted Renewal' and task_workflow_step_nm  =  'Process Admitted Renewal';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Renewal' where task_workflow_nm = 'Admitted Renewal' and task_workflow_step_nm  =  'Quote Admitted Renewal';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Cancellation' where task_workflow_nm = 'Cancellation' and task_workflow_step_nm  =  'Cancellation Request';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Cancellation' where task_workflow_nm = 'Cancellation' and task_workflow_step_nm  =  'Cancellation Request Rescinded';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Cancellation' where task_workflow_nm = 'Cancellation' and task_workflow_step_nm  =  'Policy Canceled';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Claims' where task_workflow_nm = 'Claims' and task_workflow_step_nm  =  'Claim Risk Alert Review';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Referral' where task_workflow_nm = 'Endorsement Referral' and task_workflow_step_nm  =  'Endorsement Quote Not Taken';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Referral' where task_workflow_nm = 'Endorsement Referral' and task_workflow_step_nm  =  'Referral Approved';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Referral' where task_workflow_nm = 'Endorsement Referral' and task_workflow_step_nm  =  'Referral Denied';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Endorsement' where task_workflow_nm = 'Endorsement Referral' and task_workflow_step_nm  =  'Referral Review';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Cancellation' where task_workflow_nm = 'Legacy' and task_workflow_step_nm  =  'Cancellation Request';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Claims' where task_workflow_nm = 'Legacy' and task_workflow_step_nm  =  'Claims';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Endorsement' where task_workflow_nm = 'Legacy' and task_workflow_step_nm  =  'Endorsement Referral';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Endorsement' where task_workflow_nm = 'Legacy' and task_workflow_step_nm  =  'Endorsment';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'RMS' where task_workflow_nm = 'Legacy' and task_workflow_step_nm  =  'Inspection has been cancelled';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'RMS' where task_workflow_nm = 'Legacy' and task_workflow_step_nm  =  'Inspection Ordered on Cancelled Policy';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'New Business' where task_workflow_nm = 'Legacy' and task_workflow_step_nm  =  'Manual Bind Request';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'New Business' where task_workflow_nm = 'Legacy' and task_workflow_step_nm  =  'Manual Quote';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'New Business' where task_workflow_nm = 'Legacy' and task_workflow_step_nm  =  'New Business Referral';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Forms' where task_workflow_nm = 'Legacy' and task_workflow_step_nm  =  'New York Change form requires stamping';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Renewal' where task_workflow_nm = 'Legacy' and task_workflow_step_nm  =  'Renewal';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Renewal' where task_workflow_nm = 'Legacy' and task_workflow_step_nm  =  'Renewal Referral';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'RMS' where task_workflow_nm = 'Legacy' and task_workflow_step_nm  =  'RMS';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'New Business' where task_workflow_nm = 'Legacy' and task_workflow_step_nm  =  'UW Inquiry';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'null' where task_workflow_nm = 'Legacy' and task_workflow_step_nm  =  '';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Binds' where task_workflow_nm = 'New Business' and task_workflow_step_nm  =  'NB Bind Request Review';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'New Business' where task_workflow_nm = 'New Business' and task_workflow_step_nm  =  'NB Bound & Issued';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'New Business' where task_workflow_nm = 'New Business' and task_workflow_step_nm  =  'NB Declined';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'New Business' where task_workflow_nm = 'New Business' and task_workflow_step_nm  =  'NB Underwriting Review';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'New Business' where task_workflow_nm = 'New Business' and task_workflow_step_nm  =  'Quote Declined';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'New Business' where task_workflow_nm = 'New Business' and task_workflow_step_nm  =  'Quote Not Taken';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'New Business' where task_workflow_nm = 'New Business' and task_workflow_step_nm  =  'Quote Offered';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'New Business' where task_workflow_nm = 'New Business' and task_workflow_step_nm  =  'Submit Dec & Diligent Effort to ELANY';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'New Business' where task_workflow_nm = 'New Business' and task_workflow_step_nm  =  'Upload ELANY Dec and Issue';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Follow Ups' where task_workflow_nm = 'New Business Follow Up' and task_workflow_step_nm  =  'NB Bind Requested';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Follow Ups' where task_workflow_nm = 'New Business Follow Up' and task_workflow_step_nm  =  'NB Bound & Issued';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Follow Ups' where task_workflow_nm = 'New Business Follow Up' and task_workflow_step_nm  =  'New Business Follow Up';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Follow Ups' where task_workflow_nm = 'New Business Follow Up' and task_workflow_step_nm  =  'Quote Not Taken';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Referral' where task_workflow_nm = 'New Business Referral' and task_workflow_step_nm  =  'Quote Not Taken';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Referral' where task_workflow_nm = 'New Business Referral' and task_workflow_step_nm  =  'Referral Approved';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Referral' where task_workflow_nm = 'New Business Referral' and task_workflow_step_nm  =  'Referral Denied';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Referral' where task_workflow_nm = 'New Business Referral' and task_workflow_step_nm  =  'Referral Review';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Endorsement' where task_workflow_nm = 'Non-Admitted Endorsement' and task_workflow_step_nm  =  'Non Premium Endorsement Bind Request';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Endorsement' where task_workflow_nm = 'Non-Admitted Endorsement' and task_workflow_step_nm  =  'Non Premium Endorsement Review';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Endorsement' where task_workflow_nm = 'Non-Admitted Endorsement' and task_workflow_step_nm  =  'Non-Admitted Endorsement Bound & Issued';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Endorsement' where task_workflow_nm = 'Non-Admitted Endorsement' and task_workflow_step_nm  =  'Non-Admitted Endorsement Declined';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Endorsement' where task_workflow_nm = 'Non-Admitted Endorsement' and task_workflow_step_nm  =  'Non-Admitted Endorsement Not Taken';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Endorsement' where task_workflow_nm = 'Non-Admitted Endorsement' and task_workflow_step_nm  =  'Non-Admitted Endorsement Offered';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Endorsement' where task_workflow_nm = 'Non-Admitted Endorsement' and task_workflow_step_nm  =  'Premium Endorsement Bind Request';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Endorsement' where task_workflow_nm = 'Non-Admitted Endorsement' and task_workflow_step_nm  =  'Premium Endorsement Review';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Endorsement' where task_workflow_nm = 'Non-Admitted Endorsement' and task_workflow_step_nm  =  'Submit Dec & Policy Change to ELANY';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Endorsement' where task_workflow_nm = 'Non-Admitted Endorsement' and task_workflow_step_nm  =  'Upload ELANY Dec and Issue';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Binds' where task_workflow_nm = 'Non-Admitted Option (From Admitted)' and task_workflow_step_nm  =  'Non-Admitted Renewal Option Bind Request Review';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Renewal' where task_workflow_nm = 'Non-Admitted Renewal' and task_workflow_step_nm  =  'Non-Admitted Renewal Bind Request Review';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Renewal' where task_workflow_nm = 'Non-Admitted Renewal' and task_workflow_step_nm  =  'Non-Admitted Renewal Bound & Issued';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Renewal' where task_workflow_nm = 'Non-Admitted Renewal' and task_workflow_step_nm  =  'Non-Admitted Renewal Not Taken';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Renewal' where task_workflow_nm = 'Non-Admitted Renewal' and task_workflow_step_nm  =  'Non-Admitted Renewal Offered';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Renewal' where task_workflow_nm = 'Non-Admitted Renewal' and task_workflow_step_nm  =  'Process Non-Admitted Renewal';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Renewal' where task_workflow_nm = 'Non-Admitted Renewal' and task_workflow_step_nm  =  'Quote Non-Admitted Renewal';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Renewal' where task_workflow_nm = 'Non-Admitted Renewal' and task_workflow_step_nm  =  'Submit Dec to ELANY';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Renewal' where task_workflow_nm = 'Non-Admitted Renewal' and task_workflow_step_nm  =  'Upload ELANY Dec and Issue';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Non-Renewal' where task_workflow_nm = 'Non-Renewal' and task_workflow_step_nm  =  'Mail out Non-Renewal Notice';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Non-Renewal' where task_workflow_nm = 'Non-Renewal' and task_workflow_step_nm  =  'Non-Renewal Rescinded';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Non-Renewal' where task_workflow_nm = 'Non-Renewal' and task_workflow_step_nm  =  'Non-Renewed';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Non-Renewal' where task_workflow_nm = 'Non-Renewal' and task_workflow_step_nm  =  'Process Non-Renewal';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Follow Ups' where task_workflow_nm = 'Renewal Follow Up' and task_workflow_step_nm  =  'Renewal Bind Requested';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Follow Ups' where task_workflow_nm = 'Renewal Follow Up' and task_workflow_step_nm  =  'Renewal Bound';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Follow Ups' where task_workflow_nm = 'Renewal Follow Up' and task_workflow_step_nm  =  'Renewal Follow Up';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Follow Ups' where task_workflow_nm = 'Renewal Follow Up' and task_workflow_step_nm  =  'Renewal Not Taken';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Follow Ups' where task_workflow_nm = 'Renewal Follow Up' and task_workflow_step_nm  =  'Renewal Option Bind Requested';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Follow Ups' where task_workflow_nm = 'Renewal Follow Up' and task_workflow_step_nm  =  'Renewal Option Bound';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Follow Ups' where task_workflow_nm = 'Renewal Follow Up' and task_workflow_step_nm  =  'Renewal Option Follow Up';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Follow Ups' where task_workflow_nm = 'Renewal Follow Up' and task_workflow_step_nm  =  'Renewal Option Not Taken ';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Referral' where task_workflow_nm = 'Renewal Referral' and task_workflow_step_nm  =  'Referral Approved';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Referral' where task_workflow_nm = 'Renewal Referral' and task_workflow_step_nm  =  'Referral Denied';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Referral' where task_workflow_nm = 'Renewal Referral' and task_workflow_step_nm  =  'Referral Review';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Referral' where task_workflow_nm = 'Renewal Referral' and task_workflow_step_nm  =  'Renewal Quote Not Taken';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Renewal' where task_workflow_nm = 'Renewal Review' and task_workflow_step_nm  =  'Renewal Review';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'RMS' where task_workflow_nm = 'RMS Queue' and task_workflow_step_nm  =  'Inspection Ordered on Cancelled Policy';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Cancellation' where task_workflow_nm = 'VC - Cancellation Queue' and task_workflow_step_nm  =  'Cancellation Request';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Cancellation' where task_workflow_nm = 'VC - Cancellation Queue' and task_workflow_step_nm  =  'Renewal';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Forms' where task_workflow_nm = 'VC - Diligent Effort Forms Queue' and task_workflow_step_nm  =  'Acknowledgement of Applicant';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Forms' where task_workflow_nm = 'VC - Diligent Effort Forms Queue' and task_workflow_step_nm  =  'Diligent Effort Affidavit';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Forms' where task_workflow_nm = 'VC - Diligent Effort Forms Queue' and task_workflow_step_nm  =  'Diligent Effort Form';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Forms' where task_workflow_nm = 'VC - Diligent Effort Forms Queue' and task_workflow_step_nm  =  'New Jersey Customer Affidavit';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Forms' where task_workflow_nm = 'VC - Diligent Effort Forms Queue' and task_workflow_step_nm  =  'Statement of Diligent Effort';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Forms' where task_workflow_nm = 'VC - Diligent Effort Forms Queue' and task_workflow_step_nm  =  'Texas Diligent Effort';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Endorsement' where task_workflow_nm = 'VC - Endorsement Queue' and task_workflow_step_nm  =  'Endorsement Referral';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Endorsement' where task_workflow_nm = 'VC - Endorsement Queue' and task_workflow_step_nm  =  'New York Change form requires stamping';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'General' where task_workflow_nm = 'VC - General Queue' and task_workflow_step_nm  =  'Vehicle Not Yet Registered';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Renewal' where task_workflow_nm = 'VC - Renewal Queue' and task_workflow_step_nm  =  'New York Dec requires stamping';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Renewal' where task_workflow_nm = 'VC - Renewal Queue' and task_workflow_step_nm  =  'Renewal Referral';
update edw_core.ttask_workflow_step set task_workflow_step_category_nm  = 'Follow Ups' where task_workflow_nm = 'Anythng in the follow up status' and task_workflow_step_nm  =  '';
