
-- tedw_release_summary
INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 02/20/2024 :</span>
<h4 style="margin-top: 0;">This release includes the following:</h4>
<ol>
    <li>Enhancements - 11
        <ul>
			<li>Added new columns to Renewal Data Mart</li>
			<li>Created task workflow step table and updated categories</li>
            <li>Updated the subscriber contribution logic for homeowner policies with collections endorsement</li>
            <li>Created new stored procedures to support eBao claims UI and Majesco billing process</li>
			<li>Created Metal 01/24 release related columns</li>
			<li>Created new tclaim_litigation table</li>
            <li>Created Florida OIR related columns </li>
			<li>Added new columns to broker and producer tables</li>
	   </ul>
    </li>
    <li>Bug tickets - 9
        <ul>
            <li>Fixed Workday UEP issue to capture a few Auto related missing transactions</li>
			<li>Fixed duplicates in Auto vehicle table and updated inforce vehicle count logic</li>
            <li>Fixed logic to calculate PEL Youthful Drivers count</li>
			<li>Fixed logic for unit_no in thome_location </li>
			<li>Fixed logic for a few IVANS Home related fields </li>
            <li>Metal Data Fixes </li>
        </ul>
    </li>
</ol>
'
,'Yes'
,'2024-02-20'
,getdate()
,getdate()
)
;

-- tedw_release_note

INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD4651','Roof_ Field Additions into additional coverage tables','Enhancement','2024-02-09','Alberto Almario','Addition','edw_core','thome_additional_coverage ','roof_exclusion_with_ensuing_loss_in ','Metal 01/24 release related new column','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD4651','Roof_ Field Additions into additional coverage tables','Enhancement','2024-02-09','Alberto Almario','Addition','edw_core','thome_additional_coverage ','roof_coverage_endorsement_wh_in ','Metal 01/24 release related new column','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD4651','Roof_ Field Additions into additional coverage tables','Enhancement','2024-02-09','Alberto Almario','Addition','edw_core','thome_additional_coverage ','roof_coverage_endorsement_ap_in ','Metal 01/24 release related new column','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD4651','Roof_ Field Additions into additional coverage tables','Enhancement','2024-02-09','Alberto Almario','Addition','edw_core','thome_additional_coverage ','roof_coverage_endorsement_rv_in ','Metal 01/24 release related new column','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD4651','Roof_ Field Additions into additional coverage tables','Enhancement','2024-02-09','Alberto Almario','Addition','edw_core','tquote_home_additional_coverage','roof_exclusion_with_ensuing_loss_in ','Metal 01/24 release related new column','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD4651','Roof_ Field Additions into additional coverage tables','Enhancement','2024-02-09','Alberto Almario','Addition','edw_core','tquote_home_additional_coverage','roof_coverage_endorsement_wh_in ','Metal 01/24 release related new column','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD4651','Roof_ Field Additions into additional coverage tables','Enhancement','2024-02-09','Alberto Almario','Addition','edw_core','tquote_home_additional_coverage','roof_coverage_endorsement_ap_in ','Metal 01/24 release related new column','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD4651','Roof_ Field Additions into additional coverage tables','Enhancement','2024-02-09','Alberto Almario','Addition','edw_core','tquote_home_additional_coverage','roof_coverage_endorsement_rv_in ','Metal 01/24 release related new column','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI28496/AD4703','EDW: Missing field for total liability location count for home policies ','Enhancement','2024-02-02','Alberto Almario','Addition','edw_core','thome_additional_coverage','extended_liability_location_ct','Created new column','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI28496/AD4703','EDW: Missing field for total liability location count for home policies ','Enhancement','2024-02-02','Alberto Almario','Addition','edw_core','tquote_home_additional_coverage ','extended_liability_location_ct','Created new column','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5029','Add producer_id and producer_sk to tproducer tpolicy_history and tquote_history tables ','Enhancement','2024-02-09','Alberto Almario','Addition','edw_core','tproducer','producer_id','Created new column','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5029','Add producer_id and producer_sk to tproducer tpolicy_history and tquote_history tables ','Enhancement','2024-02-09','Alberto Almario','Addition','edw_core','tpolicy_history','producer_sk ','Created new column','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5029','Add producer_id and producer_sk to tproducer tpolicy_history and tquote_history tables ','Enhancement','2024-02-09','Alberto Almario','Addition','edw_core','tquote_history ','producer_sk ','Created new column','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29503/AD4940','Workflow step category update','Enhancement','2024-02-20','Architha Gudimalla','Datafix','edw_core','ttask_workflow_step','task_workflow_step_category_nm','Updated the category to show as VRE to VES for "Quote VRE to VES Option" and "Non-Admitted Renewal Option Underwriting Review"','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29318/AD4961','Monoline Indicator','Enhancement','2024-02-20','Architha Gudimalla','Addition','edw_core','trenewal_summary','expiring_customer_other_inforce_ct','Added new column to show how many other active policies the expiring policy customer has at the expiration date.  ','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD4829','Subscriber contribution changes for LUX on HO policies ','Enhancement','2024-02-20','Architha Gudimalla','Datafix','edw_core','tpolicy_transaction','','Subscriber contribution logic for LUX on HO is updated to use from Lux product instead of HO product','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI28950/AD4816','Vehicle Premium not flowing through correctly from tpolicy_transaction to tauto_vehicle_coverage','Bug','2024-02-20','Architha Gudimalla','Datafix','edw_core','tauto_vehicle','','Identified vehicles with multiple vehicle_unique_id for same VIN and fixed it in Metal and EDW.  Validation has been added to monitor it.','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI28950/AD4799','Update inforce logic to use vehicle_deleted_in','Bug','2024-02-20','Architha Gudimalla','Datafix','edw_core','tinternal_coverage_inforce','','Inforce logic is updated to use tauto_vehicle_coverage.vehicle_deleted_in','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI28950/AD4799','Update inforce logic to use vehicle_deleted_in','Bug','2024-02-20','Architha Gudimalla','Datafix','edw_core','titem_inforce','','Inforce logic is updated to use tauto_vehicle_coverage.vehicle_deleted_in','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29340/AD4961','Pending non-renewal indicator','Enhancement','2024-02-20','Architha Gudimalla','Addition','edw_core','trenewal_summary','expiring_pending_non_renewal_written_premium_amt','Added new column to show pending non-renewal written premium for the expiring policy','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29438/AD5100','Add producer status to tproducer','Enhancement','2024-02-20','Hernando Garcia','Addition','edw_core','tproducer','producer_status','Created new column','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI28565/AD4710','PEL Youthful Drivers count incorrect','Bug','2024-02-02','Hernando Gonzalez','Datafix','edw_core','tpel_coverage','driver','Identified issue with driver age calculation associated with PEL drivers.  Code has been fixed to address this issue.','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD4712','IVANS Home - Field Given Name is blank for some policies','Bug','2024-02-02','Hernando Gonzalez','Modification','edw_integration','policy_ivans_home_feed','GivenName_013','Modified logic for "GivenName_013" as per vendor requirement','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD4712','IVANS Home - Field Given Name is blank for some policies','Bug','2024-02-02','Hernando Gonzalez','Modification','edw_integration','policy_ivans_home_feed','OtherGivenName_014','Modified logic for "OtherGivenName_014" as per vendor requirement','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD4712','IVANS Home Logic for Amt_039 needs to be changed','Bug','2024-02-02','Hernando Gonzalez','Modification','edw_integration','policy_ivans_home_feed','Amt_039','Modified logic for "Amt_039" as per vendor requirement','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI28550/AD4707','eBao to Claims Model Integration - Subclaim Additional Fields','Enhancement','2024-02-09','Yunus Mohammed','Addition','edw_core','tclaim_feature','assignment_of_benefits_contractor_in','Florida OIR project related new column','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI28550/AD4707','eBao to Claims Model Integration - Subclaim Additional Fields','Enhancement','2024-02-09','Yunus Mohammed','Addition','edw_core','tclaim_feature','public_adjuster_in','Florida OIR project related new column','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI28550/AD4707','eBao to Claims Model Integration - Subclaim Additional Fields','Enhancement','2024-02-09','Yunus Mohammed','Addition','edw_core','tclaim_feature','arbitration_in','Florida OIR project related new column','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI28550/AD4707','eBao to Claims Model Integration - Subclaim Additional Fields','Enhancement','2024-02-09','Yunus Mohammed','Addition','edw_core','tclaim_feature','mediation_in','Florida OIR project related new column','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI28550/AD4707','eBao to Claims Model Integration - Subclaim Additional Fields','Enhancement','2024-02-09','Yunus Mohammed','Addition','edw_core','tclaim_feature','appraisal_in','Florida OIR project related new column','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI28550/AD4707','eBao to Claims Model Integration - Subclaim Additional Fields','Enhancement','2024-02-09','Yunus Mohammed','Addition','edw_core','tclaim_feature','alternative_dispute_resolution_in','Florida OIR project related new column','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI28550/AD4707','eBao to Claims Model Integration - Subclaim Additional Fields','Enhancement','2024-02-09','Yunus Mohammed','Addition','edw_core','tclaim_feature','neutral_evaluation_in','Florida OIR project related new column','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI28550/AD4707','eBao to Claims Model Integration - Subclaim Additional Fields','Enhancement','2024-02-09','Yunus Mohammed','Addition','edw_core','tclaim_feature','settlement_conference_in','Florida OIR project related new column','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI28550/AD4707','eBao to Claims Model Integration - Subclaim Additional Fields','Enhancement','2024-02-09','Yunus Mohammed','Addition','edw_core','tclaim_feature','settlement_resolution_in','Florida OIR project related new column','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD4978','Workday unearned premium issue- Missing transactions','Bug','2024-02-20','Yunus Mohammed','Modification','edw_integration','policy_workday_unearned_premium_feed','','Identified issue with workday UEP file generation process where records with identical coverage and premium associated with Auto policy were getting eliminated (which was causing under-reported premium).  Code has been fixed to address this issue.','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29137/AD4877','API Integration - List of generic product types for claims portal','Enhancement','2024-02-02','Yunus Mohammed','Addition','edw_integration','claim_product_search_api','','New stored procedure has been created in the integration layer to support claims portal (fetch generic product codes)','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29137/AD4936','API Integration - New stored procedure for Majesco Billing File Processing','Enhancement','2024-02-09','Yunus Mohammed','Addition','edw_integration','policy_customer_portal_api','','New stored procedure has been created in the integration layer to support Majesco Billing File Processing (fetch billing account number and policy number)','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI28554/AD4921','eBao to Claims Model Integration - Litigation table','Enhancement','2024-02-09','Yunus Mohammed','Addition','edw_core','tclaim_litigation','','Created new tclaim_litigation table','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI27990/AD4646','All unit numbers are blank','Bug','2024-02-02','Yunus Mohammed','Datafix','edw_core','thome_location','unit_no','Identified issue with unit_no field.  Code has been fixed to address this issue.','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29519','Duplicate Cancellation Records for 3 policies  ','Bug','2024-02-17','Sandeep Gundreddy','Datafix','edw_core','','','Issue was identified in Metal and it impacts 3 policies only. HO100021087-03,CO100097381-02,HO100020233-03. Fix was implemented in Metal to prevent the issue in the future.  Deleted duplicate cancellation record from Metal and EDW. Validation has been added to montor it.','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29697','Duplicate records for 2 policies','Bug','2024-02-17','Sandeep Gundreddy','Datafix','edw_core','','','Issue was identified in Metal and it impacts 2 policies only. HO125197511036-03,EX100223220-05. Fix was implemented in Metal to prevent the issue in the future.  Deleted duplicate records from Metal and EDW. Validation has been added to montor it.','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI21429/AD4845','Homeowners Policies Missing Counties (obstacle for TICO Home Monthly Report)','Bug','2024-02-17','Alberto Almario','Datafix','edw_core','thome_location','county_nm','Updated county name for 16 policies as per the request in Metal and EDW. This is just a onetime update.','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI21429/AD4845','Homeowners Policies Missing Counties (obstacle for TICO Home Monthly Report)','Bug','2024-02-17','Alberto Almario','Datafix','edw_core','tquote_home_location','county_nm','Updated county name for 16 policies as per the request in Metal and EDW. This is just a onetime update.','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI28895/AD4803','vehicle type = /','Bug','2024-02-17','Alberto Almario','Datafix','edw_core','tauto_vehicle','vehicle_type','vehicle type  was migrated as / instead of Snowmobile / ATV.  This is a migration issue and there is no issue with Metal issued policies.  Fixed data in Metal and EDW','1','Yes','2024-02-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI28895/AD4803','vehicle type = /','Bug','2024-02-17','Alberto Almario','Datafix','edw_core','tquote_auto_vehicle','vehicle_type','vehicle type  was migrated as / instead of Snowmobile / ATV.  This is a migration issue and there is no issue with Metal issued policies.  Fixed data in Metal and EDW','1','Yes','2024-02-20',getdate(),getdate());