-- tedw_release_summary
INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 03/04/2024 :</span>
<h4 style="margin-top: 0;">This release includes the following:</h4>
<ol>
    <li>Enhancements - 5
        <ul>
			<li>Added one_year_non_cat_earned_net_premium_amt and three_year_non_cat_earned_net_premium_amt columns to tbroker_summary </li>
			<li>Added Metal 02/24 release related new columns for Home</li>
			<li>Added Metal 02/24 release related new columns for Auto</li>
			<li>Updated the subscriber contribution logic for homeowner quotes with collections endorsement</li>
			<li>Updated task_workflow_step_category_nm for a few tasks</li>			
	   </ul>
    </li>
    <li>Bug tickets - 13
        <ul>
            <li>Fixed logic affecting claim policy search API for Condo policies</li>
			<li>Fixed logic for duplicate incidents in tauto_driver_incident</li>
			<li>Fixed logic to capture claim expense refund paid amount</li>
			<li>Fixed logic for antitheft_device_feature in tauto_vehicle_coverage </li>
			<li>Updated line of business mapping for auto coverage - property protection insurance</li>
			<li>Fixed migration data issue related to water_deductible field in thome_coverage</li>
			<li>Fixed migration data issue related to rating_territory_cd field in thome_coverage table</li> 
		 	<li>Fixed migration data issue related to exclude_wind_in field in thome_additional_coverage table</li>
			<li>Fixed migration data issue related to extended_replacement_cost_coverage_option field in thome_additional_coverage table</li>
			<li>Fixed migration data issue related to cause_of_loss_sk associated with 5 OnsShield claims</li>
        </ul>
    </li>
</ol>
'
,'Yes'
,'2024-03-04'
,getdate()
,getdate()
)
;


INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29803/AD5206','Enhancements - tbroker_summary','Enhancement','2024-03-01','Architha Gudimalla','Addition','edw_core','tbroker_summary','one_year_non_cat_earned_net_premium_amt','Created new column','3','Yes','2024-03-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29803/AD5206','Enhancements - tbroker_summary','Enhancement','2024-03-01','Architha Gudimalla','Addition','edw_core','tbroker_summary','three_year_non_cat_earned_net_premium_amt','Created new column','3','Yes','2024-03-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29808/AD5202','Enhancements - ttask_workflow_step','Enhancement','2024-03-01','Architha Gudimalla','Datafix','edw_core','ttask_workflow_step','task_workflow_step_category_nm','Updated task_workflow_step_category_nm for 19 rows','3','Yes','2024-03-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29566/AD5180','Fix antitheft_device_feature ','Bug','2024-03-01','Architha Gudimalla','Modification','edw_core','tauto_vehicle_coverage','antitheft_device_feature ','Updated the logic to load description for antitheft devices','3','Yes','2024-03-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5188','Subscriber contribution changes for LUX on HO policies ','Enhancement','2024-03-01','Architha Gudimalla','Datafix','edw_core','tquote_transaction','','For quotes, subscriber contribution logic for LUX on HO is updated to use details from LUX product instead of HO product','3','Yes','2024-03-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29688/AD5152','Fix duplicate incidents in tauto_driver_incident','Bug','2024-03-01','Architha Gudimalla','Modification','edw_core','tauto_driver_incident','','Updated the logic to fix duplicate incidents in tauto_driver_incident table','3','Yes','2024-03-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29688/AD5152','Fix duplicate incidents in tquote_auto_driver_incident','Bug','2024-03-01','Architha Gudimalla','Modification','edw_core','tquote_auto_driver_incident','','Updated the logic to fix duplicate incidents in tauto_driver_incident table','3','Yes','2024-03-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD4934','Auto - Metal 02/24 release related columns','Enhancement','2024-03-01','Rushin Shah','Addition','edw_core','tauto_vehicle_coverage','carfax_wholesale_value_amt','Metal 02/24 release related new column','3','Yes','2024-03-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD4934','Auto - Metal 02/24 release related columns','Enhancement','2024-03-01','Rushin Shah','Addition','edw_core','tauto_driver_incident','lending_loss_in','Metal 02/24 release related new column','3','Yes','2024-03-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD4934','Auto - Metal 02/24 release related columns','Enhancement','2024-03-01','Rushin Shah','Addition','edw_core','tquote_auto_vehicle_coverage','carfax_wholesale_value_amt','Metal 02/24 release related new column','3','Yes','2024-03-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD4934','Auto - Metal 02/24 release related columns','Enhancement','2024-03-01','Rushin Shah','Addition','edw_core','tquote_auto_driver_incident','lending_loss_in','Metal 02/24 release related new column','3','Yes','2024-03-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD4935','Home - Metal 02/24 release related columns','Enhancement','2024-03-01','Rushin Shah','Addition','edw_core','thome_coverage','aon_hurricane_cat_score_amt','Metal 02/24 release related new column','3','Yes','2024-03-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD4935','Home - Metal 02/24 release related columns','Enhancement','2024-03-01','Rushin Shah','Addition','edw_core','thome_coverage',' aon_hurricane_reinsurance_margin_amt','Metal 02/24 release related new column','3','Yes','2024-03-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD4935','Home - Metal 02/24 release related columns','Enhancement','2024-03-01','Rushin Shah','Addition','edw_core','thome_coverage','aon_hurricane_ceded_loss_amt','Metal 02/24 release related new column','3','Yes','2024-03-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD4935','Home - Metal 02/24 release related columns','Enhancement','2024-03-01','Rushin Shah','Addition','edw_core','thome_coverage','aon_hurricane_reinsurance_premium_amt','Metal 02/24 release related new column','3','Yes','2024-03-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD4935','Home - Metal 02/24 release related columns','Enhancement','2024-03-01','Rushin Shah','Addition','edw_core','thome_coverage','aon_hurricane_capital_cost_amt','Metal 02/24 release related new column','3','Yes','2024-03-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD4935','Home - Metal 02/24 release related columns','Enhancement','2024-03-01','Rushin Shah','Addition','edw_core','thome_coverage','aon_hurricane_cat_score_to_premium_ratio','Metal 02/24 release related new column','3','Yes','2024-03-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD4935','Home - Metal 02/24 release related columns','Enhancement','2024-03-01','Rushin Shah','Addition','edw_core','thome_coverage','aon_hurricane_aal_to_premium_ratio','Metal 02/24 release related new column','3','Yes','2024-03-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD4935','Home - Metal 02/24 release related columns','Enhancement','2024-03-01','Rushin Shah','Addition','edw_core','thome_coverage','aon_hurricane_aal_amt','Metal 02/24 release related new column','3','Yes','2024-03-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD4935','Home - Metal 02/24 release related columns','Enhancement','2024-03-01','Rushin Shah','Addition','edw_core','tquote_home_coverage','aon_hurricane_cat_score_amt','Metal 02/24 release related new column','3','Yes','2024-03-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD4935','Home - Metal 02/24 release related columns','Enhancement','2024-03-01','Rushin Shah','Addition','edw_core','tquote_home_coverage',' aon_hurricane_reinsurance_margin_amt','Metal 02/24 release related new column','3','Yes','2024-03-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD4935','Home - Metal 02/24 release related columns','Enhancement','2024-03-01','Rushin Shah','Addition','edw_core','tquote_home_coverage','aon_hurricane_ceded_loss_amt','Metal 02/24 release related new column','3','Yes','2024-03-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD4935','Home - Metal 02/24 release related columns','Enhancement','2024-03-01','Rushin Shah','Addition','edw_core','tquote_home_coverage','aon_hurricane_reinsurance_premium_amt','Metal 02/24 release related new column','3','Yes','2024-03-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD4935','Home - Metal 02/24 release related columns','Enhancement','2024-03-01','Rushin Shah','Addition','edw_core','tquote_home_coverage','aon_hurricane_capital_cost_amt','Metal 02/24 release related new column','3','Yes','2024-03-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD4935','Home - Metal 02/24 release related columns','Enhancement','2024-03-01','Rushin Shah','Addition','edw_core','tquote_home_coverage','aon_hurricane_cat_score_to_premium_ratio','Metal 02/24 release related new column','3','Yes','2024-03-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD4935','Home - Metal 02/24 release related columns','Enhancement','2024-03-01','Rushin Shah','Addition','edw_core','tquote_home_coverage','aon_hurricane_aal_to_premium_ratio','Metal 02/24 release related new column','3','Yes','2024-03-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD4935','Home - Metal 02/24 release related columns','Enhancement','2024-03-01','Rushin Shah','Addition','edw_core','tquote_home_coverage','aon_hurricane_aal_amt','Metal 02/24 release related new column','3','Yes','2024-03-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES (' VI29384/AD4976','Incorrect Subscriber contribution for EX100111060-01','Bug','2024-03-01','Rushin Shah','Datafix','edw_core','','','This is a migration issue.  Updated data in Metal and EDW. This is just a onetime update.','3','Yes','2024-03-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29885','Fix Line of Business Mapping for Auto Coverage - Property Protection Insurance','Bug','2024-02-27','Sandeep Gundreddy','Datafix','edw_core','tinternal_coverage','aslob_cd','Updated aslob to 192 for Property Protection Insurance as per the request. Updated data in Metal and EDW.','3','Yes','2024-03-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI26986/AD5171','HO146665442836-02 (FL) shows a 5000 water deductible on the backend that does not exist','Bug','2024-02-25','Yunus Mohammed','Datafix','edw_core','thome_coverage','water_deductible','This is a migration issue.  Updated data in Metal and EDW. This is just a onetime update.','3','Yes','2024-03-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI26969/AD5171','HO100025342-02 is missing a water deductible','Bug','2024-02-25','Yunus Mohammed','Datafix','edw_core','thome_coverage','water_deductible','This is a migration issue.  Updated data in Metal and EDW. This is just a onetime update.','3','Yes','2024-03-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI28407/AD4894','112 policies (127 transactions) missing extended replacement cost option','Bug','2024-02-25','Yunus Mohammed','Datafix','edw_core','thome_additional_coverage','extended_replacement_cost_coverage_option','This is a migration issue.  Updated data in Metal and EDW. This is just a onetime update.','3','Yes','2024-03-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI28774/AD4830','Exclude Wind migration issues','Bug','2024-02-25','Yunus Mohammed','Datafix','edw_core','thome_additional_coverage','exclude_wind_in','This is a migration issue.  Updated data in Metal and EDW. This is just a onetime update and affected 275 transactions.','3','Yes','2024-03-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI28483/AD4693','EDW: Missing rating territories','Bug','2024-02-25','Yunus Mohammed','Datafix','edw_core','thome_coverage','rating_territory_cd','This is a migration issue.  Updated data in Metal and EDW. This is just a onetime update.','3','Yes','2024-03-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29877/AD5226','Risk Location Missing for Condo policies','Bug','2024-03-01','Yunus Mohammed','Datafix','edw_integration','edw_integration.claim_policy_search_api','risk_item','This was an API integration issue affecting claim policy search API.  We have updated the stored procedure to fetch the missing risk values.','3','Yes','2024-03-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29925/5248','Update cause_of_loss_sk for 5 OS claims','Bug','2024-03-01','Yunus Mohammed','Datafix','edw_core','tclaim','cause_of_loss_sk','This is a migration issue.  Updated cause_of_loss_sk for 5 OS claims.  This is just a onetime update.  ','3','Yes','2024-03-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29828/AD4438','EDW data issue for claims that have expense refunds','Bug','2024-03-01','Yunus Mohammed','Datafix','edw_core','tclaim_transaction','refund_expense_paid_amt','Updated logic to appropriately capture refund_expense_paid_amt.','3','Yes','2024-03-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI28355','HO100262564 - Exclude Wind migration issues','Bug','2024-02-25','Yunus Mohammed','Datafix','edw_core','thome_additional_coverage','exclude_wind_in','This is a migration issue.  Updated data in Metal and EDW. This is just a onetime update.','3','Yes','2024-03-04',getdate(),getdate());