-- tedw_release_summary
INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 03/11/2024 :</span>
<h4 style="margin-top: 0;">This release includes the following:</h4>
<ol>
    <li>Enhancements - 6
        <ul>
			<li>Added one_year_loss_ratio, one_year_loss_ratio_capped, one_year_non_cat_loss_ratio, one_year_non_cat_loss_ratio_capped, one_year_frequency, one_year_non_cat_frequency, one_year_severity, one_year_non_cat_severity, three_year_loss_ratio, three_year_loss_ratio_capped, three_year_non_cat_loss_ratio, three_year_non_cat_loss_ratio_capped, three_year_frequency, three_year_non_cat_frequency, three_year_severity, three_year_non_cat_severity to tbroker_summary </li>
			<li>Added collision_ncrb_premium_amt, otc_ncrb_premium_amt columns for Auto </li>
			<li>Added fire_station_connected_fire_alarm_in, police_station_connected_burglar_alarm_in, local_fire_alarm_system_in, local_burglar_alarm_system_in, automatic_smoke_detectors_in, automatic_sprinkler_system columns for Home</li>
			<li>Added waive_inspection_in, waive_inspection_reason,inspection_note,rms_reviewed_in columns for Home </li>
			<li>Added rater_pip_discount column for Auto</li>
			<li>Updated task_workflow_step_category_nm for review inspection requirements</li>			
	   </ul>
    </li>
    <li>Bug tickets - 5
        <ul>
			<li>Fixed migration data issue related to prior_policy_no in tpolicy</li>
		</ul>
    </li>
</ol>
'
,'Yes'
,'2024-03-11'
,getdate()
,getdate()
)
;

-- tedw_release_note

INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES (' VI30069','The City and State is blank for policy# HO200024393. As a result the policy is not going to Majesco.','Bug','2024-03-04','Sandeep Gundreddy','Datafix','edw_core','tpolicy','mailing_address_city_nm','Isolated issue in Metal. impacts only HO200024393.  Updated data in Metal and EDW. This is just a onetime update.','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30098','Unable to amend the expiration date on the pended renewal to 7/5/2024 to issue as a Short-Term renewal','Bug','2024-03-05','Sandeep Gundreddy','Datafix','edw_core','tquote','expiration_dt','Updated expiration date for quote#HO100125881-02 as per the request to allow for short-term renewal','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29252/AD4899','Enhancements - NCRB additions into tauto_policy_coverage','Enhancement','2024-03-08','Architha Gudimalla','Addition','edw_core','tauto_policy_coverage','collision_ncrb_premium_amt','Created new column','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29252/AD4899','Enhancements - NCRB additions into tauto_policy_coverage','Enhancement','2024-03-08','Architha Gudimalla','Addition','edw_core','tauto_policy_coverage','otc_ncrb_premium_amt','Created new column','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29252/AD4899','Enhancements - NCRB additions into tquote_auto_policy_coverage','Enhancement','2024-03-08','Architha Gudimalla','Addition','edw_core','tquote_auto_policy_coverage','collision_ncrb_premium_amt','Created new column','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29252/AD4899','Enhancements - NCRB additions into tquote_auto_policy_coverage','Enhancement','2024-03-08','Architha Gudimalla','Addition','edw_core','tquote_auto_policy_coverage','otc_ncrb_premium_amt','Created new column','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29808/AD5333','Enhancements - Workflow step category update','Enhancement','2024-03-08','Architha Gudimalla','Datafix','edw_core','ttask_workflow_step','task_workflow_step_category_nm','Updated the category to show as Inspections for "Review Inspection Requirements"','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30157/AD5327','Enhancements - KPI additions into tbroker_summary','Enhancement','2024-03-08','Architha Gudimalla','Addition','edw_core','tbroker_summary','one_year_loss_ratio','Created new column','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30157/AD5327','Enhancements - KPI additions into tbroker_summary','Enhancement','2024-03-08','Architha Gudimalla','Addition','edw_core','tbroker_summary','one_year_loss_ratio_capped           ','Created new column','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30157/AD5327','Enhancements - KPI additions into tbroker_summary','Enhancement','2024-03-08','Architha Gudimalla','Addition','edw_core','tbroker_summary','one_year_non_cat_loss_ratio          ','Created new column','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30157/AD5327','Enhancements - KPI additions into tbroker_summary','Enhancement','2024-03-08','Architha Gudimalla','Addition','edw_core','tbroker_summary','one_year_non_cat_loss_ratio_capped   ','Created new column','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30157/AD5327','Enhancements - KPI additions into tbroker_summary','Enhancement','2024-03-08','Architha Gudimalla','Addition','edw_core','tbroker_summary','one_year_frequency ','Created new column','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30157/AD5327','Enhancements - KPI additions into tbroker_summary','Enhancement','2024-03-08','Architha Gudimalla','Addition','edw_core','tbroker_summary','one_year_non_cat_frequency           ','Created new column','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30157/AD5327','Enhancements - KPI additions into tbroker_summary','Enhancement','2024-03-08','Architha Gudimalla','Addition','edw_core','tbroker_summary','one_year_severity  ','Created new column','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30157/AD5327','Enhancements - KPI additions into tbroker_summary','Enhancement','2024-03-08','Architha Gudimalla','Addition','edw_core','tbroker_summary','one_year_non_cat_severity            ','Created new column','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30157/AD5327','Enhancements - KPI additions into tbroker_summary','Enhancement','2024-03-08','Architha Gudimalla','Addition','edw_core','tbroker_summary','three_year_loss_ratio                ','Created new column','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30157/AD5327','Enhancements - KPI additions into tbroker_summary','Enhancement','2024-03-08','Architha Gudimalla','Addition','edw_core','tbroker_summary','three_year_loss_ratio_capped         ','Created new column','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30157/AD5327','Enhancements - KPI additions into tbroker_summary','Enhancement','2024-03-08','Architha Gudimalla','Addition','edw_core','tbroker_summary','three_year_non_cat_loss_ratio        ','Created new column','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30157/AD5327','Enhancements - KPI additions into tbroker_summary','Enhancement','2024-03-08','Architha Gudimalla','Addition','edw_core','tbroker_summary','three_year_non_cat_loss_ratio_capped  ','Created new column','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30157/AD5327','Enhancements - KPI additions into tbroker_summary','Enhancement','2024-03-08','Architha Gudimalla','Addition','edw_core','tbroker_summary','three_year_frequency','Created new column','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30157/AD5327','Enhancements - KPI additions into tbroker_summary','Enhancement','2024-03-08','Architha Gudimalla','Addition','edw_core','tbroker_summary','three_year_non_cat_frequency          ','Created new column','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30157/AD5327','Enhancements - KPI additions into tbroker_summary','Enhancement','2024-03-08','Architha Gudimalla','Addition','edw_core','tbroker_summary','three_year_severity ','Created new column','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30157/AD5327','Enhancements - KPI additions into tbroker_summary','Enhancement','2024-03-08','Architha Gudimalla','Addition','edw_core','tbroker_summary','three_year_non_cat_severity  ','Created new column','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29830/AD5269','Enhancements - Add raterpipdiscount for Auto','Enhancement','2024-03-08','Rushin Shah','Addition','edw_core','tauto_policy_coverage','rater_pip_discount','Created new column','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29830/AD5269','Enhancements - Add raterpipdiscount for Auto','Enhancement','2024-03-08','Rushin Shah','Addition','edw_core','tquote_auto_policy_coverage','rater_pip_discount','Created new column','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29891/AD5267','Enhancements - Add inspection columns for Home','Enhancement','2024-03-08','Rushin Shah','Addition','edw_core','thome_coverage','waive_inspection_in','Created new column','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29891/AD5267','Enhancements - Add inspection columns for Home','Enhancement','2024-03-08','Rushin Shah','Addition','edw_core','thome_coverage','waive_inspection_reason','Created new column','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29891/AD5267','Enhancements - Add inspection columns for Home','Enhancement','2024-03-08','Rushin Shah','Addition','edw_core','thome_coverage',' inspection_note','Created new column','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29891/AD5267','Enhancements - Add inspection columns for Home','Enhancement','2024-03-08','Rushin Shah','Addition','edw_core','thome_coverage',' rms_reviewed_in','Created new column','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29891/AD5267','Enhancements - Add inspection columns for Home','Enhancement','2024-03-08','Rushin Shah','Addition','edw_core','tquote_home_coverage','waive_inspection_in','Created new column','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29891/AD5267','Enhancements - Add inspection columns for Home','Enhancement','2024-03-08','Rushin Shah','Addition','edw_core','tquote_home_coverage','waive_inspection_reason','Created new column','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29891/AD5267','Enhancements - Add inspection columns for Home','Enhancement','2024-03-08','Rushin Shah','Addition','edw_core','tquote_home_coverage',' inspection_note','Created new column','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29891/AD5267','Enhancements - Add inspection columns for Home','Enhancement','2024-03-08','Rushin Shah','Addition','edw_core','tquote_home_coverage',' rms_reviewed_in','Created new column','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29960/AD5266','Enhancements - Add 6 additional coverage columns for Home','Enhancement','2024-03-08','Rushin Shah','Addition','edw_core','thome_additional_coverage','fire_station_connected_fire_alarm_in','Created new column','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29960/AD5266','Enhancements - Add 6 additional coverage columns for Home','Enhancement','2024-03-08','Rushin Shah','Addition','edw_core','thome_additional_coverage','police_station_connected_burglar_alarm_in','Created new column','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29960/AD5266','Enhancements - Add 6 additional coverage columns for Home','Enhancement','2024-03-08','Rushin Shah','Addition','edw_core','thome_additional_coverage','local_fire_alarm_system_in','Created new column','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29960/AD5266','Enhancements - Add 6 additional coverage columns for Home','Enhancement','2024-03-08','Rushin Shah','Addition','edw_core','thome_additional_coverage','local_burglar_alarm_system_in','Created new column','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29960/AD5266','Enhancements - Add 6 additional coverage columns for Home','Enhancement','2024-03-08','Rushin Shah','Addition','edw_core','thome_additional_coverage','automatic_smoke_detectors_in','Created new column','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29960/AD5266','Enhancements - Add 6 additional coverage columns for Home','Enhancement','2024-03-08','Rushin Shah','Addition','edw_core','thome_additional_coverage','automatic_sprinkler_system','Created new column','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29960/AD5266','Enhancements - Add 6 additional coverage columns for Home','Enhancement','2024-03-08','Rushin Shah','Addition','edw_core','tquote_home_additional_coverage','fire_station_connected_fire_alarm_in','Created new column','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29960/AD5266','Enhancements - Add 6 additional coverage columns for Home','Enhancement','2024-03-08','Rushin Shah','Addition','edw_core','tquote_home_additional_coverage','police_station_connected_burglar_alarm_in','Created new column','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29960/AD5266','Enhancements - Add 6 additional coverage columns for Home','Enhancement','2024-03-08','Rushin Shah','Addition','edw_core','tquote_home_additional_coverage','local_fire_alarm_system_in','Created new column','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29960/AD5266','Enhancements - Add 6 additional coverage columns for Home','Enhancement','2024-03-08','Rushin Shah','Addition','edw_core','tquote_home_additional_coverage','local_burglar_alarm_system_in','Created new column','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29960/AD5266','Enhancements - Add 6 additional coverage columns for Home','Enhancement','2024-03-08','Rushin Shah','Addition','edw_core','tquote_home_additional_coverage','automatic_smoke_detectors_in','Created new column','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29960/AD5266','Enhancements - Add 6 additional coverage columns for Home','Enhancement','2024-03-08','Rushin Shah','Addition','edw_core','tquote_home_additional_coverage','automatic_sprinkler_system','Created new column','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI28488/AD4695','Most prior policy numbers in EDW','Bug','2024-03-08','Sandeep Gundreddy','Datafix','edw_core','tpolicy','prior_policy_no','This is a migration issue. Updated data in Metal and EDW. This is just a onetime update.','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI27073/AD4478','HO100262655 is missing prior policy no HO100206574','Bug','2024-03-08','Sandeep Gundreddy','Datafix','edw_core','tpolicy','prior_policy_no','This is a migration issue. Updated data in Metal and EDW. This is just a onetime update.','4','Yes','2024-03-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29693','Incorrect active vehicles','Bug','2024-03-08','Architha Gudimalla','Datafix','edw_core','tauto_vehicle_coverage','vehicle_deleted_in','This is a migration issue. Updated data in Metal and EDW. This is just a onetime update.','4','Yes','2024-03-11',getdate(),getdate());