-- tedw_release_summary
INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 03/18/2024 :</span>
<h4 style="margin-top: 0;">This release includes the following:</h4>
<ol>
    <li>Enhancements - 13
        <ul>
			<li>Integrated the following third party vendor report data into EDW </li>
                   1.Hazard Hub<br>
                   2.Aon CAT Score<br>
                   3.Guycarpenter<br>
                   4.CARFAX Mileage<br>
                   5.CARFAX Value<br>
                   6.MVR<br>
                   7.ISO Vehicle<br>
                   8.ISO Property<br>
                   9.NHTSA<br>
                   10.Transunion
			<li>Added oneshield_migrated_in column to tpolicy table</li>
			<li>Added party_subtype_role_nm column to tclaim_payment table</li>
			<li>Added broker_tier column to tbroker_commission table.Broker commisson data is loaded at the tier level</li>
		</ul>
    </li>
    <li>Bug tickets - 10
        <ul>
            <li>Fixed Auto issues related to duplicate vehicle rows for the same VIN and vehicle_coverage_sk=0 </li>     
			<li>Fixed stored procedure - "sp_claim_renewal_rating_auto_pel_api" to avoid displaying duplication of payment amounts in Metal</li>
			<li>Fixed data issue related to cat codes for OneShield claims in tclaim table</li>
			<li>Fixed migration data issue related to loss_of_use_option, protection_class,water_deductible thome_coverage table for a few policies</li> 
        </ul>
    </li>
</ol>
'
,'Yes'
,'2024-03-18'
,getdate()
,getdate()
)
;

-- tedw_release_note
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5374','Views for Vendor Reports','Enhancement','2024-03-15','Hernando Gonzalez','Addition','edw_core','vcarfaxmileage','','Carfax Mileage data is integrated into EDW. This view returns the data.','5','Yes','2024-03-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5374','Views for Vendor Reports','Enhancement','2024-03-15','Hernando Gonzalez','Addition','edw_core','vcarfaxvalue','','Carfax value data is integrated into EDW. This view returns the data.','5','Yes','2024-03-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5374','Views for Vendor Reports','Enhancement','2024-03-15','Hernando Gonzalez','Addition','edw_core','visovehicle','','ISO vehicle data is integrated into EDW. This view returns the data.','5','Yes','2024-03-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5374','Views for Vendor Reports','Enhancement','2024-03-15','Hernando Gonzalez','Addition','edw_core','visoproperty','','ISO property data is integrated into EDW. This view returns the data.','5','Yes','2024-03-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5374','Views for Vendor Reports','Enhancement','2024-03-15','Hernando Gonzalez','Addition','edw_core','vmvr','','MVR data is integrated into EDW. This view returns the data.','5','Yes','2024-03-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5374','Views for Vendor Reports','Enhancement','2024-03-15','Hernando Gonzalez','Addition','edw_core','vnhtsa','','NHTSA data is integrated into EDW. This view returns the data.','5','Yes','2024-03-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5374','Views for Vendor Reports','Enhancement','2024-03-15','Hernando Gonzalez','Addition','edw_core','vtransunion','','Transunion data is integrated into EDW. This view returns the data.','5','Yes','2024-03-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5374','Views for Vendor Reports','Enhancement','2024-03-15','Hernando Gonzalez','Addition','edw_core','vguycarpenter','','GuyCarpenter data is integrated into EDW. This view returns the data.','5','Yes','2024-03-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5374','Views for Vendor Reports','Enhancement','2024-03-15','Hernando Gonzalez','Addition','edw_core','vhazardhub','','HazardHub data is integrated into EDW. This view returns the data.','5','Yes','2024-03-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5374','Views for Vendor Reports','Enhancement','2024-03-15','Hernando Gonzalez','Addition','edw_core','vaoncatscore','','Aon CAT score data is integrated into EDW. This view returns the data.','5','Yes','2024-03-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-30234/AD5326','Enhancements - Add oneshield_migrated_in column to tpolicy table','Enhancement','2024-03-15','Yunus Mohammed','Addition','edw_core','tpolicy','oneshield_migrated_in','Created new column','5','Yes','2024-03-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5228','Enhancement : Add party_subtype_role_nm to tclaim_payment table','Enhancement','2024-03-15','Yunus Mohammed','Addition','edw_core','tclaim_payment','party_subtype_role_nm','Created new column','5','Yes','2024-03-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5127','Addition of broker_tier column','Enhancement','2024-03-15','Rushin Shah','Addition','edw_core','tbroker_commission','broker_tier','Created new column. Broker commisson data is loaded at the tier level .','5','Yes','2024-03-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29774/AD5361','Claim payments getting duplicated for some claims','Bug','2024-03-15','Yunus Mohammed','Modification','edw_integration','claim_renewal_rating_auto_pel_api','','This is a display issue in Metal where eBao  payments are duplicated due to a bug in stored procedure that returns eBao data from EDW.  Fixed the logic in the stored procedure to return correct payment amounts.','5','Yes','2024-03-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30356/AD5392','Update cat codes for OS claims','Bug','2024-03-15','Yunus Mohammed','Modification','edw_core','tclaim','catastrophe_sk','This is a migration issue. Updated data in EDW for OS claims. This is just a onetime update.','5','Yes','2024-03-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29703/AD5400','4 policies whose cov D needs to be updated (HO100094593-02, HO100105931-02, HO100126711-02, HO100142448-02)','Bug','2024-03-15','Rushin Shah','Datafix','edw_core','thome_coverage','loss_of_use_option','This is a migration issue. Updated data in Metal and EDW. This is just a onetime update.','5','Yes','2024-03-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI27843/AD5354','Update Water deductible for one policy HO100027518-03','Bug','2024-03-15','Rushin Shah','Datafix','edw_core','thome_coverage','water_deductible','This is a migration issue. Updated data in Metal and EDW. This is just a onetime update.','5','Yes','2024-03-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI27688/AD5364','Update protection_class for 1 policy (HO127055264236-01)','Bug','2024-03-15','Rushin Shah','Datafix','edw_core','thome_coverage','protection_class','This is a migration issue. Updated data in Metal and EDW. This is just a onetime update.','5','Yes','2024-03-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD3916','Multiple records for the same vehicle on the same policy term in tauto_vehicle','Bug','2024-03-15','Sandeep Gundreddy','Datafix','edw_core','tauto_vehicle','',' Updated data in Metal and EDW. This is just a onetime update. There are still small number of policies with the issue due to bad data in AV2 but majority are fixed.','5','Yes','2024-03-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI28761/AD4751','Missing auto garaging locations','Bug','2024-03-15','Sandeep Gundreddy','Datafix','edw_core','tauto_vehicle_coverage','','Updated data in Metal and EDW. This is just a onetime update. There are still small number of policies with the issue due to bad data in AV2 but majority are fixed.','5','Yes','2024-03-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-28950/AD4816','Vehicle Premium not flowing through correctly from tpolicy_transaction to tauto_vehicle_coverage','Bug','2024-03-15','Sandeep Gundreddy','Datafix','edw_core','tauto_vehicle_coverage','','Updated data in Metal and EDW. This is just a onetime update. There are still small number of policies with the issue due to bad data in AV2 but majority are fixed.','5','Yes','2024-03-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29907','4465 Records where vehicle_coverage_sk is null (ISS Auto)','Bug','2024-03-15','Sandeep Gundreddy','Datafix','edw_core','tauto_vehicle_coverage','','Updated data in Metal and EDW. This is just a onetime update. There are still small number of policies with the issue due to bad data in AV2 but majority are fixed.','5','Yes','2024-03-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29776','tpolicy_transaction records for auto with 0 vehicle_coverage_sks','Bug','2024-03-15','Sandeep Gundreddy','Datafix','edw_core','tauto_vehicle_coverage','','Updated data in Metal and EDW. This is just a onetime update. There are still small number of policies with the issue due to bad data in AV2 but majority are fixed.','5','Yes','2024-03-18',getdate(),getdate());