-- tedw_release_summary
INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 03/25/2024 :</span>
<h4 style="margin-top: 0;">This release includes the following:</h4>
<ol>
    <li>Enhancements - 11
        <ul>
			<li>Workday Enhancement - Added claim_party_subtype_nm to workday payments table</li>
			<li>Workday Enhancement - Updated written premium file to capture aslob for Condo policies; updated ITD claims file with logic updated for month_end column; updated ceded premium file to capture Condo policies.</li>
            <li>Datamart Enhancement - Added commission_amt column to tdaily_inforce_policy, titem_inforce, tinternal_coverage_inforce, tpolicy_transaction_summary tables</li>
			<li>Datamart Enhancement - Updated logic for one_year_non_cat_earned_net_premium_amt and three_year_non_cat_earned_net_premium_amt columns in tbroker_summary table to exclude these primary coverages - Hurricane,Wildfire,Wind_Hail</li>
			<li>Datamart Enhancement - Updated logic for renewal_sixty_day_written_premium_amt, renewal_sixty_day_commission_amt, renewal_sixty_day_tiv_amt, renewal_sixty_day_cova_amt and renewal_accepted_price_sqft columns in trenewal_summary table to show data in this column as the renewal date instead of 60 days for policies that were renewed after 60 days of expiry</li>
			<li>Added tnote table in EDW to capture notes entered in Metal</li>
			<li>Added collection_class_type_sk and quote_collection_class_type_sk to tpolicy_transaction and tquote_transaction tables respectively. This gives the ability to link collections policies premium to limits.</li>  
			<li>Added class_deleted_in column to tcollection_class_type table</li>
			<li>Added close_reason_desc column to tquote table</li>
			<li>Updated prior policy number for cancel rewrites issued in Metal and OneShield migrated policies</li>
			<li>Added rewritten_in column to tpolicy table</li>
		</ul>
    </li>
    <li>Bug tickets - 5
        <ul>
			<li>Standardized coverage names as per finance teams request(Service Line Admitted to Service Line; Cyber Liability to Cyber Protection; System Protection to Systems Protection)</li>
			<li>44 policies were not migrated from AV2 to Metal due to bad data in AV2. All these policies were rekeyed in Metal by VC team. Transaction issue date were updated to the original transaction issue date.</li>
			<li>Updated auto_complete_coverage_in to NULL for a large number of auto policies</li>
			<li>Standarized values for rms_review_in</li> 			
        </ul>
    </li>
</ol>
'
,'Yes'
,'2024-03-25'
,getdate()
,getdate()
)
;

-- tedw_release_note
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30254','Standarize values for rms_review_in','Bug','2024-03-22','Sandeep Gundreddy','Datafix','edw_core','thome_coverage','rms_reviewed_in','This is a migration issue. Updated true to Yes and false to No  in Metal and EDW. This is just a onetime update.','6','Yes','2024-03-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30457','why does rms_reviewed_in = true for HO100186118-01 when its blank in metal?','Bug','2024-03-22','Sandeep Gundreddy','Datafix','edw_core','thome_coverage','rms_reviewed_in','This is a migration issue. Updated true to Yes and false to No  in Metal and EDW. This is just a onetime update.','6','Yes','2024-03-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30430','update auto_complete_coverage_in to NULL for a large number of auto policies','Bug','2024-03-22','Sandeep Gundreddy','Datafix','edw_core','tauto_policy_coverage','auto_complete_coverage_in','Updated data in Metal and EDW. This is just a onetime update as per Product teams request. Please refer to the ticket for more details.','6','Yes','2024-03-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-30311/AD5464','Datamart Enhancement - tdaily_inforce_policy - add commission_amt','Enhancement','2024-03-22','Architha Gudimalla','Addition','edw_core','tdaily_inforce_policy','commission_amt','Created new column','6','Yes','2024-03-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-30311/AD5464','Datamart Enhancement - titem_inforce - add commission_amt','Enhancement','2024-03-22','Architha Gudimalla','Addition','edw_core','titem_inforce','commission_amt','Created new column','6','Yes','2024-03-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-30311/AD5464','Datamart Enhancement - tinternal_coverage_inforce - add commission_amt','Enhancement','2024-03-22','Architha Gudimalla','Addition','edw_core','tinternal_coverage_inforce','commission_amt','Created new column','6','Yes','2024-03-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-30311/AD5464','Datamart Enhancement - tpolicy_transaction_summary - add commission_amt','Enhancement','2024-03-22','Architha Gudimalla','Addition','edw_core','tpolicy_transaction_summary','commission_amt','Created new column','6','Yes','2024-03-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-30309/AD5438','Datamart Enhancement - tbroker_summary','Enhancement','2024-03-22','Architha Gudimalla','Modification','edw_core','tbroker_summary','one_year_non_cat_earned_net_premium_amt','Updated logic to exclude these primary coverages - Hurricane,Wildfire,Wind_Hail','6','Yes','2024-03-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-30309/AD5438','Datamart Enhancement - tbroker_summary','Enhancement','2024-03-22','Architha Gudimalla','Modification','edw_core','tbroker_summary','three_year_non_cat_earned_net_premium_amt','Updated logic to exclude these primary coverages - Hurricane,Wildfire,Wind_Hail','6','Yes','2024-03-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-30415\AD5108','Addition of tnote table in EDW','Enhancement','2024-03-22','Yunus Mohammed','Addition','edw_core','tnote','','Addition of tnote table in EDW to capture notes entered in Metal','6','Yes','2024-03-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30494/AD5469','Enhancement - Add close_reason_desc to tquote','Enhancement','2024-03-22','Rushin Shah','Addition','edw_core','tquote','close_reason_desc','Created new column','6','Yes','2024-03-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5410','Workday Enhancement - Add claim_party_subtype_nm to workday payments table','Enhancement','2024-03-22','Yunus Mohammed','Addition','edw_integration','claim_workday_payment_feed',' party_subtype_role_nm','Created new column','6','Yes','2024-03-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5230','Workday Enhancement - Update WD Written Prem, Ceded Prem and ITD Reserves file','Enhancement','2023-03-22','Yunus Mohammed','Modification','edw_integration','policy_workday_written_premium_feed','aslob','Updated written premium file to capture aslob for Condo policies.  Updated ITD claims file with logic updated for month_end column.  Updated ceded premium file to capture Condo policies.','6','Yes','2024-03-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5212','Enhancement -  tpolicy_transaction - Add collection_class_type_sk','Enhancement','2024-03-22','Sandeep Gundreddy','Addition','edw_core','tpolicy_transaction','collection_class_type_sk','Created new column.  This gives the ability to link collection premium to collection limits.','6','Yes','2024-03-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5212','Enhancement - tquote_transaction - Add quote_collection_class_type_sk','Enhancement','2024-03-22','Sandeep Gundreddy','Addition','edw_core','tquote_transaction','quote_collection_class_type_sk','Created new column.  This gives the ability to link collection premium to collection limits.','6','Yes','2024-03-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5302','Standardized coverage names as per finance teams request','Bug','2024-03-22','Sandeep Gundreddy','Datafix','edw_core','tinternal_coverage','internal_coverage_cd','Updated data in Metal and EDW. This is just a onetime update as per Finance teams request. Please refer to the ticket for more details.','6','Yes','2024-03-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30284/AD5411','Enhancement - tpolicy - Add rewritten_in','Enhancement','2024-03-22','Sandeep Gundreddy','Addition','edw_core','tpolicy','rewritten_in','Created new column and updated logic to load into prior_policy_no for cancel rewrites','6','Yes','2024-03-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5446','Update prior_policy_no for OneShield Migrated Policies','Enhancement','2024-03-22','Yunus Mohammed','Datafix','edw_core','tpolicy','prior_policy_no','Updated prior_policy_no for AV2 policies migrated from OneShield.  This is just a onetime update.','6','Yes','2024-03-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI28125/AD4790','Metal rekey project to enter 44 missing policies','Bug','2024-03-22','Sandeep Gundreddy','Datafix','edw_core','tpolicy','','44 policies were not migrated from AV2 to Metal due to bad data in AV2.  All these policies were rekeyed in Metal by VC team.  Transaction issue date were updated to the original transaction issue date.','6','Yes','2024-03-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-30170/AD5485','Datamart Update - trenewal_summary','Enhancement','2024-03-22','Architha Gudimalla','Modification','edw_core','trenewal_summary','renewal_sixty_day_written_premium_amt','Updated logic to show data in this column as the renewal date instead of 60 days for policies that were renewed after 60 days of expiry','6','Yes','2024-03-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-30170/AD5485','Datamart Update - trenewal_summary','Enhancement','2024-03-22','Architha Gudimalla','Modification','edw_core','trenewal_summary','renewal_sixty_day_commission_amt','Updated logic to show data in this column as the renewal date instead of 60 days for policies that were renewed after 60 days of expiry','6','Yes','2024-03-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-30170/AD5485','Datamart Update - trenewal_summary','Enhancement','2024-03-22','Architha Gudimalla','Modification','edw_core','trenewal_summary','renewal_sixty_day_tiv_amt','Updated logic to show data in this column as the renewal date instead of 60 days for policies that were renewed after 60 days of expiry','6','Yes','2024-03-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-30170/AD5485','Datamart Update - trenewal_summary','Enhancement','2024-03-22','Architha Gudimalla','Modification','edw_core','trenewal_summary','renewal_sixty_day_cova_amt','Updated logic to show data in this column as the renewal date instead of 60 days for policies that were renewed after 60 days of expiry','6','Yes','2024-03-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-30170/AD5485','Datamart Update - trenewal_summary','Enhancement','2024-03-22','Architha Gudimalla','Modification','edw_core','trenewal_summary','renewal_accepted_price_sqft','Updated logic to show data in this column as the renewal date instead of 60 days for policies that were renewed after 60 days of expiry','6','Yes','2024-03-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5129','Enhancement - tcollection_class_type - add class_deteled_in','Enhancement','2024-03-22','Architha Gudimalla','Addition','edw_core','tcollection_class_type','class_deleted_in','Created new column','6','Yes','2024-03-25',getdate(),getdate());
