-- tedw_release_summary
INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 04/08/2024 :</span>
<h4 style="margin-top: 0;">This release includes the following:</h4>
<ol>
    <li>Enhancements - 9
        <ul>
			<li>Added Metal 04/06 release related 78 new columns for Auto</li>
			<li>Added Metal 04/06 release related 80 new columns for PEL</li>
			<li>Enhancement - Added total of 64 Auto Premium adjustments columns into tauto_vehicle_coverage and tquote_auto_vehicle_coverage (backfill will happen next weekend)</li>
			<li>Added tauto_vehicle_coverage_rapa and tquote_auto_vehicle_coverage_rapa table in EDW to capture RAPA fields related to Auto</li>
			<li>Added tpel_vehicle_rapa and tquote_pel_vehicle_rapa table in EDW to capture RAPA fields related to PEL</li>
			<li>Backfill of motor home class field for 22 auto policies (as per product team request)</li>
			<li>Updated stored procedure logic to create the tbroker_vault_team table from CompanyTeamBrokerage and CompanyTeamMember tables</li>
			<li>Datamart Enhancement - Updated logic for collection policies to only include those classes where collection_class_deleted_in = No</li>
			<li>Enhancement - Added collection_class_type_sk column to tinternal_coverage_inforce and tinternal_coverage_summary tables</li>
		</ul>
    </li>
    <li>Bug tickets - 5
        <ul>
			<li>Updated logic to fix policies that are missing vehicle_coverage_sk</li>
			<li>Updated logic to default to 0.2 for locations having loss_of_use_option as Reasonable and Necessary Expenses</li>
			<li>Updated transaction issued date for 2 policies (out of 44 policies rekeyed by VC team) to its original AV2 transaction issued date.</li>			
        </ul>
    </li>
</ol>
'
,'Yes'
,'2024-04-08'
,getdate()
,getdate()
)
;

-- tedw_release_note

INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30306','HO100126564-02 - premium issued at 0 ','Bug','2024-03-28','Sandeep Gundreddy','Datafix','edw_core','tpolicy_transaction','','Isolated issue in Metal. Policies issued with $0 premium.Impacted 3 policies. Updated their status to In Progress in Metal so VC can reissue the transactions. EX100043758-03, AU100140647-03, HO100126564-02','7','Yes','2024-04-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30687','RN issued with $0 premium-AU100140647-03','Bug','2024-03-28','Sandeep Gundreddy','Datafix','edw_core','tpolicy_transaction','','Isolated issue in Metal. Policies issued with $0 premium.Impacted 3 policies. Updated their status to In Progress in Metal so VC can reissue the transactions. EX100043758-03, AU100140647-03, HO100126564-02','7','Yes','2024-04-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30789','44 missing policies in the Bind Board','Bug','2024-04-03','Sandeep Gundreddy','Datafix','edw_core','tpolicy_history','transaction_ts','Out of 44 policies rekeyed in Metal, the following 2 policies transaction issued date is not updated to its original AV2 transaction issued date.  HO100111310,AUX10003684-01.  Updated in Metal and EDW. This is just a onetime update.','7','Yes','2024-04-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5431','Auto - Metal 04/06 release RAPA related table','Enhancement','2024-04-05','Hernando Gonzalez','Addition','edw_core','tquote_auto_vehicle_coverage_rapa','','Addition of tquote_auto_vehicle_coverage_rapa table in EDW to capture RAPA related fields','7','Yes','2024-04-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5431','Auto - Metal 04/06 release RAPA related table','Enhancement','2024-04-05','Hernando Gonzalez','Addition','edw_core','tauto_vehicle_coverage_rapa','','Addition of tauto_vehicle_coverage_rapa table in EDW to capture RAPA related fields','7','Yes','2024-04-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5434','PEL- Metal 04/06 release RAPA related table','Enhancement','2024-04-05','Hernando Gonzalez','Addition','edw_core','tquote_pel_vehicle_rapa','','Addition of tquote_pel_vehicle_rapa table in EDW to capture RAPA related fields','7','Yes','2024-04-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5434','PEL- Metal 04/06 release RAPA related table','Enhancement','2024-04-05','Hernando Gonzalez','Addition','edw_core','tpel_vehicle_rapa','','Addition of tpel_vehicle_rapa table in EDW to capture RAPA related fields','7','Yes','2024-04-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5571','Auto - Metal 04/06 release related columns','Enhancement','2024-04-05','Alberto Valbuena','Addition','edw_core','tauto_vehicle','','Created 5 new columns','7','Yes','2024-04-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5571','Auto - Metal 04/06 release related columns','Enhancement','2024-04-05','Alberto Valbuena','Addition','edw_core','tauto_vehicle_coverage','','Created 31 new columns','7','Yes','2024-04-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5571','Auto - Metal 04/06 release related columns','Enhancement','2024-04-05','Alberto Valbuena','Addition','edw_core','tauto_policy_coverage','','Created 3 new columns','7','Yes','2024-04-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5571','Auto - Metal 04/06 release related columns','Enhancement','2024-04-05','Alberto Valbuena','Addition','edw_core','tquote_auto_vehicle','','Created 5 new columns','7','Yes','2024-04-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5571','Auto - Metal 04/06 release related columns','Enhancement','2024-04-05','Alberto Valbuena','Addition','edw_core','tquote_auto_vehicle_coverage','','Created 31 new columns','7','Yes','2024-04-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5571','Auto - Metal 04/06 release related columns','Enhancement','2024-04-05','Alberto Valbuena','Addition','edw_core','tquote_auto_policy_coverage','','Created 3 new columns','7','Yes','2024-04-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5572','PEL - Metal 04/06 release related columns','Enhancement','2024-04-05','Hernando Gonzalez','Addition','edw_core','tpel_vehicle','','Created 40 new columns','7','Yes','2024-04-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5572','PEL - Metal 04/06 release related columns','Enhancement','2024-04-05','Hernando Gonzalez','Addition','edw_core','tquote_pel_vehicle','','Created 40 new columns','7','Yes','2024-04-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI28761/AD4751','Missing auto garaging locations','Bug','2024-04-05','Architha Gudimalla','Datafix','edw_core','tpolicy_transaction','vehicle_coverage_sk','Updated logic to fix policies that are missing vehicle_coverage_sk','7','Yes','2024-04-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5412','Backfill of motor home class field (as per product team request)','Enhancement','2024-04-05','Rushin Shah','Datafix','edw_core','tauto_vehicle_coverage','','Updated motor home class for 22 policies in EDW. This is just a one time update.','7','Yes','2024-04-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5140','Enhancements - Auto Premium adjustments into tauto_vehicle_coverage','Enhancement','2024-04-05','Alberto Valbuena','Addition','edw_core','tauto_vehicle_coverage','','Created 32 new columns (backfill will happen next week)','7','Yes','2024-04-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5140','Enhancements - Auto Premium adjustments into tquote_auto_vehicle_coverage','Enhancement','2024-04-05','Alberto Valbuena','Addition','edw_core','tquote_auto_vehicle_coverage','','Created 32 new columns (backfill will happen next week)','7','Yes','2024-04-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5374','Views on Vendor report','Enhancement','2024-04-05','','Addition','edw_core','Vclueproperty','','Clue Property data is integrated into EDW. This view returns the data.','7','Yes','2024-04-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5406','Updated stored procedure logic to create the “tbroker_vault_team” table','Enhancement','2024-04-05','Rushin Shah','Modification','edw_core','tbroker_vault_team','','Modified existing stored procedure to get data from CompanyTeamBrokerage and CompanyTeamMember tables','7','Yes','2024-04-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5212','Datamart Enhancements - tinternal_coverage_inforce - add collection_class_type_sk','Enhancement','2024-04-05','Architha Gudimalla','Addition','edw_core','tinternal_coverage_inforce','collection_class_type_sk','Created new column','7','Yes','2024-04-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5212','Datamart Enhancements - tinternal_coverage_summary - add collection_class_type_sk','Enhancement','2024-04-05','Architha Gudimalla','Addition','edw_core','tinternal_coverage_summary','collection_class_type_sk','Created new column','7','Yes','2024-04-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5512','Datamart Enhancements - tinternal_coverage_inforce','Enhancement','2024-04-05','Architha Gudimalla','Modification','edw_core','tinternal_coverage_inforce','','Updated logic for collection policies to only include those classes where collection_class_deleted_in = No','7','Yes','2024-04-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5413','Updated logic for thome_coverage.loss_of_use_derived_pc','Bug','2024-04-05','Architha Gudimalla','Modification','edw_core','thome_coverage','loss_of_use_derived_pc','Updated logic to default to 0.2 for locations having loss_of_use_option as Reasonable and Necessary Expenses- 12 months','7','Yes','2024-04-08',getdate(),getdate());
