-- tedw_release_summary
INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 04/22/2024 :</span>
<h4 style="margin-top: 0;">This release includes the following:</h4>
<ol>
    <li>Enhancements - 3
        <ul>
			<li>Integrated Broker Parent-Child Relationship data into EDW</li>
			<li>Integrated UW Referral Message data into EDW for policies and quotes</li>
			<li>Created an automated process to trigger an email whenever new coverage codes are added to Metal. This will help Workday reporting and IVANS feed</li>
		</ul>
    </li>
    <li>Bug tickets - 9
        <ul>
            <li>AU limit columns were storing metal back end values, these are now updated to show the actual metal front end display values</li>	
			<li>Fixed isloated issues related to prior_policy_no </li>
			<li>Updated prior_policy_no to null when prior_policy_no is same as prior_term_policy_no (for 14 policies) and when the product type of prior policy is different from the current policy (for 4 policies)</li>
		</ul>
    </li>
</ol>
'
,'Yes'
,'2024-04-22'
,getdate()
,getdate()
)
;

-- tedw_release_note

INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30811','prior_policy_no fix','Bug','2024-04-19','Architha Gudimalla','Datafix','edw_core','tpolicy','prior_policy_no','Removed prior_policy_no for AU100073742-01','8','Yes','2024-04-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30813','prior_policy_no fix','Bug','2024-04-19','Architha Gudimalla','Datafix','edw_core','tpolicy','prior_policy_no','Fixed prior_policy_no for EX100197392-02','8','Yes','2024-04-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30814','prior_policy_no fix','Bug','2024-04-19','Architha Gudimalla','Datafix','edw_core','tpolicy','prior_policy_no','Fixed prior_policy_no for HO100033099-01','8','Yes','2024-04-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30719/AD5584','prior_policy_no fix','Bug','2024-04-19','Architha Gudimalla','Datafix','edw_core','tpolicy','prior_policy_no','Updated prior_policy_no to null when the product type of prior policy is different from the current policy. Updated for policies -  AU100148267-01, EX100202768-03, EX100266882-03, CO100243128-02','8','Yes','2024-04-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30682','prior_policy_no fix','Bug','2024-04-19','Architha Gudimalla','Datafix','edw_core','tpolicy','prior_policy_no','Updated prior_policy_no to null when prior_policy_no is same as prior_term_policy_no for 14 policies','8','Yes','2024-04-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5316','Integrate Broker Relation Data Into EDW','Enhancement','2024-04-19','Yunus Mohammed','Addition','edw_core','tbroker_relation','','Addition of tbroker_relation table in EDW','8','Yes','2024-04-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5667','Trigger an email when a new internal_coverage_cd is added to tinternal_coverage table','Enhancement','2024-04-19','Alberto Valbuena','Addition','edw_core','','','Created a python script to trigger an email when new internal_coverage_cd is added to tinternal_coverage table.  This will help the Finance and IVANS feed.','8','Yes','2024-04-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5109','Integrate UW Referral Message Into EDW','Enhancement','2024-04-19','Yunus Mohammed','Addition','edw_core','tpolicy_referral_message','','Addition of tpolicy_referral_message table in EDW','8','Yes','2024-04-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5109','Integrate UW Referral Message Into EDW','Enhancement','2024-04-19','Yunus Mohammed','Addition','edw_core','tquote_referral_message','','Addition of tquote_referral_message table in EDW','8','Yes','2024-04-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI31032','Policy Number: EX100143167-03- For some reason this renewal premium is showing $0.','Bug','2024-04-19','Sandeep Gundreddy','Datafix','edw_core','tpolicy_transaction','','Isolated issue in Metal. Policies issued with $0 premium.Impacted 1 policy. Updated their status to In Progress in Metal so VC can reissue the transactions.  EX100143167-03','8','Yes','2024-04-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI31234','Missing garaging zip - AU100031429','Bug','2024-04-19','Architha Gudimalla','Datafix','edw_core','tauto_garage_location','garage_address_zip_code','Policy garage is issued with incorrect zip and is now updated to 34683','8','Yes','2024-04-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI31236','AU100100293: Garaging location does not look right (need for reporting)','Bug','2024-04-19','Architha Gudimalla','Datafix','edw_core','tauto_garage_location','','Telluride garage location is removed','8','Yes','2024-04-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30050','Auto policy limits','Bug','2024-04-19','Architha Gudimalla','Datafix','edw_core','tauto_policy_coverage','','AU limit columns were storing metal back end values, these are now updated to show the actual metal front end display values','8','Yes','2024-04-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30050','Auto policy limits','Bug','2024-04-19','Architha Gudimalla','Datafix','edw_core','tquote_auto_policy_coverage','','AU limit columns were storing metal back end values, these are now updated to show the actual metal front end display values','8','Yes','2024-04-22',getdate(),getdate());