-- tedw_release_summary
INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 05/06/2024 :</span>
<h4 style="margin-top: 0;">This release includes the following:</h4>
<ol>
    <li>Enhancements - 3
        <ul>
			<li>Added Metal 05/04 release related 29 new columns for PEL</li>
			<li>Added broker_tier column to tbroker table</li>
			<li>Datamart Enhancement - Added expiring_mid_term_endorsement_premium_amt, expiring_price_sqft, issued_price_sqft, renewal_offered_price_sqft, cancellation_reason_desc columns to trenewal_summary table</li>
		</ul>
    </li>
    <li>Bug tickets - 19
        <ul>
			<li>AV2 to Metal Data migration cleanup. Following are the fields that were fixed (by comparing AV2 to Metal data) for accurate reporting and facilitate claims, renewal & endorsement processing.</li> 
            1) WildfireDeductibleManual<br>
            2) BasicOrAddedFirstPartyBenefit<br>
            3) WorkLossBenefit<br>
            4) UMLimit
			<li>Moved policies from one account to another for 10 accounts</li>
			<li>Updated total finished square feet for 23 policies</li>
			<li>Updated expiration date for 4 renewal quotes</li>
			<li>Deleted 2 renewal quotes that were generated in error</li>
			<li>Updated policy attributes for 5 policies as per VC team so that it can be issued</li>
			<li>Updated logic of ttask table to exclude commercial lines</li>
			<li>Updated logic for rewritten_in column from tpolicy table</li>
			<li>Updated logic for assigned_to_nm column from ttask table</li>			
        </ul>
    </li>
</ol>
'
,'Yes'
,'2024-05-06'
,getdate()
,getdate()
)
;

-- tedw_release_note

INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30580','Need to amend renewal expiration dates','Bug','2024-03-26','Sandeep Gundreddy','Datafix','edw_core','tquote','','Updated expiration date for 3 renewal quotes as per the request.HO100155316-02, CO100156369-02, EX100155800-02','9','Yes','2024-05-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29203','2 Different accounts for the same insured - Accounts need to be combined','Bug','2024-04-02','Sandeep Gundreddy','Datafix','edw_core','tpolicy','','Moved policies from customerid 1234583441 to 1234636310. Data is udpated in Metal and EDW. This is just a onetime update as per VC team request.','9','Yes','2024-05-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30547','Customer profile merge ','Bug','2024-04-02','Sandeep Gundreddy','Datafix','edw_core','tpolicy','','Moved policies from customerid 1234586158 to 1234521919. Data is updated in Metal and EDW. This is just a onetime update as per VC team request.','9','Yes','2024-05-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29258','Please combine the accounts for policies EX100040216-03 and HO100262831-04','Bug','2024-04-02','Sandeep Gundreddy','Datafix','edw_core','tpolicy','','Moved policies from customerid 1234520509 to 1234641784. Data is updated in Metal and EDW. This is just a onetime update as per VC team request.','9','Yes','2024-05-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI28854','Combine accounts - Sheryl Sample','Bug','2024-04-02','Sandeep Gundreddy','Datafix','edw_core','tpolicy','','Moved policies from one account to another account for the following policies. Data is updated in Metal and EDW. This is just a onetime update as per VC team request. 1234511498 to 1234638811; 1234550866 to 1234643348; 1234581343 to 1234637453; 1234621646 to 1234642443; 1234633556 to 1234612430; 1234576692,1234572014 to 1234576699','9','Yes','2024-05-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30580','Need to amend renewal expiration dates','Bug','2024-04-03','Sandeep Gundreddy','Datafix','edw_core','tquote','','Updated expiration date for renewal quote as per the request. EX100231836-02','9','Yes','2024-05-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29735','Future renewals with renewal tasks','Bug','2024-04-03','Sandeep Gundreddy','Datafix','edw_core','tquote','','Deleted 2 renewal quotes in Metal and EDW that were generated in error as per the request. EX100194946-02, HO100014167-01','9','Yes','2024-05-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI31032','Policy Number: EX100143167-03- For some reason this renewal premium is showing $0.','Bug','2024-04-12','Sandeep Gundreddy','Datafix','edw_core','tpolicy_transaction','','Isolated issue in Metal. Policies issued with $0 premium.Impacted 1 policy. Updated their status to In Progress in Metal so VC can reissue the transactions.  EX100143167-03','9','Yes','2024-05-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI31065','Migration of Policy and RN term error - HO100248510-06','Bug','2024-04-29','Sandeep Gundreddy','Datafix','edw_core','tpolicy_transaction','','Renewal policy HO100248510-06 created in error in AV2 and migrated to Metal.  As per the request from VC policy HO100248510-06 was deleted so that VC can process the renewal for HO100248510-05','9','Yes','2024-05-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-31515/AD5903','Two policies in a Pending Non-Renewal status in Metal have a "No" on the "pending_non_renewal_in" flag.','Bug','2024-05-03','Yunus Mohammed','Datafix','edw_core','tpolicy','pending_non_renewal_in','Fixed procedure to resolve the issue.','9','Yes','2024-05-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI31485','Policy is in Majesco with incorrect effective dates CO100100540-02','Bug','2024-05-03','Sandeep Gundreddy','Datafix','edw_core','tpolicy','','Renewal policy CO100100540-02 created with incorrect effectivedate-20221119 in AV2 and migrated to Metal.  As per the request from billing team updated policy effective date to 20231119 in Metal and EDW.','9','Yes','2024-05-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-31477/AD5906','ttask includes commercial line policies','Bug','2024-05-03','Architha Gudimalla','Datafix','edw_core','ttask','','Updated the logic in the store procedure to exclude commercial lines','9','Yes','2024-05-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-31232/AD5823','Enhancement - trenewal_summary - addition of new columns','Enhancement','2024-05-03','Architha Gudimalla','Addition','edw_core','trenewal_summary','expiring_mid_term_endorsement_premium_amt','Created new column','9','Yes','2024-05-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-31232/AD5823','Enhancement - trenewal_summary - addition of new columns','Enhancement','2024-05-03','Architha Gudimalla','Addition','edw_core','trenewal_summary','expiring_price_sqft','Created new column','9','Yes','2024-05-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-31232/AD5823','Enhancement - trenewal_summary - addition of new columns','Enhancement','2024-05-03','Architha Gudimalla','Addition','edw_core','trenewal_summary','issued_price_sqft','Created new column','9','Yes','2024-05-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-31232/AD5823','Enhancement - trenewal_summary - addition of new columns','Enhancement','2024-05-03','Architha Gudimalla','Addition','edw_core','trenewal_summary','renewal_offered_price_sqft','Created new column','9','Yes','2024-05-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-31232/AD5823','Enhancement - trenewal_summary - addition of new columns','Enhancement','2024-05-03','Architha Gudimalla','Addition','edw_core','trenewal_summary','cancellation_reason_desc','Created new column','9','Yes','2024-05-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-28583/VI-30118/VI-29995','Auto - missing Basic Or Added First Party Benefit','Bug','2024-05-03','Architha Gudimalla','Datafix','edw_core','tauto_policy_coverage','basic_or_added_first_party_benefit','This is a migration issue. Updated BasicOrAddedFirstPartyBenefit in Metal and EDW. This is just a onetime update','9','Yes','2024-05-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-26371/VI-29995','Auto - missing Work Loss Benefit','Bug','2024-05-03','Architha Gudimalla','Datafix','edw_core','tauto_policy_coverage','work_loss_benefit_limit_amt','This is a migration issue. Updated WorkLossBenefit in Metal and EDW. This is just a onetime update','9','Yes','2024-05-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-22224/VI-30012/VI-30050','Auto - missing UMLimit','Bug','2024-05-03','Architha Gudimalla','Datafix','edw_core','tauto_policy_coverage','uninsured_motorist_limit_amt','This is a migration issue. Updated UMLimit in Metal and EDW. This is just a onetime update','9','Yes','2024-05-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-30853','tpolicy - Missing rewritten_in','Bug','2024-05-03','Architha Gudimalla','Datafix','edw_core','tpolicy','rewritten_in','Fixed rewritten_in EDW. This is just a onetime update','9','Yes','2024-05-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-30736','ttask - Incorrect assignee','Bug','2024-05-03','Architha Gudimalla','Datafix','edw_core','ttask','assigned_to_nm','Fixed assigned_to_nm in EDW. This is just a onetime update','9','Yes','2024-05-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI31554','HO100246034 - Robert Mann - Renewal Error','Bug','2024-05-03','Sandeep Gundreddy','Datafix','edw_core','tpolicy','prior_term_policy_no','Policy number and prior term policy number are same. Also, policy incorrectly flagged as renewed in Metal. This is migration issue and blocking renewal issuance on this policy-HO100246034 in Metal. This is just a onetime update.  Fixed data in Metal and EDW','9','Yes','2024-05-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5671','PEL - Metal 05/04 release related columns','Enhancement','2024-05-03','Rushin Shah','Addition','edw_core','tpel_vehicle','','Created 10 new columns','9','Yes','2024-05-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5671','PEL - Metal 05/04 release related columns','Enhancement','2024-05-03','Rushin Shah','Addition','edw_core','tquote_pel_vehicle','','Created 10 new columns','9','Yes','2024-05-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5671','PEL - Metal 05/04 release related columns','Enhancement','2024-05-03','Rushin Shah','Addition','edw_core','tpel_coverage','','Created 8 new columns','9','Yes','2024-05-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5671','PEL - Metal 05/04 release related columns','Enhancement','2024-05-03','Rushin Shah','Addition','edw_core','tquote_pel_coverage','','Created 8 new columns','9','Yes','2024-05-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5671','PEL - Metal 05/04 release related columns','Enhancement','2024-05-03','Rushin Shah','Addition','edw_core','tpel_location','','Created 5 new columns','9','Yes','2024-05-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5671','PEL - Metal 05/04 release related columns','Enhancement','2024-05-03','Rushin Shah','Addition','edw_core','tquote_pel_location','','Created 5 new columns','9','Yes','2024-05-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5671','PEL - Metal 05/04 release related columns','Enhancement','2024-05-03','Rushin Shah','Addition','edw_core','tpel_watercraft','','Created 3 new columns','9','Yes','2024-05-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5671','PEL - Metal 05/04 release related columns','Enhancement','2024-05-03','Rushin Shah','Addition','edw_core','tquote_pel_watercraft','','Created 3 new columns','9','Yes','2024-05-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5671','PEL - Metal 05/04 release related columns','Enhancement','2024-05-03','Rushin Shah','Addition','edw_core','tpel_driver','driver_limit_type','Created new column','9','Yes','2024-05-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5671','PEL - Metal 05/04 release related columns','Enhancement','2024-05-03','Rushin Shah','Addition','edw_core','tquote_pel_driver','driver_limit_type','Created new column','9','Yes','2024-05-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5671','PEL - Metal 05/04 release related columns','Enhancement','2024-05-03','Rushin Shah','Addition','edw_core','tpolicy_history','insurance_score_last_run_dt','Created new column','9','Yes','2024-05-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5671','PEL - Metal 05/04 release related columns','Enhancement','2024-05-03','Rushin Shah','Addition','edw_core','tquote_history','insurance_score_last_run_dt','Created new column','9','Yes','2024-05-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5671','PEL - Metal 05/04 release related columns','Enhancement','2024-05-03','Rushin Shah','Addition','edw_core','tpolicy_history','insurance_score_last_run_dt','Created new column','9','Yes','2024-05-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5671','PEL - Metal 05/04 release related columns','Enhancement','2024-05-03','Rushin Shah','Addition','edw_core','tquote_history','insurance_score_last_run_dt','Created new column','9','Yes','2024-05-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5671','PEL - Metal 05/04 release related columns','Enhancement','2024-05-03','Rushin Shah','Addition','edw_core','tpolicy_insured','named_insured_limit_type','Created new column','9','Yes','2024-05-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5671','PEL - Metal 05/04 release related columns','Enhancement','2024-05-03','Rushin Shah','Addition','edw_core','tquote_insured','named_insured_limit_type','Created new column','9','Yes','2024-05-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5803','Backfilling of Total Finished Square Feet for Home policies','Bug','2024-05-03','Yunus Mohammed','Datafix','edw_core','thome_coverage','total_finished_square_feet','Total Finished Square Feet for 23 policies were fixed to accurate number that were previously populated with 0. This is just a onetime update.  Fixed data in Metal and EDW','9','Yes','2024-05-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5881','Enhancements  - tbroker - add tier column','Enhancement','2024-05-03','Rushin Shah','Addition','edw_core','tbroker','broker_tier','Created new column','9','Yes','2024-05-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5910','Home - missing wildfire deductible','Bug','2024-05-03','Yunus Mohammed','Datafix','edw_core','thome_coverage','wildfire_deductible','This is a migration issue. Updated wildfire_deductible in Metal and EDW. This is just a onetime update','9','Yes','2024-05-06',getdate(),getdate());