-- tedw_release_summary
INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 05/20/2024 :</span>
<h4 style="margin-top: 0;">This release includes the following:</h4>
<ol>
    <li>Enhancements - 4
        <ul>
			<li>Re-architecture of quotes data model to incorporate work in progress quotes(Quotes without a transaction).  Also, updated logic to set tquote_history/latest_row_in=Y for most recently updated quote transaction</li>
			<li>Integrated CAPE Analytics data into EDW</li>
			<li>Datamart Enhancement - tbroker_summary : Added new columns policy_renewal_offered_ct, policy_renewal_offered_premiumm_amt related to renewals</li>
			<li>Datamart Enhancement - trenewal_summary : Added new columns renewal_quote_written_premium_amt, renewal_quote_tiv_amt, renewal_quote_dwelling_limit_amt, renewal_quote_other_structures_limit_amt, renewal_quote_contents_limit_amt and renewal_quote_loss_of_use_limit_amt related to quote data</li>
		</ul>
    </li>
    <li>Bug tickets - 28
        <ul>
			<li>Updated incorrect Auto vehicle coverage level premium for AV2 policies for cancellation transactions. This is a migration issue</li>
			<li>AV2 to Metal data migration cleanup by comparing AV2 vs Metal data and applied fixes on following fields wherever discrepancies were found</li>
				a) Coverage A<br>
				b) Coverage B<br> 
				c) Coverage C<br>
				d) Coverage D<br> 
				e) Coverage D percentage<br>
				f) Coverage E<br>
				g) Coverage F<br>
				h) Extended Replacement Cost Coverage<br>
				i) Named Structures Exclusion<br>
				j) Roof Exclusion<br>
				k) Water Deductible<br>
			<li>Updated rating territory for 2 policies</li>
			<li>Created alert on a few collections policies as requested by the user</li>
			<li>Updated expiration date for 4 renewal quotes</li>
			<li>Updated payment plan for 1 policiy as requested by the user</li>
			<li>Moved policies from one account to another</li>
			<li>Updated risk county for 1 policy</li>
        </ul>
    </li>
</ol>
'
,'Yes'
,'2024-05-20'
,getdate()
,getdate()
)
;

-- tedw_release_note

INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI31502','HO200032612 - Shawn Kirkpatrick - Bill Account 3996557958301','Bug','2024-05-10','Sandeep Gundreddy','Datafix','edw_core','tbilling_account','','updated payment plan to 2 pay as per the request. This is an isolated issue in Metal. ','10','Yes','2024-05-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI31568','Create Alert on collections policies.','Bug','2024-05-11','Sandeep Gundreddy','Datafix','edw_core','tnote','','Created alert for given policies as per the request','10','Yes','2024-05-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI31427','Merge account 1234522685  to 1234583472','Bug','2024-05-12','Sandeep Gundreddy','Datafix','edw_core','tpolicy','','Moved policies from customerid 1234522685  to 1234583472. Data is updated in Metal and EDW. This is just a onetime update as per VC team request.','10','Yes','2024-05-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6027','AV2 to Metal Data Migration Cleanup - Fix waterdeductible discrepancies','Bug','2024-05-17','Rushin Shah','Datafix','edw_core','thome_coverage','water_deductible','This is a migration issue. Updated water_deductible in Metal and EDW. This is just a onetime update.','10','Yes','2024-05-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6029','AV2 to Metal Data Migration Cleanup - Fix NamedStructuresExclusion discrepancies','Bug','2024-05-17','Rushin Shah','Datafix','edw_core','tadditional_home_coverage','named_structures_exclusion_in','This is a migration issue. Updated named_structures_exclusion_in in Metal and EDW. This is just a onetime update.','10','Yes','2024-05-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6034','AV2 to Metal Data Migration Cleanup - CovA discrepancies','Bug','2024-05-17','Rushin Shah','Datafix','edw_core','thome_coverage','dwelling_limit_amt','This is a migration issue. Updated dwelling_limit_amt in Metal and EDW. This is just a onetime update.','10','Yes','2024-05-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6030','AV2 to Metal Data Migration Cleanup - CovB discrepancies','Bug','2024-05-17','Rushin Shah','Datafix','edw_core','thome_coverage','other_structures_limit_amt','This is a migration issue. Updated other_structures_limit_amt in Metal and EDW. This is just a onetime update.','10','Yes','2024-05-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6031','AV2 to Metal Data Migration Cleanup - CovC discrepancies','Bug','2024-05-17','Rushin Shah','Datafix','edw_core','thome_coverage','contents_limit_amt','This is a migration issue. Updated contents_limit_amt in Metal and EDW. This is just a onetime update.','10','Yes','2024-05-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6032','AV2 to Metal Data Migration Cleanup - CovE discrepancies','Bug','2024-05-17','Rushin Shah','Datafix','edw_core','thome_coverage','personal_liability_limit_amt','This is a migration issue. Updated personal_liability_limit_amt in Metal and EDW. This is just a onetime update.','10','Yes','2024-05-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6033','AV2 to Metal Data Migration Cleanup - CovF discrepancies','Bug','2024-05-17','Rushin Shah','Datafix','edw_core','thome_coverage','medical_payments_limit_amt','This is a migration issue. Updated medical_payments_limit_amt in Metal and EDW. This is just a onetime update.','10','Yes','2024-05-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI31145/VI31359/VI31358/VI31476/AD6037','AV2 to Metal Data Migration Cleanup - CovD discrepancies','Bug','2024-05-17','Rushin Shah','Datafix','edw_core','thome_coverage','loss_of_use_limit_amt','This is a migration issue. Updated loss_of_use_limit_amt in Metal and EDW. This is just a onetime update.','10','Yes','2024-05-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI31342/VI31356/VI31361/VI28143/VI31003/AD6038','AV2 to Metal Data Migration Cleanup - CovDPercent discrepancies','Bug','2024-05-17','Rushin Shah','Datafix','edw_core','thome_coverage','loss_of_use_pc','This is a migration issue. Updated loss_of_use_pc in Metal and EDW. This is just a onetime update.','10','Yes','2024-05-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI31084/AD6039','AV2 to Metal Data Migration Cleanup - Roof Exclusion discrepancies','Bug','2024-05-17','Rushin Shah','Datafix','edw_core','thome_additional_coverage','roof_exclusion_in','This is a migration issue. Updated roof_exclusion_in in Metal and EDW. This is just a onetime update.','10','Yes','2024-05-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI31618/AD6010','HO100217097 & HO100129230-01 Update rating territory','Bug','2024-05-17','Yunus Mohammed','Datafix','edw_core','thome_coverage','rating_territory_cd','Rating territory was not matching with other transactions for policies HO100217097 & HO100129230-01. Updated data in Metal and EDW. This is just a onetime update.','10','Yes','2024-05-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI31545/AD6040','MT policy lists Los Angeles as risk county','Bug','2024-05-17','Yunus Mohammed','Datafix','edw_core','thome_location','county_nm','wrong county name present.Updated data in Metal and EDW. This is just a onetime update.','10','Yes','2024-05-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30633/VI30630/VI30617/VI30616/VI30608/VI29673','Incorrect Auto vehicle coverage level premium for cancellation transaction','Bug','2024-05-17','Sandeep Gundreddy','Datafix','edw_core','','','This is a migration issue. updated data in Metal and EDW. This is just a onetime update.','10','Yes','2024-05-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30426/VI26916/VI26520/AD5911','Re-Architect Quotes Data Model','Enhancement','2024-05-17','Sandeep Gundreddy','Addition','edw_core','','','Created 30 new stored procedures to load In Progress quotes (quote without a transaction) in all quotes tables . Also, updated logic to set tquote_history/latest_row_in=Y for most recently updated quote transaction','10','Yes','2024-05-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5940','Vendor reports -  Create view for CapeAnalytics ','Enhancement','2024-05-17','Architha Gudimalla','Addition','edw_core','vcapeanalytics','','CAPE analytics data is integrated into EDW. This view returns the data.','10','Yes','2024-05-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30737AD5932','Datamart Enhancement - tbroker_summary','Enhancement','2024-05-17','Architha Gudimalla','Addition','edw_core','tbroker_summary','policy_renewal_offered_premiumm_amt','Created new column','10','Yes','2024-05-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30737AD5932','Datamart Enhancement - tbroker_summary','Enhancement','2024-05-17','Architha Gudimalla','Addition','edw_core','tbroker_summary','policy_renewal_offered_ct','Created new column','10','Yes','2024-05-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI70925/AD5932','Datamart Enhancement - tbroker_summary','Enhancement','2024-05-17','Architha Gudimalla','Modification','edw_core','tbroker_summary','policy_expiring_ct','Corrected the logic by removing the non renewal ct','10','Yes','2024-05-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI70925/AD5932','Datamart Enhancement - tbroker_summary','Enhancement','2024-05-17','Architha Gudimalla','Modification','edw_core','tbroker_summary','policy_expiring_premium_amt','Corrected the logic by removing the non renewal premium','10','Yes','2024-05-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI31715/AD5996','Datamart Enhancement - trenewal_summary','Enhancement','2024-05-17','Architha Gudimalla','Addition','edw_core','trenewal_summary','renewal_quote_written_premium_amt','Created new column','10','Yes','2024-05-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI31715/AD5996','Datamart Enhancement - trenewal_summary','Enhancement','2024-05-17','Architha Gudimalla','Addition','edw_core','trenewal_summary','renewal_quote_tiv_amt','Created new column','10','Yes','2024-05-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI31715/AD5996','Datamart Enhancement - trenewal_summary','Enhancement','2024-05-17','Architha Gudimalla','Addition','edw_core','trenewal_summary','renewal_quote_dwelling_limit_amt','Created new column','10','Yes','2024-05-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI31715/AD5996','Datamart Enhancement - trenewal_summary','Enhancement','2024-05-17','Architha Gudimalla','Addition','edw_core','trenewal_summary','renewal_quote_other_structures_limit_amt','Created new column','10','Yes','2024-05-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI31715/AD5996','Datamart Enhancement - trenewal_summary','Enhancement','2024-05-17','Architha Gudimalla','Addition','edw_core','trenewal_summary','renewal_quote_contents_limit_amt','Created new column','10','Yes','2024-05-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI31715/AD5996','Datamart Enhancement - trenewal_summary','Enhancement','2024-05-17','Architha Gudimalla','Addition','edw_core','trenewal_summary','renewal_quote_loss_of_use_limit_amt','Created new column','10','Yes','2024-05-20',getdate(),getdate());