-- tedw_release_summary
INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 06/10/2024 :</span>
<h4 style="margin-top: 0;">This release includes the following:</h4>
<ol>
    <li>Enhancements - 4
        <ul>
			<li>Integrated Claims Estimate Payment data into EDW</li>
			<li>Integrated PEL Premium Adjustments data into EDW</li>
			<li>Integrated Collections Premium Adjustments data into EDW</li>
			<li>Added Broker contract date to tbroker table</li>
			
		</ul>
    </li>
    <li>Bug tickets - 31
        <ul>
			<li>AV2 to Metal Data migration cleanup. Following are the Home fields that were fixed (by comparing AV2 to Metal data) for accurate reporting and facilitate claims, renewal & endorsement processing.</li>
                a) ExtendedReplacementCostCoverage<br>
                b) WaterDamageSublimitAmount<br> 
                c) WaterDamageSublimit<br> 
                d) WaterDamageExclusion<br> 
                e) RoofCoveringFullReconstructionCostCoverage<br> 
                f) HomeSystemsProtection_In<br> 
                g) SpecificNamedStructuresPropertyAndLiabilityExclusion<br>
			<li>AV2 to Metal Data migration cleanup - Collections</li>
                a) LocationRentedToOthers<br> 
                b) WildfireDeductible<br>  
			<li>AV2 to Metal Data migration cleanup - PEL</li>
                a) UnderinsuredMotoristLiabilityAmount<br>
            <li>AV2 to Metal Data migration cleanup - Auto</li>
                a) Updated UMBIPolicyLimit that had limittype = Combined<br> 
                b) Updated CombinedUMPolicyLimit where limittype = Split<br>
                c) Updated UMPolicyLimit where limittype = combined<br>
                d) Updated CombinedUMPDPolicyLimit where limittype = split<br>
                e) Migrated UMPDPolicyLimit for NC from AV2 to Metal for Auto policies<br>
			<li>Updated zip code for 1 policy</li>
			<li>Updated dwelling limit amount for 21 policies</li>
			<li>Updated MedicalPaymentLimit, UMlimit, UIMLimit, CombinedUMLimit, CombinedUIMLimit for 1 policy</li>
			<li>Updated all auto limits for 1 policy </li>
			<li>Updated 5 Years Clean Discount field for 1 policy</li>
			<li>Updated deductible_waiver_large_losses_in for 1 policy as requested by the user</li>
			<li>Updated value to NULL where VendorReportedWholesaleAmount value is 0 as per the request from product team</li>			
		</ul>
    </li>
</ol>
'
,'Yes'
,'2024-06-10'
,getdate()
,getdate()
)
;

-- tedw_release_note

INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI31893','Create Alert on Auto policies.','Bug','2024-05-21','Sandeep Gundreddy','Datafix','edw_core','tnote','','Created alert for given policies as per the request','11','Yes','2024-06-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29973','UMBIPolicyLimit - Migration error for limittype = Combined','Bug','2024-06-03','Architha Gudimalla','Datafix','edw_core','tauto_policy_coverage','um_bi_policy_limit_amt','Updated the limit to null for policies that have limittype = Combined','11','Yes','2024-06-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29965','CombinedUMPolicyLimit - Migration error','Bug','2024-06-03','Architha Gudimalla','Datafix','edw_core','tauto_policy_coverage','combined_uninsured_motorist_limit_amt','Updated the limit to null for policies that have limittype = split. Also corrected the value to take out comma in the value for the display to work in the frond end','11','Yes','2024-06-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29965','UMPolicyLimit - Migration error','Bug','2024-06-03','Architha Gudimalla','Datafix','edw_core','tauto_policy_coverage','uninsured_motorist_limit_amt','Updated the limit to null for policies that have limittype = combined. Also corrected the value to take out comma in the value for the display to work in the frond end','11','Yes','2024-06-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29959','CombinedUMPDPolicyLimit was migrated for policies even when limit type = split','Bug','2024-05-23','Architha Gudimalla','Datafix','edw_core','tauto_policy_coverage','combined_um_pd_policy_limit_amt','Updated the value to null whe limitype = slit','11','Yes','2024-06-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30875','Migrate UMPDPolicyLimit for NC from Av2 to Metal','Bug','2024-06-03','Architha Gudimalla','Datafix','edw_core','tauto_policy_coverage','um_pd_policy_limit_amt','Updated the value from AV2 becuase migration excluded it before since NC did not support UMPD','11','Yes','2024-06-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30100','Update MedicalPaymentLimit for AUX10005784','Bug','2024-05-22','Architha Gudimalla','Datafix','edw_core','tauto_policy_coverage','medical_payment_limit_amt','Updated medical payment limit to 5000','11','Yes','2024-06-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30095','Update UMlimit for AUX10001774','Bug','2024-06-07','Architha Gudimalla','Datafix','edw_core','tauto_policy_coverage','uninsured_motorist_limit_amt','Updated limit to $250,000 / $500,000 / $100,000','11','Yes','2024-06-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30095','Update UIMLimit for AUX10001774','Bug','2024-06-07','Architha Gudimalla','Datafix','edw_core','tauto_policy_coverage','underinsured_motorist_limit_amt','Updated limit to $250,000 / $500,000 / $100,000','11','Yes','2024-06-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30046','Update UIMLimit for AU100199997','Bug','2024-06-07','Architha Gudimalla','Datafix','edw_core','tauto_policy_coverage','underinsured_motorist_limit_amt','Updated limit to $250,000 / $500,000','11','Yes','2024-06-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29972','Update CombinedUMLimit for AUX10001522','Bug','2024-06-07','Architha Gudimalla','Datafix','edw_core','tauto_policy_coverage','combined_uninsured_motorist_limit_amt','Updated limit to 500,000','11','Yes','2024-06-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29972','Update CombinedUIMLimit for AUX10001522','Bug','2024-06-07','Architha Gudimalla','Datafix','edw_core','tauto_policy_coverage','combined_underinsured_motorist_limit_amt','Updated limit to 500,000','11','Yes','2024-06-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29850','Update all limits for AUX10005980','Bug','2024-06-07','Architha Gudimalla','Datafix','edw_core','tauto_policy_coverage','','Updated limit type to split, conbinedsingle and um to 500000, and nulled all split limits','11','Yes','2024-06-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI31456','Years Clean Discount falling off on Endorsement','Bug','2024-05-23','Sandeep Gundreddy','Datafix','edw_core','tauto_policy_coverage','years_clean_discount','Updated value to Yes - 5 Years Clean for all terms on the policy-AU100002106. This is an isolated issued. Updated data in Metal and EDW.','11','Yes','2024-06-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30256','Terence Smith NJ  Policy Number: HO100145374-02   on coverage options the DWELL endorsement is not listed but pulling in forms on the renewal term.   This is occurring on 5/1/24 ','Bug','2024-05-23','Sandeep Gundreddy','Datafix','edw_core','thome_additional_coverage','deductible_waiver_large_losses_in','updated value to No as per the request for NJ policies with renewal effective date >=05/01/2024. This is just a onetime update. Data updated data in Metal and EDW','11','Yes','2024-06-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI31205','Profile to be moved Jeremy Wagner 1234514162 / HO64840523136-04 compliance priority','Bug','2024-05-23','Sandeep Gundreddy','Datafix','edw_core','tpolicy','','Moved policies from customerid 1234514162 to 1234573982. Data is updated in Metal and EDW. This is just a onetime update as per VC team request.','11','Yes','2024-06-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI32088','Combine two accounts for the same insured Theodore Moore','Bug','2024-05-31','Sandeep Gundreddy','Datafix','edw_core','tpolicy','','Moved policies from customerid 1234587068 to 1234532769. Data is updated in Metal and EDW. This is just a onetime update as per VC team request.','11','Yes','2024-06-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('SF96/AD6134','Carfax Blank value passing as 0','Bug','2024-05-23','Sandeep Gundreddy','Datafix','edw_core','tauto_vehicle_coverage','carfax_wholesale_value_amt','Updated value to NULL where VendorReportedWholesaleAmount value is 0 as per the request from product team. Issue is fixed in Metal to prevent it from happening in future. updated data in Metal and EDW. This is just a onetime update.','11','Yes','2024-06-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI31368/AD6081','AV2 to Metal Data Migration Cleanup - ExtendedReplacementCostCoverage discrepancies','Bug','2024-06-10','Rushin Shah','Datafix','edw_core','thome_additional_coverage','extended_replacement_cost_coverage_in','This is a migration issue. Updated extended_replacement_cost_coverage_in in Metal and EDW. This is just a onetime update.','11','Yes','2024-06-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-31738/AD6083','AV2 to Metal Data Migration Cleanup - Water Damage Sublimit Amount discrepancies','Bug','2024-06-10','Rushin Shah','Datafix','edw_core','thome_additional_coverage','waterdamage_sublimit_amt','This is a migration issue. Updated waterdamage_sublimit_amt in Metal and EDW. This is just a onetime update.','11','Yes','2024-06-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI31738/AD6125','AV2 to Metal Data Migration Cleanup - Water Damage Sublimit discrepancies','Bug','2024-06-10','Rushin Shah','Datafix','edw_core','thome_additional_coverage','waterdamage_sublimit','This is a migration issue. Updated waterdamage_sublimit in Metal and EDW. This is just a onetime update.','11','Yes','2024-06-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6082','AV2 to Metal Data Migration Cleanup - Water Damage Exclusion discrepancies','Bug','2024-06-10','Rushin Shah','Datafix','edw_core','thome_additional_coverage','waterdamage_exclusion_in','This is a migration issue. Updated waterdamage_exclusion_in in Metal and EDW. This is just a onetime update.','11','Yes','2024-06-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI31084/AD6086','AV2 to Metal Data Migration Cleanup - Roof covering full reconstruction cost coverage discrepancies','Bug','2024-06-10','Rushin Shah','Datafix','edw_core','thome_additional_coverage','roof_covering_full_reconstruction_cost_coverage_in','This is a migration issue. Updated roof_covering_full_reconstruction_cost_coverage_in in Metal and EDW. This is just a onetime update.','11','Yes','2024-06-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6080/VI28412','AV2 to Metal Data Migration Cleanup - home_systems_protection discrepancies','Bug','2024-06-10','Rushin Shah','Datafix','edw_core','thome_additional_coverage','home_systems_protection_in','This is a migration issue. Updated home_systems_protection_in in Metal and EDW. This is just a onetime update.','11','Yes','2024-06-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI31712 & VI30164','HO policies missing dwelling limit amount','Bug','2024-06-10','Rushin Shah','Datafix','edw_core','thome_coverage','dwelling_limit_amt','Updated dwelling_limit_amt for 21 policies.  This is just a onetime update. Data updated data in Metal and EDW.','11','Yes','2024-06-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6085','AV2 to Metal Data Migration Cleanup - Specific Named Structures Property and Liability Exclusion discrepancies','Bug','2024-06-10','Rushin Shah','Datafix','edw_core','thome_additional_coverage','specific_named_structures_property_and_liability_exclusion_in','This is a migration issue. Updated specific_named_structures_property_and_liability_exclusion_in in Metal and EDW. This is just a onetime update.','11','Yes','2024-06-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6247','AV2 to Metal Data Migration Cleanup - Collections location rented to others discrepancies','Bug','2024-06-10','Rushin Shah','Datafix','edw_core','','','This is a migration issue. Updated LocationRentedToOthers in Metal. This is just a onetime update.','11','Yes','2024-06-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6248','AV2 to Metal Data Migration Cleanup - Collections wildfire deductible discrepancies','Bug','2024-06-10','Rushin Shah','Datafix','edw_core','tcollection_coverage','wildfire_deductible_in','This is a migration issue. Updated wildfire_deductible_in in Metal and EDW. This is just a onetime update.','11','Yes','2024-06-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6249','AV2 to Metal Data Migration Cleanup - PEL Underinsured Motorist Liability Amount discrepancies','Bug','2024-06-10','Rushin Shah','Datafix','edw_core','tpel_coverage','uninsured_underinsured_motorist_liability_amt','This is a migration issue. Updated uninsured_underinsured_motorist_liability_amt in Metal and EDW. This is just a onetime update','11','Yes','2024-06-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI31235','Zip code is incorrect  for CO100209134','Bug','2024-06-10','Yunus Mohammed','Datafix','edw_core','tcollection_location','zip_cd','Updated zip code for CO100209134.  This is just a onetime update. Data updated data in Metal and EDW.','11','Yes','2024-06-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6119','Integrate Claims Estimate Payment document metadata to EDW','Enhancement','2024-06-10','Yunus Mohammed','Addition','edw_core','vclaimpaymentestimate','','Claims Estimate Payment data is integrated into EDW. This view returns the data.','11','Yes','2024-06-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5919','PEL - Integrate Premium Adjustments data into EDW','Enhancement','2024-06-10','Tuba Mohsin','Addition','edw_core','tpel_coverage','','Created 4 new columns','11','Yes','2024-06-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5919','PEL - Integrate Premium Adjustments data into EDW','Enhancement','2024-06-10','Tuba Mohsin','Addition','edw_core','tquote_pel_coverage','','Created 4 new columns','11','Yes','2024-06-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5141','Collections - Integrate Premium Adjustments data into EDW','Enhancement','2024-06-10','Tuba Mohsin','Addition','edw_core','tcollection_class_type','','Created 8 new columns','11','Yes','2024-06-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5141','Collections - Integrate Premium Adjustments data into EDW','Enhancement','2024-06-10','Tuba Mohsin','Addition','edw_core','tquote_collection_class_type','','Created 8 new columns','11','Yes','2024-06-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI31996','combine customer profile 1234516897 and 1234585588','Bug','2024-06-07','Sandeep Gundreddy','Datafix','edw_core','tpolicy','','Moved policies from customerid 1234585588 to 1234516897. Data is updated in Metal and EDW. This is just a onetime update as per VC team request.','11','Yes','2024-06-10',getdate(),getdate());