-- tedw_release_summary
INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 06/17/2024 :</span>
<h4 style="margin-top: 0;">This release includes the following:</h4>
<ol>
    <li>Enhancements - 7
        <ul>
			<li>Added Metal 06/15 release related 9 new columns for Auto</li>
			<li>Added Metal 06/15 release related 1 new column for Home</li>
			<li>Added Metal 06/15 release related 1 new column for PEL</li>
			<li>Added Metal 06/15 release related 1 new column for Collections</li>
			<li>Added national_agency_in to tbroker</li>
			<li>Added 3 new columns -created_by_user_sk, assigned_to_user_sk, completed_by_user_sk to ttask table</li>
			<li>Added rate_on_line column to Home</li>                       
	</ul>
    </li>
    <li>Bug tickets - 3
        <ul>
			<li>Updated logic for renewal_quote_sk in trenewal_summary table </li>
	</ul>
    </li>
</ol>
'
,'Yes'
,'2024-06-17'
,getdate()
,getdate()
)
;

-- tedw_release_note

INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI32145','Datamart - trenewal_summary','Bug','2024-06-14','Architha Gudimalla','Datafix','edw_core','trenewal_summary','renewal_quote_sk','Updated the column to use quote_sk from the quote with the same original policy number instead of the cancel rewrrite','12','Yes','2024-06-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI31494','Please combine the accounts for policies HO100032300-05 and HO100106430-02','Bug','2024-06-12','Sandeep Gundreddy','Datafix','edw_core','tpolicy','','Moved policies from customerid 1234559691 to 1234515688. Data is updated in Metal and EDW. This is just a onetime update as per VC team request.','12','Yes','2024-06-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6163','Auto - Metal 06/15 release related columns','Enhancement','2024-06-14','Rushin Shah','Addition','edw_core','tauto_driver_incident','pip_claim_override_in','Created new column','12','Yes','2024-06-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6163','Auto - Metal 06/15 release related columns','Enhancement','2024-06-14','Rushin Shah','Addition','edw_core','tquote_auto_driver_incident','pip_claim_override_in','Created new column','12','Yes','2024-06-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6163','Auto - Metal 06/15 release related columns','Enhancement','2024-06-14','Rushin Shah','Addition','edw_core','tauto_policy_coverage','permissive_driver_unique_liability_limits_in','Created new column','12','Yes','2024-06-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6163','Auto - Metal 06/15 release related columns','Enhancement','2024-06-14','Rushin Shah','Addition','edw_core','tauto_policy_coverage','permissive_driver_unique_combined_single_limit_amt','Created new column','12','Yes','2024-06-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6163','Auto - Metal 06/15 release related columns','Enhancement','2024-06-14','Rushin Shah','Addition','edw_core','tauto_policy_coverage','permissive_driver_unique_bi_limit_amt','Created new column','12','Yes','2024-06-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6163','Auto - Metal 06/15 release related columns','Enhancement','2024-06-14','Rushin Shah','Addition','edw_core','tauto_policy_coverage','permissive_driver_unique_pd_limit_amt','Created new column','12','Yes','2024-06-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6163','Auto - Metal 06/15 release related columns','Enhancement','2024-06-14','Rushin Shah','Addition','edw_core','tauto_policy_coverage','emergency_extension_notice_in','Created new column','12','Yes','2024-06-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6163','Auto - Metal 06/15 release related columns','Enhancement','2024-06-14','Rushin Shah','Addition','edw_core','tquote_auto_policy_coverage','permissive_driver_unique_liability_limits_in','Created new column','12','Yes','2024-06-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6163','Auto - Metal 06/15 release related columns','Enhancement','2024-06-14','Rushin Shah','Addition','edw_core','tquote_auto_policy_coverage','permissive_driver_unique_combined_single_limit_amt','Created new column','12','Yes','2024-06-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6163','Auto - Metal 06/15 release related columns','Enhancement','2024-06-14','Rushin Shah','Addition','edw_core','tquote_auto_policy_coverage','permissive_driver_unique_bi_limit_amt','Created new column','12','No','2024-06-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6163','Auto - Metal 06/15 release related columns','Enhancement','2024-06-14','Rushin Shah','Addition','edw_core','tquote_auto_policy_coverage','permissive_driver_unique_pd_limit_amt','Created new column','12','Yes','2024-06-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6163','Auto - Metal 06/15 release related columns','Enhancement','2024-06-14','Rushin Shah','Addition','edw_core','tquote_auto_policy_coverage','emergency_extension_notice_in','Created new column','12','Yes','2024-06-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6163','Auto - Metal 06/15 release related columns','Enhancement','2024-06-14','Rushin Shah','Addition','edw_core','tauto_vehicle_coverage','newly_purchased_vehicle_dt','Created new column','12','Yes','2024-06-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6163','Auto - Metal 06/15 release related columns','Enhancement','2024-06-14','Rushin Shah','Addition','edw_core','tauto_vehicle_coverage','newly_purchased_vehicle_override_in','Created new column','12','Yes','2024-06-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6163','Auto - Metal 06/15 release related columns','Enhancement','2024-06-14','Rushin Shah','Addition','edw_core','tquote_auto_vehicle_coverage','newly_purchased_vehicle_dt','Created new column','12','Yes','2024-06-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6163','Auto - Metal 06/15 release related columns','Enhancement','2024-06-14','Rushin Shah','Addition','edw_core','tquote_auto_vehicle_coverage','newly_purchased_vehicle_override_in','Created new column','12','Yes','2024-06-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6164','Home - Metal 06/15 release related columns','Enhancement','2024-06-14','Rushin Shah','Addition','edw_core','thome_additional_coverage','emergency_extension_notice_in','Created new column','12','Yes','2024-06-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6164','Home - Metal 06/15 release related columns','Enhancement','2024-06-14','Rushin Shah','Addition','edw_core','tquote_home_additional_coverage','emergency_extension_notice_in','Created new column','12','Yes','2024-06-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6165','PEL - Metal 06/15 release related columns','Enhancement','2024-06-14','Rushin Shah','Addition','edw_core','tpel_coverage','emergency_extension_notice_in','Created new column','12','Yes','2024-06-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6165','PEL - Metal 06/15 release related columns','Enhancement','2024-06-14','Rushin Shah','Addition','edw_core','tquote_pel_coverage','emergency_extension_notice_in','Created new column','12','Yes','2024-06-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6166','Collections - Metal 06/15 release related columns','Enhancement','2024-06-14','Rushin Shah','Addition','edw_core','tcollection_coverage','emergency_extension_notice_in','Created new column','12','Yes','2024-06-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6166','Collections - Metal 06/15 release related columns','Enhancement','2024-06-14','Rushin Shah','Addition','edw_core','tquote_collection_coverage','emergency_extension_notice_in','Created new column','12','Yes','2024-06-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI31063/AD6330','Addition of rate_on_line column for Home','Enhancement','2024-06-14','Architha Gudimalla','Addition','edw_core','thome_coverage','rate_on_line','Created new column','12','Yes','2024-06-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI31063/AD6330','Addition of rate_on_line column for Home','Enhancement','2024-06-14','Architha Gudimalla','Addition','edw_core','tquote_home_coverage','rate_on_line','Created new column','12','Yes','2024-06-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI32215/AD6285','Add user_sks to edw_core.ttask','Enhancement','2024-06-14','Architha Gudimalla','Addition','edw_core','ttask','created_by_sk','Created new column','12','Yes','2024-06-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI32215/AD6285','Add user_sks to edw_core.ttask','Enhancement','2024-06-14','Architha Gudimalla','Addition','edw_core','ttask','assigned_to_sk','Created new column','12','Yes','2024-06-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI32215/AD6285','Add user_sks to edw_core.ttask','Enhancement','2024-06-14','Architha Gudimalla','Addition','edw_core','ttask','completed_by_sk','Created new column','12','Yes','2024-06-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6107','Auto - Metal 06/15 release related columns','Enhancement','2024-06-14','Rushin Shah','Addition','edw_core','tauto_vehicle_coverage','newly_purchased_vehicle_final_in','Created new column','12','Yes','2024-06-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6107','Auto - Metal 06/15 release related columns','Enhancement','2024-06-14','Rushin Shah','Addition','edw_core','tquote_auto_vehicle_coverage','newly_purchased_vehicle_final_in','Created new column','12','Yes','2024-06-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6107','Metal 06/15 release related column','Enhancement','2024-06-14','Rushin Shah','Addition','edw_core','tbroker','national_agency_in','Created new column','12','Yes','2024-06-17',getdate(),getdate());