-- tedw_release_summary
INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 06/24/2024 :</span>
<h4 style="margin-top: 0;">This release includes the following:</h4>
<ol>
    <li>Enhancements - 4
        <ul>
			<li>Added prorate_factor column to tpolicy_history table </li>
			<li>Added nc_bureau_rate column for Home</li>
			<li>Datamart Enhancement - Added prior_mtd_net_premium_amt, mtd_net_premium_amt columns to tbroker_summary table </li>
			<li>Workday Enahancement - Enhanced commission logic for workday written premium file to capture transactions under appropriate aslob as requested by Finance</li>
			
	</ul>
    </li>
    <li>Bug tickets - 6
        <ul>
			<li>Insurance score last run date field was backfilled in Metal. This is just a onetime data fix as per business request to support AV2 shutdown. EDW will be backfilled during next full EDW refresh on 07/13.</li>
			<li>AV2 to Metal Data migration cleanup. Following are the fields that were fixed (by comparing AV2 to Metal data) for accurate reporting and facilitate claims, renewal & endorsement processing.</li> 
                        	a) Collections : Wildfire Deductible Amount<br>
                            b) Collections : Hurricane Deductible Limit<br> 
                            c) Collections : Number Of Losses Last Three Years<br>
			<li>Updated subclaim_type_nm, claim_coverage_desc, aslob_sk in EDW for OS claims as per the request </li>
			<li>Updated logic to capture appropriate broker commission tier status</li>
		</ul>
    </li>
</ol>
'
,'Yes'
,'2024-06-24'
,getdate()
,getdate()
)
;

-- tedw_release_note

INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5983','Addition of NCRB premiums for Home','Enhancement','2024-06-21','Architha Gudimalla','Addition','edw_core','thome_coverage','nc_bureau_rate','Created new column','13','Yes','2024-06-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5983','Addition of NCRB premiums for Home','Enhancement','2024-06-21','Architha Gudimalla','Addition','edw_core','tquote_home_coverage','nc_bureau_rate','Created new column','13','Yes','2024-06-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5714','Add prorate factor to tpolicy_history table','Enhancement','2024-06-21','Tuba Mohsin','Addition','edw_core','tpolicy_history','prorate_factor','Created new column','13','Yes','2024-06-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5714','Add prorate factor to tpolicy_history table','Enhancement','2024-06-21','Tuba Mohsin','Addition','edw_core','tquote_history','prorate_factor','Created new column','13','Yes','2024-06-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI32223/AD6283','Can we please add gross premium for all terms to tbroker_summary','Enhancement','2024-06-21','Architha Gudimalla','Addition','edw_core','tbroker_summary','prior_mtd_net_premium_amt','Created new column','13','Yes','2024-06-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI32223/AD6283','Can we please add gross premium for all terms to tbroker_summary','Enhancement','2024-06-21','Architha Gudimalla','Addition','edw_core','tbroker_summary','mtd_net_premium_amt','Created new column','13','Yes','2024-06-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI31848/AD6375','Broker Commission Tiers showing as expired in metal','Bug','2024-06-21','Yunus Mohammed','Modification','edw_core','sp_tbroker_commission','broker_commission_status','Updated stored procedure logic for broker_commission_status to capture appropriate data.','13','Yes','2024-06-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6387','Collections  AV2 to Metal Data Migration Cleanup - Wildfire Deductible Amount discrepancies','Bug','2024-06-21','Rushin Shah','Datafix','edw_core','tcollection_coverage','wildfire_deductible_amt','This is a migration issue. Updated wildfire_deductible_amt in Metal. This is just a onetime update.  EDW will be backfilled during next full EDW refresh on 07/13.','13','Yes','2024-06-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6388','Collections  AV2 to Metal Data Migration Cleanup - Hurricane Deductible Limit discrepancies','Bug','2024-06-21','Rushin Shah','Datafix','edw_core','tcollection_coverage','hurricane_deductible_amt','This is a migration issue. Updated hurricane_deductible_amt in Metal. This is just a onetime update.   EDW will be backfilled during next full EDW refresh on 07/13.','13','Yes','2024-06-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6389','Collections  AV2 to Metal Data Migration Cleanup - Number Of Losses Last Three Years discrepancies','Bug','2024-06-21','Rushin Shah','Datafix','edw_core','tcollection_coverage','valuable_article_losses_last3_years_ct','This is a migration issue. Updated valuable_article_losses_last3_years_ct in Metal. This is just a onetime update.  EDW will be backfilled during next full EDW refresh on 07/13.','13','Yes','2024-06-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI32358/AD6133/VI25785','Last Run Date for Insurance Scores Not Pulled From AV2; Unable to Determine if Insurance Score Needs to be Updated; ','Bug','2024-06-20','Architha Gudimalla','Datafix','edw_core','tpolicy_history','insurance_score_last_run_dt','Insurance score last run date field was backfilled in Metal. This is just a onetime data fix as per business request to support AV2 shutdown. EDW will be backfilled during next full EDW refresh on 07/13.','13','Yes','2024-06-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI32121/AD6342','Update aslob_sk logic in commission in workday written premium file','Enhancement','2024-06-21','Yunus Mohammed','Modification','edw_integration','policy_workday_written_premium_feed','aslob','Updated aslob_sk logic in workday written premium file for commission amount as requested by Finance team','13','Yes','2024-06-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI32215/AD6282','EDW oneshield data update on ASLOB_SK for oneshield auto claims','Bug','2024-06-20','Yunus Mohammed','Datafix','edw_core','tclaim_feature','subclaim_type_nm','Updated subclaim_type_nm in EDW for OS claims as per the request. This is just a onetime update.','13','Yes','2024-06-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI32215/AD6282','EDW oneshield data update on ASLOB_SK for oneshield auto claims','Bug','2024-06-20','Yunus Mohammed','Datafix','edw_core','tclaim_feature','claim_coverage_desc','Updated claim_coverage_desc in EDW for OS claims  as per the request. This is just a onetime update.','13','Yes','2024-06-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI32215/AD6282','EDW oneshield data update on ASLOB_SK for oneshield auto claims','Bug','2024-06-20','Yunus Mohammed','Datafix','edw_core','tclaim_feature','aslob_sk','Updated aslob_sk in EDW for OS claims as per the request. This is just a onetime update.','13','Yes','2024-06-24',getdate(),getdate());