-- tedw_release_summary
INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 07/15/2024 :</span>
<h4 style="margin-top: 0;">This release includes the following:</h4>
<ol>
    <li>Enhancements - 8
        <ul>
			<li>Datamart Enhancement - Added policy_history_sk to tpolicy_transaction, tdaily_inforce_policy, titem_inforce, titem_summary, tpolicy_summary, tpolicy_transaction_summary, tinternal_coverage_inforce, tinternal_coverage_summary tables</li>
			<li>Added Metal 07/13 release related 8 new columns for Auto</li>
			<li>Added Metal 07/13 release related 4 new columns for Home</li>
			<li>Added Metal 07/13 release related 7 new columns for PEL</li>
			<li>Added otc_ncrb_premium_amt and collision_ncrb_premium_amt column to tauto_policy_coverage table</li>
			<li>Deleted rater_pip_discount column from tauto_policy_coverage table and added to tauto_vehicle_coverage table</li>
			<li>Added vehicle_unique_id column to tquote_auto_vehicle and tquote_auto_vehicle_coverage tables </li>
			<li>Added primary_location_in column to tpel_location table </li>
		</ul>
    </li>
    <li>Bug tickets - 42
        <ul>
			<li>Deleted and rekeyed(by VC team) 29 NC Auto transactions so that the premium gets reflected appropriately under optional coverages (instead of taxes).Transaction issue date is updated to the original transaction issue date</li>
			<li>Data Standardization : Updated water_deductible, hurricane_deductible, hurricane_or_named_storm_deductible, wildfire_deductible, and wind_or_hailstorm_deductible with value $0 to null </li>
			<li>Data Standardization : Fixed aop_deductible, water_deductible, hurricane_deductible, wildfire_deductible, and wind_or_hailstorm_deductible amount which had formatting issues </li>
			<li>Data Standardization : Corrected metal field name "UninsuredUnderinsuredMotorist LiabilityForSecondaryInsured" to remove the extra space </li>
			<li>Backfilled NCRB Premiums for Collision and OTC on NC Auto policies </li>
			<li>Backfilled Rater PIP Discount on NC Auto policies </li>
            <li>Modified process to capture broker related changes accurately in tbroker table </li>
			<li>Modified procedure to update the policy term associated with OS data that had invalid values </li>
			<li>Modified procedure to capture disabled producer status </li>
			<li>Modified procedure to populate accurate premium modification factors for PEL policies </li>
			<li>Created alert for given set of requested policies </li>
			<li>Resolved 13 tickets associated with exclude_wind and hurricane/wind deductible fields </li>
			<li>Resolved 12 tickets associated with uninsured motorist BI/PD limit fields </li>
			<li>Resolved 4 tickets associated with underinsured motorist limit and limit type fields </li>
			<li>Updated values for extended_towing_and_labor_in, emergency_movement_coverage_in and physical_damage_deductible_adjustment for one policy </li>
			<li>Updated cape analytics view to to ensure proper data retrieval </li>
			<li>Updated city name and county name for one policy </li>
		</ul>
    </li>
</ol>
'
,'Yes'
,'2024-07-15'
,getdate()
,getdate()
)
;

-- tedw_release_note

INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI32329/AD6355','PEL Premium mod factors not matching between EDW and Metal','Bug','2024-06-20','Alberto Almario','Datafix','edw_core','','','Updated stored procedure logic to populate premium modification factors for PEL policies','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI32458','need to add a alert note to a group of policies ','Bug','2024-06-24','Sandeep Gundreddy','Datafix','edw_core','tnote','','Created alert for given policies as per the request','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6470','PEL - Metal 07/13 release related columns','Enhancement','2024-07-12','Tuba Mohsin','Addition','edw_core','tpel_coverage','coverage_deductible_amt','Created new column','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6470','PEL - Metal 07/13 release related columns','Enhancement','2024-07-12','Tuba Mohsin','Addition','edw_core','tpel_coverage','additional_coverage_deductible_amt','Created new column','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6470','PEL - Metal 07/13 release related columns','Enhancement','2024-07-12','Tuba Mohsin','Addition','edw_core','tpel_coverage','underinsured_motorist_deductible_amt','Created new column','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6470','PEL - Metal 07/13 release related columns','Enhancement','2024-07-12','Tuba Mohsin','Addition','edw_core','tpel_coverage','underinsured_deductible_amt','Created new column','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6470','PEL - Metal 07/13 release related columns','Enhancement','2024-07-12','Tuba Mohsin','Addition','edw_core','tpel_coverage','employment_practices_liability_deductible_amt','Created new column','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6470','PEL - Metal 07/13 release related columns','Enhancement','2024-07-12','Tuba Mohsin','Addition','edw_core','tpel_coverage','current_underlying_auto_insurance_company_nm','Created new column','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6470','PEL - Metal 07/13 release related columns','Enhancement','2024-07-12','Tuba Mohsin','Addition','edw_core','tpel_coverage','current_underlying_home_insurance_company_nm','Created new column','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6470','PEL - Metal 07/13 release related columns','Enhancement','2024-07-12','Tuba Mohsin','Addition','edw_core','tquote_pel_coverage','','Created 7 new columns same as policy table','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6469','Home - Metal 07/13 release related columns','Enhancement','2024-07-12','Tuba Mohsin','Addition','edw_core','thome_coverage','stated_limits_policy_in','Created new column','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6469','Home - Metal 07/13 release related columns','Enhancement','2024-07-12','Tuba Mohsin','Addition','edw_core','thome_coverage','risk_sharing_policy_in','Created new column','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6469','Home - Metal 07/13 release related columns','Enhancement','2024-07-12','Tuba Mohsin','Addition','edw_core','tquote_home_coverage','stated_limits_policy_in','Created new column','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6469','Home - Metal 07/13 release related columns','Enhancement','2024-07-12','Tuba Mohsin','Addition','edw_core','tquote_home_coverage','risk_sharing_policy_in','Created new column','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6469','Home - Metal 07/13 release related columns','Enhancement','2024-07-12','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','roof_covering_coverage_limitation_all_peril_loss_settlement_endorsement_in','Created new column','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6469','Home - Metal 07/13 release related columns','Enhancement','2024-07-12','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','all_peril_roof_covering_coverage_limitation_loss_settlement_endorsement_in','Created new column','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6469','Home - Metal 07/13 release related columns','Enhancement','2024-07-12','Tuba Mohsin','Addition','edw_core','tquote_home_additional_coverage','roof_covering_coverage_limitation_all_peril_loss_settlement_endorsement_in','Created new column','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6469','Home - Metal 07/13 release related columns','Enhancement','2024-07-12','Tuba Mohsin','Addition','edw_core','tquote_home_additional_coverage','all_peril_roof_covering_coverage_limitation_loss_settlement_endorsement_in','Created new column','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6471','Auto - Metal 07/13 release related columns','Enhancement','2024-07-12','Tuba Mohsin','Addition','edw_core','tauto_driver','aaf_factor','Created new column','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6471','Auto - Metal 07/13 release related columns','Enhancement','2024-07-12','Tuba Mohsin','Addition','edw_core','tauto_driver','afb_factor','Created new column','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6471','Auto - Metal 07/13 release related columns','Enhancement','2024-07-12','Tuba Mohsin','Addition','edw_core','tauto_driver','naf_factor','Created new column','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6471','Auto - Metal 07/13 release related columns','Enhancement','2024-07-12','Tuba Mohsin','Addition','edw_core','tauto_driver','cpa_factor','Created new column','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6471','Auto - Metal 07/13 release related columns','Enhancement','2024-07-12','Tuba Mohsin','Addition','edw_core','tauto_driver','min_factor','Created new column','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6471','Auto - Metal 07/13 release related columns','Enhancement','2024-07-12','Tuba Mohsin','Addition','edw_core','tauto_driver','maj_factor','Created new column','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6471','Auto - Metal 07/13 release related columns','Enhancement','2024-07-12','Tuba Mohsin','Addition','edw_core','tauto_driver','sdp_factor','Created new column','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6471','Auto - Metal 07/13 release related columns','Enhancement','2024-07-12','Tuba Mohsin','Addition','edw_core','tquote_auto_driver','','Created 7 new columns same as policy table','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6471','Auto - Metal 07/13 release related columns','Enhancement','2024-07-12','Tuba Mohsin','Addition','edw_core','tauto_driver_incident','increase_premium_on_renewal_in','Created new column','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6471','Auto - Metal 07/13 release related columns','Enhancement','2024-07-12','Tuba Mohsin','Addition','edw_core','tquote_auto_driver_incident','increase_premium_on_renewal_in','Created new column','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6396','Data Standardization : Update hurricane_deductible with $0 to null','Bug','2024-07-12','Rushin Shah','Datafix','edw_core','thome_coverage','hurricane_deductible','Updated $0 hurricane_deductible to null in Metal and EDW. This is just a onetime update.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6396','Data Standardization : Update hurricane_or_named_storm_deductible with $0 to null','Bug','2024-07-12','Rushin Shah','Datafix','edw_core','thome_coverage','hurricane_or_named_storm_deductible','Updated $0 hurricane_or_named_storm_deductible to null in Metal and EDW. This is just a onetime update.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6396','Data Standardization : Update water_deductible with $0 to null','Bug','2024-07-12','Rushin Shah','Datafix','edw_core','thome_coverage','water_deductible','Updated $0 water_deductible to null in Metal and EDW. This is just a onetime update.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6396','Data Standardization : Update wildfire_deductible with $0 to null','Bug','2024-07-12','Rushin Shah','Datafix','edw_core','thome_coverage','wildfire_deductible','Updated $0 wildfire_deductible to null in Metal and EDW. This is just a onetime update.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6396','Data Standardization : Update wind_or_hailstorm_deductible with $0 to null','Bug','2024-07-12','Rushin Shah','Datafix','edw_core','thome_coverage','wind_or_hailstorm_deductible','Updated $0 wind_or_hailstorm_deductible to null in Metal and EDW. This is just a onetime update.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6541','Data Standardization : Fix aop_deductible amount formatting issues','Bug','2024-07-12','Rushin Shah','Datafix','edw_core','thome_coverage','aop_deductible','Updated aop_deductible with format issues to valid amounts in Metal and EDW. This is just a onetime update.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6541','Data Standardization : Fix hurricane_deductible amount formatting issues','Bug','2024-07-12','Rushin Shah','Datafix','edw_core','thome_coverage','hurricane_deductible','Updated hurricane_deductible with format issues to valid amounts in Metal and EDW. This is just a onetime update.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6541','Data Standardization : Fix water_deductible amount formatting issues','Bug','2024-07-12','Rushin Shah','Datafix','edw_core','thome_coverage','water_deductible','Updated water_deductible with format issues to valid amounts in Metal and EDW. This is just a onetime update.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6541','Data Standardization : Fix wildfire_deductible amount formatting issues','Bug','2024-07-12','Rushin Shah','Datafix','edw_core','thome_coverage','wildfire_deductible','Updated wildfire_deductible with format issues to valid amounts in Metal and EDW. This is just a onetime update.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6541','Data Standardization : Fix wind_or_hailstorm_deductible amount formatting issues','Bug','2024-07-12','Rushin Shah','Datafix','edw_core','thome_coverage','wind_or_hailstorm_deductible','Updated wind_or_hailstorm_deductible with format issues to valid amounts in Metal and EDW. This is just a onetime update.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6496','Data Standardization : Metal field name update (UninsuredUnderinsuredMotoristLiabilityForSecondaryInsured)','Bug','2024-07-12','Rushin Shah','Datafix','edw_core','','','This is a metal field name issue.  Removed the extra space from field "UninsuredUnderinsuredMotorist LiabilityForSecondaryInsured" in Metal.  This is a just a onetime update.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30344','VRE SC Home Policies : 5 policies have 0 in hurricane_deductible and wind_or_hailstorm_deductible','Bug','2024-07-12','Rushin Shah','Datafix','edw_core','','','These were fixed in Metal and EDW as part of the ongoing data standardization project for home.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30479','HO100174069 & HOX10000137: What are the wind deductibles?','Bug','2024-07-12','Rushin Shah','Datafix','edw_core','','','These were fixed in Metal and EDW as part of the ongoing data standardization project for home.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI31175','HO100125881-02: Renewal processed in Metal shows wind deductibles as 0, instead of NULL','Bug','2024-07-12','Yunus Mohammed','Datafix','edw_core','','','These were fixed in Metal and EDW as part of the ongoing data standardization project for home.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30347','19 policies show wind_derived_deductible = ''Exclude'' and exclude_wind_in is either blank or ''No''','Bug','2024-07-12','Rushin Shah','Datafix','edw_core','','','These were fixed in Metal and EDW as part of the ongoing data standardization project for home.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI28774','Exclude Wind migration issues','Bug','2024-07-12','Rushin Shah','Datafix','edw_core','','','These were fixed in Metal and EDW as part of the ongoing data standardization project for home.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30335','HO100169129 - What is the Windstorm or Hail Deductible on this policy?','Bug','2024-07-12','Rushin Shah','Datafix','edw_core','','','These were fixed in Metal and EDW as part of the ongoing data standardization project for home.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30478','HO49397716636-03: exclude_wind_in is No but deductible is empty in EDW & on Metal UI','Bug','2024-07-12','Rushin Shah','Datafix','edw_core','','','These were fixed in Metal and EDW as part of the ongoing data standardization project for home.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30703','HO100204853-03: Hurricane or Named Storm Deductible seems to be missing in Metal','Bug','2024-07-12','Rushin Shah','Datafix','edw_core','','','These were fixed in Metal and EDW as part of the ongoing data standardization project for home.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI31061','HOX10011664-01: What is "Other" wind_or_hailstorm_deductible and wind_derived_deductible in EDW?','Bug','2024-07-12','Yunus Mohammed','Datafix','edw_core','','','These were fixed in Metal and EDW as part of the ongoing data standardization project for home.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI31072','HOX10013298: Where is wind/hail deductible stored in EDW?','Bug','2024-07-12','Yunus Mohammed','Datafix','edw_core','','','These were fixed in Metal and EDW as part of the ongoing data standardization project for home.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI31112','HO10005779-03 - Lyn Comfort - AV2 to Metal, Info Did Not Migrate','Bug','2024-07-12','Yunus Mohammed','Datafix','edw_core','','','These were fixed in Metal and EDW as part of the ongoing data standardization project for home.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI31189','HOX10004852-02: "Other" suddenly appears for wind_or_hailstorm_deductible on endorsement, but Dec page still shows no deductible','Bug','2024-07-12','Yunus Mohammed','Datafix','edw_core','','','These were fixed in Metal and EDW as part of the ongoing data standardization project for home.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30473','3 policy records where exclude_wind_in = Yes and wind_derived_deductible is "0.02" or "AOP Applies"','Bug','2024-07-12','Rushin Shah','Datafix','edw_core','','','These were fixed in Metal and EDW as part of the ongoing data standardization project for home.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI32662','HO100251794 (all terms). City should be "Brookline", not "Broookline"','Bug','2024-07-12','Yunus Mohammed','Datafix','edw_core','thome_location','city_nm','Updated city name for one policy','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6491/VI32648','Cape analytics view is unavailable to query','Bug','2024-07-12','Hernando Garcia','Modification','edw_core','vcapeanalytics','','Fixed procedure to resolve the issue','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5078','Add primary_location_in to tpel_location','Enhancement','2024-07-12','Tuba Mohsin','Addition','edw_core','tpel_location','primary_location_in','Created new column','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5078','Add primary_location_in to tpel_location','Enhancement','2024-07-12','Tuba Mohsin','Addition','edw_core','tquote_pel_location','primary_location_in','Created new column','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5751/VI30734','NC Auto Policy Data fix','Bug','2024-07-12','Sandeep Gundreddy','Datafix','edw_core','','','Deleted and rekeyed(by VC team) 29 NC Auto transactions so that the premium gets reflected appropriately under optional coverages (instead of taxes).Transaction issue date is updated to the original transaction issue date.This is just a onetime update.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI32672','Change County to Norfolk from Burlington  for changed on -01 term.','Bug','2024-07-12','Yunus Mohammed','Datafix','edw_core','thome_location','county_nm','Updated county name for one policy','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD4783','Fix tpolicy/policy_term for Oneshield policies','Bug','2024-07-12','Yunus Mohammed','Datafix','edw_core','tpolicy','policy_term','Fixed procedure to update the policy term associated with OS data that had invalid values.  This is just a onetime update.  ','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29830/AD5988','Add raterpipdiscount for NJ Auto','Enhancement','2024-07-12','Architha Gudimalla','Addition','edw_core','tauto_vehicle_coverage','rater_pip_discount','Created new column','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29252','Backfilling of NCRB and Vault Premiums for OTC on NC Auto','Bug','2024-07-12','Architha Gudimalla','Datafix','edw_core','tauto_policy_coverage','otc_ncrb_premium_amt','Av2 data is backfilled in Metal','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29252','Backfilling of NCRB and Vault Premiums for collision on NC Auto','Bug','2024-07-12','Architha Gudimalla','Datafix','edw_core','tauto_policy_coverage','collision_ncrb_premium_amt','Av2 data is backfilled in Metal','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD4899/VI29252','Add NCRB and Vault Premiums for OTC and Collision on NC Auto','Enhancement','2024-07-12','Architha Gudimalla','Addition','edw_core','tauto_policy_coverage','otc_ncrb_premium_amt','Created new column','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD4899/VI29252','Add NCRB and Vault Premiums for OTC and Collision on NC Auto','Enhancement','2024-07-12','Architha Gudimalla','Addition','edw_core','tauto_policy_coverage','collision_ncrb_premium_amt','Created new column','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6464','Capture disabled status in tproducer/producer_status','Bug','2024-07-12','Alberto Almario','Datafix','edw_core','tproducer','producer_status','Fixed procedure to resolve the issue','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6506','Add Vehicle Unique ID for Auto Quotes','Enhancement','2024-07-12','Architha Gudimalla','Addition','edw_core','tquote_auto_vehicle','vehicle_unique_id','Created new column','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6506','Add Vehicle Unique ID for Auto Quotes','Enhancement','2024-07-12','Architha Gudimalla','Addition','edw_core','tquote_auto_vehicle_coverage','vehicle_unique_id','Created new column','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6100/VI31717','Datamart Enhancement - Add policy_history_sk','Enhancement','2024-07-12','Architha Gudimalla','Addition','edw_core','tpolicy_transaction','policy_history_sk','Created new column','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6100/VI31717','Datamart Enhancement - Add policy_history_sk','Enhancement','2024-07-12','Architha Gudimalla','Addition','edw_core','tdaily_inforce_policy','policy_history_sk','Created new column','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6100/VI31717','Datamart Enhancement - Add policy_history_sk','Enhancement','2024-07-12','Architha Gudimalla','Addition','edw_core','titem_inforce','policy_history_sk','Created new column','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6100/VI31717','Datamart Enhancement - Add policy_history_sk','Enhancement','2024-07-12','Architha Gudimalla','Addition','edw_core','titem_summary','policy_history_sk','Created new column','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6100/VI31717','Datamart Enhancement - Add policy_history_sk','Enhancement','2024-07-12','Architha Gudimalla','Addition','edw_core','tpolicy_summary','policy_history_sk','Created new column','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6100/VI31717','Datamart Enhancement - Add policy_history_sk','Enhancement','2024-07-12','Architha Gudimalla','Addition','edw_core','tpolicy_transaction_summary','policy_history_sk','Created new column','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6100/VI31717','Datamart Enhancement - Add policy_history_sk','Enhancement','2024-07-12','Architha Gudimalla','Addition','edw_core','tinternal_coverage_inforce','policy_history_sk','Created new column','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6100/VI31717','Datamart Enhancement - Add policy_history_sk','Enhancement','2024-07-12','Architha Gudimalla','Addition','edw_core','tinternal_coverage_summary','policy_history_sk','Created new column','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-29964','um_bi_policy_limit_amt not working as expected when limit_type = combined','Bug','2024-07-12','Architha Gudimalla','Datafix','edw_core','tauto_policy_coverage','um_bi_policy_limit_amt','This is a migration issue. um_bi_policy_limit_amt is a column related to limit_type = Split. This was incorrectly populated with data related to limit_type = combined. Data fix was applied to clear the data.  This is just a one time update.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-29965','combined_uninsured_motorist_limit_amt not working as expected when limit_type = split','Bug','2024-07-12','Architha Gudimalla','Datafix','edw_core','tauto_policy_coverage','combined_uninsured_motorist_limit_amt ','This is a migration issue. combined_uninsured_motorist_limit_amt is a column related to limit_type = Combined. This was incorrectly populated with data related to limit_type = split. Data fix was applied to clear the data.  This is just a one time update.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-30049','UM options are invalid for SC pol AU100231831-01','Bug','2024-07-12','Architha Gudimalla','Datafix','edw_core','tauto_policy_coverage','uninsured_motorist_limit_amt','This is a migration issue. Isolated policy datafix. Datafix was applied for UM limits for policy AU100231831-01.  This is just a one time update.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-30049','UIM options are invalid for SC pol AU100231831-01','Bug','2024-07-12','Architha Gudimalla','Datafix','edw_core','tauto_policy_coverage','underinsured_motorist_limit_amt','This is a migration issue. Isolated policy datafix. Datafix was applied for UIM limits for policy AU100231831-01.  This is just a one time update.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-30046','UIM options are invalid for AU100199997','Bug','2024-07-12','Architha Gudimalla','Datafix','edw_core','tauto_policy_coverage','underinsured_motorist_limit_amt','This is a migration issue. Isolated policy datafix. Datafix was applied for UIM limits for policy AU100199997.  This is just a one time update.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-30047','combined_uninsured_motorist_limit_amt - Limit_type = split but limit_amts appear to = combined','Bug','2024-07-12','Architha Gudimalla','Datafix','edw_core','tauto_policy_coverage','combined_uninsured_motorist_limit_amt','This is a migration issue. combined_uninsured_motorist_limit_amt is a column related to limit_type = Combined. This was incorrectly populated with data related to limit_type = split. Data fix was applied to clear the data.  This is just a one time update.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-30036','bodily_injury_limit_amt - Split limits pulled in when limit type = combined','Bug','2024-07-12','Architha Gudimalla','Datafix','edw_core','tauto_policy_coverage','bodily_injury_limit_amt','This is a migration issue. bodily_injury_limit_amt is a column related to limit_type = split. This was incorrectly populated with data related to limit_type = combined. Data fix was applied to clear the data.  This is just a one time update.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-30050','uninsured_motorist_limit_amt - Cant tell UMPD limits in GA','Bug','2024-07-12','Architha Gudimalla','Datafix','edw_core','tauto_policy_coverage','uninsured_motorist_limit_amt','This is a migration issue. GA raters had 25/50/25 but metal was storing 25/50. Data fix was applied to metal data to match the raters.  This is just a one time update.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-30235','Clean up umpd_limit_amt','Bug','2024-07-12','Architha Gudimalla','Datafix','edw_core','tauto_vehicle_coverage','umpd_limit_amt','This is a migration issue. Updated UMPDLimit = Yes to 25000 and UMPDLimit = declineCoverage to Decline Coverage in Metal . This is just a one time update.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-29973','Cant tell combined limited for UMBI/UMPD in VA','Bug','2024-07-12','Architha Gudimalla','Datafix','edw_core','tauto_policy_coverage','um_bi_policy_limit_amt ','This is a migration issue. um_bi_policy_limit_amt is a column related to limit_type = split. This was incorrectly populated with data related to limit_type = combined. Data fix was applied to clear the data.  This is just a one time update.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-29973','Cant tell combined limited for UMBI/UMPD in VA','Bug','2024-07-12','Architha Gudimalla','Datafix','edw_core','tauto_policy_coverage','um_pd_policy_limit_amt','This is a migration issue. um_pd_policy_limit_amt is a column related to limit_type = split. This was incorrectly populated with data related to limit_type = combined. Data fix was applied to clear the data.  This is just a one time update.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-29959','um_pd_policy_limit_amt is contradictory/not as complete as combined_um_pd_policy_limit_amt, at least in RI','Bug','2024-07-12','Architha Gudimalla','Datafix','edw_core','tauto_policy_coverage','combined_um_pd_policy_limit_amt','This is a migration issue. combined_um_pd_policy_limit_amt is a column related to limit_type = comvined. This was incorrectly populated with data related to limit_type = split. Data fix was applied to clear the data.  This is just a one time update.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-29959','um_pd_policy_limit_amt is contradictory/not as complete as combined_um_pd_policy_limit_amt, at least in RI','Bug','2024-07-12','Architha Gudimalla','Datafix','edw_core','tauto_policy_coverage','um_pd_policy_limit_amt','This is a migration issue. um_pd_policy_limit_amt is a column related to limit_type = split. This was incorrectly populated with data related to limit_type = combined. Data fix was applied to clear the data.  This is just a one time update.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-30010','AUX10001082 did not migrate limits correctly','Bug','2024-07-12','Architha Gudimalla','Datafix','edw_core','tauto_policy_coverage','','This is a migration issue. AU policy limits did not migrate correctly. Data fix was applied to correct the data.  This is just a one time update.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-29924','AUX10003661 PD & UM limits did not migrate','Bug','2024-07-12','Architha Gudimalla','Datafix','edw_core','tauto_policy_coverage','','This is a migration issue. AU policy limits did not migrate correctly. Data fix was applied to correct the data.  This is just a one time update.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-30025','AUX10005980 has a split limit type but the dec has combined','Bug','2024-07-12','Architha Gudimalla','Datafix','edw_core','tauto_policy_coverage','','This is a migration issue. Data fix to update Limit type to combined was applied.  This is just a one time update.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-30012','AU100051563-01 missing UIM limits, where is PD limit in SC?','Bug','2024-07-12','Architha Gudimalla','Datafix','edw_core','tauto_policy_coverage','combined_uninsured_motorist_limit_amt','This is a migration issue. combined_uninsured_motorist_limit_amt is a column related to limit_type = Combined. This was incorrectly populated with data related to limit_type = split. Data fix was applied to clear the data.  This is just a one time update.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-31135','Missing um_pd_policy_limit','Bug','2024-07-12','Architha Gudimalla','Datafix','edw_core','tauto_vehicle_coverage','umpd_limit_amt','This is a migration issue. Metal had data stored which is not matching the rates. Data fix was applied to match the data to the rater.  This is just a one time update.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-31251',' Extended Towing and Labor - Datafix based on vehicle type, state and effective date','Bug','2024-07-12','Architha Gudimalla','Datafix','edw_core','tauto_vehicle_coverage','extended_towing_and_labor_in','This is a one time update. Rules were provided to update the data to null based on vehicle type, state and NB/RN effective dates.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-31251','Emergency Movement - Datafix based on state and effective date','Bug','2024-07-12','Architha Gudimalla','Datafix','edw_core','tauto_policy_coverage','emergency_movement_coverage_in','This is a one time update. Rules were provided to update the data to null based on state and NB/RN effective dates.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-31251','Physical Damage Deductible Adjustment - Datafix based on state and effective date','Bug','2024-07-12','Architha Gudimalla','Datafix','edw_core','tauto_policy_coverage','physical_damage_deductible_adjustment','This is a one time update. Rules were provided to update the data to null based on state and NB/RN effective dates.','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29830/AD5988','Add raterpipdiscount for NJ Auto','Bug','2024-07-12','Architha Gudimalla','Datafix','edw_core','tauto_vehicle_coverage','rater_pip_discount','Av2 data is backfilled in Metal','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29830/AD5988','delete raterpipdiscount from tauto_policy_coverage','Enhancement','2024-07-12','Architha Gudimalla','Deletion','edw_core','tauto_policy_coverage','rater_pip_discount','deleted from tauto_policy_coverage and added to tauto_vehicle_coverage','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29830/AD5988','delete raterpipdiscount from tquote_auto_policy_coverage','Enhancement','2024-07-12','Architha Gudimalla','Deletion','edw_core','tquote_auto_policy_coverage','rater_pip_discount','deleted from tquote_auto_policy_coverage and added to tquote_auto_vehicle_coverage','14','Yes','2024-07-15',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI32622','Agency Contact Email not updating in EDW','Bug','2024-07-12','Hernando Garcia','Datafix','edw_core','tbroker','broker_email','Updated logic in Azure Data factory to capture any  broker related changes(processed in Metal) accurately in EDW','14','Yes','2024-07-15',getdate(),getdate());