-- tedw_release_summary
INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 08/05/2024 :</span>
<h4 style="margin-top: 0;">This release includes the following:</h4>
<ol>
    <li>Enhancements - 4
        <ul>
			<li>External Integrations - Created a new automated data feed to RedZone</li>
			<li>Added Metal 08/03 release related 1 new column for Auto</li>
			<li>Added Metal 08/03 release related 1 new column for Home</li>
			<li>Added vehicle_deleted_in column to pel vehicle table </li>
		</ul>
    </li>
    <li>Bug tickets - 17
        <ul>
			<li>Updated non renewal reason for PEL policies from NON-RENEWAL OF PRIMARY PERSONAL LIABILITY INSURANCE to FAILURE TO MAINTAIN PRIMARY PERSONAL LIABILITY INSURANCE as per UW request </li>
			<li>Datamart Update - Modified date logic to include data as of sysdate-1 instead of sysdate for tdaily_inforce_policy, titem_inforce, titem_summary, tpolicy_summary, tpolicy_transaction_summary, tinternal_coverage_inforce, tinternal_coverage_summary tables</li>
			<li>Data Standardization : Fixed exclude_wind_in for Home and Condo policies to align with Product config. This resolved 7 tickets. </li>
			<li>Data Standardization : Fixed uninsured_motorist_limit_amt and underinsured_motorist_limit_amt for Auto policies to align with Product config</li>
			<li>Data Standardization : Fixed agreed_value_amt for Auto policies which had formatting issues</li>
			<li>Updated expiration date for one policy </li>
			<li>Updated insured name for one policy </li>
			<li>Updated city name for one policy </li>
			<li>Updated policy term for a few renewal policies </li>
			<li>Updated VIN number for 2 vehciles </li>
			<li>Updated year built, construction type, roof covering and roofShape for one policy </li>
			<li>Payment type name on workday claim payments feed changed from Loss (Expense A&O) to Loss (Expense - A&O) </li>
			<li>Updated stored procedure logic to capture refund expense payment cancellations accurately in tclaim_transaction table (only 2 claim transactions are impacted) </li>
			<li>Updated stored procedure logic to fetch accurate broker information for OS policies </li>
			<li>Updated transaction status to issued for 4 policies that were bound but never issued </li>
			<li>Deleted duplicate cancellation transaction for one policy </li>
		</ul>
    </li>
</ol>
'
,'Yes'
,'2024-08-05'
,getdate()
,getdate()
)
;

-- tedw_release_note

INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI31169/VI31089/VI31370/VI30491/VI30486/VI31070/VI29069','Various tickets associated with exclude_wind_in for Home policies','Bug','2024-08-02','Rushin Shah','Datafix','edw_core','thome_additional_coverage','exclude_wind_in','These were fixed in Metal and EDW as part of the ongoing data standardization project for home.','15','Yes','2024-08-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6662','Metal 08/03 release related columns','Enhancement','2024-08-02','Tuba Mohsin','Addition','edw_core','tauto_policy_coverage','enhanced_underinsured_motorist_coverage_in','Created new column','15','Yes','2024-08-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6662','Metal 08/03 release related columns','Enhancement','2024-08-02','Tuba Mohsin','Addition','edw_core','tquote_auto_policy_coverage','enhanced_underinsured_motorist_coverage_in','Created new column','15','Yes','2024-08-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6662','Metal 08/03 release related columns','Enhancement','2024-08-02','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','contents_extended_replacement_cost_limit_amt','Created new column','15','Yes','2024-08-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6662','Metal 08/03 release related columns','Enhancement','2024-08-02','Tuba Mohsin','Addition','edw_core','tquote_home_additional_coverage','contents_extended_replacement_cost_limit_amt','Created new column','15','Yes','2024-08-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5210','Vehicle Deleted Indicator needs to be added to tpel_vehicle table','Enhancement','2024-08-02','Rushin Shah','Addition','edw_core','tpel_vehicle','vehicle_deleted_in','Created new column','15','Yes','2024-08-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI32849','Code Deployment for Pending non-renewal reasons in Metal','Bug','2024-07-19','Sandeep Gundreddy','Datafix','edw_core','tpolicy','non_renewal_note_desc','Updated non renewal reason from ''NON-RENEWAL OF PRIMARY PERSONAL LIABILITY INSURANCE'' to ''FAILURE TO MAINTAIN PRIMARY PERSONAL LIABILITY INSURANCE'' as per UW request. This is just one time update','15','Yes','2024-08-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI32609','Need effective date corrected in Metal - CO200024755 - Jennifer Jones','Bug','2024-07-22','Sandeep Gundreddy','Datafix','edw_core','tpolicy','expiration_dt','Updated expiration date to 01/05/2025 as per the request. This is just a onetime update.','15','Yes','2024-08-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29275','Insureds name is blank under policy# EX100266112-01. As a result policy is not going to Majesco','Bug','2024-07-23','Sandeep Gundreddy','Datafix','edw_core','tpolicy','insured_nm','Updated insured name for policy - EX100266112-01 as per the request. This is just a onetime update.','15','Yes','2024-08-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI30417','Quote_term & policy_term incorrect for some renewals','Bug','2024-07-24','Sandeep Gundreddy','Datafix','edw_core','tpolicy','policy_term','This is a migration issue. Updated data in Metal and EDW. This is just a onetime update.','15','Yes','2024-08-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI32880','Agreed value not printing on dec pages','Bug','2024-07-24','Architha Gudimalla','Datafix','edw_core','tauto_vehicle_coverage','agreed_value_amt','Agreed value prints as 0 due to decimals in the value. Applied datafix by removing the decimals','15','Yes','2024-08-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI21229','HO100062445: policyImageId 328423 is missing YearBuilt, constructionType, reportedRoofcover, roofCovering, roofShape','Bug','2024-08-02','Yunus Mohammed','Datafix','edw_core','thome_coverage','built_year','Updated build_year for one policy. This is just a onetime update.','15','Yes','2024-08-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI21229','HO100062445: policyImageId 328423 is missing YearBuilt, constructionType, reportedRoofcover, roofCovering, roofShape','Bug','2024-08-02','Yunus Mohammed','Datafix','edw_core','thome_coverage','construction_type','Updated construction_type for one policy. This is just a onetime update.','15','Yes','2024-08-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI21229','HO100062445: policyImageId 328423 is missing YearBuilt, constructionType, reportedRoofcover, roofCovering, roofShape','Bug','2024-08-02','Yunus Mohammed','Datafix','edw_core','thome_coverage','roof_covering','Updated roof_covering for one policy. This is just a onetime update.','15','Yes','2024-08-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI21229','HO100062445: policyImageId 328423 is missing YearBuilt, constructionType, reportedRoofcover, roofCovering, roofShape','Bug','2024-08-02','Yunus Mohammed','Datafix','edw_core','thome_coverage','roof_geometry','Updated roof_geometry for one policy. This is just a onetime update.','15','Yes','2024-08-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6518/VI31827','Fix 2 edw_core.tclaim_feature.item_sk where VIN is different between claims tables & policy tables in EDW','Bug','2024-08-02','Yunus Mohammed','Datafix','edw_core','tclaim_feature','item_sk','Updated ebao staging table for 2 VIN numbers. This is just a onetime update.','15','Yes','2024-08-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI27528','city_nm includes state & zip code for manual policies','Bug','2024-08-02','Yunus Mohammed','Datafix','edw_core','thome_location','city_nm','Updated city name for one policy. This is just a onetime update.','15','Yes','2024-08-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6722','Workday claim payment - Update Loss (Expense A&O) to Loss (Expense - A&O)','Bug','2024-08-02','Yunus Mohammed','Datafix','edw_integration','claim_workday_payment_feed','paymenttype','Payment type name on workday claim payments feed changed from "Loss (Expense A&O)" to "Loss (Expense - A&O)"','15','Yes','2024-08-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6571','Refinement of tclaim transaction table ','Bug','2024-08-02','Yunus Mohammed','Datafix','edw_integration','tclaim_transaction','refund_expense_paid_amt','Updated stored procedure logic to capture refund expense payment cancellations accurately in tclaim_transaction table. (only 2 claim transactions are impacted, reported by Andrew Chan)','15','Yes','2024-08-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6555','Clean up tbroker table for OS policies / brokers','Bug','2024-08-02','Yunus Mohammed','Datafix','edw_core','tbroker','','Updated stored procedure logic to fetch accurate broker information for OS policies','15','Yes','2024-08-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6766','Datamart  Update - Updated date logic','Bug','2024-08-02','Architha Gudimalla','Modification','edw_core','tpolicy_transaction','','Updated date logic to include data as of sysdate-1 instead of sysdate','15','Yes','2024-08-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6766','Datamart  Update - Updated date logic','Bug','2024-08-02','Architha Gudimalla','Modification','edw_core','tdaily_inforce_policy','','Updated date logic to include data as of sysdate-1 instead of sysdate','15','Yes','2024-08-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6766','Datamart  Update - Updated date logic','Bug','2024-08-02','Architha Gudimalla','Modification','edw_core','titem_inforce','','Updated date logic to include data as of sysdate-1 instead of sysdate','15','Yes','2024-08-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6766','Datamart  Update - Updated date logic','Bug','2024-08-02','Architha Gudimalla','Modification','edw_core','titem_summary','','Updated date logic to include data as of sysdate-1 instead of sysdate','15','Yes','2024-08-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6766','Datamart  Update - Updated date logic','Bug','2024-08-02','Architha Gudimalla','Modification','edw_core','tpolicy_summary','','Updated date logic to include data as of sysdate-1 instead of sysdate','15','Yes','2024-08-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6766','Datamart  Update - Updated date logic','Bug','2024-08-02','Architha Gudimalla','Modification','edw_core','tpolicy_transaction_summary','','Updated date logic to include data as of sysdate-1 instead of sysdate','15','Yes','2024-08-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6766','Datamart  Update - Updated date logic','Bug','2024-08-02','Architha Gudimalla','Modification','edw_core','tinternal_coverage_inforce','','Updated date logic to include data as of sysdate-1 instead of sysdate','15','Yes','2024-08-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6766','Datamart  Update - Updated date logic','Bug','2024-08-02','Architha Gudimalla','Modification','edw_core','tinternal_coverage_summary','','Updated date logic to include data as of sysdate-1 instead of sysdate','15','Yes','2024-08-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI33120','Update transaction status to Issued for 4 policies','Bug','2024-08-02','Sandeep Gundreddy','Datafix','edw_core','tpolicy_transaction','policy_transaction_type_sk','Updated transaction status to Issued for 4 policies HO100264428,HO200024714,EX100262511-02,HO100030943-03 that were bound but never issued. This is isolated issue in Metal caused in the early days. This is just one time update. Validation has been added to monitor it going forward.','15','Yes','2024-08-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6528','External Integrations - RedZone Feed','Enhancement','2024-08-02','Sandeep Gundreddy','Addition','edw_integration','policy_redzone_feed','','Implemented changes associated with integration of RedZone feed','15','Yes','2024-08-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6773','Data Standardization : Fix UM limit amount formatting issues','Bug','2024-08-02','Architha Gudimalla','Datafix','edw_core','tauto_policy_coverage','uninsured_motorist_limit_amt','This is a migration issue. Isolated policies datafix. This is just a one time update.','15','Yes','2024-08-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6772','Data Standardization : Fix UIM limit amount formatting issues','Bug','2024-08-02','Architha Gudimalla','Datafix','edw_core','tauto_policy_coverage','underinsured_motorist_limit_amt','This is a migration issue. Isolated policies datafix. This is just a one time update.','15','Yes','2024-08-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI33122','Duplicate cancellation for AU100056279-03 in Metal','Bug','2024-08-02','Sandeep Gundreddy','Datafix','edw_core','tpolicy_transaction','','Deleted duplicate cancellation transaction in Metal and EDW. This is an isolated issue. This is just a onetime update. Validation has been added to monitor it going forward.','15','Yes','2024-08-05',getdate(),getdate());
