-- tedw_release_summary
INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 08/19/2024 :</span>
<h4 style="margin-top: 0;">This release includes the following:</h4>
<ol>
    <li>Enhancements - 10
        <ul>
			<li>Metal 08/17 Release - Task related enhancements- field- task_priority data type change</li>
			<li>Performed testing related to Metal 08/17 release. No new fields were added as part of this release</li>
                     a) South Dakota Home/Condo<br>
                     b) Georgia PEL Base rates and factor revision<br> 
			<li>Datamart Enhancement - Added product_nm, renewal_quote_note_desc, pending_non_renewal_ct, agency_primary_location_state_cd, expiring_rate_on_line, expiring_sixty_day_rate_on_line, renewal_sixty_day_rate_on_line and renewal_quote_rate_on_line to trenewal_summary table</li>
			<li>Datamart Enhancement - Updated trenewal_summary stored procedure logic to accurately calculate offered or not taken quote count</li>
			<li>Integration of forms data into EDW by creating new tpolicy_form and tquote_form tables</li>
			<li>Data quality monitoring enhancements - Added 2 new validations to check for the following</li> 
                    a) Duplicate cancelled transactions<br> 
                    b) Policies in bound status for more than 15 days</br>
			<li>Created new stored procedure logic to update underwriter_nm in tquote_history based on updates in Metal. This logic was added because underwriter_nm can be updated outside of a transaction in Metal now until quote is issued</li>
			<li>Added watercraft_deleted_in column to tpel_watercraft table</li>
			<li>Added producer_role column to tproducer table</li>
			<li>Added garage_unique_id column to tauto_garage_location and tquote_auto_garage_location table</li>
			<li>Added auto_vehicle_sk and additional_interest_deleted_in column to tadditional_interest and tquote_additional_interest tables</li>
		</ul>
    </li>
    <li>Bug tickets - 25
        <ul>
			<li>Data Standardization : Update wind_derived_deductible formatting issues for Home policies </li>
			<li>Data Standardization : Fixed earthquake_deductible_amt formatting issues for Collection policies </li>
			<li>Data Standardization : Corrected not_taken_reason_desc from</li>
                    a) Competitor quote has border coverage definition. to Competitor quote has broader coverage definition.<br>
                    b) Transaction not needed to Transaction not needed<br>
			<li>Updated stored procedure to fetch customer_sk from tquote tables instead of tpolicy table for complete and accurate details in tnote table</li>
			<li>Resolved 5 tickets associated with IVANS data feed </li>
			<li>Resolved 3 tickets associated with the stored procedure fix applied to the manuscripts table </li>
			<li>Resolved 4 tickets associated with wind deductible fields </li>
			<li>Resolved 3 tickets associated with address line and county fields </li>
			<li>Resolved 1 ticket associated with construction type field </li>
			<li>Resolved 1 ticket associated with fire protection field </li>
			<li>Resolved 1 ticket associated with BCEG Credit Percent field </li>
			<li>Resolved 1 ticket associated with workercompensation_liability_parttime_employees_ct field </li>
			<li>Created alert for given set of requested NJ policies </li>
			<li>Updated agreed_value_amt data type to capture accurate data</li>
		</ul>
    </li>
</ol>
'
,'Yes'
,'2024-08-19'
,getdate()
,getdate()
)
;

-- tedw_release_note

INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6848/VI23286','HurricaneDeductible changed incorrectly on Cancellation for  HO100249181-05','Bug','2024-08-06','Yunus Mohammed','Datafix','edw_core','thome_coverage','hurricane_deductible','Updated hurricane deductible for one policy in Metal and EDW. This is just a onetime update.','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6849/VI31113','Populate county for transactions where county dropped off. (8 policies)','Bug','2024-08-06','Yunus Mohammed','Datafix','edw_core','thome_location','county_nm','Updated county name for 8 policies in Metal and EDW. This is just a onetime update.','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6850/VI31119','Policy is in a county that is not eligible for hurricane coverage, but shows a deductible.','Bug','2024-08-06','Yunus Mohammed','Datafix','edw_core','thome_coverage','hurricane_deductible','Updated hurricane deductible for 2 policies in Metal and EDW. This is just a onetime update.','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6847/VI31829','Fix manual deductibles','Bug','2024-08-06','Rushin Shah','Datafix','edw_core','thome_coverage','aop_deductible_manual','Updated aop deductible manual for one policy in Metal and EDW. This is just a onetime update.','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6847/VI31829','Fix manual deductibles','Bug','2024-08-06','Rushin Shah','Datafix','edw_core','thome_coverage','water_deductible_manual','Updated water deductible manual for 3 policies in Metal and EDW. This is just a onetime update.','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6847/VI31829','Fix manual deductibles','Bug','2024-08-06','Rushin Shah','Datafix','edw_core','thome_coverage','wildfire_deductible_manual','Updated wildfire deductible for 7 policies in Metal and EDW. This is just a onetime update.','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6846/VI30696','Data Standardization : Not_taken_reason is inconsistent in tquote_hitory table','Bug','2024-08-06','Rushin Shah','Datafix','edw_core','tquote_history','not_taken_reason_desc','Updated not_taken_reason_desc from a) Competitor quote has border coverage definition. to Competitor quote has broader coverage definition. b) Transaction not needed to Transaction not needed.  This is just a onetime update.','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6845/VI32706','Please correct missing or null construction_type (11 records) on HO policies (ISS Reporting)','Bug','2024-08-06','Rushin Shah','Datafix','edw_core','thome_coverage','construction_type','Updated construction type for 11 policies in Metal and EDW. This is just a onetime update.','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI32732','Fire_protection incorrectly stored in protection_class','Bug','2024-08-06','Rushin Shah','Datafix','edw_core','thome_coverage','fire_protection','Updated fire protection for 3 policies in Metal and EDW. This is just a onetime update.','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI32408/VI32899/VI33188/VI33056','IVANS Policy Resend Request','Bug','2024-08-06','Rushin Shah','Datafix','edw_integration','','','Resent 26 policies to IVANS across all products.  This is just a onetime resent request.','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6878','tvalidation_sql - update target counts','Bug','2024-08-13','Yunus Mohammed','Datafix','edw_core','tvalidation_sql','','Updated target counts for tvalidation_sql table.  This is just a onetime update','16','No','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI32693','Policy appears not to have work comp/employee coverage, but workercompensation_liability_parttime_employees_ct = ''Yes''','Bug','2024-08-06','Rushin Shah','Datafix','edw_core','thome_additional_coverage','workercompensation_liability_parttime_employees_ct','Updated workercompensation_liability_parttime_employees_ct for 7 policies in Metal and EDW. This is just a onetime update.','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI33248','Update address line 1 and mortgagee name for 2 policies','Bug','2024-08-06','Yunus Mohammed','Datafix','edw_core','thome_location','address_line_1','Updated address_line_1 for one policy in Metal and EDW. This is just a onetime update.','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI33248','Update address line 1 and mortgagee name for 2 policies','Bug','2024-08-06','Yunus Mohammed','Datafix','edw_core','tmortgagee','mortgagee_nm','Updated mortgagee_nm for one policy in Metal and EDW. This is just a onetime update.','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI31113','Please populate county for transactions where county dropped off','Bug','2024-08-06','Yunus Mohammed','Datafix','edw_core','thome_location','county_nm','Updated county_nm for 7 policies in Metal and EDW. This is just a onetime update.','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI31468 / VI31469 / VI31470 ','NULL manuscripts','Bug','2024-08-06','Yunus Mohammed','Datafix','edw_core','tmanuscript','','Updated stored procedure logic to fetch accurate manuscript details','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI33329','NJ Metal Alert','Bug','2024-08-15','Sandeep Gundreddy','Datafix','edw_core','tnote','','Added alerts in Metal as per the request','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6835/VI32932','Update BCEGCreditPercent for 4 policies','Bug','2024-08-15','Architha Gudimalla','Datafix','edw_core','thome_coverage','bceg_credit_pc','Updated BCEG Credit Percent for 4 policies in Metal and EDW.  This is just a onetime update.','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6835/VI29110','Cannot tell wind deductible for HOX10004852-02, HOX10012963-01, HOX10014159','Bug','2024-08-15','Architha Gudimalla','Datafix','edw_core','thome_coverage','wind_or_hailstorm_deductible_manual','Updated WindstormOrHailDeductible Manual for 4 policies in Metal and EDW.  This is just a onetime update.','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI32342','Datamart Enhancement - trenewal_summary','Enhancement','2024-08-16','Architha Gudimalla','Addition','edw_core','trenewal_summary','product_nm','Created new column','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI32342','Datamart Enhancement - trenewal_summary','Enhancement','2024-08-16','Architha Gudimalla','Addition','edw_core','trenewal_summary','renewal_quote_note_desc','Created new column','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI32342','Datamart Enhancement - trenewal_summary','Enhancement','2024-08-16','Architha Gudimalla','Addition','edw_core','trenewal_summary','pending_non_renewal_ct','Created new column','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI32342','Datamart Enhancement - trenewal_summary','Enhancement','2024-08-16','Architha Gudimalla','Addition','edw_core','trenewal_summary','agency_primary_location_state_cd','Created new column','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI31614','Datamart Enhancement - trenewal_summary','Enhancement','2024-08-16','Architha Gudimalla','Modification','edw_core','trenewal_summary','offered_or_not_taken_quote_ct','Updated stored procedure logic to accurately calculate offered or not taken quote count','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI32405','Datamart Enhancement - trenewal_summary','Enhancement','2024-08-16','Architha Gudimalla','Addition','edw_core','trenewal_summary','expiring_rate_on_line','Created new column','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI32405','Datamart Enhancement - trenewal_summary','Enhancement','2024-08-16','Architha Gudimalla','Addition','edw_core','trenewal_summary','expiring_sixty_day_rate_on_line','Created new column','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI32405','Datamart Enhancement - trenewal_summary','Enhancement','2024-08-16','Architha Gudimalla','Addition','edw_core','trenewal_summary','renewal_sixty_day_rate_on_line','Created new column','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI32405','Datamart Enhancement - trenewal_summary','Enhancement','2024-08-16','Architha Gudimalla','Addition','edw_core','trenewal_summary','renewal_quote_rate_on_line','Created new column','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5243','Integrate forms data into EDW','Enhancement','2024-08-16','Tuba Mohsin','Addition','edw_core','tpolicy_form','','Created new table','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD5243','Integrate forms data into EDW','Enhancement','2024-08-16','Tuba Mohsin','Addition','edw_core','tquote_form','','Created new table','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6885','Addition of watercraft_deleted_in to tpel_watercraft table','Enhancement','2024-08-16','Rushin Shah','Addition','edw_core','tpel_watercraft','watercraft_deleted_in','Created new column','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6820','Addition of producer_role to tproducer table','Enhancement','2024-08-16','Architha Gudimalla','Addition','edw_core','tproducer','producer_role','Created new column','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6809','Addition of garage_unique_id to auto garage location table','Enhancement','2024-08-16','Architha Gudimalla','Addition','edw_core','tauto_garage_location','garage_unique_id','Created new column','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6809','Addition of garage_unique_id to auto garage location table','Enhancement','2024-08-16','Architha Gudimalla','Addition','edw_core','tquote_auto_garage_location','garage_unique_id','Created new column','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6675','Addition of vehicle data to tadditional_interest table','Enhancement','2024-08-16','Rushin Shah','Addition','edw_core','tadditional_interest','auto_vehicle_sk','Created new column','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6675','Addition of vehicle data to tadditional_interest table','Enhancement','2024-08-16','Rushin Shah','Addition','edw_core','tadditional_interest','additional_interest_deleted_in','Created new column','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6675','Addition of vehicle data to tadditional_interest table','Enhancement','2024-08-16','Rushin Shah','Addition','edw_core','tquote_additional_interest','quote_auto_vehicle_sk','Created new column','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6675','Addition of vehicle data to tadditional_interest table','Enhancement','2024-08-16','Rushin Shah','Addition','edw_core','tquote_additional_interest','additional_interest_deleted_in','Created new column','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6790','Data Standardization : Fix earthquake_deductible_amt formatting issues for Collection policies','Bug','2024-08-06','Rushin Shah','Datafix','edw_core','tcollection_coverage','earthquake_deductible_amt','Updated earthquake_deductible_amt with format issues to valid amounts in Metal and EDW. This is just a onetime update.','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6871','Data Standardization : Update wind_derived_deductible formatting issues for Home policies','Bug','2024-08-16','Yunus Mohammed','Datafix','edw_core','thome_coverage','wind_derived_deductible','Updated stored procedure to have standardized value for wind_derived_deductible','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6892/VI33103','Create new ETL to fix underwriter_nm issue in tquote_history','Bug','2024-08-16','Architha Gudimalla','Datafix','edw_core','tquote_history','underwriter_nm','Created new stored procedure logic to update underwriter_nm in tquote_history based on updates in Metal','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6830/VI32055','Request to add customer id to notes table','Bug','2024-08-16','Yunus Mohammed','Datafix','edw_core','tnote','customer_sk','Updated stored procedure to fetch customer_sk from tquote tables instead of tpolicy table for complete and accurate details','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6786','IVANS Data Fixes','Bug','2024-08-16','Rushin Shah','Datafix','edw_integration','policy_ivans_auto_feed','','Updated stored procedure to have accurate populate limit & deductible for each vehicle and additional interest for each applicable vehicle ','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6786','IVANS Data Fixes','Bug','2024-08-16','Rushin Shah','Datafix','edw_integration','policy_ivans_home_feed','','Updated stored procedure to have accurate premium for all scheduled items','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6786','IVANS Data Fixes','Bug','2024-08-16','Rushin Shah','Datafix','edw_integration','policy_ivans_pel_feed','','Updated stored procedure to have accurate watercraft details','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6903/VI33366','AgreedValue with decimals','Bug','2024-08-15','Architha Gudimalla','Datafix','edw_core','tauto_vehicle_coverage','agreed_value_amt','Updated agreed_value_amt data type in Metal and EDW.  This is just a onetime update.','16','Yes','2024-08-19',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6906','Metal 08/17 Release - Task related enhancements','Enhancement','45520','Sandeep Gundreddy','Modification','edw_core','ttask','task_priority','Modified data type to varchar','16','Yes','2024-08-19',getdate(),getdate());