-- tedw_release_summary
INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 09/09/2024 :</span>
<h4 style="margin-top: 0;">This release includes the following:</h4>
<ol>
    <li>Enhancements - 5
        <ul>
			<li>Created view to capture a few LC360 related fields requested by the analytics team</li>
			<li>External Integrations : Enhance the red zone data feed to capture 11 additional columns</li>
			<li>Added Metal 09/07 release related 14 new columns for Home & Condo</li>
			<li>Added term_no column to tpolicy and tquote tables. Backfill will be done during next EDW refresh on 09/14</li>
			<li>Added primary_auto_vehicle_sk column to tauto_driver and tquote_auto_driver.Backfill will be done during next EDW refresh on 09/14</li>
		</ul>
    </li>
    <li>Bug tickets - 33
        <ul>
			<li>Data Standardization : Fixed various limit fields (DeductibleWaiverLargeLossesLimit, HomeCyberProtectionCoverageLimit, HomeSystemsProtectionLimit, HomeCyberProtectionCoverageDeductible, HomeCyberProtectionCoverage and PersoanlLiabilityimit) for Home policies. Existing data updated only in Metal. EDW will be backfilled during next EDW refresh on 09/14</li>
			<li>Data Standardization : Updated hurricane_deductible for RI Admitted policies.Existing data updated only in Metal. EDW will be backfilled during next EDW refresh on 09/14</li>
			<li>Updated stored procdure to fetch wind_derived_deductible values from "manual" wind field columns when wind fields have "other" as a value.EDW will be backfilled during next EDW refresh on 09/14</li>
			<li>Backfilled missing territory codes for a few policies based on prior policy terms.Existing data updated only in Metal. EDW will be backfilled during next EDW refresh on 09/14</li>
			<li>Updated terminated producers status to disabled as per user request</li>
			<li>Updated broker_id for one agent as per user request</li>
			<li>Resolved 7 tickets associated with roofCoverageEndorsementRV; roofCoverageEndorsementWH; roofCoverageEndorsementAP fields by making them null</li>
			<li>Resolved 5 tickets associated with all the fixes we applied for IVANS data feed </li>
			<li>Resolved 3 tickets associated with county name fields. Existing data updated only in Metal. EDW will be backfilled during next EDW refresh on 09/14 </li>
			<li>Resolved 2 tickets associated with moving policies from one customer accounts to other </li>
			<li>Resolved 2 tickets associated with updating the createddate in tnote table and loading data after 10th August</li>
			<li>Resolved 1 ticket associated with updating workercompensation_liability_parttime_employees_ct for 7 policies </li>
			<li>Resolved 1 ticket associated with updating barn_on_property_in and barn_value_amt for one policy </li>
			<li>Updated agreed_value_amt data type to capture accurate data.Existing data updated only in Metal. EDW will be backfilled during next EDW refresh on 09/14</li>
		</ul>
    </li>
</ol>
'
,'Yes'
,'2024-09-09'
,getdate()
,getdate()
)
;

-- tedw_release_note

INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6880/VI31710','Update missing rating_territory_cd','Bug','2024-09-06','Architha Gudimalla','Datafix','edw_core','thome_coverage','rating_territory_cd','Backfilling missing territory codes for a few policies based on prior policy terms.  This is just a onetime update.','17','Yes','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6903/VI33366','Agreed Value not showing on dec page','Bug','2024-08-20','Architha Gudimalla','Datafix','edw_core','tauto_vehicle_coverage','agreed_value_amt','Updated data with formatting issues with agreed value amount in Metal and EDW.  This is just a onetime update.','17','Yes','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6558','Fix createddate in note table','Bug','2024-08-23','Sandeep Gundreddy','Datafix','edw_core','tnote','note_created_ts','Updated data with incorrect createddate in Metal and EDW. This is just a onetime update.','17','Yes','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI33035','Agent name and email are listed correctly however the broker/agent name is not correct','Bug','2024-08-18','Sandeep Gundreddy','Datafix','edw_core','tquote','broker_id','Updated broker_id for one agent in Metal and EDW.  This is just a onetime update.','17','Yes','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI33402','edw_core.tnote max note_created_ts of 08/10/2024','Bug','2024-08-19','Sandeep Gundreddy','Datafix','edw_core','tnote','note_created_ts','Updated data with incorrect createddate in Metal and EDW. This is just a onetime update.','17','Yes','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29841','HO57247608036: Barn value $1,000 & barn indicator are incorrect.','Bug','2024-08-20','Rushin Shah','Datafix','edw_core','thome_coverage','barn_on_property_in','Updated data with incorrect barn_on_property_in in Metal and EDW. This is just a onetime update.','17','Yes','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29841','HO57247608036: Barn value $1,000 & barn indicator are incorrect.','Bug','2024-08-20','Rushin Shah','Datafix','edw_core','thome_coverage','barn_value_amt','Updated data with incorrect barn_value_amt in Metal and EDW. This is just a onetime update.','17','Yes','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI32683','workercompensation_liability_parttime_employees_ct = ''Yes'' ; Why is the field not numeric?','Bug','2024-08-20','Rushin Shah','Datafix','edw_core','thome_additional_coverage','workercompensation_liability_parttime_employees_ct','Updated workercompensation_liability_parttime_employees_ct for 7 policies in Metal and EDW. This is just a onetime update.','17','Yes','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI32967','Data Fix - Broker Status for Terminated Migrated Agents','Bug','2024-08-20','Sandeep Gundreddy','Datafix','edw_core','tproducer','producer_status','Updated terminated producers status to disabled as per the request. This is just a onetime update.','17','Yes','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI33445','Metal combine customer accounts ','Bug','2024-08-21','Sandeep Gundreddy','Datafix','edw_core','tpolicy','customer_id','Moved policies and quotes from customer_id - 1234542984 to 1234544092 as per the request. This is a onetime update','17','Yes','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6681','Data Standardization : Fix Cov E invalid value issues for Home policies','Bug','2024-08-23','Rushin Shah','Datafix','edw_core','thome_coverage','personal_liability_limit_amt','Updated personal_liability_limit_amt with invalid value issues to valid amounts in Metal and EDW. This is just a onetime update.','17','Yes','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6986','Data Standardization : Fix DeductibleWaiverLargeLossesLimit invalid values and $0 limit issues for Home policies','Bug','2024-08-23','Rushin Shah','Datafix','edw_core','thome_additional_coverage','deductible_waiver_large_losses_limit_amt','Updated deductible_waiver_large_losses_limit_amt with invalid value and $0 limit issues to valid amounts in Metal and EDW. This is just a onetime update.','17','Yes','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7023','Data Standardization : Fix HomeCyberProtectionCoverageLimit format value issues and $0 limit issues for Home policies','Bug','2024-08-23','Rushin Shah','Datafix','edw_core','thome_additional_coverage','home_cyber_protection_coverage_limit_amt','Updated home_cyber_protection_coverage_limit_amt with format value issues and $0 limit issues to valid amounts in Metal and EDW. This is just a onetime update.','17','Yes','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7024/VI33347','Data Standardization : Fix HomeSystemsProtectionLimit format value issues and $0 limit issues for Home policies','Bug','2024-08-23','Rushin Shah','Datafix','edw_core','thome_additional_coverage','home_systems_protection_limit_amt','Updated home_systems_protection_limit_amt with format value issues and $0 limit issues to valid amounts in Metal and EDW. This is just a onetime update.','17','Yes','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7032','Data Standardization : Fix HomeCyberProtectionCoverageDeductible with incorrect values for Home policies','Bug','2024-08-23','Rushin Shah','Datafix','edw_core','thome_additional_coverage','home_cyber_protection_coverage_deductible','Updated home_cyber_protection_coverage_deductible with incorrect values to accurate values in Metal and EDW. This is just a onetime update.','17','Yes','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7086','Data Standardization : Fix HomeCyberProtectionCoverage with incorrect indicator for Home policies','Bug','2024-08-23','Rushin Shah','Datafix','edw_core','thome_additional_coverage','home_cyber_protection_coverage_in','Updated home_cyber_protection_coverage_in with incorrect indicator to valid amounts in Metal and EDW. This is just a onetime update.','17','Yes','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI33580/VI33514/VI33416/VI29690/VI33543','Policy Resent Request','Bug','2024-08-30','Rushin Shah','Datafix','edw_integration','policy_ivans_home_feed','','Resent a few policies to IVANS after applying data fixes.  This is just a onetime update.','17','Yes','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7091','Snapsheet Migration - Create a Claim API: Create table t_pty_party in edw_stage','Enhancement','2024-09-06','Bhaskar Muthyala','Addition','edw_stage','t_clm_party','','Create t_clm_party table from eBao to utilize in Snapsheet Migration process.','17','No','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7092','Snapsheet Migration - Create a Claim API: Create table t_pty_party_type in edw_stage','Enhancement','2024-09-06','Bhaskar Muthyala','Addition','edw_stage','t_pty_party_type','','Create t_clm_party_type table from eBao to utilize in Snapsheet Migration process.','17','No','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI33684/VI33723/VI33685','Update thome_location.county_nm for few policies','Bug','2024-09-06','Yunus Mohammed','Datafix','edw_core','thome_location','county_nm','Updated county_nm for few policy in Metal and EDW.  This is just a onetime update.','17','Yes','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6943/VI31194','Update wind_Derived_Deductible column logic','Bug','2024-09-06','Yunus Mohammed','Modification','edw_core','thome_coverage','wind_derived_deductible','Updated the stored procdure to fetch values values from "manual" fields when wind fields have "other"','17','Yes','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6945','Use garage_unique_id instead of garage_location_no in auto vehicle coverage','Bug','2024-09-06','Yunus Mohammed','Modification','edw_core','tauto_vehicle_coverage','auto_garage_location_sk','Updated logic to use garage_unique_id to fetch auto_garage_location_sk in tauto_vehicle_coverage table','17','No','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6945','Use garage_unique_id instead of garage_location_no in auto vehicle coverage','Bug','2024-09-06','Yunus Mohammed','Modification','edw_core','tquote_auto_vehicle_coverage','auto_garage_location_sk','Updated logic to use garage_unique_id to fetch auto_garage_location_sk in tquote_auto_vehicle_coverage table','17','No','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7013','Home/Condo - Metal 09/07 release related columns','Enhancement','2024-09-06','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','wildfire_protection_enrollment_in','Created new column','17','Yes','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7013','Home/Condo - Metal 09/07 release related columns','Enhancement','2024-09-06','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','site_scheduling_contact_nm','Created new column','17','Yes','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7013','Home/Condo - Metal 09/07 release related columns','Enhancement','2024-09-06','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','site_scheduling_phone_no','Created new column','17','Yes','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7013','Home/Condo - Metal 09/07 release related columns','Enhancement','2024-09-06','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','site_scheduling_email','Created new column','17','Yes','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7013','Home/Condo - Metal 09/07 release related columns','Enhancement','2024-09-06','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','emergency_contact_nm','Created new column','17','Yes','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7013','Home/Condo - Metal 09/07 release related columns','Enhancement','2024-09-06','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','emergency_contact_phone_no','Created new column','17','Yes','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7013','Home/Condo - Metal 09/07 release related columns','Enhancement','2024-09-06','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','emergency_contact_email','Created new column','17','Yes','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7013','Home/Condo - Metal 09/07 release related columns','Enhancement','2024-09-06','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','gate_code','Created new column','17','Yes','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7013','Home/Condo - Metal 09/07 release related columns','Enhancement','2024-09-06','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','primary_home_risk_address','Created new column','17','Yes','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7013','Home/Condo - Metal 09/07 release related columns','Enhancement','2024-09-06','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','primary_home_policy_effective_dt','Created new column','17','Yes','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7013','Home/Condo - Metal 09/07 release related columns','Enhancement','2024-09-06','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','primary_home_policy_expiration_dt','Created new column','17','Yes','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7013','Home/Condo - Metal 09/07 release related columns','Enhancement','2024-09-06','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','primary_home_carrier_nm','Created new column','17','Yes','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7013','Home/Condo - Metal 09/07 release related columns','Enhancement','2024-09-06','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','primary_home_coverage_a_threshold','Created new column','17','Yes','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7013','Home/Condo - Metal 09/07 release related columns','Enhancement','2024-09-06','Tuba Mohsin','Addition','edw_core','tquote_home_additional_coverage','','Created 13 new columns same as policy table','17','Yes','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7013','Home/Condo - Metal 09/07 release related columns','Enhancement','2024-09-06','Tuba Mohsin','Addition','edw_core','thome_coverage','no_of_family_units_in_structures','Created new column','17','Yes','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7013','Home/Condo - Metal 09/07 release related columns','Enhancement','2024-09-06','Tuba Mohsin','Addition','edw_core','tquote_home_coverage','no_of_family_units_in_structures','Created new column','17','Yes','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI33325/VI33744/VI33742/VI33730/VI33523/VI33349/VI32978/','Roof coverage endorsement updates','Bug','2024-09-06','Architha Gudimalla','Datafix','edw_core','thome_additional_coverage','roof_covering_coverage_limitation_all_peril_loss_settlement_endorsement_in','Updated "roofCoverageEndorsementRV" or "roofCoverageEndorsementWH" or "roofCoverageEndorsementAP" to null','17','Yes','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7088/VI30860','RI April renewal printing w/Hurricane deductible when should be wind/hail','Bug','2024-08-30','Rushin Shah','Datafix','edw_integration','thome_coverage','hurricane_deductible','Updated hurricane_deductible for RI Admitted policies.  This is just a onetime update.','17','Yes','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7117','ETL - add vehicle_unique_id to tquote_pel_vehicle_rapa/tpel_vehicle_rapa','Enhancement','2024-09-06','Alberto Almario','Addition','edw_core','tpel_vehicle_rapa','vehicle_unique_id','Created new column','17','No','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7117','ETL - add vehicle_unique_id to tquote_pel_vehicle_rapa/tpel_vehicle_rapa','Enhancement','2024-09-06','Alberto Almario','Addition','edw_core','tquote_pel_vehicle_rapa','vehicle_unique_id','Created new column','17','No','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6939/VI33412','Create view in edw_core for LC360','Enhancement','2024-09-06','Architha Gudimalla','Addition','edw_core','vlc360','','Created a view to capture a few requested fields associated with LC360 data.','17','Yes','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6946/VI31639','Add Primary Vehicle to tauto_driver in EDW','Enhancement','2024-09-06','Tuba Mohsin','Addition','edw_core','tauto_driver','primary_auto_vehicle_sk','Created new column','17','Yes','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6946/VI31639','Add Primary Vehicle to tauto_driver in EDW','Enhancement','2024-09-06','Tuba Mohsin','Addition','edw_core','tquote_auto_driver','primary_auto_vehicle_sk','Created new column','17','Yes','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7045/VI33428','Add Term Number to tpolicy and tquote table','Enhancement','2024-09-06','Architha Gudimalla','Addition','edw_core','tpolicy','term_no','Created new column','17','Yes','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7045/VI33428','Add Term Number to tpolicy and tquote table','Enhancement','2024-09-06','Architha Gudimalla','Addition','edw_core','tquote','term_no','Created new column','17','Yes','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6915','External Integrations- RedZone feed enhancements','Enhancement','2024-09-06','Architha Gudimalla','Addition','edw_integration','policy_redzone_feed','','Added following 11 columns (bdm_nm; new_business_underwriter_nm; renewal_underwriter_nm; effective_dt; wildfire_protection_enrollment_in; site_scheduling_contact_nm; site_scheduling_phone_no; site_scheduling_email; emergency_contact_nm; emergency_contact_phone_no; emergency_contact_email) to the existing feed','17','Yes','2024-09-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI33041','How to rekey from HO100257732-01 to the 02 term for rnwl','Bug','2024-08-02','Sandeep Gundreddy','Datafix','edw_core','tpolicy','','Moved policies from 1234638895 to 1234611140.  This is just a onetime update.','17','Yes','2024-09-09',getdate(),getdate());