-- tedw_release_summary
INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 09/23/2024 :</span>
<h4 style="margin-top: 0;">This release includes the following:</h4>
<ol>
    <li>Enhancements - 6
        <ul>
			<li>EDW External Integrations : CLUE Property Feed (Home, Condo and Collections) goes live where we will be sending our internal claims data to Lexis Nexis.</li>
			<li>Workday enhancements : Minor modification to commission logic associated with workday written premium (no change to already reported financials).</li> 
			<li>External Integrations : Updated red zone data feed logic to to send broker user email instead of brokerage email.</li>
			<li>Created view to capture ISS territories to facilitate with regulatory reporting as requested by the analytics team.</li>
			<li>Created view to capture home coverage extension details associated with the following (ChangeInTermsSummary; AnimalRelatedLiabilityExclusion; CanineLiabilityExclusion; CoverageBDetails; ExtendedLiabilityLocation; SpecificNamedStructuresPropertyAndLiabilityExclusion).</li>
			<li>Added condo collection details to tcollection_class_type and tcollection_scheduled_item</li>
		</ul>
    </li>
    <li>Bug tickets - 21
        <ul>
			<li>Data Standardization : Fixed extended_replacement_cost_coverage_in and extended_replacement_cost_coverage_option for Home policies. </li>
			<li>Updated stored procedure logic to make premium consistent between tquote_history and tquote_transaction.</li>
			<li>Updated inspection status from ''Complete'' to ''Inspection #{{InspectionNumber}} has been cancelled in LC360'' as per user request. </li>
			<li>Resolved 13 tickets associated with roofCoverageEndorsementRV; roofCoverageEndorsementWH; roofCoverageEndorsementAP fields by making them null.</li>
			<li>Resolved 2 tickets associated with BCEG Credit Percent field. </li>
			<li>Resolved 2 tickets associated with IVANS Home and Auto data feed. </li>
			<li>Resolved 1 ticket associated with county name field. </li>
		</ul>
    </li>
</ol>
'
,'Yes'
,'2024-09-23'
,getdate()
,getdate()
)
;

-- tedw_release_note

INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7244','IVANS Home Updates','Bug','2024-09-20','Hernando Garcia','Datafix','edw_integration','policy_ivans_home_feed','Home_coverages','Updated stored procedure logic to capture accurate earthquake deductible.','18','Yes','2024-09-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7236','IVANS Auto Updates','Bug','2024-09-20','Alberto Almario','Datafix','edw_integration','policy_ivans_auto_feed','AU_garaging_locations','Updated stored procedure logic to capture accurate location number for garaging locations.','18','Yes','2024-09-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7254','External Integrations- RedZone feed enhancements - .','Enhancement','2024-09-20','Architha Gudimalla','Modification','edw_integration','policy_redzone_feed','broker_email','Updated stored procedure logic to send "broker user" email instead of "brokerage" email.','18','Yes','2024-09-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7184','Create view in edw_core to capture additional coverage extension details for Home/Condo policies','Enhancement','2024-09-20','Architha Gudimalla','Addition','edw_core','vhome_coverage_ext','','Created a view to capture coverage extension details associated with the following (ChangeInTermsSummary; AnimalRelatedLiabilityExclusion; CanineLiabilityExclusion; CoverageBDetails; ExtendedLiabilityLocation; SpecificNamedStructuresPropertyAndLiabilityExclusion).','18','Yes','2024-09-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7211/VI32067','Data Standardization : Fix extended_replacement_cost_coverage_in with incorrect values for Home/Condo policies','Bug','2024-09-20','Rushin Shah','Datafix','edw_core','thome_additional_coverage','extended_replacement_cost_coverage_in','Updated extended_replacement_cost_coverage_in with incorrect values to accurate values in Metal and EDW. This is just a onetime update.','18','Yes','2024-09-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7211/VI32067','Data Standardization : Fix extended_replacement_cost_coverage_option with incorrect values for Home/Condo policies','Bug','2024-09-20','Rushin Shah','Datafix','edw_core','thome_additional_coverage','extended_replacement_cost_coverage_option','Updated extended_replacement_cost_coverage_option with incorrect values to accurate values in Metal and EDW. This is just a onetime update.','18','Yes','2024-09-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7176/VI33845','Added condo collection details to class_type and scheduled_item','Enhancement','2024-09-20','Alberto Almario','Addition','edw_core','tcollection_class_type','','Added condo collection details','18','Yes','2024-09-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7176/VI33845','Added condo collection details to class_type and scheduled_item','Enhancement','2024-09-20','Alberto Almario','Addition','edw_core','tcollection_scheduled_item','','Added condo collection details','18','Yes','2024-09-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7177/VI33786','Mismatched net_premium_amouts between tquote_history and tquote_transaction','Bug','2024-09-20','Architha Gudimalla','Datafix','edw_core','tquote_transaction','','Updated stored procedure logic to make premium consistent between tquote_history and tquote_transaction.','18','Yes','2024-09-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7129','Workday Enhancements  - Commission logic enhancements','Enhancement','2024-09-20','Rushin Shah','Addition','edw_integration','policy_workday_written_premium_feed','financial_category_id','Minor modification to commission logic associated with financial_category_id for workday written premium (no change to already reported financials).','18','Yes','2024-09-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7129','Workday Enhancements  - Commission logic enhancements','Enhancement','2024-09-20','Rushin Shah','Addition','edw_integration','policy_workday_written_premium_feed','financial_category_name','Minor modification to commission logic associated with financial_category_name for workday written premium (no change to already reported financials).','18','Yes','2024-09-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7129','Workday Enhancements  - Addition of gross_premium_amt column to ceded premium file','Enhancement','2024-09-20','Rushin Shah','Addition','edw_integration','policy_workday_ceded_premium_feed','gross_premium_amt','Created new column','18','Yes','2024-09-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7222/VI33963','Create view in edw_core for ISS Territory','Enhancement','2024-09-20','Rushin Shah','Addition','edw_core','vissterritory','','Created a view to capture a few requested fields associated with ISS home territory.','18','Yes','2024-09-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7200','Process Improvements : Updated validations to tvalidation_sql','Enhancement','2024-09-20','Yunus Mohammed','Addition','edw_core','tvalidation_sql','','Updated validation checks to identify missing collection_class_type for Home/Condo.','18','No','2024-09-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7194/VI33857/VI33649','Update BCEGCreditPercent for 2 policies','Bug','2024-09-20','Architha Gudimalla','Datafix','edw_core','thome_coverage','bceg_credit_pc','Updated BCEG Credit Percent for 2 policies in Metal and EDW.  This is just a onetime update.','18','Yes','2024-09-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7201/VI33780/VI33924/VI33930/VI3350/VI33961/VI33977/VI33970/VI34052/VI33744/VI33797/VI33782/VI33877/VI33993','Roof coverage endorsement updates','Bug','2024-09-20','Architha Gudimalla','Datafix','edw_core','thome_additional_coverage','roof_covering_coverage_limitation_all_peril_loss_settlement_endorsement_in','Updated "roofCoverageEndorsementRV" or "roofCoverageEndorsementWH" or "roofCoverageEndorsementAP" to null. This is just a onetime update.','18','Yes','2024-09-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7275/VI33956','LC360 - Need transactionstatus updated for policies with cancelled inspections','Bug','2024-09-20','Architha Gudimalla','Datafix','edw_core','vlc360','transaction_status','Updated inspection status from "Complete" to "Inspection #{{InspectionNumber}} has been cancelled in LC360" for 775 records in Metal and EDW.  This is just a onetime update.','18','Yes','2024-09-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7213/VI33721','Updating county names information (from St, St., Saint to St.) ','Bug','2024-09-20','Rushin Shah','Modification','edw_core','thome_location','county_nm','Updated county name information from St, St., Saint to St. on migrated policies in Metal and EDW.  This is just a onetime update.','18','Yes','2024-09-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6927','Update unique_key to sp_tquote_pel_vehicle_rapa','Enhancement','2024-09-20','Architha Gudimalla','Modification','edw_core','tquote_pel_vehicle_rapa','','Updated unique key to add vehicle_unique_id to the constraint','18','No','2024-09-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7154','CLUE Feed (Home, Condo and Collections) goes live','Enhancement','2024-09-20','Tuba Mohsin','Addition','edw_integration','claim_clue_property_feed','','CLUE Feed (Home, Condo and Collections) goes live where we will be sending our internal claims data to Lexis Nexis','18','Yes','2024-09-23',getdate(),getdate());
