-- tedw_release_summary
INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 10/07/2024 :</span>
<h4 style="margin-top: 0;">This release includes the following:</h4>
<ol>
    <li>Enhancements - 2
        <ul>
			<li>EDW Integrations : As part of the marine product rollout, we enhanced data pipline to accept Marine Boat & Yacht data into the tpolicy, tpolicy_history, and tpolicy_transaction tables whenever Metal starts writing business</li>
			<li>Added state filings 10/05 release related 2 new columns for Home</li>
		</ul>
    </li>
    <li>Bug tickets - 5
        <ul>
			<li>Data Standardization : Fixed home_cyber_protection_coverage_in, home_cyber_protection_coverage_limit_amt, home_systems_protection_in, home_systems_protection_limit_amt and distance_to_coast for Home and Condo policies. </li>
			<li>Resolved 2 ticket associated with city name field. </li>
			<li>Resolved 1 ticket associated with zip code field. </li>			
		</ul>
    </li>
</ol>
'
,'Yes'
,'2024-10-07'
,getdate()
,getdate()
)
;

-- tedw_release_note

INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7313','Integration of boat/yatch data into policy, policy history and transaction tables','Enhancement','2024-10-04','Yunus Mohammed','Addition','edw_core','tpolicy','','Made necessary code changes to integrate boat/yatch data into tpolicy, tpolicy_history and tpolicy_transaction tables.','19','Yes','2024-10-07',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7285/VI34055','Data Standardization : Fix distance_to_coast with incorrect values for Home/Condo policies','Bug','2024-10-04','Rushin Shah','Datafix','edw_core','thome_coverage','distance_to_coast','Updated distance_to_coast with incorrect values to accurate values in Metal and EDW. This is just a onetime update.','19','Yes','2024-10-07',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7235/VI33994','88 VRE Home records with 4-digit zip (need to add leading zero)','Bug','2024-10-04','Yunus Mohammed','Modification','edw_core','thome_location','zip_cd','Updated 4 digit zip code information by adding leading 0 to it in Metal and EDW.  This is just a onetime update.','19','Yes','2024-10-07',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI34256/VI34281','Update city_nm for 2 policies','Bug','2024-10-04','Yunus Mohammed','Modification','edw_core','thome_location','city_nm','Updated city name information for 2 policies in Metal and EDW.  This is just a onetime update.','19','Yes','2024-10-07',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7354','Data Standardization : Fix home_cyber_protection_coverage_in with incorrect values for Home/Condo policies','Bug','2024-10-04','Rushin Shah','Datafix','edw_core','thome_additional_coverage','home_cyber_protection_coverage_in','Updated home_cyber_protection_coverage_in with incorrect values to accurate values in Metal and EDW. This is just a onetime update.','19','Yes','2024-10-07',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7354','Data Standardization : Fix home_cyber_protection_coverage_limit_amt with incorrect values for Home/Condo policies','Bug','2024-10-04','Rushin Shah','Datafix','edw_core','thome_additional_coverage','home_cyber_protection_coverage_limit_amt','Updated home_cyber_protection_coverage_limit_amt with incorrect values to accurate values in Metal and EDW. This is just a onetime update.','19','Yes','2024-10-07',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7354','Data Standardization : Fix home_systems_protection_in with incorrect values for Home/Condo policies','Bug','2024-10-04','Rushin Shah','Datafix','edw_core','thome_additional_coverage','home_systems_protection_in','Updated home_systems_protection_in with incorrect values to accurate values in Metal and EDW. This is just a onetime update.','19','Yes','2024-10-07',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7354','Data Standardization : Fix home_systems_protection_limit_amt  with incorrect values for Home/Condo policies','Bug','2024-10-04','Rushin Shah','Datafix','edw_core','thome_additional_coverage','home_systems_protection_limit_amt ','Updated home_systems_protection_limit_amt  with incorrect values to accurate values in Metal and EDW. This is just a onetime update.','19','Yes','2024-10-07',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7306','State filings 10/05 release related columns','Enhancement','2024-10-04','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','fortified_roof_upgrade_endorsement_in','Created new column','19','Yes','2024-10-07',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7306','State filings 10/05 release related columns','Enhancement','2024-10-04','Tuba Mohsin','Addition','edw_core','thome_coverage','fortified_roof_credit','Created new column','19','Yes','2024-10-07',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7306','State filings 10/05 release related columns','Enhancement','2024-10-04','Tuba Mohsin','Addition','edw_core','tquote_home_additional_coverage','fortified_roof_upgrade_endorsement_in','Created new column','19','Yes','2024-10-07',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7306','State filings 10/05 release related columns','Enhancement','2024-10-04','Tuba Mohsin','Addition','edw_core','tquote_home_coverage','fortified_roof_credit','Created new column','19','Yes','2024-10-07',getdate(),getdate());
