-- tedw_release_summary
INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 10/21/2024 :</span>
<h4 style="margin-top: 0;">This release includes the following:</h4>
<ol>
    <li>Enhancements - 6
        <ul>
			<li>External Integrations - HubSpot is officially live, providing powerful tools to boost business efficiency and drive growth.</li>
			<li>External Integrations - Implemented minor code fixes for IVANS home associated with loss of use coverages, AOP deductible and earthquake deductible.</li>
			<li>Datamart enhancements - Updated logic in tbroker_summary table for calculating policy_renewal_offered_ct.</li>
			<li>Created view to capture Livevox data.</li>
			<li>Vendor reports - Updated logic to include LC360 inspections that are still pending. Added new column IsReportFromCache.  </li>
			<li>Backfilled wildfire protection data using information gathered from manual forms for the Redzone feed. </li>
		</ul>
    </li>
    <li>Bug tickets - 29
        <ul>
			<li>Data Standardization - Fixed waterdamage_limitation_endorsement_in for Home policies from True/False to Yes/No.</li>
			<li>Updated stored procedure to fetch appropriate details for loss_assessment_increase_desc. Backfilling of data in EDW will happen on 10/25. </li>
			<li>Performed a data fix to populate country_nm instead of county_nm for tquote_pel_location table.</li>
			<li>Updated stored procedure logic to remove duplicate mortgages information for a few claims.</li>
			<li>Resolved 6 tickets associated with repusing of policies associated with data fixes applied on IVANS.</li>
			<li>Resolved 6 tickets associated with roofCoverageEndorsementRV; roofCoverageEndorsementWH; roofCoverageEndorsementAP; roofExclusionWEnsuingLoss fields by making them null.</li>
			<li>Resolved 2 tickets associated with updating city name field.</li>
			<li>Resolved 2 tickets associated with updating BCEG credit percent field.</li>
			<li>Resolved 2 tickets associated with removing linkage between policies as per user request.</li>
			<li>Resolved 1 ticket associated with updating original policy effective date and subscriber contribution date field.</li>
			<li>Resolved 1 ticket associated with updating policy number as per user request on renewal quote.</li>
			<li>Resolved 1 ticket associated with updating county name field.</li>
			<li>Resolved 1 ticket associated with updating non renewal indicator to No for one policy.</li>			
		</ul>
    </li>
</ol>
'
,'Yes'
,'2024-10-21'
,getdate()
,getdate()
)
;

-- tedw_release_note

INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI34264','Unable to generate renewal on auto AU100266880-03','Bug','2024-10-07','Sandeep Gundreddy','Datafix','edw_core','tquote','','policy EX100266882-03 was incorrectly attached to AU100266880-03 preventing renewal. Removed the linkage as per the request. This is just a onetime update.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI34013','Incorrect policy number on renewal','Bug','2024-10-07','Sandeep Gundreddy','Datafix','edw_core','tquote','','Updated policynumber AU100263539-02 to AU200023762-02 as per the request on renewal quote. This is just a onetime issue in Metal.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI34447','renewal issue due to migration','Bug','2024-10-09','Sandeep Gundreddy','Datafix','edw_core','tquote','','policy AU100261191-04 was incorrectly attached to AU100084770-02 preventing renewal. Removed the linkage as per the request. This is just a onetime update.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI33995','IVANS Policy Resent Request','Bug','2024-10-14','Rushin Shah','Datafix','edw_integration','policy_ivans_auto_feed','','Resent a few policies to IVANS after applying data fixes.  This is just a onetime update.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI34512','IVANS Policy Resent Request','Bug','2024-10-14','Rushin Shah','Datafix','edw_integration','policy_ivans_pel_feed','','Resent a few policies to IVANS after applying data fixes.  This is just a onetime update.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI34451/VI32022/VI34033','IVANS Policy Resent Request','Bug','2024-10-16','Rushin Shah','Datafix','edw_integration','policy_ivans_home_feed','','Resent a few policies to IVANS after applying data fixes.  This is just a onetime update.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI34454','AV Claims did not recognize an active NFP policy','Bug','2024-10-14','Yunus Mohammed','Datafix','edw_integration','claim_policy_search_api','','Loaded NFP policies for September into claim policy search table so that NFP claim can be opened in eBao.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI34320','Downloads - Coverage Code Error - Loss of Use','Bug','2024-10-14','Rushin Shah','Datafix','edw_integration','policy_ivans_home_feed','','Updated IVANS Home stored procedure logic to capture appropriate coverage code for loss of use coverage.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI33166','AU100085257-01, transaction seq 4 shows tort as full and limited in our query; Metal UI shows Full','Bug','2024-10-16','Hernando Garcia','Datafix','edw_core','tauto_policy_coverage','tort','Explored policy attributes for this issue and confirmed that this is working as expected.','20','No','2024-10-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7429','Data Standardization : Fix waterdamage_limitation_endorsement_in to Yes/No (from True/False)','Bug','2024-10-16','Rushin Shah','Datafix','edw_core','thome_additional_coverage','waterdamage_limitation_endorsement_in','Updated waterdamage_limitation_endorsement_in from True/False to Yes/No in Metal and EDW. This is just a onetime update.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI34149','19 Home records with a blank space at the end of edw_core.thome_location.county_nm','Bug','2024-10-16','Yunus Mohammed','Datafix','edw_core','thome_location','county_nm','Updated country name information for 19 policies in Metal and EDW.  This is just a onetime update.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7018','IVANS Home AOP Updates','Enhancement','2024-10-18','Hernando Garcia','Modification','edw_integration','policy_ivans_home_feed','Home_Coverages','Update stored precedure logic to capture & display "AOP deductible" under proper coverages depending on whether it is a Home/Condo policy.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29587','Update non renewal indicator to "No" for HO84555688236-03','Bug','2024-10-14','Rushin Shah','Datafix','edw_core','tpolicy','non_renewal_in','Updated non_renewal_in to "No" for policy number HO84555688236-03 in Metal and EDW.  This is just a onetime update.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7420/VI31513','Update logic to fetch loss_assessment_increase_desc in EDW','Bug','2024-10-18','Hernando Garcia','Datafix','edw_core','thome_additional_coverage','loss_assessment_increase_desc','Updated mapping logic to fetch accurate data for loss_assessment_increase_desc in EDW.  Backfilling of historical data will happen on 10/25. ','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7420/VI31513','Update logic to fetch loss_assessment_increase_desc in EDW','Bug','2024-10-18','Hernando Garcia','Datafix','edw_core','tquote_home_additional_coverage','loss_assessment_increase_desc','Updated mapping logic to fetch accurate data for loss_assessment_increase_desc in EDW.  Backfilling of historical data will happen on 10/25. ','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7450','Remove duplicates on mortgage columns','Bug','2024-10-18','Alberto Almario','Datafix','edw_integration','claim_clue_property_feed','','Updated stored procedure logic to remove duplicate mortgages information for a few claims.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7319','Create view in edw_core for LiveVox','Enhancement','2024-10-07','Tuba Mohsin','Addition','edw_core','vlivevox','','Created a view to capture livevox data.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7007','Backfilling of Wildfire protection fields','Enhancement','2024-10-18','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','wildfire_protection_enrollment_in','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7007','Backfilling of Wildfire protection fields','Enhancement','2024-10-18','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','wildfire_protection_enrollment_in','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7007','Backfilling of Wildfire protection fields','Enhancement','2024-10-18','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','site_scheduling_contact_nm','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7007','Backfilling of Wildfire protection fields','Enhancement','2024-10-18','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','site_scheduling_contact_nm','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7007','Backfilling of Wildfire protection fields','Enhancement','2024-10-18','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','site_scheduling_phone_no','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7007','Backfilling of Wildfire protection fields','Enhancement','2024-10-18','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','site_scheduling_phone_no','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7007','Backfilling of Wildfire protection fields','Enhancement','2024-10-18','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','site_scheduling_email','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7007','Backfilling of Wildfire protection fields','Enhancement','2024-10-18','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','site_scheduling_email','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7007','Backfilling of Wildfire protection fields','Enhancement','2024-10-18','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','emergency_contact_nm','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7007','Backfilling of Wildfire protection fields','Enhancement','2024-10-18','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','emergency_contact_nm','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7007','Backfilling of Wildfire protection fields','Enhancement','2024-10-18','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','emergency_contact_phone_no','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7007','Backfilling of Wildfire protection fields','Enhancement','2024-10-18','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','emergency_contact_phone_no','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7007','Backfilling of Wildfire protection fields','Enhancement','2024-10-18','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','emergency_contact_email','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7007','Backfilling of Wildfire protection fields','Enhancement','2024-10-18','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','emergency_contact_email','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7007','Backfilling of Wildfire protection fields','Enhancement','2024-10-18','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','gate_code','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7007','Backfilling of Wildfire protection fields','Enhancement','2024-10-18','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','gate_code','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7305/VI33823','Vendor Reports - Added cache column and updated logic to include pending inspections','Enhancement','2024-10-18','Architha Gudimalla','Addition','edw_core','vlc360','IsReportFromCache','Updated logic to include LC360 inspections that are still pending. Added new column IsReportFromCache.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7440','Datamart Enhancements : tbroker_summary - update logic to use quotes for policy_renewal_offered_ct','Enhancement','2024-10-18','Architha Gudimalla','Modification','edw_core','tbroker_summary','policy_renewal_offered_ct','Updated the logic in the tbroker_summary table for calculating policy_renewal_offered_ct to match tableau logic.  Prior logic was only counting issued renewals.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7423','Update - country_nm in Tquote_pel_location','Bug','2024-10-09','Architha Gudimalla','Datafix','edw_core','tquote_pel_location','country_nm','Performed a data fix to populate country_nm instead of county_nm.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7444/VI34137','16 records with risk city as Estero, but Google Maps indicates Bonita Springs','Bug','2024-10-18','Architha Gudimalla','Datafix','edw_core','thome_location','city_nm','Updated city name information from Estero to Bonita Springs in Metal and EDW.  This is just a onetime update.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7445/VI34034','2 policies (4 records) where city Ponte Verda Beach needs changing to Ponte Vedra Beach','Bug','2024-10-18','Architha Gudimalla','Datafix','edw_core','thome_location','city_nm','Updated city name information from Ponte Verda Beach to Ponte Vedra Beach in Metal and EDW.  This is just a onetime update.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7444/VI34137','16 records with risk city as Estero, but Google Maps indicates Bonita Springs','Bug','2024-10-18','Architha Gudimalla','Datafix','edw_core','tquote_home_location','city_nm','Updated city name information from Estero to Bonita Springs in Metal and EDW.  This is just a onetime update.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7445/VI34034','2 policies (4 records) where city Ponte Verda Beach needs changing to Ponte Vedra Beach','Bug','2024-10-18','Architha Gudimalla','Datafix','edw_core','tquote_home_location','city_nm','Updated city name information from Ponte Verda Beach to Ponte Vedra Beach in Metal and EDW.  This is just a onetime update.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7399','External Integration - Hubspot','Enhancement','2024-10-18','Architha Gudimalla','Addition','edw_integration','broker_hubspot_feed','','Created new table to send broker data to Hubspot.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7399','External Integration - Hubspot','Enhancement','2024-10-18','Architha Gudimalla','Addition','edw_integration','broker_relation_hubspot_feed','','Created new table to send broker relation data to Hubspot.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7399','External Integration - Hubspot','Enhancement','2024-10-18','Architha Gudimalla','Addition','edw_integration','customer_hubspot_feed','','Created new table to send customer data to Hubspot.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7399','External Integration - Hubspot','Enhancement','2024-10-18','Architha Gudimalla','Addition','edw_integration','producer_hubspot_feed','','Created new table to send producer data to Hubspot.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7399','External Integration - Hubspot','Enhancement','2024-10-18','Architha Gudimalla','Addition','edw_integration','quote_hubspot_feed','','Created new table to send quote data to Hubspot.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7399','External Integration - Hubspot','Enhancement','2024-10-18','Architha Gudimalla','Addition','edw_integration','quote_note_hubspot_feed','','Created new table to send quote notes data to Hubspot.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7474/VI34493/VI34240/VI34429/VI34381','Roof coverage endorsement updated for 4 policies','Bug','2024-10-18','Architha Gudimalla','Datafix','edw_core','thome_additional_coverage','roof_coverage_endorsement_rv_in','Updated "roofCoverageEndorsementRV" or "roofCoverageEndorsementWH" or "roofCoverageEndorsementAP" to null.  Data is updated in Metal and will be updated in EDW during next full refresh.  This is just a onetime update.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7474/VI34493/VI34240/VI34429/VI34381','Roof coverage endorsement updated for 4 policies','Bug','2024-10-18','Architha Gudimalla','Datafix','edw_core','tquote_home_additional_coverage','roof_coverage_endorsement_rv_in','Updated "roofCoverageEndorsementRV" or "roofCoverageEndorsementWH" or "roofCoverageEndorsementAP" to null. Data is updated in Metal and will be updated in EDW during next full refresh. This is just a onetime update.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7474/VI34493/VI34240/VI34429/VI34381','Roof coverage endorsement updated for 4 policies','Bug','2024-10-18','Architha Gudimalla','Datafix','edw_core','thome_additional_coverage','roof_coverage_endorsement_wh_in','Updated "roofCoverageEndorsementRV" or "roofCoverageEndorsementWH" or "roofCoverageEndorsementAP" to null. Data is updated in Metal and will be updated in EDW during next full refresh. This is just a onetime update.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7474/VI34493/VI34240/VI34429/VI34381','Roof coverage endorsement updated for 4 policies','Bug','2024-10-18','Architha Gudimalla','Datafix','edw_core','tquote_home_additional_coverage','roof_coverage_endorsement_wh_in','Updated "roofCoverageEndorsementRV" or "roofCoverageEndorsementWH" or "roofCoverageEndorsementAP" to null. Data is updated in Metal and will be updated in EDW during next full refresh. This is just a onetime update.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7474/VI34493/VI34240/VI34429/VI34381','Roof coverage endorsement updated for 4 policies','Bug','2024-10-18','Architha Gudimalla','Datafix','edw_core','thome_additional_coverage','roof_coverage_endorsement_ap_in','Updated "roofCoverageEndorsementRV" or "roofCoverageEndorsementWH" or "roofCoverageEndorsementAP" to null. Data is updated in Metal and will be updated in EDW during next full refresh. This is just a onetime update.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7474/VI34493/VI34240/VI34429/VI34381','Roof coverage endorsement updated for 4 policies','Bug','2024-10-18','Architha Gudimalla','Datafix','edw_core','tquote_home_additional_coverage','roof_coverage_endorsement_ap_in','Updated "roofCoverageEndorsementRV" or "roofCoverageEndorsementWH" or "roofCoverageEndorsementAP" to null. Data is updated in Metal and will be updated in EDW during next full refresh. This is just a onetime update.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7475/VI34578/VI34493','RoofExclusionWEnsuingLoss updated for 2 policies','Bug','2024-10-18','Architha Gudimalla','Datafix','edw_core','thome_additional_coverage','roof_exclusion_with_ensuing_loss_in','Updated "RoofExclusionWEnsuingLoss" to null. Data is updated in Metal and will be updated in EDW during next full refresh. This is just a onetime update.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7475/VI34578/VI34493','RoofExclusionWEnsuingLoss updated for 2 policies','Bug','2024-10-18','Architha Gudimalla','Datafix','edw_core','tquote_home_additional_coverage','roof_exclusion_with_ensuing_loss_in','Updated "RoofExclusionWEnsuingLoss" to null. Data is updated in Metal and will be updated in EDW during next full refresh.This is just a onetime update.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7476/VI34453/VI34222','Update BCEGCreditPercent for 2 policies','Bug','2024-10-18','Architha Gudimalla','Datafix','edw_core','thome_coverage','bceg_credit_pc','Updated BCEG Credit Percent for 2 policies in Metal and EDW.  Data is updated in Metal and will be updated in EDW during next full refresh. This is just a onetime update.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7476/VI34453/VI34222','Update BCEGCreditPercent for 2 policies','Bug','2024-10-18','Architha Gudimalla','Datafix','edw_core','tquote_home_coverage','bceg_credit_pc','Updated BCEG Credit Percent for 2 policies in Metal and EDW.  Data is updated in Metal and will be updated in EDW during next full refresh. This is just a onetime update.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7471','Update null Effective and Expiration dates in metal account table','Bug','2024-10-18','Architha Gudimalla','Datafix','edw_core','tquote','effective_dt','Updated  null effective and expiration dates in metal.  Data is updated in Metal and will be updated in EDW during next full refresh. This is just a onetime update.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7471','Update null Effective and Expiration dates in metal account table','Bug','2024-10-18','Architha Gudimalla','Datafix','edw_core','tquote','expiration_dt','Updated  null effective and expiration dates in metal.  Data is updated in Metal and will be updated in EDW during next full refresh. This is just a onetime update.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7478/VI34579','Update ORIGINAL policy effective date in metal for 2 policies','Bug','2024-10-18','Architha Gudimalla','Datafix','edw_core','tpolicy','original_policy_effective_dt','Updated ORIGINAL policy effective date for HO100085219-05 & EX100085575. Data is updated in Metal and will be updated in EDW during next full refresh. This is just a onetime update.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7478/VI34579','Update subscriber contribution end date in metal for 2 policies','Bug','2024-10-18','Architha Gudimalla','Datafix','edw_core','tpolicy_insured','subscriber_contribution_end_dt','Updated subscriber contribution end date for HO100085219-05 & EX100085575. Data is updated in Metal and will be updated in EDW during next full refresh. This is just a onetime update.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7478/VI34579','Update ORIGINAL policy effective date in metal for 2 policies','Bug','2024-10-18','Architha Gudimalla','Datafix','edw_core','tquote','original_policy_effective_dt','Updated ORIGINAL policy effective date for HO100085219-05 & EX100085575. Data is updated in Metal and will be updated in EDW during next full refresh. This is just a onetime update.','20','Yes','2024-10-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7478/VI34579','Update subscriber contribution end date in metal for 2 policies','Bug','2024-10-18','Architha Gudimalla','Datafix','edw_core','tquote_policy_insured','subscriber_contribution_end_dt','Updated subscriber contribution end date for HO100085219-05 & EX100085575. Data is updated in Metal and will be updated in EDW during next full refresh. This is just a onetime update.','20','Yes','2024-10-21',getdate(),getdate());