INSERT INTO edw_core.tclaim_transaction_type (claim_transaction_type_cd,claim_transaction_type_nm,update_ts) VALUES
	('Claim' , 'Loss' , getdate()),
	('Salvage Loss Recovery' , 'Recovery' , getdate()),
	('Subrogation Loss Recovery' , 'Recovery' , getdate()),
	('Overpayment Loss Recovery' , 'Recovery' , getdate()),
	('Deductible Loss Recovery' , 'Recovery' , getdate()),
	('Reinsurance Loss Recovery' , 'Recovery' , getdate()),
	('Adjusting' , 'Expense' , getdate()),
	('Salvage Expense Recovery' , 'Recovery' , getdate()),
	('Subrogation Expense Recovery' , 'Recovery' , getdate()),
	('Overpayment Expense Recovery' , 'Recovery' , getdate()),
	('Deductible Expense Recovery' , 'Recovery' , getdate()),
	('Reinsurance Expense Recovery' , 'Recovery' , getdate()),
	('Defense' , 'Defense' , getdate()),
	('Salvage Defense Recovery' , 'Recovery' , getdate()),
	('Subrogation Defense Recovery' , 'Recovery' , getdate()),
	('Overpayment Defense Recovery' , 'Recovery' , getdate()),
	('Deductible Defense Recovery' , 'Recovery' , getdate()),
	('Reinsurance Defense Recovery' , 'Recovery' , getdate());
