-- tedw_release_summary
INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 11/04/2024 :</span>
<h4 style="margin-top: 0;">This release includes the following:</h4>
<ol>
    <li>Enhancements - 5
        <ul>
			<li>Added state filings 11/02 release related 17 new columns for Home/Condo.</li>
			<li>Added 2 new columns related to Programmatic and non programmatic discounts for Home/Condo (fortified_roof_program_discount_amt, non_program_discount_amt).</li>
			<li>Added state filings 10/05 release related 3 new columns for Auto (excluded_driver_in, excluded_drivers_for_all_vehicles_in, excluded_driver_for_listed_vehicles).</li>
			<li>Backfilled wildfire protection data using information gathered from manual forms for the Redzone feed. </li>
			<li>Added new column scheduled_item_deleted_in to tcollection_scheduled_item table.</li>
				
		</ul>
    </li>
    <li>Bug tickets - 13
        <ul>
			<li>External Integrations - Hubspot Fixes</li>
				a) Revised logic for Renewal Underwriters to be sent as blank, indicating a pool for brokers with multiple renewal underwriters<br>
				b) Updated logic to resolve missing customers related to insured_type = "entity" in the customer feed<br>
				c) Updated logic to resolve missing quotes related to insured_type = "entity" in the quote feed	
			<li>Data Standardization - Fixed home_cyber_protection_coverage_limit_amt and home_systems_protection_limit_amt for a few Home policies based on its associated indicators. </li>
			<li>Resolved 3 tickets associated with repushing of policies associated with data fixes applied on IVANS.</li>
			<li>Resolved 3 tickets associated with roofCoverageEndorsementRV; roofCoverageEndorsementWH; roofCoverageEndorsementAP; roofExclusionWEnsuingLoss fields by making them null.</li>
			<li>Resolved 1 ticket associated with deleting duplicate cancelled transaction for one policy.</li>
			<li>Resolved 1 ticket associated with updating missing built_yr for a few policies.</li>
			<li>Resolved 1 ticket associated with updating missing rating_territory_cd for a few NC policies.</li>
			<li>Resolved 1 ticket associated with adding notes in Metal for a few policies as per user request.</li>
		</ul>
    </li>
</ol>
'
,'Yes'
,'2024-11-04'
,getdate()
,getdate()
)
;

-- tedw_release_note

INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI34866','Duplicate cancellation transaction for policy-HO100200714-02','Bug','2024-10-31','Sandeep Gundreddy','Datafix','edw_core','tpolicy_transaction','','Deleted duplicate cancelled transaction for  policy-HO100200714-02 from Metal and EDW. This is an isolated issue in Metal.','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7470','State filings 11/02 release related columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','thome_coverage','facultative_reinsurance_in','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7470','State filings 11/02 release related columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','thome_coverage','layered_limits_in','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7470','State filings 11/02 release related columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','thome_coverage','100_pc_dwelling_limit_value_amt','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7470','State filings 11/02 release related columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','thome_coverage','100_pc_other_structures_limit_value_amt','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7470','State filings 11/02 release related columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','thome_coverage','100_pc_contents_limit_value_amt','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7470','State filings 11/02 release related columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','thome_coverage','100_pc_loss_of_use_value_amt','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7470','State filings 11/02 release related columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','thome_coverage','facultative_attachment_point','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7470','State filings 11/02 release related columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','thome_coverage','facultative_limit_amt','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7470','State filings 11/02 release related columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','thome_coverage','facultative_ceded_premium_amt','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7470','State filings 11/02 release related columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','thome_coverage','facultative_reinsurer_nm','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7470','State filings 11/02 release related columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','thome_coverage','coverage_layer','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7470','State filings 11/02 release related columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','thome_coverage','coverage_layer_placed_pc','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7470','State filings 11/02 release related columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','thome_coverage','coverage_layer_limit_amt','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7470','State filings 11/02 release related columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','thome_coverage','newly_purchased_home_in','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7470','State filings 11/02 release related columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','thome_coverage','target_closing_dt','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7470','State filings 11/02 release related columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','thome_coverage','current_policy_anniversary_dt','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7470','State filings 11/02 release related columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','thome_coverage','current_underlying_company_nm','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7470','State filings 11/02 release related columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','tquote_home_coverage','facultative_reinsurance_in','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7470','State filings 11/02 release related columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','tquote_home_coverage','layered_limits_in','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7470','State filings 11/02 release related columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','tquote_home_coverage','100_pc_dwelling_limit_value_amt','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7470','State filings 11/02 release related columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','tquote_home_coverage','100_pc_other_structures_limit_value_amt','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7470','State filings 11/02 release related columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','tquote_home_coverage','100_pc_contents_limit_value_amt','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7470','State filings 11/02 release related columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','tquote_home_coverage','100_pc_loss_of_use_value_amt','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7470','State filings 11/02 release related columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','tquote_home_coverage','facultative_attachment_point','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7470','State filings 11/02 release related columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','tquote_home_coverage','facultative_limit_amt','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7470','State filings 11/02 release related columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','tquote_home_coverage','facultative_ceded_premium_amt','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7470','State filings 11/02 release related columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','tquote_home_coverage','facultative_reinsurer_nm','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7470','State filings 11/02 release related columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','tquote_home_coverage','coverage_layer','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7470','State filings 11/02 release related columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','tquote_home_coverage','coverage_layer_placed_pc','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7470','State filings 11/02 release related columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','tquote_home_coverage','coverage_layer_limit_amt','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7470','State filings 11/02 release related columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','tquote_home_coverage','newly_purchased_home_in','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7470','State filings 11/02 release related columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','tquote_home_coverage','target_closing_dt','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7470','State filings 11/02 release related columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','tquote_home_coverage','current_policy_anniversary_dt','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7470','State filings 11/02 release related columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','tquote_home_coverage','current_underlying_company_nm','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI34738/VI34741/VI34806','IVANS Policy Resent Request','Bug','2024-11-01','Rushin Shah','Datafix','edw_integration','','','Resent a few policies to IVANS after applying data fixes.  This is just a onetime update.','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6949','State filings 10/05 release related columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','tauto_driver','excluded_driver_in','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6949','State filings 10/05 release related columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','tauto_driver','excluded_drivers_for_all_vehicles_in','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6949','State filings 10/05 release related columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','tauto_driver','excluded_driver_for_listed_vehicles','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6949','State filings 10/05 release related columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','tquote_auto_driver','excluded_driver_in','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6949','State filings 10/05 release related columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','tquote_auto_driver','excluded_drivers_for_all_vehicles_in','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6949','State filings 10/05 release related columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','tquote_auto_driver','excluded_driver_for_listed_vehicles','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7422/VI32107','Programmatic and non programmatic discounts columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','fortified_roof_program_discount_amt','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7422/VI32107','Programmatic and non programmatic discounts columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','non_program_discount_amt','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7422/VI32107','Programmatic and non programmatic discounts columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','tquote_home_additional_coverage','fortified_roof_program_discount_amt','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7422/VI32107','Programmatic and non programmatic discounts columns','Enhancement','2024-11-01','Tuba Mohsin','Addition','edw_core','tquote_home_additional_coverage','non_program_discount_amt','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7544','External Integration - Hubspot fixes','Bug','2024-11-01','Architha Gudimalla','Datafix','edw_integration','','','','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7544','External Integration - Hubspot fixes','Bug','2024-11-01','Architha Gudimalla','Datafix','edw_integration','','','','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7544','External Integration - Hubspot fixes','Bug','2024-11-01','Architha Gudimalla','Datafix','edw_integration','','','','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7585','Data Standardization : Fix home_cyber_protection_coverage_limit_amt for a few policies based on home_cyber_protection_coverage_in','Bug','2024-11-01','Rushin Shah','Datafix','edw_core','thome_additional_coverage','home_cyber_protection_coverage_limit_amt','Updated home_cyber_protection_coverage_limit_amt  with incorrect values to accurate values in Metal and EDW. This is just a onetime update.','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7586','Data Standardization : Fix home_systems_protection_limit_amt for a few policies based on home_systems_protection_in','Bug','2024-11-01','Rushin Shah','Datafix','edw_core','thome_additional_coverage','home_systems_protection_limit_amt','Updated home_systems_protection_limit_amt  with incorrect values to accurate values in Metal and EDW. This is just a onetime update.','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7591/ VI34598','Roof coverage endorsement updated for 1 policies','Bug','2024-11-01','Architha Gudimalla','Datafix','edw_core','thome_additional_coverage','roof_coverage_endorsement_wh_in','Updated "roofCoverageEndorsementWH" to null for HO100068694-04.  Data is updated in Metal and will be updated in EDW during next full refresh.  This is just a onetime update.','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7591/ VI34834','Roof coverage endorsement updated for 1 policies','Bug','2024-11-01','Architha Gudimalla','Datafix','edw_core','thome_additional_coverage','roof_coverage_endorsement_ap_in','Updated "roofCoverageEndorsementAP" to null for HO100079867-03.  Data is updated in Metal and will be updated in EDW during next full refresh.  This is just a onetime update.','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7492/VI34578','RoofExclusionWEnsuingLoss updated for 1 policies','Bug','2024-11-01','Architha Gudimalla','Datafix','edw_core','thome_additional_coverage','roof_exclusion_with_ensuing_loss_in','Updated "RoofExclusionWEnsuingLoss" to null for HO100230188-04. Data is updated in Metal and will be updated in EDW during next full refresh. This is just a onetime update.','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7588/VI34560','Update HO Records missing built_year ','Bug','2024-11-01','Tuba Mohsin','Datafix','edw_core','thome_coverage','built_year','Updated the built year for a few HO policies missing built_year','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7589/VI-34686','Update rating_territory_cd for policies missing data (NC policies)','Bug','2024-11-01','Tuba Mohsin','Datafix','edw_core','thome_coverage','rating_territory_cd','Update rating_territory_cd for a few NC policies missing this data','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7581/VI34577','Create scheduled_item_deleted_in to tcollection_scheduled_item table','Enhancement','2024-11-01','Architha Gudimalla','Addition','edw_core','tcollection_scheduled_item','scheduled_item_deleted_in','Created new column','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI-34696','Journal Note Needed for Large Policy List','Bug','2024-11-01','Architha Gudimalla','Datafix','edw_core','tnote','','Added notes in Metal as per user request for few policies.  This is just a one time update.','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7576','Backfilling of Wildfire protection fields','Enhancement','2024-11-01','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','wildfire_protection_enrollment_in','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7576','Backfilling of Wildfire protection fields','Enhancement','2024-11-01','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','wildfire_protection_enrollment_in','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7576','Backfilling of Wildfire protection fields','Enhancement','2024-11-01','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','site_scheduling_contact_nm','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7576','Backfilling of Wildfire protection fields','Enhancement','2024-11-01','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','site_scheduling_contact_nm','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7576','Backfilling of Wildfire protection fields','Enhancement','2024-11-01','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','site_scheduling_phone_no','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7576','Backfilling of Wildfire protection fields','Enhancement','2024-11-01','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','site_scheduling_phone_no','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7576','Backfilling of Wildfire protection fields','Enhancement','2024-11-01','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','site_scheduling_email','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7576','Backfilling of Wildfire protection fields','Enhancement','2024-11-01','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','site_scheduling_email','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7576','Backfilling of Wildfire protection fields','Enhancement','2024-11-01','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','emergency_contact_nm','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7576','Backfilling of Wildfire protection fields','Enhancement','2024-11-01','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','emergency_contact_nm','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7576','Backfilling of Wildfire protection fields','Enhancement','2024-11-01','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','emergency_contact_phone_no','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7576','Backfilling of Wildfire protection fields','Enhancement','2024-11-01','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','emergency_contact_phone_no','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7576','Backfilling of Wildfire protection fields','Enhancement','2024-11-01','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','emergency_contact_email','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7576','Backfilling of Wildfire protection fields','Enhancement','2024-11-01','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','emergency_contact_email','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7576','Backfilling of Wildfire protection fields','Enhancement','2024-11-01','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','gate_code','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','21','Yes','2024-11-04',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7576','Backfilling of Wildfire protection fields','Enhancement','2024-11-01','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','gate_code','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','21','Yes','2024-11-04',getdate(),getdate());