-- tedw_release_summary
INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 11/18/2024 :</span>
<h4 style="margin-top: 0;">This release includes the following:</h4>
<ol>
    <li>Enhancements - 8
        <ul>
			<li>Datamart enhancements - Updated logic in tbroker_summary table to load Month to Date(MTD) values instead of Year to date(YTD) values.</li>
			<li>Datamart enhancements - Added the following columns to tbroker_summary table. </li>
			1) ytd_policy_expiring_ct<br>
                        2) ytd_policy_renewal_accepted_ct<br>
                        3) ytd_policy_renewal_ct<br>
			4) ytd_policy_renewal_offered_ct<br>
                        5) ytd_policy_renewal_offered_over_50k_ct<br>
                        6) ytd_policy_renewal_offered_premium_amt<br>
			7) ytd_policy_renewal_offered_expiring_premium_amt<br>
                        8) ytd_policy_expiring_premium_amt<br>
                        9) ytd_policy_renewal_premium_amt			
			<li>External Integrations - Implemented minor code fixes to hubspot feed for calculating renewal retention percentage.</li>
			<li>External Integrations - Implemented minor code fixes for IVANS home associated with loss of use and contents coverages.</li>
			<li>Created view to capture TICO Place codes data.</li>
			<li>Backfilled wildfire protection data using information gathered from manual forms for the Redzone feed. </li>
			<li>Added 2 new columns lifetime_claim_ct and lifetime_loss_incurred_amt to tpolicy & tquote table.</li>
			<li>Added new column issued_quote_history_sk to tquote table.</li>
			<li>Added new column last_inspection_dt to thome_coverage and tquote_home_coverage table.</li>
		</ul>
    </li>
    <li>Bug tickets - 13
        <ul>
			<li>Updated stored procedure logic to populate policy_history_sk for OS policies in tpolicy_transaction table.</li>
			<li>Updated stored procedure logic to populate internal coverage for Clean Risk Loss Recoupment to aslob 192 from 211 in tinternal_coverage table.</li>
			<li>Updated tpel_driver_incident & tquote_pel_driver_incident table stored procedure to populate pel_driver_sk & quote_pel_driver_sk which were null.</li>
			<li>Deleted 22 brokers from Metal and EDW as per the licensing team request. These brokers were created in error due to a Metal issue. The issue is no longer happening.</li>
			<li>Deleted duplicate cancellation transactions for 10 old migrated policies. </li>
			<li>Deleted duplicate cancellation transactions for 2 policies.</li>
			<li>Updated policy status from bound to issued status for 5 non NY policies.</li>
			<li>Updated stats premium associated with transaction sequence =  0 for one policy.</li>
			<li>Resolved 2 tickets associated with repushing of policies associated with data fixes applied on IVANS.</li>
			<li>Resolved 1 ticket associated with updating original_policy_effective_dt and subscriber_contribution_dt for one policy.</li>
			<li>Resolved 1 ticket associated with updating relationship_to_insured for one policy.</li>
		</ul>
    </li>
</ol>
'
,'Yes'
,'2024-11-18'
,getdate()
,getdate()
)
;

-- tedw_release_note

INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7666','Backfilling of Wildfire protection fields','Enhancement','2024-11-15','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','wildfire_protection_enrollment_in','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7666','Backfilling of Wildfire protection fields','Enhancement','2024-11-15','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','wildfire_protection_enrollment_in','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7666','Backfilling of Wildfire protection fields','Enhancement','2024-11-15','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','site_scheduling_contact_nm','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7666','Backfilling of Wildfire protection fields','Enhancement','2024-11-15','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','site_scheduling_contact_nm','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7666','Backfilling of Wildfire protection fields','Enhancement','2024-11-15','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','site_scheduling_phone_no','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7666','Backfilling of Wildfire protection fields','Enhancement','2024-11-15','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','site_scheduling_phone_no','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7666','Backfilling of Wildfire protection fields','Enhancement','2024-11-15','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','site_scheduling_email','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7666','Backfilling of Wildfire protection fields','Enhancement','2024-11-15','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','site_scheduling_email','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7666','Backfilling of Wildfire protection fields','Enhancement','2024-11-15','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','emergency_contact_nm','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7666','Backfilling of Wildfire protection fields','Enhancement','2024-11-15','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','emergency_contact_nm','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7666','Backfilling of Wildfire protection fields','Enhancement','2024-11-15','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','emergency_contact_phone_no','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7666','Backfilling of Wildfire protection fields','Enhancement','2024-11-15','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','emergency_contact_phone_no','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7666','Backfilling of Wildfire protection fields','Enhancement','2024-11-15','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','emergency_contact_email','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7666','Backfilling of Wildfire protection fields','Enhancement','2024-11-15','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','emergency_contact_email','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7666','Backfilling of Wildfire protection fields','Enhancement','2024-11-15','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','gate_code','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7666','Backfilling of Wildfire protection fields','Enhancement','2024-11-15','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','gate_code','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7698','Update policy_history_sk and term_no for OS transactions','Bug','2024-11-15','Architha Gudimalla','Datafix','edw_core','tpolicy_transaction','policy_history_sk','Updated stored procedure logic to populate policy_history_sk for OS policies in tpolicy_transaction table','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7698','Update policy_history_sk and term_no for OS transactions','Bug','2024-11-15','Architha Gudimalla','Datafix','edw_core','tpolicy','term_no','Updated stored procedure logic to populate term_no for OS policies in tpolicy table','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7653/VI34680','Add lifetime_claim_ct and lifetime_loss_incurred_amt into EDW','Enhancement','2024-11-15','Architha Gudimalla','Addition','edw_core','tpolicy','lifetime_claim_ct','Created new column','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7653/VI34680','Add lifetime_claim_ct and lifetime_loss_incurred_amt into EDW','Enhancement','2024-11-15','Architha Gudimalla','Addition','edw_core','tpolicy','lifetime_loss_incurred_amt','Created new column','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7653/VI34680','Add lifetime_claim_ct and lifetime_loss_incurred_amt into EDW','Enhancement','2024-11-15','Architha Gudimalla','Addition','edw_core','tquote','lifetime_claim_ct','Created new column','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7653/VI34680','Add lifetime_claim_ct and lifetime_loss_incurred_amt into EDW','Enhancement','2024-11-15','Architha Gudimalla','Addition','edw_core','tquote','lifetime_loss_incurred_amt','Created new column','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7632/VI34112','Add issued_quote_history_sk in EDW','Enhancement','2024-11-15','Architha Gudimalla','Addition','edw_core','tquote','issued_quote_history_sk','Created new column','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7631/VI34653','Add Last Inspection date to EDW','Enhancement','2024-11-15','Architha Gudimalla','Addition','edw_core','thome_coverage','last_inspection_dt','Created new column','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7631/VI34653','Add Last Inspection date to EDW','Enhancement','2024-11-15','Architha Gudimalla','Addition','edw_core','tquote_home_coverage','last_inspection_dt','Created new column','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI34924/VI35164','IVANS Policy Resent Request','Bug','2024-11-15','Rushin Shah','Datafix','edw_integration','policy_ivans_pel_feed','','Resent a few policies to IVANS after applying data fixes.  This is just a onetime update.','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7610/VI33671','Created a view for TICO Place Codes','Enhancement','2024-11-15','Architha Gudimalla','Addition','edw_core','vticoplacecode','','Created a view to capture TICO place codes data.','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7656','Update tvalidation_sql to add additional validation','Enhancement','2024-11-15','Sandeep Gundreddy','Addition','edw_core','tvalidation_sql','','Added 4 validations','22','No','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7630/VI34651','North Carolina Clean Risk Loss Assessment - Auto','Bug','2024-11-15','Rushin Shah','Datafix','edw_core','tinternal_coverage','aslob_cd','Updated logic to populate internal coverage “Clean Risk Loss Recoupment” to aslob 192','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7644/VI34591','Ivans - Policy Resend Requests ','Enhancement','2024-11-15','Hernando Garcia','Datafix','edw_integration','policy_ivans_home_feed','','Updated IVANS Home stored procedure logic to capture appropriate coverage code for loss of use and contents coverage.','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7624/VI30288','Delete broker codes created in error','Bug','2024-11-15','Sandeep Gundreddy','Datafix','edw_core','tbroker','','Deleted 22 brokers from Metal and EDW as per the licensing team request. These brokers were created in error due to a Metal issue. The issue is no longer happening. This is just a onetime update.','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7674/AD7620/VI34964','tpel_driver_incident and tquote_pel_driver_incident empty','Bug','2024-11-15','Alberto Almario','Datafix','edw_core','tquote_pel_driver_incident','quote_pel_driver_sk','Updated tquote_pel_driver_incident table stored procedure to populate quote_pel_driver_sk which were null','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7672/AD7620/VI34964','tpel_driver_incident and tquote_pel_driver_incident empty','Bug','2024-11-15','Alberto Almario','Datafix','edw_core','tpel_driver_incident','pel_driver_sk','Updated tpel_driver_incident table stored procedure to populate pel_driver_sk which were null','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7645','Update broker hubspot feed','Enhancement','2024-11-15','Architha Gudimalla','Modification','edw_integration','','','Updated logic for calculating retention percentage.','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7430/VI32150','Transactions missing corresponding stats in tpolicy_transaction','Bug','2024-11-15','Architha Gudimalla','Datafix','edw_core','tpolicy_transaction','','Deleted duplicate cancellation records for 10 old migrated policies in Metal and EDW.  This is just a onetime update.','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI35190','Duplication cancellation records for 2 policies','Bug','2024-11-15','Sandeep Gundreddy','Datafix','edw_core','tpolicy_transaction','','Removed duplicate cancellation transactions for 2 policies (AU100100432-02 and HO200029508-06) from Metal and EDW.  This is an isolated issue in Metal.  This is just a one time update.','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6914','Review bound transactions','Bug','2024-11-15','Sandeep Gundreddy','Datafix','edw_core','tpolicy_transaction','','Following 5 non NY policies (HO100031939-02; HO100135498-01; HO32318043136-05; HO100102593-02; HO100107062-02) were in bound status instead of issued status in Metal.  This is an isolated issue and is no longer happening.  This is just a onetime update.','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD6449/VI30901','Negative premium on HO100102447-02','Bug','2024-11-15','Sandeep Gundreddy','Datafix','edw_core','tpolicy_transaction','','Updated stats premium for transaction sequence =  0 in Metal and EDW.  This is an isolated issue and is no longer happening.  This is just a onetime update.','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7643','Updated retention logic in tbroker_summary for MTD and YTD columns','Enhancement','2024-11-15','Architha Gudimalla','Modification','edw_core','tbroker_summary','policy_expiring_ct','Updated stored procedure logic to load Month to Date(MTD) values instead of Year to date(YTD) values. ','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7643','Updated retention logic in tbroker_summary for MTD and YTD columns','Enhancement','2024-11-15','Architha Gudimalla','Modification','edw_core','tbroker_summary','policy_renewal_accepted_ct','Updated stored procedure logic to load Month to Date(MTD) values instead of Year to date(YTD) values. ','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7643','Updated retention logic in tbroker_summary for MTD and YTD columns','Enhancement','2024-11-15','Architha Gudimalla','Modification','edw_core','tbroker_summary','policy_renewal_ct','Updated stored procedure logic to load Month to Date(MTD) values instead of Year to date(YTD) values. ','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7643','Updated retention logic in tbroker_summary for MTD and YTD columns','Enhancement','2024-11-15','Architha Gudimalla','Modification','edw_core','tbroker_summary','policy_renewal_offered_ct','Updated stored procedure logic to load Month to Date(MTD) values instead of Year to date(YTD) values. ','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7643','Updated retention logic in tbroker_summary for MTD and YTD columns','Enhancement','2024-11-15','Architha Gudimalla','Modification','edw_core','tbroker_summary','policy_renewal_offered_over_50k_ct','Updated stored procedure logic to load Month to Date(MTD) values instead of Year to date(YTD) values. ','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7643','Updated retention logic in tbroker_summary for MTD and YTD columns','Enhancement','2024-11-15','Architha Gudimalla','Modification','edw_core','tbroker_summary','policy_renewal_offered_premium_amt','Updated stored procedure logic to load Month to Date(MTD) values instead of Year to date(YTD) values. ','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7643','Updated retention logic in tbroker_summary for MTD and YTD columns','Enhancement','2024-11-15','Architha Gudimalla','Modification','edw_core','tbroker_summary','policy_renewal_offered_expiring_premium_amt','Updated stored procedure logic to load Month to Date(MTD) values instead of Year to date(YTD) values. ','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7643','Updated retention logic in tbroker_summary for MTD and YTD columns','Enhancement','2024-11-15','Architha Gudimalla','Modification','edw_core','tbroker_summary','policy_expiring_premium_amt','Updated stored procedure logic to load Month to Date(MTD) values instead of Year to date(YTD) values. ','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7643','Updated retention logic in tbroker_summary for MTD and YTD columns','Enhancement','2024-11-15','Architha Gudimalla','Modification','edw_core','tbroker_summary','policy_renewal_premium_amt','Updated stored procedure logic to load Month to Date(MTD) values instead of Year to date(YTD) values. ','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7643','Updated retention logic in tbroker_summary for MTD and YTD columns','Enhancement','2024-11-15','Architha Gudimalla','Modification','edw_core','tbroker_summary','ytd_policy_expiring_ct','Created new column','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7643','Updated retention logic in tbroker_summary for MTD and YTD columns','Enhancement','2024-11-15','Architha Gudimalla','Modification','edw_core','tbroker_summary','ytd_policy_renewal_accepted_ct','Created new column','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7643','Updated retention logic in tbroker_summary for MTD and YTD columns','Enhancement','2024-11-15','Architha Gudimalla','Modification','edw_core','tbroker_summary','ytd_policy_renewal_ct','Created new column','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7643','Updated retention logic in tbroker_summary for MTD and YTD columns','Enhancement','2024-11-15','Architha Gudimalla','Modification','edw_core','tbroker_summary','ytd_policy_renewal_offered_ct','Created new column','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7643','Updated retention logic in tbroker_summary for MTD and YTD columns','Enhancement','2024-11-15','Architha Gudimalla','Modification','edw_core','tbroker_summary','ytd_policy_renewal_offered_over_50k_ct','Created new column','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7643','Updated retention logic in tbroker_summary for MTD and YTD columns','Enhancement','2024-11-15','Architha Gudimalla','Modification','edw_core','tbroker_summary','ytd_policy_renewal_offered_premium_amt','Created new column','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7643','Updated retention logic in tbroker_summary for MTD and YTD columns','Enhancement','2024-11-15','Architha Gudimalla','Modification','edw_core','tbroker_summary','ytd_policy_renewal_offered_expiring_premium_amt','Created new column','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7643','Updated retention logic in tbroker_summary for MTD and YTD columns','Enhancement','2024-11-15','Architha Gudimalla','Modification','edw_core','tbroker_summary','ytd_policy_expiring_premium_amt','Created new column','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7643','Updated retention logic in tbroker_summary for MTD and YTD columns','Enhancement','2024-11-15','Architha Gudimalla','Modification','edw_core','tbroker_summary','ytd_policy_renewal_premium_amt','Created new column','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7729/VI34976','Update ORIGINAL policy effective date in metal for a policy','Bug','2024-10-18','Architha Gudimalla','Datafix','edw_core','tpolicy','original_policy_effective_dt','Updated ORIGINAL policy effective date for HO100085483-05. Data is updated in Metal and will be updated in EDW during next full refresh. This is just a onetime update.','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7729/VI34976','Update subscriber contribution end date in metal for a policy','Bug','2024-10-18','Architha Gudimalla','Datafix','edw_core','tpolicy_insured','subscriber_contribution_end_dt','Updated subscriber contribution end date for HO100085483-05. Data is updated in Metal and will be updated in EDW during next full refresh. This is just a onetime update.','22','Yes','2024-11-18',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7692','Update RelationshipToInsured in metal for one AU policy','Bug','2024-10-18','Architha Gudimalla','Datafix','edw_core','tpolicy_insured','subscriber_contribution_end_dt','Updated RelationshipToInsured  for AU100213229-01 to self. Data is updated in Metal and will be updated in EDW during next full refresh. This is just a onetime update.','22','Yes','2024-11-18',getdate(),getdate());