-- tedw_release_summary
INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 12/09/2024 :</span>
<h4 style="margin-top: 0;">This release includes the following:</h4>
<ol>
    <li>Enhancements - 4
        <ul>
			<li>EDW enhancements - Integration of Boat / Yacht data into EDW.  Following were the new tables created in EDW. </li>
			1) tmarine_boat_yacht<br>
			2) tquote_marine_boat_yacht<br>
			3) tmarine_boat_yacht_location<br>
			4) tquote_marine_boat_yacht_location<br>
			5) tmarine_boat_yacht_coverage<br>
			6) tquote_marine_boat_yacht_coverage<br>
			7) tmarine_boat_yacht_operator<br>
			8) tquote_marine_boat_yacht_operator<br>
			9) tmarine_boat_yacht_watercraft<br>
			10) tquote_marine_boat_yacht_watercraft
			<li>Added state filings 12/06 release related 17 new columns for Home/Condo. </li>
			<li>Added driver_unique_id to tauto_driver & tquote_auto_driver table.</li>
			<li>Added driver_unique_id to tpel_driver & tquote_pel_driver table.</li>
		</ul>
    </li>
    <li>Bug tickets - 10
        <ul>
			<li>Resolved 3 tickets associated with roofCoverageEndorsementRV; roofCoverageEndorsementWH; roofCoverageEndorsementAP fields by making them null.</li>
			<li>Resolved 3 tickets associated with updating BCEGCredit as per user request.</li>
			<li>Resolved 1 ticket associated with updating subscriber_contribution_dt for one policy.</li>
			<li>Resolved 1 ticket associated with updating included_on_dec_in for one policy.</li>
			<li>Resolved 1 ticket associated with deleting duplicate transaction for one policy.</li>
			<li>Resolved 1 ticket associated with adding notes in Metal for a few policies as per user request.</li>
		</ul>
    </li>
</ol>
'
,'Yes'
,'2024-12-09'
,getdate()
,getdate()
)
;

-- tedw_release_note
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7748/VI35207','Roof coverage endorsement updated for one policy','Bug','2024-11-26','Rushin Shah','Datafix','edw_core','thome_additional_coverage','roof_coverage_endorsement_rv_in','Updated "RoofCoverageEndorsementRV" to null for HO200042802.  Data is updated in Metal and EDW.  This is just a onetime update.','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7748/VI35327','Roof coverage endorsement updated for one policy','Bug','2024-11-26','Rushin Shah','Datafix','edw_core','thome_additional_coverage','roof_coverage_endorsement_wh_in','Updated "RoofCoverageEndorsementWH" to null for HO100017264-04.  Data is updated in Metal and EDW.  This is just a onetime update.','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7748/VI35362','Roof coverage endorsement updated for one policy','Bug','2024-11-26','Rushin Shah','Datafix','edw_core','thome_additional_coverage','roof_coverage_endorsement_ap_in','Updated "roofCoverageEndorsementAP" to null for HO100070217-04.  Data is updated in Metal and EDW.  This is just a onetime update.','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7832','State filings 11/02 release related columns','Enhancement','2024-12-06','Tuba Mohsin','Addition','edw_core','thome_coverage','no_of_bathrooms','Created new column','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7832','State filings 11/02 release related columns','Enhancement','2024-12-06','Tuba Mohsin','Addition','edw_core','thome_coverage','no_of_fireplaces','Created new column','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7832','State filings 11/02 release related columns','Enhancement','2024-12-06','Tuba Mohsin','Addition','edw_core','thome_coverage','foundation_type','Created new column','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7832','State filings 11/02 release related columns','Enhancement','2024-12-06','Tuba Mohsin','Addition','edw_core','thome_coverage','waived_inflation_factor_in','Created new column','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7832','State filings 11/02 release related columns','Enhancement','2024-12-06','Tuba Mohsin','Addition','edw_core','tquote_home_coverage','no_of_bathrooms','Created new column','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7832','State filings 11/02 release related columns','Enhancement','2024-12-06','Tuba Mohsin','Addition','edw_core','tquote_home_coverage','no_of_fireplaces','Created new column','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7832','State filings 11/02 release related columns','Enhancement','2024-12-06','Tuba Mohsin','Addition','edw_core','tquote_home_coverage','foundation_type','Created new column','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7832','State filings 11/02 release related columns','Enhancement','2024-12-06','Tuba Mohsin','Addition','edw_core','tquote_home_coverage','waived_inflation_factor_in','Created new column','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7832','State filings 11/02 release related columns','Enhancement','2024-12-06','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','risk_score_water_non_weather','Created new column','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7832','State filings 11/02 release related columns','Enhancement','2024-12-06','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','risk_score_water_weather','Created new column','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7832','State filings 11/02 release related columns','Enhancement','2024-12-06','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','risk_score_water_backup','Created new column','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7832','State filings 11/02 release related columns','Enhancement','2024-12-06','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','risk_score_wind_hail','Created new column','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7832','State filings 11/02 release related columns','Enhancement','2024-12-06','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','risk_score_other','Created new column','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7832','State filings 11/02 release related columns','Enhancement','2024-12-06','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','risk_score_lightning','Created new column','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7832','State filings 11/02 release related columns','Enhancement','2024-12-06','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','risk_score_theft','Created new column','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7832','State filings 11/02 release related columns','Enhancement','2024-12-06','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','risk_score_liability','Created new column','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7832','State filings 11/02 release related columns','Enhancement','2024-12-06','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','risk_score_hurricane','Created new column','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7832','State filings 11/02 release related columns','Enhancement','2024-12-06','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','risk_score_wildfire','Created new column','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7832','State filings 11/02 release related columns','Enhancement','2024-12-06','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','risk_score_sinkhole_mine','Created new column','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7832','State filings 11/02 release related columns','Enhancement','2024-12-06','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','risk_score_all_perils','Created new column','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7832','State filings 11/02 release related columns','Enhancement','2024-12-06','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','full_extended_replacement_cost_in','Created new column','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7832','State filings 11/02 release related columns','Enhancement','2024-12-06','Tuba Mohsin','Addition','edw_core','tquote_thome_additional_coverage','risk_score_water_non_weather','Created new column','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7832','State filings 11/02 release related columns','Enhancement','2024-12-06','Tuba Mohsin','Addition','edw_core','tquote_thome_additional_coverage','risk_score_water_weather','Created new column','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7832','State filings 11/02 release related columns','Enhancement','2024-12-06','Tuba Mohsin','Addition','edw_core','tquote_thome_additional_coverage','risk_score_water_backup','Created new column','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7832','State filings 11/02 release related columns','Enhancement','2024-12-06','Tuba Mohsin','Addition','edw_core','tquote_thome_additional_coverage','risk_score_wind_hail','Created new column','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7832','State filings 11/02 release related columns','Enhancement','2024-12-06','Tuba Mohsin','Addition','edw_core','tquote_thome_additional_coverage','risk_score_other','Created new column','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7832','State filings 11/02 release related columns','Enhancement','2024-12-06','Tuba Mohsin','Addition','edw_core','tquote_thome_additional_coverage','risk_score_lightning','Created new column','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7832','State filings 11/02 release related columns','Enhancement','2024-12-06','Tuba Mohsin','Addition','edw_core','tquote_thome_additional_coverage','risk_score_theft','Created new column','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7832','State filings 11/02 release related columns','Enhancement','2024-12-06','Tuba Mohsin','Addition','edw_core','tquote_thome_additional_coverage','risk_score_liability','Created new column','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7832','State filings 11/02 release related columns','Enhancement','2024-12-06','Tuba Mohsin','Addition','edw_core','tquote_thome_additional_coverage','risk_score_hurricane','Created new column','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7832','State filings 11/02 release related columns','Enhancement','2024-12-06','Tuba Mohsin','Addition','edw_core','tquote_thome_additional_coverage','risk_score_wildfire','Created new column','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7832','State filings 11/02 release related columns','Enhancement','2024-12-06','Tuba Mohsin','Addition','edw_core','tquote_thome_additional_coverage','risk_score_sinkhole_mine','Created new column','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7832','State filings 11/02 release related columns','Enhancement','2024-12-06','Tuba Mohsin','Addition','edw_core','tquote_thome_additional_coverage','risk_score_all_perils','Created new column','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7832','State filings 11/02 release related columns','Enhancement','2024-12-06','Tuba Mohsin','Addition','edw_core','tquote_thome_additional_coverage','full_extended_replacement_cost_in','Created new column','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7386','Integrate boat and yacht data into EDW','Enhancement','2024-12-06','Rushin Shah','Addition','edw_core','tmarine_boat_yacht','','Created new table','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7386','Integrate boat and yacht data into EDW','Enhancement','2024-12-06','Rushin Shah','Addition','edw_core','tquote_marine_boat_yacht','','Created new table','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7386','Integrate boat and yacht data into EDW','Enhancement','2024-12-06','Rushin Shah','Addition','edw_core','tmarine_boat_yacht_location','','Created new table','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7386','Integrate boat and yacht data into EDW','Enhancement','2024-12-06','Rushin Shah','Addition','edw_core','tquote_marine_boat_yacht_location','','Created new table','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7386','Integrate boat and yacht data into EDW','Enhancement','2024-12-06','Rushin Shah','Addition','edw_core','tmarine_boat_yacht_coverage','','Created new table','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7386','Integrate boat and yacht data into EDW','Enhancement','2024-12-06','Rushin Shah','Addition','edw_core','tquote_marine_boat_yacht_coverage','','Created new table','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7386','Integrate boat and yacht data into EDW','Enhancement','2024-12-06','Rushin Shah','Addition','edw_core','tmarine_boat_yacht_operator','','Created new table','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7386','Integrate boat and yacht data into EDW','Enhancement','2024-12-06','Rushin Shah','Addition','edw_core','tquote_marine_boat_yacht_operator','','Created new table','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7386','Integrate boat and yacht data into EDW','Enhancement','2024-12-06','Rushin Shah','Addition','edw_core','tmarine_boat_yacht_watercraft','','Created new table','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7386','Integrate boat and yacht data into EDW','Enhancement','2024-12-06','Rushin Shah','Addition','edw_core','tquote_marine_boat_yacht_watercraft','','Created new table','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7827/VI35352','Update BCEGCreditPercent for one policy','Bug','2024-11-27','Rushin Shah','Datafix','edw_core','thome_coverage','bceg_credit_pc','Updated BCEG Credit Percent for one policy HO100265233-03 in Metal and EDW.  Data is updated in Metal and EDW. This is just a onetime update.','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7827/VI35352','Update BCEGCreditPercent for one policy','Bug','2024-11-27','Rushin Shah','Datafix','edw_core','tquote_home_coverage','bceg_credit_pc','Updated BCEG Credit Percent for one policy HO100265233-03 in Metal and EDW.  Data is updated in Metal and EDW. This is just a onetime update.','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7876/VI35279','Issue with offered endorsement','Bug','2024-12-05','Sandeep Gundreddy','Datafix','edw_core','tpolicy_transaction','','Removed duplicate cancellation transactions for HO200051071 from Metal and EDW.  This is an isolated issue in Metal.  This is just a one time update.','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7756','Add driver_unique_id to Auto policies','Enhancement','2024-11-26','Architha Gudimalla','Addition','edw_core','tauto_driver','driver_unique_id','Created new column','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7756','Add driver_unique_id to Auto policies','Enhancement','2024-11-26','Architha Gudimalla','Addition','edw_core','tquote_auto_driver','driver_unique_id','Created new column','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7757','Add driver_unique_id to PEL policies','Enhancement','2024-11-26','Architha Gudimalla','Addition','edw_core','tpel_driver','driver_unique_id','Created new column','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7757','Add driver_unique_id to PEL policies','Enhancement','2024-11-26','Architha Gudimalla','Addition','edw_core','tquote_pel_driver','driver_unique_id','Created new column','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7823/VI35342','Update subscriber contribution end date in metal for 3 policies','Bug','2024-11-26','Rushin Shah','Datafix','edw_core','tpolicy_insured','subscriber_contribution_end_dt','Updated subscriber contribution end date for HO160389732736-04, HO50254853636-04, EX56292696436-06. Data is updated in Metal and EDW. This is just a onetime update.','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7799/VI35283','Update BCEGCreditPercent for one policy','Bug','2024-11-27','Rushin Shah','Datafix','edw_core','thome_coverage','bceg_credit_pc','Updated BCEG Credit Percent for one policy HO37797523536-06 in Metal and EDW.  Data is updated in Metal and EDW. This is just a onetime update.','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7799/VI35283','Update BCEGCreditPercent for one policy','Bug','2024-11-27','Rushin Shah','Datafix','edw_core','tquote_home_coverage','bceg_credit_pc','Updated BCEG Credit Percent for one policy HO37797523536-06 in Metal and EDW.  Data is updated in Metal and EDW. This is just a onetime update.','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7799/VI35299','Update BCEGCreditPercent for one policy','Bug','2024-11-27','Rushin Shah','Datafix','edw_core','thome_coverage','bceg_credit_pc','Updated BCEG Credit Percent for one policy HO89198089536-04 in Metal and EDW.  Data is updated in Metal and EDW. This is just a onetime update.','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7799/VI35299','Update BCEGCreditPercent for one policy','Bug','2024-11-27','Rushin Shah','Datafix','edw_core','tquote_home_coverage','bceg_credit_pc','Updated BCEG Credit Percent for one policy HO89198089536-04 in Metal and EDW.  Data is updated in Metal and EDW. This is just a onetime update.','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7822/VI35252','Pending NR Rescissions Needed - Invalid Reason Codes','Bug','2024-11-27','Sandeep Gundreddy','Datafix','edw_core','tnote','','Added notes in Metal as per user request for few policies.  This is just a one time update.','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7820/VI35157','Update included on dec for 1 policy','Bug','2024-11-26','Rushin Shah','Datafix','edw_core','tpolicy_insured','include_on_dec_in','Updated included on dec for one policy EX100078369-02 in Metal and EDW.  Data is updated in Metal and EDW. This is just a onetime update.','23','Yes','2024-12-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7820/VI35157','Update included on dec for 1 policy','Bug','2024-11-26','Rushin Shah','Datafix','edw_core','tquote_insured','include_on_dec_in','Updated included on dec for one policy EX100078369-02 in Metal and EDW.  Data is updated in Metal and EDW. This is just a onetime update.','23','Yes','2024-12-09',getdate(),getdate());