-- tedw_release_summary
INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 12/23/2024 :</span>
<h4 style="margin-top: 0;">This release includes the following:</h4>
<ol>
    <li>Enhancements - 5
        <ul>
			<li>Datamart enhancements - Added 30 new columns to tbroker_summary table. </li>
			<li>Added state filings 12/21 release related new columns risk_score_fire for Home/Condo. </li>
			<li>Backfilled wildfire protection data using information gathered from manual forms for the Redzone feed. </li>
			<li>Backfilled data for rater_pip_discount column in tauto_vehicle_coverage & tquote_auto_vehicle_coverage table.</li>
			<li>Fixed long column names in LC360.</li>
		</ul>
    </li>
    <li>Bug tickets - 11
        <ul>
			<li>Resolved 1 ticket associated with roofCoverageEndorsementRV fields by making them null.</li>
			<li>Resolved 1 ticket associated with correcting garging location id for auto policies in metal to correctly calcualte rate capping. This is just a onetime datefix in metal with no impact on EDW.</li>
			<li>Resolved 2 tickets associated with adding alerts to list of policies as per user request.</li>
			<li>Resolved 1 ticket by updating stored procedure logic to titem_summary to capture boat/yacht data.</li>
			<li>Resolved 5 tickets associated with updateing the IVAN Auto stored procedure to exclude deleted drivers from data feed and repushing a few policies.</li>
			<li>Resolved 1 ticket associated with updating initial rating tier for one policy.</li>
		</ul>
    </li>
</ol>
'
,'Yes'
,'2024-12-23'
,getdate()
,getdate()
)
;

-- tedw_release_note
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7988/VI35692','Roof coverage endorsement updated for one policy','Bug','2024-12-18','Rushin Shah','Datafix','edw_core','thome_additional_coverage','roof_coverage_endorsement_rv_in','Updated "RoofCoverageEndorsementRV" to null for HO100072593-03.  Data is updated in Metal and EDW.  This is just a onetime update.','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7988/VI35692','Roof coverage endorsement updated for one policy','Bug','2024-12-18','Rushin Shah','Datafix','edw_core','tquote_home_additional_coverage','roof_coverage_endorsement_rv_in','Updated "RoofCoverageEndorsementRV" to null for HO100072593-03.  Data is updated in Metal and EDW.  This is just a onetime update.','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7963','State filings 12/21 release related columns','Enhancement','2024-12-20','Tuba Mohsin','Addition','edw_core','thome_coverage','risk_score_fire','Created new column','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7963','State filings 12/21 release related columns','Enhancement','2024-12-20','Tuba Mohsin','Addition','edw_core','tquote_home_coverage','risk_score_fire','Created new column','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7805','Backfilling of Wildfire protection fields','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','wildfire_protection_enrollment_in','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7805','Backfilling of Wildfire protection fields','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','wildfire_protection_enrollment_in','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7805','Backfilling of Wildfire protection fields','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','site_scheduling_contact_nm','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7805','Backfilling of Wildfire protection fields','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','site_scheduling_contact_nm','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7805','Backfilling of Wildfire protection fields','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','site_scheduling_phone_no','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7805','Backfilling of Wildfire protection fields','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','site_scheduling_phone_no','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7805','Backfilling of Wildfire protection fields','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','site_scheduling_email','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7805','Backfilling of Wildfire protection fields','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','site_scheduling_email','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7805','Backfilling of Wildfire protection fields','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','emergency_contact_nm','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7805','Backfilling of Wildfire protection fields','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','emergency_contact_nm','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7805','Backfilling of Wildfire protection fields','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','emergency_contact_phone_no','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7805','Backfilling of Wildfire protection fields','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','emergency_contact_phone_no','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7805','Backfilling of Wildfire protection fields','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','emergency_contact_email','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7805','Backfilling of Wildfire protection fields','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','emergency_contact_email','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7805','Backfilling of Wildfire protection fields','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','gate_code','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7805','Backfilling of Wildfire protection fields','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','gate_code','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7941','Datamart Enhancement - tbroker_summary','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','tbroker_summary','prior_ytd_new_business_dwelling_limit_amt','Created new column','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7941','Datamart Enhancement - tbroker_summary','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','tbroker_summary','prior_ytd_new_business_tiv_amt','Created new column','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7941','Datamart Enhancement - tbroker_summary','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','tbroker_summary','prior_qtd_new_business_dwelling_limit_amt','Created new column','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7941','Datamart Enhancement - tbroker_summary','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','tbroker_summary','prior_qtd_new_business_tiv_amt','Created new column','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7941','Datamart Enhancement - tbroker_summary','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','tbroker_summary','prior_mtd_new_business_dwelling_limit_amt','Created new column','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7941','Datamart Enhancement - tbroker_summary','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','tbroker_summary','prior_mtd_new_business_tiv_amt','Created new column','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7941','Datamart Enhancement - tbroker_summary','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','tbroker_summary','ytd_new_business_dwelling_limit_amt','Created new column','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7941','Datamart Enhancement - tbroker_summary','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','tbroker_summary','ytd_new_business_tiv_amt','Created new column','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7941','Datamart Enhancement - tbroker_summary','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','tbroker_summary','qtd_new_business_dwelling_limit_amt','Created new column','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7941','Datamart Enhancement - tbroker_summary','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','tbroker_summary','qtd_new_business_tiv_amt','Created new column','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7941','Datamart Enhancement - tbroker_summary','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','tbroker_summary','mtd_new_business_dwelling_limit_amt','Created new column','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7941','Datamart Enhancement - tbroker_summary','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','tbroker_summary','mtd_new_business_tiv_amt','Created new column','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7941','Datamart Enhancement - tbroker_summary','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','tbroker_summary','prior_ytd_quote_dwelling_limit_amt','Created new column','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7941','Datamart Enhancement - tbroker_summary','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','tbroker_summary','prior_ytd_quote_tiv_amt','Created new column','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7941','Datamart Enhancement - tbroker_summary','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','tbroker_summary','prior_qtd_quote_dwelling_limit_amt','Created new column','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7941','Datamart Enhancement - tbroker_summary','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','tbroker_summary','prior_qtd_quote_tiv_amt','Created new column','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7941','Datamart Enhancement - tbroker_summary','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','tbroker_summary','prior_mtd_quote_dwelling_limit_amt','Created new column','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7941','Datamart Enhancement - tbroker_summary','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','tbroker_summary','prior_mtd_quote_tiv_amt','Created new column','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7941','Datamart Enhancement - tbroker_summary','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','tbroker_summary','ytd_quote_dwelling_limit_amt','Created new column','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7941','Datamart Enhancement - tbroker_summary','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','tbroker_summary','ytd_quote_tiv_amt','Created new column','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7941','Datamart Enhancement - tbroker_summary','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','tbroker_summary','qtd_quote_dwelling_limit_amt','Created new column','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7941','Datamart Enhancement - tbroker_summary','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','tbroker_summary','qtd_quote_tiv_amt','Created new column','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7941','Datamart Enhancement - tbroker_summary','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','tbroker_summary','mtd_quote_dwelling_limit_amt','Created new column','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7941','Datamart Enhancement - tbroker_summary','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','tbroker_summary','mtd_quote_tiv_amt','Created new column','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7941','Datamart Enhancement - tbroker_summary','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','tbroker_summary','inforce_dwelling_limit_amt','Created new column','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7941','Datamart Enhancement - tbroker_summary','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','tbroker_summary','inforce_tiv_amt','Created new column','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7941','Datamart Enhancement - tbroker_summary','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','tbroker_summary','mtd_mid_term_cancellation_ct','Created new column','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7941','Datamart Enhancement - tbroker_summary','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','tbroker_summary','mtd_mid_term_cancellation_home_sold_ct','Created new column','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7941','Datamart Enhancement - tbroker_summary','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','tbroker_summary','mtd_mid_term_cancellation_coverage_replaced_ct','Created new column','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7941','Datamart Enhancement - tbroker_summary','Enhancement','2024-12-20','Architha Gudimalla','Addition','edw_core','tbroker_summary','mtd_mid_term_cancellation_non_pay_ct','Created new column','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7933/AD7944','Need to add a alert note to a group of policies ','Bug','2024-12-18','Rushin Shah','Datafix','edw_core','tnote','','Added alerts in Metal as per the request','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7895','Boat/yacht data missing in titem_summary','Bug','2024-12-20','Architha Gudimalla','Datafix','edw_core','titem_summary','','Fixed the issue associated with loading of boat/yacht data into titem_summary table.  This is just a onetime update.','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7911','Backfilling of rater_pip_discount data','Enhancement','2024-12-20','Architha Gudimalla','Modification','edw_core','tauto_vehicle_coverage','rater_pip_discount','Backfilled data in Metal and EDW.  Thisis just a onetime update.','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7911','Backfilling of rater_pip_discount data','Enhancement','2024-12-20','Architha Gudimalla','Modification','edw_core','tquote_auto_vehicle_coverage','rater_pip_discount','Backfilled data in Metal and EDW.  Thisis just a onetime update.','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7969','LC360 data','Enhancement','2024-12-20','Architha Gudimalla','Modification','edw_core','vlc360','','Fixed long column names in LC360','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7947','IVANS Auto Update ','Bug','2024-12-20','Alberto Almario','Modification','edw_integration','policy_ivans_auto_feed','AU_Drivers','Updated the stored procedure to not send deleted drivers in the daily feed.','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI35564/VI35563/VI35443/VI35690','Ivans - Policy Resend Requests ','Bug','2024-12-18','Rushin Shah','Datafix','edw_integration','policy_ivans_auto_feed','','Resent a few policies to IVANS after applying data fixes.  This is just a onetime update.','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI35591/AD7954','PA Auto Rate Capping not working','Bug','2024-12-20','Architha Gudimalla','Datafix','edw_stage','','','Corrected garging location id for auto policies in metal to correctly calcualte the rate capping. This is just a onetime datefix in metal.  No impact on EDW.','24','Yes','2024-12-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI35669/AD7998','Datafix - InitialRatingTier','Bug','2024-12-20','Architha Gudimalla','Datafix','edw_stage','','','No impact to EDW data. This datafix is to correct InitialRating Tier for AU100175695-02. This is just a onetime datefix in metal','24','Yes','2024-12-23',getdate(),getdate());