-- tedw_release_summary
INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 01/06/2025 :</span>
<h4 style="margin-top: 0;">This release includes the following:</h4>
<ol>
    <li>Enhancements - 2
        <ul>
			<li>Updated EDW stored procedure to exclude rejected claims while calculating lifetime claim count. </li>
			<li>Backfilled wildfire protection data using information gathered from manual forms for the Redzone feed. </li>
		</ul>
    </li>
    <li>Bug tickets - 6
        <ul>
			<li>Resolved 1 ticket associated with deleting 7 duplicate eBao transactions for accurate reporting. This is just a onetime datafix in EDW.</li>
			<li>Resolved 1 ticket associated with roofCoverageEndorsementRV fields by making them null.</li>
			<li>Resolved 1 ticket associated with roofCoverageEndorsementWH fields by making them null.</li>
			<li>Resolved 1 ticket associated with updating total square footage for one policy.</li>
			<li>Resolved 1 ticket associated with updating inspection date for one policy.</li>
			<li>Resolved 1 ticket by updating stored procedure logic for hubspot customer and quote feed to capture appropriate last name where insured type is entity.</li>
		</ul>
    </li>
</ol>
'
,'Yes'
,'2025-01-06'
,getdate()
,getdate()
)
;

-- tedw_release_note
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8026/VI35845','Roof coverage endorsement updated for one policy','Bug','2025-01-02','Rushin Shah','Datafix','edw_core','thome_additional_coverage','roof_coverage_endorsement_rv_in','Updated "RoofCoverageEndorsementRV" to null for HO100257144-04.  Data is updated in Metal and EDW.  This is just a onetime update.','25','Yes','2025-01-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8026/VI35845','Roof coverage endorsement updated for one policy','Bug','2025-01-02','Rushin Shah','Datafix','edw_core','tquote_home_additional_coverage','roof_coverage_endorsement_rv_in','Updated "RoofCoverageEndorsementRV" to null for HO100257144-04.  Data is updated in Metal and EDW.  This is just a onetime update.','25','Yes','2025-01-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8026/VI35758','Roof coverage endorsement updated for one policy','Bug','2025-01-02','Rushin Shah','Datafix','edw_core','thome_additional_coverage','roof_coverage_endorsement_wh_in','Updated "RoofCoverageEndorsementWH" to null for HO100201986-02.  Data is updated in Metal and EDW.  This is just a onetime update.','25','Yes','2025-01-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8026/VI35758','Roof coverage endorsement updated for one policy','Bug','2025-01-02','Rushin Shah','Datafix','edw_core','tquote_home_additional_coverage','roof_coverage_endorsement_wh_in','Updated "RoofCoverageEndorsementRV" to null for HO100201986-02.  Data is updated in Metal and EDW.  This is just a onetime update.','25','Yes','2025-01-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8029/VI35806','Square footage updated for one policy','Bug','2025-01-02','Rushin Shah','Datafix','edw_core','thome_coverage','total_finished_square_feet','Updated Total Square Feet for HO200046548.  This is just a onetime datefix in metal.','25','Yes','2025-01-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8029/VI35806','Square footage updated for one policy','Bug','2025-01-02','Rushin Shah','Datafix','edw_core','tquote_home_coverage','total_finished_square_feet','Updated Total Square Feet for HO200046548.  This is just a onetime datefix in metal.','25','Yes','2025-01-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8028/VI34680','Exclude rejected claims from lifetime claims','Enhancement','2025-01-02','Alberto Almario','Modification','edw_core','tpolicy','lifetime_claim_ct','Updated EDW stored procedure to exclude rejected claims while calculating lifetime claim count.','25','Yes','2025-01-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8032/VI35797','Deletion of eBao Duplicate transactions','Bug','2025-01-02','Rushin Shah','Datafix','edw_core','tclaim_transaction','','Identified and deleted 7 duplicate eBao claim transactions from EDW for accurate reporting.  ','25','Yes','2025-01-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8032/VI35797','Deletion of eBao Duplicate transactions','Bug','2025-01-02','Rushin Shah','Datafix','edw_core','tclaim_summary','','Identified and deleted 7 duplicate eBao claim transactions from EDW for accurate reporting.  ','25','Yes','2025-01-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8032/VI35797','Deletion of eBao Duplicate transactions','Bug','2025-01-02','Rushin Shah','Datafix','edw_core','tclaim_feature_summary','','Identified and deleted 7 duplicate eBao claim transactions from EDW for accurate reporting.  ','25','Yes','2025-01-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8012/VI35256','Insured name is blank for entity/trust LLC','Bug','2025-01-02','Alberto Almario','Datafix','edw_integration','customer_hubspot_feed','last_nm','Updated stored procedure logic for hubspot customer feed to capture appropriate last name where insured type is entity','25','Yes','2025-01-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8012/VI35256','Insured name is blank for entity/trust LLC','Bug','2025-01-02','Alberto Almario','Datafix','edw_integration','quote_hubspot_feed','insured_last_nm','Updated stored procedure logic for hubspot quote feed to capture appropriate last name where insured type is entity','25','Yes','2025-01-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7821/VI35216','Datafix : Update inspection date for one policy','Bug','2025-01-02','Architha Gudimalla','Datafix','edw_core','thome_coverage','last_inspection_dt','Updated last inspection date for HO100030047-04.  Data is updated in Metal and EDW.  This is just a onetime update.','25','Yes','2025-01-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7821/VI35216','Datafix : Update inspection date for one policy','Bug','2025-01-02','Architha Gudimalla','Datafix','edw_core','tquote_home_coverage','last_inspection_dt','Updated last inspection date for HO100030047-04.  Data is updated in Metal and EDW.  This is just a onetime update.','25','Yes','2025-01-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8031','Update tvalidation_sql to add additional validation','Enhancement','2025-01-02','Yunus Mohammed','Addition','edw_core','tvalidation_sql','Added 1 validation to capture duplicate claim transactions','','25','No','2025-01-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8041','Backfilling of Wildfire protection fields','Enhancement','2025-01-02','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','wildfire_protection_enrollment_in','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','25','Yes','2025-01-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8041','Backfilling of Wildfire protection fields','Enhancement','2025-01-02','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','wildfire_protection_enrollment_in','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','25','Yes','2025-01-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8041','Backfilling of Wildfire protection fields','Enhancement','2025-01-02','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','site_scheduling_contact_nm','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','25','Yes','2025-01-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8041','Backfilling of Wildfire protection fields','Enhancement','2025-01-02','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','site_scheduling_contact_nm','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','25','Yes','2025-01-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8041','Backfilling of Wildfire protection fields','Enhancement','2025-01-02','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','site_scheduling_phone_no','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','25','Yes','2025-01-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8041','Backfilling of Wildfire protection fields','Enhancement','2025-01-02','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','site_scheduling_phone_no','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','25','Yes','2025-01-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8041','Backfilling of Wildfire protection fields','Enhancement','2025-01-02','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','site_scheduling_email','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','25','Yes','2025-01-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8041','Backfilling of Wildfire protection fields','Enhancement','2025-01-02','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','site_scheduling_email','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','25','Yes','2025-01-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8041','Backfilling of Wildfire protection fields','Enhancement','2025-01-02','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','emergency_contact_nm','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','25','Yes','2025-01-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8041','Backfilling of Wildfire protection fields','Enhancement','2025-01-02','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','emergency_contact_nm','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','25','Yes','2025-01-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8041','Backfilling of Wildfire protection fields','Enhancement','2025-01-02','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','emergency_contact_phone_no','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','25','Yes','2025-01-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8041','Backfilling of Wildfire protection fields','Enhancement','2025-01-02','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','emergency_contact_phone_no','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','25','Yes','2025-01-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8041','Backfilling of Wildfire protection fields','Enhancement','2025-01-02','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','emergency_contact_email','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','25','Yes','2025-01-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8041','Backfilling of Wildfire protection fields','Enhancement','2025-01-02','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','emergency_contact_email','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','25','Yes','2025-01-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8041','Backfilling of Wildfire protection fields','Enhancement','2025-01-02','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','gate_code','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','25','Yes','2025-01-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8041','Backfilling of Wildfire protection fields','Enhancement','2025-01-02','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','gate_code','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','25','Yes','2025-01-06',getdate(),getdate());
