-- tedw_release_summary
INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 01/27/2025 :</span>
<h4 style="margin-top: 0;">This release includes the following:</h4>
<ol>
    <li>Enhancements - 5
        <ul>
			<li>Added state filings 1/25 release related 3 new columns for Home/Condo/Collections (fenced_pool_in, theft_or_loss_general_conditions_endorsement_in, animal_related_liability_endorsement_in). </li>
			<li>Backfilled wildfire protection data using information gathered from manual forms for the Redzone feed. </li>
			<li>Removed latitude and longitude columns from tmarine_boat_yacht_location and tquote_marine_boat_yacht_location tables. </li>
			<li>Updated IVANS Home data feed to incorporate introduction of granular coverages which gets rolled into AOP. </li>
			<li>Addition of uw_company_original_policy_effective_dt to tpolicy and tquote tables. </li>
		</ul>
    </li>
    <li>Bug tickets - 17
        <ul>
			<li>Resolved 1 ticket associated with updating 600 Home/Condo/Collections policies that were missing latitude and longitude columns. This is just a onetime datafix in EDW.</li>
			<li>Resolved 1 ticket associated with updating water damage limitation endorsement limit.</li>
			<li>Resolved 1 ticket associated with updating inspection date for ~7000 policies.</li>
			<li>Resolved 1 ticket associated with updating "water damage" loss type to "water" for multiple policies.</li>
			<li>Resolved 1 ticket associated with updating CoverageDOption to null where CoverageDOption = 0 and CoverageDPercentage > 0 for multiple policies.</li>
			<li>Resolved 1 ticket associated with updating logic in the hubspot broker feed stored procedure to exclude marine brokers.</li>
			<li>Resolved 1 ticket associated with updating logic in the tloss_history stored procedure to load include_in_rating_in column.</li>
			<li>Resolved 1 ticket associated with updating BCEGCreditPercent for one policy.</li>
			<li>Resolved 2 tickets associated with updating special characters from address fields affecting 2 policies for CLUE property feed.</li>
			<li>Resolved 7 tickets associated with repushing of IVANS policies.</li>
		</ul>
    </li>
</ol>
'
,'Yes'
,'2025-01-27'
,getdate()
,getdate()
)
;

-- tedw_release_note
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8250','Backfilling of Wildfire protection fields','Enhancement','2025-01-24','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','wildfire_protection_enrollment_in','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8250','Backfilling of Wildfire protection fields','Enhancement','2025-01-24','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','wildfire_protection_enrollment_in','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8250','Backfilling of Wildfire protection fields','Enhancement','2025-01-24','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','site_scheduling_contact_nm','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8250','Backfilling of Wildfire protection fields','Enhancement','2025-01-24','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','site_scheduling_contact_nm','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8250','Backfilling of Wildfire protection fields','Enhancement','2025-01-24','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','site_scheduling_phone_no','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8250','Backfilling of Wildfire protection fields','Enhancement','2025-01-24','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','site_scheduling_phone_no','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8250','Backfilling of Wildfire protection fields','Enhancement','2025-01-24','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','site_scheduling_email','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8250','Backfilling of Wildfire protection fields','Enhancement','2025-01-24','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','site_scheduling_email','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8250','Backfilling of Wildfire protection fields','Enhancement','2025-01-24','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','emergency_contact_nm','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8250','Backfilling of Wildfire protection fields','Enhancement','2025-01-24','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','emergency_contact_nm','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8250','Backfilling of Wildfire protection fields','Enhancement','2025-01-24','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','emergency_contact_phone_no','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8250','Backfilling of Wildfire protection fields','Enhancement','2025-01-24','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','emergency_contact_phone_no','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8250','Backfilling of Wildfire protection fields','Enhancement','2025-01-24','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','emergency_contact_email','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8250','Backfilling of Wildfire protection fields','Enhancement','2025-01-24','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','emergency_contact_email','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8250','Backfilling of Wildfire protection fields','Enhancement','2025-01-24','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','gate_code','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8250','Backfilling of Wildfire protection fields','Enhancement','2025-01-24','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','gate_code','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI35216/AD7821','Metal datafix - Update Inspection Date','Bug','2025-01-06','Architha Gudimalla','Datafix','','','','No impact to EDW. One time datafix was done in metal to update inspection date for about 7000 policies','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI35892/AD8071','Metal datafix - Update BCEGCreditPercent for one policy','Bug','2025-01-24','Architha Gudimalla','Datafix','edw_core','thome_coverage','bceg_credit_pc','Updated BCEG Credit Percent for one policy HO100116934-02 in Metal and EDW.  Data is updated in Metal and EDW. This is just a onetime update.','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI35892/AD8071','Metal datafix - Update BCEGCreditPercent for one policy','Bug','2025-01-24','Architha Gudimalla','Datafix','edw_core','tquote_home_coverage','bceg_credit_pc','Updated BCEG Credit Percent for one policy HO100116934-02 in Metal and EDW.  Data is updated in Metal and EDW. This is just a onetime update.','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI35944/AD8141','Metal datafix - Update Water Damage loss type to water','Bug','2025-01-10','Architha Gudimalla','Datafix','edw_core','tloss_history','type_of_loss','One time bulk datafix was done to all losses to update loss type from Water damage to Water','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI35944/AD8141','Metal datafix - Update Water Damage loss type to water','Bug','2025-01-10','Architha Gudimalla','Datafix','edw_core','tquote_loss_history','type_of_loss','One time bulk datafix was done to all losses to update loss type from Water damage to Water','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI35980/AD8149','Metal datafix - Update Loss of use option to null','Bug','2025-01-10','Architha Gudimalla','Datafix','edw_core','thome_coverage','loss_of_use_option','One time datafix was done to all policies to update loss of use option to null when it is 0  and loss of use % was greater than 0','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8150','Metal datafix - Update Latitude for missing home policies ','Bug','2025-01-13','Architha Gudimalla','Datafix','edw_core','thome_location','latitude','One time datafix was done to update null Latitude','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8150','Metal datafix - Update Longitude for missing home policies ','Bug','2025-01-13','Architha Gudimalla','Datafix','edw_core','thome_location','longitude','One time datafix was done to update null Latitude','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8150','Metal datafix - Update Latitude for missing collection policies ','Bug','2025-01-13','Architha Gudimalla','Datafix','edw_core','tcollection_location','latitude','One time datafix was done to update null Latitude','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8150','Metal datafix - Update Longitude for missing collection policies ','Bug','2025-01-13','Architha Gudimalla','Datafix','edw_core','tcollection_location','longitude','One time datafix was done to update null Latitude','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI35879/AD8205','Metal datafix - Update Water Damage Limitation  Endorsement Limit to 0','Bug','2025-01-14','Architha Gudimalla','Datafix','edw_core','thome_additional_coverage','waterdamage_limitation_endorsement_limit_amt','Updated Water Damage Limitation Endorsement Limit to 0 for one policy HO100126623-02.  Data is updated in Metal and EDW. This is just a onetime update.','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI35879/AD8205','Metal datafix - Update Water Damage Limitation Endorsement to null','Bug','2025-01-14','Architha Gudimalla','Datafix','edw_core','thome_additional_coverage','waterdamage_limitation_endorsement_in','Updated Water Damage Limitation Endorsement to Null for one policy HO100126623-02.  Data is updated in Metal and EDW. This is just a onetime update.','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8207','Metal datafix - Updated spanish character in the address for two polciies to support Clue','Bug','2025-01-14','Architha Gudimalla','Datafix','edw_core','thome_location','address_line_1 ','Updated mailing and location address for HO200034033 and HO200042778 to remove the spanish character.  Data is updated in Metal and EDW. This is just a onetime update.','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8207','Metal datafix - Updated spanish character in the address for two polciies to support Clue','Bug','2025-01-14','Architha Gudimalla','Datafix','edw_core','tpolicy','mailing_address_line1 ','Updated mailing and location address for HO200034033 and HO200042778 to remove the spanish character.  Data is updated in Metal and EDW. This is just a onetime update.','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI35894/AD8173','Hubspot - - Update null underwrited in the broker feed','Bug','2025-01-14','Architha Gudimalla','Modification','edw_integration','broker_hubspot_feed','new_business_uw_nm','Logic in the broker feed procedure was updated to exclude marine brokers','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI35894/AD8173','Hubspot - - Update null underwrited in the broker feed','Bug','2025-01-14','Architha Gudimalla','Modification','edw_integration','broker_hubspot_feed','renewal_uw_nm','Logic in the broker feed procedure was updated to exclude marine brokers','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI36061/AD8233','Hubspot - - Update null underwrited in the broker feed','Bug','2025-01-14','Architha Gudimalla','Modification','edw_core','tloss_history','include_in_rating_in','Updated logic in the loss history procedure for policies to load the column','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI36061/AD8233','Hubspot - - Update null underwrited in the broker feed','Bug','2025-01-14','Architha Gudimalla','Modification','edw_core','tquote_loss_history','include_in_rating_in','Updated logic in the loss history procedure for quotes to load the column','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI33968/AD7635','tpolicy - added original effective date by company','Enhancement','2025-01-24','Architha Gudimalla','Addition','edw_core','tpolicy','uw_company_original_policy_effective_dt','Created new column','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI33968/AD7635','tpolicy - added original effective date by company','Enhancement','2025-01-24','Architha Gudimalla','Addition','edw_core','tquote','uw_company_original_policy_effective_dt','Created new column','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8164','State filings 1/25 release related columns','Enhancement','2025-01-24','Tuba Mohsin','Addition','edw_core','thome_coverage','fenced_pool_in','Created new column','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8164','State filings 1/25 release related columns','Enhancement','2025-01-24','Tuba Mohsin','Addition','edw_core','tquote_home_coverage','fenced_pool_in','Created new column','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8164','State filings 1/25 release related columns','Enhancement','2025-01-24','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','theft_or_loss_general_conditions_endorsement_in','Created new column','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8164','State filings 1/25 release related columns','Enhancement','2025-01-24','Tuba Mohsin','Addition','edw_core','tquote_home_additional_coverage','theft_or_loss_general_conditions_endorsement_in','Created new column','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8164','State filings 1/25 release related columns','Enhancement','2025-01-24','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','animal_related_liability_endorsement_in','Created new column','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8164','State filings 1/25 release related columns','Enhancement','2025-01-24','Tuba Mohsin','Addition','edw_core','tquote_home_additional_coverage','animal_related_liability_endorsement_in','Created new column','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8164','State filings 1/25 release related columns','Enhancement','2025-01-24','Tuba Mohsin','Addition','edw_core','tcollection_coverage','theft_or_loss_general_conditions_endorsement_in','Created new column','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8164','State filings 1/25 release related columns','Enhancement','2025-01-24','Tuba Mohsin','Addition','edw_core','tquote_collection_coverage','theft_or_loss_general_conditions_endorsement_in','Created new column','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7831','Remove latitude and longitude columns from yacht location tables','Enhancement','2025-01-24','Rushin Shah','Deletion','edw_core','tmarine_boat_yacht_location','latitude','Deleted column','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7831','Remove latitude and longitude columns from yacht location tables','Enhancement','2025-01-24','Rushin Shah','Deletion','edw_core','tmarine_boat_yacht_location','longitude','Deleted column','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7831','Remove latitude and longitude columns from yacht location tables','Enhancement','2025-01-24','Rushin Shah','Deletion','edw_core','tquote_marine_boat_yacht_location','latitude','Deleted column','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7831','Remove latitude and longitude columns from yacht location tables','Enhancement','2025-01-24','Rushin Shah','Deletion','edw_core','tquote_marine_boat_yacht_location','longitude','Deleted column','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8175','Fix applied to Clue Property file rejections','Bug','2025-01-24','Alberto Almario','Datafix','edw_integration','claim_clue_property_feed','riskAddressStreetName','Removed special characters from address fields affecting 2 policies from Metal and EDW.  This is just a one time update.','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8175','Fix applied to Clue Property file rejections','Bug','2025-01-24','Alberto Almario','Datafix','edw_integration','claim_clue_property_feed','policyHolderMailAddressStreetName','Removed special characters from address fields affecting 2 policies from Metal and EDW.  This is just a one time update.','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8044','IVANS Home Feed update','Enhancement','2025-01-24','Rushin Shah','Modification','edw_integration','policy_ivans_home_feed','','Updated IVANS Home data feed to incorporate introduction of granular coverages which gets rolled into AOP.','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI36200;VI36198;VI36020;VI36021;VI35954;VI36121;VI36124','IVANS Policy Resent Request','Bug','2025-01-24','Rushin Shah','Datafix','edw_integration','policy_ivans_home_feed','','Resent a few home policies to IVANS','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI36200;VI36198;VI36020;VI36021;VI35954;VI36121;VI36124','IVANS Policy Resent Request','Bug','2025-01-24','Rushin Shah','Datafix','edw_integration','policy_ivans_auto_feed','','Resent a few auto policies to IVANS','26','Yes','2025-01-27',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI36200;VI36198;VI36020;VI36021;VI35954;VI36121;VI36124','IVANS Policy Resent Request','Bug','2025-01-24','Rushin Shah','Datafix','edw_integration','policy_ivans_pel_feed','','Resent a few PEL policies to IVANS','26','Yes','2025-01-27',getdate(),getdate());