update edw_core.taslob set aslob_cd='211', aslob_desc= 'Auto Physical Damage' where aslob_sk = 47 and product_cd='Auto' and coverage_cd='PD Liability Limit'
update edw_core.taslob set aslob_cd='090' where aslob_sk = 12 and product_cd='Collections' and coverage_cd='Any'
update edw_core.taslob set aslob_cd='090' where aslob_sk = 16 and product_cd='Collections' and coverage_cd='Scheduled Property Item'
update edw_core.taslob set aslob_cd='090' where aslob_sk = 81 and product_cd='Collections' and coverage_cd='Valuable Articles Coverage - Bank Vaulted Jewelry Scheduled'
update edw_core.taslob set aslob_cd='090' where aslob_sk = 82 and product_cd='Collections' and coverage_cd='Valuable Articles Coverage - Guns Scheduled'
update edw_core.taslob set aslob_cd='090' where aslob_sk = 69 and product_cd='Collections' and coverage_cd='Valuable Articles Coverage - Misc Blanket'
update edw_core.taslob set aslob_cd='090' where aslob_sk = 83 and product_cd='Collections' and coverage_cd='Valualbe Articles Coverage - Wine Scheduled'
update edw_core.taslob set aslob_cd='040', aslob_desc= 'Homeowners' where aslob_sk = 28 and product_cd='Homeowners' and coverage_cd='HO Collections - Blanket Limit'
update edw_core.taslob set aslob_cd='040', aslob_desc= 'Homeowners' where aslob_sk = 38 and product_cd='Homeowners' and coverage_cd='HO Collections - Blanket Limit'
update edw_core.taslob set aslob_cd='090' where aslob_sk = 42 and product_cd='Homeowners' and coverage_cd='Scheduled Property Item'
update edw_core.taslob set aslob_cd='090' where aslob_sk = 84 and product_cd='Homeowners' and coverage_cd='Valuable Articles Coverage - Bank Vaulted Jewelry Scheduled'
update edw_core.taslob set aslob_cd='090' where aslob_sk = 64 and product_cd='Homeowners' and coverage_cd='Valuable Articles Coverage - Fine Arts Blanket'
update edw_core.taslob set aslob_cd='090' where aslob_sk = 66 and product_cd='Homeowners' and coverage_cd='Valuable Articles Coverage - Guns Blanket'
update edw_core.taslob set aslob_cd='090' where aslob_sk = 85 and product_cd='Homeowners' and coverage_cd='Valuable Articles Coverage - Guns Scheduled'
update edw_core.taslob set aslob_cd='090' where aslob_sk = 72 and product_cd='Homeowners' and coverage_cd='Valuable Articles Coverage - Wine Blanket'
update edw_core.taslob set aslob_cd='090' where aslob_sk = 86 and product_cd='Homeowners' and coverage_cd='Valualbe Articles Coverage - Wine Scheduled'