-- tedw_release_summary
INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 02/24/2025 :</span>
<h4 style="margin-top: 0;">This release includes the following:</h4>
<ol>
    <li>Enhancements - 2
        <ul>
			<li>Workday Reporting : Enhanced stored procedure logic for claim payments, reserves, and reserves inception-to-date files to accurately calculate payment/reserve amounts by incorporating new additional amount columns introduced in Snapsheet. </li>
			<li>CLUE Property Feed : Updated logic to include overpayment while calculating  claim amount. </li>
		</ul>
    </li>
    <li>Bug tickets - 9
        <ul>
			<li>Updated ceded_premium_amt to 0 for HSB transactions which had a gross premium amount of 0. This is just a onetime update.</li>
			<li>Resolved 1 ticket associated with updating loan number for one policy. This is just a onetime datafix.</li>
			<li>Resolved 1 ticket associated with updating waterdamage_limitation_endorsement_in and waterdamage_limitation_endorsement_limit_amt for one policy. This is just a onetime datafix.</li>
			<li>Resolved 1 ticket associated with updating BCEG credit percent for one policy. This is just a onetime datafix.</li>
			<li>Various one time data fixes associated with eBao to Snapsheet Claims Migration.</li>
			<li>Updated logic to populate payee address fields in tclaim_payment table.</li>
			</li>Updated logic to populate source_of_fire in tclaim table.</li>
		</ul>
    </li>
</ol>
'
,'Yes'
,'2025-02-24'
,getdate()
,getdate()
)
;

-- tedw_release_note
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8469','Snapsheet implementation data fix : Updated logic to populate source_of_fire in tclaim table','Bug','2025-02-22','Rushin Shah','Datafix','edw_core','tclaim','source_of_fire','Updated logic to populate source_of_fire','28','Yes','2025-02-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI36212/AD8529','Policy not pushed to majesco HO200055428','Bug','2025-02-22','Architha Gudimalla','Datafix','edw_core','tmortgagee','loan_no','Updated loan number to null for one policy','28','Yes','2025-02-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI36151/AD8530','Update water damage limit for one policy HO100236277-02','Bug','2025-02-22','Architha Gudimalla','Datafix','edw_core','thome_additional_coverage','waterdamage_limitation_endorsement_in','Updated waterdamage_limitation_endorsement_in to null for one policy','28','Yes','2025-02-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI36151/AD8530','Update water damage limit for one policy HO100236277-02','Bug','2025-02-22','Architha Gudimalla','Datafix','edw_core','thome_additional_coverage','waterdamage_limitation_endorsement_limit_amt','Updated waterdamage_limitation_endorsement_limit_amt to null for one policy','28','Yes','2025-02-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI36453/VI36549/AD8531','Metal datafix - Update BCEGCreditPercent for one policy','Bug','2025-02-22','Architha Gudimalla','Datafix','edw_core','thome_coverage','bceg_credit_pc','Updated BCEG Credit Percent for HO36832122136-06 and HO100245003-06 in Metal and EDW.  Data is updated in Metal and EDW. This is just a onetime update.','28','Yes','2025-02-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI36453/VI36549/AD8531','Metal datafix - Update BCEGCreditPercent for one policy','Bug','2025-02-22','Architha Gudimalla','Datafix','edw_core','tquote_home_coverage','bceg_credit_pc','Updated BCEG Credit Percent for HO36832122136-06 and HO100245003-06 in Metal and EDW.  Data is updated in Metal and EDW. This is just a onetime update.','28','Yes','2025-02-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8280','Data fix for ceded premium','Bug','2025-02-22','Rushin Shah','Datafix','edw_core','tpolicy_transaction','ceded_premium_amt','Updated ceded_premium_amt to 0 for HSB transactions which had a gross premium amount of 0.  Data is updated in Metal and EDW. This is just a onetime update.','28','Yes','2025-02-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8280','Data fix for ceded premium','Bug','2025-02-22','Rushin Shah','Datafix','edw_core','tquote_transaction','ceded_premium_amt','Updated ceded_premium_amt to 0 for HSB transactions which had a gross premium amount of 0.  Data is updated in Metal and EDW. This is just a onetime update.','28','Yes','2025-02-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8510','Clue property feed modification','Enhancement','2025-02-22','Sandeep Gundreddy','Modification','edw_integration','claim_clue_property_feed','claimAmount','Updated logic to include overpayment while calculating  claim amount ','28','Yes','2025-02-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8400','Snapsheet implementation data fix : Updated logic to populate payee address fields in tclaim_payment table','Bug','2025-02-22','Alberto Almario','Datafix','edw_core','tclaim_payment','payee_address','Updated logic to populate payee_address.','28','Yes','2025-02-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8611','Update datatype for 3 columns for edw_stage.AccountTransactionCoveragePremium','Bug','2025-02-22','Architha Gudimalla','Datafix','edw_stage','AccountTransactionCoveragePremium','CededPremium','Updated the datatype to decimal(16,4) for this column to match with Metal tables.','28','No','2025-02-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8611','Update datatype for 3 columns for edw_stage.AccountTransactionCoveragePremium','Bug','2025-02-22','Architha Gudimalla','Datafix','edw_stage','AccountTransactionCoveragePremium','CededPremiumDelta','Updated the datatype to decimal(16,4) for this column to match with Metal tables.','28','No','2025-02-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8611','Update datatype for 3 columns for edw_stage.AccountTransactionCoveragePremium','Bug','2025-02-22','Architha Gudimalla','Datafix','edw_stage','AccountTransactionCoveragePremium','CededPremiumDeltaProRated','Updated the datatype to decimal(16,4) for this column to match with Metal tables.','28','No','2025-02-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8608','Workday updates : Updates to claim payment file','Enhancement','2025-02-22','Yunus Mohammed','Modification','edw_integration','claim_workday_payment_feed','paymentamount','Updated the logic to calculate payment amount based on the new additional amount columns introduced in Snapsheet','28','Yes','2025-02-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8608','Workday updates : Updates to claim reserves file','Enhancement','2025-02-22','Yunus Mohammed','Modification','edw_integration','claim_workday_reserve_feed','reserve_amount','Updated the logic to calculate reserve amount based on the new additional amount columns introduced in Snapsheet','28','Yes','2025-02-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8608','Workday updates : Updates to claim reserve itd file','Enhancement','2025-02-22','Yunus Mohammed','Modification','edw_integration','claim_workday_itd_reserve_feed','reserve_amount','Updated the logic to calculate reserve amount based on the new additional amount columns introduced in Snapsheet','28','Yes','2025-02-22',getdate(),getdate());