-- tedw_release_summary
INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 03/10/2025 :</span>
<h4 style="margin-top: 0;">This release includes the following:</h4>
<ol>
    <li>Enhancements - 13
        <ul>
			<li>Snapsheet related enhancements : </li>
			1) Added automated data validation scripts to ensure data quality and to ensure that the data was successfully migrated.<br>
			2) Updated stored procedure logic to load policy_effective_dt in tclaim table for NFP policies.<br>
			3) Updated stored procedure logic to load payment_submitted_nm and payment_approver_nm in tclaim_payment table.<br>
			4) Updated stored procedure logic to load missing payee_nm in tclaim_payment table.<br>
			5) Updated stored procedure logic to load missing recovery payment into snapsheet financial transactions actions table.<br>
			6) Loaded missing coverage name and aslob into tclaim_feature and tclaim_feature_summary tables.<br>
			7) Updated stored procedure logic to remove extra spaces in region variable for policyEntities field in snapsheet policy search and policy webhook.<br>
			8) Created provisional policies to support litigation claims in Snapsheet.
			<li>EDW Enhancements : </li>
			1) Updated quote_status logic by capturing new quote close types and reasons in EDW for better reporting on lost business.  Also added competitor_carrier_nm and close_reason_other_desc to tquote table.<br>
			2) Updated quote_status related columns in summary table to reflect new quote close reasons. Refreshed quote_status related columns in trenewal_summary and tbroker_summary tables to reflect new quote close reasons. <br>
			3) Added transaction_status field to tpolicy_history table to capture reversed/reversal/issued transactions status.<br>
			4) Updated logic to load transaction reviewed/created user_sk in tquote_transaction and tpolicy_transaction.
			<li>Backfilled wildfire protection data using information gathered from manual forms for the Redzone feed. </li>
		</ul>
    </li>
    <li>Bug tickets - 13
        <ul>
			<li>Updated stored procedure logic to load missing extended_liability_location_ct in thome_additional_coverage table.</li>
			<li>Updated stored procedure logic to populate term_no in tpolicy table for cancelled rewrite policies.</li>
			<li>Rollback defense_reserve_amt for historic ebao transactions.</li>
			<li>Minor code changes applied to HSB inforce feed to make it production ready.</li>
			<li>Fixed a few home_cyber_protection_coverage_limit_amt and home_systems_protection_limit_amt by making them null where the indicator for these coverages were no but limit amounts were set. This is just a onetime datafix.</li>
			<li>Fixed wind_or_hailstorm_deductible data format issues for home policies. This is just a onetime datafix.</li>
			<li>Resolved 1 ticket associated with updating logic to send latest broker information in quotes and policy feed to hubspot.</li>
			<li>Resolved 1 ticket associated with updating BCEGCreditPercent for one policy.</li>
			<li>Resolved 1 ticket associated with updating CreatedDate and UpdatedDate for one record in user table</li>
			<li>Resolved 2 tickets associated with repushing of policies associated with data fixes applied on IVANS.</li>
			<li>Resolved 1 ticket associated with adding alerts to list of policies as per user request.</li>
			<li>Fixed missing users in tuser table. Fixed data in following downstream tables associated with this change. </li>
			1) tuser<br>
			2) tbroker_vault_team<br>
			3) tnote<br>
			4) tquote_note_hubspot_feed<br>
			5) tquote_status_history<br>
			6) tquote_transaction_status_history<br>
			7) tquote_history<br>
			8) tpolicy_history<br>
			9) ttask
		</ul>
    </li>
</ol>
'
,'Yes'
,'2025-03-10'
,getdate()
,getdate()
)
;

-- tedw_release_note
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8715','Backfilling of Wildfire protection fields','Enhancement','2025-03-07','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','wildfire_protection_enrollment_in','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8715','Backfilling of Wildfire protection fields','Enhancement','2025-03-07','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','wildfire_protection_enrollment_in','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8715','Backfilling of Wildfire protection fields','Enhancement','2025-03-07','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','site_scheduling_contact_nm','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8715','Backfilling of Wildfire protection fields','Enhancement','2025-03-07','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','site_scheduling_contact_nm','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8715','Backfilling of Wildfire protection fields','Enhancement','2025-03-07','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','site_scheduling_phone_no','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8715','Backfilling of Wildfire protection fields','Enhancement','2025-03-07','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','site_scheduling_phone_no','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8715','Backfilling of Wildfire protection fields','Enhancement','2025-03-07','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','site_scheduling_email','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8715','Backfilling of Wildfire protection fields','Enhancement','2025-03-07','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','site_scheduling_email','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8715','Backfilling of Wildfire protection fields','Enhancement','2025-03-07','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','emergency_contact_nm','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8715','Backfilling of Wildfire protection fields','Enhancement','2025-03-07','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','emergency_contact_nm','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8715','Backfilling of Wildfire protection fields','Enhancement','2025-03-07','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','emergency_contact_phone_no','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8715','Backfilling of Wildfire protection fields','Enhancement','2025-03-07','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','emergency_contact_phone_no','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8715','Backfilling of Wildfire protection fields','Enhancement','2025-03-07','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','emergency_contact_email','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8715','Backfilling of Wildfire protection fields','Enhancement','2025-03-07','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','emergency_contact_email','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8715','Backfilling of Wildfire protection fields','Enhancement','2025-03-07','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','gate_code','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8715','Backfilling of Wildfire protection fields','Enhancement','2025-03-07','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','gate_code','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8684','EDW Enhancements : Modify logic to load user_sk in tquote_transaction and tpolicy_transaction','Enhancement','2025-03-07','Architha Gudimalla','Modification','edw_core','tquote_transaction','user_sk','Updated logic to load transaction created user_sk in tquote_transaction','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8684','EDW Enhancements : Modify logic to load user_sk in tquote_transaction and tpolicy_transaction','Enhancement','2025-03-07','Architha Gudimalla','Modification','edw_core','tpolicy_transaction','user_sk','Updated logic to load transaction reviewed/created user_sk in tpolicy_transaction','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8672','EDW External Integrations : HSB inforce data feed fixes','Bug','2025-03-07','Alberto Valbuena','Datafix','edw_integration','policy_hsb_cyber_feed','','Minor code changes applied to HSB inforce feed to make it production ready.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8672','EDW External Integrations : HSB inforce data feed fixes','Bug','2025-03-07','Alberto Valbuena','Datafix','edw_integration','policy_hsb_hsp_feed','','Minor code changes applied to HSB inforce feed to make it production ready.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8672','EDW External Integrations : HSB inforce data feed fixes','Bug','2025-03-07','Alberto Valbuena','Datafix','edw_integration','policy_hsb_slc_feed','','Minor code changes applied to HSB inforce feed to make it production ready.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8766','Data Standardization : Cyber protection and system protection indicator vs limit amount mismatch','Bug','2025-03-07','Rushin Shah','Datafix','edw_core','thome_additional_coverage','home_cyber_protection_coverage_limit_amt','Fixed a few home_cyber_protection_coverage_limit_amt by making them null where the indicator for these coverages were no but limit amounts were set.  This is a one time fix applied in Metal and EDW.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8766','Data Standardization : Cyber protection and system protection indicator vs limit amount mismatch','Bug','2025-03-07','Rushin Shah','Datafix','edw_core','thome_additional_coverage','home_systems_protection_limit_amt','Fixed a few home_systems_protection_limit_amt by making them null where the indicator for these coverages were no but limit amounts were set.  This is a one time fix applied in Metal and EDW.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8342','Data Standardization : Wind_or_hailstorm_deductible is coming as 0 instead of null','Bug','2025-03-07','Rushin Shah','Datafix','edw_core','thome_coverage','wind_or_hailstorm_deductible','Fixed a few Wind_or_hailstorm_deductible by making them null where it was coming as 0. This is a one time fix applied in Metal and EDW.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8771/VI36729','Data Fixes : Null Values in extended_liability_location_ct','Bug','2025-03-07','Alberto Valbuena','Datafix','edw_core','thome_additional_coverage','extended_liability_location_ct','Updated stored procedure logic to load missing extended_liability_location_ct.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7981/AD8751','Snapsheet related enhancements : Added new validations for snapsheet claims','Enhancement','2025-03-07','Sandeep Gundreddy','Addition','edw_core','tvalidation_sql','','Added automated data validation scripts to ensure data quality and to ensure that the data was successfully migrated.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8659','Data Fixes : Fix missing users in tuser table and in downstream tables','Bug','2025-03-07','Architha Gudimalla','Datafix','edw_core','tuser','','Fixed missing users in tuser table and updated data in all downstream tables associated with this change.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8659','Data Fixes : Fix missing users in tuser table and in downstream tables','Bug','2025-03-07','Architha Gudimalla','Datafix','edw_core','tbroker_vault_team','team_member_nm','Fixed missing team_member_nm in tbroker_vault_team table.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8659','Data Fixes : Fix missing users in tuser table and in downstream tables','Bug','2025-03-07','Architha Gudimalla','Datafix','edw_core','tnote','user_sk','Fixed missing user_sk in tnote table.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8659','Data Fixes : Fix missing users in tuser table and in downstream tables','Bug','2025-03-07','Architha Gudimalla','Datafix','edw_core','tquote_note_hubspot_feed','note_user_nm','Fixed missing note_user_nm in tquote_note_hubspot_feed table.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8659','Data Fixes : Fix missing users in tuser table and in downstream tables','Bug','2025-03-07','Architha Gudimalla','Datafix','edw_core','tquote_status_history','user_sk','Fixed missing user_sk in tquote_status_history table.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8659','Data Fixes : Fix missing users in tuser table and in downstream tables','Bug','2025-03-07','Architha Gudimalla','Datafix','edw_core','tquote_transaction_status_history','user_sk','Fixed missing user_sk in tquote_transaction_status_history table.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8659','Data Fixes : Fix missing users in tuser table and in downstream tables','Bug','2025-03-07','Architha Gudimalla','Datafix','edw_core','tquote_history','underwriter_nm','Fixed missing underwriter_nm in tquote_history table.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8659','Data Fixes : Fix missing users in tuser table and in downstream tables','Bug','2025-03-07','Architha Gudimalla','Datafix','edw_core','tpolicy_history','underwriter_nm','Fixed missing underwriter_nm in tpolicy_history table.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8659','Data Fixes : Fix missing users in tuser table and in downstream tables','Bug','2025-03-07','Architha Gudimalla','Datafix','edw_core','ttask','created_by_nm','Fixed missing created_by_nm in ttask table.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8659','Data Fixes : Fix missing users in tuser table and in downstream tables','Bug','2025-03-07','Architha Gudimalla','Datafix','edw_core','ttask','assigned_to_nm','Fixed missing assigned_to_nm in tbroker_vault_team table.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8659','Data Fixes : Fix missing users in tuser table and in downstream tables','Bug','2025-03-07','Architha Gudimalla','Datafix','edw_core','ttask','completed_by_nm','Fixed missing completed_by_nm in ttask table.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8783','Data Fixes : Rollback defense_reserve_amt for historic ebao transactions','Bug','2025-03-07','Sandeep Gundreddy','Datafix','edw_core','tclaim_transaction','defense_reserve_amt','Rollback defense_reserve_amt for historic ebao transactions (we had moved expense_reserve_amt to defense_reserve_amt previously which was rollbacked now)','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8145','Snapsheet related enhancements : Populate payment_submitted_nm, payment_submitted_dt, payment_approver_nm and payment_approver_dt in tclaim_payment table','Enhancement','2025-03-07','Sandeep Gundreddy','Modification','edw_core','tclaim_payment','payment_submitted_nm','Updated stored procedure logic to load payment_submitted_nm.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8145','Snapsheet related enhancements : Populate payment_submitted_nm, payment_submitted_dt, payment_approver_nm and payment_approver_dt in tclaim_payment table','Enhancement','2025-03-07','Sandeep Gundreddy','Modification','edw_core','tclaim_payment','payment_submitted_dt','Updated stored procedure logic to load payment_submitted_dt.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8145','Snapsheet related enhancements : Populate payment_submitted_nm, payment_submitted_dt, payment_approver_nm and payment_approver_dt in tclaim_payment table','Enhancement','2025-03-07','Sandeep Gundreddy','Modification','edw_core','tclaim_payment','payment_approver_nm','Updated stored procedure logic to load payment_approver_nm.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8145','Snapsheet related enhancements : Populate payment_submitted_nm, payment_submitted_dt, payment_approver_nm and payment_approver_dt in tclaim_payment table','Enhancement','2025-03-07','Sandeep Gundreddy','Modification','edw_core','tclaim_payment','payment_approver_dt','Updated stored procedure logic to load payment_approver_dt.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8665','Snapsheet related enhancements : Populate missing payee_nm is missing in tclaim_payment table','Enhancement','2025-03-07','Sandeep Gundreddy','Modification','edw_core','tclaim_payment','','Updated stored procedure logic to load missing payee_nm in tclaim_payment table.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8729','Snapsheet related enhancements : Load missing policy effecive date for NFP policies in tclaim table','Enhancement','2025-03-07','Yunus Mohammed','Modification','edw_core','tclaim','policy_effective_dt','Updated stored procedure logic to load policy_effective_dt in tclaim table for NFP policies.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8631','Snapsheet related enhancements : Populate missing aslob and coverage name in tclaim_feature and tclaim_feature_summary tables','Enhancement','2025-03-07','Rushin Shah','Modification','edw_core','tclaim_feature','claim_coverage_desc','Loaded missing coverage name and aslob into tclaim_feature and tclaim_feature_summary tables','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8631','Snapsheet related enhancements : Populate missing aslob and coverage name in tclaim_feature and tclaim_feature_summary tables','Enhancement','2025-03-07','Rushin Shah','Modification','edw_core','tclaim_feature','aslob_sk','Loaded missing coverage name and aslob into tclaim_feature and tclaim_feature_summary tables','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8631','Snapsheet related enhancements : Populate missing aslob and coverage name in tclaim_feature and tclaim_feature_summary tables','Enhancement','2025-03-07','Rushin Shah','Modification','edw_core','tclaim_feature_summary','aslob_sk','Loaded missing coverage name and aslob into tclaim_feature and tclaim_feature_summary tables','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8568','Provisional policy for Vault UW Litigation companies','Enhancement','2025-03-07','Yunus Mohammed','Addition','edw_core','tpolicy','policy_no','Created provisional policies to support litigation claims in Snapsheet.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8532','NFP policies for policy search and policy webhook','Enhancement','2025-03-07','Bhaskar Muthyala','Modification','edw_stage','nfp_policy','','Updated stored procedure logic to remove extra spaces in region variable for policyEntities field in Snapsheet policy search & Policy Webhook.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8532','NFP policies for policy search and policy webhook','Enhancement','2025-03-07','Bhaskar Muthyala','Modification','edw_stage','claim_policy_webhook_snapsheet_api','','Updated stored procedure logic to remove extra spaces in region variable for policyEntities field in Snapsheet policy search & Policy Webhook.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8753','Snapsheet related enhancements : Populate missing recovery payment data','Enhancement','2025-03-07','Yunus Mohammed','Modification','edw_integration','claim_financial_transaction_action_snapsheet_api','','Updated stored procedure logic to load recovery payment in Snapsheet financial transactions actions table.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8526/VI35627','EDW Enhancements : Add reversed/reversal transaction indicators','Enhancement','2025-03-07','Architha Gudimalla','Addition','edw_core','tpolicy_history','transaction_status','Added transaction_status field to tpolicy_history table to capture reversed/reversal/issued transactions status.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8317','EDW Enhancements : Quote close reasons updates and field additions','Enhancement','2025-03-07','Architha Gudimalla','Addition','edw_core','tquote','competitor_carrier_nm','Created new column.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8317','EDW Enhancements : Quote close reasons updates and field additions','Enhancement','2025-03-07','Architha Gudimalla','Addition','edw_core','tquote','close_reason_other_desc','Created new column.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8317','EDW Enhancements : Quote close reasons updates and field additions','Enhancement','2025-03-07','Architha Gudimalla','Addition','edw_core','tquote','quote_status','Updated quote_status logic by capturing new quote close types and reasons in EDW for better reporting on lost business.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8347','EDW Enhancements : Refreshed summary tables for quote_status logic to get reflected with updated quote reasons','Enhancement','2025-03-07','Architha Gudimalla','Datafix','edw_core','trenewal_summary','offered_or_not_taken_quote_ct','Refreshed quote_status related columns in summary table to reflect new quote close reasons.','29','No','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8347','EDW Enhancements : Refreshed summary tables for quote_status logic to get reflected with updated quote reasons','Enhancement','2025-03-07','Architha Gudimalla','Datafix','edw_core','tbroker_summary','open_submission_ct','Refreshed quote_status related columns in summary table to reflect new quote close reasons.','29','No','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8347','EDW Enhancements : Refreshed summary tables for quote_status logic to get reflected with updated quote reasons','Enhancement','2025-03-07','Architha Gudimalla','Datafix','edw_core','tbroker_summary','policy_renewal_offered_ct','Refreshed quote_status related columns in summary table to reflect new quote close reasons.','29','No','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8347','EDW Enhancements : Refreshed summary tables for quote_status logic to get reflected with updated quote reasons','Enhancement','2025-03-07','Architha Gudimalla','Datafix','edw_core','tbroker_summary','policy_renewal_offered_over_50k_ct','Refreshed quote_status related columns in summary table to reflect new quote close reasons.','29','No','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI36539/VI36806','IVANS Policy Resent Request','Bug','2025-03-07','Rushin Shah','Datafix','edw_integration','policy_ivans_home_feed','','Resent a few home policies to IVANS','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI36539/VI36806','IVANS Policy Resent Request','Bug','2025-03-07','Rushin Shah','Datafix','edw_integration','policy_ivans_auto_feed','','Resent a few auto policies to IVANS','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI36539/VI36806','IVANS Policy Resent Request','Bug','2025-03-07','Rushin Shah','Datafix','edw_integration','policy_ivans_pel_feed','','Resent a few PEL policies to IVANS','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8781','EDW External Integrations : Fix hubspot customer/quote feed to send latest data from broker/broker vault','Bug','2025-03-07','Architha Gudimalla','Datafix','edw_integration','quote_hubspot_feed','broker_nm','Updated logic to send latest broker information in quotes and policy feed.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8781','EDW External Integrations : Fix hubspot customer/quote feed to send latest data from broker/broker vault','Bug','2025-03-07','Architha Gudimalla','Datafix','edw_integration','quote_hubspot_feed','broker_tier','Updated logic to send latest broker information in quotes and policy feed.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8781','EDW External Integrations : Fix hubspot customer/quote feed to send latest data from broker/broker vault','Bug','2025-03-07','Architha Gudimalla','Datafix','edw_integration','quote_hubspot_feed','national_agency_in','Updated logic to send latest broker information in quotes and policy feed.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8781','EDW External Integrations : Fix hubspot customer/quote feed to send latest data from broker/broker vault','Bug','2025-03-07','Architha Gudimalla','Datafix','edw_integration','quote_hubspot_feed','bdm_nm','Updated logic to send latest broker information in quotes and policy feed.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8781','EDW External Integrations : Fix hubspot customer/quote feed to send latest data from broker/broker vault','Bug','2025-03-07','Architha Gudimalla','Datafix','edw_integration','customer_hubspot_feed','broker_nm','Updated logic to send latest broker information in quotes and policy feed.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8781','EDW External Integrations : Fix hubspot customer/quote feed to send latest data from broker/broker vault','Bug','2025-03-07','Architha Gudimalla','Datafix','edw_integration','customer_hubspot_feed','broker_phone_no','Updated logic to send latest broker information in quotes and policy feed.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8781','EDW External Integrations : Fix hubspot customer/quote feed to send latest data from broker/broker vault','Bug','2025-03-07','Architha Gudimalla','Datafix','edw_integration','customer_hubspot_feed','bdm_nm','Updated logic to send latest broker information in quotes and policy feed.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI36549','Metal datafix - Update BCEGCreditPercent for one policy','Bug','2025-03-07','Architha Gudimalla','Datafix','edw_core','thome_coverage','bceg_credit_pc','Updated BCEG Credit Percent for one policy HO100116934-02 in Metal and EDW.  Data is updated in Metal and EDW. This is just a onetime update.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI36693','Need to add a alert note to a group of policies ','Bug','2025-03-07','Architha Gudimalla','Datafix','edw_core','tnote','create_ts','Added alerts in Metal as per the request','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8792','Invalid createddate & updatedate in user table for one record','Bug','2025-03-07','Architha Gudimalla','Datafix','edw_stage','User','CreatedDate','Updated CreatedDate and UpdatedDate for one record in Metal.  This is a onetime update.','29','Yes','2025-03-10',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8792','Invalid createddate & updatedate in user table for one record','Bug','2025-03-07','Architha Gudimalla','Datafix','edw_stage','User','UpdatedDate','Updated CreatedDate and UpdatedDate for one record in Metal.  This is a onetime update.','29','Yes','2025-03-10',getdate(),getdate());