-- tedw_release_summary
INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 03/24/2025 :</span>
<h4 style="margin-top: 0;font-style: italic;color: blue;">This release had 17 enhancements and 13 bug fix tickets.  Release details are as follows. </h4>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; }
        h1, h2 { color: #333; }
        ul { margin: 10px 0; padding-left: 20px; }
    </style>
</head>
<body>
    <h2 style="font-style: italic;">1. EDW/Datamart Enhancements</h2>
    

    <ul>
        <li>Integration of Redzone data into EDW</li>
        <li>Added column - premium_rater_version in tpolicy_history and tquote_history tables</li>
        <li>Updated datatype to nvarchar(max) for column - remark in tclaim_payment table</li>
        <li>Created a view - vnfppolicy to query NFP data</li>
        <li>Added the following coverage codes to taslob table:
            <ul>
                <li>Auto: Split Limits & Underinsured Motorist Liability</li>
                <li>PEL: Excess Liability</li>
                <li>Home: Screen Enclosure & Water Damage limitation</li>
            </ul>
        </li>
        <li>Updated stored procedure to load migrated stop payments in tclaim_transaction table</li>
        <li>Updated logic to populate missing item_sk in tclaim_feature table</li>
    </ul>
    
  <h3>Metal 3/22 Release:</h3>
  <ul>
        <li>Added the following new fields:</li>
    <ul>
        <li>target_account: tpolicy and tquote tables</li>
        <li>wildfire_risk_score: thome_coverage and tquote_home_coverage tables</li>
        <li>wildfire_risk_class: thome_coverage and tquote_home_coverage tables</li>
    </ul>
    </ul>
    
    <h2 style="font-style: italic;">2. EDW Process Improvements</h2>
    <ul>
        <li>Automated daily data quality checks for loss incurred amounts between EDW and Snapsheet</li>
        <li>Automated daily checks for missing claim coverage descriptions, aslob_sk, item_sk, coverage_sk, and vehicle_coverage_sk in tclaim_feature table</li>
        <li>Automated daily checks for missing feature_status_sk in tclaim_transaction table</li>
        <li>Automated daily checks for policies with gross premium but missing ceded premium</li>
    </ul>
    
    <h2 style="font-style: italic;">3. EDW Integrations</h2>
    <h3>a. Workday Enhancements</h3>
    <ul>
        <li>Updated annual statement line of business in tinternal_coverage table:</li>
        <ul>
            <li>Collections: From 090 to 091</li>
            <li>Marine Boat Yacht: From 090 to 080</li>
        </ul>
        <li>Updated claim payment file to populate payment_no in transaction_id column</li>
    </ul>
    
    <h3>b. Snapsheet</h3>
    <ul>
        <li>Created provisional records for customers (tcustomer table) and policies (tpolicy table) to support litigation claims in Snapsheet</li>
    </ul>
    
    <h3>c. HSB Reinsurance Feed</h3>
    <ul>
        <li>Updated logic to send monthly inforce files to a new FTP location as requested by HSB team</li>
    </ul>
    
    <h3>d. Hubspot</h3>
    <ul>
        <li>Added the following new fields:</li>
        <ul>
            <li>ytd_new_business_yacht_premium_amt</li>
            <li>occupancy_type</li>
            <li>new_client_for_agency_in</li>
            <li>current_underlying_company_nm</li>
            <li>note_user_nm</li>
        </ul>
    </ul>
    
    <h2 style="font-style: italic;">4. Data Standardization</h2>
    <ul>
        <li>Fixed wind_or_hailstorm_deductible data format issues for home policies</li>
    </ul>
    
    <h2 style="font-style: italic;">5. Data Fixes</h2>
    <ul>
        <li>VI-36893: Updated “original effective date” for AU100046425-05 in Metal and EDW.</li>
        <li>VI-36974: Updated “inspection status” for 18 policies in Metal.</li>
        <li>VI-36968: Updated “relationship to insured” for AU100155682-03 in Metal and EDW.</li>
        <li>VI-37010: Updated “initial rating tier” for AU100124072-03 in Metal and EDW.</li>
        <li>VI-37027: Inserted one transaction associated with CO100168218-03 in Metal and EDW.</li>
        <li>VI-36784: Added alert notes on user-requested accounts in Metal.</li>
        <li>VI-37084: Updated DateTimeReceived for HO200037041 in Metal.</li>
        <li>VI37011/VI37037/VI36198/VI36671: Resent IVANS policies associated with these tickets.</li>
    </ul>
</body>
'
,'Yes'
,'2025-03-24'
,getdate()
,getdate()
)
;

-- tedw_release_note
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8839','EDW/Datamart Enhancements: Metal 3/22 Release Field additions','Enhancement','2025-03-22','Tuba Mohsin','Addition','edw_core','thome_coverage','wildfire_risk_score','Created new column','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8839','EDW/Datamart Enhancements: Metal 3/22 Release Field additions','Enhancement','2025-03-22','Tuba Mohsin','Addition','edw_core','thome_coverage','wildfire_risk_class','Created new column','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8839','EDW/Datamart Enhancements: Metal 3/22 Release Field additions','Enhancement','2025-03-22','Tuba Mohsin','Addition','edw_core','tquote_home_coverage','wildfire_risk_score','Created new column','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8839','EDW/Datamart Enhancements: Metal 3/22 Release Field additions','Enhancement','2025-03-22','Tuba Mohsin','Addition','edw_core','tquote_home_coverage','wildfire_risk_class','Created new column','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8919','EDW/Datamart Enhancements: Metal 3/22 Release Field additions','Enhancement','2025-03-22','Sandeep Gundreddy','Addition','edw_core','tpolicy','target_account','Created new column','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8919','EDW/Datamart Enhancements: Metal 3/22 Release Field additions','Enhancement','2025-03-22','Sandeep Gundreddy','Addition','edw_core','tquote','target_account','Created new column','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8897','EDW/Datamart Enhancements: Integration of Redzone data into EDW','Enhancement','2025-03-22','Architha Gudimalla','Addition','edw_core','vredzone','','Created new view','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8848/VI36041','EDW/Datamart Enhancements: Added column - premium_rater_version in tpolicy_history and tquote_history tables','Enhancement','2025-03-22','Bhaskar Muthyala','Addition','edw_core','tpolicy_history','premium_rater_version','Created new column','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8848/VI36041','EDW/Datamart Enhancements: Added column - premium_rater_version in tpolicy_history and tquote_history tables','Enhancement','2025-03-22','Bhaskar Muthyala','Addition','edw_core','tquote_history','premium_rater_version','Created new column','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8900','EDW/Datamart Enhancements: Created a view - vnfppolicy to query NFP data','Enhancement','2025-03-22','Sandeep Gundreddy','Addition','edw_core','vnfppolicy ','','Created new view','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8812','EDW/Datamart Enhancements: Modify tclaim_payment/remark data type to nvarchar(max)','Enhancement','2025-03-22','Sandeep Gundreddy','Modification','edw_core','tclaim_payment','remark','Updated datatype to nvarchar(max)','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8904','EDW Process Enhancements : Validation to check incorrect ceded premium','Enhancement','2025-03-22','Sandeep Gundreddy','Addition','edw_core','tvalidation_sql','','Added a new validation to check records with gross premium but no ceded premium with HSB coverages','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8846','HSB Reinsurance Feed : Update FTP location','Enhancement','2025-03-22','Alberto Valbuena','Modification','edw_integration','policy_hsb_cyber_feed','','Updated logic to send monthly inforce files to new FTP location requested by HSB team','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8846','HSB Reinsurance Feed : Update FTP location','Enhancement','2025-03-22','Alberto Valbuena','Modification','edw_integration','policy_hsb_hsp_feed','','Updated logic to send monthly inforce files to new FTP location requested by HSB team','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8846','HSB Reinsurance Feed : Update FTP location','Enhancement','2025-03-22','Alberto Valbuena','Modification','edw_integration','policy_hsb_slc_feed','','Updated logic to send monthly inforce files to new FTP location requested by HSB team','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8872/VI36968','Data Fixes: AU100155682-03 need data fix for Relationship To Insured','Bug','2025-03-22','Bhaskar Muthyala','Datafix','edw_core','tquote_auto_driver','relationship_to_insured','Updated “relationship to insured” for AU100155682-03 in Metal and EDW','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8872/VI36968','Data Fixes: AU100155682-03 need data fix for Relationship To Insured','Bug','2025-03-22','Bhaskar Muthyala','Datafix','edw_core','tauto_driver','relationship_to_insured','Updated “relationship to insured” for AU100155682-03 in Metal and EDW','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8837/VI36893','Data Fixes: AU100046425-05 shows "date of loss is outside of policy coverage dates" in Snapsheet','Bug','2025-03-22','Bhaskar Muthyala','Datafix','edw_core','tpolicy','original_policy_effective_dt','Updated “original effective date” for AU100046425-05 in Metal and EDW','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8837/VI36893','Data Fixes: AU100046425-05 shows "date of loss is outside of policy coverage dates" in Snapsheet','Bug','2025-03-22','Bhaskar Muthyala','Datafix','edw_core','tquote','original_policy_effective_dt','Updated “original effective date” for AU100046425-05 in Metal and EDW','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8863/VI36974','Data Fixes: Fix inspection status for 18 policies','Bug','2025-03-22','Sandeep Gundreddy','Datafix','edw_stage','accountreport','DateOrdered','Updated “inspection status” for 18 policies in Metal','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8863/VI36974','Data Fixes: Fix inspection status for 18 policies','Bug','2025-03-22','Sandeep Gundreddy','Datafix','edw_stage','accountreport','DateTimeCompleted','Updated “inspection status” for 18 policies in Metal','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8863/VI36974','Data Fixes: Fix inspection status for 18 policies','Bug','2025-03-22','Sandeep Gundreddy','Datafix','edw_stage','accountreport','DateTimeRecieved','Updated “inspection status” for 18 policies in Metal','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8879/VI36784','Data Fixes: Add a standard IAT BOR alert to the accounts listed on the excel','Bug','2025-03-22','Architha Gudimalla','Datafix','edw_core','tnote','','Added alert notes on the list of accounts requested by user in Metal','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8890/VI37010','Data Fixes: InitialRatingTier Data Fix for an Endorsement Transaction on AU100124072-03','Bug','2025-03-22','Bhaskar Muthyala','Datafix','edw_stage','AccountTransactionVersionObjectField','','Updated “initial rating tier” for AU100124072-03 in Metal and EDW','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8928/VI37084','Data Fixes: Update completed time for LC360','Bug','2025-03-22','Architha Gudimalla','Datafix','edw_stage','accountreport','','Updated DateTimeRecieved for HO200037041 in Metal','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8516','EDW Integrations : Hubspot field additions','Enhancement','2025-03-22','Architha Gudimalla','Addition','edw_integration','broker_hubspot_feed','ytd_new_business_yacht_premium_amt','Created new column','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8516','EDW Integrations : Hubspot field additions','Enhancement','2025-03-22','Architha Gudimalla','Addition','edw_integration','quote_hubspot_feed','occupancy_type','Created new column','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8516','EDW Integrations : Hubspot field additions','Enhancement','2025-03-22','Architha Gudimalla','Addition','edw_integration','quote_hubspot_feed','new_client_for_agency_in','Created new column','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8516','EDW Integrations : Hubspot field additions','Enhancement','2025-03-22','Architha Gudimalla','Addition','edw_integration','quote_hubspot_feed','current_underlying_company_nm','Created new column','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8516','EDW Integrations : Hubspot field additions','Enhancement','2025-03-22','Architha Gudimalla','Addition','edw_integration','quote_note_hubspot_feed','note_user_nm','Created new column','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8786/VI37027','Data Fixes: CO100168218-03 - missing transaction 0 in prod','Bug','2025-03-22','Architha Gudimalla','Datafix','edw_core','tpolicy_history','','Inserted one transaction associated with CO100168218-03 in Metal and EDW','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8786/VI37027','Data Fixes: CO100168218-03 - missing transaction 0 in prod','Bug','2025-03-22','Architha Gudimalla','Datafix','edw_core','tpolicy_transaction','','Inserted one transaction associated with CO100168218-03 in Metal and EDW','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8786/VI37027','Data Fixes: CO100168218-03 - missing transaction 0 in prod','Bug','2025-03-22','Architha Gudimalla','Datafix','edw_core','tpolicy_insured','','Inserted one transaction associated with CO100168218-03 in Metal and EDW','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8786/VI37027','Data Fixes: CO100168218-03 - missing transaction 0 in prod','Bug','2025-03-22','Architha Gudimalla','Datafix','edw_core','tcollection_coverage','','Inserted one transaction associated with CO100168218-03 in Metal and EDW','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8786/VI37027','Data Fixes: CO100168218-03 - missing transaction 0 in prod','Bug','2025-03-22','Architha Gudimalla','Datafix','edw_core','tcollection_class_type','','Inserted one transaction associated with CO100168218-03 in Metal and EDW','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8786/VI37027','Data Fixes: CO100168218-03 - missing transaction 0 in prod','Bug','2025-03-22','Architha Gudimalla','Datafix','edw_core','tcollection_scheduled_item','','Inserted one transaction associated with CO100168218-03 in Metal and EDW','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8824','Data Standardization : Wind_or_hailstorm_deductible is coming as 0 instead of null','Bug','2025-03-22','Rushin Shah','Datafix','edw_core','thome_coverage','wind_or_hailstorm_deductible','','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI37011/VI37037/VI36198/VI36671','IVANS Policy Resent Request','Bug','2025-03-22','Rushin Shah','Datafix','edw_integration','policy_ivans_home_feed','','Resent a few home policies to IVANS','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI37011/VI37037/VI36198/VI36671','IVANS Policy Resent Request','Bug','2025-03-22','Rushin Shah','Datafix','edw_integration','policy_ivans_auto_feed','','Resent a few auto policies to IVANS','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI37011/VI37037/VI36198/VI36671','IVANS Policy Resent Request','Bug','2025-03-22','Rushin Shah','Datafix','edw_integration','policy_ivans_pel_feed','','Resent a few PEL policies to IVANS','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8568','EDW Integration : Created provisional policy and customer for Vault UW Litigation companies','Enhancement','2025-03-22','Yunus Mohammed','Addition','edw_core','tpolicy','','Created provisional record for 6 policies to support litigation claims in Snapsheet','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8568','EDW Integration : Created provisional policy and customer for Vault UW Litigation companies','Enhancement','2025-03-22','Yunus Mohammed','Addition','edw_core','tcustomer','','Created provisional record for 1 customer to support litigation claims in Snapsheet','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8880','EDW/Datamart Enhancements: Load ebao migrated stopped payments in Snapsheet','Enhancement','2025-03-22','Sandeep Gundreddy','Addition','edw_core','tclaim_transaction','','Updated stored procedure to load migrated stop payments in tclaim_transaction table','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8746','EDW/Datamart Enhancements: Populate missing item_sk in tclaim_feature table','Bug','2025-03-22','Yunus Mohammed','Datafix','edw_core','tclaim_feature','item_sk','Updated logic to populate missing item_sk in tclaim_feature table','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8568','EDW Process Enhancements: Validation to identify missing claim_coverage_desc, aslob_sk, item_sk, coverage_sk and vehicle_coverage_sk in tclaim_feature table','Enhancement','2025-03-22','Yunus Mohammed','Addition','edw_core','tvalidation_sql','','Added a new validation to identify missing claim_coverage_desc, aslob_sk, item_sk, coverage_sk and vehicle_coverage_sk in tclaim_feature table','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8902','EDW Process Enhancements: Validation to identify missing feature_status_sk in tclaim_transaction table','Enhancement','2025-03-22','Sandeep Gundreddy','Addition','edw_core','tvalidation_sql','','Added a new validation identify missing feature_status_sk in tclaim_transaction table','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD7981','EDW Process Enhancements: Create data quality check to validate loss incurred amounts between EDW and Snapsheet','Enhancement','2025-03-22','Yunus Mohammed','Addition','edw_core','treconciliation','','Added  daily data quality check to validate loss incurred amounts between EDW and Snapsheet','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8871/AD8825/VI35605','Workday enhancements: Update Annual Statement Line of Business from 090 to 091','Enhancement','2025-03-22','Rushin Shah','Modification','edw_core','tinternal_coverage','aslob_cd','Updated annual statement line of business from 090 to 091 for collections; 090 to 080 for marine boat yacht','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8876','Workday enhancements: Update claim_payment file to fetch payment_no in transaction_id','Bug','2025-03-22','Yunus Mohammed','Datafix','edw_integration','claim_workday_payment_feed','tranmsaction_id','Updated claim payment file to populate payment_no in column - transaction_id','30','Yes','2025-03-24',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8819','EDW/Datamart Enhancements: Addition of coverage codes to taslob table','Enhancement','2025-03-22','Rushin Shah','Addition','edw_core','taslob','','Added 5 coverage codes (Split Limits; Underinsured Motorist Liablity;  Excess Liability; Screen Enclosure; Water Damage limitation) to taslob table','30','Yes','2025-03-24',getdate(),getdate());