-- tedw_release_summary
INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 04/06/2025 :</span>
    <h4 style="margin-top: 0;font-style: italic;color: blue;">This release had 13 enhancements and 22 bug fix tickets.  Release details are as follows.</h4>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; }
        h1, h2 { color: #333; }
        ul { margin: 10px 0; padding-left: 20px; }
    </style>
</head>
<body>

    <h2 style="font-style: italic;">1. EDW/Datamart Enhancements</h2>

    <ul>
        <li><strong>Commercial EDW (Phase-1) Go-Live</strong>: Included the following foundational tables:
            <ul>
                <li>tcommercial_policy</li>
                <li>tcommercial_policy_history</li>
                <li>tcommercial_policy_transaction</li>
                <li>tcommercial_policy_coverage</li>
                <li>tcommercial_policy_tower</li>
                <li>tcommercial_policy_quota_share</li>
                <li>tcommercial_policy_subjectivity</li>
                <li>tcommercial_quote</li>
                <li>tcommercial_quote_history</li>
                <li>tcommercial_quote_transaction</li>
                <li>tcommercial_quote_coverage</li>
                <li>tcommercial_quote_tower</li>
                <li>tcommercial_quote_quota_share</li>
                <li>tcommercial_quote_subjectivity</li>
            </ul>
        </li>
        <li>Added column automatic_seismic_shutoff_valve_in to thome_additional_coverage and tquote_home_additional_coverage tables</li>
        <li>Updated vissterritory view to include ISS Auto and Home territories data</li>
        <li>Updated multiple stored procedures to:
            <ul>
                <li>Load missing aslob_sk for condo policies in tclaim_feature</li>
                <li>Populate missing payee_nm in tclaim_payment</li>
                <li>Populate loss_desc in tclaim, roof_deck_attachment in thome_coverage</li>
                <li>Populate missing underwriter_nm, producer_sk, producer_nm in tquote_history</li>
            </ul>
        </li>
        <li>Updated datatype to varchar(3000) for close_reason_desc in tquote table</li>
    </ul>

    <h2 style="font-style: italic;">2. EDW Process Enhancements</h2>
    <ul>
        <li>Automated daily data quality checks for invalid data in CLUE property feed</li>
        <li>Refined date filters in daily snapsheet reconciliation stored procedures</li>
        <li>ADF pipeline for AccountRaterReference changed to full load</li>
        <li>Enabled daily refresh of views via updated stored procedure logic</li>
        <li>Created new DAG for IVANS procedures, re-scheduled to avoid sunday maintenance</li>
        <li>Migrated Hubspot codebase to Azure Git Repository</li>
    </ul>

    <h2 style="font-style: italic;">3. EDW Integrations</h2>
    <h3>a. IVANS</h3>
    <ul>
        <li>Updated PEL feed logic to exclude deleted vehicles from PEL_Objects JSON</li>
        <li>Resent IVANS policies for tickets VI37154 and VI37014</li>
    </ul>

    <h3>b. Hubspot</h3>
    <ul>
        <li>Added new fields:
            <ul>
                <li>target_account</li>
                <li>close_reason_desc</li>
            </ul>
        </li>
        <li>Concatenated broker_id to broker names to differentiate brokers</li>
        <li>Fixed quote notes writeback process from Hubspot to Metal</li>
    </ul>

    <h2 style="font-style: italic;">4. Data Fixes</h2>
    <ul>
        <li>VI-37070: Updated item_sk for claims 25ATFL584939175 and 25ATMO773862395</li>
        <li>VI-36653: Updated item_sk for claim C23AUA00001</li>
        <li>VI-35404: Pulled missing loss date for HO100237433-02 from prior term</li>
        <li>VI-35938: Corrected garaging zip code for AU100013558-03 and AU100013558-04</li>
        <li>AD-8981: Restored missing lat/lng using prior term values</li>
        <li>VI-36991: Fixed PD, UMPD, and Medical Payments limits for NC Auto policies</li>
        <li>VI-36281: Inserted missing loss date records for policies/quotes</li>
        <li>VI-36640: Corrected premium amounts for HO10010204-04</li>
        <li>VI-37137: Updated billing account for HO100245360-07</li>
        <li>VI-37141: Updated relationship to insured for AU200026757 and AU100074386-04</li>
        <li>VI-37155: Updated initial rating tier for AU100244272-02</li>
        <li>VI-37220: Updated insured relationship for AU100037746-03</li>
        <li>AD-8971: Fixed ceded premium for policies with HSB coverage and incorrect values</li>
        <li>AD-8719: Removed duplicate records from <code>taslob</code> table</li>
        <li>VI-36862: Fixed cancel rewrite logic to capture missing limits</li>
        <li>VI-31071: Updated rating territory code for ~400 Home policy transactions</li>
        <li>VI-29960: Updated stored procedure logic to capture appropriate primary home companion credit</li>
        <li>AD-9000: Corrected loss amount for 25ATFL457137560 after payment cancellation error</li>
    </ul>
</body>
'
,'Yes'
,'2025-04-06'
,getdate()
,getdate()
)
;

-- tedw_release_note
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8951','EDW/Datamart Enhancements: Commercial EDW Phase 1 tables','Enhancement','2025-04-04','Sandeep Gundreddy','Addition','edw_core','tcommercial_policy','','Created new table','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8951','EDW/Datamart Enhancements: Commercial EDW Phase 1 tables','Enhancement','2025-04-04','Sandeep Gundreddy','Addition','edw_core','tcommercial_policy_history','','Created new table','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8951','EDW/Datamart Enhancements: Commercial EDW Phase 1 tables','Enhancement','2025-04-04','Sandeep Gundreddy','Addition','edw_core','tcommercial_policy_transaction','','Created new table','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8951','EDW/Datamart Enhancements: Commercial EDW Phase 1 tables','Enhancement','2025-04-04','Sandeep Gundreddy','Addition','edw_core','tcommercial_policy_coverage','','Created new table','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8951','EDW/Datamart Enhancements: Commercial EDW Phase 1 tables','Enhancement','2025-04-04','Sandeep Gundreddy','Addition','edw_core','tcommercial_policy_tower','','Created new table','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8951','EDW/Datamart Enhancements: Commercial EDW Phase 1 tables','Enhancement','2025-04-04','Sandeep Gundreddy','Addition','edw_core','tcommercial_policy_quota_share','','Created new table','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8951','EDW/Datamart Enhancements: Commercial EDW Phase 1 tables','Enhancement','2025-04-04','Sandeep Gundreddy','Addition','edw_core','tcommercial_policy_subjectivity','','Created new table','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8951','EDW/Datamart Enhancements: Commercial EDW Phase 1 tables','Enhancement','2025-04-04','Sandeep Gundreddy','Addition','edw_core','tcommercial_quote','','Created new table','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8951','EDW/Datamart Enhancements: Commercial EDW Phase 1 tables','Enhancement','2025-04-04','Sandeep Gundreddy','Addition','edw_core','tcommercial_quote_history','','Created new table','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8951','EDW/Datamart Enhancements: Commercial EDW Phase 1 tables','Enhancement','2025-04-04','Sandeep Gundreddy','Addition','edw_core','tcommercial_quote_transaction','','Created new table','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8951','EDW/Datamart Enhancements: Commercial EDW Phase 1 tables','Enhancement','2025-04-04','Sandeep Gundreddy','Addition','edw_core','tcommercial_quote_coverage','','Created new table','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8951','EDW/Datamart Enhancements: Commercial EDW Phase 1 tables','Enhancement','2025-04-04','Sandeep Gundreddy','Addition','edw_core','tcommercial_quote_tower','','Created new table','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8951','EDW/Datamart Enhancements: Commercial EDW Phase 1 tables','Enhancement','2025-04-04','Sandeep Gundreddy','Addition','edw_core','tcommercial_quote_quota_share','','Created new table','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8951','EDW/Datamart Enhancements: Commercial EDW Phase 1 tables','Enhancement','2025-04-04','Sandeep Gundreddy','Addition','edw_core','tcommercial_quote_subjectivity','','Created new table','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9032/VI37202','EDW/Datamart Enhancements: Added column - automatic_seismic_shutoff_valve_in in thome_additional_coverage and tquote_home_additional_coverage tables','Enhancement','2025-04-04','Bhaskar Muthyala','Addition','edw_core','thome_additional_coverage','automatic_seismic_shutoff_valve_in','Created new column','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9032/VI37202','EDW/Datamart Enhancements: Added column - automatic_seismic_shutoff_valve_in in thome_additional_coverage and tquote_home_additional_coverage tables','Enhancement','2025-04-04','Bhaskar Muthyala','Addition','edw_core','tquote_home_additional_coverage','automatic_seismic_shutoff_valve_in','Created new column','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8900','EDW/Datamart Enhancements: Updated a view - vissterritory to query ISS Auto and Home territories data ','Enhancement','2025-04-04','Bhaskar Muthyala','Modification','edw_core','vissterritory','','Updated existing view to query ISS Auto and Home territories data','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9030','EDW/Datamart Enhancements: Modify tquote/close_reason_desc data type to varchar(3000)','Enhancement','2025-04-04','Sandeep Gundreddy','Modification','edw_core','tquote','close_reason_desc','Updated datatype to varchar(3000)','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9039','EDW/Datamart Enhancements: Populate missing aslob_sk for condo policies in tclaim_feature table ','Bug','2025-04-04','Yunus Mohammed','Datafix','edw_core','tclaim_feature','aslob_sk','Updated logic to populate missing aslob_sk for condo policies in tclaim_feature table ','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9009','EDW/Datamart Enhancements: Populate missing missing payee_nm in tclaim_payment table','Bug','2025-04-04','Yunus Mohammed','Datafix','edw_core','tclaim_payment','payee_nm','Updated logic to populate missing payee_nm in tclaim_payment table','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9054','EDW/Datamart Enhancements: Populate missing missing underwriter_nm, producer_sk and producer_nm in tquote_history table','Bug','2025-04-04','Architha Gudimalla','Datafix','edw_core','tquote_history','underwriter_nm','Updated logic to populate missing underwriter_nm, producer_sk and producer_nm in tquote_history table','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9054','EDW/Datamart Enhancements: Populate missing missing underwriter_nm, producer_sk and producer_nm in tquote_history table','Bug','2025-04-04','Architha Gudimalla','Datafix','edw_core','tquote_history','producer_sk','Updated logic to populate missing underwriter_nm, producer_sk and producer_nm in tquote_history table','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9054','EDW/Datamart Enhancements: Populate missing missing underwriter_nm, producer_sk and producer_nm in tquote_history table','Bug','2025-04-04','Architha Gudimalla','Datafix','edw_core','tquote_history','producer_nm','Updated logic to populate missing underwriter_nm, producer_sk and producer_nm in tquote_history table','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8747','EDW/Datamart Enhancements: Populate fact of loss details in tclaim.loss_desc field','Enhancement','2025-04-04','Yunus Mohammed','Modification','edw_core','tclaim','loss_desc','Updated logic to populate fact of loss details in tclaim.loss_desc field','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8969','EDW Process Enhancements: Validation to monitor invalid data in CLUE Property  feed','Enhancement','2025-04-04','Sandeep Gundreddy','Addition','edw_core','tvalidation_sql','','Added a new validation to monitor invalid data in CLUE Property  feed','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8902','EDW Process Enhancements: Updated date filter in the stored procedure logic which reconciles daily snapsheet vs EDW data','Enhancement','2025-04-04','Sandeep Gundreddy','Addition','edw_core','treconciliation','','Updated date filter in the stored procedure logic which reconciles daily snapsheet vs EDW data','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8992','EDW Process Enhancements: Updated ADF pipeline for AccountRaterReference table load method to full load','Enhancement','2025-04-04','Hernando Garcia','Modification','edw_stage','AccountRaterReference','','Updated ADF pipeline','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8972','EDW Process Enhancements : Updated stored procedure logic to automatically refresh views daily','Enhancement','2025-04-04','Hernando Garcia','Modification','edw_core','sp_refresh_views','','Updated stored procedure logic to add 7 new views for daily refresh','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8955','EDW Process Enhancements: Created a new DAG to separately call IVANS stored procedures and modified job schedule to avoid Ivans maintenance window on Sunday','Enhancement','2025-04-04','Alberto Valbuena','Modification','edw_stage','','','Created a new DAG','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI37154/VI37014','IVANS Policy Resent Request','Bug','2025-04-04','Rushin Shah','Datafix','edw_integration','policy_ivans_home_feed','','Resent a few home policies to IVANS','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI37154/VI37014','IVANS Policy Resent Request','Bug','2025-04-04','Rushin Shah','Datafix','edw_integration','policy_ivans_auto_feed','','Resent a few auto policies to IVANS','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI37154/VI37014','IVANS Policy Resent Request','Bug','2025-04-04','Rushin Shah','Datafix','edw_integration','policy_ivans_pel_feed','','Resent a few PEL policies to IVANS','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8826/VI36873','IVANS Feed : Updated IVANS PEL feed logic to remove deleted vehicles from PEL_Objects JSON field','Bug','2025-04-04','Alberto Valbuena','Modification','edw_integration','policy_ivans_pel_feed','PEL_Objects','Updated stored procedure logic to remove deleted vehicles from PEL_Objects JSON field','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8898/AD8907/VI367790/VI36066','EDW Integrations : Hubspot field additions','Enhancement','2025-04-04','Architha Gudimalla','Addition','edw_integration','quote_hubspot_feed','target_account','Created new column','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8898/AD8907/VI367790/VI36066','EDW Integrations : Hubspot field additions','Enhancement','2025-04-04','Architha Gudimalla','Addition','edw_integration','quote_hubspot_feed','close_reason_desc','Created new column','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9023/VI36791','EDW Integrations : Concatenated broker_id to the end of broker name to distinctly identify the brokers','Enhancement','2025-04-04','Architha Gudimalla','Modification','edw_integration','broker_hubspot_feed','broker_nm','Modified existing column','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9023/VI36791','EDW Integrations : Concatenated broker_id to the end of broker name to distinctly identify the brokers','Enhancement','2025-04-04','Architha Gudimalla','Modification','edw_integration','quote_hubspot_feed','broker_nm','Modified existing column','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8980/AD8982/VI37070/VI36653','Data Fixes: Updated missing item_sk for 25ATFL584939175, 25ATMO773862395, C23AUA00001','Bug','2025-04-04','Bhaskar Muthyala','Datafix','edw_core','tclaim_feature','item_sk','Updated item_sk for 25ATFL584939175, 25ATMO773862395, C23AUA00001 in EDW','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8997/AD9048/VI37141/VI37220','Data Fixes: AU200026757 and AU100074386-04 need data fix for Relationship To Insured','Bug','2025-04-04','Bhaskar Muthyala','Datafix','edw_core','tquote_auto_driver','relationship_to_insured','Updated relationship to insured for AU200026757 and AU100074386-04 in Metal and EDW','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8997/AD9048/VI37141/VI37220','Data Fixes: AU200026757 and AU100074386-04 need data fix for Relationship To Insured','Bug','2025-04-04','Bhaskar Muthyala','Datafix','edw_core','tauto_driver','relationship_to_insured','Updated relationship to insured for AU200026757 and AU100074386-04 in Metal and EDW','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9013/VI37155','Data Fixes: InitialRatingTier Data Fix for AU100244272-02','Bug','2025-04-04','Bhaskar Muthyala','Datafix','edw_stage','AccountTransactionVersionObjectField','','Updated initial rating tier for AU100244272-02 in Metal and EDW','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8719','Data Fixes: Deleted duplicate records from taslob table','Bug','2025-04-04','Bhaskar Muthyala','Datafix','edw_core','taslob','','Deleted duplicate records from EDW','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8995/VI36938','Data Fixes: AU100013558-03 and AU100013558-04 need data fix to garaging zip code','Bug','2025-04-04','Rushin Shah','Datafix','edw_stage','tauto_garage_location','garage_address_zip_code','Updated garage address zip code for AU100013558-03 and AU100013558-04 in Metal and EDW','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8995/VI36938','Data Fixes: AU100013558-03 and AU100013558-04 need data fix to garaging zip code','Bug','2025-04-04','Rushin Shah','Datafix','edw_stage','tauto_garage_location','garage_address_zip_code','Updated garage address zip code for AU100013558-03 and AU100013558-04 in Metal and EDW','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8974/VI31071','Data Fixes: Updated rating territory code for ~400 Home policy transactions','Bug','2025-04-04','Rushin Shah','Datafix','edw_core','thome_coverage','rating_territory_cd','Updated rating territory code for ~400 Home policy transactions','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9000','Data Fixes: Updated loss amounts for claim 25ATFL457137560 to correct issue caused by adjuster cancelling a approved payment transaction','Bug','2025-04-04','Sandeep Gundreddy','Datafix','edw_core','tclaim_transaction','','Updated loss amounts for one claim in EDW','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8971','Data Fixes: Updated ceded premium for policies where HSB coverages exists but ceded premium is 0 or negative','Bug','2025-04-04','Tuba Mohsin','Datafix','edw_core','tpolicy_transaction','ceded_premium_amt','Updated ceded premium amounts for 5 policies in Metal and EDW','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8994/VI37137','Data Fixes: Updated billing account for HO100245360-07','Bug','2025-04-04','Sandeep Gundreddy','Datafix','edw_core','tpolicy','billingaccount_sk','Updated billing account for one policy HO100245360-07 in Metal and EDW.  This is just a one time update.','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8958/VI36640','Data Fixes: Updated premium amounts associated with HO10010204-04','Bug','2025-04-04','Bhaskar Muthyala','Datafix','edw_stage','AccountTransaction','','Updated all delta amount columns value to $0','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8958/VI36640','Data Fixes: Updated premium amounts associated with HO10010204-04','Bug','2025-04-04','Bhaskar Muthyala','Datafix','edw_stage','AccountTransactionCoveragePremium','','Updated all delta amount columns value to $0','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8958/VI36640','Data Fixes: Updated premium amounts associated with HO10010204-04','Bug','2025-04-04','Bhaskar Muthyala','Datafix','edw_stage','AccountTransactionTaxAndFee','','Updated all delta amount columns value to $0','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8981','Data Fixes: Updated latitude and longitude for policies having NULL values using prior term values','Bug','2025-04-04','Tuba Mohsin','Datafix','edw_core','tcollection_location','latitude','One time datafix was done to update latitude in Metal and EDW','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8981','Data Fixes: Updated latitude and longitude for policies having NULL values using prior term values','Bug','2025-04-04','Tuba Mohsin','Datafix','edw_core','tcollection_location','longitude','One time datafix was done to update longitude in Metal and EDW','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI36862','Data Fixes: Updated stored procedure logic to capture missing limits on cancel rewrites collections policies','Bug','2025-04-04','Architha Gudimalla','Datafix','edw_core','tcollection_class_type','','Updated stored procedure logic to capture missing limits on cancel rewrites collections policies','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29960','Data Fixes : Updated stored procedure logic to capture appropriate primary home companion credit','Bug','2025-04-04','Rushin Shah','Datafix','edw_core','tpolicy_history','home_policy_credit_in','Updated stored procedure logic to capture appropriate primary home companion credit','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI29960','Data Fixes : Updated stored procedure logic to capture appropriate primary home companion credit','Bug','2025-04-04','Rushin Shah','Datafix','edw_core','tquote_history','home_policy_credit_in','Updated stored procedure logic to capture appropriate primary home companion credit','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8952/VI36991','Data Fixes: Updated PD, UMPD and Medical Payments limit on a few NC Auto policies','Bug','2025-04-04','Architha Gudimalla','Datafix','edw_core','tauto_policy_coverage','property_damage_limit_amt','One time datafix was done to update latitude in Metal and EDW','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8952/VI36991','Data Fixes: Updated PD, UMPD and Medical Payments limit on a few NC Auto policies','Bug','2025-04-04','Architha Gudimalla','Datafix','edw_core','tauto_policy_coverage','medical_payment_limit_amt','One time datafix was done to update latitude in Metal and EDW','31','Yes','2025-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8952/VI36991','Data Fixes: Updated PD, UMPD and Medical Payments limit on a few NC Auto policies','Bug','2025-04-04','Architha Gudimalla','Datafix','edw_core','tauto_policy_coverage','um_pd_policy_limit_amt','One time datafix was done to update latitude in Metal and EDW','31','Yes','2025-04-06',getdate(),getdate());