-- tedw_release_summary
INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 04/21/2025 :</span>
    <h4 style="margin-top: 0;font-style: italic;color: blue;">This release had 5 enhancements and 20 bug fix tickets.  Release details are as follows.</h4>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; }
        h1, h2 { color: #333; }
        ul { margin: 10px 0; padding-left: 20px; }
    </style>
</head>
<body>

    <h2 style="font-style: italic;">1. EDW/Datamart Enhancements</h2>
    <ul>
        <li>Added the following premium mod columns in tauto_vehicle_coverage and tquote_auto_vehicle_coverage tables:
            <ul>
                <li>added_first_party_premium_adjustment_amount</li>
                <li>added_first_party_premium_adjustment_method</li>
                <li>added_first_party_premium_adjustment_reason</li>
                <li>added_first_party_premium_adjustment_retention</li>
                <li>added_personal_injury_protection_premium_adjustment_amount</li>
                <li>added_personal_injury_protection_premium_adjustment_method</li>
                <li>added_personal_injury_protection_premium_adjustment_reason</li>
                <li>added_personal_injury_protection_premium_adjustment_retention</li>
                <li>basic_first_party_premium_adjustment_amount</li>
                <li>basic_first_party_premium_adjustment_method</li>
                <li>basic_first_party_premium_adjustment_reason</li>
                <li>basic_first_party_premium_adjustment_retention</li>
                <li>customized_premium_adjustment_amount</li>
                <li>customized_premium_adjustment_method</li>
                <li>customized_premium_adjustment_reason</li>
                <li>customized_premium_adjustment_retention</li>
                <li>fire_premium_adjustment_amount</li>
                <li>fire_premium_adjustment_method</li>
                <li>fire_premium_adjustment_reason</li>
                <li>fire_premium_adjustment_retention</li>
                <li>property_protection_insurance_premium_adjustment_amount</li>
                <li>property_protection_insurance_premium_adjustment_method</li>
                <li>property_protection_insurance_premium_adjustment_reason</li>
                <li>property_protection_insurance_premium_adjustment_retention</li>
                <li>theft_premium_adjustment_amount</li>
                <li>theft_premium_adjustment_method</li>
                <li>theft_premium_adjustment_reason</li>
                <li>theft_premium_adjustment_retention</li>
                <li>uninsured_bodily_injury_premium_adjustment_amount</li>
                <li>uninsured_bodily_injury_premium_adjustment_method</li>
                <li>uninsured_bodily_injury_premium_adjustment_reason</li>
                <li>uninsured_bodily_injury_premium_adjustment_retention</li>
                <li>uninsured_motorist_premium_adjustment_amount</li>
                <li>uninsured_motorist_premium_adjustment_method</li>
                <li>uninsured_motorist_premium_adjustment_reason</li>
                <li>uninsured_motorist_premium_adjustment_retention</li>
                <li>uninsured_property_damage_premium_adjustment_amount</li>
                <li>uninsured_property_damage_premium_adjustment_method</li>
                <li>uninsured_property_damage_premium_adjustment_reason</li>
                <li>uninsured_property_damage_premium_adjustment_retention</li>
            </ul>
        </li>
        <li>Updated stored procedure logic to populate missing premium mods (blanket_premium_adjustment_method, blanket_premium_adjustment_factor, blanket_premium_adjustment_retention, blanket_premium_adjustment_retention_reason, scheduled_premium_adjustment_method, scheduled_premium_adjustment_factor, scheduled_premium_adjustment_retention, scheduled_premium_adjustment_retention_reason) in tcollection_class_type and tquote_collection_class_type tables  for home/condo policies which had collections coverage</li>
        <li>Updated stored procedure logic to populate missing premium mods (premium_adjustment_method, premium_adjustment_factor, premium_adjustment_retention, premium_adjustment_retention_reason) in thome_coverage and tquote_home_coverage tables</li>
        <li>Updated stored procedure logic to load missing payment_approver_nm and payment_approver_dt in tclaim_payment table</li>
        <li>Updated stored procedure logic to accurately assign claim feature status in tclaim_transaction table</li>
        <li>Updated the stored procedure logic to align the roof deck attachment value with the Metal display value in both in thome_coverage and tquote_home_coverage tables</li>
        <li>Updated the stored procedure logic to align the AdditionalPIP, BasicPIP, BILimit, DeductibleAppliesTo, UIMLimit, UMLimit, UMBIPolicyLimit and WorkLossExclusion value in both tauto_policy_coverage and tquote_auto_policy_coverage tables</li>
        <li>Updated stored procedure logic to populate certain fields (policy_effective_dt, policy_sk, product_sk, underwriting_company_nm, broker_id, customer_id) associated with litigation claims in tclaim table</li>
    </ul>

    <h2 style="font-style: italic;">2. EDW Process Enhancements</h2>
    <ul>
        <li>Updated stored procedure logic to support long labels for LC360 vendor report</li>
    </ul>

    <h2 style="font-style: italic;">3. EDW Integrations</h2>

    <h3>a. Workday Enhancements</h3>
    <ul>
        <li>Updated claim payment, reserves, and reserves ITD file to remove entries for litigation claims</li>
    </ul>

    <h3>b. Ivans</h3>
    <ul>
        <li>VI-37323/VI-36873/VI-37337/VI-37336: Resent IVANS policies</li>
    </ul>

    <h3>c. Hubspot</h3>
    <ul>
        <li>VI-36789: Fixed quote notes to remove special character that we get from Metal before displaying it in Hubspot</li>
    </ul>

    <h2>4. Data Fixes</h2>
    <ul>
        <li>VI-34518: Updated missing construction type for 16 records in Metal and EDW by pulling it from prior term</li>
        <li>VI-35404: Updated missing loss date in Metal using loss date from prior policy / CLUE data</li>
        <li>VI-34053: Updated incorrect address line 1 associated with 11 policies in Metal and EDW</li>
        <li>VI-37356: Updated status to quoted; policy number was assigned to the original submission, and a commercial submission created in error was closed</li>
        <li>VI-37355: Updated BCEG Credit percent for HO200036580, HO100245003-06, HO200033170 in Metal and EDW</li>
        <li>VI-34699: Updated garaging zip code associated with AU100031429 in Metal and EDW</li>
        <li>AD9210: Updated claim C24AUA00804 and C24AUA01026 to correct the total loss incurred, which was impacted by adjuster’s cancellation of an approved payment transaction</li>
    </ul>
</body>
'
,'Yes'
,'2025-04-21'
,getdate()
,getdate()
)
;

-- tedw_release_note
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tauto_vehicle_coverage','added_first_party_premium_adjustment_amount','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tauto_vehicle_coverage','added_first_party_premium_adjustment_method','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tauto_vehicle_coverage','added_first_party_premium_adjustment_reason','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tauto_vehicle_coverage','added_first_party_premium_adjustment_retention','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tauto_vehicle_coverage','added_personal_injury_protection_premium_adjustment_amount','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tauto_vehicle_coverage','added_personal_injury_protection_premium_adjustment_method','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tauto_vehicle_coverage','added_personal_injury_protection_premium_adjustment_reason','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tauto_vehicle_coverage','added_personal_injury_protection_premium_adjustment_retention','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tauto_vehicle_coverage','basic_first_party_premium_adjustment_amount','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tauto_vehicle_coverage','basic_first_party_premium_adjustment_method','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tauto_vehicle_coverage','basic_first_party_premium_adjustment_reason','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tauto_vehicle_coverage','basic_first_party_premium_adjustment_retention','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tauto_vehicle_coverage','customized_premium_adjustment_amount','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tauto_vehicle_coverage','customized_premium_adjustment_method','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tauto_vehicle_coverage','customized_premium_adjustment_reason','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tauto_vehicle_coverage','customized_premium_adjustment_retention','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tauto_vehicle_coverage','fire_premium_adjustment_amount','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tauto_vehicle_coverage','fire_premium_adjustment_method','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tauto_vehicle_coverage','fire_premium_adjustment_reason','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tauto_vehicle_coverage','fire_premium_adjustment_retention','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tauto_vehicle_coverage','property_protection_insurance_premium_adjustment_amount','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tauto_vehicle_coverage','property_protection_insurance_premium_adjustment_method','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tauto_vehicle_coverage','property_protection_insurance_premium_adjustment_reason','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tauto_vehicle_coverage','property_protection_insurance_premium_adjustment_retention','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tauto_vehicle_coverage','theft_premium_adjustment_amount','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tauto_vehicle_coverage','theft_premium_adjustment_method','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tauto_vehicle_coverage','theft_premium_adjustment_reason','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tauto_vehicle_coverage','theft_premium_adjustment_retention','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tauto_vehicle_coverage','uninsured_bodily_injury_premium_adjustment_amount','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tauto_vehicle_coverage','uninsured_bodily_injury_premium_adjustment_method','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tauto_vehicle_coverage','uninsured_bodily_injury_premium_adjustment_reason','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tauto_vehicle_coverage','uninsured_bodily_injury_premium_adjustment_retention','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tauto_vehicle_coverage','uninsured_motorist_premium_adjustment_amount','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tauto_vehicle_coverage','uninsured_motorist_premium_adjustment_method','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tauto_vehicle_coverage','uninsured_motorist_premium_adjustment_reason','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tauto_vehicle_coverage','uninsured_motorist_premium_adjustment_retention','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tauto_vehicle_coverage','uninsured_property_damage_premium_adjustment_amount','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tauto_vehicle_coverage','uninsured_property_damage_premium_adjustment_method','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tauto_vehicle_coverage','uninsured_property_damage_premium_adjustment_reason','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tauto_vehicle_coverage','uninsured_property_damage_premium_adjustment_retention','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tquote_auto_vehicle_coverage','added_first_party_premium_adjustment_amount','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tquote_auto_vehicle_coverage','added_first_party_premium_adjustment_method','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tquote_auto_vehicle_coverage','added_first_party_premium_adjustment_reason','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tquote_auto_vehicle_coverage','added_first_party_premium_adjustment_retention','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tquote_auto_vehicle_coverage','added_personal_injury_protection_premium_adjustment_amount','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tquote_auto_vehicle_coverage','added_personal_injury_protection_premium_adjustment_method','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tquote_auto_vehicle_coverage','added_personal_injury_protection_premium_adjustment_reason','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tquote_auto_vehicle_coverage','added_personal_injury_protection_premium_adjustment_retention','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tquote_auto_vehicle_coverage','basic_first_party_premium_adjustment_amount','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tquote_auto_vehicle_coverage','basic_first_party_premium_adjustment_method','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tquote_auto_vehicle_coverage','basic_first_party_premium_adjustment_reason','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tquote_auto_vehicle_coverage','basic_first_party_premium_adjustment_retention','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tquote_auto_vehicle_coverage','customized_premium_adjustment_amount','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tquote_auto_vehicle_coverage','customized_premium_adjustment_method','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tquote_auto_vehicle_coverage','customized_premium_adjustment_reason','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tquote_auto_vehicle_coverage','customized_premium_adjustment_retention','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tquote_auto_vehicle_coverage','fire_premium_adjustment_amount','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tquote_auto_vehicle_coverage','fire_premium_adjustment_method','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tquote_auto_vehicle_coverage','fire_premium_adjustment_reason','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tquote_auto_vehicle_coverage','fire_premium_adjustment_retention','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tquote_auto_vehicle_coverage','property_protection_insurance_premium_adjustment_amount','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tquote_auto_vehicle_coverage','property_protection_insurance_premium_adjustment_method','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tquote_auto_vehicle_coverage','property_protection_insurance_premium_adjustment_reason','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tquote_auto_vehicle_coverage','property_protection_insurance_premium_adjustment_retention','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tquote_auto_vehicle_coverage','theft_premium_adjustment_amount','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tquote_auto_vehicle_coverage','theft_premium_adjustment_method','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tquote_auto_vehicle_coverage','theft_premium_adjustment_reason','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tquote_auto_vehicle_coverage','theft_premium_adjustment_retention','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tquote_auto_vehicle_coverage','uninsured_bodily_injury_premium_adjustment_amount','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tquote_auto_vehicle_coverage','uninsured_bodily_injury_premium_adjustment_method','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tquote_auto_vehicle_coverage','uninsured_bodily_injury_premium_adjustment_reason','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tquote_auto_vehicle_coverage','uninsured_bodily_injury_premium_adjustment_retention','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tquote_auto_vehicle_coverage','uninsured_motorist_premium_adjustment_amount','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tquote_auto_vehicle_coverage','uninsured_motorist_premium_adjustment_method','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tquote_auto_vehicle_coverage','uninsured_motorist_premium_adjustment_reason','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tquote_auto_vehicle_coverage','uninsured_motorist_premium_adjustment_retention','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tquote_auto_vehicle_coverage','uninsured_property_damage_premium_adjustment_amount','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tquote_auto_vehicle_coverage','uninsured_property_damage_premium_adjustment_method','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tquote_auto_vehicle_coverage','uninsured_property_damage_premium_adjustment_reason','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9130','EDW/Datamart Enhancements: Added Premium Modifications Columns for Auto Product','Enhancement','2025-04-18','Bhaskar Muthyala','Addition','edw_core','tquote_auto_vehicle_coverage','uninsured_property_damage_premium_adjustment_retention','Created new column','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9121/VI37241','EDW/Datamart Enhancements: Updated stored procedure logic to populate missing premium mods in thome_coverage and tquote_home_coverage tables','Bug','2025-04-18','Yunus Mohammed','Datafix','edw_core','thome_coverage','','Updated logic to populate missing premium mods in thome_coverage table ','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9121/VI37241','EDW/Datamart Enhancements: Updated stored procedure logic to populate missing premium mods in thome_coverage and tquote_home_coverage tables','Bug','2025-04-18','Yunus Mohammed','Datafix','edw_core','tquote_home_coverage','','Updated logic to populate missing premium mods in tquote_home_coverage table ','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9140','EDW/Datamart Enhancements: Updated stored procedure logic to populate missing premium mods in tcollection_class_type and tquote_collection_class_type tables','Bug','2025-04-18','Yunus Mohammed','Datafix','edw_core','tcollection_class_type','','Updated logic to populate missing premium mods in tcollection_class_type table ','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9140','EDW/Datamart Enhancements: Updated stored procedure logic to populate missing premium mods in tcollection_class_type and tquote_collection_class_type tables','Bug','2025-04-18','Yunus Mohammed','Datafix','edw_core','tquote_collection_class_type','','Updated logic to populate missing premium mods in tquote_collection_class_type table ','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9044','EDW/Datamart Enhancements: Updated stored procedure logic to populate missing payment_approver_nm and payment_approver_dt in tclaim_payment table','Bug','2025-04-18','Yunus Mohammed','Datafix','edw_core','tclaim_payment','payment_approver_nm','Updated logic to populate missing payment_approver_nm in tclaim_payment table','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9044','EDW/Datamart Enhancements: Updated stored procedure logic to populate missing payment_approver_nm and payment_approver_dt in tclaim_payment table','Bug','2025-04-18','Yunus Mohammed','Datafix','edw_core','tclaim_payment','payment_approver_dt','Updated logic to populate missing payment_approver_dt in tclaim_payment table','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9163','EDW/Datamart Enhancements: Updated stored procedure logic to accurately assign claim feature status in tclaim_transaction table','Bug','2025-04-18','Yunus Mohammed','Datafix','edw_core','tclaim_transaction','feature_status_sk','Updated logic to accurately assign claim feature status in tclaim_transaction table','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8973/VI37110','EDW/Datamart Enhancements: Updated stored procedure logic to populate roof deck attachment value to match Metal display value in thome_coverage and tquote_home_coverage tables','Bug','2025-04-18','Rushin Shah','Datafix','edw_core','thome_coverage','roof_deck_attachment','Updated logic to populate roof deck attachment in thome_coverage table','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8973/VI37110','EDW/Datamart Enhancements: Updated stored procedure logic to populate roof deck attachment value to match Metal display value in thome_coverage and tquote_home_coverage tables','Bug','2025-04-18','Rushin Shah','Datafix','edw_core','tquote_home_coverage','roof_deck_attachment','Updated logic to populate roof deck attachment in tquote_home_coverage table','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9109','EDW/Datamart Enhancements: Updated stored procedure logic to populate certain fields associated with litigation claims in tclaim table','Bug','2025-04-18','Yunus Mohammed','Datafix','edw_core','tclaim','policy_effective_dt','Updated logic to populate missing policy_effective_dt associated with litigation claims','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9109','EDW/Datamart Enhancements: Updated stored procedure logic to populate certain fields associated with litigation claims in tclaim table','Bug','2025-04-18','Yunus Mohammed','Datafix','edw_core','tclaim','policy_sk','Updated logic to populate missing policy_sk associated with litigation claims','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9109','EDW/Datamart Enhancements: Updated stored procedure logic to populate certain fields associated with litigation claims in tclaim table','Bug','2025-04-18','Yunus Mohammed','Datafix','edw_core','tclaim','product_sk','Updated logic to populate missing product_sk associated with litigation claims','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9109','EDW/Datamart Enhancements: Updated stored procedure logic to populate certain fields associated with litigation claims in tclaim table','Bug','2025-04-18','Yunus Mohammed','Datafix','edw_core','tclaim','underwriting_company_nm','Updated logic to populate missing underwriting_company_nm associated with litigation claims','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9109','EDW/Datamart Enhancements: Updated stored procedure logic to populate certain fields associated with litigation claims in tclaim table','Bug','2025-04-18','Yunus Mohammed','Datafix','edw_core','tclaim','broker_id','Updated logic to populate missing broker_id associated with litigation claims','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9109','EDW/Datamart Enhancements: Updated stored procedure logic to populate certain fields associated with litigation claims in tclaim table','Bug','2025-04-18','Yunus Mohammed','Datafix','edw_core','tclaim','customer_id','Updated logic to populate missing customer_id associated with litigation claims','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9171','EDW Process Enhancements: Updated stored procedure logic to handle long label for LC360 vendor report','Enhancement','2025-04-18','Architha Gudimalla','Modification','edw_stage','tvendor_report_field','label','Updated one record','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI37323/VI36873/VI37337/VI37336','IVANS Policy Resent Request','Bug','2025-04-18','Rushin Shah','Datafix','edw_integration','policy_ivans_home_feed','','Resent a few home policies to IVANS','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI37323/VI36873/VI37337/VI37336','IVANS Policy Resent Request','Bug','2025-04-18','Rushin Shah','Datafix','edw_integration','policy_ivans_auto_feed','','Resent a few auto policies to IVANS','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI37323/VI36873/VI37337/VI37336','IVANS Policy Resent Request','Bug','2025-04-18','Rushin Shah','Datafix','edw_integration','policy_ivans_pel_feed','','Resent a few PEL policies to IVANS','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9117','Workday enhancements: Updated claim payment, claim reserves and claim reserves inception to date (ITD) file to remove payment/reserves associated with litigation claims','Enhancement','2025-04-18','Yunus Mohammed','Modification','edw_integration','claim_workday_payment_feed','','Updated stored procedure logic to remove litigation claim details','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9117','Workday enhancements: Updated claim payment, claim reserves and claim reserves inception to date (ITD) file to remove payment/reserves associated with litigation claims','Enhancement','2025-04-18','Yunus Mohammed','Modification','edw_integration','claim_workday_reserve_feed','','Updated stored procedure logic to remove litigation claim details','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9117','Workday enhancements: Updated claim payment, claim reserves and claim reserves inception to date (ITD) file to remove payment/reserves associated with litigation claims','Enhancement','2025-04-18','Yunus Mohammed','Modification','edw_integration','claim_workday_itd_reserve_feed','','Updated stored procedure logic to remove litigation claim details','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9157/VI34699','Data Fixes: AU100031429 need data fix to garaging zip code and county name','Bug','2025-04-18','Rushin Shah','Datafix','edw_core','tauto_garage_location','garage_address_zip_code','Updated garage address zip code for AU100031429 in Metal and EDW','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9157/VI34699','Data Fixes: AU100031429 need data fix to garaging zip code and county name','Bug','2025-04-18','Rushin Shah','Datafix','edw_core','tqoute_auto_garage_location','garage_address_zip_code','Updated garage address zip code for AU100031429 in Metal and EDW','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9157/VI34699','Data Fixes: AU100031429 need data fix to garaging zip code and county name','Bug','2025-04-18','Rushin Shah','Datafix','edw_core','tauto_garage_location','garage_address_county_nm','Updated garage address county name for AU100031429 in Metal and EDW','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9157/VI34699','Data Fixes: AU100031429 need data fix to garaging zip code and county name','Bug','2025-04-18','Rushin Shah','Datafix','edw_core','tqoute_auto_garage_location','garage_address_county_nm','Updated garage address county name for AU100031429 in Metal and EDW','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9170/AD9210','Data Fixes: Updated total loss incurred amount for C24AUA00804 and C24AUA01026','Bug','2025-04-18','Rushin Shah','Datafix','edw_core','tclaim_transaction','','Deleted one claim transaction to update total loss incurred amount','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9085/VI34053','Data Fixes: Updated address line 1 for 11 policies','Bug','2025-04-18','Tuba Mohsin','Datafix','edw_core','tpolicy','mailing_address_line1','Updated address line 1 for 11 policies in Metal and EDW','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9085/VI34053','Data Fixes: Updated address line 1 for 11 policies','Bug','2025-04-18','Tuba Mohsin','Datafix','edw_core','thome_location','address_line1','Updated address line 1 for 11 policies in Metal and EDW','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9085/VI34053','Data Fixes: Updated address line 1 for 11 policies','Bug','2025-04-18','Tuba Mohsin','Datafix','edw_core','tpel_location','address_line1','Updated address line 1 for 11 policies in Metal and EDW','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8847/VI34518','Data Fixes: Updated construction type for 16 records','Bug','2025-04-18','Tuba Mohsin','Datafix','edw_core','thome_coverage','construction_type','Updated construction type for 16 records in Metal and EDW','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8847/VI34518','Data Fixes: Updated construction type for 16 records','Bug','2025-04-18','Tuba Mohsin','Datafix','edw_core','tquote_home_covergage','construction_type','Updated construction type for 16 records in Metal and EDW','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8193/VI35404','Data Fixes: Updated missing loss date using loss date from prior policy / CLUE data','Bug','2025-04-18','Architha Gudimalla','Datafix','edw_core','tloss_history','loss_dt','Updated missing loss date in Metal and EDW','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8193/VI35404','Data Fixes: Updated missing loss date in Metal using loss date from prior policy / CLUE data','Bug','2025-04-18','Architha Gudimalla','Datafix','edw_core','tquote_loss_history','loss_dt','Updated missing loss date in Metal and EDW','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9173/VI67355/VI37415/VI37431','Data Fixes: Updated BCEGCreditPercent for HO200036580, HO100245003-06, HO200033170','Bug','2025-04-18','Tuba Mohsin','Datafix','edw_core','thome_coverage','bceg_credit_pc','Updated BCEG Credit Percent for 3 policies in Metal and EDW','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9173/VI67355/VI37415/VI37431','Data Fixes: Updated BCEGCreditPercent for HO200036580, HO100245003-06, HO200033170','Bug','2025-04-18','Tuba Mohsin','Datafix','edw_core','tquote_home_coverage','bceg_credit_pc','Updated BCEG Credit Percent for 3 policies in Metal and EDW','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9195/VI37356','Data Fixes: Updated commercial submission created in error','Bug','2025-04-18','Bhaskar Muthyala','Datafix','edw_stage','Account','','Updated status to “quoted”; policy number was assigned to the original submission','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9195/VI37356','Data Fixes: Updated commercial submission created in error','Bug','2025-04-18','Bhaskar Muthyala','Datafix','edw_stage','AccountTransaction','','Updated status to “quoted”; policy number was assigned to the original submission','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9195/VI37356','Data Fixes: Updated commercial submission created in error','Bug','2025-04-18','Bhaskar Muthyala','Datafix','edw_stage','AccountTransactionVersion','','Updated status to “quoted”; policy number was assigned to the original submission','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9049/VI36789','EDW Integrations: Fixed hubspot quote notes to remove special character that we get from Metal before displaying it in Hubspot','Enhancement','2025-04-18','Hernando Garcia','Modification','edw_integration','quote_note_hubspot_feed','note_desc','Updated note_desc to remove special characters','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9089','EDW/Datamart Enhancements: Updated stored procedure logic to populate AdditionalPIP value to match Metal display value in tauto_policy_coverage and tquote_auto_policy_coverage tables','Enhancement','2025-04-18','Architha Gudimalla','Modification','edw_core','tauto_policy_coverage','additional_pip','Updated logic to populate additional pip in tauto_policy_coverage table','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9089','EDW/Datamart Enhancements: Updated stored procedure logic to populate AdditionalPIP value to match Metal display value in tauto_policy_coverage and tquote_auto_policy_coverage tables','Enhancement','2025-04-18','Architha Gudimalla','Modification','edw_core','tquote_auto_policy_coverage','additional_pip','Updated logic to populate additional pip in tquote_auto_policy_coverage table','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9089','EDW/Datamart Enhancements: Updated stored procedure logic to populate BasicPIP value to match Metal display value in tauto_policy_coverage and tquote_auto_policy_coverage tables','Enhancement','2025-04-18','Architha Gudimalla','Modification','edw_core','tauto_policy_coverage','basic_pip','Updated logic to populate basic pip in tauto_policy_coverage table','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9089','EDW/Datamart Enhancements: Updated stored procedure logic to populate BasicPIP value to match Metal display value in tauto_policy_coverage and tquote_auto_policy_coverage tables','Enhancement','2025-04-18','Architha Gudimalla','Modification','edw_core','tquote_auto_policy_coverage','basic_pip','Updated logic to populate basic pip in tquote_auto_policy_coverage table','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9089','EDW/Datamart Enhancements: Updated stored procedure logic to populate BILimit value to match Metal display value in tauto_policy_coverage and tquote_auto_policy_coverage tables','Enhancement','2025-04-18','Architha Gudimalla','Modification','edw_core','tauto_policy_coverage','bodily_injury_limit_amt','Updated logic to populate BI limit in tauto_policy_coverage table','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9089','EDW/Datamart Enhancements: Updated stored procedure logic to populate BILimit value to match Metal display value in tauto_policy_coverage and tquote_auto_policy_coverage tables','Enhancement','2025-04-18','Architha Gudimalla','Modification','edw_core','tquote_auto_policy_coverage','bodily_injury_limit_amt','Updated logic to populate BI limit in tquote_auto_policy_coverage table','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9089','EDW/Datamart Enhancements: Updated stored procedure logic to populate DeductibleAppliesTo value to match Metal display value in tauto_policy_coverage and tquote_auto_policy_coverage tables','Enhancement','2025-04-18','Architha Gudimalla','Modification','edw_core','tauto_policy_coverage','deductible_applies_to','Updated logic to populate deductible applies to in tauto_policy_coverage table','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9089','EDW/Datamart Enhancements: Updated stored procedure logic to populate DeductibleAppliesTo value to match Metal display value in tauto_policy_coverage and tquote_auto_policy_coverage tables','Enhancement','2025-04-18','Architha Gudimalla','Modification','edw_core','tquote_auto_policy_coverage','deductible_applies_to','Updated logic to populate deductible applies to in tquote_auto_policy_coverage table','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9089','EDW/Datamart Enhancements: Updated stored procedure logic to populate UIMLimit value to match Metal display value in tauto_policy_coverage and tquote_auto_policy_coverage tables','Enhancement','2025-04-18','Architha Gudimalla','Modification','edw_core','tauto_policy_coverage','uninsured_motorist_limit_amt','Updated logic to populate UIM limit in tauto_policy_coverage table','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9089','EDW/Datamart Enhancements: Updated stored procedure logic to populate UIMLimit value to match Metal display value in tauto_policy_coverage and tquote_auto_policy_coverage tables','Enhancement','2025-04-18','Architha Gudimalla','Modification','edw_core','tquote_auto_policy_coverage','uninsured_motorist_limit_amt','Updated logic to populate UIM limit in tquote_auto_policy_coverage table','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9089','EDW/Datamart Enhancements: Updated stored procedure logic to populate UMBIPolicyLimit value to match Metal display value in tauto_policy_coverage and tquote_auto_policy_coverage tables','Enhancement','2025-04-18','Architha Gudimalla','Modification','edw_core','tauto_policy_coverage','um_bi_policy_limit_amt','Updated logic to populate UMBI policy limit in tauto_policy_coverage table','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9089','EDW/Datamart Enhancements: Updated stored procedure logic to populate UMBIPolicyLimit value to match Metal display value in tauto_policy_coverage and tquote_auto_policy_coverage tables','Enhancement','2025-04-18','Architha Gudimalla','Modification','edw_core','tquote_auto_policy_coverage','um_bi_policy_limit_amt','Updated logic to populate UMBI policy limit in tquote_auto_policy_coverage table','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9089','EDW/Datamart Enhancements: Updated stored procedure logic to populate UMLimit value to match Metal display value in tauto_policy_coverage and tquote_auto_policy_coverage tables','Enhancement','2025-04-18','Architha Gudimalla','Modification','edw_core','tauto_policy_coverage','underinsured_motorist_limit_amt','Updated logic to populate underinsured motorist limit in tauto_policy_coverage table','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9089','EDW/Datamart Enhancements: Updated stored procedure logic to populate UMLimit value to match Metal display value in tauto_policy_coverage and tquote_auto_policy_coverage tables','Enhancement','2025-04-18','Architha Gudimalla','Modification','edw_core','tquote_auto_policy_coverage','underinsured_motorist_limit_amt','Updated logic to populate underinsured motorist limit in tquote_auto_policy_coverage table','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9089','EDW/Datamart Enhancements: Updated stored procedure logic to populate WorkLossExclusion value to match Metal display value in tauto_policy_coverage and tquote_auto_policy_coverage tables','Enhancement','2025-04-18','Architha Gudimalla','Modification','edw_core','tauto_policy_coverage','work_loss_exclusion','Updated logic to populate work loss exclusion in tauto_policy_coverage table','32','Yes','2025-04-21',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9089','EDW/Datamart Enhancements: Updated stored procedure logic to populate WorkLossExclusion value to match Metal display value in tauto_policy_coverage and tquote_auto_policy_coverage tables','Enhancement','2025-04-18','Architha Gudimalla','Modification','edw_core','tquote_auto_policy_coverage','work_loss_exclusion','Updated logic to populate work loss exclusion in tquote_auto_policy_coverage table','32','Yes','2025-04-21',getdate(),getdate());