-- tedw_release_summary
INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 05/05/2025 :</span>
    <h4 style="margin-top: 0;font-style: italic;color: blue;">This release had 15 enhancements and 9 bug fix tickets.  Release details are as follows.</h4>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; }
        h1, h2 { color: #333; }
        ul { margin: 10px 0; padding-left: 20px; }
    </style>
</head>
<body>

    <h2 style="font-style: italic;">1. EDW/Datamart Enhancements</h2>

    <ul>
    <li>Created following data marts for commercial business:
        <ul>
            <li>tcommercial_broker_summary</li>
            <li>tcommercial_policy_summary</li>
            <li>tcommercial_daily_inforce_policy</li>
        </ul>
    </li>
    <li>Added column - agreed_value_coverage_in to tauto_vehicle_coverage and tquote_auto_vehicle_coverage (part of Metal 5/3 release)</li>
    <li>Added column - flood_deductible to tauto_vehicle_coverage and tquote_auto_vehicle_coverage (part of Metal 5/3 release)</li>
    <li>Added column - cancellation_sub_reason_desc to tpolicy_history table</li>
    <li>Added column - fronting_fee_total and underwriting_year_percentage to nfp_policy table</li>
    <li>Added column - coverage_confirmed_ts, coverage_confirmed_by_nm and coverage_confirmed_in to tclaim table</li>
    <li>Created a new table tclaim_tag to capture tags data</li>
    <li>Updated stored procedure logic to capture one missing transaction from tpolicy_history and tquote_history tables</li>
    <li>Updated stored procedure logic to handle duplicate records caused by payments cancelled in OneInc</li>
    <li>Updated stored procedure logic to accurately populate claim_first_reopen_dt in tclaim table</li>
    <li>Updated stored procedure logic to accurately populate loss_of_use_derived_pc in thome_coverage table</li>
    <li>Added new PEL coverage code to taslob table</li>
</ul>

<h2 style="font-style: italic;">2. EDW Integrations</h2>

<h3>a. Workday Enhancements</h3>
<ul>
    <li>Created new Workday feeds for litigation claims:
        <ul>
            <li><i>litigation_claim_payment</i></li>
            <li><i>litigation_claim_reserve</i></li>
            <li><i>litigation_claim_reserve_itd</i></li>
        </ul>
    </li>
    <li>Updated stored procedure logic for written premium, unearned premium and ceded premium file to populate risk address instead of mailing address in address fields</li>
</ul>

<h3>b. Hubspot</h3>
<ul>
    <li>Added column - monoline_in to quote_hubspot_feed and customer_hubspot_feed</li>
    <li>Added column - primary_address_state_cd to broker_hubspot_feed table</li>
</ul>

<h3>c. Ivans</h3>
<ul>
    <li>VI-36538/VI-37391 : Resent IVANS policies associated with these ticket</li>
</ul>

<h2 style="font-style: italic;">3. Data Fixes</h2>
<ul>
    <li>AD9258 : Inserted missing endorsement record associated with EX100166793 into tpolicy_history table</li>
    <li>AD9236 : Inserted missing endorsement record associated with AU100167000 into tpolicy_history table</li>
    <li>AD9320 : Removed Social Security Numbers (SSNs) from the eBao staging table for 4 claims</li>
    <li>VI-35404 : Updated missing loss date in Metal using loss date from prior policy / CLUE data</li>
    <li>VI-37419 : Updated missing policy number and issued date for old commercial policies in AccountTransaction table within the staging schema</li>
    <li>INC-37541 : Updated distance to coast field to null for ~200 policies from inland states</li>
    <li>AD8971: Updated ceded premium amounts for HO100145793-02 and HO200041071</b></li>
</ul>
</body>
'
,'Yes'
,'2025-05-05'
,getdate()
,getdate()
)
;

-- tedw_release_note
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9227','EDW/Datamart Enhancements: Added data marts for commercial business','Enhancement','2025-05-02','Architha Gudimalla','Addition','edw_integration','tcommercial_broker_summary','','Created new table','33','Yes','2025-05-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9227','EDW/Datamart Enhancements: Added data marts for commercial business','Enhancement','2025-05-02','Architha Gudimalla','Addition','edw_integration','tcommercial_policy_summary','','Created new table','33','Yes','2025-05-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9227','EDW/Datamart Enhancements: Added data marts for commercial business','Enhancement','2025-05-02','Architha Gudimalla','Addition','edw_integration','tcommercial_daily_inforce_policy','','Created new table','33','Yes','2025-05-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9286','EDW/Datamart Enhancements: Added agreed_value_coverage_in and flood_deductible columns as part of Metal 5/3 release','Enhancement','2025-05-02','Tuba Mohsin','Addition','edw_core','tauto_vehicle_coverage','agreed_value_coverage_in','Created new column','33','Yes','2025-05-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9286','EDW/Datamart Enhancements: Added agreed_value_coverage_in and flood_deductible columns as part of Metal 5/3 release','Enhancement','2025-05-02','Tuba Mohsin','Addition','edw_core','tquote_auto_vehicle_coverage','agreed_value_coverage_in','Created new column','33','Yes','2025-05-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9286','EDW/Datamart Enhancements: Added agreed_value_coverage_in and flood_deductible columns as part of Metal 5/3 release','Enhancement','2025-05-02','Tuba Mohsin','Addition','edw_core','tauto_vehicle_coverage','flood_deductible','Created new column','33','Yes','2025-05-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9286','EDW/Datamart Enhancements: Added agreed_value_coverage_in and flood_deductible columns as part of Metal 5/3 release','Enhancement','2025-05-02','Tuba Mohsin','Addition','edw_core','tquote_auto_vehicle_coverage','flood_deductible','Created new column','33','Yes','2025-05-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9322','EDW/Datamart Enhancements: Added cancellation sub reason column to tpolicy_history table','Enhancement','2025-05-02','Bhaskar Muthyala','Addition','edw_core','tpolicy_history','cancellation_sub_reason_desc','Created new column','33','Yes','2025-05-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9268','EDW/Datamart Enhancements: Added fronting_fee_total and underwriting_year_percentage columns to nfp_policy table','Enhancement','2025-05-02','Rushin Shah','Addition','edw_stage','nfp_policy','fronting_fee_total','Created new column','33','Yes','2025-05-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9268','EDW/Datamart Enhancements: Added fronting_fee_total and underwriting_year_percentage columns to nfp_policy table','Enhancement','2025-05-02','Rushin Shah','Addition','edw_stage','nfp_policy','underwriting_year_percentage','Created new column','33','Yes','2025-05-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9203','EDW/Datamart Enhancements: Added snapsheet coverage check fields to tclaim table','Enhancement','2025-05-02','Tuba Mohsin','Addition','edw_core','tclaim','coverage_confirmed_in','Created new column','33','Yes','2025-05-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9203','EDW/Datamart Enhancements: Added snapsheet coverage check fields to tclaim table','Enhancement','2025-05-02','Tuba Mohsin','Addition','edw_core','tclaim','coverage_confirmed_by_nm','Created new column','33','Yes','2025-05-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9203','EDW/Datamart Enhancements: Added snapsheet coverage check fields to tclaim table','Enhancement','2025-05-02','Tuba Mohsin','Addition','edw_core','tclaim','coverage_confirmed_ts','Created new column','33','Yes','2025-05-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9200','EDW/Datamart Enhancements: Created new table to capture tags data','Enhancement','2025-05-02','Tuba Mohsin','Addition','edw_core','tclaim_tag','','Created new table','33','Yes','2025-05-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9259','EDW/Datamart Enhancements: Updated stored procedure logic to capture missing transaction in tpolicy_history and tquote_history tables','Enhancement','2025-05-02','Yunus Mohammed','Modification','edw_core','tpolicy_history','','Updated logic to capture missing transaction in tpolicy_history table','33','Yes','2025-05-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9259','EDW/Datamart Enhancements: Updated stored procedure logic to capture missing transaction in tpolicy_history and tquote_history tables','Enhancement','2025-05-02','Yunus Mohammed','Modification','edw_core','tquote_history','','Updated logic to capture missing transaction in tquote_history table','33','Yes','2025-05-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9185','EDW/Datamart Enhancements: Updated stored procedure logic to handle duplicate records caused by payments cancelled in OneInc','Enhancement','2025-05-02','Sandeep Gundreddy','Modification','edw_core','tclaim_transaction','','Updated logic to to handle duplicate records caused by payments cancelled in OneInc','33','Yes','2025-05-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8748','EDW/Datamart Enhancements: Updated stored procedure logic to accurately populate claim_first_reopen_dt in tclaim table','Enhancement','2025-05-02','Yunus Mohammed','Modification','edw_core','tclaim','claim_first_reopen_dt','Updated logic to accurately capture claim_first_reopen_dt','33','Yes','2025-05-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9235','EDW/Datamart Enhancements: Updated stored procedure logic accurately populate loss_of_use_derived_pc in home_coverage table','Enhancement','2025-05-02','Architha Gudimalla','Modification','edw_core','thome_coverage','loss_of_use_derived_pc','Updated logic to accurately capture loss_of_use_derived_pc','33','Yes','2025-05-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9235','EDW/Datamart Enhancements: Updated stored procedure logic accurately populate loss_of_use_derived_pc in home_coverage table','Enhancement','2025-05-02','Architha Gudimalla','Modification','edw_core','tquote_home_coverage','loss_of_use_derived_pc','Updated logic to accurately capture loss_of_use_derived_pc','33','Yes','2025-05-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9249','EDW/Datamart Enhancements: Added new PEL coverage code to taslob table (for litigation claims)','Enhancement','2025-05-02','Rushin Shah','Addition','edw_core','taslob','','Added new PEL coverage code','33','Yes','2025-05-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9246','Workday enhancements: Created new workday feed associated with litigation claims','Enhancement','2025-05-02','Rushin Shah','Addition','edw_integration','claim_litigation_workday_payment_feed','','Created new table','33','Yes','2025-05-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9246','Workday enhancements: Created new workday feed associated with litigation claims','Enhancement','2025-05-02','Rushin Shah','Addition','edw_integration','claim_litigation_workday_reserve_feed','','Created new table','33','Yes','2025-05-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9246','Workday enhancements: Created new workday feed associated with litigation claims','Enhancement','2025-05-02','Rushin Shah','Addition','edw_integration','claim_litigation_workday_itd_reserve_feed','','Created new table','33','Yes','2025-05-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8820','Workday enhancements: Updated stored procedure logic for written premium, unearned premium and ceded premium file to populate risk address instead of mailing address in address fields','Enhancement','2025-05-02','Yunus Mohammed','Modification','edw_integration','policy_workday_written_premium_feed','','Updated stored procedure logic to populate address, county, city, risk_state and zip columns','33','Yes','2025-05-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8820','Workday enhancements: Updated stored procedure logic for written premium, unearned premium and ceded premium file to populate risk address instead of mailing address in address fields','Enhancement','2025-05-02','Yunus Mohammed','Modification','edw_integration','policy_workday_unearned_premium_feed','','Updated stored procedure logic to populate address, county, city, risk_state and zip columns','33','Yes','2025-05-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8820','Workday enhancements: Updated stored procedure logic for written premium, unearned premium and ceded premium file to populate risk address instead of mailing address in address fields','Enhancement','2025-05-02','Yunus Mohammed','Modification','edw_integration','policy_workday_ceded_premium_feed','','Updated stored procedure logic to populate address, county, city, risk_state and zip columns','33','Yes','2025-05-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI36538/VI37391','IVANS Policy Resent Request','Bug','2025-05-02','Rushin Shah','Datafix','edw_integration','policy_ivans_home_feed','','Resent a few home policies to IVANS','33','Yes','2025-05-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI36538/VI37391','IVANS Policy Resent Request','Bug','2025-05-02','Rushin Shah','Datafix','edw_integration','policy_ivans_auto_feed','','Resent a few auto policies to IVANS','33','Yes','2025-05-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('VI36538/VI37391','IVANS Policy Resent Request','Bug','2025-05-02','Rushin Shah','Datafix','edw_integration','policy_ivans_pel_feed','','Resent a few PEL policies to IVANS','33','Yes','2025-05-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9292/VI37310','EDW Integrations : Hubspot field additions','Enhancement','2025-05-02','Architha Gudimalla','Addition','edw_integration','quote_hubspot_feed','monoline_in','Created new column','33','Yes','2025-05-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9292/VI37310','EDW Integrations : Hubspot field additions','Enhancement','2025-05-02','Architha Gudimalla','Addition','edw_integration','customer_hubspot_feed','monoline_in','Created new column','33','Yes','2025-05-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9290/VI37383','EDW Integrations : Hubspot field additions','Enhancement','2025-05-02','Architha Gudimalla','Addition','edw_integration','broker_hubspot_feed','primary_address_state_cd','Created new column','33','Yes','2025-05-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9258','Data Fixes: Inserted missing endorsement record associated with EX100166793','Bug','2025-05-02','Yunus Mohammed','Datafix','edw_core','tpolicy_history','','Inserted a record in tpolicy_history table','33','Yes','2025-05-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9236','Data Fixes: Inserted missing endorsement record associated with AU100167000','Bug','2025-05-02','Yunus Mohammed','Datafix','edw_core','tpolicy_history','','Inserted a record in tpolicy_history table','33','Yes','2025-05-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9320','Data Fixes: Removed Social Security Numbers (SSNs) from the eBao staging table for 4 claims','Bug','2025-05-02','Yunus Mohammed','Datafix','edw_stage','t_clm_case','dynamic_fields','Updated SSN from the eBao staging table to null for 4 claims','33','Yes','2025-05-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8193/VI35404','Data Fixes: Updated missing loss date using loss date from prior policy / CLUE data','Bug','2025-05-02','Architha Gudimalla','Datafix','edw_core','tloss_history','loss_dt','Updated missing loss date in Metal and EDW','33','Yes','2025-05-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8193/VI35404','Data Fixes: Updated missing loss date in Metal using loss date from prior policy / CLUE data','Bug','2025-05-02','Architha Gudimalla','Datafix','edw_core','tquote_loss_history','loss_dt','Updated missing loss date in Metal and EDW','33','Yes','2025-05-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9216/VI37419','Data Fixes: Updated missing policy number and issued date for old commercial policies','Bug','2025-05-02','Bhaskar Muthyala','Datafix','edw_stage','AccountTransaction','PolicyNumber','Updated missing policy number in Metal and EDW','33','Yes','2025-05-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9216/VI37419','Data Fixes: Updated missing policy number and issued date for old commercial policies','Bug','2025-05-02','Bhaskar Muthyala','Datafix','edw_stage','AccountTransaction','issueddate','Updated missing policy number in Metal and EDW','33','Yes','2025-05-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9333/INC37541','Data Fixes: Updated distance to coast field to null for ~200 policies from inland states','Bug','2025-05-02','Rushin Shah','Datafix','edw_core','thome_coverage','distance_to_coast','Updated distance_to_coast for inland policies to null in Metal and EDW','33','Yes','2025-05-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9333/INC37541','Data Fixes: Updated distance to coast field to null for ~200 policies from inland states','Bug','2025-05-02','Rushin Shah','Datafix','edw_core','tquote_home_coverage','distance_to_coast','Updated distance_to_coast for inland policies to null in Metal and EDW','33','Yes','2025-05-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8971','Data Fixes: Updated ceded premium amounts for HO100145793-02 and HO200041071','Bug','2025-05-02','Tuba Mohsin','Datafix','edw_core','tpolicy_transaction','ceded_premium_amt','Updated ceded premium for 2 policies in Metal and EDW','33','Yes','2025-05-05',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8971','Data Fixes: Updated ceded premium amounts for HO100145793-02 and HO200041071','Bug','2025-05-02','Tuba Mohsin','Datafix','edw_core','tpolicy_transaction','ceded_annual_premium_amt','Updated ceded premium for 2 policies in Metal and EDW','33','Yes','2025-05-05',getdate(),getdate());