-- tedw_release_summary
INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 05/26/2025 :</span>
<h4 style="margin-top: 0;font-style: italic;color: blue;">This release had 13 enhancements and 4 bug fix tickets.  Release details are as follows. </h4>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; }
        h1, h2 { color: #333; }
        ul { margin: 10px 0; padding-left: 20px; }
    </style>
</head>
<body>
    <h2 style="font-style: italic;">1. EDW/Datamart Enhancements</h2>
    

    <ul>
        <li>Created two new tables :
            <ul>
                <li>tbroker_servicing_team</li>
                <li>tbroker_servicing_team_member</li>
            </ul>
        </li>
        <li>Created tcommercial_renewal_summary datamarts for commercial business</li>
        <li>Created new tables in stage schema to load Majesco Billing data from Azure Storage Account</li>
        <li>Added column broker_servicing_team_sk to tbroker table</li>
        <li>Added column forecast_quote_in to tquote table</li>
        <li>Added column first_party_driver_relationship_to_insured to tclaim table</li>
        <li>Added column AdjusterName to claim_renewal_rating_home_collection_api and claim_renewal_rating_auto_pel_api tables</li>
        <li>Added column FirstPartyDriverRelationshipToInsured to claim_renewal_rating_auto_pel_api table</li>
        <li>Added column prior_term_policy_no to tcommercial_policy table</li>
        <li>Added column first_quoted_commercial_quote_history_sk to tcommercial_quote table</li>
        <li>Added column prior_term_policy_no to tcommercial_quote table</li>
        <li>Added column first_quoted_commercial_quote_ts to tcommercial_quote table</li>
        <li>Added new provisional policy for Vault UW litigation company</li>
        <li>Updated Snapsheet validation scripts to exclude provisional policy</li>
        <li>Backfilling of wildfire protection fields</li>
    </ul>
    
  <h3>Metal 5/22 Release:</h3>
  <ul>
        <li>Added the following new fields:</li>
    <ul>
        <li>caddy_grade: thome_additional_coverage and tquote_home_additional_coverage tables</li>
        <li>all_peril_roof_covering_coverage_cw_in: thome_additional_coverage and tquote_home_additional_coverage tables</li>
        <li>auto_liability_exclusion_in: tpel_coverage and tquote_pel_coverage tables</li>
        <li>insurance_score_source: tpolicy_history and tquote_history tables</li>
        <li>recreational_watercraft_exclusion_in: tpel_coverage and tquote_pel_coverage tables</li>
        <li>recreational_motorvehicle_exclusion_in: tpel_coverage and tquote_pel_coverage tables</li>
        <li>consent_to_rate_otccoll: tauto_policy_coverage and tquote_auto_policy_coverage tables</li>
    </ul>
    </ul>
    
    <h2 style="font-style: italic;">2. EDW Process Improvements</h2>
    <ul>
        <li>Automated data quality checks to validate monthly written premium, unearned premium and claims payment amounts between Workday and EDW</li>
    </ul>
    
    <h2 style="font-style: italic;">3. EDW Integrations</h2>
    <h3>a. Hubspot</h3>
    <ul>
        <li>Added column broker_state to quote_hubspot_feed table</li>
    </ul>    
    
    <h3>b. IVANS</h3>
    <ul>
        <li>Resent IVANS policies for tickets INC37778 and INC37616</li>
    </ul>
    
    <h2>4. Data Fixes</h2>
    <ul>
        <li>AD9431: Updated Mailing address for two new business policies in Metal</li>
        <li>AD8750: Populated some of the missing claim notes in tclaim_note table</li>
        <li>AD9506: Updated claim numbers for 2 snapsheet claims</li>
    </ul>
</body>
'
,'Yes'
,'2025-05-26'
,getdate()
,getdate()
)
;

-- tedw_release_note
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9400','EDW/Datamart Enhancements: Created provisional policy for Vault UW Litigation companies','Enhancement','2025-05-22','Bhaskar Muthyala','Addition','edw_core','tpolicy','','Created provisional record to support litigation claims in Snapsheet','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9400','EDW/Datamart Enhancements: Created provisional policy for Vault UW Litigation companies','Enhancement','2025-05-22','Bhaskar Muthyala','Addition','edw_integration','claim_policy_search_snapsheet_api','','Created provisional record to support litigation claims in Snapsheet','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9400','EDW/Datamart Enhancements: Created provisional policy for Vault UW Litigation companies','Enhancement','2025-05-22','Bhaskar Muthyala','Addition','edw_integration','claim_policy_webhook_snapsheet_api','','Created provisional record to support litigation claims in Snapsheet','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9458','EDW/Datamart Enhancements: Updated Snapsheet validation scripts to exclude provisional policy','Enhancement','2025-05-22','Yunus Mohammed','Addition','edw_core','tvalidation_sql','source_sql','Updated source_sql column to add provisional policy so it will exclude from validation','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9399','EDW Integration: Added column AdjusterName in Home and Collections Renewal Rating API Response to Metal','Enhancement','2025-05-22','Bhaskar Muthyala','Addition','edw_integration','claim_renewal_rating_home_collection_api','AdjusterName','Created new column','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9399','EDW Integration: Added column AdjusterName in Auto and Excess Liability Renewal Rating API Response to Metal','Enhancement','2025-05-22','Bhaskar Muthyala','Addition','edw_integration','claim_renewal_rating_auto_pel_api ','AdjusterName','Created new column','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9399','EDW Integration: Added column FirstPartyDriverRelationshipToInsured in Auto and Excess Liability Renewal Rating API Response to Metal','Enhancement','2025-05-22','Bhaskar Muthyala','Addition','edw_integration','claim_renewal_rating_auto_pel_api ','FirstPartyDriverRelationshipToInsured','Created new column','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9399','EDW/Datamart Enhancements: Added column first_party_driver_relationship_to_insured to tclaim table','Enhancement','2025-05-22','Bhaskar Muthyala','Addition','edw_core','tclaim','first_party_driver_relationship_to_insured','Created new column','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9431/VI37434','Data Fixes: Updated mailing address for two policies','Bug','2025-05-22','Architha Gudimalla','Datafix','edw_stage','AccountTransactionVersionObjectField','value','Updated mailing address in Metal and EDW','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9431/VI37434','Data Fixes: Updated mailing address for two policies','Bug','2025-05-22','Architha Gudimalla','Datafix','edw_core','tpolicy_insured','mailing_address_line_1','Updated mailing address in EDW','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9390','EDW/Datamart Enhancements: Created new column to tcommercial_policy and tcommercial_quote table','Enhancement','2025-05-22','Architha Gudimalla','Addition','edw_core','tcommercial_policy','prior_term_policy_no','Created new column','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9390','EDW/Datamart Enhancements: Created new column to tcommercial_quote table','Enhancement','2025-05-22','Architha Gudimalla','Addition','edw_core','tcommercial_quote','prior_term_policy_no','Created new column','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9390','EDW/Datamart Enhancements: Created new column to tcommercial_policy table','Enhancement','2025-05-22','Architha Gudimalla','Addition','edw_core','tcommercial_quote','first_quoted_commercial_quote_history_sk','Created new column','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9390','EDW/Datamart Enhancements: Created new column to tcommercial_policy table','Enhancement','2025-05-22','Architha Gudimalla','Addition','edw_core','tcommercial_quote','first_quoted_commercial_quote_ts','Created new column','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9470','EDW/Datamart Enhancements: Created new data mart tcommercial_renewal_summary table','Enhancement','2025-05-22','Architha Gudimalla','Addition','edw_core','tcommercial_renewal_summary','','Created new table','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9506','Data Fixes: Updated Claim Numbers for two Snapsheet claims','Bug','2025-05-22','Bhaskar Muthyala','Datafix','edw_core','tclaim','claim_no','Updated claim number for 2 claims in EDW','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9506','Data Fixes: Updated Claim Numbers for two Snapsheet claims','Bug','2025-05-22','Bhaskar Muthyala','Datafix','edw_core','tclaim_feature','claim_no','Updated claim number for 2 claims in EDW','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9506','Data Fixes: Updated Claim Numbers for two Snapsheet claims','Bug','2025-05-22','Bhaskar Muthyala','Datafix','edw_core','tclaim_note','claim_no','Updated claim number for 2 claims in EDW','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9506','Data Fixes: Updated Claim Numbers for two Snapsheet claims','Bug','2025-05-22','Bhaskar Muthyala','Datafix','edw_core','tclaim_task','claim_no','Updated claim number for 2 claims in EDW','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9512/VI37383','EDW Integrations : Hubspot field additions','Enhancement','2025-05-22','Architha Gudimalla','Addition','edw_integration','quote_hubspot_feed','broker_state','Created new column','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9465','Backfilling of Wildfire protection fields','Enhancement','2025-05-22','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','wildfire_protection_enrollment_in','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9465','Backfilling of Wildfire protection fields','Enhancement','2025-05-22','Tuba Mohsin','Addition','edw_core','tquote_home_additional_coverage','wildfire_protection_enrollment_in','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9465','Backfilling of Wildfire protection fields','Enhancement','2025-05-22','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','site_scheduling_contact_nm','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9465','Backfilling of Wildfire protection fields','Enhancement','2025-05-22','Tuba Mohsin','Addition','edw_core','tquote_home_additional_coverage','site_scheduling_contact_nm','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9465','Backfilling of Wildfire protection fields','Enhancement','2025-05-22','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','site_scheduling_phone_no','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9465','Backfilling of Wildfire protection fields','Enhancement','2025-05-22','Tuba Mohsin','Addition','edw_core','tquote_home_additional_coverage','site_scheduling_phone_no','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9465','Backfilling of Wildfire protection fields','Enhancement','2025-05-22','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','site_scheduling_email','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9465','Backfilling of Wildfire protection fields','Enhancement','2025-05-22','Tuba Mohsin','Addition','edw_core','tquote_home_additional_coverage','site_scheduling_email','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9465','Backfilling of Wildfire protection fields','Enhancement','2025-05-22','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','emergency_contact_nm','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9465','Backfilling of Wildfire protection fields','Enhancement','2025-05-22','Tuba Mohsin','Addition','edw_core','tquote_home_additional_coverage','emergency_contact_nm','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9465','Backfilling of Wildfire protection fields','Enhancement','2025-05-22','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','emergency_contact_phone_no','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9465','Backfilling of Wildfire protection fields','Enhancement','2025-05-22','Tuba Mohsin','Addition','edw_core','tquote_home_additional_coverage','emergency_contact_phone_no','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9465','Backfilling of Wildfire protection fields','Enhancement','2025-05-22','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','emergency_contact_email','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9465','Backfilling of Wildfire protection fields','Enhancement','2025-05-22','Tuba Mohsin','Addition','edw_core','tquote_home_additional_coverage','emergency_contact_email','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9465','Backfilling of Wildfire protection fields','Enhancement','2025-05-22','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','gate_code','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9465','Backfilling of Wildfire protection fields','Enhancement','2025-05-22','Tuba Mohsin','Addition','edw_core','tquote_home_additional_coverage','gate_code','Backfilling data for following wildfire protection fields WFSiteSchedulingContactName, WFSiteSchedulingPhoneNumber,WFSiteSchedulingEmailAddress, WFEmergencyContactName, WFEmergencyContactPhoneNumber, WFEmergencyContactEmail and WFGateCodes based on information received from manual forms.','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9375','EDW/Datamart Enhancements: Metal 5/22 Release Field additions','Enhancement','2025-05-22','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','caddy_grade','Created new column','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9375','EDW/Datamart Enhancements: Metal 5/22 Release Field additions','Enhancement','2025-05-22','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','all_peril_roof_covering_coverage_cw_in','Created new column','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9375','EDW/Datamart Enhancements: Metal 5/22 Release Field additions','Enhancement','2025-05-22','Tuba Mohsin','Addition','edw_core','tquote_home_additional_coverage','caddy_grade','Created new column','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9375','EDW/Datamart Enhancements: Metal 5/22 Release Field additions','Enhancement','2025-05-22','Tuba Mohsin','Addition','edw_core','tquote_home_additional_coverage','all_peril_roof_covering_coverage_cw_in','Created new column','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9375','EDW/Datamart Enhancements: Metal 5/22 Release Field additions','Enhancement','2025-05-22','Tuba Mohsin','Addition','edw_core','tpel_coverage','auto_liability_exclusion_in','Created new column','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9375','EDW/Datamart Enhancements: Metal 5/22 Release Field additions','Enhancement','2025-05-22','Tuba Mohsin','Addition','edw_core','tpel_coverage','recreational_watercraft_exclusion_in','Created new column','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9375','EDW/Datamart Enhancements: Metal 5/22 Release Field additions','Enhancement','2025-05-22','Tuba Mohsin','Addition','edw_core','tpel_coverage','recreational_motorvehicle_exclusion_in','Created new column','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9375','EDW/Datamart Enhancements: Metal 5/22 Release Field additions','Enhancement','2025-05-22','Tuba Mohsin','Addition','edw_core','tquote_pel_coverage','auto_liability_exclusion_in','Created new column','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9375','EDW/Datamart Enhancements: Metal 5/22 Release Field additions','Enhancement','2025-05-22','Tuba Mohsin','Addition','edw_core','tquote_pel_coverage','recreational_watercraft_exclusion_in','Created new column','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9375','EDW/Datamart Enhancements: Metal 5/22 Release Field additions','Enhancement','2025-05-22','Tuba Mohsin','Addition','edw_core','tquote_pel_coverage','recreational_motorvehicle_exclusion_in','Created new column','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9375','EDW/Datamart Enhancements: Metal 5/22 Release Field additions','Enhancement','2025-05-22','Tuba Mohsin','Addition','edw_core','tpolicy_history','insurance_score_source','Created new column','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9375','EDW/Datamart Enhancements: Metal 5/22 Release Field additions','Enhancement','2025-05-22','Tuba Mohsin','Addition','edw_core','tquote_history','insurance_score_source','Created new column','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9375','EDW/Datamart Enhancements: Metal 5/22 Release Field additions','Enhancement','2025-05-22','Tuba Mohsin','Addition','edw_core','tauto_policy_coverage','consent_to_rate_otccoll','Created new column','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9375','EDW/Datamart Enhancements: Metal 5/22 Release Field additions','Enhancement','2025-05-22','Tuba Mohsin','Addition','edw_core','tquote_auto_policy_coverage','consent_to_rate_otccoll','Created new column','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8750','Data Fixes: Populated some of the missing claim notes in tclaim_note table','Bug','2025-05-22','Bhaskar Muthyala','Datafix','edw_core','tclaim_note','','Populated missing claim notes created after claim has been created in Snapsheet','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC37778/INC37616','IVANS Policy Resent Request','Bug','2025-05-22','Rushin Shah','Datafix','edw_integration','policy_ivans_home_feed','','Resent a few home policies to IVANS','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC37778/INC37616','IVANS Policy Resent Request','Bug','2025-05-22','Rushin Shah','Datafix','edw_integration','policy_ivans_auto_feed','','Resent a few auto policies to IVANS','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC37778/INC37616','IVANS Policy Resent Request','Bug','2025-05-22','Rushin Shah','Datafix','edw_integration','policy_ivans_pel_feed','','Resent a few PEL policies to IVANS','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9361','EDW/Datamart Enhancements : Total Agency Partnership (TAP) related enhancements','Enhancement','2025-05-22','Sandeep Gundreddy','Addition','edw_core','tbroker_servicing_team','','Created new table','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9361','EDW/Datamart Enhancements : Total Agency Partnership (TAP) related enhancements','Enhancement','2025-05-22','Sandeep Gundreddy','Addition','edw_core','tbroker_servicing_team_member','','Created new table','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9361','EDW/Datamart Enhancements : Total Agency Partnership (TAP) related enhancements','Enhancement','2025-05-22','Sandeep Gundreddy','Addition','edw_core','tbroker','broker_servicing_team_sk','Created new column','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9361','EDW/Datamart Enhancements : Total Agency Partnership (TAP) related enhancements','Enhancement','2025-05-22','Sandeep Gundreddy','Addition','edw_core','tquote','forecast_quote_in','Created new column','34','Yes','2025-05-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9250','EDW Process Improvements : Created data quality checks to validate monthly written premium, unearned premium and claims payment ','Enhancement','2025-05-22','Yunus Mohammed','Addition','edw_core','tvalidation_sql','','Automated data quality checks to validate monthly written premium, unearned premium and claims payment amounts between Workday and EDW','34','Yes','2025-05-26',getdate(),getdate());