update edw_core.tedw_release_note set impacted_column_nm = 'Litigation' where ticket_no= 'AD9733' and impacted_table_nm = 'claim_renewal_rating_auto_pel_api' and impacted_column_nm = 'litigation_in'
update edw_core.tedw_release_note set impacted_table_nm = 'claim_renewal_rating_home_collection_api' where ticket_no= 'AD9733' and impacted_table_nm = 'claim_renewal_rating_home_collection_api tables'
update edw_core.tedw_release_note set impacted_column_nm = 'Litigation' where ticket_no= 'AD9733' and impacted_table_nm = 'claim_renewal_rating_home_collection_api' and impacted_column_nm = 'litigation_in'

INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9733','EDW/Datamart Enhancements: Created new column to tclaim, claim_renewal_rating_auto_pel_api and claim_renewal_rating_home_collection_api tables','Enhancement','2025-06-14','Bhaskar Muthyala','Addition','edw_core','tclaim','litigation_complete_in','Created new column','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9733','EDW/Datamart Enhancements: Created new column to tclaim, claim_renewal_rating_auto_pel_api and claim_renewal_rating_home_collection_api tables','Enhancement','2025-06-14','Bhaskar Muthyala','Addition','edw_integration','claim_renewal_rating_auto_pel_api','LitigationComplete','Created new column','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9733','EDW/Datamart Enhancements: Created new column to tclaim, claim_renewal_rating_auto_pel_api and claim_renewal_rating_home_collection_api tables','Enhancement','2025-06-14','Bhaskar Muthyala','Addition','edw_integration','claim_renewal_rating_home_collection_api','LitigationComplete','Created new column','35','Yes','2025-06-16',getdate(),getdate());


