-- tedw_release_summary
INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 06/16/2025 :</span>
<h4 style="margin-top: 0;font-style: italic;color: blue;">This release had 13 enhancements and 8 bug fix tickets.  Release details are as follows. </h4>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; }
        h1, h2 { color: #333; }
        ul { margin: 10px 0; padding-left: 20px; }
    </style>
</head>
<body>
    <h2 style="font-style: italic;">1. EDW/Datamart Enhancements</h2>
    

    <ul>
        <li>Added column - document_delivery_method to tpolicy and tquote tables</li>
        <li>Added column - document_delivery_to to tpolicy and tquote tables</li>
        <li>Added column - litigation_in to tclaim, claim_renewal_rating_auto_pel_api and claim_renewal_rating_home_collection_api tables</li>
        <li>Added column - wildfire_suppression_system to thome_coverage and tquote_home_coverage tables</li>
        <li>Added column - wildfire_decks_balconies_porches_stairs to thome_coverage and tquote_home_coverage tables</li>
        <li>Updated claims stored procedures to exclude Commercial Lines claims from being loaded into the Personal Lines EDW. This involved integrating tag data to accurately filter out Commercial Lines claims.</li>
        <li>Updated gate_code field logic in thome_additional_coverage and tquote_home_additional_coverage table to capture multiple gate codes seperated by "|" as a delimiter</li>
        <li>SQL scripts for four Commercial Lines Phase 1 reports are complete, and reports can now be generated on demand</li>
        <li>Update trenewal_summary data mart code to exclude forecast quotes</li>
    </ul>

    <h2 style="font-style: italic;">2. EDW Process Improvements</h2>
    <ul>
        <li>Added data quality checks to identify missing product_sk for snapsheet claims</li>
        <li>Added data quality checks to identify claims where claim_no exceeds 15 characters in length</li>
        <li>Added data quality checks to flag transactions incorrectly mapped to internal coverage categories, specifically for "Surplus Lines Tax", "Clearing House Fee", "EMPA Surcharge" and "Healthy Homes Fund Surcharge"</li>
        <li>Added data quality checks to ensure key CLUE Auto feed columns do not contain NULL values</li>
    </ul>
    
    <h2 style="font-style: italic;">3. EDW Integrations</h2>
    <h3>a. Hubspot</h3>
    <ul>
        <li>Added column - document_delivery_preference to customer_hubspot_feed table</li>
    </ul>
    
    <h3>b. IVANS</h3>
    <ul>
        <li>INC38280/INC37991/INC27371: Resent IVANS policies associated with these tickets</li>
    </ul>
    
    <h3>c. Majesco</h3>
    <ul>
        <li>Created following 2 views on top of Majesco stage tables for daily reporting:</li>
        <ul>
            <li>vmajescocashactivity</li>
            <li>vmajescoduedateaging</li>
        </ul>
    </ul>

    <h2>4. Data Fixes</h2>
    <ul>
        <li>AD9676: Fixed transactions mapped to incorrect internal coverage category specifically for "Surplus Lines Tax", "Clearing House Fee", "EMPA Surcharge" and "Healthy Homes Fund Surcharge" in Metal and EDW</li>
        <li>AD9689: Reclassified all historical Condo claim transactions as "Condo" (from "Homeowners") and ensure all future transactions follow the same categorization</li>
        <li>AD9604: Deleted 2 duplicated snapsheet claims from renewal rating tables</li>
        <li>AD9637: Updated BCEG Credit percent for HO200037882 in Metal and EDW</li>
        <li>AD9769 : Updated latitude and longitude columns for 14 policies in Metal and EDW</li>
    </ul>
</body>
'
,'Yes'
,'2025-06-16'
,getdate()
,getdate()
)
;

INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9713','EDW/Datamart Enhancements: Created new column to tpolicy and tquote tables','Enhancement','2025-06-14','Bhaskar Muthyala','Addition','edw_core','tpolicy','document_delivery_method','Created new column','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9713','EDW/Datamart Enhancements: Created new column to tpolicy and tquote tables','Enhancement','2025-06-14','Bhaskar Muthyala','Addition','edw_core','tquote','document_delivery_method','Created new column','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9713','EDW/Datamart Enhancements: Created new column to tpolicy and tquote tables','Enhancement','2025-06-14','Bhaskar Muthyala','Addition','edw_core','tpolicy','document_delivery_to','Created new column','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9713','EDW/Datamart Enhancements: Created new column to tpolicy and tquote tables','Enhancement','2025-06-14','Bhaskar Muthyala','Addition','edw_core','tquote','document_delivery_to','Created new column','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9733','EDW/Datamart Enhancements: Created new column to tclaim, claim_renewal_rating_auto_pel_api and claim_renewal_rating_home_collection_api tables','Enhancement','2025-06-14','Bhaskar Muthyala','Addition','edw_core','tclaim','litigation_in','Created new column','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9733','EDW/Datamart Enhancements: Created new column to tclaim, claim_renewal_rating_auto_pel_api and claim_renewal_rating_home_collection_api tables','Enhancement','2025-06-14','Bhaskar Muthyala','Addition','edw_integration','claim_renewal_rating_auto_pel_api','litigation_in','Created new column','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9733','EDW/Datamart Enhancements: Created new column to tclaim, claim_renewal_rating_auto_pel_api and claim_renewal_rating_home_collection_api tables','Enhancement','2025-06-14','Bhaskar Muthyala','Addition','edw_integration','claim_renewal_rating_home_collection_api tables','litigation_in','Created new column','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9706','EDW/Datamart Enhancements: Created new column to thome_coverage and tquote_home_coverage tables','Enhancement','2025-06-14','Tuba Mohsin','Addition','edw_core','thome_coverage','wildfire_suppression_system','Created new column','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9706','EDW/Datamart Enhancements: Created new column to thome_coverage and tquote_home_coverage tables','Enhancement','2025-06-14','Tuba Mohsin','Addition','edw_core','tquote_home_coverage','wildfire_suppression_system','Created new column','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9706','EDW/Datamart Enhancements: Created new column to thome_coverage and tquote_home_coverage tables','Enhancement','2025-06-14','Tuba Mohsin','Addition','edw_core','thome_coverage','wildfire_decks_balconies_porches_stairs','Created new column','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9706','EDW/Datamart Enhancements: Created new column to thome_coverage and tquote_home_coverage tables','Enhancement','2025-06-14','Tuba Mohsin','Addition','edw_core','tquote_home_coverage','wildfire_decks_balconies_porches_stairs','Created new column','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9754','EDW Integrations : Hubspot field additions','Enhancement','2025-06-14','Architha Gudimalla','Addition','edw_integration','customer_hubspot_feed','document_delivery_preference','Created new column','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC38280/INC37991/INC27371','IVANS Policy Resent Request','Bug','2025-06-14','Rushin Shah','Datafix','edw_integration','policy_ivans_home_feed','','Resent a few home policies to IVANS','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC38280/INC37991/INC27371','IVANS Policy Resent Request','Bug','2025-06-14','Rushin Shah','Datafix','edw_integration','policy_ivans_auto_feed','','Resent a few auto policies to IVANS','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC38280/INC37991/INC27371','IVANS Policy Resent Request','Bug','2025-06-14','Rushin Shah','Datafix','edw_integration','policy_ivans_pel_feed','','Resent a few PEL policies to IVANS','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9637','Data Fixes: Updated BCEGCreditPercent for HO200037882','Bug','2025-06-14','Tuba Mohsin','Datafix','edw_core','thome_coverage','bceg_credit_pc','Updated BCEG Credit Percent for 1 policy in Metal and EDW','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9637','Data Fixes: Updated BCEGCreditPercent for HO200037882','Bug','2025-06-14','Tuba Mohsin','Datafix','edw_core','tquote_home_coverage','bceg_credit_pc','Updated BCEG Credit Percent for 1 policy in Metal and EDW','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9602','EDW/Datamart Enhancements: Created a view to query Majesco data','Enhancement','2025-06-14','Bhaskar Muthyala','Addition','edw_core','vmajescocashactivity','','Created new view','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9602','EDW/Datamart Enhancements: Created a view to query Majesco data','Enhancement','2025-06-14','Bhaskar Muthyala','Addition','edw_core','vmajescoduedateaging','','Created new view','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9700','Process Improvements : Updated validations to tvalidation_sql','Enhancement','2025-06-14','Yunus Mohammed','Addition','edw_core','tvalidation_sql','','Updated validation checks to identify missing product_sk for snapsheet claims','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9782','Process Improvements : Updated validations to tvalidation_sql','Enhancement','2025-06-14','Yunus Mohammed','Addition','edw_core','tvalidation_sql','','Updated validation checks to identify claims where claim_no exceeds 15 characters in length','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9765','Process Improvements : Updated validations to tvalidation_sql','Enhancement','2025-06-14','Yunus Mohammed','Addition','edw_core','tvalidation_sql','','Updated validation checks to flag transactions incorrectly mapped to internal coverage categories, specifically for Surplus Lines Tax, Clearing House Fee, EMPA Surcharge and Healthy Homes Fund Surcharge','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9652','Process Improvements : Updated validations to tvalidation_sql','Enhancement','2025-06-14','Yunus Mohammed','Addition','edw_core','tvalidation_sql','','Updated validation checks to ensure key CLUE Auto feed columns do not contain NULL values','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9585','EDW/Datamart Enhancements: Commercial Lines Phase 1 reports','Enhancement','2025-06-14','Rushin Shah','Addition','edw_core','','','Created SQL script for Bordereau report','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9585','EDW/Datamart Enhancements: Commercial Lines Phase 1 reports','Enhancement','2025-06-14','Rushin Shah','Addition','edw_core','','','Created SQL script for Bound Account Tracker','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9585','EDW/Datamart Enhancements: Commercial Lines Phase 1 reports','Enhancement','2025-06-14','Rushin Shah','Addition','edw_core','','','Created SQL script for Renewal Tracker','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9585','EDW/Datamart Enhancements: Commercial Lines Phase 1 reports','Enhancement','2025-06-14','Rushin Shah','Addition','edw_core','','','Created SQL script for Submission Log','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9542','EDW/Datamart Enhancements: Exclude Commercial Lines Claims from Personal Lines EDW (by integrating tags data)','Enhancement','2025-06-14','Bhaskar Muthyala','Modification','edw_core','','','Updated claims stored procedures sp_tcause_of_loss_snapsheet, sp_tclaim_cost_category_snapsheet, sp_tclaim_note_snapsheet, sp_tclaim_snapsheet and sp_tclaim_transaction_snapsheet to exclude Commercial Lines claims from being loaded into the Personal Lines EDW','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9668','EDW/Datamart Enhancements: Update gate_code field logic to capture multiple gate codes','Enhancement','2025-06-14','Yunus Mohammed','Modification','edw_core','thome_additional_coverage','gate_code','Updated gate_code field logic to capture multiple gate codes seperated by "|" as a delimiter','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9668','EDW/Datamart Enhancements: Update gate_code field logic to capture multiple gate codes','Enhancement','2025-06-14','Yunus Mohammed','Modification','edw_core','tquote_home_additional_coverage','gate_code','Updated gate_code field logic to capture multiple gate codes seperated by "|" as a delimiter','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9676','Data Fixes: Fixed transactions mapped to incorrect internal coverage category','Bug','2025-06-14','Rushin Shah','Datafix','edw_stage','AccountTransactionTaxAndFee','Type','Fixed transactions mapped to incorrect internal coverage category specifically for Surplus Lines Tax, Clearing House Fee, EMPA Surcharge and Healthy Homes Fund Surcharge in Metal and EDW','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9676','Data Fixes: Fixed transactions mapped to incorrect internal coverage category','Bug','2025-06-14','Rushin Shah','Datafix','edw_stage','AccountPremiumTaxAndFee','Type','Fixed transactions mapped to incorrect internal coverage category specifically for Surplus Lines Tax, Clearing House Fee, EMPA Surcharge and Healthy Homes Fund Surcharge in Metal and EDW','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9689','Data Fixes: Reclassified all historical Condo claim transactions as Condo product from Homeowners','Bug','2025-06-14','Bhaskar Muthyala','Datafix','edw_core','tclaim','product_sk','Updated stored procedure to classify condo claims under condo product','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9689','Data Fixes: Reclassified all historical Condo claim transactions as Condo product from Homeowners','Bug','2025-06-14','Bhaskar Muthyala','Datafix','edw_core','tclaim_feature','product_sk','Updated stored procedure to classify condo claims under condo product','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9689','Data Fixes: Reclassified all historical Condo claim transactions as Condo product from Homeowners','Bug','2025-06-14','Bhaskar Muthyala','Datafix','edw_core','tclaim_feature_summary','product_sk','Updated stored procedure to classify condo claims under condo product','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9689','Data Fixes: Reclassified all historical Condo claim transactions as Condo product from Homeowners','Bug','2025-06-14','Bhaskar Muthyala','Datafix','edw_core','tclaim_summary','product_sk','Updated stored procedure to classify condo claims under condo product','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9689','Data Fixes: Reclassified all historical Condo claim transactions as Condo product from Homeowners','Bug','2025-06-14','Bhaskar Muthyala','Datafix','edw_core','tclaim_transaction','product_sk','Updated stored procedure to classify condo claims under condo product','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9604','Data Fixes: Deleted 2 duplicated snapsheet claims from renewal rating tables','Bug','2025-06-14','Bhaskar Muthyala','Datafix','edw_integration','claim_renewal_rating_auto_pel_api','','Deleted duplicate snapsheet claim numbers 25ATBRITISH COLUMBIA903308018','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9604','Data Fixes: Deleted 2 duplicated snapsheet claims from renewal rating tables','Bug','2025-06-14','Bhaskar Muthyala','Datafix','edw_integration','claim_renewal_rating_home_collection_api','','Deleted duplicate snapsheet claim numbers 25PRCAICOS ISLANDS941253674','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9769','Data Fixes: Updated latitude and longitude columns for 14 policies in Metal and EDW','Bug','2025-06-14','Tuba Mohsin','Datafix','edw_core','thome_location','latitude','Updated missing latitude for 14 policies in Metal and EDW','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9769','Data Fixes: Updated latitude and longitude columns for 14 policies in Metal and EDW','Bug','2025-06-14','Tuba Mohsin','Datafix','edw_core','thome_location','longitude','Updated missing longitude for 14 policies in Metal and EDW','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9769','Data Fixes: Updated latitude and longitude columns for 14 policies in Metal and EDW','Bug','2025-06-14','Tuba Mohsin','Datafix','edw_core','tquote_home_location','latitude','Updated missing latitude for 14 policies in Metal and EDW','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9769','Data Fixes: Updated latitude and longitude columns for 14 policies in Metal and EDW','Bug','2025-06-14','Tuba Mohsin','Datafix','edw_core','tquote_home_location','longitude','Updated missing longitude for 14 policies in Metal and EDW','35','Yes','2025-06-16',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9823','EDW/Datamart Enhancements: Exclude forecast quotes from trenewal_summary data mart table','Enhancement','2025-06-14','Architha Gudimalla','Modification','edw_core','trenewal_summary','','Updated trenewal_summary data mart code to exclude forecast quotes','35','Yes','2025-06-16',getdate(),getdate());