-- tedw_release_summary
INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 07/14/2025 :</span>
<h4 style="margin-top: 0;font-style: italic;color: blue;">This release had 13 enhancements and 11 bug fix tickets.  Release details are as follows. </h4>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; }
        h1, h2 { color: #333; }
        ul { margin: 10px 0; padding-left: 20px; }
    </style>
</head>
<body>
    <h2 style="font-style: italic;">1. EDW/Datamart Enhancements</h2>
  
    <ul>
        <li>Added column - renewal_cap_factor to tpolicy and tquote tables</li>
        <li>Added column - bound_by_broker_in to tpolicy and tquote tables</li>
        <li>Added columns - bound_by_user_nm and issued_by_user_nm to tquote_history table</li>
        <li>Added column - transaction_bound_by_user_nm to tpolicy_history table</li>
        <li>Added column - commercial_or_personal_business_type to tbroker table</li>
        <li>Added column - all_peril_roof_covering_coverage_specified_states_in to thome_additional_coverage and tquote_home_additional_coverage tables</li>
        <li>Added column - task_id to ttask table</li>
        <li>Added column - license_type to tbroker_license table</li>
        <li>Added column - billing_paid_in to tpolicy table</li>
        <li>Created new stored procedures to integrate commercial policies with Snapsheet via webhook to enable creation of commercial claims in Snapsheet</li>
        <li>Updated um_pd_policy_limit_amt field logic in tauto_policy_coverage and tquote_auto_policy_coverage table specifically for NC auto policies</li>
        <li>Added new provisional policy for Vault UW Litigation Company for commercial lines</li>
    </ul>

    <h2 style="font-style: italic;">2. EDW Process Improvements</h2>
    <ul>
        <li>Added data quality checks to identify brokers which are not mapped to personal lines or commercial lines</li>
        <li>Added data quality checks to identify invalid created/bound/issued userid in Metal</li>
        <li>Updated our standard release notes HTML to point to Vault Solution Center URL</li>
    </ul>
    
    <h2 style="font-style: italic;">3. EDW Integrations</h2>
    <h3>a. Hubspot</h3>
    <ul>
        <li>Added column - product_cd to customer_hubspot_feed table</li>
    </ul>    
    
    <h3>b. IVANS</h3>
    <ul>
        <li>Resent IVANS policies for tickets INC38713,INC38600 and INC38520</li>
    </ul>
    
    <h2>4. Data Fixes</h2>
    <ul>
        <li>AD8426: Fixed transactions mapped to 8 closed claims which had negative reserves</li>
        <li>AD9861: Updated latitude and longitude columns for CO200024575 in Metal and EDW</li>
        <li>AD9812: Fixed premium transactions mapped to 12 expired commercial policies</li>
        <li>AD9862: Updated roof_coverage_endorsement_wh_in for HO100191352-02 in Metal and EDW</li>
        <li>AD9841: Updated missing product_sk in tclaim, tclaim_feature, tclaim_summary and tclaim_feature_summary tables for 2 claims</li>
        <li>AD10002: Updated policy number for 2 commercial policies as per user request</li>
        <li>AD10016: Deleted duplicate record associated with NFP policy NFP071243</li>
        <li>AD10168 : For Metal automated user, updated last_nm to null in tuser table.  This change was applied to the following downstream tables tpolicy_history, tquote_history, tcommercial_quote_history, ttask, tquote_status_history, tquote_transaction_status_history and tnote table.</li>
    </ul>
</body>
'
,'Yes'
,'2025-07-14'
,getdate()
,getdate()
)
;

-- tedw_release_note
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10212','EDW/Datamart Enhancements: Created new column to tpolicy and tquote tables','Enhancement','2025-07-12','Rushin Shah','Addition','edw_core','tpolicy','renewal_cap_factor','Created new column','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10212','EDW/Datamart Enhancements: Created new column to tpolicy and tquote tables','Enhancement','2025-07-12','Rushin Shah','Addition','edw_core','tquote','renewal_cap_factor','Created new column','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10120','EDW/Datamart Enhancements: Created new column to tpolicy, tquote, tpolicy_history and tquote_history tables','Enhancement','2025-07-12','Tuba Mohsin','Addition','edw_core','tpolicy','bound_by_broker_in','Created new column','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10120','EDW/Datamart Enhancements: Created new column to tpolicy, tquote, tpolicy_history and tquote_history tables','Enhancement','2025-07-12','Tuba Mohsin','Addition','edw_core','tquote','bound_by_broker_in','Created new column','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10120','EDW/Datamart Enhancements: Created new column to tpolicy, tquote, tpolicy_history and tquote_history tables','Enhancement','2025-07-12','Tuba Mohsin','Addition','edw_core','tquote_history','bound_by_user_nm','Created new column','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10120','EDW/Datamart Enhancements: Created new column to tpolicy, tquote, tpolicy_history and tquote_history tables','Enhancement','2025-07-12','Tuba Mohsin','Addition','edw_core','tquote_history','issued_by_user_nm','Created new column','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10120','EDW/Datamart Enhancements: Created new column to tpolicy, tquote, tpolicy_history and tquote_history tables','Enhancement','2025-07-12','Tuba Mohsin','Addition','edw_core','tpolicy_history','transaction_bound_by_user_nm','Created new column','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10120','EDW/Datamart Enhancements: Created new column to tpolicy, tquote, tpolicy_history and tquote_history tables','Enhancement','2025-07-12','Tuba Mohsin','Addition','edw_core','tpolicy_history','transaction_bound_by_user_nm','Created new column','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9997','EDW/Datamart Enhancements: Created new column to tbroker tables','Enhancement','2025-07-12','Tuba Mohsin','Addition','edw_core','tbroker','commercial_or_personal_business_type','Created new column','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9990','EDW/Datamart Enhancements: Metal 7/12 Release Field additions','Enhancement','2025-07-12','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','all_peril_roof_covering_coverage_specified_states_in','Created new column','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9990','EDW/Datamart Enhancements: Metal 7/12 Release Field additions','Enhancement','2025-07-12','Tuba Mohsin','Addition','edw_core','tquote_home_additional_coverage','all_peril_roof_covering_coverage_specified_states_in','Created new column','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9962','EDW/Datamart Enhancements: Created new column to ttask tables','Enhancement','2025-07-12','Architha Gudimalla','Addition','edw_core','ttask','task_id','Created new column','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9842','EDW/Datamart Enhancements: Created new column to tpolicy tables','Enhancement','2025-07-12','Bhaskar Muthyala','Addition','edw_core','tpolicy','billing_paid_in','Created new column','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9793','EDW/Datamart Enhancements: Created new column to tbroker_license tables','Enhancement','2025-07-12','Tuba Mohsin','Addition','edw_core','tbroker_license','license_type','Created new column','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9845','EDW Integrations : Hubspot field additions','Enhancement','2025-07-12','Architha Gudimalla','Addition','edw_integration','customer_hubspot_feed','product_cd','Created new column','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC38713/INC38600/INC38520','IVANS Policy Resent Request','Bug','2025-07-12','Rushin Shah','Datafix','edw_integration','policy_ivans_home_feed','','Resent a few home policies to IVANS','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC38713/INC38600/INC38520','IVANS Policy Resent Request','Bug','2025-07-12','Rushin Shah','Datafix','edw_integration','policy_ivans_auto_feed','','Resent a few auto policies to IVANS','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC38713/INC38600/INC38520','IVANS Policy Resent Request','Bug','2025-07-12','Rushin Shah','Datafix','edw_integration','policy_ivans_pel_feed','','Resent a few PEL policies to IVANS','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9997','Process Improvements : Updated validations to tvalidation_sql','Enhancement','2025-07-12','Tuba Mohsin','Addition','edw_core','tvalidation_sql','','Added validation checks to identify brokers which are not mapped to personal lines or commercial lines','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10219','Process Improvements : Updated validations to tvalidation_sql','Enhancement','2025-07-12','Dinesh Bobbili','Addition','edw_core','tvalidation_sql','','Added validation checks to identify invalid created/bound/issued userid in Metal','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9838','Process Improvements : Updated URL link on release notes HTML','Enhancement','2025-07-12','Alberto Valbuena','Modification','edw_core','','','Updated URL on our standard release notes HTML to point to Vault Solution Center','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9830','EDW/Datamart Enhancements: Created provisional policy for Vault UW Litigation companies','Enhancement','2025-07-12','Bhaskar Muthyala','Addition','edw_integration','claim_policy_search_snapsheet_api','','Created provisional record to support litigation claims in Snapsheet for Commercial Lines','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9830','EDW/Datamart Enhancements: Created provisional policy for Vault UW Litigation companies','Enhancement','2025-07-12','Bhaskar Muthyala','Addition','edw_integration','claim_policy_webhook_snapsheet_api','','Created provisional record to support litigation claims in Snapsheet for Commercial Lines','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9861','Data Fixes: Updated latitude and longitude columns for CO200024575 in Metal and EDW','Bug','2025-07-12','Architha Gudimalla','Datafix','edw_core','thome_location','latitude','Updated missing latitude for CO200024575 in Metal and EDW','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9861','Data Fixes: Updated latitude and longitude columns for CO200024575 in Metal and EDW','Bug','2025-07-12','Architha Gudimalla','Datafix','edw_core','thome_location','longitude','Updated missing latitude for CO200024575 in Metal and EDW','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9861','Data Fixes: Updated latitude and longitude columns for CO200024575 in Metal and EDW','Bug','2025-07-12','Architha Gudimalla','Datafix','edw_core','tquote_home_location','latitude','Updated missing latitude for CO200024575 in Metal and EDW','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9861','Data Fixes: Updated latitude and longitude columns for CO200024575 in Metal and EDW','Bug','2025-07-12','Architha Gudimalla','Datafix','edw_core','tquote_home_location','longitude','Updated missing latitude for CO200024575 in Metal and EDW','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10146','EDW/Datamart Enhancements: Updated um_pd_policy_limit_amt field logic for NC Auto policies','Enhancement','2025-07-12','Architha Gudimalla','Modification','edw_core','tauto_policy_coverage','um_pd_policy_limit_amt','Updatedum_pd_policy_limit_amt field logic in tauto_policy_coverage and tquote_auto_policy_coverage stored procedures for NC Auto policies','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10146','EDW/Datamart Enhancements: Updated um_pd_policy_limit_amt field logic for NC Auto policies','Enhancement','2025-07-12','Architha Gudimalla','Modification','edw_core','tquote_auto_policy_coverage','um_pd_policy_limit_amt','Updatedum_pd_policy_limit_amt field logic in tauto_policy_coverage and tquote_auto_policy_coverage stored procedures for NC Auto policies','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9916','EDW/Datamart Enhancements: Integration of commercial policies with snapsheet to create claims','Enhancement','2025-07-12','Bhaskar Muthyala','Addition','edw_core','','','Created 3 new stored procedures to integrate commercial policies with Snapsheet via webhook to enable creation of commercial claims in Snapsheet','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10016','Data Fixes: Deleted duplicate NFP record','Bug','2025-07-12','Rushin Shah','Datafix','edw_stage','nfp_policy','','Deleted duplicate record associated with NFP policy NFP071243','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10002','Data Fixes: Updated policy number for 2 commercial policies as per user request','Bug','2025-07-12','Bhaskar Muthyala','Datafix','edw_stage','account','policynumber','Updated policy number for 2 commercial policies M5020219 and M5020221 in Metal and EDW','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10002','Data Fixes: Updated policy number for 2 commercial policies as per user request','Bug','2025-07-12','Bhaskar Muthyala','Datafix','edw_stage','accounttransaction','policynumber','Updated policy number for 2 commercial policies M5020219 and M5020221 in Metal and EDW','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10002','Data Fixes: Updated policy number for 2 commercial policies as per user request','Bug','2025-07-12','Bhaskar Muthyala','Datafix','edw_stage','accounttransactionversion','policynumber','Updated policy number for 2 commercial policies M5020219 and M5020221 in Metal and EDW','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8426','Data Fixes: Fixed transactions mapped to 8 closed claims which had negative reserves','Bug','2025-07-12','Bhaskar Muthyala','Datafix','edw_core','tclaim_transaction','','Updated claim transactions associated with 8 closed claims','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8426','Data Fixes: Fixed transactions mapped to 8 closed claims which had negative reserves','Bug','2025-07-12','Bhaskar Muthyala','Datafix','edw_core','tclaim','','Updated claim transactions associated with 8 closed claims','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8426','Data Fixes: Fixed transactions mapped to 8 closed claims which had negative reserves','Bug','2025-07-12','Bhaskar Muthyala','Datafix','edw_core','tclaim_feature','','Updated claim transactions associated with 8 closed claims','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8426','Data Fixes: Fixed transactions mapped to 8 closed claims which had negative reserves','Bug','2025-07-12','Bhaskar Muthyala','Datafix','edw_core','tclaim_summary','','Updated claim transactions associated with 8 closed claims','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD8426','Data Fixes: Fixed transactions mapped to 8 closed claims which had negative reserves','Bug','2025-07-12','Bhaskar Muthyala','Datafix','edw_core','tclaim_feature_summary','','Updated claim transactions associated with 8 closed claims','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9841','Data Fixes: Updated missing product_sk for 2 claims','Bug','2025-07-12','Bhaskar Muthyala','Datafix','edw_core','tclaim','product_sk','Updated missing product_sk for 2 claims 25PRFL954208748 and 25ATFL499819318','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9841','Data Fixes: Updated missing product_sk for 2 claims','Bug','2025-07-12','Bhaskar Muthyala','Datafix','edw_core','tclaim_feature','product_sk','Updated missing product_sk for 2 claims 25PRFL954208748 and 25ATFL499819318','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9841','Data Fixes: Updated missing product_sk for 2 claims','Bug','2025-07-12','Bhaskar Muthyala','Datafix','edw_core','tclaim_summary','product_sk','Updated missing product_sk for 2 claims 25PRFL954208748 and 25ATFL499819318','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9841','Data Fixes: Updated missing product_sk for 2 claims','Bug','2025-07-12','Bhaskar Muthyala','Datafix','edw_core','tclaim_feature_summary','product_sk','Updated missing product_sk for 2 claims 25PRFL954208748 and 25ATFL499819318','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9862','Data Fixes: Roof coverage endorsement updated for one policy','Bug','2025-07-12','Architha Gudimalla','Datafix','edw_core','thome_additional_coverage','roof_coverage_endorsement_wh_in','Updated roof coverage endorsement to null for HO100191352-02.  Data is updated in Metal and EDW.  This is just a onetime update.','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9862','Data Fixes: Roof coverage endorsement updated for one policy','Bug','2025-07-12','Architha Gudimalla','Datafix','edw_core','tquote_home_additional_coverage','roof_coverage_endorsement_wh_in','Updated roof coverage endorsement to null for HO100191352-02.  Data is updated in Metal and EDW.  This is just a onetime update.','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9812','Data Fixes: Fixed premium transactions mapped to 12 expired commercial policies','Bug','2025-07-12','Bhaskar Muthyala','Datafix','edw_stage','AccountTransaction','','Updated various premium related columns to null for 12 expired commercial policies.  Data is updated in Metal and EDW.  This is just a one time update.','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9812','Data Fixes: Fixed premium transactions mapped to 12 expired commercial policies','Bug','2025-07-12','Bhaskar Muthyala','Datafix','edw_stage','AccountTransactionCoveragePremium','','Updated various premium related columns to null for 12 expired commercial policies.  Data is updated in Metal and EDW.  This is just a one time update.','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10168','Data Fixes:  For Metal automated user, updated last_nm to null','Bug','2025-07-12','Architha Gudimalla','Datafix','edw_core','tpolicy_history','transaction_issued_by','Updated last name to null for Metal automated user','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10168','Data Fixes:  For Metal automated user, updated last_nm to null','Bug','2025-07-12','Architha Gudimalla','Datafix','edw_core','tquote_history','created_by_nm','Updated last name to null for Metal automated user','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10168','Data Fixes:  For Metal automated user, updated last_nm to null','Bug','2025-07-12','Architha Gudimalla','Datafix','edw_core','tcommercial_quote_history','created_by_nm','Updated last name to null for Metal automated user','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10168','Data Fixes:  For Metal automated user, updated last_nm to null','Bug','2025-07-12','Architha Gudimalla','Datafix','edw_core','ttask','created_by_nm','Updated last name to null for Metal automated user','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10168','Data Fixes:  For Metal automated user, updated last_nm to null','Bug','2025-07-12','Architha Gudimalla','Datafix','edw_core','ttask','completed_by_nm','Updated last name to null for Metal automated user','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10168','Data Fixes:  For Metal automated user, updated last_nm to null','Bug','2025-07-12','Architha Gudimalla','Datafix','edw_core','ttask','assigned_to_nm','Updated last name to null for Metal automated user','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10168','Data Fixes:  For Metal automated user, updated last_nm to null','Bug','2025-07-12','Architha Gudimalla','Datafix','edw_core','tquote_status_history','user_nm','Updated last name to null for Metal automated user','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10168','Data Fixes:  For Metal automated user, updated last_nm to null','Bug','2025-07-12','Architha Gudimalla','Datafix','edw_core','tquote_transaction_status_history','user_nm','Updated last name to null for Metal automated user','36','Yes','2025-07-14',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10168','Data Fixes:  For Metal automated user, updated last_nm to null','Bug','2025-07-12','Architha Gudimalla','Datafix','edw_core','tnote','user_last_nm','Updated last name to null for Metal automated user','36','Yes','2025-07-14',getdate(),getdate());