INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 07/28/2025 :</span>
<h4 style="margin-top: 0;font-style: italic;color: blue;">This release had 7 enhancements and 10 bug fix tickets.  Release details are as follows. </h4>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; }
        h1, h2 { color: #333; }
        ul { margin: 10px 0; padding-left: 20px; }
    </style>
</head>
<body>
    <h2 style="font-style: italic;">1. EDW/Datamart Enhancements</h2>
    

    <ul>
        <li>Added column - business_flag to tbroker table to indicate commercial lines or personal lines broker</li>
        <li>Added column - location_deleted_in to tpel_location table</li>
        <li>Integration of commercial lines claims into claims model which includes creating following new tables
            <ul>
                <li>tcommercial_claim</li>
                <li>tcommercial_claim_feature</li>
                <li>tcommercial_claim_note</li>
                <li>tcommercial_claim_task</li>
            </ul>
        </li>
        <li>Updated stored procedure for tquote_history table to remove timestamp from loss date</li>
        <li>Updated stored procedure for tquote_transaction_status_history table to fetch data from account transaction table</li>
        <li>Bount_by_broker_in tpolicy and tquote tables was defaulted to No</li>
    </ul>

    <h2 style="font-style: italic;">2. EDW Process Improvements</h2>
    <ul>
        <li>Added data quality checks to identify null state code in productobjectfieldvaluedisplay table</li>
        <li>Added data quality checks to identify brokers writing policies for both commercial and personal lines</li>
    </ul>
    
    <h2 style="font-style: italic;">3. EDW Integrations</h2>
    <h3>a. Workday Enhancements</h3>
    <ul>
        <li>Added following PEL limit related columns to written premium and unearned premium files:</li>
        <ul>
            <li>do_limit_amt</li>
            <li>employment_practices_liability_amt</li>
            <li>pel_limit_amt</li>
            <li>uninsured_underinsured_liability_amt</li>
            <li>uninsured_underinsured_motorist_liability_amt</li>
        </ul>
    <h3>b. IVANS</h3>
    <ul>
        <li>INC39165/INC38852/INC38713: Resent IVANS policies associated with these tickets</li>
        <li>Updated IVANS PEL stored procedure to filter data based on newly created  location_deleted_in</li>
    </ul>

    <h2 style="font-style: italic;">4. Data Fixes</h2>
    <ul>
        <li>AD9957: Fixed transactions mapped to HO200026198 which had a duplicate Fire Marshal Tax premium</li>
        <li>AD10342/AD10401: Updated roof_coverage_endorsement_rv_in for HO200038781-03 and HO100257275-04 in Metal and EDW</li>
        <li>AD10405: Updated windstormOrHailDeductible to null for HO200038140-01 and HO100253766-05 in Metal and EDW</li>
        <li>AD10418: Updated address fields associated with AU100089866-03 in Metal and EDW</li>
    </ul>
</body>
'
,'Yes'
,'2025-07-28'
,getdate()
,getdate()
)
;

INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10318','EDW/Datamart Enhancements: Created new column to tbroker tables','Enhancement','2025-07-26','Architha Gudimalla','Addition','edw_core','tbroker','business_flag','Created new column','37','Yes','2025-07-28',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10325','EDW/Datamart Enhancements: Integration of commercial lines claims into claims model','Enhancement','2025-07-26','Tuba Mohsin','Addition','edw_commercial','tcommercial_claim','','Created new table','37','Yes','2025-07-28',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10325','EDW/Datamart Enhancements: Integration of commercial lines claims into claims model','Enhancement','2025-07-26','Tuba Mohsin','Addition','edw_commercial','tcommercial_claim_feature','','Created new table','37','Yes','2025-07-28',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10325','EDW/Datamart Enhancements: Integration of commercial lines claims into claims model','Enhancement','2025-07-26','Tuba Mohsin','Addition','edw_commercial','tcommercial_claim_note','','Created new table','37','Yes','2025-07-28',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10325','EDW/Datamart Enhancements: Integration of commercial lines claims into claims model','Enhancement','2025-07-26','Tuba Mohsin','Addition','edw_commercial','tcommercial_claim_task','','Created new table','37','Yes','2025-07-28',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10335','EDW/Datamart Enhancements: Created new column to tpel_location table','Enhancement','2025-07-26','Rushin Shah','Addition','edw_core','tpel_location','location_deleted_in','Created new column','37','Yes','2025-07-28',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10301','EDW/Datamart Enhancements: Updated stored procedure for tquote_history table to remove timestamp','Bug','2025-07-26','Dinesh Bobbili','Modification','edw_core','tquote_loss_history','loss_dt','Removed timestamp from loss_dt','37','Yes','2025-07-28',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10309','EDW/Datamart Enhancements: Updated stored procedure for tquote_transaction_status_history to handle batch issues','Bug','2025-07-26','Sandeep Gundreddy','Modification','edw_core','tquote_transaction_status_history','','Modified stage filter to use accounttransaction table','37','Yes','2025-07-28',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10314','EDW/Datamart Enhancements: Defaulted a column in tpolicy and tquote to No','Enhancement','2025-07-26','Sandeep Gundreddy','Addition','edw_core','tpolicy','bound_by_broker_in','Updated default value to No','37','Yes','2025-07-28',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10314','EDW/Datamart Enhancements: Defaulted a column in tpolicy and tquote to No','Enhancement','2025-07-26','Sandeep Gundreddy','Addition','edw_core','tquote','bound_by_broker_in','Updated default value to No','37','Yes','2025-07-28',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC39165/INC38852/INC38713','IVANS Policy Resent Request','Bug','2025-07-26','Rushin Shah','Datafix','edw_integration','policy_ivans_home_feed','','Resent a few home policies to IVANS','37','Yes','2025-07-28',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC39165/INC38852/INC38713','IVANS Policy Resent Request','Bug','2025-07-26','Rushin Shah','Datafix','edw_integration','policy_ivans_auto_feed','','Resent a few auto policies to IVANS','37','Yes','2025-07-28',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC39165/INC38852/INC38713','IVANS Policy Resent Request','Bug','2025-07-26','Rushin Shah','Datafix','edw_integration','policy_ivans_pel_feed','','Resent a few PEL policies to IVANS','37','Yes','2025-07-28',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10341','Process Improvements : Updated validations to tvalidation_sql','Enhancement','2025-07-26','Dinesh Bobbili','Addition','edw_core','tvalidation_sql','','Added validation checks to identify null state code in productobjectfieldvaluedisplay','37','Yes','2025-07-28',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10204','Workday Enhancements: Added PEL limit columns to written premium and unearned premium files','Enhancement','2025-07-26','Rushin Shah','Addition','edw_integration','policy_workday_written_premium_feed','do_limit_amt','Created new column','37','Yes','2025-07-28',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10204','Workday Enhancements: Added PEL limit columns to written premium and unearned premium files','Enhancement','2025-07-26','Rushin Shah','Addition','edw_integration','policy_workday_written_premium_feed','employment_practices_liability_amt','Created new column','37','Yes','2025-07-28',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10204','Workday Enhancements: Added PEL limit columns to written premium and unearned premium files','Enhancement','2025-07-26','Rushin Shah','Addition','edw_integration','policy_workday_written_premium_feed','pel_limit_amt','Created new column','37','Yes','2025-07-28',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10204','Workday Enhancements: Added PEL limit columns to written premium and unearned premium files','Enhancement','2025-07-26','Rushin Shah','Addition','edw_integration','policy_workday_written_premium_feed','uninsured_underinsured_liability_amt','Created new column','37','Yes','2025-07-28',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10204','Workday Enhancements: Added PEL limit columns to written premium and unearned premium files','Enhancement','2025-07-26','Rushin Shah','Addition','edw_integration','policy_workday_written_premium_feed','uninsured_underinsured_motorist_liability_amt','Created new column','37','Yes','2025-07-28',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10204','Workday Enhancements: Added PEL limit columns to written premium and unearned premium files','Enhancement','2025-07-26','Rushin Shah','Addition','edw_integration','policy_workday_unearned_premium_feed','do_limit_amt','Created new column','37','Yes','2025-07-28',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10204','Workday Enhancements: Added PEL limit columns to written premium and unearned premium files','Enhancement','2025-07-26','Rushin Shah','Addition','edw_integration','policy_workday_unearned_premium_feed','employment_practices_liability_amt','Created new column','37','Yes','2025-07-28',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10204','Workday Enhancements: Added PEL limit columns to written premium and unearned premium files','Enhancement','2025-07-26','Rushin Shah','Addition','edw_integration','policy_workday_unearned_premium_feed','pel_limit_amt','Created new column','37','Yes','2025-07-28',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10204','Workday Enhancements: Added PEL limit columns to written premium and unearned premium files','Enhancement','2025-07-26','Rushin Shah','Addition','edw_integration','policy_workday_unearned_premium_feed','uninsured_underinsured_liability_amt','Created new column','37','Yes','2025-07-28',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10204','Workday Enhancements: Added PEL limit columns to written premium and unearned premium files','Enhancement','2025-07-26','Rushin Shah','Addition','edw_integration','policy_workday_unearned_premium_feed','uninsured_underinsured_motorist_liability_amt','Created new column','37','Yes','2025-07-28',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10327','IVANS Integration: Updated PEL stored procedure','Enhancement','2025-07-26','Alberto Valbuena','Modification','edw_integration','policy_ivans_pel_feed','','Updated stored procedure to filter data based on newly created location_deleted_in column','37','Yes','2025-07-28',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10342/AD10401','Data Fixes: Roof coverage endorsement updated for one policy','Bug','2025-07-26','Architha Gudimalla','Datafix','edw_core','thome_additional_coverage','roof_coverage_endorsement_rv_in','Updated roof coverage endorsement to null for HO200038781-03 and HO100257275-04.  Data is updated in Metal and EDW.  This is just a onetime update.','37','Yes','2025-07-28',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10405','Data Fixes: Updated windstormOrHailDeductible to null for HO200038140-01 & HO100253766-05','Bug','2025-07-26','Rushin Shah','Datafix','edw_core','thome_coverage','wind_or_hailstorm_deductible','Updated $0 wind_or_hailstorm_deductible to null in Metal and EDW. This is just a onetime update.','37','Yes','2025-07-28',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10342/AD10401','Data Fixes: Roof coverage endorsement updated for one policy','Bug','2025-07-26','Architha Gudimalla','Datafix','edw_core','tquote_home_additional_coverage','roof_coverage_endorsement_rv_in','Updated roof coverage endorsement to null for HO200038781-03 and HO100257275-04.  Data is updated in Metal and EDW.  This is just a onetime update.','37','Yes','2025-07-28',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD9957','Data Fixes: Fixed transactions associated with policy # HO200026198 which had a duplicate Fire Marshal Tax premium','Bug','2025-07-26','Bhaskar Muthyala','Datafix','edw_core','tpolicy_transaction','','Updated policy transactions associated with policy # HO200026198','37','Yes','2025-07-28',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10418','Data Fixes: Address fields were updated for one policy','Bug','2025-07-26','Tuba Mohsin','Datafix','edw_core','tpolicy','mailing_address_line1','Updated address fields for policy AU100089866-03.  Data is updated in Metal and EDW.  This is just a onetime update.','37','Yes','2025-07-28',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10418','Data Fixes: Address fields were updated for one policy','Bug','2025-07-26','Tuba Mohsin','Datafix','edw_core','tpolicy','mailing_address_city_nm','Updated address fields for policy AU100089866-03.  Data is updated in Metal and EDW.  This is just a onetime update.','37','Yes','2025-07-28',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10418','Data Fixes: Address fields were updated for one policy','Bug','2025-07-26','Tuba Mohsin','Datafix','edw_core','tpolicy','mailing_address_state_cd','Updated address fields for policy AU100089866-03.  Data is updated in Metal and EDW.  This is just a onetime update.','37','Yes','2025-07-28',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10418','Data Fixes: Address fields were updated for one policy','Bug','2025-07-26','Tuba Mohsin','Datafix','edw_core','tpolicy','mailing_address_county_nm','Updated address fields for policy AU100089866-03.  Data is updated in Metal and EDW.  This is just a onetime update.','37','Yes','2025-07-28',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10418','Data Fixes: Address fields were updated for one policy','Bug','2025-07-26','Tuba Mohsin','Datafix','edw_core','tpolicy','mailing_address_zip_cd','Updated address fields for policy AU100089866-03.  Data is updated in Metal and EDW.  This is just a onetime update.','37','Yes','2025-07-28',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10418','Data Fixes: Address fields were updated for one policy','Bug','2025-07-26','Tuba Mohsin','Datafix','edw_core','tpolicy','mailing_address_country_nm','Updated address fields for policy AU100089866-03.  Data is updated in Metal and EDW.  This is just a onetime update.','37','Yes','2025-07-28',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10418','Data Fixes: Address fields were updated for one policy','Bug','2025-07-26','Tuba Mohsin','Datafix','edw_core','tpolicy_insured','primary_insured_in','Updated address fields for policy AU100089866-03.  Data is updated in Metal and EDW.  This is just a onetime update.','37','Yes','2025-07-28',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10418','Data Fixes: Address fields were updated for one policy','Bug','2025-07-26','Tuba Mohsin','Datafix','edw_core','tquote_insured','primary_insured_in','Updated address fields for policy AU100089866-03.  Data is updated in Metal and EDW.  This is just a onetime update.','37','Yes','2025-07-28',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10341','Process Improvements : Updated validations to tvalidation_sql','Enhancement','2025-07-26','Dinesh Bobbili','Addition','edw_core','tvalidation_sql','','Added validation checks to identify brokers writing policies for both commercial and personal lines','37','Yes','2025-07-28',getdate(),getdate());