INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 08/11/2025 :</span>
    <h4 style="margin-top: 0;font-style: italic;color: blue;">This release had 9 enhancements and 2 bug fix tickets.  Release details are as follows.</h4>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; }
        h1, h2 { color: #333; }
        ul { margin: 10px 0; padding-left: 20px; }
    </style>
</head>
<body>

    <h2 style="font-style: italic;">1. EDW/Datamart Enhancements</h2>

    <ul>
        <li>Updated earned_premium_amt and unearned_premium_amt for all mid term transactions from current "pro rata" method to "catch up" method as per request from the finance team in the following tables
            <ul>
                <li>tpolicy_summary</li>
                <li>tpolicy_transaction_summary</li>
                <li>titem_summary</li>
                <li>tinternal_coverage_summary</li>
            </ul>
        </li>
        <li>Added column - driver_status to tpel_driver and tquote_pel_driver tables</li>
        <li>Added column - mine_subsidence_and_sinkhole_coverage_in to thome_additional_coverage and tquote_home_additional_coverage tables</li>
        <li>Standardized cancellation reason in tpolicy_history table specifically when cancellation reason is selected as "Other" then additional details entered by the user will be captured in cancellation sub reason</li>
    </ul>

    <h2 style="font-style: italic;">2. Commercial EDW Enhancements</h2>
    <ul>
        <li>Updated stored procedure for tcommercial_claim and tcommercial_claim_feature table to remove unnecessary tables, columns, and conditions, and to retrieve policy-level details from the tcommercial_policy_history table</li>
        <li>Updated stored procedure for tcommercial_claim_note and tcommercial_claim_task table to remove an unnecessary filtering condition</li>
        <li>Updated stored procedure for tcommercial_quote to revise the condition that derives quote_status, setting it to "Bound" instead of "In Progress" for bound quotes</li>
    </ul>

    <h2 style="font-style: italic;">3. EDW Process Improvements</h2>
    <ul>
        <li>Added data quality checks to monitor written premium and earned premium between summary tables</li>
        <li>Added data quality checks to identify inforce customers with $0 inforce premium</li>
    </ul>

        <h2 style="font-style: italic;">4. Data Fixes</h2>
    <ul>
        <li>AD10485: Updated gate code for HO200066446</li>
        <li>AD10574: Updated subscriber contribution date for HO100033168-05</li>
    </ul>
</body>
'
,'Yes'
,'2025-08-11'
,getdate()
,getdate()
)
;

INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10475','EDW/Datamart Enhancements: Updated earned_premium_amt and unearned_premium_amt for all mid term transactions','Enhancement','2025-08-09','Architha Gudimalla','Modification','edw_core','tpolicy_summary','earned_premium_amt','Updated the calculation from pro-rata method to catch-up method','38','Yes','2025-08-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10475','EDW/Datamart Enhancements: Updated earned_premium_amt and unearned_premium_amt for all mid term transactions','Enhancement','2025-08-09','Architha Gudimalla','Modification','edw_core','tpolicy_summary','earned_net_premium_amt','Updated the calculation from pro-rata method to catch-up method','38','Yes','2025-08-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10475','EDW/Datamart Enhancements: Updated earned_premium_amt and unearned_premium_amt for all mid term transactions','Enhancement','2025-08-09','Architha Gudimalla','Modification','edw_core','tpolicy_summary','unearned_premium_amt','Updated the calculation from pro-rata method to catch-up method','38','Yes','2025-08-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10475','EDW/Datamart Enhancements: Updated earned_premium_amt and unearned_premium_amt for all mid term transactions','Enhancement','2025-08-09','Architha Gudimalla','Modification','edw_core','tpolicy_summary','unearned_net_premium_amt','Updated the calculation from pro-rata method to catch-up method','38','Yes','2025-08-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10475','EDW/Datamart Enhancements: Updated earned_premium_amt and unearned_premium_amt for all mid term transactions','Enhancement','2025-08-09','Architha Gudimalla','Modification','edw_core','titem_summary','earned_premium_amt','Updated the calculation from pro-rata method to catch-up method','38','Yes','2025-08-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10475','EDW/Datamart Enhancements: Updated earned_premium_amt and unearned_premium_amt for all mid term transactions','Enhancement','2025-08-09','Architha Gudimalla','Modification','edw_core','titem_summary','earned_net_premium_amt','Updated the calculation from pro-rata method to catch-up method','38','Yes','2025-08-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10475','EDW/Datamart Enhancements: Updated earned_premium_amt and unearned_premium_amt for all mid term transactions','Enhancement','2025-08-09','Architha Gudimalla','Modification','edw_core','titem_summary','unearned_premium_amt','Updated the calculation from pro-rata method to catch-up method','38','Yes','2025-08-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10475','EDW/Datamart Enhancements: Updated earned_premium_amt and unearned_premium_amt for all mid term transactions','Enhancement','2025-08-09','Architha Gudimalla','Modification','edw_core','titem_summary','unearned_net_premium_amt','Updated the calculation from pro-rata method to catch-up method','38','Yes','2025-08-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10475','EDW/Datamart Enhancements: Updated earned_premium_amt and unearned_premium_amt for all mid term transactions','Enhancement','2025-08-09','Architha Gudimalla','Modification','edw_core','tinternal_coverage_summary','earned_premium_amt','Updated the calculation from pro-rata method to catch-up method','38','Yes','2025-08-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10475','EDW/Datamart Enhancements: Updated earned_premium_amt and unearned_premium_amt for all mid term transactions','Enhancement','2025-08-09','Architha Gudimalla','Modification','edw_core','tinternal_coverage_summary','earned_net_premium_amt','Updated the calculation from pro-rata method to catch-up method','38','Yes','2025-08-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10475','EDW/Datamart Enhancements: Updated earned_premium_amt and unearned_premium_amt for all mid term transactions','Enhancement','2025-08-09','Architha Gudimalla','Modification','edw_core','tinternal_coverage_summary','unearned_premium_amt','Updated the calculation from pro-rata method to catch-up method','38','Yes','2025-08-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10475','EDW/Datamart Enhancements: Updated earned_premium_amt and unearned_premium_amt for all mid term transactions','Enhancement','2025-08-09','Architha Gudimalla','Modification','edw_core','tinternal_coverage_summary','unearned_net_premium_amt','Updated the calculation from pro-rata method to catch-up method','38','Yes','2025-08-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10475','EDW/Datamart Enhancements: Updated earned_premium_amt and unearned_premium_amt for all mid term transactions','Enhancement','2025-08-09','Architha Gudimalla','Modification','edw_core','tpolicy_transaction_summary','earned_premium_amt','Updated the calculation from pro-rata method to catch-up method','38','Yes','2025-08-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10475','EDW/Datamart Enhancements: Updated earned_premium_amt and unearned_premium_amt for all mid term transactions','Enhancement','2025-08-09','Architha Gudimalla','Modification','edw_core','tpolicy_transaction_summary','earned_net_premium_amt','Updated the calculation from pro-rata method to catch-up method','38','Yes','2025-08-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10475','EDW/Datamart Enhancements: Updated earned_premium_amt and unearned_premium_amt for all mid term transactions','Enhancement','2025-08-09','Architha Gudimalla','Modification','edw_core','tpolicy_transaction_summary','unearned_premium_amt','Updated the calculation from pro-rata method to catch-up method','38','Yes','2025-08-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10475','EDW/Datamart Enhancements: Updated earned_premium_amt and unearned_premium_amt for all mid term transactions','Enhancement','2025-08-09','Architha Gudimalla','Modification','edw_core','tpolicy_transaction_summary','unearned_net_premium_amt','Updated the calculation from pro-rata method to catch-up method','38','Yes','2025-08-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10466','EDW/Datamart Enhancements: Created new column to tpel_location table','Enhancement','2025-08-09','Tuba Mohsin','Addition','edw_core','tpel_driver','driver_status','Created new column','38','Yes','2025-08-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10466','EDW/Datamart Enhancements: Created new column to tpel_location table','Enhancement','2025-08-09','Tuba Mohsin','Addition','edw_core','tquote_pel_driver','driver_status','Created new column','38','Yes','2025-08-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10466','EDW/Datamart Enhancements: Created new column to tpel_location table','Enhancement','2025-08-09','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','mine_subsidence_and_sinkhole_coverage_in','Created new column','38','Yes','2025-08-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10466','EDW/Datamart Enhancements: Created new column to tpel_location table','Enhancement','2025-08-09','Tuba Mohsin','Addition','edw_core','tquote_home_additional_coverage','mine_subsidence_and_sinkhole_coverage_in','Created new column','38','Yes','2025-08-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10198','EDW/Datamart Enhancements: Standardized cancellation reason in tpolicy_history table','Enhancement','2025-08-09','Bhaskar Muthyala','Modification','edw_core','tpolicy_history','cancellation_sub_reason_desc','When cancellation reason is selected as "OTHER" in Metal UI, same will be captured in cancellation_reason_desc column and any additional details manually entered by the user will be captured in cancellation_sub_reason_desc column.','38','Yes','2025-08-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC39399','IVANS Policy Resent Request','Bug','2025-08-09','Rushin Shah','Datafix','edw_integration','policy_ivans_home_feed','','Resent a few home policies to IVANS','38','Yes','2025-08-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC39399','IVANS Policy Resent Request','Bug','2025-08-09','Rushin Shah','Datafix','edw_integration','policy_ivans_auto_feed','','Resent a few auto policies to IVANS','38','Yes','2025-08-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC39399','IVANS Policy Resent Request','Bug','2025-08-09','Rushin Shah','Datafix','edw_integration','policy_ivans_pel_feed','','Resent a few PEL policies to IVANS','38','Yes','2025-08-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10341','Process Improvements : Updated validations to tvalidation_sql','Enhancement','2025-08-09','Architha Gudimalla','Addition','edw_core','tvalidation_sql','','Added data quality checks to monitor written premium and earned premium between summary tables','38','Yes','2025-08-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10568','Process Improvements : Updated validations to tvalidation_sql','Enhancement','2025-08-09','Rushin Shah','Addition','edw_core','tvalidation_sql','','Added data quality checks to identify inforce customers with $0 inforce premium','38','Yes','2025-08-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10537','Commercial EDW Enhancements: Updated stored procedure for tcommercial_claim and tcommercial_claim_feature to remove unnecessary tables, columns, and conditions','Enhancement','2025-08-09','Yunus Mohammed','Modification','edw_commercial','tcommercial_claim','','Updated stored procedure to remove unnecessary tables, columns, and conditions','38','Yes','2025-08-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10537','Commercial EDW Enhancements: Updated stored procedure for tcommercial_claim and tcommercial_claim_feature to remove unnecessary tables, columns, and conditions','Enhancement','2025-08-09','Yunus Mohammed','Modification','edw_commercial','tcommercial_claim_feature','','Updated stored procedure to remove unnecessary tables, columns, and conditions','38','Yes','2025-08-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10570','Commercial EDW Enhancements: Updated stored procedure for tcommercial_claim_note and tcommercial_claim_task table to remove an unnecessary filtering condition','Enhancement','2025-08-09','Yunus Mohammed','Modification','edw_commercial','tcommercial_claim_note','','Updated stored procedure to remove unnecessary filtering conditions','38','Yes','2025-08-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10570','Commercial EDW Enhancements: Updated stored procedure for tcommercial_claim_note and tcommercial_claim_task table to remove an unnecessary filtering condition','Enhancement','2025-08-09','Yunus Mohammed','Modification','edw_commercial','tcommercial_claim_task','','Updated stored procedure to remove unnecessary filtering conditions','38','Yes','2025-08-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10493','Commercial EDW Enhancements: Updated stored procedure for tcommercial_quote to revise the condition that derives quote_status','Enhancement','2025-08-09','Yunus Mohammed','Modification','edw_commercial','tcommercial_quote','quote_status','Updated stored procedure to set quote_status to Bound instead of In Progress for bound quotes','38','Yes','2025-08-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10485','Data Fixes: Backfilling of Wildfire protection fields','Enhancement','2025-08-09','Architha Gudimalla','Addition','edw_core','thome_additional_coverage','gate_code','Backfilling data for gate code wildfire protection fields based on information received from manual forms.','38','Yes','2025-08-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10485','Data Fixes: Backfilling of Wildfire protection fields','Enhancement','2025-08-09','Architha Gudimalla','Addition','edw_core','tquote_home_additional_coverage','gate_code','Backfilling data for gate code wildfire protection fields based on information received from manual forms.','38','Yes','2025-08-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10574','Data Fixes: Update subscriber contribution end date in metal for a policy','Bug','2025-07-26','Tuba Mohsin','Datafix','edw_core','tpolicy_insured','subscriber_contribution_end_dt','Updated subscriber contribution end date for HO100033168-05. Data is updated in Metal and will be updated in EDW during next full refresh. This is just a onetime update.','38','Yes','2025-08-11',getdate(),getdate());