INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 08/25/2025 :</span>
<h4 style="margin-top: 0;font-style: italic;color: blue;">This release had 6 enhancements and 7 bug fix tickets.  Release details are as follows. </h4>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; }
        h1, h2 { color: #333; }
        ul { margin: 10px 0; padding-left: 20px; }
    </style>
</head>
<body>
    <h2 style="font-style: italic;">1. EDW/Datamart Enhancements</h2>
    

    <ul>
        <li>Added column - defense_coverage_within_limits_in to thome_additional_coverage and tquote_home_additional_coverage tables</li>
        <li>Added column - wind_sublimit_in to thome_additional_coverage and tquote_home_additional_coverage tables</li>
        <li>Added column - wind_sublimit_value_amt to thome_additional_coverage and tquote_home_additional_coverage tables</li>
        <li>Added column - first_billing_payment_dt to tpolicy table</li>
        <li>Updated stored procedure for tproducer table to accurately populate producer status to match to Metal UI</li>
        <li>Updated stored procedure for tadditional_interest table to accurately populate transaction_date and transaction_effective_date</li>
    </ul>

    <h2 style="font-style: italic;">2. EDW Process Improvements</h2>
    <ul>
        <li>Added data quality checks to monitor premium differences between tpolicy_summary and tinternal_coverage_summary</li>
        <li>Added data quality checks to monitor premium differences between tpolicy_summary and tpolicy_transaction_summary</li>
    </ul>
    
    <h2 style="font-style: italic;">3. EDW Integrations</h2>
    <h3>a. Hubspot</h3>
    <ul>
        <li>Updated stored procedure for broker_hubspot_feed to filter data only for personal lines</li>
    </ul>
    <h3>b. IVANS</h3>
    <ul>
        <li>INC39801/INC39799: Resent IVANS policies associated with these tickets</li>
    </ul>

    <h2 style="font-style: italic;">4. Data Fixes</h2>
    <ul>
        <li>INC39468 : Updated Subscriber Contribution Date for HO100033168-05 and EX100033179-05 policies</li>
        <li>AD10616 : Fixed negative premium associated with 2 NY bound policies HO200073843 and HO200077788 in Metal and EDW</li>
        <li>AD10693: Updated hurricaneDeductible to null for HO100083513-01 in Metal and EDW</li>
        <li>AD10694: Updated internal coverage category from "Tax" to "State Tax" for 3 policies in Metal and EDW</li>
        <li>AD10589 : Updated broker ids on 3 commercial policies and 20 commercial quotes in Metal and EDW</li>
    </ul>
</body>
'
,'Yes'
,'2025-08-22'
,getdate()
,getdate()
)
;

INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10613','EDW/Datamart Enhancements: Created new column to thome_additional_coverage table','Enhancement','2025-08-23','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','defense_coverage_within_limits_in','Created new column','39','Yes','2025-08-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10613','EDW/Datamart Enhancements: Created new column to thome_additional_coverage table','Enhancement','2025-08-23','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','wind_sublimit_in','Created new column','39','Yes','2025-08-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10613','EDW/Datamart Enhancements: Created new column to thome_additional_coverage table','Enhancement','2025-08-23','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','wind_sublimit_value_amt','Created new column','39','Yes','2025-08-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10613','EDW/Datamart Enhancements: Created new column to tquote_home_additional_coverage table','Enhancement','2025-08-23','Tuba Mohsin','Addition','edw_core','tquote_home_additional_coverage','defense_coverage_within_limits_in','Created new column','39','Yes','2025-08-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10613','EDW/Datamart Enhancements: Created new column to tquote_home_additional_coverage table','Enhancement','2025-08-23','Tuba Mohsin','Addition','edw_core','tquote_home_additional_coverage','wind_sublimit_in','Created new column','39','Yes','2025-08-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10613','EDW/Datamart Enhancements: Created new column to tquote_home_additional_coverage table','Enhancement','2025-08-23','Tuba Mohsin','Addition','edw_core','tquote_home_additional_coverage','wind_sublimit_value_amt','Created new column','39','Yes','2025-08-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10561','EDW/Datamart Enhancements: Created new column to tpolicy table','Enhancement','2025-08-23','Bhaskar Muthyala','Addition','edw_core','tpolicy','first_billing_payment_dt','Created new column','39','Yes','2025-08-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC39801/INC39799','IVANS Policy Resent Request','Bug','2025-08-23','Rushin Shah','Datafix','edw_integration','policy_ivans_home_feed','','Resent a few home policies to IVANS','39','Yes','2025-08-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC39801/INC39799','IVANS Policy Resent Request','Bug','2025-08-23','Rushin Shah','Datafix','edw_integration','policy_ivans_auto_feed','','Resent a few auto policies to IVANS','39','Yes','2025-08-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC39801/INC39799','IVANS Policy Resent Request','Bug','2025-08-23','Rushin Shah','Datafix','edw_integration','policy_ivans_pel_feed','','Resent a few PEL policies to IVANS','39','Yes','2025-08-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10426','Process Improvements : Updated validations to tvalidation_sql','Enhancement','2025-08-23','Dinesh Bobbili','Addition','edw_core','tvalidation_sql','','Added data quality checks to monitor premium differences between tpolicy_summary and tinternal_coverage_summary','39','Yes','2025-08-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10426','Process Improvements : Updated validations to tvalidation_sql','Enhancement','2025-08-23','Dinesh Bobbili','Addition','edw_core','tvalidation_sql','','Added data quality checks to monitor premium differences between tpolicy_summary and tpolicy_transaction_summary','39','Yes','2025-08-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10706','EDW/Datamart Enhancements: Updated stored procedure for tproducer table to accurately populate producer status to match to Metal UI','Enhancement','2025-08-23','Architha Gudimalla','Modification','edw_core','tproducer','producer_status','Updated stored procedure to use broker status from Metal table instead of using a derived logic','39','Yes','2025-08-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10684','EDW/Datamart Enhancements: Updated stored procedure for tadditional_interest table to accurately populate transaction_date and transaction_effective_date','Enhancement','2025-08-23','Dinesh Bobbili','Modification','edw_core','tadditional_interest','transaction_effective_dt','Updated stored procedure to fix the mapping issue for transaction_effective_dt and transaction_dt','39','Yes','2025-08-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10684','EDW/Datamart Enhancements: Updated stored procedure for tadditional_interest table to accurately populate transaction_date and transaction_effective_date','Enhancement','2025-08-23','Dinesh Bobbili','Modification','edw_core','tadditional_interest','transaction_dt','Updated stored procedure to fix the mapping issue for transaction_effective_dt and transaction_dt','39','Yes','2025-08-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10269','EDW External Integrations : Updated stored procedure for hubspot broker feed','Enhancement','2025-08-23','Architha Gudimalla','Modification','edw_commercial','broker_hubspot_feed','','Updated stored procedure for hubspot broker feed to filter data only for personal lines','39','Yes','2025-08-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC39468','Data Fixes: Update subscriber contribution end date in metal for HO100033168-05 and EX100033179-05','Bug','2025-08-23','Rushin Shah','Datafix','edw_core','tpolicy_insured','subscriber_contribution_end_dt','Updated subscriber contribution end date for HO100033168-05 and EX100033179-05. Data is updated in Metal and will be updated in EDW during next full refresh. This is just a onetime update.','39','Yes','2025-08-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC39468','Data Fixes: Update subscriber contribution end date in metal for HO100033168-05 and EX100033179-05','Bug','2025-08-23','Rushin Shah','Datafix','edw_core','tquote_policy_insured','subscriber_contribution_end_dt','Updated subscriber contribution end date for HO100033168-05 and EX100033179-05. Data is updated in Metal and will be updated in EDW during next full refresh. This is just a onetime update.','39','Yes','2025-08-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10616','Data Fixes: Fixed negative premium associated with 2 NY bound policies','Bug','2025-08-23','Architha Gudimalla','Datafix','edw_core','tpolicy_transaction','','Updated stats associated with 2 NY bound policies HO200073843 and HO200077788 in Metal and EDW. This is just a onetime update.','39','Yes','2025-08-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10693','Data Standardization : Update hurricane_deductible with $0 to null','Bug','2025-08-23','Rushin Shah','Datafix','edw_core','thome_coverage','hurricane_deductible','Updated $0 hurricane_deductible to null for HO100083513-01 in Metal and EDW. This is just a onetime update.','39','Yes','2025-08-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10693','Data Standardization : Update hurricane_deductible with $0 to null','Bug','2025-08-23','Rushin Shah','Datafix','edw_core','tquote_home_coverage','hurricane_deductible','Updated $0 hurricane_deductible to null for HO100083513-01 in Metal and EDW. This is just a onetime update.','39','Yes','2025-08-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10694','Data Fixes: Fixed internal coverage category from "Tax" to "State Tax" for 3 policies','Bug','2025-08-23','Rushin Shah','Datafix','edw_stage','AccountTransactionTaxAndFee','Type','Updated internal coverage from Tax to State Tax for 3 policies in Metal. This is just a onetime update.','39','Yes','2025-08-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10694','Data Fixes: Fixed internal coverage category from "Tax" to "State Tax" for 3 policies','Bug','2025-08-23','Rushin Shah','Datafix','edw_stage','AccountPremiumTaxAndFee','Type','Updated internal coverage from Tax to State Tax for 3 policies in Metal. This is just a onetime update.','39','Yes','2025-08-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10589','Data Fixes: Updated broker ids on 3 commercial policies and 20 commercial quotes','Bug','2025-08-23','Architha Gudimalla','Datafix','edw_commercial','tcommercial_policy','broker_id','Updated broker ids on 3 commercial policies and 20 commercial quotes in Metal and EDW. This is just a onetime update.','39','Yes','2025-08-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10589','Data Fixes: Updated broker ids on 3 commercial policies and 20 commercial quotes','Bug','2025-08-23','Architha Gudimalla','Datafix','edw_commercial','tcommercial_policy_history','broker_id','Updated broker ids on 3 commercial policies and 20 commercial quotes in Metal and EDW. This is just a onetime update.','39','Yes','2025-08-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10589','Data Fixes: Updated broker ids on 3 commercial policies and 20 commercial quotes','Bug','2025-08-23','Architha Gudimalla','Datafix','edw_commercial','tcommercial_policy_history','broker_sk','Updated broker ids on 3 commercial policies and 20 commercial quotes in Metal and EDW. This is just a onetime update.','39','Yes','2025-08-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10589','Data Fixes: Updated broker ids on 3 commercial policies and 20 commercial quotes','Bug','2025-08-23','Architha Gudimalla','Datafix','edw_commercial','tcommercial_quote','broker_id','Updated broker ids on 3 commercial policies and 20 commercial quotes in Metal and EDW. This is just a onetime update.','39','Yes','2025-08-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10589','Data Fixes: Updated broker ids on 3 commercial policies and 20 commercial quotes','Bug','2025-08-23','Architha Gudimalla','Datafix','edw_commercial','tcommercial_quote_history','broker_id','Updated broker ids on 3 commercial policies and 20 commercial quotes in Metal and EDW. This is just a onetime update.','39','Yes','2025-08-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10589','Data Fixes: Updated broker ids on 3 commercial policies and 20 commercial quotes','Bug','2025-08-23','Architha Gudimalla','Datafix','edw_commercial','tcommercial_quote_history','broker_sk','Updated broker ids on 3 commercial policies and 20 commercial quotes in Metal and EDW. This is just a onetime update.','39','Yes','2025-08-25',getdate(),getdate());