INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 09/08/2025 :</span>
    <h4 style="margin-top: 0;font-style: italic;color: blue;">This release had 5 enhancements and 5 bug fix tickets.  Release details are as follows.</h4>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; }
        h1, h2 { color: #333; }
        ul { margin: 10px 0; padding-left: 20px; }
    </style>
</head>
<body>

    <h2 style="font-style: italic;">1. EDW/Datamart Enhancements</h2>

    <ul>
        <li>Added column - ncrb_premium_amt to tpolicy_transaction and tquote_transaction tables</li>
        <li>Added column - ncrb_annual_premium_amt to tpolicy_transaction and tquote_transaction tables</li>
        <li>Updated stored procedure for tauto_vehicle_coverage to accurately populate vehicle_deleted_in (specifically deleted on renewal)</li>
        <li>Updated stored procedure for tauto_driver to accurately populate driver_deleted_in (specifically deleted on renewal)</li>
        <li>Updated stored procedure for tproducer table to accurately populate producer status to match to Metal UI</li>
    </ul>

    <h2 style="font-style: italic;">2. EDW Integrations</h2>
    <h3>a. Metal</h3>
    <ul>
        <li>Created a new table broker_claim_metal_feed which captures rolling 1 year loss ratio for each broker id which would update the brokerage table in Metal</li>
    </ul>

    <h3>b. IVANS</h3>
    <ul>
        <li>INC38990: Resent IVANS policies associated with these tickets</li>
    </ul>

    <h2 style="font-style: italic;">3. Data Fixes</h2>
    <ul>
        <li>AD10589 : Updated broker ids on 3 commercial policies and 20 commercial quotes in Metal and EDW</li>
        <li>INC39883 : Updated BCEGCreditPercent for one policy HO200037341-06</li>
        <li>INC39727 : Updated reported incidents for one policy EX100071408-04</li>
        <li>AD10814 : Updated vehicle_deleted_in to Y for 8 auto policies that had duplicate VIN</li>
    </ul>

</body>
'
,'Yes'
,'2025-09-08'
,getdate()
,getdate()
)
;



-- tedw_release_note
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10523','EDW/Datamart Enhancements: Created new column to tpolicy_transaction and tquote_transaction table','Enhancement','2025-09-06','Rushin Shah','Addition','edw_core','tpolicy_transaction','ncrb_premium_amt','Created new column','40','Yes','2025-09-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10523','EDW/Datamart Enhancements: Created new column to tpolicy_transaction and tquote_transaction table','Enhancement','2025-09-06','Rushin Shah','Addition','edw_core','tquote_transaction','ncrb_premium_amt','Created new column','40','Yes','2025-09-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10523','EDW/Datamart Enhancements: Created new column to tpolicy_transaction and tquote_transaction table','Enhancement','2025-09-06','Rushin Shah','Addition','edw_core','tpolicy_transaction','ncrb_annual_premium_amt','Created new column','40','Yes','2025-09-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10523','EDW/Datamart Enhancements: Created new column to tpolicy_transaction and tquote_transaction table','Enhancement','2025-09-06','Rushin Shah','Addition','edw_core','tquote_transaction','ncrb_annual_premium_amt','Created new column','40','Yes','2025-09-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10815','EDW/Datamart Enhancements: Updated stored procedure for tauto_vehicle_coverage to accurately populate vehicle_deleted_in','Enhancement','2025-09-06','Bhaskar Muthyala','Modification','edw_core','tauto_vehicle_coverage','vehicle_deleted_in','Updated stored procedure to accurately populate vehicle_deleted_in (specifically deleted on renewal)','40','Yes','2025-09-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10815','EDW/Datamart Enhancements: Updated stored procedure for tauto_vehicle_coverage to accurately populate vehicle_deleted_in','Enhancement','2025-09-06','Bhaskar Muthyala','Modification','edw_core','tquote_auto_vehicle_coverage','vehicle_deleted_in','Updated stored procedure to accurately populate vehicle_deleted_in (specifically deleted on renewal)','40','Yes','2025-09-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10855','EDW/Datamart Enhancements: Updated stored procedure for tauto_driver to accurately populate driver_deleted_in','Enhancement','2025-09-06','Bhaskar Muthyala','Modification','edw_core','tauto_driver','driver_deleted_in','Updated stored procedure to accurately populate driver_deleted_in (specifically deleted on renewal)','40','Yes','2025-09-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC38990','IVANS Policy Resent Request','Bug','2025-09-06','Rushin Shah','Datafix','edw_integration','policy_ivans_home_feed','','Resent a few home policies to IVANS','40','Yes','2025-09-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC38990','IVANS Policy Resent Request','Bug','2025-09-06','Rushin Shah','Datafix','edw_integration','policy_ivans_auto_feed','','Resent a few auto policies to IVANS','40','Yes','2025-09-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC38990','IVANS Policy Resent Request','Bug','2025-09-06','Rushin Shah','Datafix','edw_integration','policy_ivans_pel_feed','','Resent a few PEL policies to IVANS','40','Yes','2025-09-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10813','EDW/Datamart Enhancements: Updated stored procedure for tproducer table to accurately populate producer status to match to Metal UI','Enhancement','2025-09-06','Dinesh Bobbili','Modification','edw_core','tproducer','producer_status','Updated stored procedure to use broker status from Metal table instead of using a derived logic','40','Yes','2025-09-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10814','Data Fixes : Updated vehicle_deleted_in to Y for 8 auto policies that had duplicate VIN','Bug','2025-09-06','Yunus Mohammed','Datafix','edw_core','tauto_vehicle','vehicle_deleted_in','Update vehicle_deleted_in to Y for 8 auto policies with duplicate VIN in EDW. This is just a onetime update.','40','Yes','2025-09-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10700','EDW Integrations : Created new table to capture 1Yr loss ratio for each broker to feed into brokerage table in Metal','Enhancement','2025-09-06','Bhaskar Muthyala','Addition','edw_integration','broker_claim_metal_feed','','Created new table','40','Yes','2025-09-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10788','Data Fixes: Updated BCEGCreditPercent for HO200037341-06','Bug','2025-09-06','Tuba Mohsin','Datafix','edw_core','thome_coverage','bceg_credit_pc','Updated BCEG Credit Percent for 1 policy in Metal and EDW','40','Yes','2025-09-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10788','Data Fixes: Updated BCEGCreditPercent for HO200037341-06','Bug','2025-09-06','Tuba Mohsin','Datafix','edw_core','tquote_home_coverage','bceg_credit_pc','Updated BCEG Credit Percent for 1 policy in Metal and EDW','40','Yes','2025-09-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10589','Data Fixes: Updated broker ids on 3 commercial policies and 20 commercial quotes','Bug','2025-09-06','Architha Gudimalla','Datafix','edw_commercial','tcommercial_policy','broker_id','Updated broker ids on 3 commercial policies and 20 commercial quotes in Metal and EDW. This is just a onetime update.','40','Yes','2025-09-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10589','Data Fixes: Updated broker ids on 3 commercial policies and 20 commercial quotes','Bug','2025-09-06','Architha Gudimalla','Datafix','edw_commercial','tcommercial_policy_history','broker_id','Updated broker ids on 3 commercial policies and 20 commercial quotes in Metal and EDW. This is just a onetime update.','40','Yes','2025-09-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10589','Data Fixes: Updated broker ids on 3 commercial policies and 20 commercial quotes','Bug','2025-09-06','Architha Gudimalla','Datafix','edw_commercial','tcommercial_policy_history','broker_sk','Updated broker ids on 3 commercial policies and 20 commercial quotes in Metal and EDW. This is just a onetime update.','40','Yes','2025-09-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10589','Data Fixes: Updated broker ids on 3 commercial policies and 20 commercial quotes','Bug','2025-09-06','Architha Gudimalla','Datafix','edw_commercial','tcommercial_quote','broker_id','Updated broker ids on 3 commercial policies and 20 commercial quotes in Metal and EDW. This is just a onetime update.','40','Yes','2025-09-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10589','Data Fixes: Updated broker ids on 3 commercial policies and 20 commercial quotes','Bug','2025-09-06','Architha Gudimalla','Datafix','edw_commercial','tcommercial_quote_history','broker_id','Updated broker ids on 3 commercial policies and 20 commercial quotes in Metal and EDW. This is just a onetime update.','40','Yes','2025-09-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10589','Data Fixes: Updated broker ids on 3 commercial policies and 20 commercial quotes','Bug','2025-09-06','Architha Gudimalla','Datafix','edw_commercial','tcommercial_quote_history','broker_sk','Updated broker ids on 3 commercial policies and 20 commercial quotes in Metal and EDW. This is just a onetime update.','40','Yes','2025-09-08',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10834','Data Fixes: Drop reported incidents on EX100071408-04','Bug','2025-09-06','Architha Gudimalla','Datafix','edw_stage','AccountObject','',' Drop reported incidents on EX100071408-04 from metal.  This is just a onetime update.','40','Yes','2025-09-08',getdate(),getdate());