INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 09/22/2025 :</span>
    <h4 style="margin-top: 0;font-style: italic;color: blue;">This release had 15 enhancements and 11 bug fix tickets.  Release details are as follows.</h4>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; }
        h1, h2 { color: #333; }
        ul { margin: 10px 0; padding-left: 20px; }
    </style>
</head>
<body>
    <h2 style="font-style: italic;">1. EDW/Datamart Enhancements</h2>
    <ul>
        <li>Added column renewal_quote_in to tquote table</li>
        <li>Added column renewal_quote_review_start_dt to tquote table</li>
        <li>Created a new stored procedure to update email address in tcustomer table</li>
        <li>Created a new stored procedure to update transaction_status in tpolicy_history table (specifically to address reversed/reversal transactions)</li>
        <li>Renamed column ncrb_premium_amt to state_premium_amt in tpolicy_transaction and tquote_transaction tables</li>
        <li>Renamed column ncrb_annual_premium_amt to state_annual_premium_amt in tpolicy_transaction and tquote_transaction tables</li>
        <li>Updated stored procedure for tadditional_interest to accurately populate additional_interest_deleted_in (specifically deleted on renewal)</li>
        <li>Updated stored procedure for tcollection_class_type to accurately populate class_deleted_in (specifically deleted on renewal)</li>
        <li>Updated stored procedure for tcollection_scheduled_item to accurately populate scheduled_item_deleted_in (specifically deleted on renewal)</li>
        <li>Updated stored procedure for thome_additional_coverage to accurately populate extended_liability_loc_ct (specifically deleted on renewal)</li>
        <li>Updated stored procedure for tpel_location to accurately populate location_deleted_in (specifically deleted on renewal)</li>
        <li>Updated stored procedure for tpel_vehicle to accurately populate vehicle_deleted_in (specifically deleted on renewal)</li>
        <li>Updated stored procedure for tpel_watercraft to accurately populate watercraft_deleted_in (specifically deleted on renewal)</li>
    </ul>
    <h2 style="font-style: italic;">2. EDW Integrations</h2>
    <h3>a. Hubspot</h3>
    <ul>
        <li>Updated stored procedure for customer_hubspot_feed to add insured_nm</li>
        <li>Updated stored procedure for customer_hubspot_feed to retrieve the latest email from the tcustomer table</li>
        <li>Updated stored procedure for customer_hubspot_feed and quote_hubspot_feed to apply the monoline_in fix</li>
    </ul>
    <h3>b. IVANS</h3>
    <ul>
        <li>IVANS Collections Feed goes live</li>
        <li>Updated IVANS Prod endpoint to point to Azure URL</li>
        <li>Updated stored procedure logic associated with medical payments limit amount in the auto coverages column</li>
        <li>Resent 14 auto policies affected as part of the vehicle_deleted_in fix</li>
        <li>INC40122/INC39981: Resent IVANS policies associated with these tickets</li>
    </ul>
    
    <h3>c. CLUE</h3>
    <ul>
        <li>Updated CLUE property stored procedure to create and send a new record when claim status changes</li>
    </ul>
    <h2 style="font-style: italic;">3. EDW Process Improvements</h2>
    <ul>
        <li>Added data quality checks to monitor issues associated with HONK feed</li>
        <li>Added data quality checks to monitor issues associated with current carrier feed</li>
    </ul>
    <h2 style="font-style: italic;">4. Data Fixes</h2>
    <ul>
        <li>INC34009 : Updated roof_covering_full_reconstruction_cost_coverage_in to NULL when values are either blank & 0</li>
        <li>AD10985 : Update stored procedure logic for tower_deleted_in in tcommercial_policy_tower table to reflect Yes or No instead of 0 or 1</li>
    </ul>
</body>
'
,'Yes'
,'2025-09-22'
,getdate()
,getdate()
)
;
-- tedw_release_note
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10947','EDW/Datamart Enhancements: Renamed 2 columns in tpolicy_transaction and tquote_transaction table','Enhancement','2025-09-20','Rushin Shah','Modification','edw_core','tpolicy_transaction','state_premium_amt','Renamed column from ncrb_premium_amt to state_premium_amt','41','Yes','2025-09-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10947','EDW/Datamart Enhancements: Renamed 2 columns in tpolicy_transaction and tquote_transaction table','Enhancement','2025-09-20','Rushin Shah','Modification','edw_core','tquote_transaction','state_premium_amt','Renamed column from ncrb_premium_amt to state_premium_amt','41','Yes','2025-09-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10947','EDW/Datamart Enhancements: Renamed 2 columns in tpolicy_transaction and tquote_transaction table','Enhancement','2025-09-20','Rushin Shah','Modification','edw_core','tpolicy_transaction','state_annual_premium_amt','Renamed column from ncrb_annual_premium_amt to state_annual_premium_amt','41','Yes','2025-09-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10947','EDW/Datamart Enhancements: Renamed 2 columns in tpolicy_transaction and tquote_transaction table','Enhancement','2025-09-20','Rushin Shah','Modification','edw_core','tquote_transaction','state_annual_premium_amt','Renamed column from ncrb_annual_premium_amt to state_annual_premium_amt','41','Yes','2025-09-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10965','EDW/Datamart Enhancements: Updated stored procedure for tadditional_interest to accurately populate additional_interest_deleted_in','Enhancement','2025-09-20','Bhaskar Muthyala','Modification','edw_core','tadditional_interest','additional_interest_deleted_in','Updated stored procedure to accurately populate additional_interest_deleted_in (specifically deleted on renewal)','41','Yes','2025-09-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10815','EDW/Datamart Enhancements: Updated stored procedure for tcollection_class_type to accurately populate class_deleted_in','Enhancement','2025-09-20','Bhaskar Muthyala','Modification','edw_core','tcollection_class_type','class_deleted_in','Updated stored procedure to accurately populate class_deleted_in (specifically deleted on renewal)','41','Yes','2025-09-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10855','EDW/Datamart Enhancements: Updated stored procedure for tcollection_scheduled_item to accurately populate scheduled_item_deleted_in','Enhancement','2025-09-20','Bhaskar Muthyala','Modification','edw_core','tcollection_scheduled_item','scheduled_item_deleted_in','Updated stored procedure to accurately populate scheduled_item_deleted_in (specifically deleted on renewal)','41','Yes','2025-09-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10855','EDW/Datamart Enhancements: Updated stored procedure for thome_additional_coverage to accurately populate extended_liability_loc_ct','Enhancement','2025-09-20','Bhaskar Muthyala','Modification','edw_core','thome_additional_coverage','extended_liability_loc_ct','Updated stored procedure to accurately populate extended_liability_loc_ct (specifically deleted on renewal)','41','Yes','2025-09-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10855/AD10905','EDW/Datamart Enhancements: Updated stored procedure for tpel_location to accurately populate location_deleted_in','Enhancement','2025-09-20','Bhaskar Muthyala','Modification','edw_core','tpel_location','location_deleted_in','Updated stored procedure to accurately populate location_deleted_in (specifically deleted on renewal)','41','Yes','2025-09-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10855/AD10899','EDW/Datamart Enhancements: Updated stored procedure for tpel_vehicle to accurately populate vehicle_deleted_in','Enhancement','2025-09-20','Bhaskar Muthyala','Modification','edw_core','tpel_vehicle','vehicle_deleted_in','Updated stored procedure to accurately populate vehicle_deleted_in (specifically deleted on renewal)','41','Yes','2025-09-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10855/AD10904','EDW/Datamart Enhancements: Updated stored procedure for tpel_watercraft to accurately populate watercraft_deleted_in','Enhancement','2025-09-20','Bhaskar Muthyala','Modification','edw_core','tpel_watercraft','watercraft_deleted_in','Updated stored procedure to accurately populate watercraft_deleted_in (specifically deleted on renewal)','41','Yes','2025-09-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10855/AD10900','EDW/Datamart Enhancements: Updated stored procedure for tpel_driver to accurately populate driver_deleted_in','Enhancement','2025-09-20','Bhaskar Muthyala','Modification','edw_core','tpel_driver','driver_deleted_in','Updated stored procedure to accurately populate driver_deleted_in (specifically deleted on renewal)','41','Yes','2025-09-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10892','EDW/Datamart Enhancements: Created new column to tquote tables','Enhancement','2025-09-20','Bhaskar Muthyala','Addition','edw_core','tquote','renewal_quote_in','Created new column','41','Yes','2025-09-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10892','EDW/Datamart Enhancements: Created new column to tquote tables','Enhancement','2025-09-20','Bhaskar Muthyala','Addition','edw_core','tquote','renewal_quote_review_start_dt','Created new column','41','Yes','2025-09-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC40122/INC39981','IVANS Policy Resent Request','Bug','2025-09-20','Rushin Shah','Datafix','edw_integration','policy_ivans_home_feed','','Resent a few home policies to IVANS','41','Yes','2025-09-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC40122/INC39981/AD10863','IVANS Policy Resent Request','Bug','2025-09-20','Rushin Shah','Datafix','edw_integration','policy_ivans_auto_feed','','Resent a few auto policies to IVANS including 14 policies associated with vehicle_deleted_in fix','41','Yes','2025-09-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC40122/INC39981','IVANS Policy Resent Request','Bug','2025-09-20','Rushin Shah','Datafix','edw_integration','policy_ivans_pel_feed','','Resent a few PEL policies to IVANS','41','Yes','2025-09-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11027','IVANS Collections Feed goes live','Enhancement','2025-09-20','Rushin Shah','Addition','edw_integration','policy_ivans_collections_feed','','Created new table','41','Yes','2025-09-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10865','IVANS Integration: Updated IVANS Prod endpoint to point to Azure','Enhancement','2025-09-20','Rushin Shah','Modification','edw_integration','','','Updated the endpoint in airflow production to point to Azure URL','41','Yes','2025-09-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10955','IVANS Integration: Updated PEL stored procedure','Bug','2025-09-20','Alberto Valbuena','Datafix','edw_integration','policy_ivans_auto_feed','','Updated medical payments logic at vehicle level','41','Yes','2025-09-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10813','Process Improvements : Updated validations to tvalidation_sql','Enhancement','2025-09-20','Dinesh Bobbili','Addition','edw_core','tvalidation_sql','','Added data quality checks to monitor issues associated with HONK feed','41','Yes','2025-09-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10925','Process Improvements : Updated validations to tvalidation_sql','Enhancement','2025-09-20','Yunus Mohammed','Addition','edw_core','tvalidation_sql','','Added data quality checks to monitor issues associated with current carrier feed','41','Yes','2025-09-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10930','EDW/Datamart Enhancements: Implemented updated logic to populate email address in tcustomer table','Bug','2025-09-20','Yunus Mohammed','Addition','edw_core','tcustomer','email','Created a new stored procedure to update email address in tcustomer table','41','Yes','2025-09-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10825','EDW/Datamart Enhancements: Implemented updated logic to transaction_status in tpolicy_history table','Bug','2025-09-20','Yunus Mohammed','Addition','edw_core','tpolicy_history','transaction_status','Created a new stored procedure to update transaction_status in tpolicy_history table (specifically to address reversed/reversal transactions)','41','Yes','2025-09-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10814','CLUE : Updated CLUE property stored procedure to create and send a new record when claim status changes','Enhancement','2025-09-20','Alberto Valbuena','Modification','edw_integration','claim_clue_property_feed','','CLUE property stored procedure to create to send a new record when claim status changes','41','Yes','2025-09-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11000','EDW Integrations : Hubspot field additions','Enhancement','2025-09-20','Hernando Garcia','Addition','edw_integration','customer_hubspot_feed','insured_nm','Created new column','41','Yes','2025-09-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10960','EDW External Integrations : Updated stored procedure for hubspot feed','Bug','2025-09-20','Architha Gudimalla','Modification','edw_integration','customer_hubspot_feed','email','Updated stored procedure for customer_hubspot_feed to retrieve the latest email from the tcustomer table','41','Yes','2025-09-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10935','EDW External Integrations : Updated stored procedure for hubspot feed','Bug','2025-09-20','Architha Gudimalla','Modification','edw_integration','customer_hubspot_feed','monoline_in','Updated stored procedure for customer_hubspot_feed and quote_hubspot_feed to apply the monoline_in fix','41','Yes','2025-09-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10935','EDW External Integrations : Updated stored procedure for hubspot feed','Bug','2025-09-20','Architha Gudimalla','Modification','edw_integration','quote_hubspot_feed','monoline_in','Updated stored procedure for customer_hubspot_feed and quote_hubspot_feed to apply the monoline_in fix','41','Yes','2025-09-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10944','Data Fixes: Fix inspection status for 18 policies','Bug','2025-09-20','Rushin Shah','Datafix','edw_core','thome_additional_coverage','roof_covering_full_reconstruction_cost_coverage_in','Updated roof_covering_full_reconstruction_cost_coverage_in to NULL when values are either blank & 0 in Metal and EDW.  This is just a onetime update.','41','Yes','2025-09-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10985','Data Fixes: Update stored procedure logic for tower_deleted_in in tcommercial_policy_tower table','Bug','2025-09-20','Yunus Mohammed','Datafix','edw_commercial','tcommercial_policy_tower','tower_deleted_in','Update stored procedure logic for tower_deleted_in in tcommercial_policy_tower table to reflect Yes or No instead of 0 or 1','41','Yes','2025-09-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10984','Commercial EDW Enhancements: Updated stored procedure for tcommercial_broker_summary to fix inforce premium issues','Bug','2025-09-20','Rushin Shah','Modification','edw_commercial','tcommercial_broker_summary','inforce_premium_amt','Updated stored procedure for tcommercial_broker_summary to fix inforce premium issues','41','Yes','2025-09-22',getdate(),getdate());