INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 10/06/2025 :</span>
    <h4 style="margin-top: 0;font-style: italic;color: blue;">This release had 9 enhancements and 15 bug fix tickets.  Release details are as follows.</h4>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; }
        h1, h2 { color: #333; }
        ul { margin: 10px 0; padding-left: 20px; }
    </style>
</head>
<body>
    <h2 style="font-style: italic;">1. EDW/Datamart Enhancements</h2>
    <ul>
        <li>Added columns non_flat_cancelled_ct, expiring_sixty_day_written_premium_amt, mtd_earned_net_premium_amt, mtd_earned_premium_amt, mtd_written_net_premium_amt to tbroker_summary table</li>
        <li>Added column policy_inforce_in to tpolicy table</li>
        <li>Added column large_loss_in to tclaim table</li>
        <li>Added column premium_analytics_grade to thome_coverage and tquote_home_coverage tables</li>
    </ul>
    <h2 style="font-style: italic;">2. Commercial EDW Enhancements</h2>
    <ul>
        <li>Added column policy_inforce_in to tcommercial_policy table</li>
        <li>Updated stored procedure for tcommercial_broker_summary and tcommercial_renewal_summary table to update logic related to tower_deleted_in</li>
    </ul>
    <h2 style="font-style: italic;">3. EDW Integrations</h2>
    <h3>a. Workday</h3>
    <ul>
        <li>Added columns scheduled_limit_amt and blanket_limit_amt for collection policies to written premium and unearned premium files</li>
        <li>Created a new table for marine monthly report to capture commissions from Majesco</li>
    </ul>
    <h3>b. Hubspot</h3>
    <ul>
        <li>Updated stored procedure for customer_hubspot_feed to add columns occupancy_type, effective_dt, expiration_dt, policy_inforce_in, per_claim_policy_limit_amt, per_claim_attachment_amt, per_claim_retention_amt</li>
    </ul>
    
    <h3>c. IVANS</h3>
    <ul>
        <li>INC40418/INC40417/INC40416/INC40348/INC40324/INC40600/INC40792/INC40605/INC40596 : Resent IVANS policies associated with these tickets</li>
    </ul>
    <h2 style="font-style: italic;">4. Data Fixes</h2>
    <ul>
        <li>INC40238 : Updated Subscriber Contribution Date for CO100017099-05</li>
        <li>INC39898 : Updated transactions associated with HO200050040 so that all transactions have Clearing House Fee instead of Transaction Fee</li>
        <li>INC41098 : Updated IsPolicyChange to false in Metal and edw_stage for HO200077752</li>
        <li>INC23083 : Updated WindstormOrHailDeductible to AOP Applies for HO100216893 in Metal and EDW. Also updated wind_derived_deductible to AOP Applies</li>
        <li>AD10630 : Updated missing email address in tpolicy_insured table</li>
        <li>AD11065 : Backfilled Coverage A value using RC Estimator data</li>
    </ul>
</body>
'
,'Yes'
,'2025-10-06'
,getdate()
,getdate()
)
;

INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11182','EDW/Datamart Enhancements: Created new column to tpolicy tables','Enhancement','2025-10-04','Rushin Shah','Addition','edw_core','tpolicy','policy_inforce_in','Created new column','42','Yes','2025-10-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11182','EDW/Datamart Enhancements: Created new column to tcommercial_policy tables','Enhancement','2025-10-04','Rushin Shah','Addition','edw_commercial','tcommercial_policy','policy_inforce_in','Created new column','42','Yes','2025-10-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11092','EDW/Datamart Enhancements: Created new column to tclaim tables','Enhancement','2025-10-04','Bhaskar Muthyala','Addition','edw_core','tclaim','large_loss_in','Created new column','42','Yes','2025-10-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11045','EDW/Datamart Enhancements: Created new column to thome_coverage tables','Enhancement','2025-10-04','Tuba Mohsin','Addition','edw_core','thome_coverage','premium_analytics_grade','Created new column','42','Yes','2025-10-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11045','EDW/Datamart Enhancements: Created new column to thome_additional_coverage tables','Enhancement','2025-10-04','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','premium_analytics_grade','Created new column','42','Yes','2025-10-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11215','EDW/Datamart Enhancements: Created new column to tbroker_summary tables','Enhancement','2025-10-04','Architha Gudimalla','Addition','edw_core','tbroker_summary','non_flat_cancelled_ct','Created new column','42','Yes','2025-10-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11215','EDW/Datamart Enhancements: Created new column to tbroker_summary tables','Enhancement','2025-10-04','Architha Gudimalla','Addition','edw_core','tbroker_summary','expiring_sixty_day_written_premium_amt','Created new column','42','Yes','2025-10-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11215','EDW/Datamart Enhancements: Created new column to tbroker_summary tables','Enhancement','2025-10-04','Architha Gudimalla','Addition','edw_core','tbroker_summary','mtd_earned_net_premium_amt','Created new column','42','Yes','2025-10-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11215','EDW/Datamart Enhancements: Created new column to tbroker_summary tables','Enhancement','2025-10-04','Architha Gudimalla','Addition','edw_core','tbroker_summary','mtd_earned_premium_amt','Created new column','42','Yes','2025-10-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11215','EDW/Datamart Enhancements: Created new column to tbroker_summary tables','Enhancement','2025-10-04','Architha Gudimalla','Addition','edw_core','tbroker_summary','mtd_written_net_premium_amt','Created new column','42','Yes','2025-10-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('SR40404/SR40271','EDW Integrations : Hubspot field additions','Enhancement','2025-10-04','Architha Gudimalla','Addition','edw_integration','customer_hubspot_feed','occupancy_type','Created new column','42','Yes','2025-10-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('SR40404/SR40271','EDW Integrations : Hubspot field additions','Enhancement','2025-10-04','Architha Gudimalla','Addition','edw_integration','customer_hubspot_feed','effective_dt','Created new column','42','Yes','2025-10-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('SR40404/SR40271','EDW Integrations : Hubspot field additions','Enhancement','2025-10-04','Architha Gudimalla','Addition','edw_integration','customer_hubspot_feed','expiration_dt','Created new column','42','Yes','2025-10-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('SR40404/SR40271','EDW Integrations : Hubspot field additions','Enhancement','2025-10-04','Architha Gudimalla','Addition','edw_integration','customer_hubspot_feed','policy_inforce_in','Created new column','42','Yes','2025-10-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('SR40404/SR40271','EDW Integrations : Hubspot field additions','Enhancement','2025-10-04','Architha Gudimalla','Addition','edw_integration','customer_hubspot_feed','per_claim_policy_limit_amt','Created new column','42','Yes','2025-10-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('SR40404/SR40271','EDW Integrations : Hubspot field additions','Enhancement','2025-10-04','Architha Gudimalla','Addition','edw_integration','customer_hubspot_feed','per_claim_attachment_amt','Created new column','42','Yes','2025-10-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('SR40404/SR40271','EDW Integrations : Hubspot field additions','Enhancement','2025-10-04','Architha Gudimalla','Addition','edw_integration','customer_hubspot_feed','per_claim_retention_amt','Created new column','42','Yes','2025-10-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11089','Commercial EDW Enhancements: Updated stored procedure for tcommercial_broker_summary and tcommercial_renewal_summary table to update logic related to tower_deleted_in','Enhancement','2025-10-04','Yunus Mohammed','Modification','edw_commercial','tcommercial_broker_summary','','Updated stored procedure to update logic related to tower_deleted_in','42','Yes','2025-10-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11089','Commercial EDW Enhancements: Updated stored procedure for tcommercial_broker_summary and tcommercial_renewal_summary table to update logic related to tower_deleted_in','Enhancement','2025-10-04','Yunus Mohammed','Modification','edw_commercial','tcommercial_renewal_summary','','Updated stored procedure to update logic related to tower_deleted_in','42','Yes','2025-10-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC40418/40417/40416/40348/40324/40600/40792/40605/40596','IVANS Policy Resent Request','Bug','2025-10-04','Rushin Shah','Datafix','edw_integration','policy_ivans_home_feed','','Resent a few home policies to IVANS','42','Yes','2025-10-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC40418/40417/40416/40348/40324/40600/40792/40605/40596','IVANS Policy Resent Request','Bug','2025-10-04','Rushin Shah','Datafix','edw_integration','policy_ivans_auto_feed','','Resent a few auto policies to IVANS','42','Yes','2025-10-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC40418/40417/40416/40348/40324/40600/40792/40605/40596','IVANS Policy Resent Request','Bug','2025-10-04','Rushin Shah','Datafix','edw_integration','policy_ivans_pel_feed','','Resent a few PEL policies to IVANS','42','Yes','2025-10-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11097','Workday Enhancements: Added Collection limit columns to written premium and unearned premium files','Enhancement','2025-10-04','Rushin Shah','Addition','edw_integration','policy_workday_written_premium_feed','scheduled_limit_amt','Created new column','42','Yes','2025-10-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11097','Workday Enhancements: Added Collection limit columns to written premium and unearned premium files','Enhancement','2025-10-04','Rushin Shah','Addition','edw_integration','policy_workday_written_premium_feed','blanket_limit_amt','Created new column','42','Yes','2025-10-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11097','Workday Enhancements: Added Collection limit columns to written premium and unearned premium files','Enhancement','2025-10-04','Rushin Shah','Addition','edw_integration','policy_workday_unearned_premium_feed','scheduled_limit_amt','Created new column','42','Yes','2025-10-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11097','Workday Enhancements: Added Collection limit columns to written premium and unearned premium files','Enhancement','2025-10-04','Rushin Shah','Addition','edw_integration','policy_workday_unearned_premium_feed','blanket_limit_amt','Created new column','42','Yes','2025-10-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11106','Workday enhancements: Created new workday feed associated with litigation claims','Enhancement','2025-10-04','Rushin Shah','Addition','edw_integration','policy_yacht_commission_feed','','Created new table','42','Yes','2025-10-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC40238','Data Fixes: Update subscriber contribution end date in metal for CO100017099-05','Bug','2025-10-04','Sandeep Gundreddy','Datafix','edw_core','tpolicy_insured','subscriber_contribution_end_dt','Updated subscriber contribution end date for CO100017099-05. Data is updated in Metal and will be updated in EDW during next full refresh. This is just a onetime update.','42','Yes','2025-10-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC40238','Data Fixes: Update subscriber contribution end date in metal for CO100017099-05','Bug','2025-10-04','Sandeep Gundreddy','Datafix','edw_core','tquote_policy_insured','subscriber_contribution_end_dt','Updated subscriber contribution end date for CO100017099-05. Data is updated in Metal and EDW. This is just a onetime update.','42','Yes','2025-10-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC39898','Data Fixes: Fixed transactions associated with policy # HO200050040 which had Transaction Fee instead of Clearing House Fee','Bug','2025-10-04','Bhaskar Muthyala','Datafix','edw_core','tpolicy_transaction','','Updated policy transactions associated with policy # HO200050040','42','Yes','2025-10-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC41098','Data Fixes : Updated IsPolicyChange for HO200077752 in Metal and edw_stage ','Bug','2025-10-04','Tuba Mohsin','Datafix','edw_stage','Account','IsPolicyChange','Updated IsPolicyChange to false for HO200077752 in Metal and edw_stage. This is just a onetime update.','42','Yes','2025-10-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC23083','Data Fixes : Updated WindOrHailstormDeductible for HO100216893-01','Bug','2025-10-04','Tuba Mohsin','Datafix','edw_core','thome_coverage','wind_or_hailstorm_deductible','Updated wind_or_hailstorm_deductible for HO100216893-01. Data is updated in Metal and EDW. This is just a onetime update.','42','Yes','2025-10-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC23083','Data Fixes : Updated WindOrHailstormDeductible for HO100216893-01','Bug','2025-10-04','Tuba Mohsin','Datafix','edw_core','thome_coverage','wind_derived_deductible','Updated wind_derived_deductible for HO100216893-01. Data is updated in EDW. This is just a onetime update.','42','Yes','2025-10-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC23083','Data Fixes : Updated WindOrHailstormDeductible for HO100216893-01','Bug','2025-10-04','Tuba Mohsin','Datafix','edw_core','tquote_home_coverage','wind_or_hailstorm_deductible','Updated wind_or_hailstorm_deductible for HO100216893-01. Data is updated in Metal and EDW. This is just a onetime update.','42','Yes','2025-10-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC23083','Data Fixes : Updated WindOrHailstormDeductible for HO100216893-01','Bug','2025-10-04','Tuba Mohsin','Datafix','edw_core','tquote_home_coverage','wind_derived_deductible','Updated wind_derived_deductible for HO100216893-01. Data is updated in EDW. This is just a onetime update.','42','Yes','2025-10-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10630','Data Fixes : Updated missing email address in tpolicy_insured table','Bug','2025-10-04','Dinesh Bobbili','Datafix','edw_core','tpolicy_insured','email','Updated missing email address in tpolicy_insured table.  This is just a onetime update','42','Yes','2025-10-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11065','Data Fixes : Backfilled Coverage A value using RC Estimator data','Bug','2025-10-04','Dinesh Bobbili','Datafix','edw_stage','AccountObjectField','Value','Backfilled Coverage A value using RC Estimator data.  This is just a onetime update.','42','Yes','2025-10-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11065','Data Fixes : Backfilled Coverage A value using RC Estimator data','Bug','2025-10-04','Dinesh Bobbili','Datafix','edw_stage','AccountTransactionVersionObjectField','Value','Backfilled Coverage A value using RC Estimator data.  This is just a onetime update.','42','Yes','2025-10-06',getdate(),getdate());