INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 10/20/2025 :</span>
    <h4 style="margin-top: 0;font-style: italic;color: blue;">This release had 8 enhancements and 12 bug fix tickets.  Release details are as follows.</h4>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; }
        h1, h2 { color: #333; }
        ul { margin: 10px 0; padding-left: 20px; }
    </style>
</head>
<body>
    <h2 style="font-style: italic;">1. EDW/Datamart Enhancements</h2>
    <ul>
        <li>Added column - watercraft_unique_id to tpel_watercraft and tquote_pel_watercraft tables</li>
        <li>Added column - renewal_released_by_metal_in to tquote table</li>
        <li>Added column - closed_reason_desc to tclaim and tclaim_feature tables</li>
        <li>Updated tbroker_summary stored procedure logic to run for 3 months</li>
    </ul>
    <h2 style="font-style: italic;">2. EDW Process Improvements</h2>
    <ul>
        <li>Added data quality checks to check for new mailing address states in customer hubspot feed</li>
    </ul>
    <h2 style="font-style: italic;">3. EDW Integrations</h2>
    <h3>a. Workday</h3>
    <ul>
        <li>Updated ceded premium stored procedure to include all records with HSB coverage which either has ceded amount or gross amount as non zero</li>
    </ul>
    <h3>b. Hubspot</h3>
    <ul>
        <li>Added some of the non US locations (like ON, QC, BC, NSW, PR, England, London) to contact and policy properties in Hubspot so that these can be displayed correctly</li>
        <li>Added stored procedure logic to include David Tester policies in customer_hubspot_feed</li>
    </ul>
    
    <h3>c. IVANS</h3>
    <ul>
        <li>INC42233: Resent IVANS policies associated with these tickets</li>
    </ul>
    
    <h3>d. Claim Renewal Rating</h3>
    <ul>
        <li>Added column - LargeLoss to claim_renewal_rating_auto_pel_api and claim_renewal_rating_home_collection_api tables</li>
        <li>Added column - LossDescription2 to claim_renewal_rating_auto_pel_api and claim_renewal_rating_home_collection_api tables</li>
        <li>Added column - TotalIncurred to claim_renewal_rating_auto_pel_api and claim_renewal_rating_home_collection_api tables</li>
    </ul>
    
    <h3>e. CLUE Property</h3>
    <ul>
        <li>Updated CLUE Property stored procedure to add a product_sk filter</li>
    </ul>
    
    <h2 style="font-style: italic;">4. Data Fixes</h2>
    <ul>
        <li>INC41260 : Moved 3 commercial submissions from one broker to other</li>
        <li>INC40143 : Updated document_type to Id Card in the forms table where form_type = Id Card AND document_type = Policy Document</li>
        <li>INC41049 : Updated missing auto_vehicle_sk from tadditional_interest table</li>
        <li>INC42471 : Updated IsPolicyChange to false for HO100261804-04 in Account table</li>
        <li>INC41560 : Updated MinimumEarnedPremiumPercent  for HO200072607 in Account, AccountTransaction and AccountTransactionVersion Metal tables</li>
        <li>AD11383 : Updated primary_insured_in field for HO100011280-04 & HO100227250-02</li>
        <li>AD11332 : Updated missing VIN for 2 auto policies</li>
        <li>AD11371 : Updated subscriber contribution date for HO53366001836-07</li>
        <li>AD11309 : Updated vehicle_model for one vehicle from four auto policies</li>
        <li>AD11325 : Updated flagged_in from tnote table for a few records and also updated the stored procedure to capture appropriate data</li>
    </ul>
</body>
'
,'Yes'
,'2025-10-20'
,getdate()
,getdate()
)
;
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11351','EDW/Datamart Enhancements: Created new column to tpel_watercraft and tquote_pel_watercraft tables','Enhancement','2025-10-18','Yunus Mohammed','Addition','edw_core','tpel_watercraft','watercraft_unique_id','Created new column','43','Yes','2025-10-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11351','EDW/Datamart Enhancements: Created new column to tpel_watercraft and tquote_pel_watercraft tables','Enhancement','2025-10-18','Yunus Mohammed','Addition','edw_core','tquote_pel_watercraft','watercraft_unique_id','Created new column','43','Yes','2025-10-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11341','EDW/Datamart Enhancements: Created new column to tquote tables','Enhancement','2025-10-18','Rushin Shah','Addition','edw_core','tquote','renewal_released_by_metal_in','Created new column','43','Yes','2025-10-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11320','EDW/Datamart Enhancements: Created new column to tclaim and tclaim_feature tables','Enhancement','2025-10-18','Bhaskar Muthyala','Addition','edw_core','tclaim','closed_reason_desc','Created new column','43','Yes','2025-10-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11320','EDW/Datamart Enhancements: Created new column to tclaim and tclaim_feature tables','Enhancement','2025-10-18','Bhaskar Muthyala','Addition','edw_core','tclaim_feature','closed_reason_desc','Created new column','43','Yes','2025-10-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10932','EDW Integrations: Claim renewal rating field additions','Enhancement','2025-10-18','Bhaskar Muthyala','Addition','edw_integration','claim_renewal_rating_auto_pel_api','LargeLoss','Created new column','43','Yes','2025-10-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10932','EDW Integrations: Claim renewal rating field additions','Enhancement','2025-10-18','Bhaskar Muthyala','Addition','edw_integration','claim_renewal_rating_home_collection_api','LargeLoss','Created new column','43','Yes','2025-10-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10932','EDW Integrations: Claim renewal rating field additions','Enhancement','2025-10-18','Bhaskar Muthyala','Addition','edw_integration','claim_renewal_rating_auto_pel_api','TotalIncurred','Created new column','43','Yes','2025-10-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10932','EDW Integrations: Claim renewal rating field additions','Enhancement','2025-10-18','Bhaskar Muthyala','Addition','edw_integration','claim_renewal_rating_home_collection_api','TotalIncurred','Created new column','43','Yes','2025-10-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10932','EDW Integrations: Claim renewal rating field additions','Enhancement','2025-10-18','Bhaskar Muthyala','Addition','edw_integration','claim_renewal_rating_auto_pel_api','LargeLoss','Created new column','43','Yes','2025-10-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10932','EDW Integrations: Claim renewal rating field additions','Enhancement','2025-10-18','Bhaskar Muthyala','Addition','edw_integration','claim_renewal_rating_home_collection_api','LargeLoss','Created new column','43','Yes','2025-10-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11286','EDW/Datamart Enhancements: Updated tbroker_summary stored procedure logic to run for 3 months','Enhancement','2025-10-18','Dinesh Bobbili','Modification','edw_core','trenewal_summary','','Updated stored procedure  to run for 3 months','43','Yes','2025-10-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11288','Workday Enhancements: Updated ceded premium stored procedure','Enhancement','2025-10-18','Rushin Shah','Addition','edw_integration','policy_workday_ceded_premium_feed','','Updated ceded premium stored procedure to include all records with HSB coverage which either has ceded amount or gross amount as non zero','43','Yes','2025-10-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC42233','IVANS Policy Resent Request','Bug','2025-10-18','Rushin Shah','Datafix','edw_integration','policy_ivans_home_feed','','Resent a few home policies to IVANS','43','Yes','2025-10-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC42233','IVANS Policy Resent Request','Bug','2025-10-18','Rushin Shah','Datafix','edw_integration','policy_ivans_auto_feed','','Resent a few auto policies to IVANS','43','Yes','2025-10-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC42233','IVANS Policy Resent Request','Bug','2025-10-18','Rushin Shah','Datafix','edw_integration','policy_ivans_pel_feed','','Resent a few PEL policies to IVANS','43','Yes','2025-10-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11339','Process Improvements : Updated validations to tvalidation_sql','Enhancement','2025-10-18','Dinesh Bobbili','Addition','edw_core','tvalidation_sql','','Added data quality checks to check for new mailing address states in customer hubspot feed','43','Yes','2025-10-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11334','EDW Integrations : Hubspot field updates','Enhancement','2025-10-18','Architha Gudimalla','Modification','edw_integration','customer_hubspot_feed','','Added some of the non US locations (like ON, QC, BC, NSW, PR, England, London) to contact and policy properties in Hubspot so that these can be displayed correctly','43','Yes','2025-10-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11334','EDW Integrations : Hubspot field updates','Enhancement','2025-10-18','Dinesh Bobbili','Modification','edw_integration','customer_hubspot_feed','','Added stored procedure logic to include David Tester policies in customer_hubspot_feed','43','Yes','2025-10-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11371','Data Fixes: Update subscriber contribution end date in metal for HO53366001836-07','Bug','2025-10-18','Rushin Shah','Datafix','edw_core','tpolicy_insured','subscriber_contribution_end_dt','Updated subscriber contribution end date for HO53366001836-07. Data is updated in Metal and will be updated in EDW during next full refresh. This is just a onetime update.','43','Yes','2025-10-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11371','Data Fixes: Update subscriber contribution end date in metal for HO53366001836-07','Bug','2025-10-18','Rushin Shah','Datafix','edw_core','tquote_policy_insured','subscriber_contribution_end_dt','Updated subscriber contribution end date for HO53366001836-07. Data is updated in Metal and EDW. This is just a onetime update.','43','Yes','2025-10-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11383','Data Fixes: Update isPrimaryInsured for HO100011280-04 & HO100227250-02','Bug','2025-10-18','Architha Gudimalla','Datafix','edw_core','tpolicy_insured','primary_insured_in','Update isPrimaryInsured for HO100011280-04 & HO100227250-02 in Metal and EDW.  This is just a onetime update.','43','Yes','2025-10-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC40143','Data Fixes : Updated document_type to Id Card in the forms table','Bug','2025-10-18','Tuba Mohsin','Datafix','edw_core','tpolicy_form','document_type','Updated document_type to Id Card in the forms table where form_type = Id Card AND document_type = Policy Document in Metal and edw_stage. This is just a onetime update.','43','Yes','2025-10-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC40143','Data Fixes : Updated document_type to Id Card in the forms table','Bug','2025-10-18','Tuba Mohsin','Datafix','edw_core','tquote_form','document_type','Updated document_type to Id Card in the forms table where form_type = Id Card AND document_type = Policy Document in Metal and edw_stage. This is just a onetime update.','43','Yes','2025-10-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11332','Data Fixes : Updated missing VIN for 2 auto policies','Bug','2025-10-18','Tuba Mohsin','Datafix','edw_core','tauto_vehicle','vehicle_vin','Updated vehicle VIN for AU200026339 and AU200031119. Data is updated in Metal and EDW. This is just a onetime update.','43','Yes','2025-10-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11332','Data Fixes : Updated missing VIN for 2 auto policies','Bug','2025-10-18','Tuba Mohsin','Datafix','edw_core','tquote_auto_vehicle','vehicle_vin','Updated vehicle VIN for AU200026339 and AU200031119. Data is updated in Metal and EDW. This is just a onetime update.','43','Yes','2025-10-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC41560','Data Fixes : Updated MinimumEarnedPremiumPercent for HO200072607','Bug','2025-10-18','Rushin Shah','Datafix','edw_stage','Account','MinimumEarnedPremiumPercent','Updated MinimumEarnedPremiumPercent for HO200072607 to 0. This is just a onetime update.','43','Yes','2025-10-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC41560','Data Fixes : Updated MinimumEarnedPremiumPercent for HO200072607','Bug','2025-10-18','Rushin Shah','Datafix','edw_stage','AccountTransaction','MinimumEarnedPremiumPercent','Updated MinimumEarnedPremiumPercent for HO200072607 to 0. This is just a onetime update.','43','Yes','2025-10-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC41560','Data Fixes : Updated MinimumEarnedPremiumPercent for HO200072607','Bug','2025-10-18','Rushin Shah','Datafix','edw_stage','AccountTransactionVersion','MinimumEarnedPremiumPercent','Updated MinimumEarnedPremiumPercent for HO200072607 to 0. This is just a onetime update.','43','Yes','2025-10-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC41260','Data Fixes : Moved 3 commercial submissions from one broker to other','Bug','2025-10-18','Architha Gudimalla','Datafix','edw_commercial','tcommercial_quote','broker_id','Updated broker_id for 3 commercial submissions from 10019 to 57914.  This is just a onetime update.','43','Yes','2025-10-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11309','Data Fixes : Update vehicle_model for 4 policies','Bug','2025-10-18','Rushin Shah','Datafix','edw_core','tauto_vehicle','vehicle_model','Updated vehicle_model for one vehicle from four auto policies to remove double quotes from vehicle model.  Data was fixed in Metal and EDW.  This is just a onetime update.','43','Yes','2025-10-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11309','Data Fixes : Update vehicle_model for 4 policies','Bug','2025-10-18','Rushin Shah','Datafix','edw_core','tquote_auto_vehicle','vehicle_model','Updated vehicle_model for one vehicle from four auto policies to remove double quotes from vehicle model.  Data was fixed in Metal and EDW.  This is just a onetime update.','43','Yes','2025-10-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC41049','Data Fixes : Updated missing auto_vehicle_sk in tadditional_interest table for a few records','Bug','2025-10-18','Dinesh Bobbili','Datafix','edw_core','tadditional_interest','auto_vehicle_sk','Updated missing auto_vehicle_sk in tadditional_interest table for 272 records.  This is just a onetime update.','43','Yes','2025-10-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11325','Data Fixes : Updated flagged_in from tnote table','Bug','2025-10-18','Dinesh Bobbili','Datafix','edw_core','tnote','flagged_in','Updated flagged_in from tnote table for a few records and also updated the stored procedure to capture appropriate data.  This is just a onetime update','43','Yes','2025-10-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11412','Data Fixes : Updated CLUE Property stored procedure to add a product_sk filter','Bug','2025-10-18','Sandeep Gundreddy','Modification','edw_integration','claim_clue_property_feed','','Updated CLUE Property stored procedure to add a product_sk filter to only select Home, Condo and Collections','43','Yes','2025-10-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC42471','Data Fixes : Updated IsPolicyChange for HO100261804-04 in Metal and edw_stage ','Bug','2025-10-18','Rushin Shah','Datafix','edw_stage','Account','IsPolicyChange','Updated IsPolicyChange to false for HO100261804-04 in Metal and edw_stage. This is just a onetime update.','43','Yes','2025-10-20',getdate(),getdate());