INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 11/03/2025 :</span>
    <h4 style="margin-top: 0;font-style: italic;color: blue;">This release had 9 enhancements and 13 bug fix tickets.  Release details are as follows.</h4>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; }
        h1, h2 { color: #333; }
        ul { margin: 10px 0; padding-left: 20px; }
    </style>
</head>
<body>
    <h2 style="font-style: italic;">1. EDW/Datamart Enhancements</h2>
    <ul>
        <li>Added columns - stalled_quote_in and new_business_work_status to tquote table</li>
        <li>Added columns - affliation_in and broker_affiliation_nm to tbroker table</li>
        <li>Added columns - Mtd_claim_ct,  mtd_loss_incurred_amt,  mtd_loss_incurred_capped_amt, prior_mtd_claim_ct, prior_mtd_loss_incurred_amt,  prior_mtd_loss_incurred_capped_amt, prior_mtd_earned_premium_amt, prior_mtd_earned_net_premium_amt, prior_year_earned_premium_amt, prior_year_earned_net_premium_amt to tbroker_summary table</li>
        <li>Added column : underwriter_required_inspection to thome_coverage table</li>
        <li>Added column : underwriter_required_inspection to tquote_home_coverage table</li>
        <li>Backfilled data for bound_by_broker_in in tquote table</li>
        <li>Updated stored procedure logic to remove timestamp from subscribercontributionenddate in tpolicy_insured and tquote_insured tables</li>
        <li>Changed data type associated with total_finished_square_feet to varchar(255) in thome_coverage and tquote_home_coverage table</li>
    </ul>
    <h2 style="font-style: italic;">2. EDW Process Improvements</h2>
    <ul>
        <li>Added data quality checks to check for auto limit amounts in tauto_policy_coverage table to match display value</li>
        <li>Few validation SQL were refined to enhance accuracy</li>
    </ul>
    <h2 style="font-style: italic;">3. EDW Integrations</h2>
    <h3>a. Hubspot</h3>
    <ul>
        <li>Updated stored procedure for customer_hubspot_feed to add insured_nm and uw_company_nm</li>
    </ul>
    
    <h3>b. IVANS</h3>
    <ul>
        <li>INC43176/43172/43170/42881/42587 : Resent IVANS policies associated with these tickets</li>
    </ul>

    <h2 style="font-style: italic;">4. Data Fixes</h2>
    <ul>
        <li>AD11117 : Updated relationship_to_insured for 13 auto policies in Metal and EDW</li>
        <li>AD11516 : Updated yacht claim number from 1.86082 to 25ATFL20004275 in Snapsheet and all EDW claims table</li>
        <li>INC41016 : Updated reserve amount associated with one closed claim C24AUA00796. This is just a onetime update.</li>
        <li>INC38643 : Updated unisured_motorist_limit_amt in tauto_policy_coverage table for AU100117583-02</li>
        <li>INC43451 : Updated subscriber contribution end date for one customer</li>
        <li>AD11531/AD11529 : Updated group_name in nfp_policy table that was erroneously populated for 200 records.  Also made this update in snapsheet webhook table.</li>
    </ul>
</body>
'
,'Yes'
,'2025-11-03'
,getdate()
,getdate()
)
;

INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11206','EDW/Datamart Enhancements: Created new column to tquote table','Enhancement','2025-11-01','Rushin Shah','Addition','edw_core','tquote','stalled_quote_in','Created new column','44','Yes','2025-11-03',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11206','EDW/Datamart Enhancements: Created new column to tquote table','Enhancement','2025-11-01','Rushin Shah','Addition','edw_core','tquote','new_business_work_status','Created new column','44','Yes','2025-11-03',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11485','EDW/Datamart Enhancements: Created new column to tbroker table','Enhancement','2025-11-01','Tuba Mohsin','Addition','edw_core','tbroker','affliation_in','Created new column','44','Yes','2025-11-03',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11485','EDW/Datamart Enhancements: Created new column to tbroker table','Enhancement','2025-11-01','Tuba Mohsin','Addition','edw_core','tbroker','broker_affiliation_nm','Created new column','44','Yes','2025-11-03',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11449','EDW/Datamart Enhancements: Created new column to thome_coverage and tquote_home_coverage tables','Enhancement','2025-11-01','Tuba Mohsin','Addition','edw_core','thome_coverage','underwriter_required_inspection','Created new column','44','Yes','2025-11-03',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11449','EDW/Datamart Enhancements: Created new column to thome_coverage and tquote_home_coverage tables','Enhancement','2025-11-01','Tuba Mohsin','Addition','edw_core','tquote_home_coverage','underwriter_required_inspection','Created new column','44','Yes','2025-11-03',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11454','EDW/Datamart Enhancements: Created new column to tbroker_summary table','Enhancement','2025-11-01','Architha Gudimalla','Addition','edw_core','tbroker_summary','mtd_claim_ct','Created new column','44','Yes','2025-11-03',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11454','EDW/Datamart Enhancements: Created new column to tbroker_summary table','Enhancement','2025-11-01','Architha Gudimalla','Addition','edw_core','tbroker_summary','mtd_loss_incurred_amt','Created new column','44','Yes','2025-11-03',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11454','EDW/Datamart Enhancements: Created new column to tbroker_summary table','Enhancement','2025-11-01','Architha Gudimalla','Addition','edw_core','tbroker_summary','mtd_loss_incurred_capped_amt','Created new column','44','Yes','2025-11-03',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11454','EDW/Datamart Enhancements: Created new column to tbroker_summary table','Enhancement','2025-11-01','Architha Gudimalla','Addition','edw_core','tbroker_summary','prior_mtd_claim_ct','Created new column','44','Yes','2025-11-03',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11454','EDW/Datamart Enhancements: Created new column to tbroker_summary table','Enhancement','2025-11-01','Architha Gudimalla','Addition','edw_core','tbroker_summary','prior_mtd_loss_incurred_amt','Created new column','44','Yes','2025-11-03',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11454','EDW/Datamart Enhancements: Created new column to tbroker_summary table','Enhancement','2025-11-01','Architha Gudimalla','Addition','edw_core','tbroker_summary','prior_mtd_loss_incurred_capped_amt','Created new column','44','Yes','2025-11-03',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11454','EDW/Datamart Enhancements: Created new column to tbroker_summary table','Enhancement','2025-11-01','Architha Gudimalla','Addition','edw_core','tbroker_summary','prior_mtd_earned_premium_amt','Created new column','44','Yes','2025-11-03',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11454','EDW/Datamart Enhancements: Created new column to tbroker_summary table','Enhancement','2025-11-01','Architha Gudimalla','Addition','edw_core','tbroker_summary','prior_mtd_earned_net_premium_amt','Created new column','44','Yes','2025-11-03',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11454','EDW/Datamart Enhancements: Created new column to tbroker_summary table','Enhancement','2025-11-01','Architha Gudimalla','Addition','edw_core','tbroker_summary','prior_year_earned_premium_amt','Created new column','44','Yes','2025-11-03',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11454','EDW/Datamart Enhancements: Created new column to tbroker_summary table','Enhancement','2025-11-01','Architha Gudimalla','Addition','edw_core','tbroker_summary','prior_year_earned_net_premium_amt','Created new column','44','Yes','2025-11-03',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11491','EDW/Datamart Enhancements: Created new column to Account table','Enhancement','2025-11-01','Bhaskar Muthyala','Addition','edw_stage','Account','NewBusinessWorkStatus','Created new column','44','Yes','2025-11-03',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11491','EDW/Datamart Enhancements: Created new column to Account table','Enhancement','2025-11-01','Bhaskar Muthyala','Addition','edw_stage','Account','IsBrokerBindEligible','Created new column','44','Yes','2025-11-03',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11491','EDW/Datamart Enhancements: Created new column to Account table','Enhancement','2025-11-01','Bhaskar Muthyala','Addition','edw_stage','Account','IsBrokerOfferEligibile','Created new column','44','Yes','2025-11-03',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11491','EDW/Datamart Enhancements: Created new column to Account table','Enhancement','2025-11-01','Bhaskar Muthyala','Addition','edw_stage','Account','IsOfferTriggeredByBroker','Created new column','44','Yes','2025-11-03',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11491','EDW/Datamart Enhancements: Created new column to Account table','Enhancement','2025-11-01','Bhaskar Muthyala','Addition','edw_stage','Account','IsQuickQuoteDisabled','Created new column','44','Yes','2025-11-03',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11484','EDW/Datamart Enhancements: Backfilling of bound_by_broker_in in tquote table','Bug','2025-11-01','Bhaskar Muthyala','Datafix','edw_core','tquote','bound_by_broker_in','Backfilled data for bound_by_broker_id','44','Yes','2025-11-03',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC43176/INC43172/INC43170/INC42881/INC42587','IVANS Policy Resent Request','Bug','2025-11-01','Rushin Shah','Datafix','edw_integration','policy_ivans_home_feed','','Resent a few home policies to IVANS','44','Yes','2025-11-03',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC43176/INC43172/INC43170/INC42881/INC42587','IVANS Policy Resent Request','Bug','2025-11-01','Rushin Shah','Datafix','edw_integration','policy_ivans_auto_feed','','Resent a few auto policies to IVANS','44','Yes','2025-11-03',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC43176/INC43172/INC43170/INC42881/INC42587','IVANS Policy Resent Request','Bug','2025-11-01','Rushin Shah','Datafix','edw_integration','policy_ivans_pel_feed','','Resent a few PEL policies to IVANS','44','Yes','2025-11-03',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11524','Process Improvements : Updated validations to tvalidation_sql','Enhancement','2025-11-01','Yunus Mohammed','Modification','edw_core','tvalidation_sql','','Few validation SQL were refined to enhance accuracy','44','Yes','2025-11-03',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11524','Process Improvements : Updated validations to tvalidation_sql','Enhancement','2025-11-01','Yunus Mohammed','Addition','edw_core','tvalidation_sql','','Added data quality checks to check for auto limit amounts in tauto_policy_coverage table to match display value','44','Yes','2025-11-03',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11458','EDW Integrations : Hubspot field additions','Enhancement','2025-11-01','Architha Gudimalla','Addition','edw_integration','customer_hubspot_feed','insured_nm','Created new column','44','Yes','2025-11-03',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11458','EDW Integrations : Hubspot field additions','Enhancement','2025-11-01','Architha Gudimalla','Addition','edw_integration','customer_hubspot_feed','uw_company_nm','Created new column','44','Yes','2025-11-03',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11542','Data Fixes: Update subscriber contribution end date in metal for one customer','Bug','2025-11-01','Tuba Mohsin','Datafix','edw_core','tpolicy_insured','subscriber_contribution_end_dt','Updated subscriber contribution end date for one customer. Data is updated in Metal and will be updated in EDW during next full refresh. This is just a onetime update.','44','Yes','2025-11-03',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11542','Data Fixes: Update subscriber contribution end date in metal for one customer','Bug','2025-11-01','Tuba Mohsin','Datafix','edw_core','tquote_policy_insured','subscriber_contribution_end_dt','Updated subscriber contribution end date for one customer. Data is updated in Metal and will be updated in EDW during next full refresh. This is just a onetime update.','44','Yes','2025-11-03',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11432','EDW/Datamart Enhancements:  Updated tpolicy_insured and tquote_insured stored procedure logic','Enhancement','2025-11-01','Yunus Mohammed','Modification','edw_core','tpolicy_insured','subscriber_contribution_end_dt','Updated stored procedure logic to remove timestamp from subscribercontributionenddate in tpolicy_insured and tquote_insured tables','44','Yes','2025-11-03',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11432','EDW/Datamart Enhancements:  Updated tpolicy_insured and tquote_insured stored procedure logic','Enhancement','2025-11-01','Yunus Mohammed','Modification','edw_core','tquote_insured','subscriber_contribution_end_dt','Updated stored procedure logic to remove timestamp from subscribercontributionenddate in tpolicy_insured and tquote_insured tables','44','Yes','2025-11-03',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11529/AD11531','Data Fixes : Updated group_name in nfp_policy table and webhook','Bug','2025-11-01','Dinesh Bobbili','Datafix','edw_stage','nfp_policy','group_name','Updated group_name in nfp_policy table that was erroneously populated for 200 records and also updated policy webhook. ','44','Yes','2025-11-03',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11117','Data Fixes : Updated relationship_to_insured for 13 auto policies','Bug','2025-11-01','Tuba Mohsin','Datafix','edw_core','tauto_driver','relationship_to_insured','Updated relationship_to_insured for 13 auto policies. Data is updated in Metal and EDW. This is just a onetime update.','44','Yes','2025-11-03',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11117','Data Fixes : Updated relationship_to_insured for 13 auto policies','Bug','2025-11-01','Tuba Mohsin','Datafix','edw_core','tquote_auto_driver','relationship_to_insured','Updated relationship_to_insured for 13 auto policies. Data is updated in Metal and EDW. This is just a onetime update.','44','Yes','2025-11-03',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11516','Data Fixes : Updated yaccht claim from 1.86082 to 25ATFL20004275 in EDW and Snapsheet','Bug','2025-11-01','Bhaskar Muthyala','Datafix','edw_core','tclaim','claim_no ','Updated yacht claim number from 1.86082 to 25ATFL20004275 in Snapsheet and all EDW claims table','44','Yes','2025-11-03',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11516','Data Fixes : Updated yaccht claim from 1.86082 to 25ATFL20004275 in EDW and Snapsheet','Bug','2025-11-01','Bhaskar Muthyala','Datafix','edw_core','tclaim_feature','claim_no ','Updated yacht claim number from 1.86082 to 25ATFL20004275 in Snapsheet and all EDW claims table','44','Yes','2025-11-03',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11516','Data Fixes : Updated yaccht claim from 1.86082 to 25ATFL20004275 in EDW and Snapsheet','Bug','2025-11-01','Bhaskar Muthyala','Datafix','edw_core','tclaim_payment','claim_no ','Updated yacht claim number from 1.86082 to 25ATFL20004275 in Snapsheet and all EDW claims table','44','Yes','2025-11-03',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11516','Data Fixes : Updated yaccht claim from 1.86082 to 25ATFL20004275 in EDW and Snapsheet','Bug','2025-11-01','Bhaskar Muthyala','Datafix','edw_core','tclaim_task','claim_no ','Updated yacht claim number from 1.86082 to 25ATFL20004275 in Snapsheet and all EDW claims table','44','Yes','2025-11-03',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11489','EDW/Datamart Enhancements:  Updated data type associated with total_finished_square_feet','Enhancement','2025-11-01','Dinesh Bobbili','Modification','edw_core','thome_coverage','total_finished_square_feet','Updated data type associated with total_finished_square_feet to varchar(255)','44','Yes','2025-11-03',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11489','EDW/Datamart Enhancements:  Updated data type associated with total_finished_square_feet','Enhancement','2025-11-01','Dinesh Bobbili','Modification','edw_core','tquote_home_coverage','total_finished_square_feet','Updated data type associated with total_finished_square_feet to varchar(255)','44','Yes','2025-11-03',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC38643','Data Fixes : Updated unisured_motorist_limit_amt in tauto_policy_coverage table for AU100117583-02','Bug','2025-11-01','Dinesh Bobbili','Datafix','edw_core','tauto_policy_coverage','unisured_motorist_limit_amt','Updated unisured_motorist_limit_amt in tauto_policy_coverage table for AU100117583-02.   Data was fixed in Metal and EDW.  This is just a onetime update.','44','Yes','2025-11-03',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC41016','Data Fixes: Fixed reserve amount associated with one closed claim C24AUA00796 which had non zero reserves','Bug','2025-11-01','Bhaskar Muthyala','Datafix','edw_core','tclaim_transaction','','Fixed reserve amount associated with one closed claim C24AUA00796 This is just a onetime update.','44','Yes','2025-11-03',getdate(),getdate());