INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 11/14/2025 :</span>
    <h4 style="margin-top: 0;font-style: italic;color: blue;">This release had 3 enhancements and 7 bug fix tickets.  Release details are as follows.</h4>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; }
        h1, h2 { color: #333; }
        ul { margin: 10px 0; padding-left: 20px; }
    </style>
</head>
<body>

    <h2 style="font-style: italic;">1. EDW/Datamart Enhancements</h2>

    <ul>
        <li>Added column - broker_of_record_change_in to tpolicy and tquote table</li>
        <li>Code deployment i.e. pushing code to repo associated with integration of NFP data in EDW (this weekend).  Plan is to insert NFP data into the following tables on 11/23.
            <ul>
                <li>tpolicy</li>
                <li>tpolicy_history</li>
                <li>tpolicy_transaction</li>
                <li>tcustomer</li>
                <li>tgrpel_coverage</li>
                <li>tcustomer_summary</li>
                <li>tdaily_inforce_summary</li>
                <li>titem_inforce</li>
                <li>titem_summary</li>
                <li>tpolicy_summary</li>
                <li>tpolicy_transaction_summary</li>
                <li>trenewal_summary</li>
                <li>tbroker_summary</li>
                <li>customer_hubspot_feed</li>
                <li>quote_hubspot_feed</li>
                <li>policy_workday_unearned_premium_feed</li>
                <li>policy_workday_written_premium_feed</li>
                <li>claim_workday_payment_feed</li>
                <li>claim_workday_reserve_feed</li>
                <li>claim_workday_itd_reserve_feed</li>
                <li>tclaim</li>
                <li>tclaim_feature</li>
                <li>tclaim_transaction</li>
                <li>tclaim_summary</li>
                <li>tclaim_feature_summary</li>
                <li>claim_renewal_rating_auto_pel_api</li>
            </ul>
        </li>
    </ul>

    <h2 style="font-style: italic;">2. EDW Process Enhancements</h2>
    <ul>
        <li>Modified Azure Data Factory(ADF) linked service connection to use SQL Server to support AWS to Azure migration</li>
        <li>Modified few data validation SQLs to enhance accuracy</li>
    </ul>

    <h2 style="font-style: italic;">3. EDW Integrations</h2>
    <h3>a. Current Carrier Auto</h3>
    <ul>
        <li>Feed goes live</li>
    </ul>

    <h3>b. Clue Auto feed</h3>
    <ul>
        <li>Feed goes live</li>
    </ul>
    
    <h3>c. IVANS</h3>
    <ul>
        <li>INC44013/44014 : Resent IVANS policies associated with these tickets</li>
    </ul>

    <h2 style="font-style: italic;">4. Data Fixes</h2>
    <ul>
        <li>AD10988 : Fixed commercial policy which had policy number as 0 in Metal and EDW.  This is just a one time update.</li>
        <li>INC43921: Updated IsDeletedOnRenewal indicator for EX100095343-04 in Metal.  This is just a onetime update.</li>
        <li>AD11585 : Updated relationship_to_insured for AU100092568-04 and AU100101364-04 in Metal and EDW.</li>
        <li>INC43652 : Updated effectivedate, expirationdate, originaleffectivedate, accountingeffectivedate, transactioneffectivedate and duedate for 2 commercial policies M5020227 and M5020229 in Metal and EDW.  This is just a onetime update.</li>
        <li>AD11564 : Updated brokerage affiliation values in Metal based on user request.</li>
    </ul>
</body>
'
,'Yes'
,'2025-11-17'
,getdate()
,getdate()
)
;
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11314','EDW/Datamart Enhancements: Created new column to tpolicy and tquote table','Enhancement','2025-11-15','Rushin Shah','Addition','edw_core','tpolicy','broker_of_record_change_in','Created new column','45','Yes','2025-11-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11314','EDW/Datamart Enhancements: Created new column to tpolicy and tquote table','Enhancement','2025-11-15','Rushin Shah','Addition','edw_core','tpolicy','broker_of_record_change_in','Created new column','45','Yes','2025-11-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10771','EDW/Datamart Enhancements: Integrate NFP Group Excess data into EDW','Enhancement','2025-11-15','Dinesh Bobbili','Modification','edw_core','tpolicy','','Integrated NFP data into this table','45','Yes','2025-11-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10771','EDW/Datamart Enhancements: Integrate NFP Group Excess data into EDW','Enhancement','2025-11-15','Dinesh Bobbili','Modification','edw_core','tpolicy_history','','Integrated NFP data into this table','45','Yes','2025-11-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10771','EDW/Datamart Enhancements: Integrate NFP Group Excess data into EDW','Enhancement','2025-11-15','Dinesh Bobbili','Modification','edw_core','tpolicy_transaction','','Integrated NFP data into this table','45','Yes','2025-11-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10771','EDW/Datamart Enhancements: Integrate NFP Group Excess data into EDW','Enhancement','2025-11-15','Dinesh Bobbili','Modification','edw_core','tcustomer','','Integrated NFP data into this table','45','Yes','2025-11-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10771','EDW/Datamart Enhancements: Integrate NFP Group Excess data into EDW','Enhancement','2025-11-15','Dinesh Bobbili','Modification','edw_core','trpel_coverage','','Created new table','45','Yes','2025-11-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10771','EDW/Datamart Enhancements: Integrate NFP Group Excess data into EDW','Enhancement','2025-11-15','Dinesh Bobbili','Modification','edw_core','tdaily_inforce_summary','','Integrated NFP data into this table','45','Yes','2025-11-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10771','EDW/Datamart Enhancements: Integrate NFP Group Excess data into EDW','Enhancement','2025-11-15','Dinesh Bobbili','Modification','edw_core','titem_inforce','','Integrated NFP data into this table','45','Yes','2025-11-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10771','EDW/Datamart Enhancements: Integrate NFP Group Excess data into EDW','Enhancement','2025-11-15','Dinesh Bobbili','Modification','edw_core','titem_summary','','Integrated NFP data into this table','45','Yes','2025-11-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10771','EDW/Datamart Enhancements: Integrate NFP Group Excess data into EDW','Enhancement','2025-11-15','Dinesh Bobbili','Modification','edw_core','tpolicy_summary','','Integrated NFP data into this table','45','Yes','2025-11-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10771','EDW/Datamart Enhancements: Integrate NFP Group Excess data into EDW','Enhancement','2025-11-15','Dinesh Bobbili','Modification','edw_core','tpolicy_transaction_summary','','Integrated NFP data into this table','45','Yes','2025-11-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10771','EDW/Datamart Enhancements: Integrate NFP Group Excess data into EDW','Enhancement','2025-11-15','Dinesh Bobbili','Modification','edw_core','trenewal_summary','','Integrated NFP data into this table','45','Yes','2025-11-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10771','EDW/Datamart Enhancements: Integrate NFP Group Excess data into EDW','Enhancement','2025-11-15','Dinesh Bobbili','Modification','edw_core','tbroker_summary','','Integrated NFP data into this table','45','Yes','2025-11-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10771','EDW/Datamart Enhancements: Integrate NFP Group Excess data into EDW','Enhancement','2025-11-15','Architha Gudimalla','Modification','edw_integration','customer_hubspot_feed','','Excluded NFP data to be loaded in this table','45','Yes','2025-11-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10771','EDW/Datamart Enhancements: Integrate NFP Group Excess data into EDW','Enhancement','2025-11-15','Architha Gudimalla','Modification','edw_integration','quote_hubspot_feed','','Excluded NFP data to be loaded in this table','45','Yes','2025-11-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10771','EDW/Datamart Enhancements: Integrate NFP Group Excess data into EDW','Enhancement','2025-11-15','Yunus Mohammed','Modification','edw_core','policy_workday_unearned_premium_feed','','Excluded NFP data to be loaded in this table','45','Yes','2025-11-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10771','EDW/Datamart Enhancements: Integrate NFP Group Excess data into EDW','Enhancement','2025-11-15','Yunus Mohammed','Modification','edw_core','policy_workday_written_premium_feed','','Excluded NFP data to be loaded in this table','45','Yes','2025-11-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10771','EDW/Datamart Enhancements: Integrate NFP Group Excess data into EDW','Enhancement','2025-11-15','Yunus Mohammed','Modification','edw_core','claim_workday_payment_feed','','Fetch NFP policy details from base tables','45','Yes','2025-11-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10771','EDW/Datamart Enhancements: Integrate NFP Group Excess data into EDW','Enhancement','2025-11-15','Yunus Mohammed','Modification','edw_core','claim_workday_reserve_feed','','Fetch NFP policy details from base tables','45','Yes','2025-11-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10771','EDW/Datamart Enhancements: Integrate NFP Group Excess data into EDW','Enhancement','2025-11-15','Yunus Mohammed','Modification','edw_core','claim_workday_itd_reserve_feed','','Fetch NFP policy details from base tables','45','Yes','2025-11-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10771','EDW/Datamart Enhancements: Integrate NFP Group Excess data into EDW','Enhancement','2025-11-15','Yunus Mohammed','Modification','edw_core','tclaim','','Update policy_sk, policy_history_sk, product_sk, broker_id and customer_id associated with NFP data','45','Yes','2025-11-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10771','EDW/Datamart Enhancements: Integrate NFP Group Excess data into EDW','Enhancement','2025-11-15','Yunus Mohammed','Modification','edw_core','tclaim_feature','','Update policy_sk, policy_history_sk, product_sk, broker_id and customer_id associated with NFP data','45','Yes','2025-11-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10771','EDW/Datamart Enhancements: Integrate NFP Group Excess data into EDW','Enhancement','2025-11-15','Yunus Mohammed','Modification','edw_core','tclaim_transaction','','Update policy_sk, policy_history_sk, product_sk, broker_id and customer_id associated with NFP data','45','Yes','2025-11-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10771','EDW/Datamart Enhancements: Integrate NFP Group Excess data into EDW','Enhancement','2025-11-15','Yunus Mohammed','Modification','edw_core','tclaim_summary','','Update policy_sk, policy_history_sk, product_sk, broker_id and customer_id associated with NFP data','45','Yes','2025-11-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10771','EDW/Datamart Enhancements: Integrate NFP Group Excess data into EDW','Enhancement','2025-11-15','Yunus Mohammed','Modification','edw_core','tclaim_feature_summary','','Update policy_sk, policy_history_sk, product_sk, broker_id and customer_id associated with NFP data','45','Yes','2025-11-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10771','EDW/Datamart Enhancements: Integrate NFP Group Excess data into EDW','Enhancement','2025-11-15','Yunus Mohammed','Modification','edw_integration','claim_renewal_rating_auto_pel_api','','Integrated NFP data into this table','45','Yes','2025-11-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC44013/INC44014','IVANS Policy Resent Request','Bug','2025-11-15','Rushin Shah','Datafix','edw_integration','policy_ivans_home_feed','','Resent a few home policies to IVANS','45','Yes','2025-11-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC44013/INC44014','IVANS Policy Resent Request','Bug','2025-11-15','Rushin Shah','Datafix','edw_integration','policy_ivans_auto_feed','','Resent a few auto policies to IVANS','45','Yes','2025-11-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC44013/INC44014','IVANS Policy Resent Request','Bug','2025-11-15','Rushin Shah','Datafix','edw_integration','policy_ivans_pel_feed','','Resent a few PEL policies to IVANS','45','Yes','2025-11-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10499','Process Improvements : Updated validations to tvalidation_sql','Enhancement','2025-11-15','Yunus Mohammed','Modification','edw_core','tvalidation_sql','','Few validation SQL were refined to enhance accuracy','45','Yes','2025-11-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10988','Data Fixes: Fix commercial policy which had policy number as 0','Bug','2025-11-15','Rushin Shah','Datafix','edw_stage','AccountTransaction','PolicyNumber','Fixed commercial policy which had policy number as 0 in Metal and EDW.  This is just a one time update.','45','Yes','2025-11-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD10988','Data Fixes: Fix commercial policy which had policy number as 0','Bug','2025-11-15','Rushin Shah','Datafix','edw_stage','AccountTransaction','state','Fixed commercial policy which had policy number as 0 in Metal and EDW.  This is just a one time update.','45','Yes','2025-11-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC43921','Data Fixes: Update IsDeletedOnRenewal indicator for EX100095343-04 in Metal','Bug','2025-11-15','Rushin Shah','Datafix','edw_stage','AccountTransactionVersionObject','IsDeletedOnRenewal','Updated IsDeletedOnRenewal indicator for EX100095343-04 in Metal. This is just a onetime update.','45','Yes','2025-11-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC43921','Data Fixes: Update IsDeletedOnRenewal indicator for EX100095343-04 in Metal','Bug','2025-11-15','Rushin Shah','Datafix','edw_stage','AccountObject','IsDeletedOnRenewal','Updated IsDeletedOnRenewal indicator for EX100095343-04 in Metal. This is just a onetime update.','45','Yes','2025-11-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC43652','EDW/Datamart Enhancements:  Updated policy attributes for 2 commercial policies M5020227 and M5020229 in Metal and EDW.  This is just a onetime update.','Bug','2025-11-15','Yunus Mohammed','Datafix','edw_commercial','tcommercial_policy','effective_dt','Updated effectivedate, expirationdate, originaleffectivedate, accountingeffectivedate, transactioneffectivedate and duedate for 2 commercial policies M5020227 and M5020229 in Metal and EDW.  This is just a onetime update.','45','Yes','2025-11-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC43652','EDW/Datamart Enhancements:  Updated policy attributes for 2 commercial policies M5020227 and M5020229 in Metal and EDW.  This is just a onetime update.','Bug','2025-11-15','Yunus Mohammed','Datafix','edw_commercial','tcommercial_policy','expiration_dt','Updated effectivedate, expirationdate, originaleffectivedate, accountingeffectivedate, transactioneffectivedate and duedate for 2 commercial policies M5020227 and M5020229 in Metal and EDW.  This is just a onetime update.','45','Yes','2025-11-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC43652','EDW/Datamart Enhancements:  Updated policy attributes for 2 commercial policies M5020227 and M5020229 in Metal and EDW.  This is just a onetime update.','Bug','2025-11-15','Yunus Mohammed','Datafix','edw_commercial','tcommercial_quote','effective_dt','Updated effectivedate, expirationdate, originaleffectivedate, accountingeffectivedate, transactioneffectivedate and duedate for 2 commercial policies M5020227 and M5020229 in Metal and EDW.  This is just a onetime update.','45','Yes','2025-11-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC43652','EDW/Datamart Enhancements:  Updated policy attributes for 2 commercial policies M5020227 and M5020229 in Metal and EDW.  This is just a onetime update.','Bug','2025-11-15','Yunus Mohammed','Datafix','edw_commercial','tcommercial_quote','expiration_dt','Updated effectivedate, expirationdate, originaleffectivedate, accountingeffectivedate, transactioneffectivedate and duedate for 2 commercial policies M5020227 and M5020229 in Metal and EDW.  This is just a onetime update.','45','Yes','2025-11-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11564','Data Fixes : Update brokerage affiliation values in Metal based on user request','Bug','2025-11-15','Bhaskar Muthyala','Datafix','edw_stage','Brokerage','Affiliation','Updated brokerage affiliation values in Metal based on user request.  This is just a onetime update','45','Yes','2025-11-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11564','Data Fixes : Update brokerage affiliation values in Metal based on user request','Bug','2025-11-15','Bhaskar Muthyala','Datafix','edw_stage','Brokerage','IsAffiliation','Updated brokerage affiliation values in Metal based on user request.  This is just a onetime update','45','Yes','2025-11-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11564','Data Fixes : Update brokerage affiliation values in Metal based on user request','Bug','2025-11-15','Bhaskar Muthyala','Datafix','edw_stage','Brokerage','UpdatedDate','Updated brokerage affiliation values in Metal based on user request.  This is just a onetime update','45','Yes','2025-11-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11585','Data Fixes : Update relationship_to_insured for AU100092568-04 and AU100101364-04','Bug','2025-11-15','Tuba Mohsin','Datafix','edw_core','tauto_driver','relationship_to_insured','Updated relationship_to_insured for AU100092568-04 and AU100101364-04. Data is updated in Metal and EDW. This is just a onetime update.','45','Yes','2025-11-17',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11585','Data Fixes : Update relationship_to_insured for AU100092568-04 and AU100101364-04','Bug','2025-11-15','Tuba Mohsin','Datafix','edw_core','tquote_auto_driver','relationship_to_insured','Updated relationship_to_insured for AU100092568-04 and AU100101364-04. Data is updated in Metal and EDW. This is just a onetime update.','45','Yes','2025-11-17',getdate(),getdate());
