INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 12/22/2025 :</span>
    <h4 style="margin-top: 0;font-style: italic;color: blue;">This release had 2 enhancements and 9 bug fix tickets.  Release details are as follows.</h4>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; }
        h1, h2 { color: #333; }
        ul { margin: 10px 0; padding-left: 20px; }
    </style>
</head>
<body>
    <h2 style="font-style: italic;">1. EDW/Datamart Enhancements</h2>
    <ul>
        <li>Updated the stored procedure logic to fix missing payee_address in tclaim_payment and tcommercial_claim_payment </li>
        </ul>
    <h2 style="font-style: italic;">2. Process Enhancements</h2>
    <ul>
        <li>Added validations to identify duplicates in workday tables</li>
   </ul>
    <h2 style="font-style: italic;">3. EDW Integrations</h2>
    <h3>a. IVANS</h3>
    <ul>
        <li>AD12016: Updated IVANS Home stored procedure to correctly populate Home_Collection_Coverages field</li>
        <li>INC45840/INC45783/INC45777 : Resent few IVANS policies associated with these tickets</li>
    </ul>
    <h2 style="font-style: italic;">4. Data Fixes</h2>
    <ul>
        <li>AD12039: Updated relationship_to_insured in tauto_driver for an excluded driver to stay in compliance for current carrier (AU100024659)</li>
        <li>AD12015: Updated NetPremiumDeltaProRated = NULL in Metal and EDW for one commercial policy (1010067)</li>
        <li>AD12054: Updated RiskAddressLine2 = NULL in Metal and EDW for one policy and its renewal term (HO100111997-03 & HO100111997-04)</li>
        <li>AD11993: Updated transaction status for one policy HO200089867 in Metal and EDW</li>
   </ul>
</body>
'
,'Yes'
,'2025-12-22'
,getdate()
,getdate()
)
;
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC45840/INC45783/INC45777','IVANS Policy Resent Request','Bug','2025-12-20','Rushin Shah','Datafix','edw_integration','policy_ivans_home_feed','','Resent a few home policies to IVANS','48','Yes','2025-12-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC45840/INC45783/INC45777','IVANS Policy Resent Request','Bug','2025-12-20','Rushin Shah','Datafix','edw_integration','policy_ivans_auto_feed','','Resent a few auto policies to IVANS','48','Yes','2025-12-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC45840/INC45783/INC45777','IVANS Policy Resent Request','Bug','2025-12-20','Rushin Shah','Datafix','edw_integration','policy_ivans_pel_feed','','Resent a few PEL policies to IVANS','48','Yes','2025-12-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12016','EDW Data Integrations : IVANS Home code fix','Bug','2025-12-20','Hernando Gonzalez Garcia','Modification','edw_integration','policy_ivans_home_feed','Home_Collection_Coverages ','Updated IVANS Home stored procedure to correctly populate Home_Collection_Coverages field','48','Yes','2025-12-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12039','Data Fixes : Update relationship_to_insured for AU100024659','Bug','2025-12-20','Tuba Mohsin','Datafix','edw_core','tauto_driver','relationship_to_insured','Updated relationship_to_insured for AU100024659. Data is updated in Metal and EDW. This is just a onetime update. ','48','Yes','2025-12-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12039','Data Fixes : Update relationship_to_insured for AU100024659','Bug','2025-12-20','Tuba Mohsin','Datafix','edw_core','tquote_auto_driver','relationship_to_insured','Updated relationship_to_insured for AU100024659. Data is updated in Metal and EDW. This is just a onetime update. ','48','Yes','2025-12-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12015','Data Fixes : Data fix for commercial policy 1010067','Bug','2025-12-20','Rushin Shah','Datafix','edw_commercial','tcommercial_policy_transaction ','premium_amt ','Updated premium amount fields for commercial policy 1010067 in EDW.  This is just a onetime update.','48','Yes','2025-12-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12015','Data Fixes : Data fix for commercial policy 1010067','Bug','2025-12-20','Rushin Shah','Datafix','edw_commercial','tcommercial_policy_transaction ','net_premium_amt ','Updated premium amount fields for commercial policy 1010067 in EDW.  This is just a onetime update.','48','Yes','2025-12-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12015','Data Fixes : Data fix for commercial policy 1010067','Bug','2025-12-20','Rushin Shah','Datafix','edw_commercial','tcommercial_policy_transaction ','annual_premium_amt  ','Updated premium amount fields for commercial policy 1010067 in EDW.  This is just a onetime update.','48','Yes','2025-12-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12015','Data Fixes : Data fix for commercial policy 1010067','Bug','2025-12-20','Rushin Shah','Datafix','edw_commercial','tcommercial_policy_transaction ','annual_net_premium_amt ','Updated premium amount fields for commercial policy 1010067 in EDW.  This is just a onetime update.','48','Yes','2025-12-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11984','Process Improvements : Updated validations to tvalidation_sql','Enhancement','2025-12-20','Yunus Mohammed','Modification','edw_core','tvalidation_sql','','Few validation SQL were added','48','Yes','2025-12-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11923','EDW Integrations : Updated claim payment address logic to use address fields from financial_payment_details','Enhancement','2025-12-20','Dinesh Bobbili','Modification','edw_core','tclaim_payment','','Updated the stored procedure logic to fix missing payee_address in tclaim_payment','48','Yes','2025-12-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11923','EDW Integrations : Updated claim payment address logic to use address fields from financial_payment_details','Enhancement','2025-12-20','Dinesh Bobbili','Modification','edw_commercial','tcommercial_claim_payment','','Updated the stored procedure logic to fix missing payee_address in tcommercial_claim_payment','48','Yes','2025-12-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11948','Data Fixes : Updated tax_fee_surcharge_sk for nfp in tpolicy_transaction table','Bug','2025-12-20','Dinesh Bobbili','Datafix','edw_core','tpolicy_transaction ','tax_fee_surcharge_sk ','Updated tpolicy_transaction stored procedure to fix tax_fee_surcharge_sk for nfp','48','Yes','2025-12-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11993','Data Fixes : HO200089867 - Error reversing transaction on out os status endorsement','Bug','2025-12-20','Tuba Mohsin','Datafix','edw_core','tpolicy_history','transaction_status','Updated transaction_status for HO200089867. Data is updated in Metal and EDW. This is just a onetime update. ','48','Yes','2025-12-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12054','Data Fixes : Update address_line_2 for policy no HO100111997-03, HO100111997-04','Bug','2025-12-20','Tuba Mohsin','Datafix','edw_core','thome_location','address_line_2 ','Updated address_line_2 for HO100111997-03 & HO100111997-04. Data is updated in Metal and EDW. This is just a onetime update. ','48','Yes','2025-12-22',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12054','Data Fixes : Update address_line_2 for policy no HO100111997-03, HO100111997-04','Bug','2025-12-20','Tuba Mohsin','Datafix','edw_core','tquote_home_location','address_line_2 ','Updated address_line_2 for HO100111997-03 & HO100111997-04. Data is updated in Metal and EDW. This is just a onetime update. ','48','Yes','2025-12-22',getdate(),getdate());