INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 01/12/2026 :</span>
    <h4 style="margin-top: 0;font-style: italic;color: blue;">This release had 6 enhancements and 12 bug fix tickets.  Release details are as follows.</h4>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; }
        h1, h2 { color: #333; }
        ul { margin: 10px 0; padding-left: 20px; }
    </style>
</head>
<body>
    <h2 style="font-style: italic;">1. EDW/Datamart Enhancements</h2>
    <ul>
        <li>Created following new tables to capture lending loss details.
            <ul>
                <li>tauto_policy_lending_loss</li>
                <li>tquote_auto_policy_lending_loss</li>
                <li>tpel_policy_lending_loss</li>
                <li>tquote_pel_policy_lending_loss</li>
            </ul>
        </li>
        <li>Added column indication_staus to tquote_history table</li>
        <li>Added column non_binding_indication_offered_in to tquote table</li>
        <li>Added column current_producer_nm to tpolicy and tquote tables</li>
        <li>Added column current_underwriter_nm to tpolicy and tquote tables</li>
        <li>Added column current_producer_sk to tpolicy and tquote tables</li>
        <li>Updated stored procedure to fix content_desc column on tclaim_note table</li>
    </ul>
    <h2 style="font-style: italic;">2. Commercial EDW Enhancements</h2>
    <ul>
        <li>Updated stored procedure to fix content_desc column on tcommercial_claim_note table</li>
        <li>Dropped column salvage_recover_expense_reserve_amt from tcommercial_claim table</li>
    </ul>
    
    <h2 style="font-style: italic;">3. EDW Integrations</h2>
    <li>a. Customer midterm personal recommendation process is going live</li>
    <li>b. IVANS : Resent IVANS policies associated with these INC46544/INC46970/INC46972 tickets</li>

    <h2 style="font-style: italic;">4. Data Fixes</h2>
    <ul>
        <li>INC43164: Updated uninsured_motorist_limit_amt to NULL for 343 transactions associated with combined limits in Metal and EDW. This is just a one time update.</li>
        <li>INC46154: Updated IsReversed flag to 0 for the policy CO200023663-01 in Metal and EDW. This is just a one time update.</li>
        <li>INC47013: Updated broker_id associated with 4 commercial policies in Metal and EDW.  This is just a onetime update. </li>
        <li>AD12123: Updated premium_amt, net_premium_amt, annual_premium_amt and commission_amt in  tcommercial_policy_transaction and tcommercial_policy_history tables for one commercial policy : M5020235. This is just a one time update. </li>
        <li>AD12163: Updated latitude and longitude for 8 policies in EDW and Metal. This is just a one time update. </li>
        <li>AD12129: Updated subrogation_recovery_expense_reserve_amt in tclaim_transaction for one closed claim C21HOA00850. This is a one time update. </li>
        <li>AD12144: Fixed 4 records associated with incorrect coverage category in Metal and EDW. This is just a one time update. </li>
  </ul>
</body>
'
,'Yes'
,'2026-01-12'
,getdate()
,getdate()
)
;

INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC46544/INC46970/INC46972','IVANS Policy Resent Request','Bug','2026-01-10','Rushin Shah','Datafix','edw_integration','policy_ivans_collections_feed','','Resent a few home policies to IVANS','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC46544/INC46970/INC46972','IVANS Policy Resent Request','Bug','2026-01-10','Rushin Shah','Datafix','edw_integration','policy_ivans_home_feed','','Resent a few collection policies to IVANS','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC46544/INC46970/INC46972','IVANS Policy Resent Request','Bug','2026-01-10','Rushin Shah','Datafix','edw_integration','policy_ivans_auto_feed','','Resent a few home policies to IVANS','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC46544/INC46970/INC46972','IVANS Policy Resent Request','Bug','2026-01-10','Rushin Shah','Datafix','edw_integration','policy_ivans_pel_feed','','Resent a few collection policies to IVANS','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12163','Data Fixes : Updated latitude & longitude for 8 policies','Bug','2026-01-10','Tuba Mohsin','Datafix','edw_core','tcollection_location','latitude','Updated latitude & longitude for 8 policies. Data is updated in Metal and EDW. This is just a onetime update. ','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12163','Data Fixes : Updated latitude & longitude for 8 policies','Bug','2026-01-10','Tuba Mohsin','Datafix','edw_core','tcollection_location','longitude','Updated latitude & longitude for 8 policies. Data is updated in Metal and EDW. This is just a onetime update. ','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12163','Data Fixes : Updated latitude & longitude for 8 policies','Bug','2026-01-10','Tuba Mohsin','Datafix','edw_core','thome_location','latitude','Updated latitude & longitude for 8 policies. Data is updated in Metal and EDW. This is just a onetime update. ','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12163','Data Fixes : Updated latitude & longitude for 8 policies','Bug','2026-01-10','Tuba Mohsin','Datafix','edw_core','thome_location','longitude','Updated latitude & longitude for 8 policies. Data is updated in Metal and EDW. This is just a onetime update. ','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12163','Data Fixes : Updated latitude & longitude for 8 policies','Bug','2026-01-10','Tuba Mohsin','Datafix','edw_core','tquote_collection_location','latitude','Updated latitude & longitude for 8 policies. Data is updated in Metal and EDW. This is just a onetime update. ','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12163','Data Fixes : Updated latitude & longitude for 8 policies','Bug','2026-01-10','Tuba Mohsin','Datafix','edw_core','tquote_collection_location','longitude','Updated latitude & longitude for 8 policies. Data is updated in Metal and EDW. This is just a onetime update. ','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12163','Data Fixes : Updated latitude & longitude for 8 policies','Bug','2026-01-10','Tuba Mohsin','Datafix','edw_core','tquote_home_location','latitude','Updated latitude & longitude for 8 policies. Data is updated in Metal and EDW. This is just a onetime update. ','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12163','Data Fixes : Updated latitude & longitude for 8 policies','Bug','2026-01-10','Tuba Mohsin','Datafix','edw_core','tquote_home_location','longitude','Updated latitude & longitude for 8 policies. Data is updated in Metal and EDW. This is just a onetime update. ','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11983','Data Fixes : Updated uninsured_motorist_limit_amt to null for Combined limit_type','Bug','2026-01-10','Dinesh Bobbili','Datafix','edw_core','tauto_policy_coverage','uninsured_motorist_limit_amt','Updated uninsured_motorist_limit_amt to null for Combined limit_type. Data is updated in Metal and EDW. This is just a onetime update. ','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11983','Data Fixes : Updated uninsured_motorist_limit_amt to null for Combined limit_type','Bug','2026-01-10','Dinesh Bobbili','Datafix','edw_core','tquote_auto_policy_coverage','uninsured_motorist_limit_amt','Updated uninsured_motorist_limit_amt to null for Combined limit_type. Data is updated in Metal and EDW. This is just a onetime update. ','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12123','Data Fixes : Updated amounts for commercial policy M5020235','Bug','2026-01-10','Rushin Shah','Datafix','edw_commercial','tcommercial_policy_transaction ','premium_amt','Updated premium_amt,net_premium_amt,annual_premium_amt,commission_amt for commercial policy M5020235. Data is updated in EDW. This is just a onetime update. ','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12123','Data Fixes : Updated amounts for commercial policy M5020235','Bug','2026-01-10','Rushin Shah','Datafix','edw_commercial','tcommercial_policy_transaction ','net_premium_amt','Updated premium_amt,net_premium_amt,annual_premium_amt,commission_amt for commercial policy M5020235. Data is updated in EDW. This is just a onetime update. ','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12123','Data Fixes : Updated amounts for commercial policy M5020235','Bug','2026-01-10','Rushin Shah','Datafix','edw_commercial','tcommercial_policy_transaction ','annual_premium_amt','Updated premium_amt,net_premium_amt,annual_premium_amt,commission_amt for commercial policy M5020235. Data is updated in EDW. This is just a onetime update. ','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12123','Data Fixes : Updated amounts for commercial policy M5020235','Bug','2026-01-10','Rushin Shah','Datafix','edw_commercial','tcommercial_policy_transaction ','commission_amt','Updated premium_amt,net_premium_amt,annual_premium_amt,commission_amt for commercial policy M5020235. Data is updated in EDW. This is just a onetime update. ','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12123','Data Fixes : Updated amounts for commercial policy M5020235','Bug','2026-01-10','Rushin Shah','Datafix','edw_commercial','tcommercial_policy_history ','premium_amt','Updated premium_amt,net_premium_amt,annual_premium_amt,commission_amt for commercial policy M5020235. Data is updated in EDW. This is just a onetime update. ','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12123','Data Fixes : Updated amounts for commercial policy M5020235','Bug','2026-01-10','Rushin Shah','Datafix','edw_commercial','tcommercial_policy_history ','net_premium_amt','Updated premium_amt,net_premium_amt,annual_premium_amt,commission_amt for commercial policy M5020235. Data is updated in EDW. This is just a onetime update. ','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12123','Data Fixes : Updated amounts for commercial policy M5020235','Bug','2026-01-10','Rushin Shah','Datafix','edw_commercial','tcommercial_policy_history ','annual_premium_amt','Updated premium_amt,net_premium_amt,annual_premium_amt,commission_amt for commercial policy M5020235. Data is updated in EDW. This is just a onetime update. ','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12123','Data Fixes : Updated amounts for commercial policy M5020235','Bug','2026-01-10','Rushin Shah','Datafix','edw_commercial','tcommercial_policy_history ','commission_amt','Updated premium_amt,net_premium_amt,annual_premium_amt,commission_amt for commercial policy M5020235. Data is updated in EDW. This is just a onetime update. ','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12124','Data Fixes : Updated IsReversed flag for CO200023663-01 for one of the transaction','Bug','2026-01-10','Rushin Shah','Datafix','edw_stage','AccountTransaction ','IsReversed ','Updated IsReversed flag for CO200023663-01 for one of the transaction. Data is updated in Metal & EDW. This is just a onetime update. ','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12129','Data Fixes : Updated subrogation_recovery_expense_reserve_amt for closed claim C21HOA00850','Bug','2026-01-10','Rushin Shah','Datafix','edw_core','tclaim_transaction','subrogation_recovery_expense_reserve_amt','Updated subrogation_recovery_expense_reserve_amt for closed claim C21HOA00850.Data is updated in EDW. This is just a onetime update. ','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12144','Data Fixes : Surplus Lines Tax transactions mapped to incorrect coverage category','Bug','2026-01-10','Rushin Shah','Datafix','edw_stage','AccountTransactionTaxAndFee','Type','Fixed 4 records associated with incorrect coverage category in Metal and EDW. This is just a one time update. ','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12144','Data Fixes : Surplus Lines Tax transactions mapped to incorrect coverage category','Bug','2026-01-10','Rushin Shah','Datafix','edw_stage','AccountPremiumTaxAndFee','Type','Fixed 4 records associated with incorrect coverage category in Metal and EDW. This is just a one time update. ','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12061','Data Fixes : Current Carrier  - Missing VIN AU200034181','Bug','2026-01-10','Tuba Mohsin','Datafix','edw_core','tauto_vehicle','vehicle_vin','Data is updated in Metal and EDW. This is just a onetime update. ','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12116','EDW/Datamart Enhancements: Drop column from tcommercial_claim table','Enhancement','2026-01-10','Yunus Mohammed','Deletion','edw_commercial','tcommercial_claim','salvage_recover_expense_reserve_amt','Dropped a column which had a typo','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12178','EDW/Datamart Enhancements: Created new column to tquote table','Enhancement','2026-01-10','Bhaskar Muthyala','Addition','edw_core','tquote','current_producer_nm','Created new column','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12178','EDW/Datamart Enhancements: Created new column to tquote table','Enhancement','2026-01-10','Bhaskar Muthyala','Addition','edw_core','tquote','current_underwriter_nm','Created new column','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12178','EDW/Datamart Enhancements: Created new column to tquote table','Enhancement','2026-01-10','Bhaskar Muthyala','Addition','edw_core','tquote','current_producer_sk','Created new column','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12178','EDW/Datamart Enhancements: Created new column to tpolicy table','Enhancement','2026-01-10','Bhaskar Muthyala','Addition','edw_core','tpolicy','current_producer_nm','Created new column','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12178','EDW/Datamart Enhancements: Created new column to tpolicy table','Enhancement','2026-01-10','Bhaskar Muthyala','Addition','edw_core','tpolicy','current_underwriter_nm','Created new column','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12178','EDW/Datamart Enhancements: Created new column to tpolicy table','Enhancement','2026-01-10','Bhaskar Muthyala','Addition','edw_core','tpolicy','current_producer_sk','Created new column','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12142','EDW/Datamart Enhancements: Created new column to tquote table','Enhancement','2026-01-10','Tuba Mohsin','Addition','edw_core','tquote','non_binding_indication_offered_in','Created new column','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12142','EDW/Datamart Enhancements: Created new column to tquote_history table','Enhancement','2026-01-10','Tuba Mohsin','Addition','edw_core','tquote_history','indication_status','Created new column','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12062','EDW/Datamart Enhancements: Created new table ','Enhancement','2026-01-10','Tuba Mohsin','Addition','edw_core','tauto_policy_lending_loss','','Created new table','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12062','EDW/Datamart Enhancements: Created new table ','Enhancement','2026-01-10','Tuba Mohsin','Addition','edw_core','tquote_auto_policy_lending_loss','','Created new table','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12062','EDW/Datamart Enhancements: Created new table ','Enhancement','2026-01-10','Tuba Mohsin','Addition','edw_core','tpel_policy_lending_loss','','Created new table','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12062','EDW/Datamart Enhancements: Created new table ','Enhancement','2026-01-10','Tuba Mohsin','Addition','edw_core','tquote_pel_policy_lending_loss','','Created new table','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11370','Data Fixes : content_desc fix','Bug','2026-01-10','Bhaskar Muthyala','Datafix','edw_core','tclaim_note','content_desc','Updated content_desc column. Data is updated in EDW. This is just a onetime update. ','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11370','Data Fixes : content_desc fix','Bug','2026-01-10','Bhaskar Muthyala','Datafix','edw_commercial','tcommercial_claim_note','content_desc','Updated content_desc column. Data is updated in EDW. This is just a onetime update. ','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC47013','Data Fixes : Move 4 commercial policies from one broker to other','Bug','2026-01-10','Yunus Mohammed','Datafix','edw_commercial','tcommercial_policy','broker_id','Updated broker_id associated with 4 commercial policies.  Data is updated in Metal and EDW.  This is just a onetime update.','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC47013','Data Fixes : Move 4 commercial policies from one broker to other','Bug','2026-01-10','Yunus Mohammed','Datafix','edw_commercial','tcommercial_policy_transaction','broker_id','Updated broker_id associated with 4 commercial policies.  Data is updated in Metal and EDW.  This is just a onetime update.','49','Yes','2026-01-12',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC47013','Data Fixes : Move 4 commercial policies from one broker to other','Bug','2026-01-10','Yunus Mohammed','Datafix','edw_commercial','tcommercial_policy_history','broker_id','Updated broker_id associated with 4 commercial policies.  Data is updated in Metal and EDW.  This is just a onetime update.','49','Yes','2026-01-12',getdate(),getdate());