INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 01/26/2026 :</span>
    <h4 style="margin-top: 0;font-style: italic;color: blue;">This release had 6 enhancements and 10 bug fix tickets.  Release details are as follows.</h4>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; }
        h1, h2 { color: #333; }
        ul { margin: 10px 0; padding-left: 20px; }
    </style>
</head>
<body>
    <h2 style="font-style: italic;">1. EDW/Datamart Enhancements</h2>
    <ul>
        <li>Updated tpolicy_history and tquote_history stored procedures to accurately map home_credit_in</li>
        <li>Added new column primary_home_credit_in to tpolicy_history and tquote_history tables</li>
    </ul>

    <h2 style="font-style: italic;">2. EDW Integrations</h2>
    <h3>a. Hubspot</h3>
    <ul>
        <li>Created a new table tbroker_goal for the new business agency goals report in HubSpot</li>
        <li>Updated tbroker_hubspot_feed to add the following fields :
            <ul>
                <li>homeowner_2026_premium_goal_amt</li>
                <li>homeowner_2026_premium_actual_amt</li>
                <li>homeowner_2026_goal_progress_pc</li>
            </ul>
        </li>
        <li>Updated quote_hubspot_feed logic to remove $ sign from  auto_liability_limit_amt column</li>
    </ul>

    <h3>b. IVANS</h3>
    <ul>
        <li>INC47029/INC46971/INC47060/INC47551/INC46968/INC46969/INC47026: Resend IVANS policies associated with these tickets</li>
    </ul>


    <h3>c. Customer midterm personal recommendation process</h3>
    <ul>
        <li>Excluded products that are not recommended from GhostDraft fee for midterm review</li>
        <li>Updated the logic for setting the midterm review completed date</li>
    </ul>    
    <h2 style="font-style: italic;">3. Data Fixes</h2>
    <ul>
        <li>INC47110: Updated effective date and expiration date for commercial policy number A5010267 in Metal and EDW. This is just a one time update.</li>
        <li>INC46815: Updated roof_deck_attachment in thome_coverage and tquote_home_coverage tables for SC homeowner policies in EDW. This is a one time update.</li>
        <li>INC47252: Updated the policy number for two commercial policies O1520304 and O1540305 in Metal and EDW. This is just a one time update.</li>

    </ul>
</body>
'
,'Yes'
,'2026-01-26'
,getdate()
,getdate()
)
;

INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC47029/INC46971/INC47060/INC47551/INC46968/INC46969/INC47026','IVANS Policy Resent Request','Bug','2026-01-23','Rushin Shah','Datafix','edw_integration','policy_ivans_collections_feed','','Resent a few home policies to IVANS','50','Yes','2026-01-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC47029/INC46971/INC47060/INC47551/INC46968/INC46969/INC47026','IVANS Policy Resent Request','Bug','2026-01-23','Rushin Shah','Datafix','edw_integration','policy_ivans_home_feed','','Resent a few home policies to IVANS','50','Yes','2026-01-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC47029/INC46971/INC47060/INC47551/INC46968/INC46969/INC47026','IVANS Policy Resent Request','Bug','2026-01-23','Rushin Shah','Datafix','edw_integration','policy_ivans_auto_feed','','Resent a few auto policies to IVANS','50','Yes','2026-01-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC47029/INC46971/INC47060/INC47551/INC46968/INC46969/INC47026','IVANS Policy Resent Request','Bug','2026-01-23','Rushin Shah','Datafix','edw_integration','policy_ivans_pel_feed','','Resent a few pel policies to IVANS','50','Yes','2026-01-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12220','Data Fixes : INC#47252: Booked account with wrong dates, need to keep the policy number','Bug','2026-01-23','Yunus Mohammed','Datafix','edw_commercial','tcommercial_policy','policy_no','Renamed the policies O1520304 to M1520304, O1540305 to O1540305_00000000 . Data is updated EDW. This is just a onetime update. ','50','Yes','2026-01-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12220','Data Fixes : INC#47252: Booked account with wrong dates, need to keep the policy number','Bug','2026-01-23','Yunus Mohammed','Datafix','edw_commercial','tcommercial_policy_history','policy_no','Renamed the policies O1520304 to M1520304, O1540305 to O1540305_00000000 . Data is updated EDW. This is just a onetime update. ','50','Yes','2026-01-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12220','Data Fixes : INC#47252: Booked account with wrong dates, need to keep the policy number','Bug','2026-01-23','Yunus Mohammed','Datafix','edw_commercial','tcommercial_policy_tower','policy_no','Renamed the policies O1520304 to M1520304, O1540305 to O1540305_00000000 . Data is updated EDW. This is just a onetime update. ','50','Yes','2026-01-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12220','Data Fixes : INC#47252: Booked account with wrong dates, need to keep the policy number','Bug','2026-01-23','Yunus Mohammed','Datafix','edw_commercial','tcommercial_policy_quota_share','policy_no','Renamed the policies O1520304 to M1520304, O1540305 to O1540305_00000000 . Data is updated EDW. This is just a onetime update. ','50','Yes','2026-01-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12220','Data Fixes : INC#47252: Booked account with wrong dates, need to keep the policy number','Bug','2026-01-23','Yunus Mohammed','Datafix','edw_commercial','tcommercial_policy_subjectivity','policy_no','Renamed the policies O1520304 to M1520304, O1540305 to O1540305_00000000 . Data is updated EDW. This is just a onetime update. ','50','Yes','2026-01-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12220','Data Fixes : INC#47252: Booked account with wrong dates, need to keep the policy number','Bug','2026-01-23','Yunus Mohammed','Datafix','edw_commercial','tcommercial_policy_coverage','policy_no','Renamed the policies O1520304 to M1520304, O1540305 to O1540305_00000000 . Data is updated EDW. This is just a onetime update. ','50','Yes','2026-01-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12220','Data Fixes : INC#47252: Booked account with wrong dates, need to keep the policy number','Bug','2026-01-23','Yunus Mohammed','Datafix','edw_commercial','tcommercial_claim','policy_no','Renamed the policies O1520304 to M1520304, O1540305 to O1540305_00000000 . Data is updated EDW. This is just a onetime update. ','50','Yes','2026-01-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12255','Data Fixes : INC47110  Booked account with wrong dates, need to keep the policy number','Bug','2026-01-23','Yunus Mohammed','Datafix','edw_commercial','tcommercial_policy','policy_no','Updated effective_dt for one commercial policy. Data is updated in Metal and EDW. This is just a onetime update. ','50','Yes','2026-01-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12255','Data Fixes : INC47110  Booked account with wrong dates, need to keep the policy number','Bug','2026-01-23','Yunus Mohammed','Datafix','edw_commercial','tcommercial_policy_history','policy_no','Updated effective_dt for one commercial policy. Data is updated in Metal and EDW. This is just a onetime update. ','50','Yes','2026-01-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12255','Data Fixes : INC47110  Booked account with wrong dates, need to keep the policy number','Bug','2026-01-23','Yunus Mohammed','Datafix','edw_commercial','tcommercial_policy_tower','policy_no','Updated effective_dt for one commercial policy. Data is updated in Metal and EDW. This is just a onetime update. ','50','Yes','2026-01-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12255','Data Fixes : INC47110  Booked account with wrong dates, need to keep the policy number','Bug','2026-01-23','Yunus Mohammed','Datafix','edw_commercial','tcommercial_policy_quota_share','policy_no','Updated effective_dt for one commercial policy. Data is updated in Metal and EDW. This is just a onetime update. ','50','Yes','2026-01-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12255','Data Fixes : INC47110  Booked account with wrong dates, need to keep the policy number','Bug','2026-01-23','Yunus Mohammed','Datafix','edw_commercial','tcommercial_policy_subjectivity','policy_no','Updated effective_dt for one commercial policy. Data is updated in Metal and EDW. This is just a onetime update. ','50','Yes','2026-01-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12255','Data Fixes : INC47110  Booked account with wrong dates, need to keep the policy number','Bug','2026-01-23','Yunus Mohammed','Datafix','edw_commercial','tcommercial_policy_coverage','policy_no','Updated effective_dt for one commercial policy. Data is updated in Metal and EDW. This is just a onetime update. ','50','Yes','2026-01-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12255','Data Fixes : INC47110  Booked account with wrong dates, need to keep the policy number','Bug','2026-01-23','Yunus Mohammed','Datafix','edw_commercial','tcommercial_claim','policy_no','Updated effective_dt for one commercial policy. Data is updated in Metal and EDW. This is just a onetime update. ','50','Yes','2026-01-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12148','Data Fixes : INC-46815 Missing Data in EDW that is in Metal JSON for RoofDeckAttachment Fields','Bug','2026-01-23','Dinesh Bobbili','Datafix','edw_core','thome_coverage','roof_deck_attachment','Updated roof_deck_attachment data for SC Home policies in Metal and EDW. This is just a onetime update. ','50','Yes','2026-01-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12148','Data Fixes : INC-46815 Missing Data in EDW that is in Metal JSON for RoofDeckAttachment Fields','Bug','2026-01-23','Dinesh Bobbili','Datafix','edw_core','tquote_home_coverage','roof_deck_attachment','Updated roof_deck_attachment data for SC Home quotes in Metal and EDW. This is just a onetime update. ','50','Yes','2026-01-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12293','EDW/Datamart Enhancements: tpolicy_history - primary_home_credit_in','Enhancement','2026-01-23','Yunus Mohammed','Addition','edw_core','tpolicy_history','primary_home_credit_in','Created new column','50','Yes','2026-01-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12293','EDW/Datamart Enhancements: tquote_history - primary_home_credit_in','Enhancement','2026-01-23','Yunus Mohammed','Addition','edw_core','tquote_history','primary_home_credit_in','Created new column','50','Yes','2026-01-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12217','EDW/Datamart Enhancements: Updated stored procedure to accurately map home_credit_in','Enhancement','2026-01-23','Yunus Mohammed','Modification','edw_core','tpolicy_history','home_credit_in','Updated stored procedures to accurately map home_credit_in','50','Yes','2026-01-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12217','EDW/Datamart Enhancements: Updated stored procedure to accurately map home_credit_in','Enhancement','2026-01-23','Yunus Mohammed','Modification','edw_core','tquote_history','home_credit_in','Updated stored procedures to accurately map home_credit_in','50','Yes','2026-01-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12246','EDW Integrations :  Creation of tbroker_goal table for hubspot','Enhancement','2026-01-23','Sandeep Gundreddy','Addition','edw_core','tbroker_goal',' ','Created new table','50','Yes','2026-01-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12143','EDW Integrations :  Field additions to hubspot tables','Enhancement','2026-01-23','Dinesh Bobbili','Addition','edw_integration','quote_hubspot_feed','non_binding_indication_offered_in','Created new column','50','Yes','2026-01-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12143','EDW Integrations :  Field additions to hubspot tables','Enhancement','2026-01-23','Dinesh Bobbili','Addition','edw_integration','broker_hubspot_feed','homeowner_2026_premium_goal_amt','Created new column','50','Yes','2026-01-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12143','EDW Integrations :  Field additions to hubspot tables','Enhancement','2026-01-23','Dinesh Bobbili','Addition','edw_integration','broker_hubspot_feed','homeowner_2026_premium_actual_amt','Created new column','50','Yes','2026-01-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12143','EDW Integrations :  Field additions to hubspot tables','Enhancement','2026-01-23','Dinesh Bobbili','Addition','edw_integration','broker_hubspot_feed','homeowner_2026_goal_progress_pc','Created new column','50','Yes','2026-01-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12315','EDW Integrations :  Fix auto_liability_limit_amt format in quote_hubspot_feed','Enhancement','2026-01-23','Architha Gudimalla','Addition','edw_integration','quote_hubspot_feed','auto_liability_limit_amt','Updated quote_hubspot_feed logic to remove $ sign from  auto_liability_limit_amt column','50','Yes','2026-01-26',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12205','EDW Integrations :  Customer MidTerm Review','Enhancement','2026-01-23','Bhaskar Muthyala','Modification','edw_integration','customer_midterm_review_eligibility_feed',' ','Updated logic to exclude products that are not recommended from GhostDraft feed and logic to set the midterm review completed date ','50','Yes','2026-01-26',getdate(),getdate());