INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 02/09/2026 :</span>
    <h4 style="margin-top: 0;font-style: italic;color: blue;">This release had 10 enhancements and 12 bug fix tickets.  Release details are as follows.</h4>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; }
        h1, h2 { color: #333; }
        ul { margin: 10px 0; padding-left: 20px; }
    </style>
</head>
<body>
    <h2 style="font-style: italic;">1. EDW/Datamart Enhancements</h2>
    <ul>
        <li>Added the following columns to thome_coverage and tquote_home_coverage tables
          <ul>
                <li>high_risk_wui_property_in</li>
                <li>effective_built_year</li>
          </ul>
        </li>
        <li>Added the following columns to tpel_location and tquote_pel_location tables
          <ul>
                <li>owned_by_trust_llc_or_other_entity_in</li>
                <li>trust_or_legal_entity_legal_nm</li>
                <li>trust_or_legal_entity_mailing_address</li>
                <li>trust_or_legal_entity_purpose</li>
                <li>trust_or_legal_entity_asset_use_or_possession</li>
                <li>trust_or_legal_entity_grantor_and_beneficiaries</li>
                <li>trust_or_legal_entity_membership_details</li>
                <li>trust_or_legal_entity_owned_holding_or_assets</li>
                <li>trust_or_legal_entity_business_activities</li>
                <li>trust_or_legal_entity_insurance_coverage</li>
                <li>trust_or_legal_entity_employees_and_reponsibilities</li>
                <li>trust_or_legal_entity_income_details</li>
                <li>additional_owners_in</li>
                <li>business_operations_in</li>
                <li>rented_outside_owners_family_in</li>
                <li>home_type</li>
                <li>occupancy_type</li>
                <li>under_construction_or_renovation_in</li>
          </ul>
        </li>
        <li>Added the column - theft_or_loss_general_conditions_approval_in to thome_additional_coverage, tquote_home_additional_coverage, tcollection_coverage, tquote_collection_coverage tables</li>
        <li>Updated the vhome_coverage_ext view to include the Extended Liability fields and the Additional Insured Trustee fields</li>
        <li>Created the table broker_commission_email_api to send data to the API call that will replace the commissions bot</li>
        <li>Added the column -  california_dba_nm to tbroker table </li>
        <li>Modified the stored procedure to include additional transaction type to update billing_paid_in in tpolicy table</li>
        <li>Added the following retention column to trenewal_summary table
          <ul>
                <li>renewal_rate_on_line_amt</li>
                <li>outstanding_in_progress_renewal_ct</li>
                <li>closed_with_no_offer_pending_process_renewal_ct</li>
          </ul>
        </li>
    </ul>
    <h2 style="font-style: italic;">2. EDW Integrations</h2>
    <h3>a. Workday Enhancements</h3>
    <ul>
        <li>Updated product name from Marine Boat & Yacht to Marine_Boat&Yacht in workday files</li>
    </ul>
    <h3>b. Hubspot</h3>
    <ul>
        <li>Created an enhanced email‑notification process for Hubspot to report integration errors</li>
        <li>Added total policy premium to the customer Hubspot feed</li>
    </ul>
    <h3>c. Customer midterm personal recommendation process</h3>
    <ul>
        <li>Updated missing state codes in the customer address records for 9 customers in EDW and Metal</li>
        <li>Updated stored procedure to clean up customer names so they are formatted in clean, proper capitalization</li>
    </ul>
    <h3>d. IVANS</h3>
    <ul>
        <li>INC47839: Updated the IVANS collection feed stored procedure to not send the deleted scheduled items</li>
        <li>INC48106: Resent IVANS policies associated with this ticket</li>
    </ul>
    <h2 style="font-style: italic;">3. Data Fixes</h2>
    <ul>
        <li>INC48088: Updated the commercial policy number from x01540305 to O1540305 in Metal and EDW. This is just a one time update.</li>
        <li>AD12366: Updated latitude and longitude for 9 policies in Metal and EDW. This is just a one time update.</li>
        <li>AD12431: Updated issued date and bind date for HO200070420-01 in Metal. This is just a one time update.</li>
        
        <li>INC48192: Updated initial rating tier for AU200033368 and AU200034176 in Metal and EDW. This is just a one time update.</li>
        <li>AD12383: Updated MVR vendor reports violation notes for EX100025490-05 and EX200029764-06 in EDW. This is just a one time update.</li>
        <li>AD12323: Updated missing VIN number on a vehicle for AU200035734 in Metal and EDW. This is just a one time update.</li>
        
        <li>AD12333 : Updated policy_sk in tclaim table associated with 2 claims C21AUA00240 and C22XLA00002.  This is just a one time update.</li>
        <li>AD12367: Updated primary insured flag on HO100227250-03 and HO100011280-05 in Metal and EDW. This is just a one time update.</li>
        <li>AD12495 : Updated Description from Vault Homeowners Application - IL to Vault Homeowners Application in Metal and EDW.  This is just a onetime update.</li>
    </ul>
</body>
'
,'Yes'
,'2026-02-09'
,getdate()
,getdate()
)
;

INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC48106','IVANS Policy Resent Request','Bug','2026-02-06','Rushin Shah','Datafix','edw_integration','policy_ivans_collections_feed','','Resent a few home policies to IVANS','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC48106','IVANS Policy Resent Request','Bug','2026-02-06','Rushin Shah','Datafix','edw_integration','policy_ivans_home_feed','','Resent a few home policies to IVANS','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC48106','IVANS Policy Resent Request','Bug','2026-02-06','Rushin Shah','Datafix','edw_integration','policy_ivans_auto_feed','','Resent a few auto policies to IVANS','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC48106','IVANS Policy Resent Request','Bug','2026-02-06','Rushin Shah','Datafix','edw_integration','policy_ivans_pel_feed','','Resent a few pel policies to IVANS','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','thome_coverage','high_risk_wui_property_in','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','tquote_home_coverage','high_risk_wui_property_in','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','thome_coverage','effective_built_year','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','tquote_home_coverage','effective_built_year','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','thome_additional_coverage','theft_or_loss_general_conditions_approval_in','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','tcollection_coverage','theft_or_loss_general_conditions_approval_in','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','tquote_collection_coverage','theft_or_loss_general_conditions_approval_in','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','tquote_home_additional_coverage','theft_or_loss_general_conditions_approval_in','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','tpel_location','owned_by_trust_llc_or_other_entity_in','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','tpel_location','trust_or_legal_entity_legal_nm','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','tpel_location','trust_or_legal_entity_mailing_address','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','tpel_location','trust_or_legal_entity_purpose','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','tpel_location','trust_or_legal_entity_asset_use_or_possession','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','tpel_location','trust_or_legal_entity_grantor_and_beneficiaries','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','tpel_location','trust_or_legal_entity_membership_details','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','tpel_location','trust_or_legal_entity_owned_holding_or_assets','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','tpel_location','trust_or_legal_entity_business_activities','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','tpel_location','trust_or_legal_entity_insurance_coverage','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','tpel_location','trust_or_legal_entity_employees_and_reponsibilities','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','tpel_location','trust_or_legal_entity_income_details','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','tpel_location','additional_owners_in','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','tpel_location','business_operations_in','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','tpel_location','rented_outside_owners_family_in','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','tpel_location','home_type','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','tpel_location','occupancy_type','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','tpel_location','under_construction_or_renovation_in','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','tquote_pel_location','owned_by_trust_llc_or_other_entity_in','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','tquote_pel_location','trust_or_legal_entity_legal_nm','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','tquote_pel_location','trust_or_legal_entity_mailing_address','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','tquote_pel_location','trust_or_legal_entity_purpose','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','tquote_pel_location','trust_or_legal_entity_asset_use_or_possession','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','tquote_pel_location','trust_or_legal_entity_grantor_and_beneficiaries','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','tquote_pel_location','trust_or_legal_entity_membership_details','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','tquote_pel_location','trust_or_legal_entity_owned_holding_or_assets','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','tquote_pel_location','trust_or_legal_entity_business_activities','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','tquote_pel_location','trust_or_legal_entity_insurance_coverage','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','tquote_pel_location','trust_or_legal_entity_employees_and_reponsibilities','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','tquote_pel_location','trust_or_legal_entity_income_details','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','tquote_pel_location','additional_owners_in','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','tquote_pel_location','business_operations_in','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','tquote_pel_location','rented_outside_owners_family_in','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','tquote_pel_location','home_type','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','tquote_pel_location','occupancy_type','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12414','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Tuba Mohsin','Addition','edw_core','tquote_pel_location','under_construction_or_renovation_in','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12402','EDW/Datamart Enhancements: Created new table ','Enhancement','2026-02-06','Rushin Shah','Addition','edw_integration','broker_commission_email_api','','Created new table','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12472','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Rushin Shah','Addition','edw_stage','Brokerage','DBAforCA','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12472','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Rushin Shah','Addition','edw_core','tbroker','california_dba_nm','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12426','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Architha Gudimalla','Addition','edw_core','trenewal_summary','renewal_rate_on_line_amt','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12426','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Architha Gudimalla','Addition','edw_core','trenewal_summary','outstanding_in_progress_renewal_ct','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12426','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-06','Architha Gudimalla','Addition','edw_core','trenewal_summary','closed_with_no_offer_pending_process_renewal_ct','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12440','EDW/Datamart Enhancements: Updated vhome_coverage_ext and vquote_home_coverage_ext view to capture additional fields','Enhancement','2026-02-06','Dinesh Bobbili','Modification','edw_core','vhome_coverage_ext','','Updated view to include the Extended Liability fields and the Additional Insured Trustee fields','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12440','EDW/Datamart Enhancements: Updated vhome_coverage_ext and vquote_home_coverage_ext view to capture additional fields','Enhancement','2026-02-06','Dinesh Bobbili','Modification','edw_core','vquote_home_coverage_ext','','Updated view to include the Extended Liability fields and the Additional Insured Trustee fields','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12386','EDW/Datamart Enhancements: Updated stored procedure to include additional transaction type','Enhancement','2026-02-06','Yunus Mohammed','Modification','edw_core','tpolicy','billing_paid_in','Updated stored procedure to include additional transaction type to update billing_paid_in in tpolicy table','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12461','Workday Enhancements : Updated product name for Marine in workday files','Enhancement','2026-02-06','Yunus Mohammed','Modification','edw_integration','claim_workday_payment_feed','product','Updated product name from Marine Boat & Yacht to Marine_Boat&Yacht in workday files','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12461','Workday Enhancements : Updated product name for Marine in workday files','Enhancement','2026-02-06','Yunus Mohammed','Modification','edw_integration','claim_workday_itd_reserve_feed','product','Updated product name from Marine Boat & Yacht to Marine_Boat&Yacht in workday files','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12461','Workday Enhancements : Updated product name for Marine in workday files','Enhancement','2026-02-06','Yunus Mohammed','Modification','edw_integration','claim_workday_reserve_feed','product','Updated product name from Marine Boat & Yacht to Marine_Boat&Yacht in workday files','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12461','Workday Enhancements : Updated product name for Marine in workday files','Enhancement','2026-02-06','Yunus Mohammed','Modification','edw_integration','claim_litigation_workday_payment_feed','product','Updated product name from Marine Boat & Yacht to Marine_Boat&Yacht in workday files','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12461','Workday Enhancements : Updated product name for Marine in workday files','Enhancement','2026-02-06','Yunus Mohammed','Modification','edw_integration','claim_litigation_workday_itd_reserve_feed','product','Updated product name from Marine Boat & Yacht to Marine_Boat&Yacht in workday files','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12461','Workday Enhancements : Updated product name for Marine in workday files','Enhancement','2026-02-06','Yunus Mohammed','Modification','edw_integration','claim_litigation_workday_reserve_feed','product','Updated product name from Marine Boat & Yacht to Marine_Boat&Yacht in workday files','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12461','Workday Enhancements : Updated product name for Marine in workday files','Enhancement','2026-02-06','Yunus Mohammed','Modification','edw_integration','policy_workday_unearned_premium_feed','product','Updated product name from Marine Boat & Yacht to Marine_Boat&Yacht in workday files','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12076','EDW Integrations:  Field additions to hubspot tables','Enhancement','2026-02-06','Architha Gudimalla','Addition','edw_integration','customer_hubspot_feed','total_policy_premium_amt','Created new column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC47839','EDW Integrations: IVANS Collections Code Fix','Bug','2026-02-06','Alberto Valbuena','Modification','edw_integration','policy_ivans_collections_feed','Scheduled_Items','Updated stored procedure to filter data based on newly created location_deleted_in column','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12344','Process Improvements : Hubspot','Enhancement','2026-02-06','Hernando Garcia','Addition','edw_integration','','','Created an enhanced email‑notification process for Hubspot to report integration errors','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12374','EDW_Integrations : Clean up customer names so they are formatted in clean, proper capitalization for customer midterm review ','Enhancement','2026-02-06','Yunus Mohammed','Modification','edw_integration','','','Updated stored procedure to clean up customer names so they are formatted in clean, proper capitalization','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12391','Data Fix : Updated customer address records for 9 records','Bug','2026-02-06','Architha Gudimalla','Modification','edw_core','tcustomer','mailing_address_state_cd','Updated missing state codes and city names in the customer address records for 9 customers in EDW and Metal.  This is just a onetime update.','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12391','Data Fix : Updated customer address records for 9 records','Bug','2026-02-06','Architha Gudimalla','Modification','edw_core','tcustomer','mailing_address_city_nm','Updated missing state codes and city names in the customer address records for 9 customers in EDW and Metal.  This is just a onetime update.','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC48088','Data Fixes : Updated the commercial policy number from x01540305 to O1540305.','Bug','2026-02-06','Rushin Shah','Datafix','edw_commercial','tcommercial_policy','policy_no','Updated the commercial policy number from x01540305 to O1540305 In Metal and EDW. This is just a onetime update. ','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC48088','Data Fixes : Updated the commercial policy number from x01540305 to O1540305.','Bug','2026-02-06','Rushin Shah','Datafix','edw_commercial','tcommercial_policy_tower','policy_no','Updated the commercial policy number from x01540305 to O1540305 In Metal and EDW. This is just a onetime update. ','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC48088','Data Fixes : Updated the commercial policy number from x01540305 to O1540305.','Bug','2026-02-06','Rushin Shah','Datafix','edw_commercial','tcommercial_policy_history','policy_no','Updated the commercial policy number from x01540305 to O1540305 In Metal and EDW. This is just a onetime update. ','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC48088','Data Fixes : Updated the commercial policy number from x01540305 to O1540305.','Bug','2026-02-06','Rushin Shah','Datafix','edw_commercial','tcommercial_policy_coverage','policy_no','Updated the commercial policy number from x01540305 to O1540305 In Metal and EDW. This is just a onetime update. ','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12366','Data Fixes : Updated latitude & longitude for 9 policies','Bug','2026-02-06','Tuba Mohsin','Datafix','edw_core','tcollection_location','latitude','Updated latitude & longitude for 9 policies. Data is updated in Metal and EDW. This is just a onetime update. ','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12366','Data Fixes : Updated latitude & longitude for 9 policies','Bug','2026-02-06','Tuba Mohsin','Datafix','edw_core','tcollection_location','longitude','Updated latitude & longitude for 9 policies. Data is updated in Metal and EDW. This is just a onetime update. ','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12366','Data Fixes : Updated latitude & longitude for 9 policies','Bug','2026-02-06','Tuba Mohsin','Datafix','edw_core','tquote_collection_location','latitude','Updated latitude & longitude for 9 policies. Data is updated in Metal and EDW. This is just a onetime update. ','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12366','Data Fixes : Updated latitude & longitude for 9 policies','Bug','2026-02-06','Tuba Mohsin','Datafix','edw_core','tquote_collection_location','longitude','Updated latitude & longitude for 9 policies. Data is updated in Metal and EDW. This is just a onetime update. ','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12431','Data Fines : Updated issued date and bind date for HO200070420-01','Bug','2026-02-06','Rushin Shah','Datafix','edw_stage','AccountTransaction','IssuedDate','Updated issued date and bind date for HO200070420-01 in Metal. This is just a one time update.','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12431','Data Fines : Updated issued date and bind date for HO200070420-01','Bug','2026-02-06','Rushin Shah','Datafix','edw_stage','AccountTransaction','BindDate','Updated issued date and bind date for HO200070420-01 in Metal. This is just a one time update.','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC48192','Data Fixes: InitialRatingTier Data Fix for AU200033368 and AU200034176','Bug','2026-02-06','Rushin Shah','Datafix','edw_stage','AccountTransactionVersionObjectField','','Updated initial rating tier for AU200033368 and AU200034176 in Metal and EDW. This is just a one time update.','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12383','Data Fixes : Updated violation notes for EX100025490-05 and EX200029764-06 in EDW','Bug','2026-02-06','Architha Gudimalla','Datafix','edw_core','tnote','note_desc','Updated MVR vendor reports violation notes for EX100025490-05 and EX200029764-06 in EDW. This is just a one time update.','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12323','Data Fixes : Updated missing VIN for AU200035734','Bug','2026-02-06','Tuba Mohsin','Datafix','edw_core','tauto_vehicle','vehicle_vin','Updated missing VIN number on a vehicle for AU200035734 in Metal and EDW. This is just a one time update.','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12323','Data Fixes : Updated missing VIN for AU200035734','Bug','2026-02-06','Tuba Mohsin','Datafix','edw_core','tquote_auto_vehicle','vehicle_vin','Updated missing VIN number on a vehicle for AU200035734 in Metal and EDW. This is just a one time update.','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12367','Data Fixes: Update isPrimaryInsured for HO100227250-03 and HO100011280-05','Bug','2026-02-06','Tuba Mohsin','Datafix','edw_core','tpolicy_insured','primary_insured_in','Updated primary insured flag on HO100227250-03 and HO100011280-05 in Metal and EDW. This is just a one time update. ','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12333','Data Fixes : Update policy_no in tclaim table associated with 2 claims C21AUA00240 and C22XLA00002','Bug','2026-02-06','Rushin Shah','Datafix','edw_core','tclaim','policy_no','Updated policy_no in tclaim table associated with 2 claims C21AUA00240 and C22XLA00002','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12495','Data Fixes : Update Description for Forms','Bug','2026-02-06','Bhaskar Muthyala','Datafix','edw_stage','AccountForm','Description','Updated Description from Vault Homeowners Application - IL to Vault Homeowners Application in Metal and EDW.  This is just a onetime update.','51','Yes','2026-02-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12495','Data Fixes : Update Description for Forms','Bug','2026-02-06','Bhaskar Muthyala','Datafix','edw_stage','AccountTransactionVersionForm','Description','Updated Description from Vault Homeowners Application - IL to Vault Homeowners Application in Metal and EDW.  This is just a onetime update.','51','Yes','2026-02-09',getdate(),getdate());