INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 02/23/2026 :</span>
    <h4 style="margin-top: 0;font-style: italic;color: blue;">This release had 4 enhancements and 8 bug fix tickets.  Release details are as follows.</h4>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; }
        h1, h2 { color: #333; }
        ul { margin: 10px 0; padding-left: 20px; }
    </style>
</head>
<body>
    <h2 style="font-style: italic;">1. EDW/Datamart Enhancements</h2>
    <ul>
        <li>Added the column subscriber_contribution_end_dt to tcustomer table</li>
    </ul>
    <h2 style="font-style: italic;">2. EDW Integrations</h2>
    <h3>a. Hubspot</h3>
    <ul>
        <li>Added association from policy to producer</li>
        <li>Added association from quote to producer</li>
    </ul>
    <h3>b. IVANS</h3>
    <ul>
        <li>INC47839: Updated the IVANS collection feed stored procedure to not send the deleted scheduled items</li>
        <li>INC48552/INC48551/INC48550/INC48794: Resent IVANS policies associated with this ticket</li>
    </ul>
    <h2 style="font-style: italic;">3. Data Fixes</h2>
    <ul>
        <li>INC46040: Updated loss of use option to NULL for 408 transactions in Metal and EDW to facilitate renewals.  This is just a onetime update.</li>
        <li>INC48742: Updated the subscriber contribution end date on 19 policies in Metal and EDW.  This is just a onetime update.</li>
        <li>INC48961: Updated the subscriber contribution end date for one customer in Metal and EDW.  This is just a onetime update.</li>
        <li>AD12549: Updated animal_related_liability_endorsement_in to NULL from Yes for a few Admitted HO/CO policies in following states AZ, IN, LA, MD, RI, GA, UT in Metal and EDW.  This is just a onetime update.</li>
        <li>AD11666: Update stored procedure to fetch claim policy search and policy webhook NFP data from base tables instead of NFP staging tables.</li>
    </ul>
</body>
'
,'Yes'
,'2026-02-23'
,getdate()
,getdate()
)
;

INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC48552/INC48551/INC48550/INC48794','IVANS Policy Resent Request','Bug','2026-02-20','Rushin Shah','Datafix','edw_integration','policy_ivans_collections_feed','','Resent a few home policies to IVANS','52','Yes','2026-02-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC48552/INC48551/INC48550/INC48794','IVANS Policy Resent Request','Bug','2026-02-20','Rushin Shah','Datafix','edw_integration','policy_ivans_home_feed','','Resent a few home policies to IVANS','52','Yes','2026-02-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC48552/INC48551/INC48550/INC48794','IVANS Policy Resent Request','Bug','2026-02-20','Rushin Shah','Datafix','edw_integration','policy_ivans_auto_feed','','Resent a few auto policies to IVANS','52','Yes','2026-02-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC48552/INC48551/INC48550/INC48794','IVANS Policy Resent Request','Bug','2026-02-20','Rushin Shah','Datafix','edw_integration','policy_ivans_pel_feed','','Resent a few pel policies to IVANS','52','Yes','2026-02-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12563','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-02-20','Rushin Shah','Addition','edw_core','tcustomer','subscriber_contribution_end_dt','Created new column','52','Yes','2026-02-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC46040','Data Fix : Updated loss of use option to NULL for 408 records','Bug','2026-02-20','Tuba Mohsin','Datafix','edw_core','thome_coverage','loss_of_use_option','Updated loss of use option to NULL for 408 transaction in Metal and EDW to facilitate renewals.  This is just a onetime update.','52','Yes','2026-02-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC46040','Data Fix : Updated loss of use option to NULL for 408 records','Bug','2026-02-20','Tuba Mohsin','Datafix','edw_core','tquote_home_coverage','loss_of_use_option','Updated loss of use option to NULL for 408 transaction in Metal and EDW to facilitate renewals.  This is just a onetime update.','52','Yes','2026-02-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC48742','Data Fixes: Update subscriber contribution end date in metal for HO89198089536-06','Bug','2026-02-20','Tuba Mohsin','Datafix','edw_core','tpolicy_insured','subscriber_contribution_end_dt','Updated subscriber contribution end date for HO89198089536-06. Data is updated in Metal and EDW. This is just a onetime update.','52','Yes','2026-02-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC48742','Data Fixes: Update subscriber contribution end date in metal for HO89198089536-06','Bug','2026-02-20','Tuba Mohsin','Datafix','edw_core','tquote_policy_insured','subscriber_contribution_end_dt','Updated subscriber contribution end date for HO89198089536-06. Data is updated in Metal and EDW. This is just a onetime update.','52','Yes','2026-02-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC48961','Data Fixes: Update subscriber contribution end date in metal for one customer','Bug','2026-02-20','Tuba Mohsin','Datafix','edw_core','tpolicy_insured','subscriber_contribution_end_dt','Updated subscriber contribution end date for one customer. Data is updated in Metal and EDW. This is just a onetime update.','52','Yes','2026-02-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC48961','Data Fixes: Update subscriber contribution end date in metal for one customer','Bug','2026-02-20','Tuba Mohsin','Datafix','edw_core','tquote_policy_insured','subscriber_contribution_end_dt','Updated subscriber contribution end date for one customer. Data is updated in Metal and EDW. This is just a onetime update.','52','Yes','2026-02-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12549','Data Fixes : Update animal_related_liability_endorsement_in to NULL from Yes for a few Admitted HO/CO policies','Bug','2026-02-20','Rushin Shah','Datafix','edw_core','thome_additional_coverage','animal_related_liability_endorsement_in','Updated animal_related_liability_endorsement_in to NULL from Yes for a few Admitted HO/CO policies in following states AZ, IN, LA, MD, RI, GA, UT in Metal and EDW.  This is just a onetime update.','52','Yes','2026-02-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12549','Data Fixes : Update animal_related_liability_endorsement_in to NULL from Yes for a few Admitted HO/CO policies','Bug','2026-02-20','Rushin Shah','Datafix','edw_core','tquote_home_additional_coverage','animal_related_liability_endorsement_in','Updated animal_related_liability_endorsement_in to NULL from Yes for a few Admitted HO/CO policies in following states AZ, IN, LA, MD, RI, GA, UT in Metal and EDW.  This is just a onetime update.','52','Yes','2026-02-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12454','EDW Integrations : Add association from policy to producer in Hubspot','Enhancement','2026-02-20','Architha Gudimalla','Addition','edw_integration','customer_hubspot_feed','','Added association from policy to producer','52','Yes','2026-02-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12525','EDW Integrations : Add association from quote to producer in Hubspot','Enhancement','2026-02-20','Architha Gudimalla','Addition','edw_integration','quote_hubspot_feed','','Added association from quote to producer','52','Yes','2026-02-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11666','EDW Integrations : Update stored procedure to fetch claim policy search NFP data from base tables instead of NFP staging tables','Enhancement','2026-02-20','Yunus Mohammed','Modification','edw_integration','claim_policy_search_snapsheet_api','','Update stored procedure to fetch claim policy search NFP data from base tables instead of NFP staging tables','52','Yes','2026-02-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11666','EDW Integrations : Update stored procedure to fetch policy webhook NFP data from base tables instead of NFP staging tables','Enhancement','2026-02-20','Yunus Mohammed','Modification','edw_integration','claim_policy_webhook_snapsheet_api','','Update stored procedure to fetch policy webhook NFP data from base tables instead of NFP staging tables','52','Yes','2026-02-23',getdate(),getdate());