INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 03/09/2026 :</span>
    <h4 style="margin-top: 0;font-style: italic;color: blue;">This release had 7 enhancements and 5 bug fix tickets.  Release details are as follows.</h4>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; }
        h1, h2 { color: #333; }
        ul { margin: 10px 0; padding-left: 20px; }
    </style>
</head>
<body>
    <h2 style="font-style: italic;">1. EDW/Datamart Enhancements</h2>
    <ul>
        <li>Added the column external_apply_scope to tpolicy_referral_message and tquote_referral_message tables</li>
        <li>Added rate_on_line_exclude_collection to thome_coverage table</li>
        <li>Added the column residence_owned_by_trust_in to tadditional_interest and tquote_additional_interest tables</li>
        <li>Added the column frame_to_foundation_connection_in column to thome_coverage and tquote_home_coverage tables</li>
        <li>Added these risk address columns to tpolicy and tquote tables
          <ul>
                <li>risk_address_line_1</li>
                <li>risk_address_line_2</li>
                <li>risk_address_unit_no</li>
                <li>risk_address_city_nm</li>
                <li>risk_address_state_cd</li>
                <li>risk_address_zip_cd</li>
                <li>risk_address_country_nm</li>
          </ul>
        </li>
        <li>Created a version of renewal summary table (trenewal_summary_v1) to support the new retention report</li>
        <li>Added a new column mid_term_cancelled_premium_amt to trenewal_summary table</li>
    </ul>
    <h2 style="font-style: italic;">2. EDW Integrations</h2>
    <h3>a. Hubspot</h3>
    <ul>
        <li>Hubspot feed for commercial data goes live</li>
    </ul>
    <h3>b. IVANS</h3>
    <ul>
        <li>INC49514/INC49632: Resent IVANS policies associated with this ticket</li>
    </ul>
    <h2 style="font-style: italic;">3. Data Fixes</h2>
    <ul>
        <li>SR49033 : Updated CompanyTeamBrokerage table in Metal and EDW with new UW/BDM assignments for the new Group Excess policy for a new user. This is just a one time update.</li>
        <li>AD12697 : Updated uninsured_motorist_limit_amt = NULL in Metal and EDW for AU200037075. This is just a one time update.</li>
        <li>INC34307: Updated garage address zip code and garage address county name for the policy AU100214349,AU100214349-01,AU100214349-02 in Metal and EDW.This is just a one time update.</li>
    </ul>
</body>
'
,'Yes'
,'2026-03-09'
,getdate()
,getdate()
)
;

INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC49514/INC49632','IVANS Policy Resent Request','Bug','2026-03-06','Rushin Shah','Datafix','edw_integration','policy_ivans_collections_feed','','Resent a few home policies to IVANS','53','Yes','2026-03-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC49514/INC49632','IVANS Policy Resent Request','Bug','2026-03-06','Rushin Shah','Datafix','edw_integration','policy_ivans_home_feed','','Resent a few home policies to IVANS','53','Yes','2026-03-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC49514/INC49632','IVANS Policy Resent Request','Bug','2026-03-06','Rushin Shah','Datafix','edw_integration','policy_ivans_auto_feed','','Resent a few auto policies to IVANS','53','Yes','2026-03-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC49514/INC49632','IVANS Policy Resent Request','Bug','2026-03-06','Rushin Shah','Datafix','edw_integration','policy_ivans_pel_feed','','Resent a few pel policies to IVANS','53','Yes','2026-03-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12652','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-03-06','Rushin Shah','Addition','edw_core','tpolicy_referral_message','external_apply_scope','Created new column','53','Yes','2026-03-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12652','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-03-06','Rushin Shah','Addition','edw_core','tquote_referral_message','external_apply_scope','Created new column','53','Yes','2026-03-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12622','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-03-06','Architha Gudimalla','Addition','edw_core','thome_coverage','rate_on_line_exclude_collection','Created new column','53','Yes','2026-03-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12616','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-03-06','Architha Gudimalla','Addition','edw_core','trenewal_summary','mid_term_cancelled_premium_amt','Created new column','53','Yes','2026-03-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12607','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-03-06','Tuba Mohsin','Addition','edw_core','tadditional_interest','residence_owned_by_trust_in','Created new column','53','Yes','2026-03-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12607','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-03-06','Tuba Mohsin','Addition','edw_core','tquote_additional_interest','residence_owned_by_trust_in','Created new column','53','Yes','2026-03-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12607','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-03-06','Tuba Mohsin','Addition','edw_core','thome_coverage','frame_to_foundation_connection_in','Created new column','53','Yes','2026-03-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12607','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-03-06','Tuba Mohsin','Addition','edw_core','tquote_home_coverage','frame_to_foundation_connection_in','Created new column','53','Yes','2026-03-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12627','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-03-06','Yunus Mohammed','Addition','edw_core','tpolicy','risk_address_line_1','Created new column','53','Yes','2026-03-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12627','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-03-06','Yunus Mohammed','Addition','edw_core','tpolicy','risk_address_line_2','Created new column','53','Yes','2026-03-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12627','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-03-06','Yunus Mohammed','Addition','edw_core','tpolicy','risk_address_unit_no','Created new column','53','Yes','2026-03-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12627','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-03-06','Yunus Mohammed','Addition','edw_core','tpolicy','risk_address_city_nm','Created new column','53','Yes','2026-03-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12627','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-03-06','Yunus Mohammed','Addition','edw_core','tpolicy','risk_address_state_cd','Created new column','53','Yes','2026-03-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12627','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-03-06','Yunus Mohammed','Addition','edw_core','tpolicy','risk_address_zip_cd','Created new column','53','Yes','2026-03-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12627','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-03-06','Yunus Mohammed','Addition','edw_core','tpolicy','risk_address_country_nm','Created new column','53','Yes','2026-03-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12627','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-03-06','Yunus Mohammed','Addition','edw_core','tquote','risk_address_line_1','Created new column','53','Yes','2026-03-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12627','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-03-06','Yunus Mohammed','Addition','edw_core','tquote','risk_address_line_2','Created new column','53','Yes','2026-03-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12627','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-03-06','Yunus Mohammed','Addition','edw_core','tquote','risk_address_unit_no','Created new column','53','Yes','2026-03-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12627','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-03-06','Yunus Mohammed','Addition','edw_core','tquote','risk_address_city_nm','Created new column','53','Yes','2026-03-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12627','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-03-06','Yunus Mohammed','Addition','edw_core','tquote','risk_address_state_cd','Created new column','53','Yes','2026-03-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12627','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-03-06','Yunus Mohammed','Addition','edw_core','tquote','risk_address_zip_cd','Created new column','53','Yes','2026-03-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12627','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-03-06','Yunus Mohammed','Addition','edw_core','tquote','risk_address_country_nm','Created new column','53','Yes','2026-03-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('SR49033','Data Fixes: Added Contact records in hubspot for customers that only have quotes and no policies','Enhancement','2026-03-06','Architha Gudimalla','Modification','edw_stage','CompanyTeamBrokerage','','Updated CompanyTeamBrokerage table in Metal and EDW with new UW/BDM assignments for the new Group Excess policy for a new user. This is just a one time update.','53','Yes','2026-03-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC34307','Data Fixes: Update garage address zip code and garage address county name for the policy AU100214349,AU100214349-01,AU100214349-02','Bug','2026-03-06','Tuba Mohsin','Datafix','edw_core','tauto_garage_location','garage_address_zip_code','Updated garage address zip code and garage address county name for the policy AU100214349,AU100214349-01,AU100214349-02. Data is updated in Metal and EDW. This is just a onetime update.','53','Yes','2026-03-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC34307','Data Fixes: Update garage address zip code and garage address county name for the policy AU100214349,AU100214349-01,AU100214349-02','Bug','2026-03-06','Tuba Mohsin','Datafix','edw_core','tauto_garage_location','garage_address_county_nm','Updated garage address zip code and garage address county name for the policy AU100214349,AU100214349-01,AU100214349-02. Data is updated in Metal and EDW. This is just a onetime update.','53','Yes','2026-03-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC34307','Data Fixes: Update garage address zip code and garage address county name for the policy AU100214349,AU100214349-01,AU100214349-02','Bug','2026-03-06','Tuba Mohsin','Datafix','edw_core','tquote_auto_garage_location','garage_address_zip_code','Updated garage address zip code and garage address county name for the policy AU100214349,AU100214349-01,AU100214349-02. Data is updated in Metal and EDW. This is just a onetime update.','53','Yes','2026-03-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC34307','Data Fixes: Update garage address zip code and garage address county name for the policy AU100214349,AU100214349-01,AU100214349-02','Bug','2026-03-06','Tuba Mohsin','Datafix','edw_core','tquote_auto_garage_location','garage_address_county_nm','Updated garage address zip code and garage address county name for the policy AU100214349,AU100214349-01,AU100214349-02. Data is updated in Metal and EDW. This is just a onetime update.','53','Yes','2026-03-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12640','Data Fixes: Update uninsured_motorist_limit_amt to NULL for AU200037075','Bug','2026-03-06','Tuba Mohsin','Datafix','edw_core','tauto_policy_coverage','uninsured_motorist_limit_amt','Updated uninsured_motorist_limit_amt to NULL for AU200037075. Data is updated in Metal and EDW. This is just a onetime update.','53','Yes','2026-03-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12640','Data Fixes: Update uninsured_motorist_limit_amt to NULL for AU200037075','Bug','2026-03-06','Tuba Mohsin','Datafix','edw_core','tquote_auto_policy_coverage','uninsured_motorist_limit_amt','Updated uninsured_motorist_limit_amt to NULL for AU200037075. Data is updated in Metal and EDW. This is just a onetime update.','53','Yes','2026-03-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12600','EDW/Datamart Enhancements: Created new table for Majesco data','Enhancement','2026-03-06','Bhaskar Muthyala','Addition','edw_stage','stage_majesco_transaction_data_feed','','Created new table','53','Yes','2026-03-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12600','EDW/Datamart Enhancements: Created new table for Majesco data','Enhancement','2026-03-06','Bhaskar Muthyala','Addition','edw_stage','stage_majesco_installment_data_feed','','Created new table','53','Yes','2026-03-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12600','EDW/Datamart Enhancements: Created new table for Majesco data','Enhancement','2026-03-06','Bhaskar Muthyala','Addition','edw_stage','stage_majesco_payment_data_feed','','Created new table','53','Yes','2026-03-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12600','EDW/Datamart Enhancements: Created new table for Majesco data','Enhancement','2026-03-06','Bhaskar Muthyala','Addition','edw_stage','stage_majesco_output_data_feed','','Created new table','53','Yes','2026-03-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12600','EDW/Datamart Enhancements: Created new table for Majesco data','Enhancement','2026-03-06','Bhaskar Muthyala','Addition','edw_stage','stage_majesco_notes_data_feed','','Created new table','53','Yes','2026-03-09',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12600','EDW/Datamart Enhancements: Created new table for Majesco data','Enhancement','2026-03-06','Bhaskar Muthyala','Addition','edw_stage','stage_majesco_invoice_data_feed','','Created new table','53','Yes','2026-03-09',getdate(),getdate());
