INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 03/23/2026 :</span>
    <h4 style="margin-top: 0;font-style: italic;color: blue;">This release had 7 enhancements and 9 bug fix tickets.  Release details are as follows.</h4>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; }
        h1, h2 { color: #333; }
        ul { margin: 10px 0; padding-left: 20px; }
    </style>
</head>
<body>
    <h2 style="font-style: italic;">1. EDW/Datamart Enhancements</h2>
    <ul>
        <li>Added marine_boat_yacht_broker_nm to tpolicy and tquote tables.</li>
        <li>Updated renewal summary to use net premium instead of premium amount for offered_quote_premium_amt.</li>
    </ul>
    <h2 style="font-style: italic;">2. EDW Integrations</h2>
    <h3>a. Hubspot</h3>
    <ul>
        <li>Updated HubSpot feed to check if association already exists for type 30 (Customer-Quote association).</li>
        <li>Updated HubSpot feed to account for association limit for type 37 (Quote-Producer association).</li>
        <li>Created a new Standard Sandbox for HubSpot and built key integrations and app connections. Validated all workflows before retiring the legacy sandbox.</li>
    </ul>
    <h3>b. IVANS</h3>
    <ul>
        <li>Updated IVANS stored procedure to exclude sending data associated with deleted additional interest.</li>
        <li>INC50072/INC49924/INC49922/INC49920: Resent IVANS policies associated with these ticket.</li>
    </ul>
    <h2 style="font-style: italic;">3. Data Fixes</h2>
    <ul>
        <li>AD12738: Fixed a few home_systems_protection_limit_amt by making them null where the indicator for these coverages were no but limit amounts were set.</li>
        <li>AD12737: Fixed a few home_cyber_protection_coverage_limit_amt by making them null where the indicator for these coverages were no but limit amounts were set.</li>
        <li>AD12739: Reassigned 10 policies and quotes from one broker to another.</li>
        <li>INC32187: Fixed a garaging address formatting issue and corrected the county for a few policies. This is just a one time update.</li>
        <li>INC32167: Updated garage_address_state_cd with risk_state_cd in Metal and EDW for 29 auto policies. This is just a one time update.</li>
    </ul>
</body>
'
,'Yes'
,'2026-03-23'
,getdate()
,getdate()
)
;

INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC50072/INC49924/INC49922/INC49920','IVANS Policy Resent Request','Bug','2026-03-20','Rushin Shah','Datafix','edw_integration','policy_ivans_collections_feed','','Resent a few collections policies to IVANS','54','Yes','2026-03-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC50072/INC49924/INC49922/INC49920','IVANS Policy Resent Request','Bug','2026-03-20','Rushin Shah','Datafix','edw_integration','policy_ivans_home_feed','','Resent a few home policies to IVANS','54','Yes','2026-03-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC50072/INC49924/INC49922/INC49920','IVANS Policy Resent Request','Bug','2026-03-20','Rushin Shah','Datafix','edw_integration','policy_ivans_auto_feed','','Resent a few auto policies to IVANS','54','Yes','2026-03-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC50072/INC49924/INC49922/INC49920','IVANS Policy Resent Request','Bug','2026-03-20','Rushin Shah','Datafix','edw_integration','policy_ivans_pel_feed','','Resent a few pel policies to IVANS','54','Yes','2026-03-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12788','Updated IVANS stored procedure to exclude data associated with deleted additional interest and collection class types','Enhancement','2026-03-20','Alberto Valbuena','Modification','edw_integration','policy_ivans_collections_feed','Scheduled_Items','Updated IVANS stored procedure to exclude data associated with deleted additional interest and collection class types','54','Yes','2026-03-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12788','Updated IVANS stored procedure to exclude data associated with deleted additional interest and collection class types','Enhancement','2026-03-20','Alberto Valbuena','Modification','edw_integration','policy_ivans_collections_feed','Collection_Coverages','Updated IVANS stored procedure to exclude data associated with deleted additional interest and collection class types','54','Yes','2026-03-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12788','Updated IVANS stored procedure to exclude data associated with deleted additional interest and collection class types','Enhancement','2026-03-20','Alberto Valbuena','Modification','edw_integration','policy_ivans_pel_feed','PEL_Drivers','Updated IVANS stored procedure to exclude data associated with deleted additional interest and collection class types','54','Yes','2026-03-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12790','Updated IVANS stored procedure to exclude data associated with deleted additional interest and collection class types','Enhancement','2026-03-20','Hernando Garcia','Modification','edw_integration','policy_ivans_home_feed','Home_Collection_Coverages','Updated IVANS stored procedure to exclude data associated with deleted additional interest and collection class types','54','Yes','2026-03-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12790','Updated IVANS stored procedure to exclude data associated with deleted additional interest and collection class types','Enhancement','2026-03-20','Hernando Garcia','Modification','edw_integration','policy_ivans_home_feed','Additional_Interests','Updated IVANS stored procedure to exclude data associated with deleted additional interest and collection class types','54','Yes','2026-03-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12790','Updated IVANS stored procedure to exclude data associated with deleted additional interest and collection class types','Enhancement','2026-03-20','Hernando Garcia','Modification','edw_integration','policy_ivans_home_feed','Scheduled_Items','Updated IVANS stored procedure to exclude data associated with deleted additional interest and collection class types','54','Yes','2026-03-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('SR49570','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-03-20','Tuba Mohsin','Addition','edw_core','tpolicy','marine_boat_yacht_broker_nm','Created new column','54','Yes','2026-03-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('SR49570','EDW/Datamart Enhancements: Created new columns','Enhancement','2026-03-20','Tuba Mohsin','Addition','edw_core','tquote','marine_boat_yacht_broker_nm','Created new column','54','Yes','2026-03-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12737','Data Fixes : Cyber protection indicator vs limit amount mismatch','Bug','2026-03-20','Rushin Shah','Datafix','edw_core','thome_additional_coverage','home_cyber_protection_coverage_limit_amt','Fixed a few home_cyber_protection_coverage_limit_amt by making them null where the indicator for these coverages were no but limit amounts were set.  This is a one time fix applied in Metal and EDW.','54','Yes','2026-03-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12738','Data Fixes : System protection indicator vs limit amount mismatch','Bug','2026-03-20','Rushin Shah','Datafix','edw_core','thome_additional_coverage','home_systems_protection_limit_amt','Fixed a few home_systems_protection_limit_amt by making them null where the indicator for these coverages were no but limit amounts were set.  This is a one time fix applied in Metal and EDW.','54','Yes','2026-03-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12739','Data Fixes : Move 3 policies/quotes from one broker to other','Bug','2026-03-20','Yunus Mohammed','Datafix','edw_commercial','tcommercial_policy','broker_id','Updated broker_id associated with 3 commercial policies and quotes.  Data is updated in Metal and EDW.  This is just a onetime update.','54','Yes','2026-03-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12739','Data Fixes : Move 3 policies/quotes from one broker to other','Bug','2026-03-20','Yunus Mohammed','Datafix','edw_commercial','tcommercial_policy_history','broker_id','Updated broker_id associated with 3 commercial policies and quotes.  Data is updated in Metal and EDW.  This is just a onetime update.','54','Yes','2026-03-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12739','Data Fixes : Move 3 policies/quotes from one broker to other','Bug','2026-03-20','Yunus Mohammed','Datafix','edw_commercial','tcommercial_policy_transaction','broker_id','Updated broker_id associated with 3 commercial policies and quotes.  Data is updated in Metal and EDW.  This is just a onetime update.','54','Yes','2026-03-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12739','Data Fixes : Move 7 policies/quotes from one broker to other','Bug','2026-03-20','Yunus Mohammed','Datafix','edw_commercial','tpolicy','broker_id','Updated broker_id associated with 7 personal lines policies and quotes.  Data is updated in Metal and EDW.  This is just a onetime update.','54','Yes','2026-03-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12739','Data Fixes : Move 7 policies/quotes from one broker to other','Bug','2026-03-20','Yunus Mohammed','Datafix','edw_commercial','tpolicy_history','broker_id','Updated broker_id associated with 7 personal lines policies and quotes.  Data is updated in Metal and EDW.  This is just a onetime update.','54','Yes','2026-03-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12739','Data Fixes : Move 7 policies/quotes from one broker to other','Bug','2026-03-20','Yunus Mohammed','Datafix','edw_commercial','tpolicy_transaction','broker_id','Updated broker_id associated with 7 personal lines policies and quotes.  Data is updated in Metal and EDW.  This is just a onetime update.','54','Yes','2026-03-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC32187','Data Fixes: Fixed a garaging address formatting issue and corrected the county for a few auto policies','Bug','2026-03-20','Tuba Mohsin','Datafix','edw_core','tauto_garage_location','garage_address_city_nm','Fixed a garaging address formatting issue and corrected the county for a few policies.  Data is updated in Metal and EDW.  This is just a onetime update.','54','Yes','2026-03-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC32187','Data Fixes: Fixed a garaging address formatting issue and corrected the county for a few auto policies','Bug','2026-03-20','Tuba Mohsin','Datafix','edw_core','tquote_auto_garage_location','garage_address_city_nm','Fixed a garaging address formatting issue and corrected the county for a few policies.  Data is updated in Metal and EDW.  This is just a onetime update.','54','Yes','2026-03-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC32167','Data Fixes : Updated garage_address_state_cd with risk_state_cd in Metal and EDW for 29 auto policies','Bug','2026-03-20','Tuba Mohsin','Datafix','edw_core','tauto_garage_location','garage_address_state_cd','Updated garage_address_state_cd with risk_state_cd in Metal and EDW for 29 auto policies.  Data is updated in Metal and EDW.  This is just a onetime update.','54','Yes','2026-03-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC32167','Data Fixes : Updated garage_address_state_cd with risk_state_cd in Metal and EDW for 29 auto policies','Bug','2026-03-20','Tuba Mohsin','Datafix','edw_core','tquote_auto_garage_location','garage_address_state_cd','Updated garage_address_state_cd with risk_state_cd in Metal and EDW for 29 auto policies.  Data is updated in Metal and EDW.  This is just a onetime update.','54','Yes','2026-03-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12861','EDW/Datamart Enhancements: Updated renewal summary to use net premium instead of premium amount for offered_quote_premium_amt','Enhancement','2026-03-20','Architha Gudimalla','Modification','edw_core','trenewal_summary_v1','offered_quote_premium_amt','Updated renewal summary to use net premium instead of premium amount for offered_quote_premium_amt','54','Yes','2026-03-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12632','Process Improvements : Updated HubSpot feed to check if association already exists for type 30 (Customer-Quote association)','Enhancement','2026-03-20','Hernando Garcia','Modification','edw_integration','','','Updated HubSpot feed to check if association already exists for type 30 (Customer-Quote association)','54','Yes','2026-03-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12740','Process Improvements : Updated HubSpot feed to account for association limit for type 37 (Quote-Producer association)','Enhancement','2026-03-20','Hernando Garcia','Modification','edw_integration','','','Updated HubSpot feed to account for association limit for type 37 (Quote-Producer association)','54','Yes','2026-03-23',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12631','Process Improvements : Created a new Standard Sandbox for HubSpot and built key integrations and app connections','Enhancement','2026-03-20','Hernando Garcia','Modification','edw_integration','','','Created a new Standard Sandbox for HubSpot and built key integrations and app connections. Validated all workflows before retiring the legacy sandbox. Re‑establishing the EDW integration.','54','Yes','2026-03-23',getdate(),getdate());