INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 04/06/2026 :</span>
    <h4 style="margin-top: 0;font-style: italic;color: blue;">This release had 7 enhancements and 14 bug fix tickets.  Release details are as follows.</h4>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; }
        h1, h2 { color: #333; }
        ul { margin: 10px 0; padding-left: 20px; }
    </style>
</head>
<body>
    <h2 style="font-style: italic;">1. EDW/Datamart Enhancements</h2>
    <ul>
        <li>Created the table tcommercial_task to capture tasks from commercial policies and quotes.</li>
        <li>Updated the tmarine_boat_yatch_watercraft and tquote_marine_boat_yatch_watercraft tables to fix the mapping for make, model and year.</li>
        <li>Integrated Marine Boat & Yacht policies and coverages from EDW into the Snapsheet claims application.</li>
        <li>Updated loss_of_use_derived_pc in thome_coverage table to incorporate Reasonable and Necessary Expenses - 24 months loss of use option.</li>
        <li>Retired the Majesco billing bot process and implemented a new SFTP-based six‑file integration into the EDW staging area for reporting.</li>
    </ul>
    <h2 style="font-style: italic;">2. Process Improvements</h2>
    <ul>
        <li>Migrated the HubSpot ID‑mapping database from SQLite to SQL Server using the new edw_hubspot schema within vault_edw.</li>
    </ul>
    <h2 style="font-style: italic;">3. EDW Integrations</h2>
    <h3>a. IVANS</h3>
    <ul>
        <li>INC-50314/INC-50234/INC-50313/INC-50237/INC-50235/INC-50559/INC-50560/INC-50627/INC-50564/INC-50561 : Resent the IVANS policies associated with these tickets.</li>
    </ul>
    <h2 style="font-style: italic;">4. Data Fixes</h2>
    <ul>
        <li>INC32356: Fixed the address for 6 auto policies and 1 home policy in EDW and Metal. This is just a one time update.</li>
        <li>AD12986: Update the Latitude and Longitude for HO200106474 in Metal and EDW. This is just a one time update. </li>
        <li>AD12921: Updated document_delivery_to and document_delivery_method for CO200027211 in Metal and EDW. This is just a one time update.</li>
        <li>AD12916: Updated the claim coverage description and aslob_sk for 26PRRI323291922 in EDW. This is just a one time update.</li>
    </ul>
</body>
'
,'Yes'
,'2026-04-06'
,getdate()
,getdate()
)
;

INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC-50314/INC-50234/INC-50313/INC-50237/INC-50235/INC-50559/INC-50560/INC-50627/INC-50564/INC-50561','IVANS Policy Resent Request','Bug','2026-04-03','Rushin Shah','Datafix','edw_integration','policy_ivans_collections_feed','','Resent a few collections policies to IVANS','55','Yes','2026-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC-50314/INC-50234/INC-50313/INC-50237/INC-50235/INC-50559/INC-50560/INC-50627/INC-50564/INC-50561','IVANS Policy Resent Request','Bug','2026-04-03','Rushin Shah','Datafix','edw_integration','policy_ivans_home_feed','','Resent a few home policies to IVANS','55','Yes','2026-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC-50314/INC-50234/INC-50313/INC-50237/INC-50235/INC-50559/INC-50560/INC-50627/INC-50564/INC-50561','IVANS Policy Resent Request','Bug','2026-04-03','Rushin Shah','Datafix','edw_integration','policy_ivans_auto_feed','','Resent a few auto policies to IVANS','55','Yes','2026-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC-50314/INC-50234/INC-50313/INC-50237/INC-50235/INC-50559/INC-50560/INC-50627/INC-50564/INC-50561','IVANS Policy Resent Request','Bug','2026-04-03','Rushin Shah','Datafix','edw_integration','policy_ivans_pel_feed','','Resent a few pel policies to IVANS','55','Yes','2026-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12952','EDW/Datamart Enhancements: Created the table tcommercial_task to capture tasks from commercial policies and quotes','Enhancement','2026-04-03','Tuba Mohsin','Addition','edw_commercial','tcommercial_task','','Created new table','55','Yes','2026-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12948','EDW Integrations : Updated IVANS Auto stored procedure to update logic associated with additional interest','Enhancement','2026-04-03','Yunus Mohammed','Modification','edw_integration','policy_ivans_auto_feed','additionalInterests','Updated IVANS Auto stored procedure to update logic associated with additional interest JSON fields natureInterestCd, countryCd, countryName specifically when there is loss payee','55','Yes','2026-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12963','EDW/Datamart Enhancements: Updated tmarine_boat_yatch_watercraft and tquote_marine_boat_yatch_watercraft tables stored procedure  to fix the mapping for make, model and year','Enhancement','2026-04-03','Tuba Mohsin','Modification','edw_core','tmarine_boat_yacht_watercraft','watercraft_make','Updated stored procedure  to fix the mapping for make, model and year','55','Yes','2026-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12963','EDW/Datamart Enhancements: Updated tmarine_boat_yatch_watercraft and tquote_marine_boat_yatch_watercraft tables stored procedure  to fix the mapping for make, model and year','Enhancement','2026-04-03','Tuba Mohsin','Modification','edw_core','tmarine_boat_yacht_watercraft','watercraft_model','Updated stored procedure  to fix the mapping for make, model and year','55','Yes','2026-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12963','EDW/Datamart Enhancements: Updated tmarine_boat_yatch_watercraft and tquote_marine_boat_yatch_watercraft tables stored procedure  to fix the mapping for make, model and year','Enhancement','2026-04-03','Tuba Mohsin','Modification','edw_core','tmarine_boat_yacht_watercraft','watercraft_year','Updated stored procedure  to fix the mapping for make, model and year','55','Yes','2026-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12963','EDW/Datamart Enhancements: Updated tmarine_boat_yatch_watercraft and tquote_marine_boat_yatch_watercraft tables stored procedure  to fix the mapping for make, model and year','Enhancement','2026-04-03','Tuba Mohsin','Modification','edw_core','tquote_marine_boat_yacht_watercraft','watercraft_make','Updated stored procedure  to fix the mapping for make, model and year','55','Yes','2026-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12963','EDW/Datamart Enhancements: Updated tmarine_boat_yatch_watercraft and tquote_marine_boat_yatch_watercraft tables stored procedure  to fix the mapping for make, model and year','Enhancement','2026-04-03','Tuba Mohsin','Modification','edw_core','tquote_marine_boat_yacht_watercraft','watercraft_model','Updated stored procedure  to fix the mapping for make, model and year','55','Yes','2026-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12963','EDW/Datamart Enhancements: Updated tmarine_boat_yatch_watercraft and tquote_marine_boat_yatch_watercraft tables stored procedure  to fix the mapping for make, model and year','Enhancement','2026-04-03','Tuba Mohsin','Modification','edw_core','tquote_marine_boat_yacht_watercraft','watercraft_year','Updated stored procedure  to fix the mapping for make, model and year','55','Yes','2026-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11587','EDW/Datamart Enhancements: Integrated Marine Boat & Yacht policies and coverages from EDW into the Snapsheet Claims application','Enhancement','2026-04-03','Yunus Mohammed','Modification','edw_integration','claim_policy_search_snapsheet_api','','Integrated Marine Boat & Yacht policies and coverages from EDW into the Snapsheet Claims application','55','Yes','2026-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12897','EDW/Datamart Enhancements: Integrated Marine Boat & Yacht policies and coverages from EDW into the Snapsheet Claims application','Enhancement','2026-04-03','Yunus Mohammed','Modification','edw_integration','claim_policy_webhook_snapsheet_api','','Integrated Marine Boat & Yacht policies and coverages from EDW into the Snapsheet Claims application.  Object name logic was also updated.','55','Yes','2026-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12864','EDW/Datamart Enhancements: Updated stored procedure logic associated with billing paid indicator and billing payment date','Enhancement','2026-04-03','Yunus Mohammed','Modification','edw_core','tpolicy','billing_paid_in','Updated stored procedure logic associated with billing paid indicator and billing payment date','55','Yes','2026-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12864','EDW/Datamart Enhancements: Updated stored procedure logic associated with billing paid indicator and billing payment date','Enhancement','2026-04-03','Yunus Mohammed','Modification','edw_core','tpolicy','first_billing_payment_dt','Updated stored procedure logic associated with billing paid indicator and billing payment date','55','Yes','2026-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12986','Data Fixes : Updated latitude & longitude for HO200106474','Bug','2026-04-03','Tuba Mohsin','Datafix','edw_core','thome_location','latitude','Updated latitude & longitude for HO200106474. Data is updated in Metal and EDW. This is just a onetime update. ','55','Yes','2026-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12986','Data Fixes : Updated latitude & longitude for HO200106474','Bug','2026-04-03','Tuba Mohsin','Datafix','edw_core','thome_location','longitude','Updated latitude & longitude for HO200106474. Data is updated in Metal and EDW. This is just a onetime update. ','55','Yes','2026-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12986','Data Fixes : Updated latitude & longitude for HO200106474','Bug','2026-04-03','Tuba Mohsin','Datafix','edw_core','tquote_home_location','latitude','Updated latitude & longitude for HO200106474. Data is updated in Metal and EDW. This is just a onetime update. ','55','Yes','2026-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12986','Data Fixes : Updated latitude & longitude for HO200106474','Bug','2026-04-03','Tuba Mohsin','Datafix','edw_core','tquote_home_location','longitude','Updated latitude & longitude for HO200106474. Data is updated in Metal and EDW. This is just a onetime update. ','55','Yes','2026-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12916','Data Fixes : Updated claim_coverage_desc and aslob_sk for one claim 26PRRI323291922','Bug','2026-04-03','Tuba Mohsin','Datafix','edw_core','tclaim_feature','claim_coverage_desc','Updated claim_coverage_desc and aslob_sk for one claim 26PRRI323291922.Data is updated in EDW. This is just a onetime update. ','55','Yes','2026-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12916','Data Fixes : Updated claim_coverage_desc and aslob_sk for one claim 26PRRI323291922','Bug','2026-04-03','Tuba Mohsin','Datafix','edw_core','tclaim_feature','aslob_sk','Updated claim_coverage_desc and aslob_sk for one claim 26PRRI323291922.Data is updated in EDW. This is just a onetime update. ','55','Yes','2026-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12951','EDW/Datamart Enhancements : Updated loss_of_use_derived_pc in thome_coverage to incorporate Reasonable and Necessary Expenses - 24 months','Enhancement','2026-04-03','Yunus Mohammed','Modification','edw_core','thome_coverage','loss_of_use_derived_pc','Updated loss_of_use_derived_pc in thome_coverage to incorporate Reasonable and Necessary Expenses - 24 months loss of use option','55','Yes','2026-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12908','Data Fixes: Fixed the address for 6 auto policies and 1 home policy','Bug','2026-04-03','Tuba Mohsin','Datafix','edw_core','tauto_garage_location','garage_address_line1','Fixed the address for 6 auto policies and 1 home policy in EDW and Metal. This is just a one time update.','55','Yes','2026-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12908','Data Fixes: Fixed the address for 6 auto policies and 1 home policy','Bug','2026-04-03','Tuba Mohsin','Datafix','edw_core','tauto_garage_location','garage_address_line2','Fixed the address for 6 auto policies and 1 home policy in EDW and Metal. This is just a one time update.','55','Yes','2026-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12908','Data Fixes: Fixed the address for 6 auto policies and 1 home policy','Bug','2026-04-03','Tuba Mohsin','Datafix','edw_core','tquote_auto_garage_location','garage_address_line1','Fixed the address for 6 auto policies and 1 home policy in EDW and Metal. This is just a one time update.','55','Yes','2026-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12908','Data Fixes: Fixed the address for 6 auto policies and 1 home policy','Bug','2026-04-03','Tuba Mohsin','Datafix','edw_core','tquote_auto_garage_location','garage_address_line2','Fixed the address for 6 auto policies and 1 home policy in EDW and Metal. This is just a one time update.','55','Yes','2026-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12921','Data Fixes :  Updated the document_delivery_to and document_delivery_method for CO200027211','Bug','2026-04-03','Yunus Mohammed','Datafix','edw_core','tpolicy','document_delivery_to','Updated the document_delivery_to and document_delivery_method for CO200027211. Data is updated in Metal and EDW. This is just a onetime update. ','55','Yes','2026-04-06',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12921','Data Fixes :  Updated the document_delivery_to and document_delivery_method for CO200027211','Bug','2026-04-03','Yunus Mohammed','Datafix','edw_core','tpolicy','document_delivery_method','Updated the document_delivery_to and document_delivery_method for CO200027211. Data is updated in Metal and EDW. This is just a onetime update. ','55','Yes','2026-04-06',getdate(),getdate());