INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 04/20/2026 :</span>
    <h4 style="margin-top: 0;font-style: italic;color: blue;">This release had 5 enhancements and 7 bug fix tickets.  Release details are as follows.</h4>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; }
        h1, h2 { color: #333; }
        ul { margin: 10px 0; padding-left: 20px; }
    </style>
</head>
<body>
    <h2 style="font-style: italic;">1. EDW/Datamart Enhancements</h2>
    <ul>
        <li>Added column - risk_address_county_nm to tpolicy and tquote tables.</li>
        <li>Added column - roof_geometry_api to thome_coverage and tquote_home_coverage tables.</li>
        <li>Updated mapping for unit_no in tpel_location and tquote_pel_location tables.</li>
        <li>Added columns - loss_location_desc, large_loss_in, closed_reason_desc,claim_last_updated_ts to tcommercial_claim_feature table.</li>
        <li>Added column - closed_reason_desc to tcommercial_claim_feature table.</li>
    </ul>
    <h2 style="font-style: italic;">2. EDW Integrations</h2>
    <h3>a. IVANS</h3>
    <ul>
        <li>INC-50759/INC-5076/INC-51207/INC-51201 : Resent the IVANS policies associated with these tickets.</li>
    </ul>
    <h2 style="font-style: italic;">3. Data Fixes</h2>
    <ul>
        <li>AD13077: Updated uninsured_motorist_limit_amt for one policy AU200039147 in Metal and EDW. This is a one time update.</li>
        <li>INC32329: Updated address_line_1 and address_line_2 for 27 policies to clean up the addresses in Metal and EDW. This is just a one time update.  </li>
        <li>INC50981: Updated the subscriber contribution end date to NULL for one customer in Metal and EDW. This is just a one time update.</li>
    </ul>
</body>
'
,'Yes'
,'2026-04-20'
,getdate()
,getdate()
)
;

INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13102','EDW/Datamart Enhancements: Added the column - risk_address_county_nm to tpolicy and tquote tables. ','Enhancement','2026-04-17','Yunus Mohammed','Addition','edw_core','tpolicy','risk_address_county_nm','Added the column - risk_address_county_nm to tpolicy and tquote tables. ','56','Yes','2026-04-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13102','EDW/Datamart Enhancements: Added the column - risk_address_county_nm to tpolicy and tquote tables. ','Enhancement','2026-04-17','Yunus Mohammed','Addition','edw_core','tquote','risk_address_county_nm','Added the column - risk_address_county_nm to tpolicy and tquote tables. ','56','Yes','2026-04-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13045','EDW/Datamart Enhancements: Added the column - roof_geometry_api to thome_coverage and tquote_home_coverage tables.','Enhancement','2026-04-17','Yunus Mohammed','Addition','edw_core','thome_coverage','roof_geometry_api','Added the column - roof_geometry_api to thome_coverage and tquote_home_coverage tables.','56','Yes','2026-04-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13045','EDW/Datamart Enhancements: Added the column - roof_geometry_api to thome_coverage and tquote_home_coverage tables.','Enhancement','2026-04-17','Yunus Mohammed','Addition','edw_core','tquote_home_coverage','risk_address_county_nm','Added the column - roof_geometry_api to thome_coverage and tquote_home_coverage tables.','56','Yes','2026-04-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13048','EDW/Datamart Enhancements: Updated the mapping for unit_no in tpel_location and tquote_pel_location tables. ','Enhancement','2026-04-17','Tuba Mohsin','Modification','edw_core','tpel_location','unit_no','Updated the mapping for unit_no in tpel_location and tquote_pel_location tables. ','56','Yes','2026-04-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13048','EDW/Datamart Enhancements: Updated the mapping for unit_no in tpel_location and tquote_pel_location tables. ','Enhancement','2026-04-17','Tuba Mohsin','Modification','edw_core','tquote_pel_location','unit_no','Updated the mapping for unit_no in tpel_location and tquote_pel_location tables. ','56','Yes','2026-04-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11426','EDW/Datamart Enhancements: Added columns to tcommercial_claim table','Enhancement','2026-04-17','Yunus Mohammed','Addition','edw_core','tcommercial_claim ','loss_location_desc ','Added new column','56','Yes','2026-04-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11426','EDW/Datamart Enhancements: Added columns to tcommercial_claim table','Enhancement','2026-04-17','Yunus Mohammed','Addition','edw_core','tcommercial_claim ','large_loss_in','Added new column','56','Yes','2026-04-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11426','EDW/Datamart Enhancements: Added columns to tcommercial_claim table','Enhancement','2026-04-17','Yunus Mohammed','Addition','edw_core','tcommercial_claim ','closed_reason_desc','Added new column','56','Yes','2026-04-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11426','EDW/Datamart Enhancements: Added columns to tcommercial_claim table','Enhancement','2026-04-17','Yunus Mohammed','Addition','edw_core','tcommercial_claim ','claim_last_updated_ts ','Added new column','56','Yes','2026-04-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD11426','EDW/Datamart Enhancements: Added column to tcommercial_claim_feature table','Enhancement','2026-04-17','Yunus Mohammed','Addition','edw_core','tcommercial_claim_feature','closed_reason_desc','Added new column','56','Yes','2026-04-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC-50759/INC-5076/INC-51207/INC-51201','IVANS Policy Resent Request','Bug','2026-04-17','Rushin Shah','Datafix','edw_integration','policy_ivans_collections_feed','','Resent a collections policy to IVANS','56','Yes','2026-04-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC-50759/INC-5076/INC-51207/INC-51201','IVANS Policy Resent Request','Bug','2026-04-17','Rushin Shah','Datafix','edw_integration','policy_ivans_home_feed','','Resent a home policy to IVANS','56','Yes','2026-04-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC-50759/INC-5076/INC-51207/INC-51201','IVANS Policy Resent Request','Bug','2026-04-17','Rushin Shah','Datafix','edw_integration','policy_ivans_pel_feed','','Resent a pel policy to IVANS','56','Yes','2026-04-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC-50759/INC-5076/INC-51207/INC-51201','IVANS Policy Resent Request','Bug','2026-04-17','Rushin Shah','Datafix','edw_integration','policy_ivans_auto_feed','','Resent a auto policy to IVANS','56','Yes','2026-04-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC32329','Data Fixes : Updated address_line_1 and address_line_2 for 27 policies','Bug','2026-04-17','Tuba Mohsin','Datafix','edw_core','thome_location','address_line_1','Updated address_line_1 and address_line_2 for 27 policies to clean up the addresses in Metal and EDW. This is a one time update. ','56','Yes','2026-04-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC32329','Data Fixes : Updated address_line_1 and address_line_2 for 27 policies','Bug','2026-04-17','Tuba Mohsin','Datafix','edw_core','thome_location','address_line_2','Updated address_line_1 and address_line_2 for 27 policies to clean up the addresses in Metal and EDW. This is a one time update. ','56','Yes','2026-04-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC32329','Data Fixes : Updated address_line_1 and address_line_2 for 27 policies','Bug','2026-04-17','Tuba Mohsin','Datafix','edw_core','tquote_home_location','address_line_1','Updated address_line_1 and address_line_2 for 27 policies to clean up the addresses in Metal and EDW. This is a one time update. ','56','Yes','2026-04-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC32329','Data Fixes : Updated address_line_1 and address_line_2 for 27 policies','Bug','2026-04-17','Tuba Mohsin','Datafix','edw_core','tquote_home_location','address_line_2','Updated address_line_1 and address_line_2 for 27 policies to clean up the addresses in Metal and EDW. This is a one time update. ','56','Yes','2026-04-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13077','Data Fixes : Updated uninsured_motorist_limit_amt for policy AU200039147','Bug','2026-04-17','Tuba Mohsin','Datafix','edw_core','tauto_policy_coverage','uninsured_motorist_limit_amt','Updated uninsured_motorist_limit_amt for the policy : AU200039147 in Metal and EDW. This is a one time update.','56','Yes','2026-04-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13077','Data Fixes : Updated uninsured_motorist_limit_amt for policy AU200039147','Bug','2026-04-17','Tuba Mohsin','Datafix','edw_core','tquote_auto_policy_coverage','uninsured_motorist_limit_amt','Updated uninsured_motorist_limit_amt for the policy : AU200039147 in Metal and EDW. This is a one time update.','56','Yes','2026-04-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC50981','Data Fixes :  Updated the subscriber contribution end date to NULL for one customer','Bug','2026-04-17','Tuba Mohsin','Datafix','edw_core','tpolicy_insured','subscriber_contribution_end_dt',' Updated the subscriber contribution end date to NULL for the customer associated with this quote HO200118323 in Metal and EDW.  This is a one time update.','56','Yes','2026-04-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC50981','Data Fixes :  Updated the subscriber contribution end date to NULL for one customer','Bug','2026-04-17','Tuba Mohsin','Datafix','edw_core','tquote_insured','subscriber_contribution_end_dt',' Updated the subscriber contribution end date to NULL for the customer associated with this quote HO200118323 in Metal and EDW.  This is a one time update.','56','Yes','2026-04-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC50981','Data Fixes :  Updated the subscriber contribution end date to NULL for one customer','Bug','2026-04-17','Tuba Mohsin','Datafix','edw_core','tcustomer','subscriber_contribution_end_dt',' Updated the subscriber contribution end date to NULL for the customer associated with this quote HO200118323 in Metal and EDW.  This is a one time update.','56','Yes','2026-04-20',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13082','Process Improvements : Updated validations to tvalidation_sql','Enhancement','2026-04-17','Yunus Mohammed','Modification','edw_core','tvalidation_sql','','Few validation SQL were added','56','No','2026-04-20',getdate(),getdate());