INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 05/11/2026 :</span>
    <h4 style="margin-top: 0;font-style: italic;color: blue;">This release had 16 enhancements and 18 bug fix tickets.  Release details are as follows.</h4>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; }
        h1, h2 { color: #333; }
        ul { margin: 10px 0; padding-left: 20px; }
    </style>
</head>
<body>
    <h2 style="font-style: italic;">1. EDW/Datamart Enhancements</h2>
    <ul>
        <li>Added column - grpel_policy_credit_in to tpolicy_history and tquote_history tables.</li>
        <li>Added column - no_of_other_watercraft to tgrpel_coverage and tquote_grpel_coverage tables.</li>
        <li>Added column - enrollment_end_dt to tgrpel_master_coverage_enrollment.</li>
        <li>Added columns underlying_auto_liability_limit_amt, underlying_home_liability_limit_amt and underlying_watercraft_liability_limit_amt to tquote_grpel_coverage table.</li>
        <li>Created a new tgrpel_participant table to capture participant enrollment information.</li>
        <li>Created a new tsubjecitivity table to capture subjectivity details. </li>
        <li>Created a new tbilling_account_payment table to capture payment activity.</li>
        <li>Dropped table tcommercial_policy_subjectivity and tcommercial_quote_subjectivity and replaced it with tcommercial_subjectivity table.</li>
        <li>Updated the mapping for columns underlying_auto_liability_limit_amt, underlying_home_liability_limit_amt and underlying_watercraft_liability_limit_amt in tgrpel_coverage table.</li>
        <li>Updated following stored procedures for better performance : tadditional_interest, tquote_additional_interest and tquote_manuscript.</li>
        <li>Updated tclaim_feature stored procedures to populate item_sk associated with boat and yacht policies.</li>
        <li>Updated tclaim_transaction and tcommercial_claim_transaction stored procedures to capture accurate transaction details associated with recoded payments.</li>
        <li>Updated taslob table to include "extra contractual" and "hull value" coverages.</li>
        
    </ul>
    <h2 style="font-style: italic;">2. EDW Integrations</h2>
    <h3>a. Commercial Claims API</h3>
    <ul>
        <li>Implemented EDW updates for Commercial Lines Claims integration and created the commercial_claim_renewal_rating_api table.</li>
    </ul>
    <h3>b. Group PEL Billing Reports</h3>
    <ul>
        <li>Created billing_grpel_cash_activity_feed and billing_grpel_payment_due_feed tables for reporting associated with Group PEL billing.</li>
    </ul>
    <h3>c. LiveVox / Aircall</h3>
    <ul>
        <li>Completed the transition to begin receiving Vault call data from Aircall and retire the LiveVox system.</li>
    </ul>
    <h3>d. IVANS</h3>
    <ul>
        <li>INC-51327/INC-51326/INC-51206/INC-51203/INC-51200/INC-51204/INC-50956/INC-51125/INC-51122/INC-51689/INC-51604/INC-51606/INC-51709: Resent the policies associated with these tickets.</li>
    </ul>
    <h2 style="font-style: italic;">3. Data Fixes</h2>
    <ul>
        <li>AD13220: Updated claim transaction associated with recovery reserves for one claim 26ATFL819445495.</li>
        <li>AD13304: Updated the uninsured motorist limit amount to NULL for 4 auto policies.</li>
        <li>AD13236: Updated the missing VIN number for a vehicle on this auto policy AU200041387.</li>
    </ul>
</body>
'
,'Yes'
,'2026-05-11'
,getdate()
,getdate()
)
;

INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13262','EDW/Datamart Enhancements: Added the column - grpel_policy_credit_in  to tpolicy_history and tquote_history tables','Enhancement','2026-05-09','Yunus Mohammed','Addition','edw_core','tpolicy_history','grpel_policy_credit_in','Added new column','57','Yes','2026-05-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13262','EDW/Datamart Enhancements: Added the column - grpel_policy_credit_in  to tpolicy_history and tquote_history tables','Enhancement','2026-05-09','Yunus Mohammed','Addition','edw_core','tquote_history','grpel_policy_credit_in','Added new column','57','Yes','2026-05-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13208','EDW/Datamart Enhancements: Created new table tgrpel_participant','Enhancement','2026-05-09','Tuba Mohsin','Addition','edw_core','tgrpel_participant','','Created new table','57','Yes','2026-05-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13199','EDW/Datamart Enhancements: Created new table tsubjectivity','Enhancement','2026-05-09','Yunus Mohammed','Addition','edw_core','tsubjectivity','','Created new table','57','Yes','2026-05-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13199','EDW/Datamart Enhancements: Created new table tcommercial_subjectivity','Enhancement','2026-05-09','Yunus Mohammed','Addition','edw_commercial','tcommercial_subjectivity','','Created new table','57','Yes','2026-05-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13199','EDW/Datamart Enhancements: Dropped the tcommercial_policy_subjectivity and tcommercial_quote_subjectivity tables','Enhancement','2026-05-09','Yunus Mohammed','Deletion','edw_commercial','tcommercial_policy_subjectivity','','Dropped the table','57','Yes','2026-05-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13199','EDW/Datamart Enhancements: Dropped the tcommercial_policy_subjectivity and tcommercial_quote_subjectivity tables','Enhancement','2026-05-09','Yunus Mohammed','Deletion','edw_commercial','tcommercial_quote_subjectivity','','Dropped the table','57','Yes','2026-05-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13248','EDW/Datamart Enhancements: Added the column - enrollment_end_dt to tgrpel_master_coverage_enrollment','Enhancement','2026-05-09','Yunus Mohammed','Addition','edw_core','tgrpel_master_coverage_enrollment','enrollment_end_dt','Added new column','57','Yes','2026-05-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13248','EDW/Datamart Enhancements: Added column - no_of_other_watercraft to tgrpel_coverage and tquote_grpel_coverage','Enhancement','2026-05-09','Yunus Mohammed','Addition','edw_core','tgrpel_coverage','no_of_other_watercraft','Added new column','57','Yes','2026-05-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13248','EDW/Datamart Enhancements: Added column - no_of_other_watercraft to tgrpel_coverage and tquote_grpel_coverage','Enhancement','2026-05-09','Yunus Mohammed','Addition','edw_core','tquote_grpel_coverage','no_of_other_watercraft','Added new column','57','Yes','2026-05-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13248','EDW/Datamart Enhancements: Added columns to tquote_grpel_coverage','Enhancement','2026-05-09','Yunus Mohammed','Addition','edw_core','tquote_grpel_coverage','underlying_auto_liability_limit_amt','Added new column','57','Yes','2026-05-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13248','EDW/Datamart Enhancements: Added columns to tquote_grpel_coverage','Enhancement','2026-05-09','Yunus Mohammed','Addition','edw_core','tquote_grpel_coverage','underlying_home_liability_limit_amt','Added new column','57','Yes','2026-05-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13248','EDW/Datamart Enhancements: Added columns to tquote_grpel_coverage','Enhancement','2026-05-09','Yunus Mohammed','Addition','edw_core','tquote_grpel_coverage','underlying_watercraft_liability_limit_amt','Added new column','57','Yes','2026-05-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13248','EDW/Datamart Enhancements: Updated mapping for columns in tgrpel_coverage','Enhancement','2026-05-09','Yunus Mohammed','Modification','edw_core','tgrpel_coverage','underlying_auto_liability_limit_amt','Updated stored procedure to modify mapping for one column','57','Yes','2026-05-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13248','EDW/Datamart Enhancements: Updated mapping for columns in tgrpel_coverage','Enhancement','2026-05-09','Yunus Mohammed','Modification','edw_core','tgrpel_coverage','underlying_home_liability_limit_amt','Updated stored procedure to modify mapping for one column','57','Yes','2026-05-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13248','EDW/Datamart Enhancements: Updated mapping for columns in tgrpel_coverage','Enhancement','2026-05-09','Yunus Mohammed','Modification','edw_core','tgrpel_coverage','underlying_watercraft_liability_limit_amt','Updated stored procedure to modify mapping for one column','57','Yes','2026-05-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13207','EDW/Datamart Enhancements: Dropped table tquote_grpel_master_coverage_enrollment','Enhancement','2026-05-09','Yunus Mohammed','Deletion','edw_core','tquote_grpel_master_coverage_enrollment','','Dropped the table','57','Yes','2026-05-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12974','EDW/Datamart Enhancements: Created a new table tbilling_account_payment','Enhancement','2026-05-09','Yunus Mohammed','Addition','edw_core','tbilling_account_payment','','Created new table','57','Yes','2026-05-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12470','Process Enhancements: Updated the stored procedures of the following tables for better performance','Enhancement','2026-05-09','Yunus Mohammed','Modification','edw_core','tadditional_interest','','Updated the stored procedures of the following table to run quicker','57','Yes','2026-05-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12470','Process Enhancements: Updated the stored procedures of the following tables for better performance','Enhancement','2026-05-09','Yunus Mohammed','Modification','edw_core','tquote_additional_interest','','Updated the stored procedures of the following table to run quicker','57','Yes','2026-05-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD12470','Process Enhancements: Updated the stored procedures of the following tables for better performance','Enhancement','2026-05-09','Yunus Mohammed','Modification','edw_core',' tquote_manuscript','','Updated the stored procedures of the following table to run quicker','57','Yes','2026-05-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13218','EDW/Datamart Enhancements: Updated tclaim_feature Sp so that item_sk associated with boat_yacht gets populated','Enhancement','2026-05-09','Yunus Mohammed','Modification','edw_core','tclaim_feature','item_sk','Updated the store procedure for tclaim_feature to populate item_sk associated with boat_yacht policies','57','Yes','2026-05-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13218','EDW/Datamart Enhancements: Updated tclaim_feature Sp so that item_sk associated with boat_yacht gets populated','Enhancement','2026-05-09','Yunus Mohammed','Modification','edw_core','tclaim_feature','coverage_sk','Updated the store procedure for tclaim_feature to populate coverage_sk associated with boat_yacht policies','57','Yes','2026-05-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13266/AD13298','EDW/Datamart Enhancements: Added coverages to taslob table','Enhancement','2026-05-09','Rushin Shah','Addition','edw_core','taslob','','Updated taslob table to capture extra contractual and hull value coverages.','57','Yes','2026-05-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13186','EDW/Datamart Enhancements: Recoded claim payments','Enhancement','2026-05-09','Yunus Mohammed','Modification','edw_core','tclaim_transaction','','Updated stored procedures to capture accurate transaction details associated with recoded payments.','57','Yes','2026-05-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13186','EDW/Datamart Enhancements: Recoded claim payments','Enhancement','2026-05-09','Yunus Mohammed','Modification','edw_commercial','tcommercial_claim_transaction','','Updated stored procedures to capture accurate transaction details associated with recoded payments.','57','Yes','2026-05-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13121','EDW Integrations : Implemented EDW updates for Commercial Lines Claims integration','Enhancement','2026-05-09','Yunus Mohammed','Addition','edw_integration','commercial_claim_renewal_rating_api','','Created new table','57','Yes','2026-05-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13228','EDW Integrations : Created new GRPEL billing tables','Enhancement','2026-05-09','Rushin Shah','Addition','edw_integration','billing_grpel_cash_activity_feed','','Created new table','57','Yes','2026-05-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13228','EDW Integrations : Created new GRPEL billing tables','Enhancement','2026-05-09','Rushin Shah','Addition','edw_integration','billing_grpel_payment_due_feed','','Created new table','57','Yes','2026-05-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13217','EDW Integrations : LiveVox to Aircall transistion','Enhancement','2026-05-09','Yunus Mohammed','Addition','edw_stage','stage_aircall_list_all_calls','','Completed the transition to begin receiving Vault’s call data from Aircall and retire the LiveVox system.','57','Yes','2026-05-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC-51327/INC-51326/INC-51206/INC-51203/INC-51200/INC-51204/INC-50956/INC-51125/INC-51122/INC-51689/INC-51604/INC-51606/INC-51709','IVANS Policy Resent Request','Bug','2026-05-09','Rushin Shah','Datafix','edw_integration','policy_ivans_collections_feed','','Resent a few collection policies to IVANS','57','Yes','2026-05-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC-51327/INC-51326/INC-51206/INC-51203/INC-51200/INC-51204/INC-50956/INC-51125/INC-51122/INC-51689/INC-51604/INC-51606/INC-51709','IVANS Policy Resent Request','Bug','2026-05-09','Rushin Shah','Datafix','edw_integration','policy_ivans_home_feed','','Resent a few home policies to IVANS','57','Yes','2026-05-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC-51327/INC-51326/INC-51206/INC-51203/INC-51200/INC-51204/INC-50956/INC-51125/INC-51122/INC-51689/INC-51604/INC-51606/INC-51709','IVANS Policy Resent Request','Bug','2026-05-09','Rushin Shah','Datafix','edw_integration','policy_ivans_auto_feed','','Resent a few auto policies to IVANS','57','Yes','2026-05-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC-51327/INC-51326/INC-51206/INC-51203/INC-51200/INC-51204/INC-50956/INC-51125/INC-51122/INC-51689/INC-51604/INC-51606/INC-51709','IVANS Policy Resent Request','Bug','2026-05-09','Rushin Shah','Datafix','edw_integration','policy_ivans_pel_feed','','Resent a few pel policies to IVANS','57','Yes','2026-05-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13220','Data Fixes: Updated claim transaction associated with one claim','Bug','2026-05-09','Rushin Shah','Datafix','edw_core','tclaim_transaction','salvage_recovery_reserve_amt ','Updated claim transaction associated with recovery reserves for one claim 26ATFL819445495','57','Yes','2026-05-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13218/AD13205/AD13304','Data Fixes: Updated uninsured_motorist_limit_amt to NULL for 4 auto policies','Bug','2026-05-09','Tuba Mohsin','Datafix','edw_core','tauto_policy_coverage','uninsured_motorist_limit_amt',' Updated uninsured_motorist_limit_amt to NULL for 4 auto policies','57','Yes','2026-05-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13218/AD13205/AD13304','Data Fixes: Updated uninsured_motorist_limit_amt to NULL for 4 auto policies','Bug','2026-05-09','Tuba Mohsin','Datafix','edw_core','tquote_auto_policy_coverage','uninsured_motorist_limit_amt',' Updated uninsured_motorist_limit_amt to NULL for 4 auto policies','57','Yes','2026-05-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13236','Data Fixes: Updated the missing VIN number for one policy AU200041387','Bug','2026-05-09','Tuba Mohsin','Datafix','edw_core','tauto_vehicle ','vehicle_vin ',' Updated the missing VIN number for a vehicle for one policy AU200041387','57','Yes','2026-05-11',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13195','Process Improvements : Updated validations to tvalidation_sql','Enhancement','2026-05-09','Tuba Mohsin','Modification','edw_core','tvalidation_sql','','Few validation SQL were added','57','Yes','2026-05-11',getdate(),getdate());