INSERT INTO edw_core.tedw_release_summary (release_summary, send_email_in, send_email_dt, create_ts, update_ts)
VALUES (
'
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <span style="background-color: #9D0208; color: white; font-weight: bold; font-size: 18px; padding: 5px; display: inline-block; text-decoration: underline;">Release Summary - 05/25/2026 :</span>
    <h4 style="margin-top: 0;font-style: italic;color: blue;">This release had 7 enhancements and 9 bug fix tickets.  Release details are as follows.</h4>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; }
        h1, h2 { color: #333; }
        ul { margin: 10px 0; padding-left: 20px; }
    </style>
</head>
<body>
    <h2 style="font-style: italic;">1. EDW/Datamart Enhancements</h2>
    <ul>
        <li>Added the column - wind_hail_roof_covering_schedule_in to thome_additional_coverage and and tquote_home_additional_coverage tables.</li>
        <li>Updated tgrpel_master_coverage and tquote_grpel_master_coverage stored procedures to populate appropriate product code associated with GPEL policies.</li>
    </ul>
    <h2 style="font-style: italic;">2. EDW Integrations</h2>
    <h3>a. Claims Renewal Rating API</h3>
    <ul>
        <li>Added a new column TotalLoss to claim_renewal_rating_auto_pel_api and claim_renewal_rating_home_collection_api tables.</li>
    </ul>
    <h3>b. Claims Policy Webhook Snapsheet API</h3>
    <ul>
        <li>Updated the stored procedure to populate the email address using the claims contact email; if unavailable, it defaults to the broker email.</li>
    </ul>
    <h3>c. Group PEL Billing Report (billing_grpel_payment_due_feed)</h3>
    <ul>
        <li>Added new columns : group_minimum_premium and broker_commission</li>
        <li>Renamed total_premium column to total_participant_premium</li>
        <li>Renamed payments_made column to payments_received</li>
        <li>Renamed balance_due_as_of_month_end column to net_amount_due_to_vault</li>
    </ul>
    <h3>d. IVANS</h3>
    <ul>
        <li>INC-51939/INC-51938/INC-51937/INC-51935/INC-51934/INC-51933/INC-51932 : Resent the policies associated with this ticket.</li>
    </ul>
    <h2 style="font-style: italic;">3. EDW Process Enhancements</h2>
    <ul>
        <li>Added validations to identify inforce policies which has ceded premium associated with HSB coverages but no gross premium amount.</li>
        <li>Added validation to identify policies which has transaction effective date after policy expiration date.</li>
    </ul>
    <h2 style="font-style: italic;">4. Data Fixes</h2>
    <ul>
        <li>AD13389: Deleted 2 commercial claims incorrectly added to the Personal Lines claims table due to missing commercial classification tags.</li>
        <li>AD13392: Deleted 4 group excess participant quotes created in error from Metal and EDW.</li>
    </ul>
</body>
'
,'Yes'
,'2026-05-25'
,getdate()
,getdate()
)
;

INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13315','EDW/Datamart Enhancements: Added the column - wind_hail_roof_covering_schedule_in to thome_additional_coverage and tquote_home_additional_coverage tables','Enhancement','2026-05-22','Yunus Mohammed','Addition','edw_core','thome_additional_coverage ','wind_hail_roof_covering_schedule_in ','Added new column','58','Yes','2026-05-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13315','EDW/Datamart Enhancements: Added the column - wind_hail_roof_covering_schedule_in to thome_additional_coverage and tquote_home_additional_coverage tables','Enhancement','2026-05-22','Yunus Mohammed','Addition','edw_core','tquote_home_additional_coverage ','wind_hail_roof_covering_schedule_in ','Added new column','58','Yes','2026-05-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13391','EDW/Datamart Enhancements: Updated tgrpel_master_coverage and tquote_grpel_master_coverage tables to update the product_cd','Enhancement','2026-05-22','Yunus Mohammed','Modification','edw_core','tgrpel_master_coverage ','product_cd','Updated stored procedure to modify mapping for one column','58','Yes','2026-05-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13391','EDW/Datamart Enhancements: Updated tgrpel_master_coverage and tquote_grpel_master_coverage tables to update the product_cd','Enhancement','2026-05-22','Yunus Mohammed','Modification','edw_core','tquote_grpel_master_coverage    ','product_cd','Updated stored procedure to modify mapping for one column','58','Yes','2026-05-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13356','EDW Integrations : Added a new column TotalLoss to claim_renewal_rating_auto_pel_api and claim_renewal_rating_home_collection_api tables','Enhancement','2026-05-22','Yunus Mohammed','Addition','edw_integration','claim_renewal_rating_auto_pel_api','TotalLoss','Added new column','58','Yes','2026-05-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13356','EDW Integrations : Added a new column TotalLoss to claim_renewal_rating_auto_pel_api and claim_renewal_rating_home_collection_api tables','Enhancement','2026-05-22','Yunus Mohammed','Addition','edw_integration','claim_renewal_rating_home_collection_api','TotalLoss','Added new column','58','Yes','2026-05-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13403','EDW Integrations : Updated the stored procedure to populate the email address using the claims contact email; if unavailable, it defaults to the broker email.','Enhancement','2026-05-22','Yunus Mohammed','Modification','edw_integration','claim_policy_webhook_snapsheet_api','agentInformation','Updated stored procedure to modify mapping for one column','58','Yes','2026-05-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13380','EDW Integrations : Made updates to billing_grpel_payment_due_feed','Enhancement','2026-05-22','Yunus Mohammed','Addition','edw_integration','billing_grpel_payment_due_feed','group_minimum_premium','Added new column','58','Yes','2026-05-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13380','EDW Integrations : Made updates to billing_grpel_payment_due_feed','Enhancement','2026-05-22','Yunus Mohammed','Addition','edw_integration','billing_grpel_payment_due_feed','broker_commission','Added new column','58','Yes','2026-05-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13380','EDW Integrations : Made updates to billing_grpel_payment_due_feed','Enhancement','2026-05-22','Yunus Mohammed','Modification','edw_integration','billing_grpel_payment_due_feed','total_participant_premium','Updated column name ','58','Yes','2026-05-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13380','EDW Integrations : Made updates to billing_grpel_payment_due_feed','Enhancement','2026-05-22','Yunus Mohammed','Addition','edw_integration','billing_grpel_payment_due_feed','payments_received','Updated column name ','58','Yes','2026-05-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13380','EDW Integrations : Made updates to billing_grpel_payment_due_feed','Enhancement','2026-05-22','Yunus Mohammed','Addition','edw_integration','billing_grpel_payment_due_feed',' net_amount_due_to_vault','Updated column name ','58','Yes','2026-05-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC-51939/INC-51938/INC-51937/INC-51935/INC-51934/INC-51933/INC-51932','IVANS Policy Resent Request','Bug','2026-05-22','Rushin Shah','Datafix','edw_integration','policy_ivans_collections_feed','','Resent a few collection policies to IVANS','58','Yes','2026-05-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC-51939/INC-51938/INC-51937/INC-51935/INC-51934/INC-51933/INC-51932','IVANS Policy Resent Request','Bug','2026-05-22','Rushin Shah','Datafix','edw_integration','policy_ivans_home_feed','','Resent a few home policies to IVANS','58','Yes','2026-05-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC-51939/INC-51938/INC-51937/INC-51935/INC-51934/INC-51933/INC-51932','IVANS Policy Resent Request','Bug','2026-05-22','Rushin Shah','Datafix','edw_integration','policy_ivans_auto_feed','','Resent a few auto policies to IVANS','58','Yes','2026-05-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('INC-51939/INC-51938/INC-51937/INC-51935/INC-51934/INC-51933/INC-51932','IVANS Policy Resent Request','Bug','2026-05-22','Rushin Shah','Datafix','edw_integration','policy_ivans_pel_feed','','Resent a few pel policies to IVANS','58','Yes','2026-05-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13401','Process Improvements : Added validations to identify inforce policies which has ceded premium associated with HSB coverages but no gross premium amount.','Enhancement','2026-05-22','Yunus Mohammed','Modification','edw_core','tvalidation_sql','','Added new validation','58','Yes','2026-05-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13292','Process Improvements : Added validation to identify policies which has transaction effective date after policy expiration date','Enhancement','2026-05-22','Yunus Mohammed','Modification','edw_core','tvalidation_sql','','Added new validation','58','Yes','2026-05-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13389/AD13411','Data Fixes: Deleted 7 commercial claims incorrectly added to the Personal Lines claims table due to missing commercial classification tags.','Bug','2026-05-22','Yunus Mohammed','Datafix','edw_core','tclaim','','Deleted details associated with 7 commercial claims from EDW.  This is just a onetime update.','58','Yes','2026-05-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13389/AD13411','Data Fixes: Deleted 7 commercial claims incorrectly added to the Personal Lines claims table due to missing commercial classification tags.','Bug','2026-05-22','Yunus Mohammed','Datafix','edw_core','tclaim_tag','','Deleted details associated with 7 commercial claims from EDW.  This is just a onetime update.','58','Yes','2026-05-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13389/AD13411','Data Fixes: Deleted 7 commercial claims incorrectly added to the Personal Lines claims table due to missing commercial classification tags.','Bug','2026-05-22','Yunus Mohammed','Datafix','edw_core','tclaim_task','','Deleted details associated with 7 commercial claims from EDW.  This is just a onetime update.','58','Yes','2026-05-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13389/AD13411','Data Fixes: Deleted 7 commercial claims incorrectly added to the Personal Lines claims table due to missing commercial classification tags.','Bug','2026-05-22','Yunus Mohammed','Datafix','edw_core','tclaim_note','','Deleted details associated with 7 commercial claims from EDW.  This is just a onetime update.','58','Yes','2026-05-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13389/AD13411','Data Fixes: Deleted 7 commercial claims incorrectly added to the Personal Lines claims table due to missing commercial classification tags.','Bug','2026-05-22','Yunus Mohammed','Datafix','edw_core','tclaim_feature ','','Deleted details associated with 7 commercial claims from EDW.  This is just a onetime update.','58','Yes','2026-05-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13392','Data Fixes: Deleted 4 group excess participant quotes created in error from Metal and EDW.','Bug','2026-05-22','Yunus Mohammed','Datafix','edw_core','tquote_history','','Deleted 4 group excess participant quotes created in error from Metal and EDW.  This is just a onetime update.','58','Yes','2026-05-25',getdate(),getdate());
INSERT INTO edw_core.tedw_release_note (ticket_no, ticket_short_desc, ticket_type, production_deployment_dt, resource_nm, database_change_type, impacted_table_schema, impacted_table_nm, impacted_column_nm, resolution_summary, edw_release_summary_sk, send_email_in, send_email_dt, create_ts, update_ts) VALUES ('AD13392','Data Fixes: Deleted 4 group excess participant quotes created in error from Metal and EDW.','Bug','2026-05-22','Yunus Mohammed','Datafix','edw_core','tquote','','Deleted 4 group excess participant quotes created in error from Metal and EDW.  This is just a onetime update.','58','Yes','2026-05-25',getdate(),getdate());