PHRASE_TO_TABLE = {
    "ADJUST WRITEOFF":"stage_majesco_adjust_writeoff",
    "AGENCY LEVEL MONTHLY COMMISSION BALANCE":"stage_majesco_agency_level_monthly_commission_balance",
    "BILLING FEE":"stage_majesco_billing_fee",
    "CASH ACTIVITY":"stage_majesco_cash_activity",
    "COMMISSION DISBURSEMENT REGISTER":"stage_majesco_commission_disbursement_register",
    "DISBURSEMENT REGISTER":"stage_majesco_disbursement_register",
    "DUE DATE AGING":"stage_majesco_due_date_aging",
    "POLICY LEVEL MONTHLY COMMISSION BALANCE":"stage_majesco_policy_level_monthly_commission_balance",
    "PREMIUM ACTIVITY REPORT":"stage_majesco_premium_activity_report",
}

# ------------------------------------------------------------
# ---------------------------Mapping--------------------------
# ------------------------------------------------------------

# ------------------------------ 1 ------------------------------
# Mapping for stage_majesco_adjust_writeoff
stage_majesco_adjust_writeoff = {
    'Operating Company Code': 'operating_company_code',
    'Operating Company': 'operating_company',
    'Underwriting Company Code': 'underwriting_company_code',
    'Underwriting Company': 'underwriting_company',
    'Operating Region Code': 'operating_region_code',
    'Operating Region': 'operating_region',
    'Agency Code': 'agency_code',
    'Agency Name': 'agency_name',
    'Account Code': 'account_code',
    'Policy No': 'policy_no',
    'Policy Eff Date': 'policy_eff_date',
    'Bill Type': 'bill_type',
    'Bill Type Description': 'bill_type_description',
    'Transaction No': 'transaction_no',
    'Transaction Code': 'transaction_code',
    'WriteOff Transaction Type': 'writeoff_transaction_type',
    'Write Off Reason Code': 'write_off_reason_code',
    'Reason Description': 'reason_description',
    'Transaction Receivable Type': 'transaction_receivable_type',
    'Gross Amount': 'gross_amount',
    'Net Amount': 'net_amount',
    'Commission Amount': 'commission_amount',
    'Entry Date': 'entry_date',
    'Accounting Month': 'accounting_month',
    'Adj Writeoff Type': 'adj_writeoff_type',
    'State Name': 'state_name',
    'Product Name': 'product_name',
    'Payment Plan': 'payment_plan',
    'CRT Name': 'crt_name',
    'Policy Term Id': 'policy_term_id',
    'Line of Business': 'line_of_business',
    'User ID': 'user_id',
    'Receivable Code': 'receivable_code',
    'Start Date': 'start_date',
    'End Date': 'end_date',
}

# ------------------------------ 2 ------------------------------
# Mapping for stage_majesco_agency_level_monthly_commission_balance
stage_majesco_agency_level_monthly_commission_balance = {
    'Commission Entity Code': 'commission_entity_code',
    'Commission Entity Name': 'commission_entity_name',
    'Begining Balance': 'begining_balance',
    'Commission to be Paid': 'commission_to_be_paid',
    'Commission Adjustment': 'commission_adjustment',
    'Commission Paid': 'commission_paid',
    'Ending Balance': 'ending_balance',
    'Month': 'month',
}

# ------------------------------ 3 ------------------------------
# Mapping for stage_majesco_billing_fee
stage_majesco_billing_fee = {
    'Operating Company Code': 'operating_company_code',
    'Operating Company': 'operating_company',
    'Underwriting Company Code': 'underwriting_company_code',
    'Underwriting Company': 'underwriting_company',
    'Agency Code': 'agency_code',
    'Agency Name': 'agency_name',
    'Account Code': 'account_code',
    'Account Name': 'account_name',
    'Policy No': 'policy_no',
    'Policy Eff Date': 'policy_eff_date',
    'Fee Code': 'fee_code',
    'Fee Type': 'fee_type',
    'Fee Date': 'fee_date',
    'Fee Month': 'fee_month',
    'Fee Amount': 'fee_amount',
    'Bill Type': 'bill_type',
    'Operating Region Code': 'operating_region_code',
    'Operating Region': 'operating_region',
    'Governing State': 'governing_state',
    'Product': 'product',
    'Pay Plan': 'pay_plan',
    'CRT Code': 'crt_code',
    'Transaction No': 'transaction_no',
    'Transaction Type': 'transaction_type',
    'Bill Type Description': 'bill_type_description',
    'Start Date': 'start_date',
    'End Date': 'end_date',
}

# ------------------------------ 4 ------------------------------
# Mapping for stage_majesco_cash_activity
stage_majesco_cash_activity = {
    'Operating Company Code': 'operating_company_code',
    'Operating Company': 'operating_company',
    'Underwriting Company Code': 'underwriting_company_code',
    'Underwriting Company': 'underwriting_company',
    'Agency Code': 'agency_code',
    'Agency Name': 'agency_name',
    'Account Code': 'account_code',
    'Account Name': 'account_name',
    'Policy No': 'policy_no',
    'Line Of_Business': 'line_of_business',
    'Company Batch No': 'company_batch_no',
    'Policy Effective Date': 'policy_effective_date',
    'Entry Date': 'entry_date',
    'Accounting Month': 'accounting_month',
    'Receivable Category': 'receivable_category',
    'Receivable Code': 'receivable_code',
    'Receivable Type': 'receivable_type',
    'Pay Type': 'pay_type',
    'Payment Identifier': 'payment_identifier',
    'Batch No': 'batch_no',
    'Check Serial No': 'check_serial_no',
    'Transaction No': 'transaction_no',
    'Amount': 'amount',
    'Transaction Type': 'transaction_type',
    'Bill Type': 'bill_type',
    'Operating Region Code': 'operating_region_code',
    'Operating Region': 'operating_region',
    'CRT Code': 'crt_code',
    'State': 'state',
    'Payment Plan': 'payment_plan',
    'User ID': 'user_id',
    'Bill Type Description': 'bill_type_description',
    'Start Date': 'start_date',
    'End Date': 'end_date',
}

# ------------------------------ 5 ------------------------------
# Mapping for stage_majesco_commission_disbursement_register
stage_majesco_commission_disbursement_register = {
    'Operating Company Code': 'operating_company_code',
    'Operating Company': 'operating_company',
    'Underwriting Company Code': 'underwriting_company_code',
    'Underwriting Company': 'underwriting_company',
    'Accounting Month': 'accounting_month',
    'Transaction Type': 'transaction_type',
    'Transaction Type Description': 'transaction_type_description',
    'Transaction Date': 'transaction_date',
    'Batch No': 'batch_no',
    'Check No': 'check_no',
    'Payment Identifier': 'payment_identifier',
    'Payment Method Code': 'payment_method_code',
    'Payment Method': 'payment_method',
    'Amount': 'amount',
    'Payee Name': 'payee_name',
    'Commission Payee Type': 'commission_payee_type',
    'Commission Payee Code': 'commission_payee_code',
    'Transaction No': 'transaction_no',
    'Month': 'month',
}

# ------------------------------ 6 ------------------------------
# Mapping for stage_majesco_disbursement_register
stage_majesco_disbursement_register = {
    'Operating Company Code': 'operating_company_code',
    'Operating Company': 'operating_company',
    'Underwriting Company Code': 'underwriting_company_code',
    'Underwriting Company': 'underwriting_company',
    'Policy No': 'policy_no',
    'Policy Effective Date': 'policy_effective_date',
    'Bill Type': 'bill_type',
    'Bill Type Description': 'bill_type_description',
    'Payment Identifier': 'payment_identifier',
    'Payer Name': 'payer_name',
    'Accounting Month': 'accounting_month',
    'Refund/Void Date': 'refund_void_date',
    'Amount': 'amount',
    'Transaction Type': 'transaction_type',
    'Transaction Type Description': 'transaction_type_description',
    'Batch No': 'batch_no',
    'Check Serial No': 'check_serial_no',
    'Account Code': 'account_code',
    'Agency Code': 'agency_code',
    'Refund Type': 'refund_type',
    'Suppress Flag': 'suppress_flag',
    'Refund Payment Method Code': 'refund_payment_method_code',
    'Refund Payment Method Description': 'refund_payment_method_description',
    'Receivable Code': 'receivable_code',
    'Transaction No': 'transaction_no',
    'Additional Payee': 'additional_payee',
    'Start Date': 'start_date',
    'End Date': 'end_date',
}

# ------------------------------ 7 ------------------------------
# Mapping for stage_majesco_due_date_aging
stage_majesco_due_date_aging = {
    'Bill Type': 'bill_type',
    'Operating Company': 'operating_company',
    'Underwriting Company': 'underwriting_company',
    'Agency Code': 'agency_code',
    'Agency Name': 'agency_name',
    'Agency City': 'agency_city',
    'Agency State': 'agency_state',
    'Agency Zip Code': 'agency_zip_code',
    'Agency Email Address': 'agency_email_address',
    'Account No': 'account_no',
    'Account Zip Code': 'account_zip_code',
    'Account Email Address': 'account_email_address',
    'Account Name': 'account_name',
    'Policy Number': 'policy_number',
    'Insured Name': 'insured_name',
    'Policy Effective Date': 'policy_effective_date',
    'Policy Status': 'policy_status',
    'Collection Flag': 'collection_flag',
    'CRT Name': 'crt_name',
    'Current Balance': 'current_balance',
    'Aged (1-30)': 'aged_1_30',
    'Aged (31-60)': 'aged_31_60',
    'Aged (61-90)': 'aged_61_90',
    'Aged Over 90': 'aged_over_90',
    'Unbilled Balance': 'unbilled_balance',
    'Unassigned Cash': 'unassigned_cash',
    'Adjustments': 'adjustments',
    'Total Balance': 'total_balance',
    'Serial No': 'serial_no',
    'Sequence No': 'sequence_no',
    'Date Generate': 'date_generate',
    'State Code': 'state_code',
    'State Name': 'state_name',
    'Product Code': 'product_code',
    'Product Name': 'product_name',
    'Payment Plan': 'payment_plan',
    'Last Invoice Send Date': 'last_invoice_send_date',
    'Due Date on the Invoice': 'due_date_on_the_invoice',
    'No. of days the oldest balance is past due': 'no_of_days_the_oldest_balance_is_past_due',
    'Source System': 'source_system',
    'Month': 'month',
}

# ------------------------------ 8 ------------------------------
# Mapping for stage_majesco_policy_level_monthly_commission_balance
stage_majesco_policy_level_monthly_commission_balance = {
    'Accounting Month': 'accounting_month',
    'Policy No': 'policy_no',
    'Policy Term ID': 'policy_term_id',
    'Policy Renew No': 'policy_renew_no',
    'Policy Effective Date': 'policy_effective_date',
    'Commission Entity Name': 'commission_entity_name',
    'Commission Entity Type': 'commission_entity_type',
    'Commission Entity Code': 'commission_entity_code',
    'Commission Payee Entity Type': 'commission_payee_entity_type',
    'Commission Payee Entity Code': 'commission_payee_entity_code',
    'Commission Statement Entity Type': 'commission_statement_entity_type',
    'Commission Statement Entity Code': 'commission_statement_entity_code',
    'Operating Company Code': 'operating_company_code',
    'Operating Company': 'operating_company',
    'Underwriting Company Code': 'underwriting_company_code',
    'Underwriting Company': 'underwriting_company',
    'Bill Type': 'bill_type',
    'Commission Basis': 'commission_basis',
    'Receivable Code': 'receivable_code',
    'Receivable Category': 'receivable_category',
    'Premium Amount': 'premium_amount',
    'Commission Percentage': 'commission_percentage',
    'Total Commission to be Paid': 'total_commission_to_be_paid',
    'Commission Adjustment': 'commission_adjustment',
    'Commission Paid': 'commission_paid',
    'Commission Balance Payable': 'commission_balance_payable',
    'Begining Balance': 'begining_balance',
    'Ending Balance': 'ending_balance',
    'Month': 'month',
}

# ------------------------------ 9 ------------------------------
# Mapping for stage_majesco_premium_activity_report
stage_majesco_premium_activity_report = {
    'Operating Company Code': 'operating_company_code',
    'Operating Company': 'operating_company',
    'Underwriting Company Code': 'underwriting_company_code',
    'Underwriting Company': 'underwriting_company',
    'Agency Code': 'agency_code',
    'Agency Name': 'agency_name',
    'Producer Code': 'producer_code',
    'Producer Name': 'producer_name',
    'Account Code': 'account_code',
    'Policy No': 'policy_no',
    'Policy Term ID': 'policy_term_id',
    'Policy Effective Date': 'policy_effective_date',
    'Insured Name': 'insured_name',
    'Operating Region Code': 'operating_region_code',
    'Operating Region': 'operating_region',
    'CRT Code': 'crt_code',
    'CRT': 'crt',
    'Transaction Type': 'transaction_type',
    'Receivable Code': 'receivable_code',
    'Receivable Type': 'receivable_type',
    'Receivable Category': 'receivable_category',
    'Transaction Amount': 'transaction_amount',
    'Commission Amount': 'commission_amount',
    'Deferred Premium': 'deferred_premium',
    'Deferred Commission': 'deferred_commission',
    'Transaction Process Date': 'transaction_process_date',
    'Entry Date': 'entry_date',
    'Transaction Month': 'transaction_month',
    'Bill Type': 'bill_type',
    'Bill Type Description': 'bill_type_description',
    'Transaction No': 'transaction_no',
    'State': 'state',
    'Product': 'product',
    'Payment Plan': 'payment_plan',
    'Policy Renew No': 'policy_renew_no',
    'Source System': 'source_system',
    'Line of Business': 'line_of_business',
    'Transaction Description': 'transaction_description',
    'Start Date': 'start_date',
    'End Date': 'end_date',
}

def get_mapping(table_name):
    """
    Returns the mapping dictionary for the given table name.
    """
    mappings = {
        'stage_majesco_adjust_writeoff': stage_majesco_adjust_writeoff,
        'stage_majesco_agency_level_monthly_commission_balance': stage_majesco_agency_level_monthly_commission_balance,
        'stage_majesco_billing_fee': stage_majesco_billing_fee,
        'stage_majesco_cash_activity': stage_majesco_cash_activity,
        'stage_majesco_commission_disbursement_register': stage_majesco_commission_disbursement_register,
        'stage_majesco_disbursement_register': stage_majesco_disbursement_register,
        'stage_majesco_due_date_aging': stage_majesco_due_date_aging,
        'stage_majesco_policy_level_monthly_commission_balance': stage_majesco_policy_level_monthly_commission_balance,
        'stage_majesco_premium_activity_report': stage_majesco_premium_activity_report,
    }
    
    return mappings.get(table_name, {})