CREATE TABLE edw_core.tauto_vehicle
(
auto_vehicle_sk            int NOT NULL IDENTITY(1,1),
policy_no                  varchar(255),
effective_dt               date,
vehicle_no                 int,
vehicle_type varchar(255),
collector_car_type varchar(255),
vehicle_vin varchar(255),
vehicle_model_year int,
vehicle_make varchar(255),
vehicle_model varchar(255),
vehicle_body varchar(255),
vehicle_weight varchar(255),
vehicle_horsepower float,
vehicle_engine_size float,
vehicle_engine_type varchar(255),
high_performance_vehicle_in varchar(255),
purchase_dt date,
source_system_sk           int,
create_ts                  datetime,
update_ts                  datetime,
etl_audit_sk               int,
CONSTRAINT pk_tauto_vehicle PRIMARY KEY (auto_vehicle_sk),
CONSTRAINT uidx_tauto_vehicle_policyno_effective_dt_vehicleno UNIQUE (policy_no,effective_dt,vehicle_no)
);

INSERT INTO edw_core.tedw_table_detail(table_nm,table_type,table_category_nm,domain_nm,load_method,load_type,load_frequency,create_ts,update_ts) 
    VALUES ('tauto_vehicle','Type-1 Dimension','Base','Auto','Stored Procedure','Insert/Update','Daily',getdate(),getdate());


CREATE TABLE edw_core.tauto_garage_location
(
	auto_garage_location_sk   int IDENTITY(1,1) NOT NULL,
	policy_no varchar(255) NOT NULL ,
	effective_dt date NOT NULL ,
    transaction_effective_dt date NOT NULL ,
    expiration_dt date NOT NULL ,
    transaction_dt date NOT NULL ,
    transaction_seq_no int NOT NULL ,
    policy_history_sk int NOT NULL ,
    garage_location_no int NOT NULL,
    garage_address_line1 varchar(255),
    garage_address_line2 varchar(255),
    garage_address_unit_no varchar(255),
    garage_address_city_nm varchar(255),
    garage_address_zip_code varchar(255),
    garage_address_state_cd  varchar(255),
    garage_address_county_nm varchar(255),
    garage_address_country_nm varchar(255),
    census_tract varchar(255),
    flood_zone varchar(255),
    wildfire_threat varchar(255),
    protection_class varchar(255),
    distance_to_coast varchar(255),
    central_reporting_fire_alarm_in varchar(255),
    central_reporting_burglar_alarm_in varchar(255),
    source_system_sk           int,
    create_ts                  datetime,
    update_ts                  datetime,
    etl_audit_sk               int,
CONSTRAINT pk_tauto_garage_location PRIMARY KEY (auto_garage_location_sk),
CONSTRAINT uidx_tagl_polno_effdt_locno_transeq UNIQUE (policy_no,effective_dt,garage_location_no,transaction_seq_no),
CONSTRAINT fk_tauto_garage_location_policy_history_sk FOREIGN KEY (policy_history_sk) REFERENCES  edw_core.tpolicy_history(policy_history_sk)
);

INSERT INTO edw_core.tedw_table_detail(table_nm,table_type,table_category_nm,domain_nm,load_method,load_type,load_frequency,create_ts,update_ts) 
    VALUES ('tauto_garage_location','Type-2 Dimension','Base','Auto','Stored Procedure','Insert','Daily',getdate(),getdate());

CREATE TABLE edw_core.tauto_vehicle_coverage
(
auto_vehicle_coverage_sk    int IDENTITY(1,1) NOT NULL,
    policy_no varchar(255) NOT NULL ,
	effective_dt date NOT NULL ,
    vehicle_no  int NOT NULL,
    transaction_effective_dt date NOT NULL ,
    expiration_dt date NOT NULL ,
    transaction_dt date NOT NULL ,
    transaction_seq_no int NOT NULL ,
    policy_history_sk int NOT NULL ,
    auto_vehicle_sk int NOT NULL ,
    auto_garage_location_sk int NOT NULL,
primary_parking_location varchar(255),
driveway_security varchar(255),
vehicle_usage varchar(255),
distance_to_work varchar(255),
annual_miles int,
lpmp_filing_dt varchar(255),
vehicle_ownership varchar(255),
registration_status varchar(255),
registration_dt date,
registration_expiration_dt date,
registered_owner_type varchar(255),
registered_owner_nm varchar(255),
listed_driver_nm varchar(255),
non_driver_nm varchar(255),
company_other_entity_nm varchar(255),
registration_state_cd varchar(255),
registration_address_line1 varchar(255),
registration_address_line2 varchar(255),
registration_address_unit_no varchar(255),
registration_address_city_nm varchar(255),
registration_address_zip_cd varchar(255),
registration_address_state_nm varchar(255),
symbol_bi_pd varchar(255),
symbol_pip_med varchar(255),
symbol_otc varchar(255),
symbol_coll varchar(255),
symbol_cost_new_amt int,
motorcycle_cost_new_amt int,
symbol_cost_new_iso varchar(255),
symbol_coll_iso varchar(255),
symbol_otc_iso varchar(255),
symbol_bi_pd_iso varchar(255),
symbol_pip_med_iso varchar(255),
otc_deductible varchar(255),
collision_deductible  varchar(255),
full_glass_coverage_in  varchar(255),
collision_type  varchar(255),
fire_coverage_in  varchar(255),
theft_coverage_in  varchar(255),
umpd_coverage_in  varchar(255),
umpd_limit_amt  varchar(255),
umpd_deductible  varchar(255),
agreed_value_amt int,
market_value_amt int,
customized_equipment_value_amt int,
extended_towing_and_labor_in varchar(255),
motorcycle_med_limit_amt varchar(255),
rating_territory_cd varchar(255),
owned_vehicle_discount_in varchar(255),
high_performance_vehicle_rating varchar(255),
bodily_injury_expense_load int,
property_damage_expense_load int,
pip_expense_load int,
medical_expense_load int,
otc_expense_load int,
collision_expense_load int,
uninsured_motorist_expense_load int,
bodily_injury_ncrb_premium_amt int,
property_damage_ncrb_premium_amt int,
medical_payments_ncrb_premium_amt int,
uninsured_motorist_bodily_injury_ncrb_premium_amt int,
uninsured_motorist_property_damage_ncrb_premium_amt int,
send_vehicle_to_liability_reporting_in varchar(255),
antitheft_device_feature varchar(255),
antilock_brake_in varchar(255),
passive_restraint_in varchar(255),
seasonal_use_in varchar(255),
direct_repair_in varchar(255),
car_storage_facility_in varchar(255),
vin_etching_in varchar(255),
loss_protection_discount_in varchar(255),
seasonal_use_part2_in varchar(255),
market_appreciation_diminution_of_value_in varchar(255),
source_system_sk           int,
create_ts                  datetime,
update_ts                  datetime,
etl_audit_sk               int,
PRIMARY KEY (auto_vehicle_coverage_sk),
CONSTRAINT uidx_tauto_vehicle_coverage_polno_effdt_vehno_transeq UNIQUE (policy_no,effective_dt,vehicle_no,transaction_seq_no),
CONSTRAINT fk_tauto_vehicle_coverage_auto_vehicle_sk FOREIGN KEY (auto_vehicle_sk) REFERENCES  edw_core.tauto_vehicle(auto_vehicle_sk),
CONSTRAINT fk_tauto_vehicle_coverage_policy_history_sk FOREIGN KEY (policy_history_sk) REFERENCES  edw_core.tpolicy_history(policy_history_sk)
);

INSERT INTO edw_core.tedw_table_detail(table_nm,table_type,table_category_nm,domain_nm,load_method,load_type,load_frequency,create_ts,update_ts) 
    VALUES ('tauto_vehicle_coverage','Type-2 Dimension','Base','Auto','Stored Procedure','Insert','Daily',getdate(),getdate());

-- tauto_policy_coverage
   
CREATE TABLE edw_core.tauto_policy_coverage (
	auto_policy_coverage_sk int IDENTITY(1,1) NOT NULL,
	policy_no varchar(255) NOT NULL ,
	effective_dt date NOT NULL ,
	transaction_effective_dt date NOT NULL ,
	expiration_dt date NOT NULL ,
	transaction_dt date NOT NULL ,
	transaction_seq_no int NOT NULL ,
	policy_history_sk int NOT NULL ,
    limit_type varchar(255),
	combined_single_limit_amt varchar(255),
	bodily_injury_limit_amt varchar(255),
	property_damage_limit_amt varchar(255),
	limited_property_damage varchar(255),
	uninsured_underinsured_motorist_type varchar(255),
	uninsured_motorist_limit_amt varchar(255),
	underinsured_motorist_limit_amt varchar(255),
	combined_uninsured_motorist_limit_amt varchar(255),
	combined_underinsured_motorist_limit_amt varchar(255),
	um_bi_policy_limit_amt varchar(255),
	um_pd_policy_limit_amt varchar(255),
	combined_um_bi_policy_limit_amt varchar(255),
	combined_um_pd_policy_limit_amt varchar(255),
	pip_limit_amt varchar(255),
	pip_deductible varchar(255),
	medical_payment_limit_amt varchar(255),
	property_protection varchar(255),
	stacked_or_nonstacked varchar(255),
	uninsured_motorist_added_reduced varchar(255),
	uninsured_motorist_deductible varchar(255),
	economic_loss_uninsured_motorist_in varchar(255),
	automobile_death_indemnity_and_disability_income varchar(255),
	cede_to_ncrf varchar(255),
	basic_pip varchar(255),
	basic_or_extended_pip varchar(255),
	additional_pip varchar(255),
	pip_medical_options varchar(255),
	extended_medical_limit_amt varchar(255),
	tort varchar(255),
	deletion_of_benefits_in varchar(255),
	basic_or_added_first_party_benefit varchar(255),
	individual_or_combination_fpb varchar(255),
	added_first_party_limit_amt varchar(255),
	accidental_death_benefit_limit_amt varchar(255),
	work_loss_benefit_limit_amt varchar(255),
	funeral_expense_benefit_limit_amt varchar(255),
	combination_fpb_limit_amt varchar(255),
	extraordinary_medical_benefits_limit_amt varchar(255),
	coordination_of_medical_benefits_in varchar(255),
	work_loss_rejection_in  varchar(255),
	coordination_of_work_loss_benefits_in  varchar(255),
	excess_attendant_care_in varchar(255),
	health_insurance_primary_in varchar(255),
	deductible_applies_to varchar(255),
	work_loss_exclusion varchar(255),
	income_loss_benefit_in  varchar(255),
	named_non_owner_in varchar(255),
	extended_non_owned_in varchar(255),
	primary_insurance_elsewhere_in varchar(255),
	extend_to varchar(255),
	named_individual varchar(255),
	auto_complete_coverage_in varchar(255),
	emergency_movement_coverage_in varchar(255),
	physical_damage_deductible_adjustment varchar(255),
	multiple_policy_deductible_enhancement_endorsement_in varchar(255),
	transportation_and_temporary_emergency_living_expense_in varchar(255),
	stated_value_enhancement_endorsement_in varchar(255),
	original_equipment_manufacturer_enhancement_endorsement_in varchar(255),
	full_glass_coverage_enhancement_endorsement_in varchar(255),
	waiver_of_collision_enhancement_endorsement_in varchar(255),
	petInjury_enhancement_endorsement_in varchar(255),
	auto_lock_coverage_enhancement_endorsement_in varchar(255),
	spare_parts_enhancement_endorsement_in varchar(255),
	coverage_for_accidental_deploy_airbag_enhancement_endorsement_in varchar(255),
	-- Additional fields
	one_year_policy_in varchar(255),
	tier int,
	total_vehicles_on_policy_ct int, 
	total_ppas_ct int,
	total_owned_ppas_ct int,
	ppa_with_physical_damage_ct int,
	collector_cars_ct int,
	total_insured_locations_ct varchar(255),
	ho_claims_ct int,
	drivers_on_policy_ct int,
	youths_on_policy_ct varchar(255),
	years_clean_discount varchar(255),
	youthful_on_policy_in varchar(255),
	prior_carrier_naf_points varchar(255),
	prior_carrier_minor_accidents_ct varchar(255),
	prior_carrier_minor_accidents_points varchar(255),
	sdip_points varchar(255),
	comp_claims_ct varchar(255),
	nc_violations_ct varchar(255),
	nc_accidents_ct varchar(255),
	motorcycles_ct varchar(255),
	other_misc_vehicles_ct varchar(255),
	multi_bike_discount_in varchar(255),
	multi_car_discount_in varchar(255),
    source_system_sk int ,
	create_ts datetime ,
	update_ts datetime ,
	etl_audit_sk int ,
	CONSTRAINT pk_tauto_policy_coverage PRIMARY KEY (auto_policy_coverage_sk),
    CONSTRAINT uidx_tauto_policy_coverage_polno_effdt_transeq UNIQUE (policy_no,effective_dt,transaction_seq_no),
    CONSTRAINT fk_tauto_policy_coverage_policy_history_sk FOREIGN KEY (policy_history_sk) REFERENCES  edw_core.tpolicy_history(policy_history_sk)
);

INSERT INTO edw_core.tedw_table_detail(table_nm,table_type,table_category_nm,domain_nm,load_method,load_type,load_frequency,create_ts,update_ts) 
    VALUES ('tauto_policy_coverage','Type-2 Dimension','Base','Auto','Stored Procedure','Insert','Daily',getdate(),getdate());
    

-- tauto_driver
   
CREATE TABLE edw_core.tauto_driver 
(
    auto_driver_sk int IDENTITY(1,1) NOT NULL,
    policy_no varchar(255) NOT NULL,
    effective_dt date  NOT NULL,
    transaction_effective_dt date NOT NULL,
    expiration_dt date NOT NULL,
    transaction_dt date NOT NULL ,
    transaction_seq_no int NOT NULL,
    driver_no int NOT NULL,
    policy_history_sk int NOT NULL,
    prefix varchar(255),
    first_nm varchar(255),
    middle_nm varchar(255),
    last_nm varchar(255),
    suffix varchar(255),
    birth_dt date,
    gender varchar(255),
    marital_status varchar(255),
    relationship_to_insured varchar(255),
    driver_status varchar(255),
    sr22_certification_required_in varchar(255),
    sr22_certification_state_cd varchar(255),
    -- primary_vehicle_id int, -- Check what it corresponds to in vehicle table
    defensive_driver_in varchar(255),
    training_discount_in varchar(255),
    license_status varchar(255),
    license_country_nm varchar(255),
    license_state_nm varchar(255),
    license_no varchar(255),
    license_year int, 
    licensed_received_age varchar(255),
    no_of_years_licensed varchar(255),
    unverifiable_driving_record_in varchar(255),
    multiple_incident_factor float,
    defensive_course_completed_in varchar(255),
    defensive_course_completed_two_years_in varchar(255),
    defensive_course_completed_three_years_in varchar(255),
    defensive_course_completion_dt date,
    training_course_completed_in varchar(255),
    good_student_in  varchar(255),
    away_at_school_in  varchar(255),
    military_personnel_discount_in varchar(255),
    army_national_guard_personnel_discount_in varchar(255),
    mobile_device_control_discount_in varchar(255),
    seasonal_use_part_in varchar(255),
    occasional_operator_discount varchar(255),
    reported_incidents_ct int, 
    sdip_points_no      varchar(255),  
    aaf_with_vault_ct   varchar(255),
    afb_with_vault_ct varchar(255),
    naf_with_vault_ct varchar(255),
    cpa_with_vault_ct varchar(255),
    min_with_vault_ct varchar(255),
    maj_with_vault_ct varchar(255),
    spd_with_vault_ct varchar(255),
    aaf_prior_ct varchar(255),
    afb_prior_ct varchar(255),
    naf_prior_ct varchar(255),
    cpa_prior_ct varchar(255),
    min_prior_ct varchar(255),
    maj_prior_ct varchar(255),
    spd_prior_ct varchar(255),
    source_system_sk int ,
    create_ts datetime ,
    update_ts datetime ,
    etl_audit_sk int ,
    CONSTRAINT pk_tauto_driver PRIMARY KEY (auto_driver_sk),
    CONSTRAINT uidx_tauto_driver_polno_effdt_drvno_transeq UNIQUE (policy_no,effective_dt,driver_no,transaction_seq_no),
    CONSTRAINT fk_tauto_driver_policy_history_sk FOREIGN KEY (policy_history_sk) REFERENCES  edw_core.tpolicy_history(policy_history_sk)
);

INSERT INTO edw_core.tedw_table_detail(table_nm,table_type,table_category_nm,domain_nm,load_method,load_type,load_frequency,create_ts,update_ts) 
    VALUES ('tauto_driver','Type-2 Dimension','Base','Auto','Stored Procedure','Insert','Daily',getdate(),getdate());
    

-- tauto_driver_incident
   
CREATE TABLE edw_core.tauto_driver_incident
(
    auto_driver_incident_sk int IDENTITY(1,1) NOT NULL,
    policy_no varchar(255) NOT NULL,
    effective_dt date  NOT NULL,
    transaction_effective_dt date NOT NULL,
    expiration_dt date NOT NULL,
    transaction_dt date NOT NULL ,
    transaction_seq_no int NOT NULL,
    policy_history_sk int NOT NULL,
    auto_driver_sk int NOT NULL,
    driver_no int NOT NULL,
    incident_no  int NOT NULL,
    incident_source varchar(255) ,
    incident_dt date,
    incident_type varchar(255) ,
    incident_description varchar(255) ,
    total_payout_amt decimal(15,2),
    is_disputed_in varchar(255) ,
    include_in_rate_in varchar(255) ,
    violation_point_class varchar(255) , -- maps to IncidentCode
    incident_status varchar(255) ,
    bodily_injury_payment decimal(15,2),
    collision_payment decimal(15,2),
    comprehensive_payment decimal(15,2),
    glass_payment decimal(15,2),
    medical_expense_payment decimal(15,2),
    medical_payment decimal(15,2),
    other_payment decimal(15,2),
    property_damage_payment decimal(15,2),
    personal_injury_protection_payment decimal(15,2),
    rental_reimbursement_payment decimal(15,2),
    spousal_liability_payment decimal(15,2),
    towing_and_labor_payment decimal(15,2),
    uninsured_motorist_payment decimal(15,2),
    underinsured_motorist_payment decimal(15,2),
    source_system_sk int ,
    create_ts datetime ,
    update_ts datetime ,
    etl_audit_sk int ,
    CONSTRAINT pk_tauto_driver_incident PRIMARY KEY (auto_driver_incident_sk),
    CONSTRAINT uidx_tauto_driver_incident_polno_effdt_drvno_incno_transeq UNIQUE (policy_no,effective_dt,driver_no,incident_no,transaction_seq_no),
    CONSTRAINT fk_tauto_driver_incident_policy_history_sk FOREIGN KEY (policy_history_sk) REFERENCES  edw_core.tpolicy_history(policy_history_sk)
);

INSERT INTO edw_core.tedw_table_detail(table_nm,table_type,table_category_nm,domain_nm,load_method,load_type,load_frequency,create_ts,update_ts) 
    VALUES ('tauto_driver_incident','Type-2 Dimension','Base','Auto','Stored Procedure','Insert','Daily',getdate(),getdate());