-- Home Tables


CREATE TABLE edw_core.thome_location 
(
home_location_sk           int NOT NULL IDENTITY(1,1),
policy_no                  varchar(255),
effective_dt               date,
address_line_1             varchar(255),
address_line_2             varchar(255),
unit_no				       varchar(255),
city_nm                    varchar(255),
state_cd                   varchar(255),
zip_cd                     varchar(255),
county_nm                  varchar(255), 
country_nm                 varchar(255), 
longitude                  varchar(255), 
latitude                   varchar(255), 
source_system_sk           int,
create_ts                  datetime,
update_ts                  datetime,
etl_audit_sk               int,
CONSTRAINT pk_thome_location PRIMARY KEY (home_location_sk),
CONSTRAINT uidx_thome_location_policy_no_effective_dt UNIQUE (policy_no,effective_dt)
);


INSERT INTO edw_core.tedw_table_detail(table_nm,table_type,table_category_nm,domain_nm,load_method,load_type,load_frequency,create_ts,update_ts) 
    VALUES ('thome_location','Type-1 Dimension','Base','Home','Stored Procedure','Insert/Update','Daily',getdate(),getdate());
    
   
CREATE TABLE edw_core.thome_coverage
(
home_coverage_sk           int NOT NULL IDENTITY(1,1),
policy_no                  varchar(255),
effective_dt               date,
transaction_effective_dt   date,
expiration_dt              date,
transaction_dt             date,
transaction_seq_no         int,
home_location_sk           int,
policy_history_sk          int,
residence_type                                 varchar(255),
dwelling_limit_amt                             int,
other_structures_limit_amt                     int,
contents_limit_amt                             int,
loss_of_use_limit_amt                          varchar(255),
loss_of_use_option                             varchar(255),
loss_of_use_pc                                 float,
personal_liability_limit_amt                   varchar(255),
medical_payments_limit_amt                     int,
total_insured_value_amt 					   int,
exclude_inflation_factor_in   varchar(255),
aop_deductible             varchar(255),
water_deductible           varchar(255),
hurricane_deductible       varchar(255),
hurricane_or_named_storm_deductible  varchar(255),
named_storm_deductible     varchar(255),  
tornado_or_hailstorm_deductible varchar(255),
wind_or_hailstorm_deductible varchar(255),
wind_derived_deductible            varchar(255),
wildfire_deductible        varchar(255),
no_of_mortgagees           int,
prior_claim_last5yr_in     varchar(255),
prior_nonwater_claim_ct    int,
prior_water_claim_ct       int,
rating_territory_cd       varchar(255),
distance_to_coast          varchar(255),
distance_to_shore          varchar(255),
within_500feet_from_shore_in  varchar(255),
distance_to_fire_hydrant_feet   varchar(255),
distance_to_fire_station_miles  float,
fire_protection            varchar(255),
occupancy_type             varchar(255),
protection_class           varchar(255),
earthquake_zone            varchar(255),
terrain_cd                 varchar(255),
windborne_debris_region_in    varchar(255),
windpool_eligibility_in       varchar(255),
sinkhole_risk_level          		  varchar(255),
sinkhole_distance_to_nearest_miles     float,
total_finished_square_feet int,
construction_type          varchar(255),
basement_type              varchar(255),
active_renovation                     varchar(255),
renovation_anticipated_completion_dt  date,
ulstandard                 varchar(255),
unit_floor                 varchar(255),
built_year                 int,
electrical_updated_year    int,
hvac_updated_year          int,
plumbing_updated_year      int,
roof_updated_year          int,
no_of_stories              varchar(255),
shear_wave_velocity        int,
barn_on_property_in           varchar(255),
barn_value_amt                 int,     
bceg_cd   		           varchar(255),
bceg_credit_pc               float,
windspeed_of_design           varchar(255),
hail_resistant_rating_in      varchar(255),
hurricane_fortification_in    varchar(255),
mmi              		   int,
swimming_pool_in           varchar(255),
wildfire_score                   varchar(255),
hazard_severity          		 varchar(255),
distance_to_very_high_fuel_feet  varchar(255),
distance_to_high_fuel_feet       varchar(255),
distance_to_moderate_fuel_feet   varchar(255),
no_of_wildfire_occurrences       varchar(255),
no_of_wildfire_near_occurrences  varchar(255),
nearest_distance_to_perimeter    varchar(255),
combustible_wood_siding_in        varchar(255),
combustible_deck_or_attached_structure_in          					   varchar(255),
firewood_or_combustibles_stored_against_home_in          				varchar(255),
defensible_space_in          		varchar(255),
woodshake_or_shingle_roof_in      varchar(255),
speciality_ember_resistant_venting_in          						varchar(255),
exterior_wildfire_sprinklers_in   varchar(255),
eaves_or_enclosed_eaves_in        varchar(255),
permanently_installed_spray_system_in          						varchar(255),
portable_fire_break_system_in     varchar(255),
gutter_guards_in          		varchar(255),
bark_mulch_within_ten_feet_of_any_structure_in          				varchar(255),
flammable_vegetation_within_ten_feet_of_any_structure_in          	varchar(255),
opening_protection         varchar(255),
roof_cover_deck            varchar(255),
roof_covering              varchar(255),
roof_deck_attachment       varchar(255),
roof_geometry              varchar(255),
roof_system_in             varchar(255),
roof_wall_attachment       varchar(255),
solar_feature_desc         varchar(255),
secondary_water_resistance  varchar(255),
source_system_sk           int,
create_ts                  datetime,
update_ts                  datetime,
etl_audit_sk               int,
CONSTRAINT pk_thome_coverage PRIMARY KEY (home_coverage_sk),
CONSTRAINT uidx_thome_coverage_polno_effdt_transeq UNIQUE (policy_no,effective_dt,transaction_seq_no),
CONSTRAINT fk_thome_coverage_location_sk FOREIGN KEY (home_location_sk) REFERENCES  edw_core.thome_location(home_location_sk)
);

INSERT INTO edw_core.tedw_table_detail(table_nm,table_type,table_category_nm,domain_nm,load_method,load_type,load_frequency,create_ts,update_ts) 
    VALUES ('thome_coverage','Type-2 Dimension','Base','Home','Stored Procedure','Insert','Daily',getdate(),getdate());

   
 
CREATE TABLE edw_core.thome_additional_coverage
(
home_additional_coverage_sk            int NOT NULL IDENTITY(1,1),
policy_no                  varchar(255),
effective_dt               date,
transaction_effective_dt   date,
expiration_dt              date,
transaction_dt             date,
transaction_seq_no         int,
home_location_sk           int,
home_coverage_sk           int,
policy_history_sk          int,
central_reporting_fire_alarm_in          	varchar(255),
central_reporting_burglar_alarm_in         varchar(255),
twentyfour_hour_doorman_in          					varchar(255),
lobby_surveillance_camera_in          		varchar(255),
locked_or_manned_elevators_in          	varchar(255),
twentyfour_hour_signal_continuity_in          				varchar(255),
guard_gated_community_in          			varchar(255),
guard_community_patrol_service_in          varchar(255),
home_safe_in          						varchar(255),
fulltime_live_in_caretaker_in          	varchar(255),
gas_leak_detector_in          				varchar(255),
lightning_protection_in          			varchar(255),
low_temperature_monitoring_device_in       varchar(255),
backup_generator_in          				varchar(255),
external_perimeter_gate_in          		varchar(255),
external_perimeter_security          	varchar(255),
water_leak_detection_system          	varchar(255),
residential_sprinkler_system_in          	varchar(255),
business_property_increase_in           varchar(255),
business_property_increase_limit_amt        int,
deductible_waiver_large_losses_in       varchar(255),
deductible_waiver_large_losses_limit_amt    int,
earthquake_coverage_extension_in        varchar(255),
earthquake_coverage_extension_deductible                varchar(255),
earthquake_coverage_extension_loss_assessment_in        varchar(255),
earthquake_coverage_extension_loss_assessment_limit_amt     int,
earthquake_earthmovement_exclusion_ind                      varchar(255),
--earthquake_damage_limt_amt                                varchar(255), 
earthquake_score			                                varchar(255), 
--earthquake_shake                                          varchar(255), 
fungi_bacteria_increase_in                  varchar(255),
fungi_bacteria_increase_limit              float,
fungi_bacteria_liability_extension_in      varchar(255),
home_systems_protection_in                  varchar(255),
home_systems_protection_limit_amt           int,
increased_incidental_business_threshold_in varchar(255),
increased_incidental_business_threshold_limit_amt                              int,
increased_incidental_business_property_in varchar(255),
increased_incidental_business_property_limit_amt                              varchar(255),
landscaping_coverage_increased_limits_in                                    varchar(255),
landscaping_coverage_increased_plant_limit_amt                                  int,
landscaping_coverage_increased_aggregate_limit                                  float, 
landscaping_coverage_sleet_and_weight_of_ice_and_snow_coverage_limit_amt              int,
landscaping_coverage_wind_and_hail_coverage_limit_amt                                 int,
law_ordinance_coverage_increase_in         varchar(255),
law_ordinance_coverage_increased_limit  varchar(255),
loss_assessment_increase_in                 varchar(255),
loss_assessment_increase_limit_amt          int,
loss_assessment_increase_desc                 varchar(255),
serviceline_protection_in               varchar(255),
thoroughbred_horse_liability_extension_in                              varchar(255),
no_of_horses                            varchar(255),
home_cyber_protection_coverage_in          varchar(255),
home_cyber_protection_coverage_deductible                                   varchar(255),
home_cyber_protection_coverage_limit_amt    int,
offpremises_other_permanent_structures_extension_in                             varchar(255),
offpremises_other_permanent_structures_extension_desc                nvarchar(max),
agreed_value_in                             varchar(255),
backup_of_sewers_limit_in                  varchar(255),
contents_extended_replacement_cost_in      varchar(255),
coverage_for_piers_wharves_and_docks_due_to_weight_of_ice_or_snow_in           varchar(255),
coverage_for_piers_wharves_and_docks_due_to_weight_of_ice_or_snow_limit_amt     int,
damage_to_property_of_others_increased_limit_amt                                int,
debris_removal_broadaned_tree_removal_in   varchar(255),
earthquake_endorsement_in               varchar(255),
earthquake_endorsement_deductible       varchar(255),
escaped_liquid_fuel_liability_limit_amt  varchar(255),
escaped_liquid_fuel_remediation_coverage_in                                 varchar(255),
escaped_liquid_fuel_remediation_liability_limit_amt                          varchar(255),
escaped_liquid_fuel_remediation_risk_class_no                               varchar(255),
fortified_roof_upgrade_in               varchar(255),
home_daycare_coverage_in                varchar(255),
home_daycare_coverage_limit_amt                varchar(255),
home_daycare_coverage_no_of_children           varchar(255),
identity_theft_in                       varchar(255),
pollutants_or_contimination_extension_in   varchar(255),
pollutants_or_contimination_tankage     varchar(255),
pollutants_or_contimination_tank_construction                               varchar(255),
pollutants_or_contimination_tank_location                                   varchar(255),
pollutants_or_contimination_tank_type   varchar(255),
residence_held_in_trust_in                 varchar(255),
sinkhole_collapse_in                        varchar(255),
sinkhole_coverage_extension_in              varchar(255),
sinkhole_territory                          varchar(255),
supplemental_loss_assessment_coverage_in   varchar(255),
supplemental_loss_assessment_coverage_additional_locations                  varchar(255),
supplemental_loss_assessment_coverage_premises                              varchar(255),
workercompensation_liability_in             varchar(255),
workercompensation_liability_fulltime_employees_ct                             int,
workercompensation_liability_occurance_limit_amt                                int,
workercompensation_liability_parttime_employees_ct                             int,
-- Reconstruction/Replacement
guaranteed_replacement_cost_in              varchar(255),
replacement_cost_coverage_in                varchar(255),
roof_covering_full_reconstruction_cost_coverage_in                      varchar(255),
additional_replacement_cost_coverage_in    varchar(255),
additional_replacement_cost_coverage_with_wildfire_in                          varchar(255),
dwelling_reconstruction_cost_coverage_in   varchar(255),
extended_replacement_cost_coverage_with_additional_wildfire_in                 varchar(255),
extended_replacement_cost_coverage_with_wildfire_in                            varchar(255),
extended_replacement_cost_coverage_in      varchar(255),
extended_replacement_cost_coverage_option                                   varchar(255),
extended_replacement_cost_coverage_with_additional_wildfire_plus_twentyfive_pc_in                 varchar(255),
mine_subsidence_coverage_in                 varchar(255),
mine_subsidence_coverage_limit_amt          int,
minimum_earned_premium_endorsement_in      varchar(255),
minimum_earned_premium_endorsement_limit_pct                                    float,
-- Coverage Limitations
contents_off_premises_loss_exclusion_in    varchar(255),
premises_liability_limitation_in            varchar(255),
manuscript_in                           varchar(255),
-- Added
amended_settlement_basis_in                 varchar(255),
additions_and_alterations_extended_replacement_cost_in                      varchar(255),
change_in_terms_summary_in                 varchar(255),
deletion_of_cosmetic_marring_exclusion_in  varchar(255),
exclude_wind_in                             varchar(255),
wind_hail_exclusion_in                     varchar(255),
roof_exclusion_in                       varchar(255),
waterdamage_exclusion_in                    varchar(255),
waterdamage_limitation_endorsement_in      varchar(255),
waterdamage_limitation_endorsement_limit_amt                                    int,
waterdamage_sublimit                    varchar(255),
waterdamage_sublimit_amt             int,
underground_resources_exclusion_in         varchar(255),
underground_water_supplyline_exclusion_in         varchar(255),
-- Liability Exclusion
named_structures_exclusion_in           varchar(255),
named_structures_exclusion_desc         nvarchar(max),
animal_related_liability_exclusion_in      varchar(255),
animal_related_liability_exclusion_desc      nvarchar(max),
libel_slander_exclusion_in                  varchar(255),
political_activities_exclusion_in          varchar(255),
equine_related_liability_exclusion_in      varchar(255),
canine_liability_exclusion_in           varchar(255),
named_structures_property_and_liability_exclusion_in                          varchar(255),
named_structures_property_and_liability_exclusion_desc                        nvarchar(max),
specific_named_structures_property_and_liability_exclusion_in                 varchar(255),
specific_named_structures_property_and_liability_exclusion_desc               nvarchar(max),
other_structures_away_from_the_residence_premises_in                          varchar(255),
other_structures_away_from_the_residence_premises_desc               nvarchar(max),
other_structures_on_the_residence_premises_increased_limit_in               varchar(255),
other_structures_on_the_residence_premises_increased_limit_amt           int,
other_structures_on_the_residence_premises_increased_limit_desc      nvarchar(max),
extended_liability_in                      varchar(255),
source_system_sk           int,
create_ts                  datetime,
update_ts                  datetime,
etl_audit_sk               int,
CONSTRAINT pk_thome_additional_coverage PRIMARY KEY (home_additional_coverage_sk),
CONSTRAINT uidx_thome_additional_coverage_polno_effdt_transeq UNIQUE (policy_no,effective_dt,transaction_seq_no),
CONSTRAINT fk_thome_additional_coverage_location_sk FOREIGN KEY (home_location_sk) REFERENCES  edw_core.thome_location(home_location_sk),
CONSTRAINT fk_thome_additional_coverage_coverage_sk FOREIGN KEY (home_coverage_sk) REFERENCES  edw_core.thome_coverage(home_coverage_sk)
);

INSERT INTO edw_core.tedw_table_detail(table_nm,table_type,table_category_nm,domain_nm,load_method,load_type,load_frequency,create_ts,update_ts) 
    VALUES ('thome_additional_coverage','Type-2 Dimension','Base','Home','Stored Procedure','Insert','Daily',getdate(),getdate());

CREATE TABLE edw_core.tmortgagee
(
mortgage_sk                int NOT NULL IDENTITY(1,1),
policy_no                  varchar(255),
effective_dt               date,
transaction_effective_dt   date,
expiration_dt              date,
transaction_dt             date,
transaction_seq_no         int,
policy_history_sk          int,
mortgagee_no               int,
mortgagee_nm	           varchar(255),         
mortgagee_type	           varchar(255),
bill_mortgagee_in          varchar(255),
email	      			   varchar(255),
fax_no                     varchar(255),
phone_no                   varchar(255),
isao_atima	               varchar(255),
isao_atima_other		   varchar(255),
loan_no                    varchar(255),
address_line_1	           varchar(255),
address_line_2	           varchar(255),
unit_no                    varchar(255), 
city_nm	                   varchar(255),
state_cd               	   varchar(255),
zip_cd                     varchar(255),
county_nm             	   varchar(255),
country_nm             	   varchar(255),
source_system_sk           int,
create_ts                  datetime,
update_ts                  datetime,
etl_audit_sk               int,
CONSTRAINT pk_tmortgagee PRIMARY KEY (mortgage_sk)
);

INSERT INTO edw_core.tedw_table_detail(table_nm,table_type,table_category_nm,domain_nm,load_method,load_type,load_frequency,create_ts,update_ts) 
    VALUES ('tmortgagee','Type-2 Dimension','Base','Policy','Stored Procedure','Insert','Daily',getdate(),getdate());
   


