-- aws_us_prod_address.t_pub_address definition

CREATE TABLE edw_stage.t_pub_address (
  ADDRESS_ID decimal(19,0) NOT NULL,
  ADDRESS_TYPE decimal(3,0) DEFAULT NULL,
  ADDRESS_STATUS decimal(3,0) DEFAULT NULL,
  IS_PRIMARY_ADDRESS char(1) ,
  COUNTRY varchar(100) ,
  ADDRESS_LINE_1 varchar(500) ,
  ADDRESS_LINE_2 varchar(500) ,
  ADDRESS_LINE_3 varchar(500) ,
  CITY varchar(100) ,
  DISTRICT varchar(100) ,
  SUB_DISTRICT varchar(100) ,
  COUNTY varchar(100) ,
  STATE varchar(100) ,
  POST_CODE varchar(20) ,
  REFER_ID decimal(19,0) DEFAULT NULL,
  FULL_ADDRESS text ,
  INSERT_BY decimal(19,0) DEFAULT NULL,
  UPDATE_BY decimal(19,0) DEFAULT NULL,
  INSERT_TIME datetime DEFAULT NULL,
  UPDATE_TIME datetime DEFAULT NULL,
  BUSINESS_OBJECT_ID decimal(19,0) DEFAULT NULL,
  MAILING_NAME varchar(100) ,
  PRIMARY KEY (ADDRESS_ID)
) ;


-- aws_us_prod_diary.t_pub_diary definition

CREATE TABLE edw_stage.t_pub_diary (
  DIARY_ID decimal(19,0) NOT NULL,
  DIARY_TYPE varchar(255) ,
  REFER_ID decimal(19,0) DEFAULT NULL,
  REFER_NO char(100) ,
  ATTACH_TO varchar(100) ,
  ASSIGN_TO decimal(19,0) DEFAULT NULL,
  DUE_DATE datetime DEFAULT NULL,
  STATUS decimal(10,0) DEFAULT NULL,
  PRIORITY decimal(10,0) DEFAULT NULL,
  SEND_MESSAGE_TO decimal(19,0) DEFAULT NULL,
  DIARY_CONTENT text ,
  INSERT_BY decimal(19,0) NOT NULL,
  INSERT_TIME datetime DEFAULT NULL,
  UPDATE_BY decimal(19,0) NOT NULL,
  UPDATE_TIME datetime DEFAULT NULL,
  DIARY_TITLE text 
) ;


-- aws_us_prod_pub.t_pub_user definition

CREATE TABLE edw_stage.t_pub_user (
  USER_ID decimal(15,0) NOT NULL,
  ORG_ID decimal(15,0) NOT NULL,
  PASSWORD varchar(1000)  NOT NULL,
  REAL_NAME varchar(2700) ,
  CREATE_DATE datetime DEFAULT NULL,
  USER_NAME varchar(60) ,
  PASSWORD_CHANGE datetime DEFAULT NULL,
  NEED_CHANGE_PASS varchar(1) ,
  DEFAULT_LANG varchar(5)  NOT NULL,
  USER_DISABLE varchar(1) ,
  DISABLE_CAUSE varchar(1) ,
  INVALID_LOGIN decimal(15,0) DEFAULT NULL,
  LATEST_IP varchar(15) ,
  LATEST_IP_OLD varchar(15) ,
  LATEST_LOGIN_TIME datetime DEFAULT NULL,
  LATEST_LOGIN_OLD datetime DEFAULT NULL,
  LATEST_LOGOUT_TIME datetime DEFAULT NULL,
  LATEST_ACCESS_TIME datetime DEFAULT NULL,
  USER_TYPE decimal(5,0) NOT NULL,
  PARTY_ID decimal(15,0) DEFAULT NULL,
  PARTY_ROLE varchar(5) ,
  DEPT_ID decimal(15,0) DEFAULT NULL,
  EMAIL varchar(100) ,
  DISABLE_DATE datetime DEFAULT NULL,
  CUSTOMER_ID varchar(40) ,
  ID_CARD varchar(40) ,
  ACTIVATE_PASSWORD varchar(32) ,
  USER_ON_LEAVE varchar(1) ,
  DISABLE_CAUSE_DETAIL varchar(1024) ,
  INSERT_BY decimal(15,0) NOT NULL,
  UPDATE_BY decimal(15,0) NOT NULL,
  DYNAMIC_FIELDS varchar(4000) ,
  MOBILE varchar(40) ,
  ORGAN_ID decimal(15,0) DEFAULT NULL,
  DEFAULT_LANGUAGE varchar(5) ,
  CODE varchar(255) ,
  STATUS varchar(255) ,
  ON_LEAVE_FLAG varchar(1) ,
  REGISTER_CODE varchar(255) ,
  REGISTER_EXPIRE_DATE datetime DEFAULT NULL,
  INSERT_TIME datetime DEFAULT NULL,
  UPDATE_TIME datetime DEFAULT NULL,
  TITLE varchar(100) ,
  USER_NO varchar(20) ,
  POSITION decimal(5,0) DEFAULT NULL,
  BRANCH_ID decimal(15,0) DEFAULT NULL,
  COM_CODE varchar(100) ,
  MAKE_CODE varchar(100) ,
  EMPLOYEE_FLAG varchar(50) ,
  NEW_USER_CODE varchar(100) ,
  VALID_STATUS decimal(2,0) DEFAULT NULL,
  ARTICLE_CODE varchar(100) ,
  FLAG varchar(100) ,
  EXTRANET_SINGLE_FLAG decimal(2,0) DEFAULT NULL,
  AGENT_ACOUNT_FLAG decimal(2,0) DEFAULT NULL,
  VOCATION_CODE varchar(100) ,
  PARTIN_TIME datetime DEFAULT NULL,
  SALES_FLAG decimal(2,0) DEFAULT NULL,
  ORG_CODE varchar(20) ,
  ADDRESS varchar(255) ,
  TEL varchar(20) ,
  B2B_BELONG_TO_ORG_ID decimal(15,0) DEFAULT NULL,
  B2B_EXT_RBANCH_NO varchar(40) ,
  B2B_CONTRACT_ID decimal(15,0) DEFAULT NULL,
  B2B_PLAN_CODE varchar(20) ,
  B2B_AGREEMENT_NO varchar(1800) ,
  BUSINESS_OBJECT_ID decimal(15,0) DEFAULT NULL,
  B2B_PRODUCT_CODE varchar(20) ,
  USER_ROLE_CODE varchar(3) ,
  RECORD_USAGE decimal(1,0) DEFAULT NULL,
  SUPERVISOR decimal(15,0) DEFAULT NULL,
  IMAGE text ,
  PRIMARY KEY (USER_ID)
) ;


-- aws_us_prod_vault.t_clm_accident definition

CREATE TABLE edw_stage.t_clm_accident (
  ACCIDENT_CODE varchar(30)  NOT NULL,
  ACCIDENT_NAME varchar(200)  NOT NULL,
  ACCIDENT_DESC text ,
  START_DATE datetime DEFAULT NULL,
  EXPIRY_DATE datetime DEFAULT NULL,
  VALID_FLAG char(1) ,
  INSERT_BY decimal(19,0) DEFAULT NULL,
  INSERT_TIME datetime DEFAULT NULL,
  UPDATE_BY decimal(19,0) DEFAULT NULL,
  UPDATE_TIME datetime DEFAULT NULL,
  FROM_DATE datetime DEFAULT NULL,
  TO_DATE datetime DEFAULT NULL,
  AREA varchar(300) ,
  LOSS_CODE varchar(300) ,
  PRIMARY KEY (ACCIDENT_CODE)
) ;


-- aws_us_prod_vault.t_clm_case definition

CREATE TABLE edw_stage.t_clm_case (
  CASE_ID decimal(19,0) NOT NULL,
  CLAIM_NO varchar(60)  NOT NULL,
  CASE_ORGAN_ID decimal(19,0) DEFAULT NULL,
  INSURE_ORGAN_ID decimal(19,0) DEFAULT NULL,
  PROCESS_ORGAN_ID decimal(19,0) DEFAULT NULL,
  POLICY_NO varchar(60) ,
  INSURED_NAME text ,
  LOSS_CAUSE varchar(30) ,
  ACCIDENT_TIME datetime DEFAULT NULL,
  NOTICE_TIME datetime DEFAULT NULL,
  REGISTER_TIME datetime NOT NULL,
  CALLER_NAME varchar(200) ,
  CALLER_TYPE varchar(20) ,
  CALLER_PHONE varchar(60) ,
  CONTACT_NAME varchar(200) ,
  CONTACT_TYPE varchar(10) ,
  CONTACT_PHONE varchar(60) ,
  ACCIDENT_PLACE text ,
  ACCIDENT_DESC text ,
  CASE_STATUS varchar(20)  NOT NULL,
  ACCIDENT_CODE varchar(30) ,
  ACCIDENT_DISTRICT decimal(19,0) DEFAULT NULL,
  AGENT_TEL varchar(60) ,
  POLICE_STATION text ,
  POLICE_STATEMENT_NO varchar(100) ,
  POLICE_STATEMENT_DATE datetime DEFAULT NULL,
  POLICE_REMARK text ,
  DC_FLAG char(1) ,
  INSURED_LIABILITY decimal(10,2) DEFAULT NULL,
  PRODUCT_CODE varchar(20) ,
  VALIDATION_DECISION char(1) ,
  VALIDATION_DATE datetime DEFAULT NULL,
  VALIDATION_REMARK text ,
  EXT_CLAIM_NO varchar(60) ,
  FNOL_TYPE varchar(10)  NOT NULL,
  LOSS_STATUS varchar(60) ,
  SALVAGE_STATUS varchar(60) ,
  SUBROGATION_STATUS varchar(60) ,
  DYNAMIC_FIELDS text ,
  BUSINESS_OBJECT_ID decimal(10,0) DEFAULT NULL,
  INSERT_BY decimal(19,0) NOT NULL,
  INSERT_TIME datetime DEFAULT NULL,
  UPDATE_BY decimal(19,0) NOT NULL,
  UPDATE_TIME datetime DEFAULT NULL,
  CURRENCY_CODE varchar(3) ,
  LAST_REVIEW_DATE datetime DEFAULT NULL,
  ACCIDENT_COUNTRY_CODE varchar(10) ,
  ACCIDENT_REGION_ID decimal(10,0) DEFAULT NULL,
  ACCIDENT_ADDRESS text ,
  INSURANCE_TYPE varchar(10) ,
  REPORTER_EMAIL varchar(60) ,
  DATE_REPORTED_INSURED datetime DEFAULT NULL,
  CLAIMS_MADE varchar(4) ,
  OWNER_ID decimal(19,0) DEFAULT NULL,
  RESERVE_EXCHANGE_RATE decimal(12,6) DEFAULT NULL,
  REVIEW_DATE datetime DEFAULT NULL,
  CLAIM_TYPE varchar(10) ,
  CONTACT_EMAIL varchar(60) ,
  INSURED_TYPE varchar(20) ,
  INSURED_ID decimal(19,0) DEFAULT NULL,
  POLICY_TYPE_CODE varchar(20) ,
  REJECT_REASON varchar(20) ,
  ACCIDENT_STREET varchar(100) ,
  ACCIDENT_TOWN varchar(100) ,
  ACCIDENT_CITY varchar(100) ,
  POSTAL_CODE varchar(100) ,
  FRAUD_STATUS varchar(10) ,
  POLICE_REPORT text ,
  OFFICER1 text ,
  BADGE1 text ,
  OFFICER2 text ,
  BADGE2 text ,
  MIGRATION_REMARK text ,
  RECOVER_FROM varchar(255) ,
  FP_DRIVER_ID decimal(19,0) DEFAULT NULL,
  FP_DRIVER_BIRTH_DATE datetime DEFAULT NULL,
  FP_TEL_NO varchar(20) ,
  CONTACT_PERSON_EMAIL varchar(60) ,
  STATUS_CHANGE_TIME datetime DEFAULT NULL,
  LEAD_CLAIM_OWNER varchar(100) ,
  CLOSURE_REASON text ,
  CLOSURE_REMARKS text ,
  REINSURANCE_CLAIM varchar(100) ,
  BROKER_REFERNCE varchar(100) ,
  LOS_CLOSURE_REASON text ,
  LOS_CLOSURE_REMARKS text ,
  SAL_CLOSURE_REASON text ,
  SAL_CLOSURE_REMARKS text ,
  SUB_CLOSURE_REASON text ,
  SUB_CLOSURE_REMARKS text ,
  CEDING_COMPANY_REFERENCE varchar(60) ,
  MAINTENANCE_PERIOD_DATE datetime DEFAULT NULL,
  CAT_CODE text ,
  PRODUCT_LINE_CODE varchar(30) ,
  SUB_CAUSE_OF_LOSS_CODE varchar(30) ,
  SUB_CAUSE_OF_LOSS_NAME varchar(200) ,
  PRIMARY KEY (CASE_ID)
) ;


-- aws_us_prod_vault.t_clm_case_status definition

CREATE TABLE edw_stage.t_clm_case_status (
  STATUS_CODE varchar(20)  NOT NULL,
  STATUS_NAME varchar(100)  NOT NULL,
  PRIMARY KEY (STATUS_CODE)
) ;


-- aws_us_prod_vault.t_clm_item definition

CREATE TABLE edw_stage.t_clm_item (
  ITEM_ID decimal(19,0) NOT NULL,
  OBJECT_ID decimal(19,0) NOT NULL,
  PRODUCT_CODE varchar(30)  NOT NULL,
  COVERAGE_CODE varchar(30)  NOT NULL,
  COVERAGE_NAME text ,
  SUM_INSURED decimal(20,2) NOT NULL,
  STATUS_CODE varchar(10) ,
  SEQ_NO varchar(10) ,
  UPPER_COVERAGE_CODE varchar(30) ,
  UPPER_COVERAGE_NAME text ,
  POL_COVERAGE_ID decimal(19,0) DEFAULT NULL,
  LOSS_STATUS varchar(60) ,
  SALVAGE_STATUS varchar(60) ,
  SUBROGATION_STATUS varchar(60) ,
  INIT_LOSS_INDEMNITY decimal(20,2) DEFAULT NULL,
  CURRENCY_CODE varchar(3) ,
  DYNAMIC_FIELDS text ,
  BUSINESS_OBJECT_ID decimal(10,0) DEFAULT NULL,
  INSERT_BY decimal(19,0) NOT NULL,
  INSERT_TIME datetime DEFAULT NULL,
  UPDATE_BY decimal(19,0) NOT NULL,
  UPDATE_TIME datetime DEFAULT NULL,
  IS_SHOW char(1) ,
  ADD_CAUSE_OF_LOSS_ON_COVERAGE varchar(100) ,
  CLOSURE_REASON text ,
  CLOSURE_REMARKS text ,
  LOS_CLOSURE_REASON text ,
  LOS_CLOSURE_REMARKS text ,
  SAL_CLOSURE_REASON text ,
  SAL_CLOSURE_REMARKS text ,
  SUB_CLOSURE_REASON text ,
  SUB_CLOSURE_REMARKS text ,
  PRIMARY KEY (ITEM_ID)
) ;


-- aws_us_prod_vault.t_clm_losscause definition

CREATE TABLE edw_stage.t_clm_losscause (
  LOSS_CAUSE_CODE varchar(30)  NOT NULL,
  LOSS_CAUSE_NAME varchar(200)  NOT NULL,
  PRODUCT_LINE_CODE varchar(30) ,
  LOSS_CAUSE_DESC text ,
  INSERT_BY decimal(19,0) DEFAULT NULL,
  INSERT_TIME datetime DEFAULT NULL,
  UPDATE_BY decimal(19,0) DEFAULT NULL,
  UPDATE_TIME datetime DEFAULT NULL,
  PRIMARY KEY (LOSS_CAUSE_CODE)
) ;


-- aws_us_prod_vault.t_clm_note definition

CREATE TABLE edw_stage.t_clm_note (
  NOTE_ID decimal(19,0) NOT NULL,
  CASE_ID decimal(19,0) DEFAULT NULL,
  OBJECT_ID decimal(19,0) DEFAULT NULL,
  NOTE_SUBJECT text ,
  NOTE_CONTENT text ,
  NOTE_CATEGORY varchar(10) ,
  SEND_MESSAGE_TO decimal(19,0) DEFAULT NULL,
  INSERT_BY decimal(19,0) NOT NULL,
  INSERT_TIME datetime DEFAULT NULL,
  UPDATE_BY decimal(19,0) NOT NULL,
  UPDATE_TIME datetime DEFAULT NULL,
  NOTE_LEVEL varchar(20) ,
  NOTE_USER_TYPE char(1) ,
  NOTE_OVERVIEW varchar(500) ,
  PRIMARY KEY (NOTE_ID)
) ;


-- aws_us_prod_vault.t_clm_object definition

CREATE TABLE edw_stage.t_clm_object (
  OBJECT_ID decimal(19,0) NOT NULL,
  CASE_ID decimal(19,0) NOT NULL,
  CLAIMANT_ID decimal(19,0) DEFAULT NULL,
  CLAIMANT_NAME text ,
  DRIVER_ID decimal(19,0) DEFAULT NULL,
  SUBCLAIM_TYPE varchar(30) ,
  RISK_NAME text ,
  INSURED_ID decimal(19,0) DEFAULT NULL,
  DAMAGE_SEVERITY varchar(10) ,
  DAMAGE_TYPE varchar(30) ,
  OBJECT_PLACE text ,
  DAMAGE_DESC text ,
  DRIVER_IS_INSURED varchar(10) ,
  IS_SUBROGATION varchar(10) ,
  IS_SALVAGE varchar(10) ,
  STATUS_CODE varchar(10) ,
  APPRAISAL_USER decimal(19,0) DEFAULT NULL,
  APPRAISAL_DATE datetime DEFAULT NULL,
  APPRAISAL_APPROVER decimal(19,0) DEFAULT NULL,
  APPRAISAL_APPROVE_DATE datetime DEFAULT NULL,
  LAST_DOC_FLAG char(1) ,
  RECEIVED_DATE datetime DEFAULT NULL,
  WORKSHOP_ID decimal(19,0) DEFAULT NULL,
  PLACETOGO_TYPE varchar(10) ,
  FRAUD_SCORE decimal(6,0) DEFAULT NULL,
  SEQ_NO varchar(10) ,
  TOTAL_LOSS_FLAG char(1) ,
  LOSS_STATUS varchar(60) ,
  SALVAGE_STATUS varchar(60) ,
  SUBROGATION_STATUS varchar(60) ,
  CAR_OWNER_ID decimal(19,0) DEFAULT NULL,
  OWNER_ID decimal(19,0) DEFAULT NULL,
  DYNAMIC_FIELDS text ,
  BUSINESS_OBJECT_ID decimal(10,0) DEFAULT NULL,
  INSERT_BY decimal(19,0) NOT NULL,
  INSERT_TIME datetime DEFAULT NULL,
  UPDATE_BY decimal(19,0) NOT NULL,
  UPDATE_TIME datetime DEFAULT NULL,
  LITIGATION_FLAG char(1) ,
  OWNER_ASSIGN_BY decimal(19,0) DEFAULT NULL,
  OWNER_ASSIGN_DATE datetime DEFAULT NULL,
  ESTIMATED_LOSS_AMOUNT decimal(20,2) DEFAULT NULL,
  ESTIMATED_LOSS_CURRENCY varchar(3) ,
  RENTAL_CAR_SERVICE_STATUS varchar(10) ,
  RENTAL_CAR_COMPANY varchar(100) ,
  CAR_RENTAL_TOWN varchar(100) ,
  DAILY_RENTAL_FEE decimal(10,2) DEFAULT NULL,
  RENTAL_PERIOD decimal(10,0) DEFAULT NULL,
  TOTAL_RENTAL_FEE decimal(20,2) DEFAULT NULL,
  COMPANY_CARE varchar(20) ,
  CARE_PROVIDER varchar(20) ,
  CARE_CALL_DATE datetime DEFAULT NULL,
  CARE_SERVICE_DATE datetime DEFAULT NULL,
  CARE_OPERATOR text ,
  INSURANCE_COMPANY varchar(20) ,
  REMARK text ,
  DRIVER_REMARK text ,
  TP_DRIVER_ID decimal(19,0) DEFAULT NULL,
  TP_DRIVER_BIRTH_DATE datetime DEFAULT NULL,
  TP_PLATE_NO varchar(20) ,
  TP_TEL_NO varchar(20) ,
  STATUS_CHANGE_TIME datetime DEFAULT NULL,
  INSURED_ID_ONE decimal(19,0) DEFAULT NULL,
  INSURED_ID_TWO decimal(19,0) DEFAULT NULL,
  SEVERITY_CODE varchar(100) ,
  CLOSURE_REASON text ,
  CLOSURE_REMARKS text ,
  LOS_CLOSURE_REASON text ,
  LOS_CLOSURE_REMARKS text ,
  SAL_CLOSURE_REASON text ,
  SAL_CLOSURE_REMARKS text ,
  SUB_CLOSURE_REASON text ,
  SUB_CLOSURE_REMARKS text ,
  BUSINESS_CLASS varchar(100) ,
  PRIMARY KEY (OBJECT_ID)
) ;


-- aws_us_prod_vault.t_clm_party definition

CREATE TABLE edw_stage.t_clm_party (
  PARTY_ID decimal(19,0) NOT NULL,
  CASE_ID decimal(19,0) NOT NULL,
  INSURED_RELATION varchar(10) ,
  SEQ_NO varchar(10) ,
  CERTI_TYPE varchar(10) ,
  CERTI_CODE varchar(60) ,
  PARTY_NAME text ,
  PARTY_ROLE varchar(2) ,
  LICENSE_NO varchar(60) ,
  LICENSE_TYPE varchar(10) ,
  LICENSE_INITIAL_DATE datetime DEFAULT NULL,
  LICENSE_EXPIRY_DATE datetime DEFAULT NULL,
  PTY_PARTY_ID decimal(19,0) DEFAULT NULL,
  PTY_ADDRESS_ID decimal(19,0) DEFAULT NULL,
  PTY_ACCOUNT_ID decimal(19,0) DEFAULT NULL,
  DYNAMIC_FIELDS text ,
  BUSINESS_OBJECT_ID decimal(10,0) DEFAULT NULL,
  INSERT_BY decimal(19,0) NOT NULL,
  INSERT_TIME datetime DEFAULT NULL,
  UPDATE_BY decimal(19,0) NOT NULL,
  UPDATE_TIME datetime DEFAULT NULL,
  PTY_CONTACT_ID decimal(19,0) DEFAULT NULL,
  NEW_ROLE_TYPE varchar(20) ,
  EMAIL varchar(100) ,
  LEGAL_NAME_UWS varchar(300) ,
  PAYEE_NAME_UWS varchar(300) ,
  PRIMARY KEY (PARTY_ID)
) ;


-- aws_us_prod_vault.t_clm_party_role definition

CREATE TABLE edw_stage.t_clm_party_role (
  ROLE_CODE varchar(2)  NOT NULL,
  ROLE_NAME varchar(200)  NOT NULL,
  PRIMARY KEY (ROLE_CODE)
) ;


-- aws_us_prod_vault.t_clm_pol_insured definition

CREATE TABLE edw_stage.t_clm_pol_insured (
  INSURED_ID decimal(19,0) NOT NULL,
  POLICY_ID decimal(19,0) DEFAULT NULL,
  INSURED_NAME text ,
  DESCRIPTION text ,
  INSURED_NO varchar(60) ,
  BRAND varchar(60) ,
  MODEL varchar(60) ,
  VIN_NO varchar(30) ,
  ENGINE_NO varchar(30) ,
  MAKE_YEAR varchar(10) ,
  CAR_OWNER varchar(60) ,
  INSURED_SEAT_NUM decimal(5,0) DEFAULT NULL,
  SEAT_NUM decimal(5,0) DEFAULT NULL,
  DRIVE_AREA text ,
  NEW_MARKET_VALUE decimal(20,2) DEFAULT NULL,
  APPOINT_DRIVER varchar(30) ,
  BUSINESS_FLAG char(1) ,
  VEHICLE_TYPE varchar(10) ,
  MAKE_MONTH decimal(5,0) DEFAULT NULL,
  PARENT_INSURED_ID decimal(19,0) DEFAULT NULL,
  WEIGHT decimal(12,2) DEFAULT NULL,
  VEHICLE_COLOR varchar(30) ,
  VEHICLE_NO varchar(30) ,
  SUM_INSURED decimal(20,2) DEFAULT NULL,
  DEDUCTIBLE_RATE decimal(5,4) DEFAULT NULL,
  DEDUCTIBLE_AMOUNT decimal(22,4) DEFAULT NULL,
  INSURED_CATEGORY decimal(5,0) DEFAULT NULL,
  EXT_CONTENT text ,
  VEHICLE_USAGE varchar(10) ,
  POST_CODE varchar(10) ,
  COUNTRY_CODE varchar(10) ,
  STATE varchar(80) ,
  DISTRICT varchar(80) ,
  RETROACTIVE_EFF_DATE datetime DEFAULT NULL,
  RETROACTIVE_EXP_DATE datetime DEFAULT NULL,
  MAINTAIN_EFF_DATE datetime DEFAULT NULL,
  MAINTAIN_EXP_DATE datetime DEFAULT NULL,
  CERTI_TYPE varchar(10) ,
  CERTI_CODE varchar(60) ,
  BIRTH_DATE datetime DEFAULT NULL,
  OCCUPATION varchar(200) ,
  ORIGIN_REGION text ,
  DESTINATION_REGION text ,
  MAIN_VOYAGE_TYPE varchar(100) ,
  VOYAGE_NO varchar(30) ,
  DEPARTURE_DATE datetime DEFAULT NULL,
  VALUATION_TYPE varchar(100) ,
  VESSELL_NAME varchar(100) ,
  OTHER_MODEL varchar(60) ,
  REG_NO_TYPE decimal(10,0) DEFAULT NULL,
  NEW_VEHICLE_FLAG decimal(1,0) DEFAULT NULL,
  CAR_OWNER_TEL varchar(30) ,
  BENE_ID decimal(19,0) DEFAULT NULL,
  PLAN_CODE varchar(20) ,
  LIMIT_ID decimal(19,0) DEFAULT NULL,
  DEDUCTIBLE_ID decimal(19,0) DEFAULT NULL,
  INSURED_UID varchar(100) ,
  DYNAMIC_FIELDS text ,
  BUSINESS_OBJECT_ID decimal(10,0) DEFAULT NULL,
  INSERT_BY decimal(19,0) NOT NULL,
  INSERT_TIME datetime DEFAULT NULL,
  UPDATE_BY decimal(19,0) NOT NULL,
  UPDATE_TIME datetime DEFAULT NULL,
  DRIVER_INFO text ,
  ADDRESS varchar(20) ,
  BUSINESS_NATURE text ,
  CONTRACT_TITLE text ,
  PERSON_NAME varchar(120) ,
  POLICY_INSURED_ID decimal(20,0) DEFAULT NULL,
  PRIMARY KEY (INSURED_ID)
) ;


-- aws_us_prod_vault.t_clm_policy definition

CREATE TABLE edw_stage.t_clm_policy (
  POLICY_ID decimal(19,0) NOT NULL,
  CASE_ID decimal(19,0) DEFAULT NULL,
  ORGAN_ID decimal(19,0) DEFAULT NULL,
  POLICY_NO varchar(60) ,
  PRODUCT_CODE varchar(30) ,
  EFF_DATE datetime NOT NULL,
  EXP_DATE datetime NOT NULL,
  PREMIUM_IS_PAID char(1) ,
  REINSURENCE_NO varchar(60) ,
  CATEGORY_REINS varchar(60) ,
  PREMIUM decimal(20,2) NOT NULL,
  ENDO_ID decimal(19,0) DEFAULT NULL,
  POLICY_REMARK text ,
  POLICY_CLAUSES text ,
  POLICY_DESC text ,
  OPEN_POLICY_INFO text ,
  CERTIFICATE_INFO text ,
  GROUP_FLAG varchar(10) ,
  MANUAL_FLAG varchar(10) ,
  ENDO_NO varchar(30) ,
  COIN_OUR_SHARE decimal(12,2) DEFAULT NULL,
  COIN_FLAG char(1) ,
  COIN_LEADER_FLAG char(1) ,
  PLAN_NAME text ,
  CURRENCY_CODE varchar(3) ,
  REINSURANCE_FLAG char(1) ,
  MASTER_POLICY_NO varchar(60) ,
  SUM_INSURED decimal(20,2) DEFAULT NULL,
  DEDUCTIBLE_RATE decimal(5,4) DEFAULT NULL,
  DEDUCTIBLE_AMOUNT decimal(22,4) DEFAULT NULL,
  EXT_CONTENT text ,
  CONFIRM_SEQUENCE_NO varchar(50) ,
  STATE_ID decimal(19,0) DEFAULT NULL,
  RELATED_POLICY_ID decimal(19,0) DEFAULT NULL,
  RENEWAL_TIMES decimal(10,0) DEFAULT NULL,
  LIMIT_ID decimal(19,0) DEFAULT NULL,
  DEDUCTIBLE_ID decimal(19,0) DEFAULT NULL,
  INSERT_BY decimal(19,0) NOT NULL,
  INSERT_TIME datetime DEFAULT NULL,
  UPDATE_BY decimal(19,0) NOT NULL,
  UPDATE_TIME datetime DEFAULT NULL,
  DYNAMIC_FIELDS text ,
  BUSINESS_OBJECT_ID decimal(10,0) DEFAULT NULL,
  RETROACTIVE_DATE datetime DEFAULT NULL,
  COMPLEMENTARY_EXTENDED_PERIOD datetime DEFAULT NULL,
  SUPPLEMENTARY_EXTENDED_PERIOD datetime DEFAULT NULL,
  INSURANCE_TYPE char(1) ,
  FIXED_EXCHANGE_RATE decimal(12,6) DEFAULT NULL,
  CLAIM_MADE varchar(4) ,
  EXTEND_REPORTING_DATE datetime DEFAULT NULL,
  MAINTAINANCE_DATE datetime DEFAULT NULL,
  SME_LCR varchar(10) ,
  SETTLEMENT_OPTION varchar(2) ,
  PML decimal(10,9) DEFAULT NULL,
  BROKER_ID varchar(60) ,
  BROKER_NAME varchar(60) ,
  CEDING_COMPANY_NAME varchar(60) ,
  CEDING_COMPANY_ID varchar(60) ,
  DIRECT_OR_ASSUMED_INDICATOR varchar(60) ,
  AW_POLICY_ID varchar(60) ,
  MAINTENANCE_PERIOD_DATE datetime DEFAULT NULL,
  PRIMARY KEY (POLICY_ID)
) ;


-- aws_us_prod_vault.t_clm_reserve_his definition

CREATE TABLE edw_stage.t_clm_reserve_his (
  HIS_ID decimal(19,0) NOT NULL,
  ITEM_ID decimal(19,0) NOT NULL,
  RESERVE_TYPE varchar(30)  NOT NULL,
  OUTSTANDING_AMOUNT decimal(20,2) NOT NULL,
  OUTSTANDING_CHANGED decimal(20,2) NOT NULL,
  SETTLE_AMOUNT decimal(20,2) NOT NULL,
  SETTLE_CHANGED decimal(20,2) NOT NULL,
  CURRENCY_CODE varchar(3) ,
  CHANGE_TYPE varchar(10)  NOT NULL,
  BUSINESS_INSTANCE_ID decimal(19,0) DEFAULT NULL,
  TRANS_ID decimal(19,0) DEFAULT NULL,
  OLD_STATUS varchar(10) ,
  NEW_STATUS varchar(10) ,
  CLOSE_TYPE varchar(10) ,
  REJECT_REASON varchar(10) ,
  REOPEN_CAUSE varchar(10) ,
  REMARK text ,
  INSERT_BY decimal(19,0) NOT NULL,
  INSERT_TIME datetime DEFAULT NULL,
  UPDATE_BY decimal(19,0) NOT NULL,
  UPDATE_TIME datetime DEFAULT NULL,
  POST_DATE datetime DEFAULT NULL,
  RETROACTIVE_ADJUST varchar(1) ,
  RESERVE_LEVEL text ,
  RESERVE_UPDATE_TRIGGER_FROM varchar(100) ,
  PRIMARY KEY (HIS_ID)
) ;


-- aws_us_prod_vault.t_clm_settle definition

CREATE TABLE edw_stage.t_clm_settle (
  SETTLE_ID decimal(19,0) NOT NULL,
  CASE_ID decimal(19,0) DEFAULT NULL,
  OBJECT_ID decimal(19,0) DEFAULT NULL,
  TIMES decimal(5,0) DEFAULT NULL,
  SUBMITTER decimal(19,0) DEFAULT NULL,
  SUBMIT_DATE datetime DEFAULT NULL,
  APPROVER decimal(19,0) DEFAULT NULL,
  APPROVE_DATE datetime DEFAULT NULL,
  SETTLE_STATUS varchar(10) ,
  REMARK text ,
  SETTLEMENT_NO varchar(100) ,
  CLAIM_TYPE varchar(30) ,
  BUSINESS_OBJECT_ID decimal(10,0) DEFAULT NULL,
  DYNAMIC_FIELDS text ,
  INSERT_BY decimal(19,0) NOT NULL,
  INSERT_TIME datetime DEFAULT NULL,
  UPDATE_BY decimal(19,0) NOT NULL,
  UPDATE_TIME datetime DEFAULT NULL,
  CO_INSURANCE_PAYMENT varchar(10) ,
  BREACH_OF_CONTRACT_REASON text ,
  SETLNO_ACTION_SUFFIX varchar(20) ,
  PRIMARY KEY (SETTLE_ID)
) ;


-- aws_us_prod_vault.t_clm_settle_item definition

CREATE TABLE edw_stage.t_clm_settle_item (
  SETTLE_ITEM_ID decimal(19,0) NOT NULL,
  SETTLE_PAYEE_ID decimal(19,0) NOT NULL,
  SETTLEMENT_ITEM_NO varchar(100) ,
  ITEM_ID decimal(19,0) DEFAULT NULL,
  RESERVE_TYPE varchar(30) ,
  PAYMENT_TYPE varchar(30) ,
  PAY_FINAL varchar(10) ,
  SETTLE_CURRENCY varchar(3) ,
  SETTLE_AMOUNT decimal(20,2) NOT NULL,
  RESERVE_CURRENCY varchar(3) ,
  RESERVE_EXCHANGE_RATE decimal(12,6) DEFAULT NULL,
  RESERVE_SETTLE_AMOUNT decimal(20,2) DEFAULT NULL,
  LOCAL_CURRENCY varchar(3) ,
  LOCAL_EXCHANGE_RATE decimal(12,6) DEFAULT NULL,
  LOCAL_SETTLE_AMOUNT decimal(20,2) DEFAULT NULL,
  BUSINESS_OBJECT_ID decimal(10,0) DEFAULT NULL,
  DYNAMIC_FIELDS text ,
  INSERT_BY decimal(19,0) NOT NULL,
  INSERT_TIME datetime DEFAULT NULL,
  UPDATE_BY decimal(19,0) NOT NULL,
  UPDATE_TIME datetime DEFAULT NULL,
  TAX_CODE varchar(30) ,
  TAX_RATE decimal(10,4) DEFAULT NULL,
  TAX_AMOUNT decimal(20,2) DEFAULT NULL,
  GST_CAL_TYPE varchar(10) ,
  GST_RECOVERABLE decimal(20,2) DEFAULT NULL,
  GST_PAYABLE decimal(20,2) DEFAULT NULL,
  PRIMARY KEY (SETTLE_ITEM_ID)
) ;


-- aws_us_prod_vault.t_clm_settle_payee definition

CREATE TABLE edw_stage.t_clm_settle_payee (
  SETTLE_PAYEE_ID decimal(19,0) NOT NULL,
  SETTLE_ID decimal(19,0) NOT NULL,
  PAYEE_ID decimal(19,0) DEFAULT NULL,
  PAYMENT_STATUS varchar(50) ,
  SETTLE_CURRENCY varchar(3) ,
  SETTLE_AMOUNT decimal(20,2) NOT NULL,
  LOCAL_CURRENCY varchar(3) ,
  LOCAL_EXCHANGE_RATE decimal(12,6) DEFAULT NULL,
  LOCAL_SETTLE_AMOUNT decimal(20,2) DEFAULT NULL,
  PAID_AMOUNT decimal(20,2) DEFAULT NULL,
  EXT_TRANS_ID decimal(19,0) DEFAULT NULL,
  PAY_MODE varchar(19) ,
  PTY_ACCOUNT_ID decimal(19,0) DEFAULT NULL,
  PTY_ADDRESS_ID decimal(19,0) DEFAULT NULL,
  BANK_CODE varchar(10) ,
  ACCOUNT_NO varchar(100) ,
  ACCOUNT_NAME text ,
  ADDRESS text ,
  CHECK_NUMBER varchar(30) ,
  CHECK_DELIVER_DATE datetime DEFAULT NULL,
  REMARK text ,
  BUSINESS_OBJECT_ID decimal(10,0) DEFAULT NULL,
  DYNAMIC_FIELDS text ,
  INSERT_BY decimal(19,0) NOT NULL,
  INSERT_TIME datetime DEFAULT NULL,
  UPDATE_BY decimal(19,0) NOT NULL,
  UPDATE_TIME datetime DEFAULT NULL,
  PAYEE_NAME text ,
  REF_NUMBER varchar(100) ,
  REF_DATE datetime DEFAULT NULL,
  ADDRESS_JSON text ,
  ACCOUNT_JSON text ,
  RESERVE_CURRENCY varchar(3) ,
  RESERVE_EXCHANGE_RATE decimal(12,6) DEFAULT NULL,
  RESERVE_SETTLE_AMOUNT decimal(20,2) DEFAULT NULL,
  PARENT_PAYEE_ID decimal(19,0) DEFAULT NULL,
  SWIFT_CODE varchar(100) ,
  CHEQUE_ISSUE_DATE datetime DEFAULT NULL,
  CHEQUE_RECEIVE_DATE datetime DEFAULT NULL,
  PAYEE_TYPE varchar(20) ,
  DEBIT_CREDIT_NO varchar(40) ,
  IS_PRIMARY_PAYEE varchar(20) ,
  TO_EMAIL varchar(300) ,
  CC_EMAIL varchar(600) ,
  PTY_PARTY_EMAIL varchar(300) ,
  LEGAL_NAME_UWS varchar(300) ,
  PAYEE_NAME_UWS varchar(300) ,
  BCC_EMAIL varchar(600) ,
  UEN varchar(30) ,
  NRIC varchar(30) ,
  MOBILE_NUMBER decimal(20,0) DEFAULT NULL,
  PTY_ORG_ORGANIZATION_ID_NUMBER varchar(120) ,
  PRIMARY KEY (SETTLE_PAYEE_ID)
) ;


-- aws_us_prod_vault.t_dd_busi_data_table_record definition

CREATE TABLE edw_stage.t_dd_busi_data_table_record (
  RECORD_ID decimal(19,0) NOT NULL,
  DATA_TABLE_ID decimal(19,0) DEFAULT NULL,
  DYNAMIC_FIELDS text ,
  INSERT_BY decimal(19,0) NOT NULL,
  UPDATE_BY decimal(19,0) NOT NULL,
  INSERT_TIME datetime DEFAULT NULL,
  UPDATE_TIME datetime DEFAULT NULL,
  RECORD_USAGE decimal(1,0) NOT NULL,
  BUSINESS_OBJECT_ID decimal(19,0) DEFAULT NULL,
  PRIMARY KEY (RECORD_ID)
) ;


-- aws_us_prod_vault.t_int_address definition

CREATE TABLE edw_stage.t_int_address (
  ID decimal(19,0) NOT NULL,
  T_ADDRESS_ID decimal(19,0) DEFAULT NULL,
  SOURCE_ID decimal(19,0) DEFAULT NULL,
  SUB_SOURCE_ID decimal(19,0) DEFAULT NULL,
  ADDRESS_PAGE_TYPE varchar(100) ,
  INSERT_BY decimal(19,0) DEFAULT NULL,
  INSERT_TIME datetime DEFAULT NULL,
  UPDATE_BY decimal(19,0) DEFAULT NULL,
  UPDATE_TIME datetime DEFAULT NULL,
  PRIMARY KEY (ID)
) ;


--t_dd_busi_code_table 

CREATE TABLE edw_stage.t_dd_busi_code_table 
(
  CODE_TABLE_ID decimal(19,0) NOT NULL,
  NAME varchar(100)  NOT NULL,
  DESCRIPTION varchar(500)  DEFAULT NULL,
  CODE_TABLE_TYPE decimal(19,0) NOT NULL,
  PREDICATE text ,
  ID_FIELD varchar(100)  NOT NULL,
  CODE_FIELD varchar(100)  NOT NULL,
  DESC_FIELD varchar(100)  NOT NULL,
  SORT_FIELD varchar(100)  DEFAULT NULL,
  SORT_TYPE varchar(10)  DEFAULT NULL,
  CONTEXT_ID decimal(19,0) NOT NULL,
  DATA_SOURCE varchar(500)  NOT NULL,
  IS_SMALL char(1)  DEFAULT NULL,
  NEED_CACHE char(1)  DEFAULT NULL,
  INSERT_BY decimal(19,0) NOT NULL,
  UPDATE_BY decimal(19,0) NOT NULL,
  INSERT_TIME datetime DEFAULT NULL,
  UPDATE_TIME datetime DEFAULT NULL,
  RECORD_USAGE decimal(1,0) NOT NULL,
  CONDITION_FIELDS varchar(2000)  DEFAULT NULL,
  NEED_MULTI_LANG char(1)  DEFAULT NULL,
  ID_DATA_TYPE decimal(5,0) DEFAULT NULL,
  CODE_DATA_TYPE decimal(5,0) DEFAULT NULL,
  DATA_TABLE_ID decimal(19,0) DEFAULT NULL,
  DOMAIN_MODEL_CLASS_ID decimal(19,0) DEFAULT NULL,
  SORT_DATA_TYPE decimal(5,0) DEFAULT NULL,
  MODULE_ID decimal(19,0) DEFAULT NULL,
  NEED_SYNCHRONIZE varchar(10)  DEFAULT NULL,
  PRIMARY KEY (CODE_TABLE_ID)
) ;