CREATE TABLE edw_integration.policy_surplus_lines_state_feed (
    	[policy_no] varchar(255),
	[prior_policy_no] varchar(255) NULL,
	[insured_name] varchar(8000) NULL,
	[processed_date] datetime NULL,
	[policy_effective_date] date,
	[policy_expiration_date] date,
	[transaction_type] varchar(255) NULL,
	[transaction_desc] varchar(4000) NULL,
	[address] varchar(511) NULL,
	[city] varchar(255) NULL,
	[state] varchar(255) NULL,
	[zip] varchar(255) NULL,
	[county] varchar(255) NULL,
	[primary_coverage_amount] int NULL,
	[aop_deductible] varchar(255) NULL,
	[hurricane_deductible] varchar(255) NULL,
	[risk_state_cd] varchar(255),
	[product_cd] varchar(255),
	[transaction_seq_no] int,
	[transaction_effective_dt] date,
	[agency_name] varchar(255) NULL,
	[broker_id] varchar(255),
	[premium_amt] decimal(38, 2) NULL,
	[mga_fee_amt] decimal(38, 2) NULL,
	[inpection_fee_amt] decimal(38, 2) NULL,
	[surplus_lines_tax_amt] decimal(38, 2) NULL,
	[fire_marshal_tax_amt] decimal(38, 2) NULL,
	[state_fee] decimal(38, 2) NULL,
	[grand_total_amt] decimal(38, 2) NULL,
	[SL_Control_Number] varchar(30) NULL,
	[bdm_name] varchar(255) NULL,
	[uw_name] varchar(255) NULL,
	[accounting_period] varchar(25),
	[state_confirmation_number] varchar(255) NULL,
	[state_submission_date] date NULL,
	[submission_notes] varchar(255) NULL,
	create_ts datetime ,
  	update_ts datetime ,
  	etl_audit_sk int,
    CONSTRAINT pk_policy_surplus_lines_state_feed PRIMARY KEY (policy_no,policy_effective_date,transaction_seq_no)
 )
;


INSERT INTO edw_integration.tintegration_table_detail(table_nm,	table_type,	table_desc,	load_method,	load_type,	load_frequency,	create_ts,	update_ts)
VALUES ('policy_surplus_lines_state_feed','Feed','This table provides Surplus lines data to support state reporting requirements','Stored Procedure','Insert','Weekly',getdate(),getdate());