
IF OBJECT_ID('edw_stage.t_clm_subclaim_type', 'U') IS NOT NULL
DROP TABLE edw_stage.t_clm_subclaim_type
GO

create table edw_stage.t_clm_subclaim_type
(
  SUBCLAIM_TYPE_CODE VARCHAR(30) NOT NULL,
  PRODUCT_LINE_CODE VARCHAR(30) NOT NULL,
  SUBCLAIM_TYPE_NAME VARCHAR(200) NOT NULL,
  IS_UNIQUE CHAR(1) NULL,
  IS_INSURED_OBJECT CHAR(1) NULL,
  SUBCLAIM_TYPE_DESC VARCHAR(255),
  FRAUD_SUBJECT_CODE VARCHAR(10)DEFAULT NULL,
  INSERT_BY DECIMAL(19,0) DEFAULT NULL,
  INSERT_TIME DATETIME DEFAULT NULL,
  UPDATE_BY DECIMAL(19,0) DEFAULT NULL,
  UPDATE_TIME DATETIME DEFAULT NULL,
  CONSTRAINT [pk_t_clm_subclaim_type] PRIMARY KEY CLUSTERED 
	(
		[SUBCLAIM_TYPE_CODE] ASC
	)
);