-- admin.dragon_customer definition

create table edw_stage.dragon_customer 
(
composite_search_key varchar(4000), 
exchange_id decimal(12,0), 
customer_id decimal(12,0) not null, 
customer_name varchar(200) null, 
customer_creation_date date null, 
customer_address varchar(500) null, 
customer_jurisdiction varchar(50) null, 
customer_zip_postal_cd varchar(10) null, 
customer_contact_name varchar(200) null, 
customer_contact_phone varchar(50) null, 
customer_object_state decimal(12,0) null, 
customer_fein varchar(10) null, 
customer_external_id varchar(100) null, 
parent_customer_id decimal(12,0) null, 
parent_customer_name varchar(200) null, 
customer_number varchar(50) null, 
customer_dba varchar(100) null, 
partner_id decimal(12,0) null, 
carrier_customer_number decimal(12,0) null, 
partner_name varchar(200) null, 
primary_entity_id decimal(12,0) null, 
customer_email_address varchar(100) null, 
customer_date_of_birth date null, 
login_password varchar(20) null, 
first_time_login_flag varchar(5) null, 
carrier_branch varchar(100) null, 
customer_search_string varchar(500) null, 
carrier_branch_id decimal(12,0) null, 
account_number varchar(50) null, 
billing_primary_csr varchar(200) null, 
customer_address_line1 varchar(100) null, 
customer_address_city varchar(100) null, 
customer_address_country varchar(100) null, 
customer_past_due decimal(38,10) null, 
customer_status varchar(100) null, 
prospect_number varchar(100) null, 
life_firm varchar(100) null, 
life_producer varchar(100) null, 
life_underwriter_mgr varchar(100) null, 
life_underwriter varchar(100) null, 
life_risk_rating varchar(20) null, 
object_source_desc varchar(30) null, 
legacy_object_id decimal(12,0) null, 
legacy_id varchar(100) null, 
policy_trsfrm_status varchar(2) null, 
external_customer_number varchar(20) null, 
customer_last_upd_dt date null, 
object_source decimal(12,0) null,
 CONSTRAINT [pk_dragon_customer] PRIMARY KEY CLUSTERED 
(
	[customer_id] ASC
) ON [PRIMARY]
)

GO

create table edw_stage.dragon_partner 
(
   composite_search_key varchar(1000), 
	partner_city varchar(100), 
	partner_id decimal(12,0) not null, 
	partner_name varchar(200), 
	partner_phone varchar(100), 
	partner_us_state varchar(100), 
	partner_state_id decimal(12,0), 
	partner_zip varchar(20), 
	partner_type_id decimal(12,0), 
	exchange_id decimal(12,0), 
	partner_parent_id decimal(12,0), 
	partner_type varchar(100), 
	agency_svcs_agent_ind varchar(50), 
	partner_agency_code varchar(50), 
	partner_object_status varchar(100), 
	agency_assigned_branch_no decimal(38,10), 
	agency_assigned_branch_name varchar(200), 
	partner_primary_contact varchar(200), 
	partner_marketing_manager varchar(200), 
	partner_county varchar(100), 
	partner_parent_name varchar(200), 
	uw_group_name varchar(100), 
	uw_group_id decimal(12,0), 
	partner_country varchar(100), 
	reinsurer_facultative_tf decimal(12,0), 
	reinsurer_treaty_tf decimal(12,0), 
	parent_partner_id decimal(12,0), 
	parent_partner_name varchar(200), 
	test_partner_indicator varchar(10), 
	annual_term_eligibility_tf varchar(10), 
	broker_type varchar(100), 
	partner_channel_type varchar(100), 
	billing_account_no varchar(100), 
	commission_plan varchar(10), 
	carrier_branch varchar(100), 
	partner_search_string varchar(500), 
	carrier_branch_id decimal(12,0), 
	carrier_branch_sub_type varchar(100), 
	carrier_branch_phone varchar(100), 
	carrier_branch_number varchar(100), 
	partner_text_search varchar(500), 
	partner_primary_address varchar(200), 
	ultimate_parent_partner decimal(12,0), 
	partner_marketing_director varchar(100), 
	partner_marketing_director_id decimal(12,0), 
	partner_marketing_manager_id decimal(12,0), 
	obligee_id decimal(12,0), 
	legacy_object_id decimal(12,0), 
	object_source_desc varchar(30), 
	legacy_id varchar(100), 
	billing_csr varchar(100), 
	object_source decimal(12,0), 
	partner_lexisnexis_code_suffix varchar(10), 
	bdm varchar(100), 
	uw_territory varchar(100), 
	contract_date varchar(100),
 constraint [pk_dragon_partner] primary key clustered 
	(
		[partner_id] asc
	)
) on [primary]

GO

CREATE TABLE [edw_stage].[dragon_billingaccount](
	[billingaccount_id] [decimal](12, 0) NOT NULL,
	[composite_search_key] [varchar](4000) NULL,
	[exchange_id] [decimal](38, 10) NULL,
	[account_number] [varchar](50) NULL,
	[account_type] [varchar](100) NULL,
	[account_status] [varchar](100) NULL,
	[partner_name] [varchar](200) NULL,
	[partner_type] [varchar](100) NULL,
	[customer_object_id] [decimal](38, 10) NULL,
	[partner_object_id] [decimal](38, 10) NULL,
	[dragonuser_object_id] [decimal](38, 10) NULL,
	[parent_object_type_id] [varchar](100) NULL,
	[partner_object_state] [varchar](100) NULL,
	[user_actor_type] [varchar](100) NULL,
	[partner_object_type] [varchar](100) NULL,
	[account_partner_name_type] [varchar](500) NULL,
	[customer_agency_id] [decimal](38, 10) NULL,
	[user_agency_id] [decimal](38, 10) NULL,
	[object_state_enum] [decimal](38, 10) NULL,
	[creation_date] [date] NULL,
	[last_updation_date] [date] NULL,
	[parent_partner_id] [decimal](38, 10) NULL,
	[parent_partner_name] [varchar](500) NULL,
	[timezone_id] [decimal](12, 0) NULL,
	[billing_primary_csr] [varchar](200) NULL,
	[balance_amount] [decimal](38, 10) NULL,
	[total_cash] [decimal](38, 10) NULL,
	[address_line1] [varchar](100) NULL,
	[address_city] [varchar](100) NULL,
	[address_state] [varchar](100) NULL,
	[address_country] [varchar](100) NULL,
	[address_zip_code] [varchar](100) NULL,
	[account_type_id] [decimal](12, 0) NULL,
	[past_due] [decimal](12, 2) NULL,
	[current_due] [decimal](12, 2) NULL,
	[future_due] [decimal](12, 2) NULL,
	[object_source_desc] [varchar](30) NULL,
	[legacy_object_id] [decimal](12, 0) NULL,
	[legacy_id] [varchar](100) NULL,
	[policy_id] [decimal](12, 0) NULL,
	[policy_number] [varchar](100) NULL,
	[policy_object_type] [varchar](100) NULL,
	[partner_agency_business_type] [decimal](5, 0) NULL,
	[account_partner_code_name] [varchar](500) NULL,
	[last_datamart_update_date] [date] NULL,
	[partner_code] [varchar](50) NULL,
	[object_source] [decimal](12, 0) NULL,
 CONSTRAINT [pk_dragon_billingaccount] PRIMARY KEY CLUSTERED 
(
	[billingaccount_id] ASC
)
) ON [PRIMARY]
GO

CREATE TABLE [edw_stage].[dragon_policy](
	[policy_id] [decimal](12, 0) NOT NULL,
	[policy_number] [varchar](50) NULL,
	[policy_external_id] [varchar](100) NULL,
	[policy_creation_date] [datetime] NULL,
	[policy_last_upd_date] [datetime] NULL,
	[policy_bound_date] [datetime] NULL,
	[policy_effective_date] [datetime] NULL,
	[policy_expiration_date] [datetime] NULL,
	[policy_object_state_id] [decimal](12, 0) NULL,
	[policy_object_state_name] [varchar](100) NULL,
	[hold_status] [varchar](30) NULL,
	[policy_product_id] [decimal](12, 0) NULL,
	[policy_product_name] [varchar](100) NULL,
	[policy_lob_id] [decimal](12, 0) NULL,
	[policy_lob_name] [varchar](100) NULL,
	[policy_broker_id] [decimal](12, 0) NULL,
	[policy_broker_name] [varchar](200) NULL,
	[policy_producer_id] [decimal](12, 0) NULL,
	[policy_producer_name] [varchar](200) NULL,
	[policy_partner_id] [decimal](12, 0) NULL,
	[policy_partner_name] [varchar](200) NULL,
	[policy_partner_channel] [varchar](100) NULL,
	[policy_uw_id] [decimal](12, 0) NULL,
	[policy_uw_name] [varchar](100) NULL,
	[customer_id] [decimal](12, 0) NULL,
	[carrier_customer_number] [decimal](12, 0) NULL,
	[primary_entity_id] [decimal](12, 0) NULL,
	[primary_entity_full_name] [varchar](200) NULL,
	[customer_fein] [varchar](20) NULL,
	[customer_ssn] [varchar](20) NULL,
	[customer_phone] [varchar](20) NULL,
	[policy_risk_address_id] [decimal](12, 0) NULL,
	[policy_risk_country_id] [decimal](12, 0) NULL,
	[policy_risk_country] [varchar](100) NULL,
	[policy_jurisdiction_id] [decimal](12, 0) NULL,
	[policy_jurisdiction_name] [varchar](100) NULL,
	[policy_risk_state_id] [decimal](12, 0) NULL,
	[policy_risk_state] [varchar](100) NULL,
	[policy_risk_city] [varchar](100) NULL,
	[policy_risk_zip_code] [varchar](10) NULL,
	[policy_premium] [decimal](38, 10) NULL,
	[policy_inforce_premium] [decimal](12, 2) NULL,
	[policy_earned_premium] [decimal](12, 2) NULL,
	[policy_claim_amount] [decimal](12, 2) NULL,
	[policy_quote_id] [decimal](12, 0) NULL,
	[policy_renewal_type] [varchar](100) NULL,
	[renewal_image_prior_days] [decimal](38, 10) NULL,
	[renewal_issue_prior_days] [decimal](38, 10) NULL,
	[renewal_hold_indicator] [varchar](1) NULL,
	[renewal_image_target_date] [datetime] NULL,
	[renewal_issue_target_date] [datetime] NULL,
	[composite_search_key] [varchar](4000) NULL,
	[customer_name] [varchar](200) NULL,
	[billing_method] [varchar](50) NULL,
	[carrier_branch] [varchar](100) NULL,
	[billing_method_id] [decimal](12, 0) NULL,
	[direct_billed_to] [varchar](100) NULL,
	[direct_billed_to_id] [decimal](12, 0) NULL,
	[timezone_id] [decimal](12, 0) NULL,
	[policy_billing_premium] [decimal](38, 10) NULL,
	[carrier_branch_id] [decimal](12, 0) NULL,
	[policy_cash_available] [decimal](38, 10) NULL,
	[responsible_billing_account] [decimal](12, 0) NULL,
	[past_due_amount] [decimal](12, 2) NULL,
	[current_due_amount] [decimal](12, 2) NULL,
	[future_due_amount] [decimal](12, 2) NULL,
	[due_amount] [decimal](38, 10) NULL,
	[company_name] [varchar](100) NULL,
	[billing_status] [varchar](100) NULL,
	[billing_primary_csr] [varchar](200) NULL,
	[billing_primary_csr_id] [decimal](12, 0) NULL,
	[obligee_name] [varchar](100) NULL,
	[principal_name] [varchar](100) NULL,
	[bond_type] [varchar](100) NULL,
	[contract_amount] [varchar](20) NULL,
	[bond_amount] [varchar](20) NULL,
	[affinity_group_id] [decimal](12, 0) NULL,
	[affinity_group_name] [varchar](100) NULL,
	[policy_current_date] [datetime] NULL,
	[life_subproduct_id] [decimal](38, 10) NULL,
	[life_subproduct_name] [varchar](100) NULL,
	[policy_term] [varchar](100) NULL,
	[object_source_desc] [varchar](30) NULL,
	[legacy_object_id] [decimal](12, 0) NULL,
	[legacy_id] [varchar](100) NULL,
	[lf_policy_yngst_ins] [varchar](200) NULL,
	[policy_down_payment_mode] [decimal](12, 0) NULL,
	[billing_account_number] [decimal](12, 0) NULL,
	[object_source] [decimal](12, 0) NULL,
	[writing_company_id] [decimal](12, 0) NULL,
	[writing_company_name] [varchar](500) NULL,
	[program] [varchar](100) NULL,
	[program_id] [decimal](38, 10) NULL,
	[policy_balance] [decimal](12, 2) NULL,
	[last_policy_trx_id] [decimal](38, 10) NULL,
 CONSTRAINT [pk_dragon_policy] PRIMARY KEY CLUSTERED 
(
	[policy_id] ASC
)
) ON [PRIMARY]
GO

CREATE TABLE [edw_stage].[dragon_policy_term](
	[policy_term_id] [decimal](12, 0) NOT NULL,
	[policy_id] [decimal](12, 0) NULL,
	[policy_term_eff_date] [date] NULL,
	[policy_term_exp_date] [date] NULL,
	[policy_term_billing_status] [varchar](100) NULL,
	[policy_term_pas_status] [varchar](100) NULL,
	[composite_search_key] [varchar](1000) NULL,
	[policy_term] [varchar](100) NULL,
	[legacy_object_id] [decimal](12, 0) NULL,
	[legacy_id] [varchar](100) NULL,
	[object_source_desc] [varchar](30) NULL,
	[legacy_effective_date] [date] NULL,
	[legacy_expiration_date] [date] NULL,
	[term_policy_number] [varchar](50) NULL,
	[policy_term_billing_method_id] [decimal](12, 0) NULL,
	[policy_term_billing_method] [varchar](50) NULL,
	[last_audit_transaction] [decimal](12, 0) NULL,
	[object_source] [decimal](12, 0) NULL,
	[outstanding_balance] [decimal](12, 2) NULL,
	[next_invoice_date] [date] NULL,
 CONSTRAINT [pk_dragon_policy_term] PRIMARY KEY CLUSTERED 
(
	[policy_term_id] ASC
)
) ON [PRIMARY]
GO


CREATE TABLE [edw_stage].[dragon_policy_trx](
	[policy_trx_id] [decimal](12, 0) NOT NULL,
	[policy_id] [decimal](12, 0) NULL,
	[policy_trx_seq_num] [decimal](38, 10) NULL,
	[policy_trx_description] [varchar](500) NULL,
	[policy_trx_eff_date] [datetime] NULL,
	[policy_trx_process_date] [datetime] NULL,
	[policy_trx_creation_date] [datetime] NULL,
	[policy_trx_last_upd_dt] [datetime] NULL,
	[policy_trx_rf_seq] [decimal](38, 10) NULL,
	[policy_trx_rb_seq] [decimal](38, 10) NULL,
	[policy_trx_premium_bef] [decimal](38, 10) NULL,
	[policy_trx_premium_aft] [decimal](38, 10) NULL,
	[policy_trx_premium_chg] [decimal](38, 10) NULL,
	[policy_trx_balance_aft] [decimal](38, 10) NULL,
	[policy_trx_image_eff_date] [datetime] NULL,
	[policy_trx_image_exp_date] [datetime] NULL,
	[policy_trx_type_id] [decimal](12, 0) NULL,
	[policy_trx_type_name] [varchar](100) NULL,
	[policy_trx_policy_number] [varchar](20) NULL,
	[policy_trx_insured_name] [varchar](200) NULL,
	[policy_trx_object_state_id] [decimal](12, 0) NULL,
	[policy_trx_object_state_name] [varchar](100) NULL,
	[policy_trx_processed_tf] [varchar](1) NULL,
	[policy_trx_rollforward_tf] [varchar](1) NULL,
	[policy_trx_rb_rollforward_tf] [varchar](1) NULL,
	[policy_trx_generic_instance] [decimal](12, 0) NULL,
	[policy_trx_cumulative_payment] [decimal](38, 10) NULL,
	[policy_trx_product_id] [decimal](12, 0) NULL,
	[policy_trx_product_name] [varchar](100) NULL,
	[policy_trx_lob_id] [decimal](12, 0) NULL,
	[policy_trx_lob_name] [varchar](100) NULL,
	[customer_id] [decimal](12, 0) NULL,
	[carrier_customer_number] [decimal](12, 0) NULL,
	[primary_entity_id] [decimal](12, 0) NULL,
	[primary_entity_full_name] [varchar](200) NULL,
	[policy_trx_broker_id] [decimal](12, 0) NULL,
	[policy_trx_broker_name] [varchar](100) NULL,
	[policy_trx_producer_id] [decimal](12, 0) NULL,
	[policy_trx_producer_name] [varchar](100) NULL,
	[policy_trx_partner_id] [decimal](12, 0) NULL,
	[policy_trx_partner_name] [varchar](100) NULL,
	[policy_trx_partner_channel] [varchar](100) NULL,
	[policy_trx_uw_id] [decimal](12, 0) NULL,
	[policy_trx_uw_name] [varchar](100) NULL,
	[policy_trx_risk_address_id] [decimal](12, 0) NULL,
	[policy_trx_risk_country_id] [decimal](12, 0) NULL,
	[policy_trx_risk_country] [varchar](100) NULL,
	[policy_trx_jurisdiction_id] [decimal](12, 0) NULL,
	[policy_trx_jurisdiction_name] [varchar](100) NULL,
	[policy_trx_risk_state_id] [decimal](12, 0) NULL,
	[policy_trx_risk_state] [varchar](100) NULL,
	[policy_trx_risk_city] [varchar](100) NULL,
	[policy_trx_risk_zip_code] [varchar](10) NULL,
	[composite_search_key] [varchar](4000) NULL,
	[ptp_id] [decimal](12, 0) NULL,
	[trx_type_eff_date] [varchar](500) NULL,
	[carrier_branch] [varchar](100) NULL,
	[carrier_branch_id] [decimal](12, 0) NULL,
	[audit_for_trx_id] [decimal](12, 0) NULL,
	[policy_term_id] [decimal](38, 10) NULL,
	[policy_trx_status_id] [decimal](22, 0) NULL,
	[policy_trx_status_name] [varchar](500) NULL,
	[payment_plan_type] [varchar](50) NULL,
	[profile_mode] [varchar](50) NULL,
	[payer_firstname] [varchar](100) NULL,
	[payer_lastname] [varchar](100) NULL,
	[card_number] [varchar](100) NULL,
	[card_exp_year] [varchar](100) NULL,
	[card_exp_month] [varchar](100) NULL,
	[bank_id] [decimal](20, 0) NULL,
	[bank_name] [varchar](100) NULL,
	[bank_transit_num] [decimal](20, 0) NULL,
	[policy_current_due] [decimal](12, 2) NULL,
	[policy_trx_subtype_id] [decimal](12, 0) NULL,
	[legacy_object_id] [decimal](12, 0) NULL,
	[policy_trx_last_updated_by] [varchar](100) NULL,
	[object_source_desc] [varchar](30) NULL,
	[legacy_id] [varchar](100) NULL,
	[object_source] [decimal](12, 0) NULL,
	[policy_trx_edw_status_id] [decimal](12, 0) NULL,
	[policy_trx_edw_status] [varchar](100) NULL,
	[policy_trx_customer_vip] [varchar](20) NULL,
	[policy_trx_policy_program] [varchar](50) NULL,
	[policy_renewal_hold_indicator] [varchar](1) NULL,
	[cancellation_reason] [varchar](100) NULL,
 CONSTRAINT [pk_dragon_policy_trx] PRIMARY KEY CLUSTERED 
(
	[policy_trx_id] ASC
)
) ON [PRIMARY]
GO

CREATE TABLE [edw_stage].[OneShieldPolicy](
	[oneshield_policy_sk] [int] IDENTITY(1,1) NOT NULL,
	[policy_number] [varchar](255) NULL,
	[insured_name] [varchar](255) NULL,
	[product] [varchar](255) NULL,
	[company] [varchar](255) NULL,
	[uw_full_name] [varchar](255) NULL,
	[transaction_processed_dt] [date] NULL,
	[transaction_effective_dt] [date] NULL,
	[policy_effective_date] [date] NULL,
	[policy_expiration_date] [date] NULL,
	[year_name_model] [varchar](1000) NULL,
	[risk_address] [varchar](1000) NULL,
	[risk_group] [varchar](1000) NULL,
 CONSTRAINT [pk_OneShieldPolicy] PRIMARY KEY CLUSTERED 
(
	[oneshield_policy_sk] ASC
)
) ON [PRIMARY]
GO

CREATE TABLE edw_stage.dragon_claim_os (
	claim_sk int,
	claim_no varchar(255) NULL,
	loss_dt date NULL,
	report_dt date NULL,
	policy_no varchar(255) NULL,
	policy_effective_dt date NULL,
	policy_sk int NULL,
	cause_of_loss_sk varchar(255) NULL,
	sub_cause_of_loss_sk int NULL,
	loss_desc nvarchar(max) NULL,
	claim_status varchar(255) NULL,
	source_claim_status varchar(255) NULL,
	catastrophe_sk varchar(255) NULL,
	product_sk int NULL,
	underwriting_company_nm varchar(255) NULL,
	loss_address varchar(255) NULL,
	loss_city_nm varchar(255) NULL,
	loss_state_nm varchar(255) NULL,
	loss_zip_cd varchar(255) NULL,
	loss_country_nm varchar(255) NULL,
	agencyid varchar(255),
	contact_nm varchar(255) NULL,
	contact_type varchar(255) NULL,
	contact_phone varchar(255) NULL,
	contact_person_email varchar(255) NULL,
	loss_reserve_amt decimal(15, 2) NULL,
	expense_reserve_amt decimal(15, 2) NULL,
	adjusting_other_reserve_amt decimal(15, 2) NULL,
	subro_reserve_amt decimal(15, 2) NULL,
	salvage_reserve_amt decimal(15, 2) NULL,
	salvage_expense_reserve_amt decimal(15, 2) NULL,
	subro_expense_reserve_amt decimal(15, 2) NULL,
	loss_paid_amt decimal(15, 2) NULL,
	expense_paid_amt decimal(15, 2) NULL,
	adjusting_other_paid_amt decimal(15, 2) NULL,
	subro_recovery_amt decimal(15, 2) NULL,
	salvage_recovery_amt decimal(15, 2) NULL,
	salvage_expense_paid_amt decimal(15, 2) NULL,
	subro_expense_paid_amt decimal(15, 2) NULL,
	refund_indemnity_paid_amt decimal(15, 2) NULL,
	refund_expense_paid_amt decimal(15, 2) NULL ,
	source_system_sk int
)
GO

CREATE TABLE edw_stage.dragon_feature_os (
  claim_feature_sk int,
  SUB_CLAIM_ID bigint NULL,
  claim_sk int NULL,
  claim_no varchar(255) null,
  subclaim_type_nm varchar(255),
  subclaim_seq_no varchar(255) NULL,
  claim_coverage_cd bigint NULL,
  claim_coverage_desc varchar(255),
  insured_name varchar(255),
  claimant_nm varchar(255) NULL,
  damage_severity varchar(255) NULL,
  damage_type varchar(255) NULL,
  possible_subrogation_in varchar(255),
  possible_salvage_in varchar(255),
  total_loss_in varchar(255) NULL,
  litigation_in varchar(255) NULL,
  product_sk int NULL,
  case_status varchar(255),
  aslob_sk int NULL,
  claim_adjuster_nm int NULL,
  loss_reserve_amt decimal(15, 2) NULL,
expense_reserve_amt decimal(15, 2) NULL,
adjusting_other_reserve_amt decimal(15, 2) NULL,
subro_reserve_amt decimal(15, 2) NULL,
salvage_reserve_amt decimal(15, 2) NULL,
salvage_expense_reserve_amt decimal(15, 2) NULL,
subro_expense_reserve_amt decimal(15, 2) NULL,
loss_paid_amt decimal(15, 2) NULL,
expense_paid_amt decimal(15, 2) NULL,
adjusting_other_paid_amt decimal(15, 2) NULL,
subro_recovery_amt decimal(15, 2) NULL,
salvage_recovery_amt decimal(15, 2) NULL,
salvage_expense_paid_amt decimal(15, 2) NULL,
subro_expense_paid_amt decimal(15, 2) NULL,
refund_indemnity_paid_amt decimal(15, 2) NULL,
refund_expense_paid_amt decimal(15, 2) NULL ,
  source_system_sk bigint NULL,
  create_ts datetime NULL,
  update_ts datetime NULL,
  join_key varchar(1000)
)
GO

CREATE TABLE edw_stage.dragon_claim_transaction_os (
	claim_transaction_sk int NULL,
	claim_sk int NULL,
	Claim_Number varchar(255),
	claim_feature_sk int NULL,
	SUBCLAIM_TRX_ID bigint NULL,
	product_sk int NULL,
	defense_cost_in varchar(255),
	transaction_date_sk int NULL,
	transaction_ts datetime NULL,
	claim_transaction_type_sk int NULL,
	feature_status_sk int NULL,
	loss_reserve_amt decimal(15, 2) NULL,
	expense_reserve_amt decimal(15, 2) NULL,
	adjusting_other_reserve_amt decimal(15, 2) NULL,
	subro_reserve_amt decimal(15, 2) NULL,
	salvage_reserve_amt decimal(15, 2) NULL,
	salvage_expense_reserve_amt decimal(15, 2) NULL,
	subro_expense_reserve_amt decimal(15, 2) NULL,
	loss_paid_amt decimal(15, 2) NULL,
	expense_paid_amt decimal(15, 2) NULL,
	adjusting_other_paid_amt decimal(15, 2) NULL,
	subro_recovery_amt decimal(15, 2) NULL,
	salvage_recovery_amt decimal(15, 2) NULL,
	salvage_expense_paid_amt decimal(15, 2) NULL,
	subro_expense_paid_amt decimal(15, 2) NULL,
	refund_indemnity_paid_amt decimal(15, 2) NULL,
	refund_expense_paid_amt decimal(15, 2) NULL ,
	source_system_sk int NULL,
	create_ts datetime NULL,
	update_ts datetime NULL,
	join_key varchar(1000)
)
GO