CREATE TABLE edw_stage.nfp_policy (
  reporting_month datetime NULL,
  group_name text,
  policy_no varchar(255),
  insured_cert_no varchar(255),
  risk_state varchar(100),
  insured_first_name varchar(255),
  insured_last_name varchar(255),
  insured_spouse_first_name varchar(255),
  insured_spouse_last_name varchar(255),
  address1 varchar(500),
  address2 varchar(500),
  city varchar(255),
  [state] varchar(255),
  zip varchar(50),
  enroll_date datetime NULL,
  effective_date datetime NULL,
  expiration_date datetime NULL,
  transaction_date date,
  transaction_type text,
  surplus_line_lic_no text,
  program_administrator_fees_no decimal(18,2) NULL,
  surplus_lines_tax decimal(18,2) NULL,
  total_collected decimal(18,2) NULL,
  written_prem_without_tax decimal(18,2) NULL,
  nfppc_commission decimal(18,2) NULL,
  net_premium decimal(18,2) NULL,
  surcharged_premium text,
  group_excess_liability_coverage decimal(18,2) NULL,
  group_excess_liability_coverage_premium decimal(18,2) NULL,
  uninsured_motorist_liability_coverage decimal(18,2) NULL,
  uninsured_motorist_liability_premium decimal(18,2) NULL,
  employment_practises_liability_coverage text,
  employment_practises_liability_premium decimal(18,2) NULL,
  [non_profit_d&o_liability_coverage] text,
  [non_profit_d&o_liability_premium] decimal(18,2) NULL,
  family_trust_management_liability_coverage decimal(18,2) NULL,
  family_trust_management_liability_premium decimal(18,2) NULL,
  number_of_residences decimal(18,2) NULL,
  number_of_vehicles decimal(18,2) NULL,
  number_of_drivers_under_22 decimal(18,2) NULL,
  number_of_drivers_from_22_to_75 decimal(18,2) NULL,
  number_of_drivers_76_and_older decimal(18,2) NULL,
  underlying_auto_liability_limit text,
  underlying_home_liability_limit decimal(18,2) NULL,
  underlying_watercraft_liability_limit decimal(18,2) NULL,
  underinsured_liability_limit text,
  nfp_program_sharing_funding decimal(18,2) NULL,
  vault_fronting_fees_xol_cc_collected decimal(18,2) NULL,
  qs_cc_collected decimal(18,2) NULL,
  total_cc_collected decimal(18,2) NULL,
  nfp_commission_paid decimal(18,2) NULL,
  vault_cc_override_after_expenses decimal(18,2) NULL,
  vault_fronting_fees decimal(18,2) NULL,
  add_fee_income_due decimal(18,2) NULL,
  vault_prem_w_profitshare_frontfees decimal(18,2) NULL,
  risk_group text,
  create_ts datetime,
  update_ts datetime,
  product_type varchar(255),
  product_nm varchar(255)
);