
CREATE TABLE edw_integration.customer_broker_livevox_feed 
( 
ID   varchar(255),
[Address_1]   varchar(255),
[Address_2]   varchar(255),
City   varchar(255),
State   varchar(255),
[Zip_Code]   varchar(255),
[Do_Not_Contact]   varchar(255),
[Email_Address]   varchar(255),
[First_Name]   varchar(255),
[Last_Name]   varchar(255),
DOB   date, -- Not sure if we want to make this date
[Payment_Balance]   varchar(255),
[Phone_1]   varchar(255),
[Phone_1_SMS_Consent]   varchar(255),
[Phone_2]   varchar(255),
[Phone_2_SMS_Consent]   varchar(255),
[Email_Consent]   varchar(255),
SMS   varchar(255),
[Legal_Entity_Name]   varchar(255),
[Brokerage_Type]   varchar(255),
[Broker_Name_Agent_Name]   varchar(255),
[Broker_Title_Status]   varchar(255),
[Broker_Phone]   varchar(255),
[Broker_Email]   varchar(255),
VIP   varchar(255),
Policy_1   varchar(255),
Location_1   varchar(255),
Effective_Date_1   date,
Expiration_Date_1   date,
Status_1   varchar(255),
Agency_Code_1   varchar(255),
Legal_Entity_Name_1   varchar(255),
Policy_2   varchar(255),
Location_2   varchar(255),
Effective_Date_2   date,
Expiration_Date_2   date,
Status_2   varchar(255),
Agency_Code_2   varchar(255),
Legal_Entity_Name_2   varchar(255),
Policy_3   varchar(255),
Location_3   varchar(255),
Effective_Date_3   date,
Expiration_Date_3   date,
Status_3   varchar(255),
Agency_Code_3   varchar(255),
Legal_Entity_Name_3   varchar(255),
Policy_4   varchar(255),
Location_4   varchar(255),
Effective_Date_4   date,
Expiration_Date_4   date,
Status_4   varchar(255),
Agency_Code_4   varchar(255),
Legal_Entity_Name_4   varchar(255),
[Contact_Type]   varchar(255),
create_ts datetime ,
update_ts datetime ,
etl_audit_sk int,
CONSTRAINT pk_customer_broker_livevox_feed PRIMARY KEY (ID)
);

INSERT INTO	edw_integration.tintegration_table_detail(table_nm,	table_type,	table_desc,	load_method,load_type,	load_frequency,	create_ts,	update_ts)
VALUES ('customer_broker_livevox_feed','Feed','This table provides customer, broker and policy details to support LiveVox phone system','Stored Procedure','Full Load','Daily',getdate(),getdate());
