CREATE TABLE edw_core.tquote_collection_location 
(
	quote_collection_location_sk int IDENTITY(1,1) NOT NULL,
	quote_no varchar(255) NOT NULL,
	effective_dt date NOT NULL,
	address_line_1 varchar(255) ,
	address_line_2 varchar(255) ,
	unit_no varchar(255) ,
	city_nm varchar(255) ,
	state_cd varchar(255) ,
	zip_cd varchar(255) ,
	county_nm varchar(255) ,
	country_nm varchar(255) ,
	longitude varchar(255) ,
	latitude varchar(255) ,
	source_system_sk int NULL,
	create_ts datetime NULL,
	update_ts datetime NULL,
	etl_audit_sk int NULL,
	CONSTRAINT pk_tquote_collection_location PRIMARY KEY (quote_collection_location_sk),
	CONSTRAINT uidx_tquote_collection_location_quote_no UNIQUE (quote_no)
);


INSERT INTO edw_core.tedw_table_detail(table_nm,table_type,table_category_nm,domain_nm,load_method,load_type,load_frequency,create_ts,update_ts) 
    VALUES ('tquote_collection_location','Type-1 Dimension','Base','Collections','Stored Procedure','Insert/Update','Daily',getdate(),getdate());

CREATE TABLE edw_core.tquote_collection_coverage (
	quote_collection_coverage_sk int IDENTITY(1,1) NOT NULL,
	quote_no varchar(255) NOT NULL,
	effective_dt date NOT NULL,
	expiration_dt date NOT NULL,
	transaction_seq_no int NOT NULL,
	quote_collection_location_sk int NOT NULL,
	quote_history_sk int NOT NULL,
	unoccupied_more_than_three_months_in varchar(255) ,
	valuable_article_losses_last3_years_ct int NULL,
	protection_class varchar(255) ,
	terrain_cd varchar(255) ,
	distance_to_coast varchar(255) ,
	roof_geometry varchar(255) ,
	roof_covering varchar(255) ,
	roof_cover_deck varchar(255) ,
	roof_deck_Attachment varchar(255) ,
	roof_wall_Attachment varchar(255) ,
	hail_resistant_rating varchar(255) ,
	secondary_water_resistance varchar(255) ,
	construction_type varchar(255) ,
	built_year int NULL,
	fire_protection varchar(255) ,
	opening_protection varchar(255) ,
	no_of_stories varchar(255) ,
	central_reporting_fire_alarm_in varchar(255) ,
	central_reporting_burglar_alarm_in varchar(255) ,
	home_safe_in varchar(255) ,
	fulltime_live_in_caretaker_in varchar(255) ,
	backup_generator_in varchar(255) ,
	residential_sprinkler_system_in varchar(255) ,
	market_value_scheduled_items_coverage_in varchar(255) ,
	bank_vaulted_jewelry_coverage_in varchar(255) ,
	coins_coverage_in varchar(255) ,
	collectibles_coverage_in varchar(255) ,
	fine_arts_coverage_in varchar(255) ,
	furs_coverage_in varchar(255) ,
	guns_coverage_in varchar(255) ,
	jewelry_coverage_in varchar(255) ,
	miscellaneous_coverage_in varchar(255) ,
	musical_instruments_coverage_in varchar(255) ,
	silver_coverage_in varchar(255) ,
	stamps_coverage_in varchar(255) ,
	wearable_collectibles_coverage_in varchar(255) ,
	wine_coverage_in varchar(255) ,
	minimum_earned_premium_endorsement_in varchar(255) ,
	minimum_earned_premium_endorsement_limit_pc float NULL,
	wardrobe_loss_prevention_in varchar(255) ,
	companion_credit_homeowner_in varchar(255) ,
	agreed_value_limitations_in varchar(255) ,
	agreed_value_specified_class_limitations_in varchar(255) ,
	agreed_value_specified_class_bank_vaulted_jewelry_limitations_in varchar(255) ,
	agreed_value_specified_class_coins_limitations_in varchar(255) ,
	agreed_value_specified_class_collectibles_limitations_in varchar(255) ,
	agreed_value_specified_class_fine_arts_limitations_in varchar(255) ,
	agreed_value_specified_class_furs_limitations_in varchar(255) ,
	agreed_value_specified_class_guns_limitations_in varchar(255) ,
	agreed_value_specified_class_worldwide_jewelry_limitations_in varchar(255) ,
	agreed_value_specified_class_miscellaneous_limitations_in varchar(255) ,
	agreed_value_specified_class_musicalInstruments_limitations_in varchar(255) ,
	agreed_value_specified_class_silver_limitations_in varchar(255) ,
	agreed_value_specified_class_stamps_limitations_in varchar(255) ,
	agreed_value_specified_class_wearable_collectibles_limitations_in varchar(255) ,
	agreed_value_specified_class_wine_limitations_in varchar(255) ,
	agreed_value_specified_items_limitations_in varchar(255) ,
	alarm_warranty_limitations_in varchar(255) ,
	breakage_exclusion_limitations_in varchar(255) ,
	terrorism_limitations_in varchar(255) ,
	Terrorism_limitations_amt varchar(255) ,
	theft_mysterious_disappearance_exclusion_in varchar(255) ,
	transit_limit_in varchar(255) ,
	transit_limit_amt varchar(255) ,
	hurricane_loss_exclusion_in varchar(255) ,
	hurricane_loss_limitation_in varchar(255) ,
	hurricane_loss_limitation_amt varchar(255) ,
	outdoor_fine_art_hurricane_exclusion_in varchar(255) ,
	terrorism_exclusion_in varchar(255) ,
	deletion_of_cosmetic_marring_exclusion_in varchar(255) ,
	earthquake_exclusion_in varchar(255) ,
	earthquake_deductible_loss_limitations_in varchar(255) ,
	earthquake_deductible_loss_limitations_limit varchar(255) ,
	hotel_motel_exclusion_in varchar(255) ,
	jewelry_off_premises_loss_limitation_in varchar(255) ,
	spoilage_exclusion_in varchar(255) ,
	change_in_terms_summary_in varchar(255) ,
	change_in_terms_options nvarchar(MAX) ,
	manuscript_in varchar(255) ,
	coverage_deductible_in varchar(255) ,
	coverage_deductible_amt varchar(255) ,
	hurricane_deductible_in varchar(255) ,
	hurricane_deductible_type varchar(255) ,
	hurricane_deductible_amt varchar(255) ,
	earthquake_deductible_in varchar(255) ,
	earthquake_deductible_amt varchar(255) ,
	wildfire_deductible_in varchar(255) ,
	wildfire_deductible_type varchar(255) ,
	wildfire_deductible_amt varchar(255) ,
	wildfire_bark_mulch_within_ten_feet_of_any_structure_in varchar(255) ,
	wildfire_combustible_deck_or_attached_structure_in varchar(255) ,
	wildfire_combustible_wood_siding_in varchar(255) ,
	wildfire_defensible_space_in varchar(255) ,
	wildfire_distance_to_high_fuel_feet varchar(255) ,
	wildfire_distance_to_moderate_fuel_feet varchar(255) ,
	wildfire_distance_to_very_high_fuel_feet varchar(255) ,
	wildfire_eaves_or_enclosed_eaves_in varchar(255) ,
	wildfire_exteriorWildfireSprinklers_in varchar(255) ,
	wildfire_firewood_or_combustibles_stored_against_home_in varchar(255) ,
	wildfire_flammable_vegetation_within_ten_feet_of_any_structure_in varchar(255) ,
	wildfire_gutter_guards_in varchar(255) ,
	wildfire_hazard_severity varchar(255) ,
	wildfire_nearest_distance_to_perimeter varchar(255) ,
	wildfire_no_of_occurrences_near varchar(255) ,
	wildfire_no_of_occurrences varchar(255) ,
	wildfire_permanently_installed_spray_system_in varchar(255) ,
	wildfire_portable_fire_break_system_in varchar(255) ,
	wildfire_speciality_ember_resistant_venting_in varchar(255) ,
	wildfire_threat varchar(255) ,
	wildfire_wood_shake_or_shingle_roof_in varchar(255) ,
	couture_wearable_collectibles_class_in varchar(255) ,
	source_system_sk int NULL,
	create_ts datetime NULL,
	update_ts datetime NULL,
	etl_audit_sk int NULL,
	CONSTRAINT pk_tquote_collection_coverage PRIMARY KEY (quote_collection_coverage_sk),
	CONSTRAINT uidx_tquote_collection_coverage_qtno_effdt_transeq UNIQUE (quote_no,effective_dt,transaction_seq_no),
	CONSTRAINT fk_tquote_collection_coverage_location_sk FOREIGN KEY (quote_collection_location_sk) REFERENCES edw_core.tquote_collection_location(quote_collection_location_sk),
	CONSTRAINT fk_tquote_collection_coverage_quote_history_sk FOREIGN KEY (quote_history_sk) REFERENCES edw_core.tquote_history(quote_history_sk)
);


INSERT INTO edw_core.tedw_table_detail(table_nm,table_type,table_category_nm,domain_nm,load_method,load_type,load_frequency,create_ts,update_ts) 
    VALUES ('tquote_collection_coverage','Type-2 Dimension','Base','Collections','Stored Procedure','Insert','Daily',getdate(),getdate());

CREATE TABLE edw_core.tquote_collection_class_type (
	quote_collection_class_type_sk int IDENTITY(1,1) NOT NULL,
	quote_no varchar(255) NOT NULL,
	effective_dt date NOT NULL,
	expiration_dt date NOT NULL,
	transaction_seq_no int NOT NULL,
	quote_collection_location_sk int NOT NULL,
	quote_history_sk int NOT NULL,
	quote_home_coverage_sk int NULL,
	quote_collection_coverage_sk int NULL,
	class_type varchar(255) ,
	scheduled_limit_amt int NULL,
	scheduled_highest_value_limit_amt int NULL,
	blanket_limit_amt int NULL,
	blanket_highest_value_limit_amt int NULL,
	blanket_single_article_limit_amt int NULL,
	highest_value_scheduled_item_appraisal_dt date NULL,
	source_system_sk int NULL,
	create_ts datetime NULL,
	update_ts datetime NULL,
	etl_audit_sk int NULL,
	CONSTRAINT pk_tquote_collection_class_type PRIMARY KEY (quote_collection_class_type_sk),
	CONSTRAINT uidx_tquote_collection_class_type_quote_no_effective_dt_transeq_class UNIQUE (quote_no,effective_dt,transaction_seq_no,class_type),
	CONSTRAINT fk_tquote_collection_class_type_location_sk FOREIGN KEY (quote_collection_location_sk) REFERENCES edw_core.tquote_collection_location(quote_collection_location_sk),
	CONSTRAINT fk_tquote_collection_class_type_quote_history_sk FOREIGN KEY (quote_history_sk) REFERENCES edw_core.tquote_history(quote_history_sk),
	CONSTRAINT uidx_tquote_collection_class_type_collection_coverage_sk FOREIGN KEY (quote_collection_coverage_sk) REFERENCES edw_core.tquote_collection_coverage(quote_collection_coverage_sk)
);

INSERT INTO edw_core.tedw_table_detail(table_nm,table_type,table_category_nm,domain_nm,load_method,load_type,load_frequency,create_ts,update_ts) 
    VALUES ('tquote_collection_class_type','Type-2 Dimension','Base','Collections','Stored Procedure','Insert','Daily',getdate(),getdate());


CREATE TABLE edw_core.tquote_collection_scheduled_item (
	quote_collection_scheduled_item_sk int IDENTITY(1,1) NOT NULL,
	quote_no varchar(255) NOT NULL,
	effective_dt date NOT NULL,
	expiration_dt date NOT NULL,
	transaction_seq_no int NOT NULL,
	quote_history_sk int NOT NULL,
	quote_collection_class_type_sk int NOT NULL,
    scheduled_item_no int NOT NULL,
	item_desc nvarchar(max) ,
	coverage_limit_amt int NULL,
	schedule_on_file_in varchar(255) ,
	appraisal_dt date NULL,
	collector_car_in varchar(255) ,
	source_system_sk int NULL,
	create_ts datetime NULL,
	update_ts datetime NULL,
	etl_audit_sk int NULL,
	CONSTRAINT pk_tquote_collection_scheduled_item PRIMARY KEY (quote_collection_scheduled_item_sk),
	CONSTRAINT fk_tquote_collection_scheduled_item_collection_class_type_sk FOREIGN KEY (quote_collection_class_type_sk) REFERENCES edw_core.tquote_collection_class_type(quote_collection_class_type_sk),
	CONSTRAINT fk_tquote_collection_scheduled_item_quote_history_sk FOREIGN KEY (quote_history_sk) REFERENCES edw_core.tquote_history(quote_history_sk)
);


INSERT INTO edw_core.tedw_table_detail(table_nm,table_type,table_category_nm,domain_nm,load_method,load_type,load_frequency,create_ts,update_ts) 
    VALUES ('tquote_collection_scheduled_item','Type-2 Dimension','Base','Collections','Stored Procedure','Insert','Daily',getdate(),getdate());




