CREATE TABLE edw_core.tquote_home_location 
(
	quote_home_location_sk int IDENTITY(1,1) NOT NULL,
	quote_no varchar(255) NOT NULL,
	effective_dt date NOT NULL,
	address_line_1 varchar(255) ,
	address_line_2 varchar(255) ,
	unit_no varchar(255) ,
	city_nm varchar(255) ,
	state_cd varchar(255) ,
	zip_cd varchar(255) ,
	county_nm varchar(255) ,
	country_nm varchar(255) ,
	longitude varchar(255) ,
	latitude varchar(255) ,
	source_system_sk int NULL,
	create_ts datetime NULL,
	update_ts datetime NULL,
	etl_audit_sk int NULL,
	CONSTRAINT pk_tquote_home_location PRIMARY KEY (quote_home_location_sk),
	CONSTRAINT uidx_tquote_home_location_quote_no UNIQUE (quote_no)
);

INSERT INTO edw_core.tedw_table_detail(table_nm,table_type,table_category_nm,domain_nm,load_method,load_type,load_frequency,create_ts,update_ts) 
    VALUES ('tquote_home_location','Type-1 Dimension','Base','Home','Stored Procedure','Insert/Update','Daily',getdate(),getdate());


CREATE TABLE edw_core.tquote_home_coverage 
(
	quote_home_coverage_sk int IDENTITY(1,1) NOT NULL,
	quote_no varchar(255) NOT NULL,
	effective_dt date NOT NULL,
	expiration_dt date NOT NULL,
	transaction_seq_no int NOT NULL,
	quote_home_location_sk int NOT NULL,
	quote_history_sk int NOT NULL,
	residence_type varchar(255) ,
	dwelling_limit_amt int NULL,
	other_structures_limit_amt int NULL,
	contents_limit_amt int NULL,
	loss_of_use_limit_amt varchar(255) ,
	loss_of_use_option varchar(255) ,
	loss_of_use_pc varchar(255) ,
	personal_liability_limit_amt varchar(255) ,
	medical_payments_limit_amt int NULL,
	total_insured_value_amt int NULL,
	exclude_inflation_factor_in varchar(255) ,
	aop_deductible varchar(255) ,
	water_deductible varchar(255) ,
	hurricane_deductible varchar(255) ,
	hurricane_or_named_storm_deductible varchar(255) ,
	named_storm_deductible varchar(255) ,
	tornado_or_hailstorm_deductible varchar(255) ,
	wind_or_hailstorm_deductible varchar(255) ,
	wind_derived_deductible varchar(255) ,
	wildfire_deductible varchar(255) ,
	no_of_mortgagees int NULL,
	prior_claim_last5yr_in varchar(255) ,
	prior_nonwater_claim_ct int NULL,
	prior_water_claim_ct int NULL,
	rating_territory_cd varchar(255) ,
	distance_to_coast varchar(255) ,
	distance_to_shore varchar(255) ,
	within_500feet_from_shore_in varchar(255) ,
	distance_to_fire_hydrant_feet varchar(255) ,
	distance_to_fire_station_miles varchar(255) NULL,
	fire_protection varchar(255) ,
	occupancy_type varchar(255) ,
	protection_class varchar(255) ,
	earthquake_zone varchar(255) ,
	terrain_cd varchar(255) ,
	windborne_debris_region_in varchar(255) ,
	windpool_eligibility_in varchar(255) ,
	sinkhole_risk_level varchar(255) ,
	sinkhole_distance_to_nearest_miles varchar(255) NULL,
	total_finished_square_feet int NULL,
	construction_type varchar(255) ,
	basement_type varchar(255) ,
	active_renovation varchar(255) ,
	renovation_anticipated_completion_dt date NULL,
	ulstandard varchar(255) ,
	unit_floor varchar(255) ,
	built_year int NULL,
	electrical_updated_year int NULL,
	hvac_updated_year int NULL,
	plumbing_updated_year int NULL,
	roof_updated_year int NULL,
	no_of_stories varchar(255) ,
	shear_wave_velocity varchar(255) ,
	barn_on_property_in varchar(255) ,
	barn_value_amt int NULL,
	bceg_cd varchar(255) ,
	bceg_credit_pc varchar(255) ,
	windspeed_of_design varchar(255) ,
	hail_resistant_rating_in varchar(255) ,
	hurricane_fortification_in varchar(255) ,
	mmi varchar(255) ,
	swimming_pool_in varchar(255) ,
	wildfire_score varchar(255) ,
	hazard_severity varchar(255) ,
	distance_to_very_high_fuel_feet varchar(255) ,
	distance_to_high_fuel_feet varchar(255) ,
	distance_to_moderate_fuel_feet varchar(255) ,
	no_of_wildfire_occurrences varchar(255) ,
	no_of_wildfire_near_occurrences varchar(255) ,
	nearest_distance_to_perimeter varchar(255) ,
	combustible_wood_siding_in varchar(255) ,
	combustible_deck_or_attached_structure_in varchar(255) ,
	firewood_or_combustibles_stored_against_home_in varchar(255) ,
	defensible_space_in varchar(255) ,
	woodshake_or_shingle_roof_in varchar(255) ,
	speciality_ember_resistant_venting_in varchar(255) ,
	exterior_wildfire_sprinklers_in varchar(255) ,
	eaves_or_enclosed_eaves_in varchar(255) ,
	permanently_installed_spray_system_in varchar(255) ,
	portable_fire_break_system_in varchar(255) ,
	gutter_guards_in varchar(255) ,
	bark_mulch_within_ten_feet_of_any_structure_in varchar(255) ,
	flammable_vegetation_within_ten_feet_of_any_structure_in varchar(255) ,
	opening_protection varchar(255) ,
	roof_cover_deck varchar(255) ,
	roof_covering varchar(255) ,
	roof_deck_attachment varchar(255) ,
	roof_geometry varchar(255) ,
	roof_system_in varchar(255) ,
	roof_wall_attachment varchar(255) ,
	solar_feature_desc varchar(255) ,
	secondary_water_resistance varchar(255) ,
	premium_adjustment_method  varchar(255),
premium_adjustment_factor  decimal(16,4),
premium_adjustment_retention   varchar(255),
premium_adjustment_retention_reason varchar(255),
reinsurance_designation nvarchar(max),
reinsurance_layered_program_in       varchar(255),
reinsurance_attachment_limit_amt  varchar(255),
reinsurance_total_tiv_amt  int,
loss_of_use_derived_pc    float,
wildfire_threat           varchar(255),
wildfire_hazard_severity  varchar(255),
	source_system_sk int NULL,
	create_ts datetime NULL,
	update_ts datetime NULL,
	etl_audit_sk int NULL,
	CONSTRAINT pk_tquote_home_coverage PRIMARY KEY (quote_home_coverage_sk),
	CONSTRAINT uidx_tquote_home_coverage_qtno_effdt_transeq UNIQUE (quote_no,effective_dt,transaction_seq_no),
	CONSTRAINT fk_tquote_home_coverage_location_sk FOREIGN KEY (quote_home_location_sk) REFERENCES edw_core.tquote_home_location(quote_home_location_sk),
    CONSTRAINT fk_tquote_home_coverage_quote_history_sk FOREIGN KEY (quote_history_sk) REFERENCES edw_core.tquote_history(quote_history_sk)
);

INSERT INTO edw_core.tedw_table_detail(table_nm,table_type,table_category_nm,domain_nm,load_method,load_type,load_frequency,create_ts,update_ts) 
    VALUES ('tquote_home_coverage','Type-2 Dimension','Base','Home','Stored Procedure','Insert','Daily',getdate(),getdate());


CREATE TABLE edw_core.tquote_home_additional_coverage (
	quote_home_additional_coverage_sk int IDENTITY(1,1) NOT NULL,
	quote_no varchar(255) NOT NULL,
	effective_dt date NOT NULL,
	expiration_dt date NOT NULL,
	transaction_seq_no int NOT NULL,
	quote_home_location_sk int NOT NULL,
	quote_home_coverage_sk int NOT NULL,
	quote_history_sk int NOT NULL,
	central_reporting_fire_alarm_in varchar(255) ,
	central_reporting_burglar_alarm_in varchar(255) ,
	twentyfour_hour_doorman_in varchar(255) ,
	lobby_surveillance_camera_in varchar(255) ,
	locked_or_manned_elevators_in varchar(255) ,
	twentyfour_hour_signal_continuity_in varchar(255) ,
	guard_gated_community_in varchar(255) ,
	guard_community_patrol_service_in varchar(255) ,
	home_safe_in varchar(255) ,
	fulltime_live_in_caretaker_in varchar(255) ,
	gas_leak_detector_in varchar(255) ,
	lightning_protection_in varchar(255) ,
	low_temperature_monitoring_device_in varchar(255) ,
	backup_generator_in varchar(255) ,
	external_perimeter_gate_in varchar(255) ,
	external_perimeter_security varchar(255) ,
	water_leak_detection_system varchar(255) ,
	residential_sprinkler_system_in varchar(255) ,
	business_property_increase_in varchar(255) ,
	business_property_increase_limit_amt varchar(255) ,
	deductible_waiver_large_losses_in varchar(255) ,
	deductible_waiver_large_losses_limit_amt varchar(255) ,
	earthquake_coverage_extension_in varchar(255) ,
	earthquake_coverage_extension_deductible varchar(255) ,
	earthquake_coverage_extension_loss_assessment_in varchar(255) ,
	earthquake_coverage_extension_loss_assessment_limit_amt varchar(255) ,
	earthquake_earthmovement_exclusion_ind varchar(255) ,
	earthquake_score varchar(255) ,
	fungi_bacteria_increase_in varchar(255) ,
	fungi_bacteria_increase_limit varchar(255) ,
	fungi_bacteria_liability_extension_in varchar(255) ,
	home_systems_protection_in varchar(255) ,
	home_systems_protection_limit_amt varchar(255) ,
	increased_incidental_business_threshold_in varchar(255) ,
	increased_incidental_business_threshold_limit_amt varchar(255) ,
	increased_incidental_business_property_in varchar(255) ,
	increased_incidental_business_property_limit_amt varchar(255) ,
	landscaping_coverage_increased_limits_in varchar(255) ,
	landscaping_coverage_increased_plant_limit_amt varchar(255) ,
	landscaping_coverage_increased_aggregate_limit varchar(255) ,
	landscaping_coverage_sleet_and_weight_of_ice_and_snow_coverage_limit_amt varchar(255) ,
	landscaping_coverage_wind_and_hail_coverage_limit_amt varchar(255) ,
	law_ordinance_coverage_increase_in varchar(255) ,
	law_ordinance_coverage_increased_limit varchar(255) ,
	loss_assessment_increase_in varchar(255) ,
	loss_assessment_increase_limit_amt varchar(255) ,
	loss_assessment_increase_desc varchar(255) ,
	serviceline_protection_in varchar(255) ,
	thoroughbred_horse_liability_extension_in varchar(255) ,
	no_of_horses varchar(255) ,
	home_cyber_protection_coverage_in varchar(255) ,
	home_cyber_protection_coverage_deductible varchar(255) ,
	home_cyber_protection_coverage_limit_amt varchar(255) ,
	offpremises_other_permanent_structures_extension_in varchar(255) ,
	offpremises_other_permanent_structures_extension_desc nvarchar(MAX) ,
	agreed_value_in varchar(255) ,
	backup_of_sewers_limit_in varchar(255) ,
	contents_extended_replacement_cost_in varchar(255) ,
	coverage_for_piers_wharves_and_docks_due_to_weight_of_ice_or_snow_in varchar(255) ,
	coverage_for_piers_wharves_and_docks_due_to_weight_of_ice_or_snow_limit_amt varchar(255) ,
	damage_to_property_of_others_increased_limit_amt varchar(255) ,
	debris_removal_broadaned_tree_removal_in varchar(255) ,
	earthquake_endorsement_in varchar(255) ,
	earthquake_endorsement_deductible varchar(255) ,
	escaped_liquid_fuel_liability_limit_amt varchar(255) ,
	escaped_liquid_fuel_remediation_coverage_in varchar(255) ,
	escaped_liquid_fuel_remediation_liability_limit_amt varchar(255) ,
	escaped_liquid_fuel_remediation_risk_class_no varchar(255) ,
	fortified_roof_upgrade_in varchar(255) ,
	home_daycare_coverage_in varchar(255) ,
	home_daycare_coverage_limit_amt varchar(255) ,
	home_daycare_coverage_no_of_children varchar(255) ,
	identity_theft_in varchar(255) ,
	pollutants_or_contimination_extension_in varchar(255) ,
	pollutants_or_contimination_tankage varchar(255) ,
	pollutants_or_contimination_tank_construction varchar(255) ,
	pollutants_or_contimination_tank_location varchar(255) ,
	pollutants_or_contimination_tank_type varchar(255) ,
	residence_held_in_trust_in varchar(255) ,
	sinkhole_collapse_in varchar(255) ,
	sinkhole_coverage_extension_in varchar(255) ,
	sinkhole_territory varchar(255) ,
	supplemental_loss_assessment_coverage_in varchar(255) ,
	supplemental_loss_assessment_coverage_additional_locations varchar(255) ,
	supplemental_loss_assessment_coverage_premises varchar(255) ,
	workercompensation_liability_in varchar(255) ,
	workercompensation_liability_fulltime_employees_ct varchar(255) ,
	workercompensation_liability_occurance_limit_amt varchar(255) ,
	workercompensation_liability_parttime_employees_ct varchar(255) ,
	guaranteed_replacement_cost_in varchar(255) ,
	replacement_cost_coverage_in varchar(255) ,
	roof_covering_full_reconstruction_cost_coverage_in varchar(255) ,
	additional_replacement_cost_coverage_in varchar(255) ,
	additional_replacement_cost_coverage_with_wildfire_in varchar(255) ,
	dwelling_reconstruction_cost_coverage_in varchar(255) ,
	extended_replacement_cost_coverage_with_additional_wildfire_in varchar(255) ,
	extended_replacement_cost_coverage_with_wildfire_in varchar(255) ,
	extended_replacement_cost_coverage_in varchar(255) ,
	extended_replacement_cost_coverage_option varchar(255) ,
	extended_replacement_cost_coverage_with_additional_wildfire_plus_twentyfive_pc_in varchar(255) ,
	mine_subsidence_coverage_in varchar(255) ,
	mine_subsidence_coverage_limit_amt varchar(255) ,
	minimum_earned_premium_endorsement_in varchar(255) ,
	minimum_earned_premium_endorsement_limit_pct varchar(255) ,
	contents_off_premises_loss_exclusion_in varchar(255) ,
	premises_liability_limitation_in varchar(255) ,
	manuscript_in varchar(255) ,
	amended_settlement_basis_in varchar(255) ,
	additions_and_alterations_extended_replacement_cost_in varchar(255) ,
	change_in_terms_summary_in varchar(255) ,
	deletion_of_cosmetic_marring_exclusion_in varchar(255) ,
	exclude_wind_in varchar(255) ,
	wind_hail_exclusion_in varchar(255) ,
	roof_exclusion_in varchar(255) ,
	waterdamage_exclusion_in varchar(255) ,
	waterdamage_limitation_endorsement_in varchar(255) ,
	waterdamage_limitation_endorsement_limit_amt varchar(255) ,
	waterdamage_sublimit varchar(255) ,
	waterdamage_sublimit_amt varchar(255) ,
	underground_resources_exclusion_in varchar(255) ,
	underground_water_supplyline_exclusion_in varchar(255) ,
	named_structures_exclusion_in varchar(255) ,
	named_structures_exclusion_desc nvarchar(MAX) ,
	animal_related_liability_exclusion_in varchar(255) ,
	animal_related_liability_exclusion_desc nvarchar(MAX) ,
	libel_slander_exclusion_in varchar(255) ,
	political_activities_exclusion_in varchar(255) ,
	equine_related_liability_exclusion_in varchar(255) ,
	canine_liability_exclusion_in varchar(255) ,
	named_structures_property_and_liability_exclusion_in varchar(255) ,
	named_structures_property_and_liability_exclusion_desc nvarchar(MAX) ,
	specific_named_structures_property_and_liability_exclusion_in varchar(255) ,
	specific_named_structures_property_and_liability_exclusion_desc nvarchar(MAX) ,
	other_structures_away_from_the_residence_premises_in varchar(255) ,
	other_structures_away_from_the_residence_premises_desc nvarchar(MAX) ,
	other_structures_on_the_residence_premises_increased_limit_in varchar(255) ,
	other_structures_on_the_residence_premises_increased_limit_amt varchar(255) ,
	other_structures_on_the_residence_premises_increased_limit_desc nvarchar(MAX) ,
	extended_liability_in varchar(255) ,
	leed_certification_discount_in varchar(255),
mortgage_free_discount_in varchar(255),
annual_brush_removal_contract_in varchar(255),
firewise_community_credit_in varchar(255),
monitored_heat_sensors_in varchar(255),
builders_defect_exclusion_in varchar(255),
gated_community_patrol_service varchar(255),
	source_system_sk int NULL,
	create_ts datetime NULL,
	update_ts datetime NULL,
	etl_audit_sk int NULL,
	CONSTRAINT pk_tquote_home_additional_coverage PRIMARY KEY (quote_home_additional_coverage_sk),
	CONSTRAINT uidx_tquote_home_additional_coverage_qtno_effdt_transeq UNIQUE (quote_no,effective_dt,transaction_seq_no),
	CONSTRAINT fk_tquote_home_additional_coverage_coverage_sk FOREIGN KEY (quote_home_coverage_sk) REFERENCES edw_core.tquote_home_coverage(quote_home_coverage_sk),
    CONSTRAINT fk_tquote_home_additional_coverage_location_sk FOREIGN KEY (quote_home_location_sk) REFERENCES edw_core.tquote_home_location(quote_home_location_sk)
);


INSERT INTO edw_core.tedw_table_detail(table_nm,table_type,table_category_nm,domain_nm,load_method,load_type,load_frequency,create_ts,update_ts) 
    VALUES ('tquote_home_additional_coverage','Type-2 Dimension','Base','Home','Stored Procedure','Insert','Daily',getdate(),getdate());




select * from edw_core.tedw_table_detail
order by 1 desc
;