IF NOT EXISTS 
(
    SELECT 1
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'edw_stage'
      AND TABLE_NAME = 'dragon_fitem'
)
BEGIN
	CREATE TABLE [edw_stage].[dragon_fitem]
(
	[fitem_id] [decimal](12, 0) NOT NULL,
	[composite_search_key] [varchar](4000) NULL,
	[exchange_id] [decimal](38, 10) NULL,
	[debit_credit] [varchar](50) NULL,
	[category] [varchar](100) NULL,
	[sub_category] [varchar](100) NULL,
	[installment_number] [decimal](38, 10) NULL,
	[date_effective] [date] NULL,
	[balance] [decimal](38, 10) NULL,
	[fitem_currency] [varchar](100) NULL,
	[reporting_currency] [varchar](100) NULL,
	[due_amount_reporting_currency] [decimal](38, 10) NULL,
	[billing_status] [varchar](100) NULL,
	[date_billing_status] [date] NULL,
	[processing_status] [varchar](100) NULL,
	[billing_account_status] [varchar](100) NULL,
	[default_payment_profile] [varchar](200) NULL,
	[policy_no] [varchar](50) NULL,
	[customer_id] [decimal](38, 10) NULL,
	[policy_id] [decimal](38, 10) NULL,
	[policy_transaction_id] [decimal](38, 10) NULL,
	[partner_id] [decimal](38, 10) NULL,
	[user_id] [decimal](38, 10) NULL,
	[billing_account_id] [decimal](38, 10) NULL,
	[due_date] [date] NULL,
	[product_id] [decimal](12, 0) NULL,
	[billing_account_number] [varchar](100) NULL,
	[priority] [decimal](38, 10) NULL,
	[entity_id] [decimal](38, 10) NULL,
	[fitem_category_id] [decimal](38, 10) NULL,
	[fitem_sub_category_id] [decimal](38, 10) NULL,
	[generic_instance_number] [decimal](38, 10) NULL,
	[creation_date] [varchar](20) NULL,
	[policy_effective_date] [date] NULL,
	[fitem_billed_tf] [char](1) NULL,
	[fitem_billed_date] [date] NULL,
	[agency_due_date] [date] NULL,
	[initial_amount] [decimal](38, 10) NULL,
	[aging_status_id] [decimal](38, 10) NULL,
	[aging_status] [varchar](100) NULL,
	[aging_status_change_date] [date] NULL,
	[fitem_type_id] [decimal](38, 10) NULL,
	[policy_term_id] [decimal](38, 10) NULL,
	[actual_due_date] [date] NULL,
	[cash_associated_with] [decimal](38, 10) NULL,
	[earned_amount] [decimal](38, 10) NULL,
	[unearned_amount] [decimal](38, 10) NULL,
	[earning_status] [varchar](100) NULL,
	[paid_amount] [decimal](38, 10) NULL,
	[cash_payment_details] [varchar](200) NULL,
	[cash_payment_type] [varchar](100) NULL,
	[creator_fitransactionset_id] [decimal](38, 10) NULL,
	[batch_security_status] [varchar](100) NULL,
	[fitem_transaction_type_id] [decimal](38, 10) NULL,
	[fitem_batch_type_name] [varchar](100) NULL,
	[account_holder_name] [varchar](200) NULL,
	[fitem_batch_creation_date] [date] NULL,
	[fitem_batch_creator] [varchar](100) NULL,
	[insured_name] [varchar](200) NULL,
	[fitem_security_status] [decimal](38, 0) NULL,
	[fitem_asset_name] [varchar](500) NULL,
	[disbursement_batch_id] [decimal](38, 10) NULL,
	[creator_fitransaction_id] [decimal](38, 10) NULL,
	[billing_element_md_id] [decimal](12, 0) NULL,
	[accounting_period] [varchar](100) NULL,
	[withdrawal_date] [date] NULL,
	[fitem_detail] [varchar](200) NULL,
	[policy_transaction_number] [decimal](38, 10) NULL,
	[policy_trx_object_state] [decimal](38, 10) NULL,
	[policy_trx_type] [varchar](100) NULL,
	[commission_pct] [decimal](12, 2) NULL,
	[fitem_allocation_id] [decimal](38, 10) NULL,
	[current_recon_batch_id] [decimal](38, 10) NULL,
	[policy_trx_generic_instance] [decimal](38, 10) NULL,
	[policy_trx_seq_num] [decimal](38, 10) NULL,
	[policy_trx_rf_seq] [decimal](38, 10) NULL,
	[policy_trx_rb_seq] [decimal](38, 10) NULL,
	[fitem_last_upt_date] [date] NULL,
	[fitem_object_state_id] [decimal](12, 0) NULL,
	[cash_associated_with_details] [varchar](100) NULL,
	[object_source_desc] [varchar](30) NULL,
	[legacy_object_id] [decimal](12, 0) NULL,
	[legacy_id] [varchar](100) NULL,
	[legacy_installment_num] [decimal](38, 10) NULL,
	[legacy_fitem_id] [decimal](12, 0) NULL,
	[related_recon_batch_id] [decimal](38, 10) NULL,
	[aging_status_days_id] [decimal](38, 10) NULL,
	[aging_status_days] [varchar](100) NULL,
	[recon_id] [varchar](100) NULL,
	[fitem_ultimate_object_id] [decimal](38, 10) NULL,
	[policy_cpa] [decimal](38, 10) NULL,
	[fitem_batch_type_id] [decimal](38, 10) NULL,
	[policy_trx_type_id] [decimal](38, 10) NULL,
	[ult_parent_account_id] [decimal](12, 0) NULL,
	[ult_parent_account_name] [varchar](100) NULL,
	[installment_id] [decimal](38, 10) NULL,
	[object_source] [decimal](12, 0) NULL,
	[policy_trx_sub_type_id] [decimal](12, 0) NULL,
	[fitem_asset_id] [decimal](38, 10) NULL,
 CONSTRAINT [pk_dragon_fitem] PRIMARY KEY ([fitem_id])
 );
END


