ALTER TABLE edw_stage.t_clm_object ADD ASSIGNMENT_OF_BENEFITS_CONTRACTOR varchar(10);
ALTER TABLE edw_stage.t_clm_object ADD PUBLIC_ADJUSTER varchar(10);
ALTER TABLE edw_stage.t_clm_object ADD ARBITRATION varchar(10);
ALTER TABLE edw_stage.t_clm_object ADD MEDIATION varchar(10);
ALTER TABLE edw_stage.t_clm_object ADD APPRAISAL varchar(10);
ALTER TABLE edw_stage.t_clm_object ADD ALTERNATIVE_DISPUTE_RESOLUTION varchar(10);
ALTER TABLE edw_stage.t_clm_object ADD NEUTRAL_EVALUATION varchar(10);
ALTER TABLE edw_stage.t_clm_object ADD SETTLEMENT_CONFERENCE varchar(10);
ALTER TABLE edw_stage.t_clm_object ADD SETTLEMENT_RESOLUTION varchar(10);

CREATE TABLE edw_stage.t_clm_litigation (
  SUIT_ID decimal(19,0) NOT NULL,
  CASE_ID decimal(19,0) NOT NULL,
  SUIT_NAME text NOT NULL,
  SUIT_TYPE varchar(10)  NOT NULL,
  OBJECT_ID decimal(19,0) NOT NULL,
  SUIT_STATUS varchar(10)  NOT NULL,
  SUIT_STATUS_REMARK text ,
  SUIT_CASE_NUMBER text ,
  SUIT_OPEN_DATE datetime DEFAULT NULL,
  AMOUNT_APEALED decimal(20,2) DEFAULT NULL,
  AMTAPE_CURCODE varchar(5)  DEFAULT NULL,
  SUIT_LOCATION text ,
  LAWYER_NAME text ,
  LAWYER_TEL text ,
  LAWYER_EMAIL text ,
  SUIT_CLOSE_DATE datetime DEFAULT NULL,
  DEPOSITION_AMOUNT decimal(20,2) DEFAULT NULL,
  DEPAMT_CURCODE varchar(5)  DEFAULT NULL,
  INSERT_BY decimal(19,0) NOT NULL,
  INSERT_TIME datetime DEFAULT NULL,
  UPDATE_BY decimal(19,0) NOT NULL,
  UPDATE_TIME datetime DEFAULT NULL,
  BUSINESS_OBJECT_ID decimal(10,0) DEFAULT NULL,
  DYNAMIC_FIELDS text ,
  LIABILITY_PERCENTAGE_ON_INSURED decimal(20,2) DEFAULT NULL,
  ESTIMATED_FULL_PROCEEDING_LITIGATION_AWARD_AND_COST decimal(20,2) DEFAULT NULL,
  TOTAL_SAVINGS decimal(20,2) DEFAULT NULL,
  COVERAGE_COUNSEL_APPOINTED_DATE datetime DEFAULT NULL,
  PROACTIVE_THIRD_PARTY_CLAIM_ACTIVATION_DATE datetime DEFAULT NULL,
  AW_COVERAGE_COUNSEL_NAME text ,
  TP_CLAIM_SETTLED_STAGE varchar(50)  DEFAULT NULL,
  AW_APPOINT_COVERAGE_COUNSEL varchar(10)  DEFAULT NULL,
  PROACTIVE_TP_CLAIMS_ACTIVATION varchar(10)  DEFAULT NULL,
  PROACTIVE_TP_CLAIMS_SUCCESS varchar(10)  DEFAULT NULL,
  TP_CLAIMANT_REPRESENTATIVE_TYPE varchar(10)  DEFAULT NULL,
  MEDIATION_SUCCESSFUL varchar(50)  DEFAULT NULL,
  NAME_OF_MEDIATOR varchar(140)  DEFAULT NULL,
  DATE_OF_MEDIATION datetime DEFAULT NULL,
  MEDIATION_ENGAGED varchar(50)  DEFAULT NULL,
  AW_DEFENSE_LAW_FIRM_ID decimal(19,0) DEFAULT NULL,
  AW_DEFENSE_LAW_FIRM_NAME varchar(140)  DEFAULT NULL,
  AW_COVERAGE_LAW_FIRM_ID decimal(19,0) DEFAULT NULL,
  AW_COVERAGE_LAW_FIRM_NAME varchar(140)  DEFAULT NULL,
  TP_CLAIMANT_LAW_FIRM_ID decimal(19,0) DEFAULT NULL,
  TP_CLAIMANT_LAW_FIRM_NAME varchar(140)  DEFAULT NULL,
  TP_CLAIMANT_LEGAL_PROCEEDING_ISSUED varchar(10)  DEFAULT NULL,
  AW_APPOINT_DEFENCE_COUNSEL varchar(10)  DEFAULT NULL,
  DATE_OF_DEFENCE_LAYER_APP datetime DEFAULT NULL,
  TP_DATE_OF_SUIT_SERVED datetime DEFAULT NULL,
  AW_DEFENCE_COUNSEL_NAME varchar(140)  DEFAULT NULL,
  TP_DATE_OF_LETTER_OF_DEMAND datetime DEFAULT NULL,
  PRIMARY KEY (SUIT_ID)
);