CREATE TABLE edw_core.tquote_auto_vehicle_coverage_rapa (
	quote_auto_vehicle_coverage_rapa_sk int identity(1,1) not null,
	quote_no varchar(255) ,
	effective_dt date NOT NULL,
	vehicle_no int NOT NULL,
	expiration_dt date NOT NULL,
	transaction_seq_no int NOT NULL,
	quote_history_sk int NOT NULL,
	quote_auto_vehicle_sk int NOT NULL,
	quote_auto_vehicle_coverage_sk int not null ,
	bodily_injury_char1_relativity varchar(255),
	property_damage_char1_relativity varchar(255),
	medical_payments_char1_relativity varchar(255), 
	personal_injury_protection_char1_relativity varchar(255),
	collision_char1_relativity varchar(255), 
	comprehensive_char1_relativity varchar(255), 
	single_limit_char1_relativity varchar(255), 
	bodily_injury_char2_relativity varchar(255), 
	property_damage_char2_relativity varchar(255), 
	medical_payments_char2_relativity varchar(255), 
	personal_injury_protection_char2_relativity varchar(255),  
	collision_char2_relativity varchar(255), 
	comprehensive_char2_relativity varchar(255), 
	single_limit_char2_relativity varchar(255), 
	bodily_injury_indicated_symbol varchar(255),
	property_damage_indicated_symbol varchar(255),
	medical_payments_indicated_symbol varchar(255),
	personal_injury_protection_indicated_symbol varchar(255),
	collision_indicated_symbol varchar(255),
	comprehensive_indicated_symbol varchar(255),
	single_limit_indicated_symbol varchar(255),
	bodily_injury_relativity varchar(255),
	property_damage_relativity varchar(255),
	medical_payments_relativity varchar(255),
	personal_injury_protection_relativity varchar(255),
	collision_relativity varchar(255),
	comprehensive_relativity varchar(255),
	single_limit_relativity varchar(255),
	comprehensive_non_glass_relativity_char1 varchar(255),
	comprehensive_non_glass_relativity_char2 varchar(255),
	comprehensive_non_glass_indicated_symbol varchar(255),
	comprehensive_non_glass_symbol_relativity varchar(255),
	bodily_injury_rating_symbol_relativity varchar(255),
	bodily_injury_symbol varchar(255),
	property_damage_rating_symbol_relativity varchar(255),
	property_damage_symbol varchar(255),
	medical_payments_rating_symbol_relativity varchar(255),
	medical_payments_symbol varchar(255),
	personal_injury_protection_rating_symbol_relativity varchar(255),
	personal_injury_protection_symbol varchar(255),
	collision_rating_symbol_relativity varchar(255),
	collision_symbol varchar(255),
	comprehensive_rating_symbol_relativity varchar(255),
	comprehensive_symbol varchar(255),
	single_limit_rating_symbol_relativity varchar(255),
	single_limit_symbol varchar(255),
	comprehensive_non_glass_rating_symbol_relativity varchar(255),
	comprehensive_non_glass_symbol varchar(255),
	bodily_injury_symbol_capping_in varchar(255),
	property_damage_symbol_capping_in varchar(255),
	medical_payments_symbol_capping_in varchar(255),
	personal_injury_protection_symbol_capping_in varchar(255),
	collision_symbol_capping_in varchar(255),
	comprehensive_symbol_capping_in varchar(255),
	single_limit_symbol_capping_in varchar(255),
	comprehensive_non_glass_symbol_capping_in varchar(255),
	vehicle_unique_id varchar(255),
	source_system_sk int ,
	create_ts datetime ,
	update_ts datetime ,
	etl_audit_sk int ,
	CONSTRAINT pk_tquote_auto_vehicle_coverage_rapa PRIMARY KEY (quote_auto_vehicle_coverage_rapa_sk),
	CONSTRAINT uidx_tquote_auto_vehicle_coverage_rapa_qtno_effdt_vehno_transeq UNIQUE (quote_no,effective_dt,vehicle_no,transaction_seq_no),
	CONSTRAINT fk_tquote_auto_vehicle_coverage_rapa_auto_vehicle_sk FOREIGN KEY (quote_auto_vehicle_sk) REFERENCES vault_edw.edw_core.tquote_auto_vehicle(quote_auto_vehicle_sk),
	CONSTRAINT fk_tquote_auto_vehicle_coverage_rapa_quote_history_sk FOREIGN KEY (quote_history_sk) REFERENCES vault_edw.edw_core.tquote_history(quote_history_sk)
);

INSERT INTO edw_core.tedw_table_detail(table_nm,table_type,table_category_nm,domain_nm,load_method,load_type,load_frequency,create_ts,update_ts) 
    VALUES ('tquote_auto_vehicle_coverage_rapa','Type-2 Dimension','Base','Auto','Stored Procedure','Insert','Daily',getdate(),getdate());