CREATE TABLE edw_integration.quote_hubspot_feed
( 
quote_no  varchar(255) NOT NULL ,  
effective_dt DATE , 
expiration_dt DATE , 
transaction_type varchar(255) , 
broker_id varchar(255) NOT NULL, 
broker_nm varchar(255) ,
broker_tier varchar(255) , 
national_agency_in varchar(255), 
bdm_nm varchar(255), 
vip_in varchar(255), 
insured_first_nm varchar(255), 
insured_last_nm varchar(255), 
underwriter_nm varchar(255), 
uw_company_nm varchar(255) ,
risk_address_line_1 varchar(255) ,   
risk_address_line_2 varchar(255) , 
risk_city_nm varchar(255) , 
risk_state_cd varchar(255) , 
risk_zip_cd varchar(255) , 
premium_amt decimal(15,2) , 
quote_status varchar(255) , 
claim_ct  int , 
note_desc varchar(255) , 
recampaign_in varchar(255) , 
rol_on_lost_business varchar(255), 
lost_company varchar(255) , 
reason_quote_not_taken varchar(255), 
construction varchar(255) , 
dwelling_limit_amt int, 
contents_limit_amt int, 
other_structures_limit_amt int, 
loss_of_use_limit_amt varchar(255), 
total_insured_value_amt int, 
roof_covering varchar(255) , 
roof_updated_year int , 
insurance_score varchar(255) , 
auto_liability_limit_amt varchar(255) , 
pel_limit_amt int, 
collections_coverage_type varchar(255), 
total_blanket_limit_amt int, 
total_scheduled_limit_amt int,
create_ts datetime NOT NULL,
update_ts datetime NOT NULL,
etl_audit_sk int NOT NULL, 
CONSTRAINT pk_quote_hubspot_feed PRIMARY KEY(quote_no)
); 

INSERT INTO	edw_integration.tintegration_table_detail(table_nm,	table_type,	table_desc,	load_method, load_type,load_frequency,create_ts,update_ts)
VALUES ('quote_hubspot_feed','Feed','This table provides quote data to Hubspot','Stored Procedure','Insert/Update','Daily',getdate(),getdate());