CREATE TABLE edw_integration.broker_hubspot_feed
( 
broker_id varchar(255) NOT NULL, 
broker_nm varchar(255), 
mailing_address_line_1 varchar(255), 
mailing_address_line_2 varchar(255), 
mailing_address_city_nm varchar(255), 
mailing_address_state_nm varchar(255), 
mailing_address_zip_cd varchar(255), 
broker_tier int, 
broker_tier_nm varchar(255), 
national_agency_in varchar(255) , 
broker_type varchar(255) , 
broker_status varchar(255), 
contract_dt date, 
primary_contact_nm varchar(255), 
broker_email varchar(255), 
broker_phone_no varchar(255), 
bdm_nm varchar(255), 
bdm_email varchar(255), 
new_business_uw_nm varchar(255), 
renewal_uw_nm varchar(255), 
open_submissions_ct int, 
one_year_actual_non_cat_loss_ratio decimal(15,2), 
two_year_ultimate_non_cat_loss_ratio decimal(15,2), 
five_year_non_cat_loss_ratio decimal(15,2), 
ytd_bind_ct int, 
ytd_submission_ct int, 
last30_days_submission_ct int,
hit_ratio decimal(15,2), 
offered_renewal_ct int, 
offered_renewal_over50k_ct int, 
inforce_policy_ct int, 
commission_tier varchar(255), 
inforce_premium_amt decimal(15,2), 
target_yoy_inforce_premium_pc decimal(15,2), 
target_yoy_ytd_nb_prem_pc decimal(15,2), 
target_ytd_nb_premium_pc decimal(15,2), 
target_ytd_renewal_retention_pc decimal(15,2), 
create_ts datetime NOT NULL,
update_ts datetime NOT NULL,
etl_audit_sk int NOT NULL, 
CONSTRAINT pk_broker_hubspot_feed PRIMARY KEY(broker_id)
); 

INSERT INTO	edw_integration.tintegration_table_detail(table_nm,	table_type,	table_desc,	load_method, load_type,load_frequency,create_ts,update_ts)
VALUES ('broker_hubspot_feed','Feed','This table provides broker data to Hubspot','Stored Procedure','Insert/Update','Daily',getdate(),getdate());