CREATE TABLE [edw_stage].[policy_workday_written_premium_reported](
[accounting_date] [date] NOT NULL,
[policy_image_id] [int] NULL,
[policy_image_identifier_id] [varchar](255) NULL,
[policy_number] [varchar](255) NOT NULL,
[product] [varchar](255) NULL,
[transaction_sequence] [int] NULL,
[company] [varchar](255) NULL,
[transaction_date] [date] NULL,
[effective_date] [date] NOT NULL,
[expiration_date] [date] NULL,
[transaction_type] [varchar](255) NULL,
[producer_code] [varchar](255) NULL,
[agency_name] [varchar](255) NULL,
[number_of_installments] [varchar](255) NULL,
[insured_name] [varchar](255) NULL,
[address] [varchar](255) NULL,
[county] [varchar](255) NULL,
[city] [varchar](255) NULL,
[risk_state] [varchar](255) NULL,
[zip] [varchar](255) NULL,
[fire_protection] [varchar](255) NULL,
[category] [varchar](255) NULL,
[subcategory] [varchar](255) NULL,
[financial_category_id] [varchar](255) NOT NULL,
[financial_category_name] [varchar](255) NULL,
[aslob] [varchar](255) NULL,
[amount] [decimal](15, 2) NULL,
[deleteddate] [date] NULL,
[contribcutoffdate] [date] NULL,
[extraction_time] [datetime] NULL,
[create_ts] [datetime] NULL,
[update_ts] [datetime] NULL,
[source] [varchar](255) NULL
)