ALTER TABLE edw_core.tclaim DROP CONSTRAINT fk_tclaim_sub_cause_of_loss_sk;

ALTER TABLE edw_core.tclaim DROP COLUMN sub_cause_of_loss_sk;
ALTER TABLE edw_core.tclaim DROP COLUMN adjusting_other_reserve_amt;
ALTER TABLE edw_core.tclaim DROP COLUMN adjusting_other_paid_amt;
ALTER TABLE edw_core.tclaim DROP COLUMN refund_indemnity_paid_amt;
ALTER TABLE edw_core.tclaim DROP COLUMN refund_expense_paid_amt;

EXEC sp_rename 'edw_core.tclaim.subro_reserve_amt', 'subrogation_recovery_reserve_amt', 'COLUMN';
EXEC sp_rename 'edw_core.tclaim.salvage_reserve_amt', 'salvage_recovery_reserve_amt', 'COLUMN';
EXEC sp_rename 'edw_core.tclaim.subro_expense_reserve_amt', 'subrogation_recovery_expense_reserve_amt', 'COLUMN';
EXEC sp_rename 'edw_core.tclaim.salvage_expense_reserve_amt', 'salvage_recovery_expense_reserve_amt', 'COLUMN';
EXEC sp_rename 'edw_core.tclaim.subro_recovery_amt', 'subrogation_recovery_amt', 'COLUMN';
EXEC sp_rename 'edw_core.tclaim.salvage_expense_paid_amt', 'salvage_expense_recovery_amt', 'COLUMN';
EXEC sp_rename 'edw_core.tclaim.subro_expense_paid_amt', 'subrogation_expense_recovery_amt', 'COLUMN';

ALTER TABLE edw_core.tclaim ADD defense_reserve_amt decimal(15,2);
ALTER TABLE edw_core.tclaim ADD deductible_recovery_reserve_amt decimal(15,2);
ALTER TABLE edw_core.tclaim ADD reinsurance_recovery_reserve_amt decimal(15,2);
ALTER TABLE edw_core.tclaim ADD overpayment_recovery_reserve_amt decimal(15,2);
ALTER TABLE edw_core.tclaim ADD deductible_recovery_expense_reserve_amt decimal(15,2);
ALTER TABLE edw_core.tclaim ADD reinsurance_recovery_expense_reserve_amt decimal(15,2);
ALTER TABLE edw_core.tclaim ADD overpayment_recovery_expense_reserve_amt decimal(15,2);
ALTER TABLE edw_core.tclaim ADD subrogation_recovery_defense_reserve_amt decimal(15,2);
ALTER TABLE edw_core.tclaim ADD salvage_recovery_defense_reserve_amt decimal(15,2);
ALTER TABLE edw_core.tclaim ADD deductible_recovery_defense_reserve_amt decimal(15,2);
ALTER TABLE edw_core.tclaim ADD reinsurance_recovery_defense_reserve_amt decimal(15,2);
ALTER TABLE edw_core.tclaim ADD overpayment_recovery_defense_reserve_amt decimal(15,2);
ALTER TABLE edw_core.tclaim ADD defense_paid_amt decimal(15,2);
ALTER TABLE edw_core.tclaim ADD deductible_recovery_amt decimal(15,2);
ALTER TABLE edw_core.tclaim ADD reinsurance_recovery_amt decimal(15,2);
ALTER TABLE edw_core.tclaim ADD overpayment_recovery_amt decimal(15,2);
ALTER TABLE edw_core.tclaim ADD deductible_expense_recovery_amt decimal(15,2);
ALTER TABLE edw_core.tclaim ADD reinsurance_expense_recovery_amt decimal(15,2);
ALTER TABLE edw_core.tclaim ADD overpayment_expense_recovery_amt decimal(15,2);
ALTER TABLE edw_core.tclaim ADD subrogation_defense_recovery_amt decimal(15,2);
ALTER TABLE edw_core.tclaim ADD salvage_defense_recovery_amt decimal(15,2);
ALTER TABLE edw_core.tclaim ADD deductible_defense_recovery_amt decimal(15,2);
ALTER TABLE edw_core.tclaim ADD reinsurance_defense_recovery_amt decimal(15,2);
ALTER TABLE edw_core.tclaim ADD overpayment_defense_recovery_amt decimal(15,2);