ALTER TABLE edw_core.tclaim_feature_summary DROP COLUMN adjusting_other_reserve_amt;
ALTER TABLE edw_core.tclaim_feature_summary DROP COLUMN itd_adjusting_other_reserve_amt;
ALTER TABLE edw_core.tclaim_feature_summary DROP COLUMN adjusting_other_paid_amt;
ALTER TABLE edw_core.tclaim_feature_summary DROP COLUMN itd_adjusting_other_paid_amt;
ALTER TABLE edw_core.tclaim_feature_summary DROP COLUMN refund_indemnity_paid_amt;
ALTER TABLE edw_core.tclaim_feature_summary DROP COLUMN itd_refund_indemnity_paid_amt;
ALTER TABLE edw_core.tclaim_feature_summary DROP COLUMN refund_expense_paid_amt;
ALTER TABLE edw_core.tclaim_feature_summary DROP COLUMN itd_refund_expense_paid_amt;
ALTER TABLE edw_core.tclaim_feature_summary DROP COLUMN itd_refund_paid_amt;
ALTER TABLE edw_core.tclaim_feature_summary DROP COLUMN dcc_expense_paid_amt;
ALTER TABLE edw_core.tclaim_feature_summary DROP COLUMN itd_dcc_expense_paid_amt;
ALTER TABLE edw_core.tclaim_feature_summary DROP COLUMN itd_dcc_expense_paid_on_close_amt;

EXEC sp_rename 'edw_core.tclaim_feature_summary.subro_reserve_amt', 'subrogation_recovery_reserve_amt', 'COLUMN';
EXEC sp_rename 'edw_core.tclaim_feature_summary.itd_subro_reserve_amt', 'itd_subrogation_recovery_reserve_amt', 'COLUMN';
EXEC sp_rename 'edw_core.tclaim_feature_summary.salvage_reserve_amt', 'salvage_recovery_reserve_amt', 'COLUMN';
EXEC sp_rename 'edw_core.tclaim_feature_summary.itd_salvage_reserve_amt', 'itd_salvage_recovery_reserve_amt', 'COLUMN';
EXEC sp_rename 'edw_core.tclaim_feature_summary.subro_expense_reserve_amt', 'subrogation_recovery_expense_reserve_amt', 'COLUMN';
EXEC sp_rename 'edw_core.tclaim_feature_summary.itd_subro_expense_reserve_amt', 'itd_subrogation_recovery_expense_reserve_amt', 'COLUMN';
EXEC sp_rename 'edw_core.tclaim_feature_summary.salvage_expense_reserve_amt', 'salvage_recovery_expense_reserve_amt', 'COLUMN';
EXEC sp_rename 'edw_core.tclaim_feature_summary.itd_salvage_expense_reserve_amt', 'itd_salvage_recovery_expense_reserve_amt', 'COLUMN';
EXEC sp_rename 'edw_core.tclaim_feature_summary.subro_recovery_amt', 'subrogation_recovery_amt', 'COLUMN';
EXEC sp_rename 'edw_core.tclaim_feature_summary.itd_subro_recovery_amt', 'itd_subrogation_recovery_amt', 'COLUMN';
EXEC sp_rename 'edw_core.tclaim_feature_summary.salvage_expense_paid_amt', 'salvage_expense_recovery_amt', 'COLUMN';
EXEC sp_rename 'edw_core.tclaim_feature_summary.itd_salvage_expense_paid_amt', 'itd_salvage_expense_recovery_amt', 'COLUMN';
EXEC sp_rename 'edw_core.tclaim_feature_summary.subro_expense_paid_amt', 'subrogation_expense_recovery_amt', 'COLUMN';
EXEC sp_rename 'edw_core.tclaim_feature_summary.itd_subro_expense_paid_amt', 'itd_subrogation_expense_recovery_amt', 'COLUMN';

ALTER TABLE edw_core.tclaim_feature_summary ADD defense_reserve_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD itd_defense_reserve_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD deductible_recovery_reserve_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD itd_deductible_recovery_reserve_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD reinsurance_recovery_reserve_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD itd_reinsurance_recovery_reserve_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD overpayment_recovery_reserve_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD itd_overpayment_recovery_reserve_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD deductible_recovery_expense_reserve_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD itd_deductible_recovery_expense_reserve_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD reinsurance_recovery_expense_reserve_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD itd_reinsurance_recovery_expense_reserve_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD overpayment_recovery_expense_reserve_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD itd_overpayment_recovery_expense_reserve_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD subrogation_recovery_defense_reserve_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD itd_subrogation_recovery_defense_reserve_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD salvage_recovery_defense_reserve_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD itd_salvage_recovery_defense_reserve_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD deductible_recovery_defense_reserve_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD itd_deductible_recovery_defense_reserve_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD reinsurance_recovery_defense_reserve_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD itd_reinsurance_recovery_defense_reserve_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD overpayment_recovery_defense_reserve_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD itd_overpayment_recovery_defense_reserve_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD defense_paid_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD itd_defense_paid_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD deductible_recovery_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD itd_deductible_recovery_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD reinsurance_recovery_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD itd_reinsurance_recovery_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD overpayment_recovery_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD itd_overpayment_recovery_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD deductible_expense_recovery_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD itd_deductible_expense_recovery_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD reinsurance_expense_recovery_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD itd_reinsurance_expense_recovery_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD overpayment_expense_recovery_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD itd_overpayment_expense_recovery_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD subrogation_defense_recovery_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD itd_subrogation_defense_recovery_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD salvage_defense_recovery_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD itd_salvage_defense_recovery_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD deductible_defense_recovery_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD itd_deductible_defense_recovery_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD reinsurance_defense_recovery_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD itd_reinsurance_defense_recovery_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD overpayment_defense_recovery_amt decimal(15,2);
ALTER TABLE edw_core.tclaim_feature_summary ADD itd_overpayment_defense_recovery_amt decimal(15,2);