CREATE TABLE edw_core.tmarine_boat_yacht_coverage 
(
	marine_boat_yacht_coverage_sk int IDENTITY(1,1) NOT NULL,
	policy_no varchar(255) NOT NULL ,
	effective_dt date NOT NULL ,
	transaction_effective_dt date NOT NULL ,
	expiration_dt date NOT NULL ,
	transaction_dt date NOT NULL ,
	transaction_seq_no int NOT NULL ,
	policy_history_sk int NOT NULL ,
	marine_boat_yacht_location_sk  int NOT NULL ,
    marine_boat_yacht_sk  int NOT NULL ,
	storage_location     varchar(255),
	distance_to_coast varchar(255),
	navigable_waters nvarchar(max),
	layup_period_in varchar(255),
	layup_period_start_dt date,
	layup_period_end_dt date,
	layup_factor varchar(255),
	no_of_prior_marine_claims int,
	purchase_dt date,
	active_tracking_device_in varchar(255),
	additional_personal_watercraft_in  varchar(255),
	manuscript_in varchar(255),
    hull_value_limit_amt int,
    liability_limit_amt int,
    personal_effects_limit_amt varchar(255), 
    opa_pollution_liability_limit_amt varchar(255),
    medical_payments_limit_amt varchar(255),
    uninsured_boater_limit_amt varchar(255),
    aop_deductible varchar(255),
    windstorm_deductible varchar(255),
    lightning_deductible varchar(255),
    theft_deductible varchar(255),
	personal_effects_deductible varchar(255),
    opa_pollution_deductible varchar(255),
    uninsured_boater_deductible varchar(255),
    medical_payments_deductible varchar(255),
	trailer_value_excess_of_5k_in varchar(255),
	trailer_value varchar(255),
	trailer_deductible varchar(255),
	trailer_year varchar(255),
	trailer_manufacturer_nm varchar(255),
	trailer_vin varchar(255),
	source_system_sk int ,
	create_ts datetime ,
	update_ts datetime ,
	etl_audit_sk int ,
	CONSTRAINT pk_tmarine_boat_yacht_coverage PRIMARY KEY (marine_boat_yacht_coverage_sk),
    CONSTRAINT uidx_tmarine_boat_yacht_coverage_polno_effdt_transeq UNIQUE (policy_no,effective_dt,transaction_seq_no),
    CONSTRAINT fk_tmarine_boat_yacht_coverage_policy_history_sk FOREIGN KEY (policy_history_sk) REFERENCES  edw_core.tpolicy_history(policy_history_sk),
    CONSTRAINT fk_tmarine_boat_yacht_coverage_marine_boat_yacht_location_sk FOREIGN KEY (marine_boat_yacht_location_sk) REFERENCES  edw_core.tmarine_boat_yacht_location(marine_boat_yacht_location_sk),
    CONSTRAINT fk_tmarine_boat_yacht_coverage_marine_boat_yacht_sk FOREIGN KEY (marine_boat_yacht_sk) REFERENCES edw_core.tmarine_boat_yacht(marine_boat_yacht_sk)
);

INSERT INTO edw_core.tedw_table_detail(table_nm,table_type,table_category_nm,domain_nm,load_method,load_type,load_frequency,create_ts,update_ts) 
    VALUES ('tmarine_boat_yacht_coverage','Type-2 Dimension','Base','Marine','Stored Procedure','Insert','Daily',getdate(),getdate());
