CREATE TABLE edw_commercial.tcommercial_policy_history
(
	commercial_policy_history_sk int IDENTITY(1,1) NOT NULL,
	policy_no varchar(255) NOT NULL,
	effective_dt date NOT NULL,
	expiration_dt date NOT NULL,
	transaction_effective_dt date NOT NULL,
	transaction_seq_no int NOT NULL,
	latest_transaction_in varchar(255) NULL,
	commercial_policy_sk int NULL,
	broker_sk int NULL,
	customer_sk int NULL,
	product_sk int NULL,
	broker_id varchar(255) NULL,
	customer_id varchar(255) NULL,
	underwriter_nm varchar(255) NULL,
	producer_nm varchar(255) NULL,
	transaction_type varchar(255) NULL,
	transaction_ts datetime NULL,
	transaction_desc varchar(4000) NULL,
	cancellation_reason_desc varchar(4000) NULL,
	policy_change_summary nvarchar(max) NULL,
	premium_amt decimal(15, 2) NULL,
	net_premium_amt decimal(15, 2) NULL,
	commission_amt decimal(15, 2) NULL,
	annual_premium_amt decimal(15, 2) NULL,
    commission_pc float NULL,
	override_commission_pc float NULL,
	transaction_initiated_by varchar(255) NULL,
	transaction_issued_by varchar(255) NULL,
	producer_sk int NULL,
	premium_rater_version varchar(255) ,
    rate_change_pc  varchar(255),   
    source_system_sk int NOT NULL,
	create_ts datetime NOT NULL,
	update_ts datetime NOT NULL,
	etl_audit_sk int NOT NULL,
CONSTRAINT pk_tcommercial_policy_history PRIMARY KEY (commercial_policy_history_sk),
CONSTRAINT fk_tcommercial_policy_history_broker_sk FOREIGN KEY (broker_sk) REFERENCES  [edw_core].[tbroker] ([broker_sk]),
CONSTRAINT fk_tcommercial_policy_history_customer_sk FOREIGN KEY (customer_sk) REFERENCES  [edw_core].[tcustomer] ([customer_sk]), 
CONSTRAINT fk_tcommercial_policy_history_producer_sk FOREIGN KEY (producer_sk) REFERENCES  [edw_core].[tproducer] ([producer_sk]),
CONSTRAINT fk_tcommercial_policy_history_product_sk FOREIGN KEY (product_sk) REFERENCES  [edw_core].[tproduct] ([product_sk]),
CONSTRAINT fk_tcommercial_policy_history_commercial_policy_sk FOREIGN KEY (commercial_policy_sk) REFERENCES  [edw_commercial].[tcommercial_policy] ([commercial_policy_sk]),
CONSTRAINT uidx_tcommercial_policy_history_policy_no_effective_dt_transactionseqno UNIQUE (policy_no,effective_dt,transaction_seq_no)
);
