CREATE TABLE edw_commercial.tcommercial_quote
(
commercial_quote_sk 	     int IDENTITY(1,1) NOT NULL,
quote_no                     varchar(255) NOT NULL,
effective_dt                  date         NOT NULL ,
expiration_dt   			  date         NOT NULL,
transaction_seq_no                  int NOT NULL,
broker_id                     varchar(255) NOT NULL,
product_nm                    varchar(255) NOT NULL,
quote_term					  varchar(255),
risk_state_cd                 varchar(255),
quote_transaction_type		  varchar(255), 
lastest_transction_in         varchar(255),   
insured_nm                    varchar(255),
mailing_address_line1         varchar(255),  
mailing_address_line2         varchar(255),
mailing_address_unit_no       varchar(255),
mailing_address_city_nm       varchar(255),
mailing_address_state_cd      varchar(255),
mailing_address_zip_cd        varchar(255),
producer_nm                     varchar(255),
underwriter_nm			        varchar(255),
quote_create_ts                 datetime,
transaction_created_ts          datetime,
transaction_updated_ts          datetime,
coverage_type					varchar(255),
memorandum_of_insurance_in		varchar(255),
employee_ct						varchar(255),
claim_history					varchar(255),
revenue_amt						int,
gross_premium_amt				decimal(15,2),
commission_amt					decimal(15,2),
commission_pc				    varchar(255),
override_commission_pc	        varchar(255),
net_premium_amt					decimal(15,2),
rate_change_pc                  varchar(255), 
create_ts                     datetime,
update_ts                     datetime,
etl_audit_sk              		int
CONSTRAINT pk_tcommercial_quote PRIMARY KEY (commercial_quote_sk),
CONSTRAINT uidx_tcommercial_quote_quote_no_effective_dt_transaction_seq_no UNIQUE (quote_no,effective_dt,transaction_seq_no)
);