CREATE TABLE edw_commercial.tcommercial_quote
(
commercial_quote_sk 	     int IDENTITY(1,1) NOT NULL,
quote_no                     varchar(255) NOT NULL,
effective_dt                  date         NOT NULL ,
expiration_dt   			  date         NOT NULL,
broker_id                     varchar(255) NOT NULL,
customer_id                 varchar(255) NOT NULL,
product_cd                    varchar(255) NOT NULL,
risk_state_cd                 varchar(255),
quote_term					  varchar(255),
quote_status                varchar(255) NULL,
quote_source_status          varchar(255) NULL,
insured_nm                    varchar(255),
mailing_address_line1         varchar(255),  
mailing_address_line2         varchar(255),
mailing_address_unit_no       varchar(255),
mailing_address_city_nm       varchar(255),
mailing_address_state_cd      varchar(255),
mailing_address_zip_cd        varchar(255),
quote_create_ts                 datetime,
policy_sk                   int NULL,
prior_term_policy_sk         int NULL,
bind_dt                      date NULL,
close_reason_desc             varchar(255) NULL,    
create_ts                     datetime NOT NULL,
update_ts                     datetime NOT NULL,
etl_audit_sk              		int NOT NULL,
source_system_sk                int NOT NULL,
CONSTRAINT pk_tcommercial_quote PRIMARY KEY (commercial_quote_sk),
CONSTRAINT uidx_tcommercial_quote_quote_no_effective_dt UNIQUE (quote_no,effective_dt)
);