CREATE TABLE [edw_commercial].[tcommercial_quote_history]
(
	[commercial_quote_history_sk] [int] IDENTITY(1,1) NOT NULL,
	[quote_no] [varchar](255) NOT NULL,
	[effective_dt] [date] NOT NULL,
	[expiration_dt] [date] NOT NULL,
	[transaction_effective_dt] [date] NOT NULL,
	[transaction_seq_no] [int] NOT NULL,
	[latest_transaction_in] [varchar](255) NULL,
	[commercial_quote_sk] [int] NULL,
	[broker_sk] [int] NULL,
	[customer_sk] [int] NULL,
	[product_sk] [int] NULL,
	[broker_id] [varchar](255) NULL,
	[customer_id] [varchar](255) NULL,
	[underwriter_nm] [varchar](255) NULL,
	[producer_nm] [varchar](255) NULL,
	[transaction_type] [varchar](255) NULL,
	[transaction_status] [varchar](255) NULL,
	[not_taken_reason_desc] [varchar](2000) NULL,
	[transaction_created_ts] [datetime2](7) NULL,
	[transaction_updated_ts] [datetime2](7) NULL,
	[transaction_desc] [varchar](4000) NULL,
	[bind_dt] [date] NULL,
	[created_by_nm] [varchar](255) NULL,
	[referred_by_nm] [varchar](255) NULL,
	[reviewed_by_nm] [varchar](255) NULL,
	[approval_note] [nvarchar](max) NULL,
	[deny_note] [nvarchar](max) NULL,
	[policy_change_summary] [nvarchar](max) NULL,
	[premium_amt] [decimal](15, 2) NULL,
	[net_premium_amt] [decimal](15, 2) NULL,
	[commission_amt] [decimal](15, 2) NULL,
	[annual_premium_amt] [decimal](15, 2) NULL,
	[commission_pc] [float] NULL,
	[override_commission_pc] [float] NULL,
    rate_change_pc  varchar(255), 
    [producer_sk] [int] NULL,
	[premium_rater_version] [varchar](255) NULL,
    [source_system_sk] [int] NOT NULL,
	[create_ts] [datetime] NOT NULL,
	[update_ts] [datetime] NOT NULL,
	[etl_audit_sk] [int] NOT NULL,
CONSTRAINT pk_tcommercial_quote_history PRIMARY KEY (commercial_quote_history_sk),
CONSTRAINT fk_tcommercial_quote_history_broker_sk FOREIGN KEY (broker_sk) REFERENCES  [edw_core].[tbroker] ([broker_sk]),
CONSTRAINT fk_tcommercial_quote_history_customer_sk FOREIGN KEY (customer_sk) REFERENCES  [edw_core].[tcustomer] ([customer_sk]), 
CONSTRAINT fk_tcommercial_quote_history_producer_sk FOREIGN KEY (producer_sk) REFERENCES  [edw_core].[tproducer] ([producer_sk]),
CONSTRAINT fk_tcommercial_quote_history_product_sk FOREIGN KEY (product_sk) REFERENCES  [edw_core].[tproduct] ([product_sk]),
CONSTRAINT fk_tcommercial_quote_history_commercial_quote_sk FOREIGN KEY (commercial_quote_sk) REFERENCES  [edw_commercial].[tcommercial_quote] ([commercial_quote_sk]),
CONSTRAINT uidx_tcommercial_quote_history_quote_no_effective_dt_transactionseqno UNIQUE (quote_no,effective_dt,transaction_seq_no)
) 
;
