CREATE TABLE [edw_commercial].[tcommercial_policy_transaction]
(
	[commercial_policy_transaction_sk] [int] IDENTITY(1,1) NOT NULL,
	[commercial_policy_sk] [int] NOT NULL,
    [commercial_policy_history_sk] [int] NOT NULL,
	[effective_dt_sk] [int] NOT NULL,
	[expiration_dt_sk] [int] NOT NULL,
	[transaction_effective_dt_sk] [int] NOT NULL,
	[transaction_seq_no] [int] NOT NULL,
	[broker_sk] [int] NOT NULL,
	[customer_sk] [int] NOT NULL,
	[premium_amt] [decimal](15, 2) NULL,
	[net_premium_amt] [decimal](15, 2) NULL,
	[commission_amt] [decimal](15, 2) NULL,
	[annual_premium_amt] [decimal](15, 2) NULL,
	[coverage_sk] [int] NULL,
	[transaction_dt_sk] [int] NOT NULL,
	[calendar_month_sk] [int] NOT NULL,
	[accounting_month_sk] [int] NOT NULL,
	[product_sk] [int] NOT NULL,
	[policy_transaction_type_sk] [int] NOT NULL,
	[source_system_sk] [int] NOT NULL,
	[policy_status_sk] [int] NOT NULL,
	[user_sk] [int] NULL,
	[create_ts] [datetime] NOT NULL,
	[update_ts] [datetime] NOT NULL,
	[etl_audit_sk] [int] NOT NULL
CONSTRAINT pk_tcommercial_policy_transaction PRIMARY KEY (commercial_policy_transaction_sk),
CONSTRAINT fk_tcommercial_policy_transaction_broker_sk FOREIGN KEY (broker_sk) REFERENCES  [edw_core].[tbroker] ([broker_sk]),
CONSTRAINT fk_tcommercial_policy_transaction_customer_sk FOREIGN KEY (customer_sk) REFERENCES  [edw_core].[tcustomer] ([customer_sk]),
CONSTRAINT fk_tcommercial_policy_transaction_product_sk FOREIGN KEY (product_sk) REFERENCES  [edw_core].[tproduct] ([product_sk]),
CONSTRAINT fk_tcommercial_policy_transaction_source_system_sk FOREIGN KEY (source_system_sk) REFERENCES  [edw_core].[tsource_system] ([source_system_sk]),
CONSTRAINT fk_tcommercial_policy_transaction_commercial_policy_sk FOREIGN KEY (commercial_policy_sk) REFERENCES  [edw_commercial].[tcommercial_policy] ([commercial_policy_sk]),
CONSTRAINT fk_tcommercial_policy_transaction_commercial_policy_history_sk FOREIGN KEY (commercial_policy_history_sk) REFERENCES  [edw_commercial].[tcommercial_policy_history] ([commercial_policy_history_sk]),
);

