CREATE TABLE edw_commercial.tcommercial_quote_transaction(
	commercial_quote_transaction_sk int IDENTITY(1,1) NOT NULL,
	commercial_quote_sk int NOT NULL,
	commercial_quote_history_sk int NOT NULL,
	effective_dt_sk int NOT NULL,
	expiration_dt_sk int NOT NULL,
	transaction_effective_dt_sk int NOT NULL,
	transaction_seq_no int NOT NULL,
	broker_sk int NOT NULL,
	customer_sk int NOT NULL,
	premium_amt decimal(15, 2) NULL,
	net_premium_amt decimal(15, 2) NULL,
	commission_amt decimal(15, 2) NULL,
	annual_premium_amt decimal(15, 2) NULL,
	coverage_sk int NULL,
	transaction_dt_sk int NOT NULL,
	product_sk int NOT NULL,
	source_system_sk int NOT NULL,
	user_sk int NULL,
	create_ts datetime NULL,
	update_ts datetime NULL,
	etl_audit_sk int NULL,
CONSTRAINT pk_tcommercial_quote_transaction PRIMARY KEY (commercial_quote_transaction_sk),
CONSTRAINT fk_tcommercial_quote_transaction_broker_sk FOREIGN KEY (broker_sk) REFERENCES  edw_core.tbroker (broker_sk),
CONSTRAINT fk_tcommercial_quote_transaction_customer_sk FOREIGN KEY (customer_sk) REFERENCES  edw_core.tcustomer (customer_sk),
CONSTRAINT fk_tcommercial_quote_transaction_product_sk FOREIGN KEY (product_sk) REFERENCES  edw_core.tproduct (product_sk),
CONSTRAINT fk_tcommercial_quote_transaction_source_system_sk FOREIGN KEY (source_system_sk) REFERENCES  edw_core.tsource_system (source_system_sk),
CONSTRAINT fk_tcommercial_quote_transaction_commercial_quote_sk FOREIGN KEY (commercial_quote_sk) REFERENCES  edw_commercial.tcommercial_quote (commercial_quote_sk),
CONSTRAINT fk_tcommercial_quote_transaction_commercial_quote_history_sk FOREIGN KEY (commercial_quote_history_sk) REFERENCES  edw_commercial.tcommercial_quote_history (commercial_quote_history_sk)
);