CREATE TABLE edw_commercial.tcommercial_policy_summary
(
month_sk                        int NOT NULL,
commercial_policy_sk            int NOT NULL,
customer_sk                     int NOT NULL,
broker_sk                       int NOT NULL,
product_sk                      int NOT NULL,
mtd_premium_amt        			decimal(15,2), 
mtd_commission_amt				decimal(15,2),			
mtd_net_premium_amt	            decimal(15,2),
ytd_premium_amt         		decimal(15,2), 
ytd_commission_amt				decimal(15,2),			
ytd_net_premium_amt	    		decimal(15,2),
itd_premium_amt                 decimal(15,2), 
itd_commission_amt				decimal(15,2),			
itd_net_premium_amt	    		decimal(15,2),
annual_premium_amt              decimal(15,2),
inforce_premium_amt             decimal(15,2),
inforce_net_premium_amt         decimal(15,2),
earned_premium_amt              decimal(15,4),
earned_net_premium_amt          decimal(15,4),
unearned_premium_amt            decimal(15,4),
unearned_net_premium_amt        decimal(15,4),
written_exposure                decimal(15,4),
earned_exposure                 decimal(15,4),
inforce_ct                      int,
source_system_sk                int NOT NULL,
update_ts                       datetime2(7) NOT NULL, 
etl_audit_sk                    int NOT NULL,
CONSTRAINT pk_tcommercial_policy_summary PRIMARY KEY (month_sk,commercial_policy_sk),
CONSTRAINT fk_tcps_tcommercial_policy_policy_sk FOREIGN KEY (commercial_policy_sk) REFERENCES  edw_commercial.tcommercial_policy(commercial_policy_sk),
CONSTRAINT fk_tcps_tbroker_broker_sk FOREIGN KEY (broker_sk) REFERENCES  edw_core.tbroker(broker_sk),
CONSTRAINT fk_tcps_tcustomer_customer_sk FOREIGN KEY (customer_sk) REFERENCES  edw_core.tcustomer(customer_sk),
CONSTRAINT fk_tcps_tproduct_product_sk FOREIGN KEY (product_sk) REFERENCES  edw_core.tproduct(product_sk),
CONSTRAINT fk_tcps_tsource_system_source_system_sk FOREIGN KEY (source_system_sk) REFERENCES  edw_core.tsource_system(source_system_sk)
);