CREATE TABLE edw_commercial.tcommercial_broker_summary
(
	month_sk int NOT NULL,
	broker_sk int NOT NULL,
	prior_ytd_submission_ct int NULL,
	ytd_submission_ct int NOT NULL,
	prior_qtd_submission_ct int NULL,
	qtd_submission_ct int NOT NULL,
	prior_mtd_submission_ct int NULL,
	mtd_submission_ct int NOT NULL,
	prior_ytd_quote_premium_amt decimal(15, 2) NULL,
	ytd_quote_premium_amt decimal(15, 2) NULL,
	prior_qtd_quote_premium_amt decimal(15, 2) NULL,
	qtd_quote_premium_amt decimal(15, 2) NULL,
	prior_mtd_quote_premium_amt decimal(15, 2) NULL,
	mtd_quote_premium_amt decimal(15, 2) NULL,
	prior_ytd_quote_ct int NOT NULL,
	ytd_quote_ct int NOT NULL,
	prior_qtd_quote_ct int NOT NULL,
	qtd_quote_ct int NOT NULL,
	prior_mtd_quote_ct int NOT NULL,
	mtd_quote_ct int NOT NULL,
	last_quote_dt date NULL,
	last_bound_dt date NULL,
	prior_customer_ct int NOT NULL,
	customer_ct int NOT NULL,
	prior_total_line_ct int NOT NULL,
	total_line_ct int NOT NULL,
	prior_ytd_new_business_ct int NOT NULL,
	ytd_new_business_ct int NOT NULL,
	prior_qtd_new_business_ct int NOT NULL,
	qtd_new_business_ct int NOT NULL,
	prior_mtd_new_business_ct int NOT NULL,
	mtd_new_business_ct int NOT NULL,
	prior_ytd_new_business_premium_amt decimal(15, 2) NOT NULL,
	ytd_new_business_premium_amt decimal(15, 2) NOT NULL,
	prior_qtd_new_business_premium_amt decimal(15, 2) NOT NULL,
	qtd_new_business_premium_amt decimal(15, 2) NOT NULL,
	prior_mtd_new_business_premium_amt decimal(15, 2) NOT NULL,
	mtd_new_business_premium_amt decimal(15, 2) NOT NULL,
	prior_mtd_gross_new_business_premium_amt decimal(15, 2) NOT NULL,
	mtd_gross_new_business_premium_amt decimal(15, 2) NOT NULL,
	prior_mtd_written_premium_amt decimal(15, 2) NOT NULL,
	mtd_written_premium_amt decimal(15, 2) NOT NULL,
	prior_inforce_ct int NOT NULL,
	prior_inforce_premium_amt decimal(15, 2) NOT NULL,
	inforce_ct int NOT NULL,
	inforce_premium_amt decimal(15, 2) NOT NULL,
	one_year_claim_ct int NOT NULL,
	one_year_loss_incurred_amt decimal(15, 2) NOT NULL,
	one_year_earned_premium_amt decimal(15, 4) NOT NULL,
	one_year_earned_exposure decimal(15, 4) NOT NULL,
	one_year_loss_incurred_capped_amt decimal(15, 2) NOT NULL,
	three_year_claim_ct int NOT NULL,
	three_year_loss_incurred_amt decimal(15, 2) NOT NULL,
	three_year_earned_premium_amt decimal(15, 4) NOT NULL,
	three_year_earned_exposure decimal(15, 4) NOT NULL,
	three_year_loss_incurred_capped_amt decimal(15, 2) NOT NULL,
	policy_expiring_ct int NOT NULL,
	policy_renewal_ct int NOT NULL,
	policy_expiring_premium_amt decimal(15, 2) NOT NULL,
	policy_renewal_premium_amt decimal(15, 2) NOT NULL,
	update_ts datetime NULL,
	etl_audit_sk int NULL,
	one_year_written_premium_amt decimal(15, 2) NULL,
	three_year_written_premium_amt decimal(15, 2) NULL,
	one_year_loss_ratio decimal(15, 2) NULL,
	one_year_loss_ratio_capped decimal(15, 2) NULL,
	one_year_frequency decimal(15, 2) NULL,
	one_year_severity decimal(15, 2) NULL,
	three_year_loss_ratio decimal(15, 2) NULL,
	three_year_loss_ratio_capped decimal(15, 2) NULL,
	three_year_frequency decimal(15, 2) NULL,
	three_year_severity decimal(15, 2) NULL,
	policy_renewal_offered_ct int NULL,
	policy_renewal_offered_premium_amt decimal(10, 2) NULL,
	policy_renewal_offered_expiring_premium_amt decimal(10, 2) NULL,
	open_submission_ct int NULL,
	last30_days_submission_ct int NULL,
	policy_renewal_offered_over_50k_ct int NULL,
	two_year_claim_ct int NULL,
	two_year_loss_incurred_amt decimal(15, 2) NULL,
	two_year_earned_premium_amt decimal(15, 4) NULL,
	five_year_claim_ct int NULL,
	five_year_loss_incurred_amt decimal(15, 2) NULL,
	five_year_earned_premium_amt decimal(15, 4) NULL,
	prior_ytd_bind_ct int NULL,
	ytd_bind_ct int NULL,
	prior_qtd_bind_ct int NULL,
	qtd_bind_ct int NULL,
	prior_mtd_bind_ct int NULL,
	mtd_bind_ct int NULL,
	ytd_policy_expiring_ct int NULL,
	ytd_policy_renewal_ct int NULL,
	ytd_policy_renewal_offered_ct int NULL,
	ytd_policy_renewal_offered_over_50k_ct int NULL,
	ytd_policy_renewal_offered_premium_amt decimal(10, 2) NULL,
	ytd_policy_renewal_offered_expiring_premium_amt decimal(10, 2) NULL,
	ytd_policy_expiring_premium_amt decimal(10, 2) NULL,
	ytd_policy_renewal_premium_amt decimal(10, 2) NULL,
	policy_renewal_accepted_ct int NULL,
	ytd_policy_renewal_accepted_ct int NULL,
	prior_ytd_new_business_limit_amt int NULL,
	prior_ytd_new_business_attachment_amt int NULL,
	prior_qtd_new_business_limit_amt int NULL,
	prior_qtd_new_business_attachment_amt int NULL,
	prior_mtd_new_business_limit_amt int NULL,
	prior_mtd_new_business_attachment_amt int NULL,
	ytd_new_business_limit_amt int NULL,
	ytd_new_business_attachment_amt int NULL,
	qtd_new_business_limit_amt int NULL,
	qtd_new_business_attachment_amt int NULL,
	mtd_new_business_limit_amt int NULL,
	mtd_new_business_attachment_amt int NULL,
	prior_ytd_quote_limit_amt int NULL,
	prior_ytd_quote_attachment_amt int NULL,
	prior_qtd_quote_limit_amt int NULL,
	prior_qtd_quote_attachment_amt int NULL,
	prior_mtd_quote_limit_amt int NULL,
	prior_mtd_quote_attachment_amt int NULL,
	ytd_quote_limit_amt int NULL,
	ytd_quote_attachment_amt int NULL,
	qtd_quote_limit_amt int NULL,
	qtd_quote_attachment_amt int NULL,
	mtd_quote_limit_amt int NULL,
	mtd_quote_attachment_amt int NULL,
	inforce_limit_amt int NULL,
	inforce_attachment_amt int NULL,
	mtd_mid_term_cancellation_ct int NULL,
CONSTRAINT pk_tcommercial_broker_summary PRIMARY KEY (month_sk,broker_sk),
CONSTRAINT fk_tcbs_tbroker_broker_sk FOREIGN KEY (broker_sk) REFERENCES  edw_core.tbroker(broker_sk)
);

