CREATE TABLE edw_commercial.tcommercial_claim (
  commercial_claim_sk int NOT NULL IDENTITY(1,1),
  claim_no varchar(255) ,
  loss_dt date ,
  report_dt date ,
  policy_no varchar(255) ,
  effective_dt date ,
  commercial_policy_sk int,
  cause_of_loss_sk int ,
  loss_desc nvarchar(max) ,
  claim_status varchar(255) ,
  source_claim_status varchar(255) ,
  product_sk int ,
  underwriting_company_nm varchar(255) ,
  loss_address varchar(255),
  loss_city_nm varchar(255),
  loss_state_cd varchar(255),
  loss_zip_cd varchar(255),
  loss_country_nm varchar(255),
  broker_id varchar(255) ,
  customer_id varchar(255) ,
  contact_nm varchar(255),
  contact_type varchar(255),
  contact_phone varchar(255),
  contact_person_email varchar(255),
  loss_reserve_amt decimal(15,2) ,
  expense_reserve_amt decimal(15,2) ,
  subrogation_recovery_reserve_amt decimal(15,2) ,
  salvage_recovery_reserve_amt decimal(15,2) ,
  salvage_recover_expense_reserve_amt decimal(15,2) ,
  subrogation_recovery_expense_reserve_amt decimal(15,2) ,
  loss_paid_amt decimal(15,2) ,
  expense_paid_amt decimal(15,2) ,
  subrogation_recovery_amt decimal(15,2) ,
  salvage_recovery_amt decimal(15,2) ,
  salvage_expense_recovery_amt decimal(15,2) ,
  subrogation_expense_recovery_amt decimal(15,2) ,
  source_system_sk int,
  create_ts datetime ,
  update_ts datetime ,
  etl_audit_sk  int,
  commercial_policy_history_sk int,
  claim_created_ts datetime,
  claim_created_by_nm varchar(255),
  claim_first_closed_dt date , 
  claim_first_reopen_dt date, 
  claim_reject_reason_desc nvarchar(max),
  defense_reserve_amt decimal(15,2) ,
  deductible_recovery_reserve_amt decimal(15,2),
  reinsurance_recovery_reserve_amt decimal(15,2), 
  overpayment_recovery_reserve_amt decimal(15,2), 
  deductible_recovery_expense_reserve_amt decimal(15,2), 
  reinsurance_recovery_expense_reserve_amt decimal(15,2),
  overpayment_recovery_expense_reserve_amt decimal(15,2),
  subrogation_recovery_defense_reserve_amt decimal(15,2),
  salvage_recovery_defense_reserve_amt decimal(15,2),
  deductible_recovery_defense_reserve_amt decimal(15,2),
  reinsurance_recovery_defense_reserve_amt decimal(15,2),
  overpayment_recovery_defense_reserve_amt decimal(15,2),
  defense_paid_amt decimal(15,2),
  deductible_recovery_amt decimal(15,2),
  reinsurance_recovery_amt decimal(15,2),
  overpayment_recovery_amt decimal(15,2),
  deductible_expense_recovery_amt decimal(15,2),
  reinsurance_expense_recovery_amt decimal(15,2),
  overpayment_expense_recovery_amt decimal(15,2),
  subrogation_defense_recovery_amt decimal(15,2),
  salvage_defense_recovery_amt decimal(15,2),
  deductible_defense_recovery_amt decimal(15,2),
  reinsurance_defense_recovery_amt decimal(15,2),
  overpayment_defense_recovery_amt decimal(15,2),
  fault_decision varchar(255),
  coverage_confirmed_ts datetime,
  coverage_confirmed_by_nm varchar(255),
  coverage_confirmed_in varchar(255),
  litigation_in varchar(255),
  litigation_complete_in varchar(255),
 CONSTRAINT pk_tcommercial_claim PRIMARY KEY (commercial_claim_sk),
 CONSTRAINT uidx_tcommercial_claim_claim_no UNIQUE (claim_no),
 CONSTRAINT fk_tcommercial_claim_cause_of_loss_sk FOREIGN KEY (cause_of_loss_sk) REFERENCES  edw_core.tcause_of_loss(cause_of_loss_sk),
 CONSTRAINT fk_tcommercial_claim_product_sk FOREIGN KEY (product_sk) REFERENCES  edw_core.tproduct(product_sk),
 CONSTRAINT fk_tcommercial_claim_source_system_sk FOREIGN KEY (source_system_sk) REFERENCES  edw_core.tsource_system(source_system_sk),
 CONSTRAINT fk_tcommercial_claim_policy_sk FOREIGN KEY (commercial_policy_sk) REFERENCES  edw_commercial.tcommercial_policy(commercial_policy_sk)
 );

INSERT INTO edw_core.tedw_table_detail(table_nm,table_type,table_category_nm,domain_nm,load_method,load_type,load_frequency,create_ts,update_ts) 
    VALUES ('tcommercial_claim','Type-1 Dimension','Base','Claim','Stored Procedure','Insert/Update','Daily',getdate(),getdate());
