CREATE TABLE edw_commercial.tcommercial_claim_feature (
  commercial_claim_feature_sk int NOT NULL IDENTITY(1,1),
  commercial_claim_sk int ,
  claim_no varchar(255) ,
  claim_coverage_cd bigint ,
  claim_coverage_desc varchar(255) ,
  claimant_nm varchar(255) ,
  total_loss_in varchar(1) ,
  product_sk int ,
  claim_feature_status varchar(255) ,
  aslob_sk int ,
  claim_adjuster_nm varchar(255) ,
  coverage_sk int,
  loss_reserve_amt decimal(15,2) ,
  expense_reserve_amt decimal(15,2) ,
  subrogation_recovery_reserve_amt decimal(15,2) ,
  salvage_recovery_reserve_amt decimal(15,2) ,
  salvage_recovery_expense_reserve_amt decimal(15,2) ,
  subrogation_recovery_expense_reserve_amt decimal(15,2) ,
  loss_paid_amt decimal(15,2) ,
  expense_paid_amt decimal(15,2) ,
  subrogation_recovery_amt decimal(15,2) ,
  salvage_recovery_amt decimal(15,2) ,
  salvage_expense_recovery_amt decimal(15,2) ,
  source_system_sk int ,
  create_ts datetime ,
  update_ts datetime ,
  etl_audit_sk  int,
  exposure_type varchar(255),
  exposure_name varchar(255),
  defense_reserve_amt decimal(15,2),
  deductible_recovery_reserve_amt decimal(15,2),
  reinsurance_recovery_reserve_amt decimal(15,2),
  overpayment_recovery_reserve_amt decimal(15,2),
  deductible_recovery_expense_reserve_amt decimal(15,2),
  reinsurance_recovery_expense_reserve_amt decimal(15,2),
  overpayment_recovery_expense_reserve_amt decimal(15,2),
  subrogation_recovery_defense_reserve_amt decimal(15,2),
  salvage_recovery_defense_reserve_amt decimal(15,2),
  deductible_recovery_defense_reserve_amt decimal(15,2),
  reinsurance_recovery_defense_reserve_amt decimal(15,2),
  overpayment_recovery_defense_reserve_amt decimal(15,2),
  defense_paid_amt decimal(15,2),
  deductible_recovery_amt decimal(15,2),
  reinsurance_recovery_amt decimal(15,2),
  overpayment_recovery_amt decimal(15,2),
  deductible_expense_recovery_amt decimal(15,2),
  reinsurance_expense_recovery_amt decimal(15,2),
  overpayment_expense_recovery_amt decimal(15,2),
  subrogation_defense_recovery_amt decimal(15,2),
  salvage_defense_recovery_amt decimal(15,2),
  deductible_defense_recovery_amt decimal(15,2),
  reinsurance_defense_recovery_amt decimal(15,2),
  overpayment_defense_recovery_amt decimal(15,2),
 CONSTRAINT pk_tcommercial_claim_feature PRIMARY KEY (commercial_claim_feature_sk),
 CONSTRAINT uidx_tcommercial_claim_feature_claimno_claimcoveragecd UNIQUE (claim_no,claim_coverage_cd),
 CONSTRAINT fk_tcommercial_claim_feature_product_sk FOREIGN KEY (product_sk) REFERENCES  edw_core.tproduct(product_sk),
 CONSTRAINT fk_tcommercial_claim_feature_claim_sk FOREIGN KEY (commercial_claim_sk) REFERENCES  edw_commercial.tcommercial_claim(commercial_claim_sk),
 CONSTRAINT fk_tcommercial_claim_feature_source_system_sk FOREIGN KEY (source_system_sk) REFERENCES  edw_core.tsource_system(source_system_sk)
)
;

INSERT INTO edw_core.tedw_table_detail(table_nm,table_type,table_category_nm,domain_nm,load_method,load_type,load_frequency,create_ts,update_ts) 
    VALUES ('tcommercial_claim_feature','Type-1 Dimension','Base','Claim','Stored Procedure','Insert/Update','Daily',getdate(),getdate());
