 ALTER TABLE edw_integration.policy_honk_policyholder_feed
DROP CONSTRAINT pk_policy_honk_policyholder_feed;

ALTER TABLE edw_integration.policy_honk_policyholder_feed
ADD CONSTRAINT pk_policy_honk_policyholder_feed PRIMARY KEY (policy_number);