CREATE TABLE [edw_integration].[policy_current_carrier_auto_np01_feed](
	[RecordCode] [char](4) NULL,
	[ContribCompanyAMBestNumber] [char](5) NULL,
	[PolicyNumber] [char](20) NULL,
	[InsuranceType] [char](2) NULL,
	[ChangeEffectiveDate] [char](8) NULL,
	[ContribCompanyName] [char](20) NULL,
	[RiskType] [char](1) NULL,
	[PolicyType] [char](2) NULL,
	[NAICCode] [char](5) NULL,
	[PolicyInceptionDate] [char](8) NULL,
	[PolicyPeriodEndDate] [char](8) NULL,
	[PolicyPeriodBeginDate] [char](8) NULL,
	[PolicyCancellationDate] [char](8) NULL,
	[PolicyPremium] [char](7) NULL,
	[PremiumPaymentPlan] [char](1) NULL,
	[PremiumMethodPayment] [char](3) NULL,
	[Reserved1] [char](1) NULL,
	[PolicyHolderMailAddressHouseNum] [char](9) NULL,
	[PolicyHolderMailAddressStreetName] [char](20) NULL,
	[PolicyHolderMailAddressAptNum] [char](5) NULL,
	[PolicyHolderMailAddressCity] [char](20) NULL,
	[PolicyHolderMailAddressState] [char](2) NULL,
	[PolicyHolderMailAddressZip] [char](5) NULL,
	[PolicyHolderMailAddressZipPlus4] [char](4) NULL,
	[PolicyHolderTelephoneAreaCode] [char](3) NULL,
	[PolicyHolderTelephoneNumber] [char](7) NULL,
	[PolicyHolderTelephoneExtension] [char](4) NULL,
	[Reserved2] [char](10) NULL,
	[Reserved3] [char](3) NULL,
	[AgentIdentifier] [char](10) NULL,
	[PolicyState] [char](2) NULL,
	[policy_sk] Varchar(255) NULL,
	[policy_no] Varchar(255) NULL,
	[policy_history_sk] int  NULL,
	[transaction_seq_no] int NULL,
	[transaction_ts] DATETIME NULL,
	[create_ts] Datetime  NULL,
	[update_ts] Datetime NULL,
	[etl_audit_sk] int NULL

) 
GO

