CREATE TABLE [edw_integration].[policy_current_carrier_auto_vr01_feed](
	[RecordCode] [char](4) NULL,
	[ContribCompanyAMBestNumber] [char](5) NULL,
	[PolicyNumber] [char](20) NULL,
	[InsuranceType] [char](2) NULL,
	[ChangeEffectiveDate] [char](8) NULL,
	[VIN] [char](25) NULL,
	[VehicleRegisteredState] [char](2) NULL,
	[VehicleType] [char](2) NULL,
	[VehicleStatus] [char](1) NULL,
	[VehicleStatusDate] [char](8) NULL,
	[vehicleCancellationReason] [char](4) NULL,
	[NonCoverageReasonCode] [char](3) NULL,
	[LicensePlateNumber] [char](10) NULL,
	[StateTrackingNumber] [char](30) NULL,
	[Reserved1] [char](10) NULL,
	[VehicleAddDate] [char](8) NULL,
	[InsuredRegistrantSequenceNumber] [char](3) NULL,
	[VehicleMileage] [char](6) NULL,
	[ALIRtSActivityCode] [char](3) NULL,
	[TelematicsIndicator] [char](3) NULL,
	[TownshipCode] [char](3) NULL,
	[RegistrationPlateType] [char](3) NULL,
	[RegistrationPlateColor] [char](1) NULL,
	[RideShareIndicator] [char](1) NULL,
	[Reserved2] [char](99) NULL,
	[CellphoneNumberCountryCode] [char](3) NULL,
	[CellphoneAreaCode] [char](3) NULL,
	[CellphoneNumber] [char](7) NULL,
	[Filler1] [char](724) NULL,
	[policy_sk] Varchar(255) NULL,
	[policy_no] Varchar(255) NULL,
	[policy_history_sk] int  NULL,
	[auto_vehicle_coverage_sk] int  NULL,
	[auto_vehicle_sk] int  NULL,
	[vehicle_no] int  NULL,
	[transaction_seq_no] int NULL,
	[transaction_ts] DATETIME NULL,
	[create_ts] Datetime  NULL,
	[update_ts] Datetime NULL,
	[etl_audit_sk] int NULL

) 
GO

