IF NOT EXISTS
(SELECT 1 FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'edw_integration'
AND TABLE_name = 'customer_midterm_review_policy_detail')
BEGIN
create table edw_integration.customer_midterm_review_policy_detail
(
	policy_no varchar(255),
	original_policy_no varchar(255),
	risk_state_cd varchar(255),
	--policy_quote_in varchar(255),
	renewal_effective_date date,
	renewal_expiration_date date,
	--uw_company_cd varchar(255),
	product_nm varchar(255),
	customer_id varchar(255),
	customer_nm  varchar(255),
	customer_email varchar(255),
	customer_phone_no varchar(255),
	vip_in varchar(255),
	[mailing_address_line1] varchar(255),
	[mailing_address_line2] varchar(255),
	[mailing_address_unit_no] varchar(255),
	[mailing_address_city_nm] varchar(255),
	[mailing_address_state_cd] varchar(255),
	[mailing_address_zip_cd] varchar(255),
	broker_id varchar(255),
	broker_nm varchar(255),
	broker_phone_no varchar(255),
	broker_email varchar(255),
	dba_nm varchar(255),
	bdm_nm varchar(255),
	bdm_phone_no varchar(255),
	bdm_email varchar(255),
	new_business_underwriter_nm varchar(255),
	new_business_underwriter_email varchar(255),
	new_business_underwriter_phone_no varchar(255),
	renewal_underwriter_nm varchar(255),
	renewal_underwriter_email varchar(255),
	renewal_underwriter_phone_no varchar(255),
	risk_address_line1 varchar(255),
	risk_address_line2 varchar(255),
	risk_address_unit_no varchar(255),
	risk_address_city_nm varchar(255),
	risk_address_state_cd varchar(255),
	risk_address_zip_cd varchar(255),
	occupancy_type varchar(255),
	water_leak_detection_system varchar(255),
	renewal_premium_amt decimal(15,2),
	pel_limit_amt int,
	pel_location_ct int,
	pel_watercraft_ct int,
	pel_vehicle_ct int,
     total_insured_value_amt decimal(15,2),
     wildfire_protection_enrollment_in varchar(255),
     distance_to_coast varchar(255),
     distance_to_shore varchar(255),
     backup_generator_in varchar(255),
     total_collection_limit_amt int,
     no_of_years_with_vault int,
     no_of_years_with_vault_tx varchar(255) null,
	emergency_movement_coverage_in varchar(255),
     auto_vehicle_list varchar(max), 
     auto_vehicle_ct int,
	yatch_product_type varchar(255),
     yacht_boat_list varchar(max), 
     yacht_boat_ct int,
     monoline_home_in varchar(255),
     primary_home_monoline_in varchar(255),
     non_primary_home_monoline_in varchar(255),
     etl_audit_sk int not null,
	create_ts datetime2(7),
	update_ts datetime2(7),
	CONSTRAINT pk_customer_midterm_review_policy_detail PRIMARY KEY (policy_no, renewal_effective_date)
);
END;

delete from edw_core.tedw_table_detail
where table_nm = 'customer_midterm_review_policy_detail' ; 
INSERT INTO edw_core.tedw_table_detail(table_nm,table_type,table_category_nm,domain_nm,load_method,load_type,load_frequency,create_ts,update_ts,schema_nm) 
	VALUES ('','','Base','Common','Manual','Insert/Update','Static',getdate(),getdate(),'edw_integration');