IF NOT EXISTS
(SELECT 1 FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'edw_integration'
AND TABLE_name = 'customer_midterm_review_ghostdraft_feed')
BEGIN

    create table edw_integration.customer_midterm_review_ghostdraft_feed
	(
        customer_id varchar(255),
        midterm_review_year int,
		customer_nm  varchar(255),
		customer_email varchar(255),
		customer_phone_no varchar(255),
		product_nm varchar(255),
        existing_product_in varchar(255), 
        policy_no varchar(255),
        customer_message_id varchar(255),
        customer_message nvarchar(max), 
--		original_policy_no varchar(255),
--		risk_state_cd varchar(255),
--		policy_quote_in varchar(255),
--		renewal_effective_date date,
--		renewal_expiration_date date,
--		uw_company_cd varchar(255),
--		vip_in varchar(255),
		[mailing_address_line1] varchar(255),
		[mailing_address_line2] varchar(255),
		[mailing_address_unit_no] varchar(255),
		[mailing_address_city_nm] varchar(255),
		[mailing_address_state_cd] varchar(255),
		[mailing_address_zip_cd] varchar(255),
		broker_id varchar(255),
		broker_nm varchar(255),
		broker_phone_no varchar(255),
		broker_email varchar(255),
--		dba_nm varchar(255),
--		bdm_nm varchar(255),
--		bdm_phone_no varchar(255),
--		bdm_email varchar(255),
/*		
        new_business_underwriter_nm varchar(255),
		new_business_underwriter_email varchar(255),
		new_business_underwriter_phone_no varchar(255),
		renewal_underwriter_nm varchar(255),
		renewal_underwriter_email varchar(255),
		renewal_underwriter_phone_no varchar(255),
*/
		risk_address_line1 varchar(255),
		risk_address_line2 varchar(255),
		risk_address_unit_no varchar(255),
		risk_address_city_nm varchar(255),
		risk_address_state_cd varchar(255),
		risk_address_zip_cd varchar(255),
        risk_address nvarchar(max), 
		occupancy_type varchar(255),
        monoline_home_in varchar(255),
--		water_leak_detection_system varchar(255),
--		renewal_premium_amt decimal(15,2),
		pel_limit_amt int,
		pel_location_ct int,
		pel_watercraft_ct int,
		pel_vehicle_ct int,
        pel_message_id varchar(255),
        pel_message nvarchar(max),
--      total_insured_value_amt decimal(15,2),
        wildfire_protection_enrollment_in varchar(255),
--      distance_to_coast varchar(255),
--      distance_to_shore varchar(255),
        backup_generator_in varchar(255),
        total_collection_limit_amt int,
        collection_message_id varchar(255),
        collection_message nvarchar(max),
        lux_on_endorsement_message_id varchar(255),
        lux_on_endorsement_message nvarchar(max), 
        no_of_years_with_vault int,
        no_of_years_with_vault_tx varchar(255) null,
        auto_vehicle_list varchar(max), 
        auto_vehicle_ct int,
        auto_message_id varchar(255),
        auto_message nvarchar(max),
		yatch_product_type varchar(255),
        yacht_boat_list varchar(max), 
        yacht_boat_ct int,
        yacht_boat_message_id varchar(255),
        yacht_boat_message nvarchar(max),
        aviation_message_id varchar(255),
        aviation_message nvarchar(max),
		rms_recommendation varchar(255),
		wildfire_protection_recommendation varchar(255),
		backup_generator_recommendation varchar(255),
		rms_recommendation_message_1_id varchar(255),
        rms_recommendation_message_1 nvarchar(max),
        rms_recommendation_message_2_id varchar(255),
        rms_recommendation_message_2 nvarchar(max),
        wildfire_protection_recommendation_message_1_id varchar(255),
        wildfire_protection_recommendation_message_1 nvarchar(max),
        wildfire_protection_recommendation_message_2_id varchar(255),
        wildfire_protection_recommendation_message_2 nvarchar(max),
        backup_generator_recommendation_message_1_id varchar(255),
        backup_generator_recommendation_message_1 nvarchar(max), 
        new_driver_recommendation_message_1_id varchar(255),
        new_driver_recommendation_message_1 nvarchar(max),  
        primary_ho_monoline_recommendation_message_1_id varchar(255),
        primary_ho_monoline_recommendation_message_1 nvarchar(max),  
        non_primary_ho_monoline_recommendation_message_1_id varchar(255),
        non_primary_ho_monoline_recommendation_message_1 nvarchar(max),
        renovation_recommendation_message_1_id varchar(255),
        renovation_recommendation_message_1 nvarchar(max), 
        custom_recommendation_message_1_id varchar(255),
        custom_recommendation_message_1 nvarchar(max),
        custom_recommendation_message_2_id varchar(255),
        custom_recommendation_message_2 nvarchar(max),
        custom_recommendation_message_3_id varchar(255),
        custom_recommendation_message_3 nvarchar(max),
        custom_recommendation_message_4_id varchar(255),
        custom_recommendation_message_4 nvarchar(max),
--		product_recommendation varchar(255),
		etl_audit_sk int not null,
		create_ts datetime2(7),
		update_ts datetime2(7)
	);
END; 

IF EXISTS
(SELECT 1 FROM edw_integration.tintegration_table_detail
	where table_nm = 'customer_midterm_review_ghostdraft_feed')
BEGIN
	delete edw_integration.tintegration_table_detail
	where table_nm = 'customer_midterm_review_ghostdraft_feed' ; 
END ;  

INSERT INTO edw_integration.tintegration_table_detail(table_nm,table_type,table_desc,load_method,load_type,load_frequency,create_ts,update_ts) 
VALUES ('customer_midterm_review_ghostdraft_feed','Feed','This table holds customers ghostdraft feed data for midterm review','Stored Procedure','Full Load','Daily',getdate(),getdate());