IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES where TABLE_SCHEMA = 'edw_commercial'
AND TABLE_name = 'tcommercial_claim_transaction')
BEGIN
CREATE TABLE [edw_commercial].tcommercial_claim_transaction (
  commercial_claim_transaction_sk int NOT NULL IDENTITY(1,1),
  commercial_claim_sk int ,
  commercial_claim_feature_sk int ,
  product_sk int ,
  commercial_policy_sk int,
  broker_sk int,
  customer_sk int,
  transaction_dt_sk int ,
  transaction_ts datetime ,
  commercial_claim_payment_sk int ,
  claim_transaction_type_sk int ,
  feature_status_sk int ,
  loss_reserve_amt decimal (15, 2) NULL,
	expense_reserve_amt decimal (15, 2) NULL,
  subrogation_recovery_reserve_amt decimal (15, 2) NULL,
  salvage_recovery_reserve_amt decimal (15, 2) NULL,
  salvage_recovery_expense_reserve_amt decimal (15, 2) NULL,
  subrogation_recovery_expense_reserve_amt decimal (15, 2) NULL,
  loss_paid_amt decimal (15, 2) NULL,
  expense_paid_amt decimal (15, 2) NULL,
  subrogation_recovery_amt decimal (15, 2) NULL,
  salvage_recovery_amt decimal (15, 2) NULL,
  salvage_expense_recovery_amt decimal (15, 2) NULL,
  subrogation_expense_recovery_amt decimal (15, 2) NULL,
  claim_cost_category_sk int null,
  defense_reserve_amt decimal (15, 2) NULL,
  deductible_recovery_reserve_amt decimal (15, 2) NULL,
  reinsurance_recovery_reserve_amt  decimal (15, 2) NULL,
  overpayment_recovery_reserve_amt  decimal (15, 2) NULL,
  deductible_recovery_expense_reserve_amt decimal (15, 2) NULL ,
  reinsurance_recovery_expense_reserve_amt  decimal (15, 2) NULL,
  overpayment_recovery_expense_reserve_amt  decimal (15, 2) NULL,
  subrogation_recovery_defense_reserve_amt  decimal (15, 2) NULL,
  salvage_recovery_defense_reserve_amt  decimal (15, 2) NULL,
  deductible_recovery_defense_reserve_amt  decimal (15, 2) NULL,
  reinsurance_recovery_defense_reserve_amt  decimal (15, 2) NULL,
  overpayment_recovery_defense_reserve_amt  decimal (15, 2) NULL,
  defense_paid_amt  decimal (15, 2) NULL,
  deductible_recovery_amt  decimal (15, 2) NULL,
  reinsurance_recovery_amt  decimal (15, 2) NULL,
  overpayment_recovery_amt decimal (15, 2) NULL,
  deductible_expense_recovery_amt  decimal (15, 2) NULL,
  reinsurance_expense_recovery_amt  decimal (15, 2) NULL,
  overpayment_expense_recovery_amt  decimal (15, 2) NULL,
  subrogation_defense_recovery_amt  decimal (15, 2) NULL,
  salvage_defense_recovery_amt  decimal (15, 2) NULL,
  deductible_defense_recovery_amt  decimal (15, 2) NULL,
  reinsurance_defense_recovery_amt  decimal (15, 2) NULL,
  overpayment_defense_recovery_amt  decimal (15, 2) NULL,
  source_system_sk int ,
  create_ts datetime ,
  update_ts datetime ,
  etl_audit_sk  int,
  CONSTRAINT pk_tcommercial_claim_transaction PRIMARY KEY (commercial_claim_transaction_sk),
  CONSTRAINT fk_tcommercial_claim_transaction_claim_sk FOREIGN KEY (commercial_claim_sk) REFERENCES edw_commercial.tcommercial_claim(commercial_claim_sk),
  CONSTRAINT fk_tcommercial_claim_transaction_claim_feature_sk FOREIGN KEY (commercial_claim_feature_sk) REFERENCES  edw_commercial.tcommercial_claim_feature(commercial_claim_feature_sk),
  CONSTRAINT fk_tcommercial_claim_transaction_product_sk FOREIGN KEY (product_sk) REFERENCES  edw_core.tproduct(product_sk),
  CONSTRAINT fk_tcommercial_claim_transaction_transaction_dt_sk FOREIGN KEY (transaction_dt_sk) REFERENCES  edw_core.tdate(date_sk),
  CONSTRAINT fk_tcommercial_claim_transaction_claim_payment_sk FOREIGN KEY (commercial_claim_payment_sk) REFERENCES edw_commercial.tcommercial_claim_payment(commercial_claim_payment_sk),
  CONSTRAINT fk_tcommercial_claim_transaction_claim_transaction_type_sk FOREIGN KEY (claim_transaction_type_sk) REFERENCES  edw_core.tclaim_transaction_type(claim_transaction_type_sk),
  CONSTRAINT fk_tcommercial_claim_transaction_claim_feature_status_sk FOREIGN KEY (feature_status_sk) REFERENCES  edw_core.tclaim_status(claim_status_sk), 
  CONSTRAINT fk_tcommercial_claim_transaction_source_system_sk FOREIGN KEY (source_system_sk) REFERENCES  edw_core.tsource_system(source_system_sk),
  CONSTRAINT fk_tcommercial_claim_transaction_policy_sk FOREIGN KEY (commercial_policy_sk) REFERENCES  edw_commercial.tcommercial_policy(commercial_policy_sk),
  CONSTRAINT fk_tcommercial_claim_transaction_broker_sk FOREIGN KEY (broker_sk) REFERENCES  edw_core.tbroker(broker_sk),
  CONSTRAINT fk_tcommercial_claim_transaction_customer_sk FOREIGN KEY (customer_sk) REFERENCES  edw_core.tcustomer(customer_sk)
  )

INSERT [edw_core].[tedw_table_detail]([table_nm], [table_type], [table_category_nm], [domain_nm], 
[load_method], [load_type], [load_frequency], 
[create_ts], [update_ts], [schema_nm]) 
VALUES ( 'tcommercial_claim_transaction', 'Fact', 'Base', 'Claim', 'Stored Procedure', 'Insert', 'Daily',
GETDATE(), GETDATE(), 'edw_commercial')


INSERT [edw_core].[tedw_table_detail] ( [table_nm], [table_type], [table_category_nm], [domain_nm], [load_method], 
[load_type], [load_frequency], [create_ts], [update_ts], [schema_nm]) 
VALUES ('tcommercial_claim_payment', 'Type-1 Dimension', 'Base', 'Claim', 'Stored Procedure', 'Insert/Update', 'Daily', 
GETDATE(), GETDATE(), 'edw_commercial')

 END