IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES where TABLE_SCHEMA = 'edw_commercial'
and TABLE_name = 'tcommercial_claim_summary')
BEGIN
CREATE TABLE [edw_commercial].[tcommercial_claim_summary]
(
    [month_sk] [int] NOT NULL,
	[commercial_claim_sk] [int] NOT NULL,
	[product_sk] [int] NULL,
	[commercial_policy_sk] [int] NULL,
	[broker_sk] [int] NULL,
	[customer_sk] [int] NULL,
	[loss_reserve_amt] [decimal](15, 2) NULL,
	[itd_loss_reserve_amt] [decimal](15, 2) NULL,
	[expense_reserve_amt] [decimal](15, 2) NULL,
	[itd_expense_reserve_amt] [decimal](15, 2) NULL,
	[subrogation_recovery_reserve_amt] [decimal](15, 2) NULL,
	[itd_subrogation_recovery_reserve_amt] [decimal](15, 2) NULL,
	[salvage_recovery_reserve_amt] [decimal](15, 2) NULL,
	[itd_salvage_recovery_reserve_amt] [decimal](15, 2) NULL,
	[salvage_recovery_expense_reserve_amt] [decimal](15, 2) NULL,
	[itd_salvage_recovery_expense_reserve_amt] [decimal](15, 2) NULL,
	[subrogation_recovery_expense_reserve_amt] [decimal](15, 2) NULL,
	[itd_subrogation_recovery_expense_reserve_amt] [decimal](15, 2) NULL,
	[loss_paid_amt] [decimal](15, 2) NULL,
	[itd_loss_paid_amt] [decimal](15, 2) NULL,
	[expense_paid_amt] [decimal](15, 2) NULL,
	[itd_expense_paid_amt] [decimal](15, 2) NULL,
	[subrogation_recovery_amt] [decimal](15, 2) NULL,
	[itd_subrogation_recovery_amt] [decimal](15, 2) NULL,
	[salvage_recovery_amt] [decimal](15, 2) NULL,
	[itd_salvage_recovery_amt] [decimal](15, 2) NULL,
	[salvage_expense_recovery_amt] [decimal](15, 2) NULL,
	[itd_salvage_expense_recovery_amt] [decimal](15, 2) NULL,
	[subrogation_expense_recovery_amt] [decimal](15, 2) NULL,
	[itd_subrogation_expense_recovery_amt] [decimal](15, 2) NULL,
	[open_claim_ct] [int] NULL,
	[closed_claim_ct] [int] NULL,
	[claim_closed_with_pay_ct] [int] NULL,
	[claim_closed_without_pay_ct] [int] NULL,
	[itd_total_incurred_amt] [decimal](15, 2) NULL,
	[itd_total_paid_amt] [decimal](15, 2) NULL,
	[itd_total_reserve_amt] [decimal](15, 2) NULL,
	[itd_loss_incurred_gt_250k_ct] [int] NULL,
	[itd_loss_incurred_gt_500k_ct] [int] NULL,
	[source_system_sk] [int] NULL,
	[update_ts] [datetime] NULL,
	[etl_audit_sk] [int] NULL,
	[defense_reserve_amt] [decimal](15, 2) NULL,
	[itd_defense_reserve_amt] [decimal](15, 2) NULL,
	[deductible_recovery_reserve_amt] [decimal](15, 2) NULL,
	[itd_deductible_recovery_reserve_amt] [decimal](15, 2) NULL,
	[reinsurance_recovery_reserve_amt] [decimal](15, 2) NULL,
	[itd_reinsurance_recovery_reserve_amt] [decimal](15, 2) NULL,
	[overpayment_recovery_reserve_amt] [decimal](15, 2) NULL,
	[itd_overpayment_recovery_reserve_amt] [decimal](15, 2) NULL,
	[deductible_recovery_expense_reserve_amt] [decimal](15, 2) NULL,
	[itd_deductible_recovery_expense_reserve_amt] [decimal](15, 2) NULL,
	[reinsurance_recovery_expense_reserve_amt] [decimal](15, 2) NULL,
	[itd_reinsurance_recovery_expense_reserve_amt] [decimal](15, 2) NULL,
	[overpayment_recovery_expense_reserve_amt] [decimal](15, 2) NULL,
	[itd_overpayment_recovery_expense_reserve_amt] [decimal](15, 2) NULL,
	[subrogation_recovery_defense_reserve_amt] [decimal](15, 2) NULL,
	[itd_subrogation_recovery_defense_reserve_amt] [decimal](15, 2) NULL,
	[salvage_recovery_defense_reserve_amt] [decimal](15, 2) NULL,
	[itd_salvage_recovery_defense_reserve_amt] [decimal](15, 2) NULL,
	[deductible_recovery_defense_reserve_amt] [decimal](15, 2) NULL,
	[itd_deductible_recovery_defense_reserve_amt] [decimal](15, 2) NULL,
	[reinsurance_recovery_defense_reserve_amt] [decimal](15, 2) NULL,
	[itd_reinsurance_recovery_defense_reserve_amt] [decimal](15, 2) NULL,
	[overpayment_recovery_defense_reserve_amt] [decimal](15, 2) NULL,
	[itd_overpayment_recovery_defense_reserve_amt] [decimal](15, 2) NULL,
	[defense_paid_amt] [decimal](15, 2) NULL,
	[itd_defense_paid_amt] [decimal](15, 2) NULL,
	[deductible_recovery_amt] [decimal](15, 2) NULL,
	[itd_deductible_recovery_amt] [decimal](15, 2) NULL,
	[reinsurance_recovery_amt] [decimal](15, 2) NULL,
	[itd_reinsurance_recovery_amt] [decimal](15, 2) NULL,
	[overpayment_recovery_amt] [decimal](15, 2) NULL,
	[itd_overpayment_recovery_amt] [decimal](15, 2) NULL,
	[deductible_expense_recovery_amt] [decimal](15, 2) NULL,
	[itd_deductible_expense_recovery_amt] [decimal](15, 2) NULL,
	[reinsurance_expense_recovery_amt] [decimal](15, 2) NULL,
	[itd_reinsurance_expense_recovery_amt] [decimal](15, 2) NULL,
	[overpayment_expense_recovery_amt] [decimal](15, 2) NULL,
	[itd_overpayment_expense_recovery_amt] [decimal](15, 2) NULL,
	[subrogation_defense_recovery_amt] [decimal](15, 2) NULL,
	[itd_subrogation_defense_recovery_amt] [decimal](15, 2) NULL,
	[salvage_defense_recovery_amt] [decimal](15, 2) NULL,
	[itd_salvage_defense_recovery_amt] [decimal](15, 2) NULL,
	[deductible_defense_recovery_amt] [decimal](15, 2) NULL,
	[itd_deductible_defense_recovery_amt] [decimal](15, 2) NULL,
	[reinsurance_defense_recovery_amt] [decimal](15, 2) NULL,
	[itd_reinsurance_defense_recovery_amt] [decimal](15, 2) NULL,
	[overpayment_defense_recovery_amt] [decimal](15, 2) NULL,
	[itd_overpayment_defense_recovery_amt] [decimal](15, 2) NULL,
   CONSTRAINT pk_tcommercial_claim_summary PRIMARY KEY (month_sk,commercial_claim_sk),
    CONSTRAINT fk_tcommercial_claim_summary_broker_sk FOREIGN KEY (broker_sk) REFERENCES [edw_core].tbroker (broker_sk),
    CONSTRAINT fk_tcommercial_claim_summary_commercial_claim_sk FOREIGN KEY (commercial_claim_sk) REFERENCES  edw_commercial.tcommercial_claim(commercial_claim_sk),
    CONSTRAINT fk_tcommercial_claim_summary_customer_sk FOREIGN KEY (customer_sk) REFERENCES  edw_core.tcustomer (customer_sk),
    CONSTRAINT fk_tcommercial_claim_summary_month_sk FOREIGN KEY (month_sk) REFERENCES  edw_core.tdate(date_sk),
    CONSTRAINT fk_tcommercial_claim_summary_commercial_policy_sk FOREIGN KEY (commercial_policy_sk) REFERENCES  edw_commercial.tcommercial_policy(commercial_policy_sk),
    CONSTRAINT fk_tcommercial_claim_summary_product_sk FOREIGN KEY (product_sk) REFERENCES  edw_core.tproduct(product_sk),
    CONSTRAINT fk_tcommercial_claim_summary_source_system_sk FOREIGN KEY (source_system_sk) REFERENCES  edw_core.tsource_system(source_system_sk)
)
END

If not exists (
select * from edw_core.tedw_table_detail 
where table_nm='tcommercial_claim_summary'
)
begin
INSERT INTO edw_core.tedw_table_detail(table_nm,table_type,table_category_nm,domain_nm,load_method,load_type,load_frequency,create_ts,update_ts,schema_nm) 
    VALUES ('tcommercial_claim_summary','Fact','Datamart','Claim','Stored Procedure','Insert/Update','Daily',getdate(),getdate(),'edw_commercial')
end;