IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES 
               WHERE TABLE_SCHEMA = 'edw_stage' 
               AND TABLE_NAME = 'majesco_transaction_data_feed')
BEGIN

CREATE TABLE [edw_stage].[majesco_transaction_data_feed](
	[policy_no] [varchar](50) NULL,
	[account_no] [bigint] NULL,
	[system_activity_no] [varchar](50) NULL,
	[system_transaction_seq] [bigint] NULL,
	[date_time_created] [datetime] NULL,
	[underwriting_company] [varchar](50) NULL,
	[operating_company] [varchar](50) NULL,
	[account_code] [varchar](50) NULL,
	[policy_term_id] [bigint] NULL,
	[policy_inception_date] [datetime] NULL,
	[policy_effective_date] [datetime] NULL,
	[policy_expiration_date] [datetime] NULL,
	[product_code] [varchar](50) NULL,
	[line_of_business] [varchar](50) NULL,
	[subline_of_business] [varchar](50) NULL,
	[state_code] [varchar](10) NULL,
	[broker_system_code] [varchar](50) NULL,
	[broker_code] [varchar](50) NULL,
	[user_id] [varchar](100) NULL,
	[bill_type] [varchar](50) NULL,
	[transaction_type] [varchar](50) NULL,
	[payment_plan] [varchar](50) NULL,
	[system_remarks] [varchar](500) NULL,
	[user_remarks] [varchar](500) NULL,
	[commission_paid_basis] [varchar](50) NULL,
	[discount_plan_code] [varchar](50) NULL,
	[cancellation_date] [datetime] NULL,
	[cancellation_type] [varchar](50) NULL,
	[cancellation_method] [varchar](50) NULL,
	[cancellation_reason] [varchar](100) NULL,
	[policy_business_type] [varchar](50) NULL,
	[transaction_expiry_date] [datetime] NULL,
	[source_accounting_month] [int] NULL,
	[amount_spread_option] [varchar](50) NULL,
	[payment_method] [varchar](50) NULL,
	[suspend_code] [varchar](50) NULL,
	[suspend_flag] [char](1) NULL,
	[release_date] [datetime] NULL,
	[suspend_noc_code] [varchar](50) NULL,
	[suspend_noc_release_date] [datetime] NULL,
	[suspend_commission_type] [varchar](50) NULL,
	[amount_bill_option] [varchar](50) NULL,
	[transaction_eff_date] [datetime] NULL,
	[source_system_process_date] [datetime] NULL,
	[billing_accounting_month] [int] NULL,
	[writeoff_reason] [varchar](100) NULL,
	[recurring_eft_token_id] [varchar](100) NULL,
	[amount] [decimal](18, 2) NULL,
	[source_system_sk] [int] NULL,
	[create_ts] [datetime] NULL,
	[update_ts] [datetime] NULL,
	[etl_audit_sk] [int] NULL
) ON [PRIMARY]

end
