IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES 
               WHERE TABLE_SCHEMA = 'edw_stage' 
               AND TABLE_NAME = 'stage_majesco_transaction_data_feed')
BEGIN

CREATE TABLE [edw_stage].[stage_majesco_transaction_data_feed](
	[policy_no] [varchar](255) NULL,
	[account_no] [varchar](255) NULL,
	[system_activity_no] [varchar](255) NULL,
	[system_transaction_seq] [varchar](255) NULL,
	[date_time_created] [varchar](255) NULL,
	[underwriting_company] [varchar](255) NULL,
	[operating_company] [varchar](255) NULL,
	[account_code] [varchar](255) NULL,
	[policy_term_id] [varchar](255) NULL,
	[policy_inception_date] [varchar](255) NULL,
	[policy_effective_date] [varchar](255) NULL,
	[policy_expiration_date] [varchar](255) NULL,
	[product_code] [varchar](255) NULL,
	[line_of_business] [varchar](255) NULL,
	[subline_of_business] [varchar](255) NULL,
	[state_code] [varchar](255) NULL,
	[broker_system_code] [varchar](255) NULL,
	[broker_code] [varchar](255) NULL,
	[user_id] [varchar](255) NULL,
	[bill_type] [varchar](255) NULL,
	[transaction_type] [varchar](255) NULL,
	[payment_plan] [varchar](255) NULL,
	[system_remarks] [varchar](255) NULL,
	[user_remarks] [varchar](255) NULL,
	[commission_paid_basis] [varchar](255) NULL,
	[discount_plan_code] [varchar](255) NULL,
	[cancellation_date] [varchar](255) NULL,
	[cancellation_type] [varchar](255) NULL,
	[cancellation_method] [varchar](255) NULL,
	[cancellation_reason] [varchar](255) NULL,
	[policy_business_type] [varchar](255) NULL,
	[transaction_expiry_date] [varchar](255) NULL,
	[source_accounting_month] [varchar](255) NULL,
	[amount_spread_option] [varchar](255) NULL,
	[payment_method] [varchar](255) NULL,
	[suspend_code] [varchar](255) NULL,
	[suspend_flag] [varchar](255) NULL,
	[release_date] [varchar](255) NULL,
	[suspend_noc_code] [varchar](255) NULL,
	[suspend_noc_release_date] [varchar](255) NULL,
	[suspend_commission_type] [varchar](255) NULL,
	[amount_bill_option] [varchar](255) NULL,
	[transaction_eff_date] [varchar](255) NULL,
	[source_system_process_date] [varchar](255) NULL,
	[billing_accounting_month] [varchar](255) NULL,
	[writeoff_reason] [varchar](255) NULL,
	[recurring_eft_token_id] [varchar](255) NULL,
	[amount] [varchar](255) NULL,
	[start_date] [varchar](255) NULL,
	[end_date] [varchar](255) NULL,
	[create_ts] [datetime] NULL
) ON [PRIMARY]

end
