 IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES 
               WHERE TABLE_SCHEMA = 'edw_stage' 
               AND TABLE_NAME = 'tbroker_summary_v1')
BEGIN
CREATE TABLE vault_edw.edw_stage.tbroker_summary_v1 (
	month_sk int NOT NULL,
	broker_sk int NOT NULL,
	customer_sk int NOT NULL,
	product_sk int NOT NULL,
	state_sk int NOT NULL,
	uw_company_cd varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	prior_ytd_submission_ct int NULL,
	ytd_submission_ct int NOT NULL,
	prior_qtd_submission_ct int NULL,
	qtd_submission_ct int NOT NULL,
	prior_mtd_submission_ct int NULL,
	mtd_submission_ct int NOT NULL,
	prior_ytd_quote_net_premium_amt decimal(15,2) NULL,
	ytd_quote_net_premium_amt decimal(15,2) NULL,
	prior_qtd_quote_net_premium_amt decimal(15,2) NULL,
	qtd_quote_net_premium_amt decimal(15,2) NULL,
	prior_mtd_quote_net_premium_amt decimal(15,2) NULL,
	mtd_quote_net_premium_amt decimal(15,2) NULL,
	prior_ytd_quote_ct int NOT NULL,
	ytd_quote_ct int NOT NULL,
	prior_qtd_quote_ct int NOT NULL,
	qtd_quote_ct int NOT NULL,
	prior_mtd_quote_ct int NOT NULL,
	mtd_quote_ct int NOT NULL,
	last_quote_dt date NULL,
	last_bound_dt date NULL,
	prior_customer_ct int NOT NULL,
	customer_ct int NOT NULL,
	prior_total_line_ct int NOT NULL,
	total_line_ct int NOT NULL,
	prior_ytd_new_business_ct int NOT NULL,
	ytd_new_business_ct int NOT NULL,
	prior_qtd_new_business_ct int NOT NULL,
	qtd_new_business_ct int NOT NULL,
	prior_mtd_new_business_ct int NOT NULL,
	mtd_new_business_ct int NOT NULL,
	prior_ytd_new_business_net_premium_amt decimal(15,2) NOT NULL,
	ytd_new_business_net_premium_amt decimal(15,2) NOT NULL,
	prior_qtd_new_business_net_premium_amt decimal(15,2) NOT NULL,
	qtd_new_business_net_premium_amt decimal(15,2) NOT NULL,
	prior_mtd_new_business_net_premium_amt decimal(15,2) NOT NULL,
	mtd_new_business_net_premium_amt decimal(15,2) NOT NULL,
	prior_mtd_gross_new_business_net_premium_amt decimal(15,2) NOT NULL,
	mtd_gross_new_business_net_premium_amt decimal(15,2) NOT NULL,
	prior_mtd_written_premium_amt decimal(15,2) NOT NULL,
	mtd_written_premium_amt decimal(15,2) NOT NULL,
	prior_inforce_ct int NOT NULL,
	prior_inforce_net_premium_amt decimal(15,2) NOT NULL,
	inforce_ct int NOT NULL,
	inforce_net_premium_amt decimal(15,2) NOT NULL,
	one_year_claim_ct int NOT NULL,
	one_year_loss_incurred_amt decimal(15,2) NOT NULL,
	one_year_non_cat_claim_ct int NOT NULL,
	one_year_non_cat_loss_incurred_amt decimal(15,2) NOT NULL,
	one_year_earned_net_premium_amt decimal(15,4) NOT NULL,
	one_year_earned_exposure decimal(15,4) NOT NULL,
	one_year_loss_incurred_capped_amt decimal(15,2) NOT NULL,
	one_year_non_cat_loss_incurred_capped_amt decimal(15,2) NOT NULL,
	three_year_claim_ct int NOT NULL,
	three_year_loss_incurred_amt decimal(15,2) NOT NULL,
	three_year_non_cat_claim_ct int NOT NULL,
	three_year_non_cat_loss_incurred_amt decimal(15,2) NOT NULL,
	three_year_earned_net_premium_amt decimal(15,4) NOT NULL,
	three_year_earned_exposure decimal(15,4) NOT NULL,
	three_year_loss_incurred_capped_amt decimal(15,2) NOT NULL,
	three_year_non_cat_loss_incurred_capped_amt decimal(15,2) NOT NULL,
	policy_expiring_ct int NOT NULL,
	policy_renewal_ct int NOT NULL,
	policy_expiring_premium_amt decimal(15,2) NOT NULL,
	policy_renewal_premium_amt decimal(15,2) NOT NULL,
	update_ts datetime NULL,
	etl_audit_sk int NULL,
	one_year_written_premium_amt decimal(15,2) NULL,
	three_year_written_premium_amt decimal(15,2) NULL,
	one_year_non_cat_earned_net_premium_amt decimal(15,4) NULL,
	three_year_non_cat_earned_net_premium_amt decimal(15,4) NULL,
	one_year_loss_ratio decimal(15,2) NULL,
	one_year_loss_ratio_capped decimal(15,2) NULL,
	one_year_non_cat_loss_ratio decimal(15,2) NULL,
	one_year_non_cat_loss_ratio_capped decimal(15,2) NULL,
	one_year_frequency decimal(15,2) NULL,
	one_year_non_cat_frequency decimal(15,2) NULL,
	one_year_severity decimal(15,2) NULL,
	one_year_non_cat_severity decimal(15,2) NULL,
	three_year_loss_ratio decimal(15,2) NULL,
	three_year_loss_ratio_capped decimal(15,2) NULL,
	three_year_non_cat_loss_ratio decimal(15,2) NULL,
	three_year_non_cat_loss_ratio_capped decimal(15,2) NULL,
	three_year_frequency decimal(15,2) NULL,
	three_year_non_cat_frequency decimal(15,2) NULL,
	three_year_severity decimal(15,2) NULL,
	three_year_non_cat_severity decimal(15,2) NULL,
	policy_renewal_offered_ct int NULL,
	policy_renewal_offered_premiumm_amt decimal(10,2) NULL,
	policy_renewal_offered_expiring_premium_amt decimal(10,2) NULL,
	prior_mtd_net_premium_amt decimal(15,2) NULL,
	mtd_net_premium_amt decimal(15,2) NULL,
	open_submission_ct int NULL,
	last30_days_submission_ct int NULL,
	policy_renewal_offered_over_50k_ct int NULL,
	two_year_claim_ct int NULL,
	two_year_loss_incurred_amt decimal(15,2) NULL,
	two_year_non_cat_claim_ct int NULL,
	two_year_non_cat_loss_incurred_amt decimal(15,2) NULL,
	two_year_earned_net_premium_amt decimal(15,4) NULL,
	two_year_non_cat_earned_net_premium_amt decimal(15,4) NULL,
	five_year_claim_ct int NULL,
	five_year_loss_incurred_amt decimal(15,2) NULL,
	five_year_non_cat_claim_ct int NULL,
	five_year_non_cat_loss_incurred_amt decimal(15,2) NULL,
	five_year_earned_net_premium_amt decimal(15,4) NULL,
	five_year_non_cat_earned_net_premium_amt decimal(15,4) NULL,
	prior_ytd_bind_ct int NULL,
	ytd_bind_ct int NULL,
	prior_qtd_bind_ct int NULL,
	qtd_bind_ct int NULL,
	prior_mtd_bind_ct int NULL,
	mtd_bind_ct int NULL,
	ytd_policy_expiring_ct int NULL,
	ytd_policy_renewal_ct int NULL,
	ytd_policy_renewal_offered_ct int NULL,
	ytd_policy_renewal_offered_over_50k_ct int NULL,
	ytd_policy_renewal_offered_premiumm_amt decimal(10,2) NULL,
	ytd_policy_renewal_offered_expiring_premium_amt decimal(10,2) NULL,
	ytd_policy_expiring_premium_amt decimal(10,2) NULL,
	ytd_policy_renewal_premium_amt decimal(10,2) NULL,
	policy_renewal_accepted_ct int NULL,
	ytd_policy_renewal_accepted_ct int NULL,
	prior_ytd_new_business_dwelling_limit_amt int NULL,
	prior_ytd_new_business_tiv_amt int NULL,
	prior_qtd_new_business_dwelling_limit_amt int NULL,
	prior_qtd_new_business_tiv_amt int NULL,
	prior_mtd_new_business_dwelling_limit_amt int NULL,
	prior_mtd_new_business_tiv_amt int NULL,
	ytd_new_business_dwelling_limit_amt int NULL,
	ytd_new_business_tiv_amt int NULL,
	qtd_new_business_dwelling_limit_amt int NULL,
	qtd_new_business_tiv_amt int NULL,
	mtd_new_business_dwelling_limit_amt int NULL,
	mtd_new_business_tiv_amt int NULL,
	prior_ytd_quote_dwelling_limit_amt int NULL,
	prior_ytd_quote_tiv_amt int NULL,
	prior_qtd_quote_dwelling_limit_amt int NULL,
	prior_qtd_quote_tiv_amt int NULL,
	prior_mtd_quote_dwelling_limit_amt int NULL,
	prior_mtd_quote_tiv_amt int NULL,
	ytd_quote_dwelling_limit_amt int NULL,
	ytd_quote_tiv_amt int NULL,
	qtd_quote_dwelling_limit_amt int NULL,
	qtd_quote_tiv_amt int NULL,
	mtd_quote_dwelling_limit_amt int NULL,
	mtd_quote_tiv_amt int NULL,
	inforce_dwelling_limit_amt int NULL,
	inforce_tiv_amt int NULL,
	mtd_mid_term_cancellation_ct int NULL,
	mtd_mid_term_cancellation_home_sold_ct int NULL,
	mtd_mid_term_cancellation_coverage_replaced_ct int NULL,
	mtd_mid_term_cancellation_non_pay_ct int NULL,
	non_flat_cancelled_ct int NULL,
	expiring_sixty_day_written_premium_amt decimal(15,2) NULL,
	mtd_earned_premium_amt decimal(15,4) NULL,
	mtd_earned_net_premium_amt decimal(15,4) NULL,
	mtd_written_net_premium_amt decimal(15,2) NULL,
	mtd_claim_ct int NULL,
	mtd_loss_incurred_amt decimal(15,2) NULL,
	mtd_loss_incurred_capped_amt decimal(15,2) NULL,
	mtd_non_cat_claim_ct int NULL,
	mtd_non_cat_loss_incurred_amt decimal(15,2) NULL,
	mtd_non_cat_loss_incurred_capped_amt decimal(15,2) NULL,
	prior_mtd_claim_ct int NULL,
	prior_mtd_loss_incurred_amt decimal(15,2) NULL,
	prior_mtd_loss_incurred_capped_amt decimal(15,2) NULL,
	prior_mtd_non_cat_claim_ct int NULL,
	prior_mtd_non_cat_loss_incurred_amt decimal(15,2) NULL,
	prior_mtd_non_cat_loss_incurred_capped_amt decimal(15,2) NULL,
	prior_mtd_earned_premium_amt decimal(15,4) NULL,
	prior_mtd_earned_net_premium_amt decimal(15,4) NULL,
	CONSTRAINT pk_tbroker_summary_v1 PRIMARY KEY (month_sk,broker_sk,customer_sk,product_sk,state_sk,uw_company_cd)
);
 CREATE NONCLUSTERED INDEX IX_tbroker_summary_v1_month_sk ON edw_stage.tbroker_summary_v1 (  month_sk ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;


-- vault_edw.edw_stage.tbroker_summary_v1 foreign keys

ALTER TABLE vault_edw.edw_stage.tbroker_summary_v1 ADD CONSTRAINT fk_tbs_tbroker_broker_sk FOREIGN KEY (broker_sk) REFERENCES vault_edw.edw_core.tbroker(broker_sk);
ALTER TABLE vault_edw.edw_stage.tbroker_summary_v1 ADD CONSTRAINT fk_tbs_tcustomer_customer_sk FOREIGN KEY (customer_sk) REFERENCES vault_edw.edw_core.tcustomer(customer_sk);
ALTER TABLE vault_edw.edw_stage.tbroker_summary_v1 ADD CONSTRAINT fk_tbs_tproduct_product_sk FOREIGN KEY (product_sk) REFERENCES vault_edw.edw_core.tproduct(product_sk);
ALTER TABLE vault_edw.edw_stage.tbroker_summary_v1 ADD CONSTRAINT fk_tbs_tstate_state_sk FOREIGN KEY (state_sk) REFERENCES vault_edw.edw_core.tstate(state_sk);
END