IF NOT EXISTS (
SELECT 1
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA='edw_core'
AND TABLE_NAME = 'tquote'
AND COLUMN_NAME = 'risk_address_line_1'
) 
BEGIN 
	ALTER TABLE edw_core.tquote ADD risk_address_line_1 VARCHAR(255) NULL
END; 

IF NOT EXISTS (
SELECT 1
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA='edw_core'
AND TABLE_NAME = 'tquote'
AND COLUMN_NAME = 'risk_address_line_2'
) 
BEGIN 
	ALTER TABLE edw_core.tquote ADD risk_address_line_2 VARCHAR(255) NULL
END;

IF NOT EXISTS (
SELECT 1
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA='edw_core'
AND TABLE_NAME = 'tquote'
AND COLUMN_NAME = 'risk_address_unit_no'
) 
BEGIN 
	ALTER TABLE edw_core.tquote ADD risk_address_unit_no VARCHAR(255) NULL
END;

IF NOT EXISTS (
SELECT 1
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA='edw_core'
AND TABLE_NAME = 'tquote'
AND COLUMN_NAME = 'risk_address_city_nm'
) 
BEGIN 
	ALTER TABLE edw_core.tquote ADD risk_address_city_nm VARCHAR(255) NULL
END; 

IF NOT EXISTS (
SELECT 1
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA='edw_core'
AND TABLE_NAME = 'tquote'
AND COLUMN_NAME = 'risk_address_state_cd'
) 
BEGIN 
	ALTER TABLE edw_core.tquote ADD risk_address_state_cd VARCHAR(255) NULL
END;

IF NOT EXISTS (
SELECT 1
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA='edw_core'
AND TABLE_NAME = 'tquote'
AND COLUMN_NAME = 'risk_address_zip_cd'
) 
BEGIN 
	ALTER TABLE edw_core.tquote ADD risk_address_zip_cd VARCHAR(255) NULL
END;

IF NOT EXISTS (
SELECT 1
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA='edw_core'
AND TABLE_NAME = 'tquote'
AND COLUMN_NAME = 'risk_address_country_nm'
) 
BEGIN 
	ALTER TABLE edw_core.tquote ADD risk_address_country_nm VARCHAR(255) NULL
END;